"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '            f"- Current decision: **{decision}**",\n',
    '        ])\n',
    '    elif intent == "regime_explanation":\n',
    '        lines.extend([\n',
    '            f"- Major regime: **{major}**",\n',
    '            f"- Alpha: **{alpha}**",\n',
    '            f"- Delta: **{delta}**",\n',
    '            f"- Transition probability: **{first(regime.get(\'transition_probability_1h\'), regime.get(\'transition_probability\'))}**",\n',
    '            f"- Regime reliability: **{pct(first(regime.get(\'reliability\'), reliability.get(\'regime_reliability\'), confidence))}**",\n',
    '            f"- Direction under this regime: **{direction}**",\n',
    '        ])\n',
    '    elif intent == "reliability_explanation":\n',
    '        lines.extend([\n',
    '            f"- Evidence-calibrated confidence: **{pct(confidence)}**",\n',
    '            f"- Uncertainty: **{pct(first(uncertainty.get(\'uncertainty_pct\'), uncertainty.get(\'uncertainty\')))}**",\n',
    '            f"- Error estimate: **{pct(first(uncertainty.get(\'error_pct\'), validation.get(\'error_pct\'), validation.get(\'mean_absolute_error_pct\')))}**",\n',
    '            f"- Conflict status: **{conflict}**",\n',
    '            f"- Data freshness: **{first(validation.get(\'data_freshness\'), validation.get(\'stale_status\'), default=\'UNKNOWN\')}**",\n',
    '            f"- Less-risky action: **{less_risky}**",\n',
    '        ])\n',
    '    elif intent == "similar_day":\n',
    '        lines.extend([\n',
    '            f"- Similar-day status: **{first(similar.get(\'status\'))}**",\n',
    '            f"- Best historical match: **{first(similar.get(\'best_match\'), similar.get(\'matched_date\'))}**",\n',
    '            f"- Similarity score: **{first(similar.get(\'similarity_score\'), similar.get(\'score\'))}**",\n',
    '            f"- Historical outcome: **{first(similar.get(\'outcome\'), similar.get(\'forward_return\'))}**",\n',
    '            f"- Reliability: **{pct(first(similar.get(\'reliability\'), confidence))}**",\n',
    '        ])\n',
    '    elif intent == "historical_comparison":\n',
    '        history = canonical.get("history_summary") if isinstance(canonical.get("history_summary"), Mapping) else {}\n',
    '        lines.extend([\n',
    '            f"- Current decision: **{decision}**",\n',
    '            f"- Current regime: **{major}**",\n',
    '            f"- 25-day direction accuracy: **{pct(first(history.get(\'direction_accuracy_pct\'), summary.get(\'direction_accuracy_pct\')))}**",\n',
    '            f"- Historical reliability: **{pct(first(history.get(\'reliability\'), confidence))}**",\n',
    '            f"- Latest completed H1: **{latest}**",\n',
    '        ])\n',
    '    elif intent == "system_health":\n',
    '        try:\n',
    '            from core.market_time_freshness_20260622 import market_time_snapshot\n',
    '            clock = market_time_snapshot(st.session_state, query_mt5=False)\n',
    '        except Exception:\n',
    '            clock = {}\n',
    '        lines.extend([\n',
    '            f"- Generation ID: **{first(pack.get(\'calculation_id\'), canonical.get(\'run_id\'))}**",\n',
    '            f"- Calculation status: **{first(canonical.get(\'calculation_status\'), validation.get(\'status\'), default=\'UNKNOWN\')}**",\n',
    '            f"- Feed freshness: **{first(clock.get(\'status\'), validation.get(\'data_freshness\'), default=\'UNKNOWN\')}**",\n',
    '            f"- Source / rows: **{clock.get(\'source\') or canonical.get(\'source\') or \'UNKNOWN\'} / {clock.get(\'rows\', \'not available\')}**",\n',
    '            f"- Latest completed H1: **{latest}**",\n',
    '            f"- Validation warning: **{first(validation.get(\'warning\'), validation.get(\'failure_reason\'), default=\'None published\')}**",\n',
    '        ])\n',
    '    else:\n',
    '        lines.extend([\n',
    '            f"- Current decision: **{decision}**",\n',
    '            f"- Directional market view: **{direction}**",\n',
    '            f"- Less-risky action: **{less_risky}**",\n',
    '            f"- Current regime: **{major}**",\n',
    '            f"- Confidence: **{pct(confidence)}**",\n',
    '            f"- Conflict status: **{conflict}**",\n',
    '        ])\n',
    '\n',
    '    if reasons and intent in {"decision_explanation", "regime_explanation", "reliability_explanation", "tp_sl_guidance"}:\n',
    '        lines.append("\\n**Why:**")\n',
    '        lines.extend(f"- {reason}" for reason in reasons[:4])\n',
    '\n',
    '    if score <= 0:\n',
    '        lines.append("\\nThis local assistant did not detect a narrow category, so it answered from the closest published decision evidence. Ask about broker time, TP/SL, forecast, regime, reliability, priority, history, or system health for a more targeted answer.")\n',
    '    try:\n',
    '        from core.shared_broker_time_20260622 import shared_broker_time_provider\n',
    '        timestamp_used = shared_broker_time_provider(st.session_state, canonical=canonical).get("shared_broker_time_display")\n',
    '    except Exception:\n',
    '        timestamp_used = latest\n',
    '    relevant_sources = {\n',
    '        "entry_guidance": "Entry, Reliability, Priority, Regime",\n',
    '        "exit_guidance": "Exit Risk, Hold, Projection, Reliability",\n',
    '        "tp_sl_guidance": "Projection, Risk, Decision",\n',
    '        "price_forecast": "Forecast, Projection, Reliability",\n',
    '        "regime_explanation": "Regime, Reliability, History",\n',
    '        "reliability_explanation": "Reliability, Uncertainty, Validation",\n',
    '        "priority_ranking": "Priority, Decision, Regime",\n',
    '        "historical_comparison": "History, Decision, Regime",\n',
    '        "market_time": "Shared Broker Time, Connector Freshness",\n',
    '    }.get(intent, "Decision, Regime, Reliability")\n',
    '    lines.extend([\n',
    '        "", "---",\n',
    '        f"**Confidence %:** {pct(confidence)}",\n',
    '        f"**Data Sources Used:** {relevant_sources}",\n',
    '        f"**Timestamp Used:** {timestamp_used}",\n',
    '        f"**Current Regime:** {major}",\n',
    '        f"**Current Reliability:** {pct(first(regime.get(\'reliability\'), confidence))}",\n',
    '        f"**Current Priority:** {first(priority.get(\'label\'), priority.get(\'priority_label\'), priority.get(\'rank\'))}",\n',
    '        f"**Reasoning Summary:** Classified as {intent.replace(\'_\', \' \')} and restricted to the relevant published modules.",\n',
    '        "\\nRead-only answer from the current canonical generation; no protected calculation, external API, or heavy model was run.",\n',
    '    ])\n',
    '    return {\n',
    '        "answer": "\\n".join(lines),\n',
    '        "status": f"LOCAL_FOCUSED_{intent.upper()}",\n',
    '        "intent": intent,\n',
    '        "generation_id": str(pack.get("calculation_id") or canonical.get("run_id") or "current"),\n',
    '        "evidence": [f"intent:{intent}", "canonical", "compact_summary", "fact_pack"],\n',
    '    }\n',
    '\n',
    '\n',
    'def render_compact_ai_assistant() -> None:\n',
    '    pack = get_ai_fact_pack(st.session_state) or _recover_fact_pack(st.session_state)\n',
    '    try:\n',
    '        from core.canonical_sync_v9 import read_snapshot_for_lunch\n',
    '        v9 = read_snapshot_for_lunch(st.session_state)\n',
    '    except Exception:\n',
    '        v9 = None\n',
    '    if v9 is not None:\n',
    '        pack = {**dict(pack or {}), **{\n',
    '            "calculation_id": v9.run_id, "generation": st.session_state.get("canonical_calculation_generation_20260617", 0),\n',
    '            "Broker Time": v9.broker_time, "latest_completed_h1": v9.candle_time,\n',
    '            "current decision": v9.decision, "direction": v9.direction,\n',
    '            "directional_regime": v9.regime, "priority_score": v9.priority_score,\n',
    '            "priority_label": v9.priority_label, "reliability_score": v9.reliability_score,\n',
    '            "data_quality_score": v9.data_quality_score, "snapshot_hash": v9.snapshot_hash,\n',
    '        }}\n',
    '        context_cols = st.columns(2)\n',
    '        context_cols[0].metric("AI context run_id", v9.run_id[:24])\n',
    '        context_cols[1].metric("AI context broker_time", v9.broker_time)\n',
    '        st.caption(f"AI context snapshot_hash: {v9.snapshot_hash}. Answers are read-only and use this canonical snapshot/history.")\n',
    '    st.caption("Reads the compact canonical fact pack. No analysis or history query runs until Send is pressed.")\n',
    '    if not pack:\n',
    '        # Last-resort recovery from a completed canonical generation. This does\n',
    '        # not calculate; it only republishes the compact AI projection.\n',
    '        pack = _recover_fact_pack(st.session_state)\n',
    '    if not pack:\n',
    '        pack = _offline_fact_pack(st.session_state)\n',
    '        st.warning("No completed canonical generation is available, so the assistant is in safe offline diagnostic mode. The chat remains active and does not fabricate trading values.")\n',
    '    elif bool(st.session_state.get("ai_fact_pack_recovered_from_disk_20260622") or st.session_state.get("ai_canonical_runtime_recovered_20260622")):\n',
    '        st.success("AI Assistant restored the newest valid published generation. A failed refresh or disconnected API did not disable the assistant.")\n',
    '    # Extend with the canonical generation-bound fact pack when available.\n',
    '    try:\n',
    '        from core.lunch_broker_sentiment_ai_history_20260622 import build_ai_fact_pack, market_time_contract, get_canonical_generation\n',
    '        extended_pack = build_ai_fact_pack(st.session_state)\n',
    '        if isinstance(extended_pack, Mapping) and not pack.get("offline_diagnostic"):\n',
    '            pack = {**dict(pack), **dict(extended_pack)}\n',
    '        contract = market_time_contract(st.session_state, get_canonical_generation(st.session_state))\n',
    '        st.info(f"AI uses calculation {contract.get(\'calculation_id\')} generation {contract.get(\'calculation_generation\')} at {contract.get(\'broker_time_display\')}. It is read-only and will not rerun calculation.")\n',
    '        with st.expander("Evidence panel — canonical fields used", expanded=False):\n',
    '            st.json({k: pack.get(k) for k in ["calculation_id", "generation", "latest_completed_h1_utc", "Broker Time", "Myanmar Time", "current decision", "less-risky decision", "direction", "data-quality status", "synchronization status"] if k in pack})\n',
    '    except Exception:\n',
    '        pass\n',
    '    calc_id = str(pack.get("calculation_id") or "OFFLINE-DIAGNOSTIC")\n',
    '    generation = pack.get("generation", pack.get("calculation_generation", 0))\n',
    '    broker_contract = {\n',
    '        "broker_offset_minutes": pack.get("broker_offset_minutes"),\n',
    '        "broker_timezone_iana": pack.get("broker_timezone_iana"),\n',
    '        "contract_version": pack.get("contract_version"),\n',
    '        "latest_completed_h1_utc": pack.get("latest_completed_h1_utc", pack.get("latest_completed_h1")),\n',
    '    }\n',
    '    phone = bool(st.session_state.get("phone_mode", False))\n',
    '    messages = st.session_state.get(LATEST_KEY)\n',
    '    if (not isinstance(messages, list)\n',
    '            or str(st.session_state.get(LATEST_CALC_KEY) or "") != calc_id\n',
    '            or str(st.session_state.get(LATEST_GENERATION_KEY) or "") != str(generation)):\n',
    '        messages = [] if pack.get("offline_diagnostic") else load_ai_messages(calc_id, limit=6 if phone else 20)\n',
    '        st.session_state[LATEST_KEY] = messages\n',
    '        st.session_state[LATEST_CALC_KEY] = calc_id\n',
    '        st.session_state[LATEST_GENERATION_KEY] = generation\n',
    '    shown = messages[-6:] if phone else messages[-20:]\n',
    '    for item in shown:\n',
    '        role = str(item.get("role", "assistant"))\n',
    '        with st.chat_message(role if role in {"user", "assistant"} else "assistant"):\n',
    '            st.markdown(str(item.get("content", "")))\n',
    '\n',
    '    with st.form("compact_ai_form_20260619", clear_on_submit=True):\n',
    '        mode = st.selectbox("Resource route", ["Automatic bounded route", "Simple evidence route", "Complex evidence route"], key="ai_mode_20260619")\n',
    '        question = st.text_input("Ask about the synchronized EURUSD H1 result", key="ai_question_20260619")\n',
    '        submitted = st.form_submit_button("Send / Analyze", use_container_width=True)\n',
    '    if not submitted or not question.strip():\n',
    '        return\n',
    '\n',
    '    key = answer_cache_key(calc_id, question, mode, generation, broker_contract)\n',
    '    cache = _bounded_cache()\n',
    '    cached = cache.get(key)\n',
    '    from_cache = isinstance(cached, Mapping)\n',
    '    if from_cache:\n',
    '        result = dict(cached)\n',
    '        answer = str(result.get("answer") or "")\n',
    '    else:\n',
    '        if pack.get("offline_diagnostic"):\n',
    '            result = _offline_answer(question, pack)\n',
    '        else:\n',
    '            from core.canonical_runtime_20260617 import get_canonical\n',
    '            from core.compact_canonical_20260619 import get_compact_summary\n',
    '            from core.ai_grounded_pipeline_20260621 import answer_question\n',
    '            canonical = get_canonical(st.session_state)\n',
    '            summary = get_compact_summary(st.session_state)\n',
    '            plan = st.session_state.get("position_sizing_plan_20260619") or {}\n',
    '            # Dynamic evidence pipeline is the primary route.  The older focused\n',
    '            # formatter remains only as a safe fallback if retrieval fails.\n',
    '            try:\n',
    '                result = answer_question(question, canonical=canonical, summary=summary, plan=plan, state=st.session_state)\n',
    '            except Exception:\n',
    '                result = _real_related_local_answer(question, canonical if isinstance(canonical, Mapping) else {}, summary if isinstance(summary, Mapping) else {}, pack)\n',
    '        answer = str(result.get("answer") or "")\n',
    '        # Reject an answer produced for a replaced generation, except the safe\n',
    '        # diagnostic context which has no mutable market generation.\n',
    '        current_pack = _recover_fact_pack(st.session_state)\n',
    '        current_generation = current_pack.get("generation", current_pack.get("calculation_generation", 0))\n',
    '        if (not pack.get("offline_diagnostic") and (\n',
    '                str(current_pack.get("calculation_id") or "") != calc_id\n',
    '                or str(current_generation) != str(generation))):\n',
    '            st.warning("A newer calculation replaced this request. The stale generation answer was discarded.")\n',
    '            return\n',
    '        cache[key] = result\n',
    '        cache.move_to_end(key)\n',
    '        while len(cache) > MAX_CACHE:\n',
    '            cache.popitem(last=False)\n',
    '        st.session_state[CACHE_KEY] = cache\n',
    '\n',
    '    # Cached answers are checked against the last 20 pairs and restructured when\n',
    '    # similarity exceeds 90%.  Fresh pipeline answers already passed this guard.\n',
    '    if from_cache or not bool(result.get("memory_recorded")):\n',
    '        try:\n',
    '            from core.ai_duplicate_guard_20260622 import prevent_duplicate_answer\n',
    '            from core.ai_conversation_memory import remember\n',
    '            evidence_rows = result.get("evidence") if isinstance(result.get("evidence"), list) else []\n',
    '            guarded = prevent_duplicate_answer(\n',
    '                st.session_state, question=question, answer=answer,\n',
    '                intent=str(result.get("intent") or "decision_explanation"), evidence=evidence_rows,\n',
    '            )\n',
    '            answer = str(guarded.get("answer") or answer)\n',
    '            result["answer"] = answer\n',
    '            result["duplicate_guard"] = guarded\n',
    '            remember(\n',
    '                st.session_state, question=question,\n',
    '                intent=str(result.get("intent") or "decision_explanation"),\n',
    '                generation_id=str(result.get("generation_id") or calc_id),\n',
    '                evidence=evidence_rows, status=str(result.get("status") or mode), answer=answer,\n',
    '            )\n',
    '            result["memory_recorded"] = True\n',
    '        except Exception:\n',
    '            pass\n',
    '    pair = [{"role": "user", "content": question}, {"role": "assistant", "content": str(answer)}]\n',
    '    messages.extend(pair)\n',
    '    st.session_state[LATEST_KEY] = messages[-20:]\n',
    '    if not pack.get("offline_diagnostic"):\n',
    '        for item in pair:\n',
    '            append_ai_message(calc_id, item["role"], item["content"])\n',
    '        _append_ai_history(calc_id, question, str(answer), str(result.get("status") or mode), pack)\n',
    '    with st.chat_message("assistant"):\n',
    '        st.markdown(str(answer))\n',
    '\n',
    '\n',
    '__all__ = ["render_compact_ai_assistant", "answer_cache_key", "_recover_fact_pack", "MAX_CACHE", "AI_ANSWER_VERSION"]\n',
]
