"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Causal deterministic calibration for the existing PowerBI projection paths.\n',
    '\n',
    'This module does not train a model and does not replace raw red/yellow/blue\n',
    'outputs.  It calibrates each existing path and horizon from completed historical\n',
    'prediction outcomes only, creates bounded reliability weights, and derives\n',
    'residual-quantile bands.  Every market feature is trailing/causal.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from typing import Any, Dict, Iterable, Mapping, Optional, Sequence\n',
    'import math\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'CALIBRATION_VERSION = "powerbi-path-calibration-20260618-v2"\n',
    'PATHS = ("red", "yellow", "blue")\n',
    '\n',
    '\n',
    'def _finite(value: Any, default: float = 0.0) -> float:\n',
    '    try:\n',
    '        number = float(value)\n',
    '        return number if math.isfinite(number) else float(default)\n',
    '    except Exception:\n',
    '        return float(default)\n',
    '\n',
    '\n',
    'def _clip(value: Any, low: float, high: float) -> float:\n',
    '    return float(max(low, min(high, _finite(value, low))))\n',
    '\n',
    '\n',
    'def _find_col(frame: pd.DataFrame, aliases: Iterable[str]) -> Optional[str]:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return None\n',
    '    norm = {str(c).strip().lower().replace("_", " "): c for c in frame.columns}\n',
    '    for alias in aliases:\n',
    '        key = str(alias).strip().lower().replace("_", " ")\n',
    '        if key in norm:\n',
    '            return norm[key]\n',
    '    for alias in aliases:\n',
    '        key = str(alias).strip().lower().replace("_", " ")\n',
    '        for n, c in norm.items():\n',
    '            if key and key in n:\n',
    '                return c\n',
    '    return None\n',
    '\n',
    '\n',
    'def _prepare_market(data: pd.DataFrame) -> pd.DataFrame:\n',
    '    if not isinstance(data, pd.DataFrame) or data.empty:\n',
    '        return pd.DataFrame()\n',
    '    t = _find_col(data, ("time", "datetime", "timestamp", "date")); c = _find_col(data, ("close", "c"))\n',
    '    if t is None or c is None:\n',
    '        return pd.DataFrame()\n',
    '    o = _find_col(data, ("open", "o")); h = _find_col(data, ("high", "h")); l = _find_col(data, ("low", "l"))\n',
    '    out = pd.DataFrame({"time": pd.to_datetime(data[t], errors="coerce"), "close": pd.to_numeric(data[c], errors="coerce")})\n',
    '    out["open"] = pd.to_numeric(data[o], errors="coerce") if o else out["close"]\n',
    '    out["high"] = pd.to_numeric(data[h], errors="coerce") if h else out[["open", "close"]].max(axis=1)\n',
    '    out["low"] = pd.to_numeric(data[l], errors="coerce") if l else out[["open", "close"]].min(axis=1)\n',
    '    out = out.dropna(subset=["time", "close"]).sort_values("time").drop_duplicates("time", keep="last").reset_index(drop=True)\n',
    '    if out.empty:\n',
    '        return out\n',
    '    out["high"] = out[["open", "high", "close"]].max(axis=1)\n',
    '    out["low"] = out[["open", "low", "close"]].min(axis=1)\n',
    '    return out\n',
    '\n',
    '\n',
    'def _bar_delta(market: pd.DataFrame) -> pd.Timedelta:\n',
    '    d = pd.to_datetime(market["time"], errors="coerce").diff().dropna()\n',
    '    median = d.median() if len(d) else pd.Timedelta(hours=1)\n',
    '    return median if pd.notna(median) and median.total_seconds() > 0 else pd.Timedelta(hours=1)\n',
    '\n',
    '\n',
    'def _atr(market: pd.DataFrame) -> float:\n',
    '    prev = market["close"].shift(1)\n',
    '    tr = pd.concat([(market["high"]-market["low"]).abs(), (market["high"]-prev).abs(), (market["low"]-prev).abs()], axis=1).max(axis=1)\n',
    '    value = _finite(tr.tail(96).median(), 0.0)\n',
    '    return value if value > 0 else max(abs(_finite(market["close"].iloc[-1])) * .00035, 1e-8)\n',
    '\n',
    '\n',
    'def _source_path(source: pd.DataFrame, *, path: str, horizon: int, future_times: Sequence[pd.Timestamp], anchor: float) -> pd.DataFrame:\n',
    '    columns = ["step", "time", f"{path}_raw"]\n',
    '    if not isinstance(source, pd.DataFrame) or source.empty:\n',
    '        return pd.DataFrame(columns=columns)\n',
    '    value_col = _find_col(source, (f"{path} path", "path", "accuracy adjusted price", "predicted close", "pred close", "projected close", "yellow predicted close", "calibrated close", "forecast close", "close", "projected path"))\n',
    '    if value_col is None:\n',
    '        return pd.DataFrame(columns=columns)\n',
    '    time_col = _find_col(source, ("time", "future time", "datetime", "date", "projection time"))\n',
    '    step_col = _find_col(source, ("step", "prediction step", "horizon", "horizon point", "projection step"))\n',
    '    work = pd.DataFrame({f"{path}_raw": pd.to_numeric(source[value_col], errors="coerce")})\n',
    '    work["step"] = pd.to_numeric(source[step_col], errors="coerce") if step_col else np.arange(1, len(work)+1)\n',
    '    work = work.dropna(subset=[f"{path}_raw", "step"])\n',
    '    work["step"] = work["step"].astype(int)\n',
    '    work = work[(work["step"] >= 1) & (work["step"] <= horizon)].sort_values("step").drop_duplicates("step", keep="last").head(horizon).copy()\n',
    '    if work.empty:\n',
    '        return pd.DataFrame(columns=columns)\n',
    '    if time_col:\n',
    '        mapped = pd.to_datetime(source.loc[work.index, time_col], errors="coerce")\n',
    '        work["time"] = mapped.to_numpy()\n',
    '    else:\n',
    '        work["time"] = [future_times[min(max(int(x)-1, 0), len(future_times)-1)] for x in work["step"]]\n',
    '    anchor_col = _find_col(source, ("anchor price", "anchor_price", "start price", "predicted open", "origin close", "open"))\n',
    '    if anchor_col is not None:\n',
    '        source_anchor = _finite(source[anchor_col].dropna().iloc[0] if source[anchor_col].notna().any() else anchor, anchor)\n',
    '        work[f"{path}_raw"] = anchor + (work[f"{path}_raw"] - source_anchor)\n',
    '    return work[columns].reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _weighted_median(values: np.ndarray, weights: np.ndarray) -> float:\n',
    '    if len(values) == 0:\n',
    '        return 0.0\n',
    '    order = np.argsort(values)\n',
    '    v = values[order]; w = weights[order]\n',
    '    total = float(w.sum())\n',
    '    if total <= 0:\n',
    '        return float(np.median(v))\n',
    '    return float(v[np.searchsorted(np.cumsum(w), total * .5, side="left")])\n',
    '\n',
    '\n',
    'def _winsorized(values: pd.Series) -> np.ndarray:\n',
    '    arr = pd.to_numeric(values, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna().to_numpy(dtype=float)\n',
    '    if len(arr) < 4:\n',
    '        return arr\n',
    '    med = float(np.median(arr)); mad = float(np.median(np.abs(arr-med)))\n',
    '    if mad > 1e-12:\n',
    '        lo, hi = med - 5.0 * 1.4826 * mad, med + 5.0 * 1.4826 * mad\n',
    '    else:\n',
    '        lo, hi = np.quantile(arr, [.05, .95])\n',
    '    return np.clip(arr, lo, hi)\n',
    '\n',
    '\n',
    'def _residual_history(history: pd.DataFrame, anchor_time: pd.Timestamp) -> pd.DataFrame:\n',
    '    columns = ["path", "horizon", "residual", "abs_error", "completed_time", "regime", "direction_correct"]\n',
    '    if not isinstance(history, pd.DataFrame) or history.empty:\n',
    '        return pd.DataFrame(columns=columns)\n',
    '    actual_col = _find_col(history, ("actual close", "actual", "close actual", "real close"))\n',
    '    pred_col = _find_col(history, ("predicted close", "pred close", "prediction", "projected close", "forecast close"))\n',
    '    if actual_col is None or pred_col is None:\n',
    '        return pd.DataFrame(columns=columns)\n',
    '    actual = pd.to_numeric(history[actual_col], errors="coerce"); pred = pd.to_numeric(history[pred_col], errors="coerce")\n',
    '    out = pd.DataFrame({"residual": actual-pred})\n',
    '    out["abs_error"] = out["residual"].abs()\n',
    '    pcol = _find_col(history, ("path", "model", "source path", "prediction path", "color"))\n',
    '    hcol = _find_col(history, ("horizon", "step", "prediction step", "horizon point"))\n',
    '    tcol = _find_col(history, ("target time", "actual time", "completed time", "time", "datetime", "timestamp"))\n',
    '    rcol = _find_col(history, ("regime", "current regime", "major regime", "regime group"))\n',
    '    dcol = _find_col(history, ("direction correct", "correct direction", "direction hit"))\n',
    '    out["path"] = history[pcol].astype(str).str.lower() if pcol else "generic"\n',
    '    out["path"] = out["path"].map(lambda x: next((p for p in PATHS if p in x), "generic"))\n',
    '    out["horizon"] = pd.to_numeric(history[hcol], errors="coerce").fillna(0).astype(int) if hcol else 0\n',
    '    out["completed_time"] = pd.to_datetime(history[tcol], errors="coerce") if tcol else pd.NaT\n',
    '    out["regime"] = history[rcol].astype(str) if rcol else "GLOBAL"\n',
    '    if dcol:\n',
    '        values = history[dcol]\n',
    '        if values.dtype == bool:\n',
    '            out["direction_correct"] = values.astype(float)\n',
    '        else:\n',
    '            out["direction_correct"] = values.astype(str).str.upper().map({"TRUE":1.,"YES":1.,"CORRECT":1.,"1":1.,"FALSE":0.,"NO":0.,"WRONG":0.,"0":0.})\n',
    '    else:\n',
    '        out["direction_correct"] = np.nan\n',
    '    out = out.replace([np.inf, -np.inf], np.nan).dropna(subset=["residual"])\n',
    '    if out["completed_time"].notna().any():\n',
    '        out = out[(out["completed_time"].isna()) | (out["completed_time"] <= anchor_time)]\n',
    '        out = out.sort_values("completed_time", na_position="first")\n',
    '    return out.reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _subset_residuals(residuals: pd.DataFrame, path: str, horizon: int, regime: str | None = None) -> pd.DataFrame:\n',
    '    if residuals.empty:\n',
    '        return residuals\n',
    '    p = residuals[(residuals["path"].isin([path, "generic"])) & (residuals["horizon"].isin([horizon, 0]))]\n',
    '    if regime:\n',
    '        same = p[p["regime"].astype(str).str.upper() == str(regime).upper()]\n',
    '        return same\n',
    '    return p\n',
    '\n',
    '\n',
    'def _decay_weights(n: int, half_life: float = 45.0) -> np.ndarray:\n',
    '    if n <= 0:\n',
    '        return np.array([], dtype=float)\n',
    '    age = np.arange(n-1, -1, -1, dtype=float)\n',
    '    return np.exp(-math.log(2.0) * age / max(half_life, 1.0))\n',
    '\n',
    '\n',
    'def _bias_for(residuals: pd.DataFrame, path: str, horizon: int, regime: str, atr: float) -> tuple[float, float, float, int, int, np.ndarray]:\n',
    '    global_rows = _subset_residuals(residuals, path, horizon)\n',
    '    same_rows = _subset_residuals(residuals, path, horizon, regime=regime) if regime else global_rows.iloc[0:0]\n',
    '    global_values = _winsorized(global_rows["residual"])\n',
    '    same_values = _winsorized(same_rows["residual"])\n',
    '    global_bias = _weighted_median(global_values, _decay_weights(len(global_values))) if len(global_values) else 0.0\n',
    '    same_bias = _weighted_median(same_values, _decay_weights(len(same_values), 30.0)) if len(same_values) else global_bias\n',
    '    regime_weight = len(same_values) / (len(same_values) + 12.0) if len(same_values) else 0.0\n',
    '    correction = regime_weight * same_bias + (1.0-regime_weight) * global_bias\n',
    '    cap = max(atr * (1.5 + .35*math.sqrt(horizon)), 1e-9)\n',
    '    correction = _clip(correction, -cap, cap)\n',
    '    return correction, global_bias, same_bias, len(global_values), len(same_values), global_values\n',
    '\n',
    '\n',
    'def _path_reliability(residuals: pd.DataFrame, path: str, horizon: int, atr: float, summary_direction: float | None) -> Dict[str, float]:\n',
    '    rows = _subset_residuals(residuals, path, horizon)\n',
    '    values = _winsorized(rows["residual"])\n',
    '    n = len(values)\n',
    '    if n:\n',
    '        weights = _decay_weights(n)\n',
    '        abs_med = _weighted_median(np.abs(values), weights)\n',
    '        stability = float(np.median(np.abs(np.abs(values)-np.median(np.abs(values))))) if n >= 3 else abs_med\n',
    '    else:\n',
    '        abs_med = atr * .75; stability = atr * .5\n',
    '    direct = rows["direction_correct"].dropna()\n',
    '    direction = float(direct.tail(120).mean()*100.0) if len(direct) else (summary_direction if summary_direction is not None else 50.0)\n',
    '    error_component = 1.0 / max(abs_med, atr*.20, 1e-10)\n',
    '    stability_penalty = 1.0 / (1.0 + stability/max(atr, 1e-10))\n',
    '    direction_factor = .65 + _clip(direction, 0, 100)/100.0*.70\n',
    '    sample_factor = .50 + min(n/60.0, 1.0)*.50\n',
    '    return {"raw_score": error_component*stability_penalty*direction_factor*sample_factor, "abs_error": abs_med, "stability": stability, "direction_accuracy": direction, "samples": float(n)}\n',
    '\n',
    '\n',
    'def _bounded_weights(scores: Dict[str, float], available: list[str]) -> Dict[str, float]:\n',
    '    if not available:\n',
    '        return {}\n',
    '    if len(available) == 1:\n',
    '        return {available[0]: 1.0}\n',
    '    vals = np.array([max(_finite(scores.get(p), 0.0), 1e-12) for p in available], dtype=float)\n',
    '    vals /= vals.sum()\n',
    '    lower, upper = .15, .55\n',
    '    # Iterative bounded simplex projection; deterministic for identical inputs.\n',
    '    w = vals.copy()\n',
    '    for _ in range(12):\n',
    '        w = np.clip(w, lower, upper)\n',
    '        diff = 1.0 - float(w.sum())\n',
    '        if abs(diff) < 1e-12:\n',
    '            break\n',
    '        if diff > 0:\n',
    '            free = np.where(w < upper-1e-12)[0]\n',
    '            if not len(free): break\n',
    '            room = upper-w[free]; add = diff*room/room.sum(); w[free] += add\n',
    '        else:\n',
    '            free = np.where(w > lower+1e-12)[0]\n',
    '            if not len(free): break\n',
    '            room = w[free]-lower; take = (-diff)*room/room.sum(); w[free] -= take\n',
    '    w /= w.sum()\n',
    '    return {p: float(v) for p, v in zip(available, w)}\n',
    '\n',
    '\n',
    'def _market_prior(market: pd.DataFrame, horizon: int, atr: float) -> list[float]:\n',
    '    close = market["close"].astype(float); returns = close.pct_change().dropna()\n',
    '    anchor = float(close.iloc[-1])\n',
    '    drift = _finite(returns.tail(12).median(), 0.0)*.55 + _finite(returns.tail(48).median(), 0.0)*.25\n',
    '    drift = _clip(drift, -atr/max(abs(anchor),1e-12), atr/max(abs(anchor),1e-12))\n',
    '    values=[]; prev=anchor\n',
    '    for step in range(1,horizon+1):\n',
    '        target = prev*(1.0+drift*(.92**(step-1)))\n',
    '        target = prev + _clip(target-prev, -atr*1.2, atr*1.2)\n',
    '        values.append(max(target, 1e-9)); prev=values[-1]\n',
    '    return values\n',
    '\n',
    '\n',
    'def calibrate_projection_bundle(\n',
    '    market_data: pd.DataFrame, *, red: pd.DataFrame|None=None, yellow: pd.DataFrame|None=None, blue: pd.DataFrame|None=None,\n',
    '    horizon: int=6, bt_history: pd.DataFrame|None=None, bt_summary: Dict[str,Any]|None=None,\n',
    '    regime_reliability: float|None=None, current_regime: str|None=None, transition_or_conflict: Any=None,\n',
    '    calculation_timestamp: Any=None, source_data_timestamp: Any=None,\n',
    ') -> Dict[str, Any]:\n',
    '    market = _prepare_market(market_data)\n',
    '    if market.empty or len(market) < 8:\n',
    '        return {"ok":False,"message":"Need clean timestamped OHLC data."}\n',
    '    horizon = int(max(1,min(int(horizon or 6),96)))\n',
    '    anchor = float(market["close"].iloc[-1]); anchor_time = pd.Timestamp(market["time"].iloc[-1]); delta = _bar_delta(market); atr = _atr(market)\n',
    '    future_times = [anchor_time+delta*step for step in range(1,horizon+1)]\n',
    '    base = pd.DataFrame({"step":np.arange(1,horizon+1),"time":future_times})\n',
    '    source_map={"red":red,"yellow":yellow,"blue":blue}\n',
    '    for path in PATHS:\n',
    '        frame=_source_path(source_map[path] if isinstance(source_map[path],pd.DataFrame) else pd.DataFrame(), path=path, horizon=horizon, future_times=future_times, anchor=anchor)\n',
    '        if not frame.empty:\n',
    '            base=base.merge(frame.drop(columns="time",errors="ignore"),on="step",how="left")\n',
    '        else:\n',
    '            base[f"{path}_raw"]=np.nan\n',
    '    available=[p for p in PATHS if base[f"{p}_raw"].notna().any()]\n',
    '    residuals=_residual_history(bt_history if isinstance(bt_history,pd.DataFrame) else pd.DataFrame(),anchor_time)\n',
    '    summary=bt_summary if isinstance(bt_summary,dict) else {}\n',
    '    direction_summary=None\n',
    '    for k in ("direction_accuracy_pct","direction accuracy pct","direction_accuracy","accuracy_pct"):\n',
    '        if k in summary:\n',
    '            direction_summary=_finite(summary[k],50.0); direction_summary*=100 if 0<=direction_summary<=1 else 1; break\n',
    '    regime=str(current_regime or "GLOBAL")\n',
    '    regime_rel=_clip(regime_reliability if regime_reliability is not None else 55.0, 0, 100)\n',
    '    expansion=any(x in regime.upper() for x in ("EXPANSION","VOLATILE"))\n',
    '    recent_tr=(market["high"]-market["low"]).abs()\n',
    '    if len(recent_tr)>=48 and _finite(recent_tr.tail(12).median(),0)>_finite(recent_tr.tail(48).median(),1)*1.35:\n',
    '        expansion=True\n',
    '    step_cap=atr*(2.0 if expansion else 1.5)\n',
    '    corrections={p:[] for p in PATHS}; global_corr={p:[] for p in PATHS}; regime_corr={p:[] for p in PATHS}; sample_counts={p:[] for p in PATHS}; residual_samples={}\n',
    '    for path in PATHS:\n',
    '        calibrated=[]; prev=anchor\n',
    '        for h in range(1,horizon+1):\n',
    '            corr,g,same,ng,nr,vals=_bias_for(residuals,path,h,regime,atr)\n',
    '            corrections[path].append(corr); global_corr[path].append(g); regime_corr[path].append(same); sample_counts[path].append((ng,nr)); residual_samples[f"{path}_H+{h}"]=vals.tolist()\n',
    '            raw=_finite(base.loc[h-1,f"{path}_raw"],float("nan"))\n',
    '            if math.isfinite(raw):\n',
    '                target=raw+corr\n',
    '                target=prev+_clip(target-prev,-step_cap,step_cap)\n',
    '                target=max(target,1e-9); calibrated.append(target); prev=target\n',
    '            else:\n',
    '                calibrated.append(np.nan)\n',
    '        base[f"{path}_path"]=calibrated\n',
    '    priors=_market_prior(market,horizon,atr)\n',
    '    main=[]; spreads=[]; weights_rows=[]; reliability_rows=[]; prev=anchor\n',
    '    for h in range(1,horizon+1):\n',
    '        vals={p:_finite(base.loc[h-1,f"{p}_path"],float("nan")) for p in available}\n',
    '        vals={p:v for p,v in vals.items() if math.isfinite(v)}\n',
    '        active=list(vals)\n',
    '        if active:\n',
    '            rels={p:_path_reliability(residuals,p,h,atr,direction_summary) for p in active}\n',
    '            spread=float(np.median(np.abs(np.array(list(vals.values()))-np.median(list(vals.values()))))) if len(vals)>1 else 0.0\n',
    '            raw_scores={p:rels[p]["raw_score"] for p in active}\n',
    '            if len(active)>1 and spread>atr*.75:\n',
    '                least=min(active,key=lambda p: raw_scores[p]); raw_scores[least]*=.60\n',
    '            weights=_bounded_weights(raw_scores,active)\n',
    '            consensus=sum(vals[p]*weights[p] for p in active)\n',
    '            disagreement_ratio=_clip(spread/max(atr,1e-12),0,3)\n',
    '            shrink=1.0/(1.0+.22*disagreement_ratio)\n',
    '            target=prev+(consensus-prev)*shrink\n',
    '            target=prev+_clip(target-prev,-step_cap,step_cap)\n',
    '            rel_score=np.mean([_clip(100*(.45*min(rels[p]["samples"]/60,1)+.35*max(0,1-rels[p]["abs_error"]/(atr*2.5))+.20*rels[p]["direction_accuracy"]/100),0,100) for p in active])\n',
    '        else:\n',
    '            # Required safe fallback: flat from the latest completed close.\n',
    '            spread=0.0; weights={}; target=anchor; rel_score=35.0\n',
    '        target=max(_finite(target,anchor),1e-9); main.append(target); spreads.append(spread); prev=target\n',
    '        weights_rows.append({"step":h,**{p:weights.get(p,0.0) for p in PATHS}})\n',
    '        reliability_rows.append(rel_score)\n',
    '    base["main_path"]=main; base["source_spread"]=spreads\n',
    '    # Signed residual-quantile bands with causal regime/global histories.\n',
    '    widths=[]; lowers=[]; uppers=[]; quantile_rows=[]; previous_width=0.0\n',
    '    previous_lower_extent=0.0; previous_upper_extent=0.0\n',
    '    conflict_text=str(transition_or_conflict or "").upper(); conflict_factor=1.20 if any(x in conflict_text for x in ("HIGH","CONFLICT","TRANSITION","TRUE")) else 1.0\n',
    '    fallback_multiplier=1.35 if len(available)==1 else 1.65 if not available else 1.0\n',
    '    for h in range(1,horizon+1):\n',
    '        pooled=[]\n',
    '        for p in available or PATHS:\n',
    '            pooled.extend(residual_samples.get(f"{p}_H+{h}",[]))\n',
    '        arr=np.asarray(pooled,dtype=float)\n',
    '        if len(arr):\n',
    '            q10=float(np.quantile(arr,.10)); q90=float(np.quantile(arr,.90)); empirical=max(float(np.median(np.abs(arr))),atr*.30)\n',
    '        else:\n',
    '            q10=-atr*(.45+.18*math.sqrt(h)); q90=atr*(.45+.18*math.sqrt(h)); empirical=atr*.55\n',
    '        q10=min(q10,-empirical*.55); q90=max(q90,empirical*.55)\n',
    '        rel=_clip(reliability_rows[h-1],0,100); disagreement=spreads[h-1]\n',
    '        scale=(1.0+(100-rel)/100*.45)*(1.0+(100-regime_rel)/100*.25)*conflict_factor*fallback_multiplier\n',
    '        volatility_floor=atr*(.42+.20*math.sqrt(h))\n',
    '        lower_extent=(max(abs(min(q10,0.0)),volatility_floor)+disagreement*.85)*scale\n',
    '        upper_extent=(max(max(q90,0.0),volatility_floor)+disagreement*.85)*scale\n',
    '        lower_extent=max(lower_extent,previous_lower_extent*1.01 if previous_lower_extent else lower_extent)\n',
    '        upper_extent=max(upper_extent,previous_upper_extent*1.01 if previous_upper_extent else upper_extent)\n',
    '        previous_lower_extent=lower_extent; previous_upper_extent=upper_extent\n',
    '        width=max(lower_extent,upper_extent,previous_width*1.01 if previous_width else 0.0); previous_width=width\n',
    '        lo=max(main[h-1]-lower_extent,1e-9); hi=max(main[h-1]+upper_extent,main[h-1]); lowers.append(lo); uppers.append(hi); widths.append(width)\n',
    '        quantile_rows.append({"step":h,"q10":q10,"q90":q90,"samples":len(arr),"lower_extent":lower_extent,"upper_extent":upper_extent})\n',
    '    base["band_width"]=widths; base["lower_band"]=np.minimum(lowers,base["main_path"]); base["upper_band"]=np.maximum(uppers,base["main_path"])\n',
    '    # All finite safety net.\n',
    '    for col in ("main_path","lower_band","upper_band","band_width","source_spread"):\n',
    '        base[col]=pd.to_numeric(base[col],errors="coerce").replace([np.inf,-np.inf],np.nan)\n',
    '    base["main_path"]=base["main_path"].fillna(anchor).clip(lower=1e-9)\n',
    '    base["band_width"]=base["band_width"].fillna(atr).clip(lower=0)\n',
    '    base["lower_band"]=base["lower_band"].fillna(base["main_path"]-base["band_width"]).clip(lower=1e-9)\n',
    '    base["upper_band"]=base["upper_band"].fillna(base["main_path"]+base["band_width"])\n',
    '    base["lower_band"]=np.minimum(base["lower_band"],base["main_path"]); base["upper_band"]=np.maximum(base["upper_band"],base["main_path"])\n',
    '    weights_df=pd.DataFrame(weights_rows)\n',
    '    path_rel=float(np.mean(reliability_rows)) if reliability_rows else 35\n',
    '    mean_rel=_clip(path_rel*.85+regime_rel*.15,25,92)\n',
    '    if residuals.empty: mean_rel=min(mean_rel,58)\n',
    '    agreement=_clip(100-float(np.mean(spreads))/max(atr,1e-12)*35,0,100)\n',
    '    source_names=available if available else ["market_prior"]\n',
    '    summary_out={\n',
    '        "version":CALIBRATION_VERSION,"reliability_pct":round(mean_rel,2),"path_agreement_pct":round(agreement,2),\n',
    '        "estimated_band_coverage_pct":round(_clip(72+min(len(residuals),80)*.18-(100-mean_rel)*.12,50,94),2),\n',
    '        "median_abs_error_pct":round((_finite(residuals["abs_error"].median(),atr*.55)/max(abs(anchor),1e-12))*100,6),\n',
    '        "error_samples":int(len(residuals)),"error_is_proxy":bool(residuals.empty),"direction_accuracy_pct":None if direction_summary is None else round(direction_summary,2),\n',
    '        "atr_price":round(atr,8),"sources_used":source_names,"anchor_time":str(anchor_time),"anchor_price":round(anchor,8),\n',
    '        "fallback_state":"ALL_PATHS_MISSING" if not available else "ONE_PATH_ONLY" if len(available)==1 else "PARTIAL_PATHS" if len(available)==2 else "NONE",\n',
    '        "current_regime":regime,"regime_reliability_pct":round(regime_rel,2),"calculation_timestamp":str(calculation_timestamp or pd.Timestamp.utcnow()),"source_data_timestamp":str(source_data_timestamp or anchor_time),\n',
    '    }\n',
    '    main_df=base[["step","time","main_path","upper_band","lower_band","band_width","source_spread"]].copy()\n',
    '    outputs={p:base[["step","time",f"{p}_path"]].dropna(subset=[f"{p}_path"]).copy() for p in PATHS}\n',
    '    raw_frames={p:base[["step","time",f"{p}_raw"]].copy() for p in PATHS}\n',
    '    audit={\n',
    '        "raw_paths":raw_frames,"calibrated_paths":outputs,"path_weights":weights_df,"horizon_residual_samples":residual_samples,\n',
    '        "global_corrections":{p:global_corr[p] for p in PATHS},"regime_corrections":{p:regime_corr[p] for p in PATHS},\n',
    '        "final_corrections":{p:corrections[p] for p in PATHS},"sample_counts":sample_counts,"band_quantiles":pd.DataFrame(quantile_rows),\n',
    '        "fallback_state":summary_out["fallback_state"],"anchor_price":anchor,"anchor_time":anchor_time,"calculation_timestamp":summary_out["calculation_timestamp"],"source_data_timestamp":summary_out["source_data_timestamp"],\n',
    '    }\n',
    '    return {"ok":True,"main":main_df,"red":outputs["red"],"yellow":outputs["yellow"],"blue":outputs["blue"],"raw":base,"summary":summary_out,"audit":audit,"path_weights":weights_df}\n',
    '\n',
    '\n',
    'def calibrated_candles(bundle: Dict[str,Any], *, anchor_price: float) -> pd.DataFrame:\n',
    '    if not isinstance(bundle,dict) or not bundle.get("ok"):\n',
    '        return pd.DataFrame()\n',
    '    main=bundle.get("main")\n',
    '    if not isinstance(main,pd.DataFrame) or main.empty:\n',
    '        return pd.DataFrame()\n',
    '    rows=[]; previous=float(anchor_price)\n',
    '    for _,row in main.iterrows():\n',
    '        close=max(_finite(row.get("main_path"),previous),1e-9); upper=max(_finite(row.get("upper_band"),close),close); lower=min(max(_finite(row.get("lower_band"),close),1e-9),close)\n',
    '        rows.append({"time":pd.Timestamp(row.get("time")),"open":round(previous,6),"high":round(max(previous,close,upper),6),"low":round(min(previous,close,lower),6),"close":round(close,6),"prediction_step":int(row.get("step",len(rows)+1)),"candle_type":"CALIBRATED_POWERBI_FUTURE","Upper Band":round(upper,6),"Lower Band":round(lower,6),"Calibration Version":CALIBRATION_VERSION})\n',
    '        previous=close\n',
    '    return pd.DataFrame(rows)\n',
    '\n',
    '# ============================================================================\n',
    '# QUANT RESEARCH V8 SHADOW EXTENSION\n',
    '# Existing raw-path and v2 calibration functions above remain unchanged.\n',
    '# ============================================================================\n',
    'V8_CALIBRATION_VERSION = "powerbi-cqr-adaptive-v8-20260622"\n',
    'V8_TARGET_COVERAGES = (0.80, 0.90, 0.95)\n',
    '\n',
    '\n',
    'def conformal_nonconformity(raw_lower: Any, raw_upper: Any, actual: Any) -> float:\n',
    '    """CQR nonconformity: max(lower-actual, actual-upper, 0)."""\n',
    '    lo, hi, y = _finite(raw_lower, float("nan")), _finite(raw_upper, float("nan")), _finite(actual, float("nan"))\n',
    '    if not all(math.isfinite(v) for v in (lo, hi, y)):\n',
    '        return float("nan")\n',
    '    if lo > hi:\n',
    '        lo, hi = hi, lo\n',
    '    return float(max(lo - y, y - hi, 0.0))\n',
]
