"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '\n',
    '\n',
    'def _v8_settled_outcomes(frame: pd.DataFrame, cutoff_utc: Any | None = None) -> pd.DataFrame:\n',
    '    """Normalize only settled rows and reject future/pending evidence."""\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame()\n',
    '    out = frame.copy(deep=False)\n',
    '    aliases = {\n',
    '        "actual": ("actual", "actual_price", "actual close", "real_close"),\n',
    '        "raw_lower": ("raw_lower", "lower", "lower_bound", "predicted_lower"),\n',
    '        "raw_upper": ("raw_upper", "upper", "upper_bound", "predicted_upper"),\n',
    '        "raw_prediction": ("raw_prediction", "predicted_price", "prediction", "predicted close"),\n',
    '        "horizon_hours": ("horizon_hours", "horizon", "step"),\n',
    '        "settlement_time_utc": ("settlement_time_utc", "settled_at", "target_time", "actual_time", "completed_time"),\n',
    '        "forecast_event_time_utc": ("forecast_event_time_utc", "prediction_time", "event_time_utc", "origin_time"),\n',
    '        "regime": ("regime", "major_regime", "current_regime"),\n',
    '        "session": ("session", "market_session"),\n',
    '        "status": ("status", "outcome_status", "settlement_status"),\n',
    '        "model": ("model", "path", "source", "expert"),\n',
    '        "calculation_id": ("calculation_id", "run_id", "canonical_calculation_id"),\n',
    '        "generation_id": ("generation_id", "calculation_generation", "generation"),\n',
    '        "calibrated_prediction": ("calibrated_prediction", "calibrated_price"),\n',
    '        "lower_80": ("lower_80", "lower80"), "upper_80": ("upper_80", "upper80"),\n',
    '        "lower_90": ("lower_90", "lower90"), "upper_90": ("upper_90", "upper90"),\n',
    '        "lower_95": ("lower_95", "lower95"), "upper_95": ("upper_95", "upper95"),\n',
    '        "reliability": ("reliability", "confidence", "forecast_reliability"),\n',
    '    }\n',
    '    lower = {str(c).strip().lower().replace("_", " "): c for c in out.columns}\n',
    '    data: dict[str, Any] = {}\n',
    '    for target, names in aliases.items():\n',
    '        hit = None\n',
    '        for name in names:\n',
    '            key = name.strip().lower().replace("_", " ")\n',
    '            if key in lower:\n',
    '                hit = lower[key]; break\n',
    '        if hit is not None:\n',
    '            data[target] = out[hit]\n',
    '    norm = pd.DataFrame(data)\n',
    '    if "actual" not in norm or "horizon_hours" not in norm:\n',
    '        return pd.DataFrame()\n',
    '    for c in ("actual", "raw_lower", "raw_upper", "raw_prediction", "calibrated_prediction", "lower_80", "upper_80", "lower_90", "upper_90", "lower_95", "upper_95", "reliability", "generation_id", "horizon_hours"):\n',
    '        if c in norm:\n',
    '            norm[c] = pd.to_numeric(norm[c], errors="coerce")\n',
    '    if "settlement_time_utc" in norm:\n',
    '        norm["settlement_time_utc"] = pd.to_datetime(norm["settlement_time_utc"], errors="coerce", utc=True)\n',
    '    else:\n',
    '        norm["settlement_time_utc"] = pd.NaT\n',
    '    if "forecast_event_time_utc" in norm:\n',
    '        norm["forecast_event_time_utc"] = pd.to_datetime(norm["forecast_event_time_utc"], errors="coerce", utc=True)\n',
    '    if "status" in norm:\n',
    '        settled = norm["status"].astype(str).str.upper().isin({"SETTLED", "COMPLETED", "RESOLVED", "ACTUAL_AVAILABLE", "OK"})\n',
    '        norm = norm[settled]\n',
    '    norm = norm.dropna(subset=["actual", "horizon_hours"])\n',
    '    if cutoff_utc is not None:\n',
    '        cutoff = pd.to_datetime(cutoff_utc, errors="coerce", utc=True)\n',
    '        if pd.notna(cutoff):\n',
    '            norm = norm[norm["settlement_time_utc"].isna() | (norm["settlement_time_utc"] <= cutoff)]\n',
    '    # Same-row leakage guard: settlement must follow forecast when both exist.\n',
    '    if "forecast_event_time_utc" in norm:\n',
    '        norm = norm[norm["forecast_event_time_utc"].isna() | norm["settlement_time_utc"].isna() | (norm["settlement_time_utc"] > norm["forecast_event_time_utc"])]\n',
    '    if "raw_lower" not in norm or "raw_upper" not in norm:\n',
    '        if "raw_prediction" not in norm:\n',
    '            return pd.DataFrame()\n',
    '        # A point forecast is treated as a zero-width raw interval; conformal expands it.\n',
    '        norm["raw_lower"] = norm["raw_prediction"]\n',
    '        norm["raw_upper"] = norm["raw_prediction"]\n',
    '    norm["raw_lower"], norm["raw_upper"] = np.minimum(norm["raw_lower"], norm["raw_upper"]), np.maximum(norm["raw_lower"], norm["raw_upper"])\n',
    '    norm["nonconformity"] = [conformal_nonconformity(a,b,c) for a,b,c in zip(norm["raw_lower"], norm["raw_upper"], norm["actual"])]\n',
    '    norm = norm.replace([np.inf,-np.inf], np.nan).dropna(subset=["nonconformity"]).sort_values("settlement_time_utc", na_position="first")\n',
    '    return norm.tail(5000).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _finite_sample_quantile(values: pd.Series, coverage: float) -> float:\n',
    '    arr = pd.to_numeric(values, errors="coerce").dropna().to_numpy(dtype=float)\n',
    '    if len(arr) == 0:\n',
    '        return float("nan")\n',
    '    rank = min(1.0, math.ceil((len(arr) + 1) * float(coverage)) / len(arr))\n',
    '    try:\n',
    '        return float(np.quantile(arr, rank, method="higher"))\n',
    '    except TypeError:\n',
    '        return float(np.quantile(arr, rank, interpolation="higher"))\n',
    '\n',
    '\n',
    'def _conditioned_calibration_rows(settled: pd.DataFrame, *, horizon: int, regime: str | None, session: str | None, minimum_samples: int) -> tuple[pd.DataFrame, str]:\n',
    '    base = settled[settled["horizon_hours"].astype(int) == int(horizon)]\n',
    '    candidates: list[tuple[pd.DataFrame, str]] = []\n',
    '    if regime and session and "regime" in base and "session" in base:\n',
    '        candidates.append((base[base["regime"].astype(str).str.upper().eq(str(regime).upper()) & base["session"].astype(str).str.upper().eq(str(session).upper())], "regime+session+horizon"))\n',
    '    if regime and "regime" in base:\n',
    '        candidates.append((base[base["regime"].astype(str).str.upper().eq(str(regime).upper())], "regime+horizon"))\n',
    '    candidates.append((base, "horizon"))\n',
    '    candidates.append((settled, "pooled_settled_evidence"))\n',
    '    for rows, label in candidates:\n',
    '        if len(rows) >= int(minimum_samples):\n',
    '            return rows.tail(1000), label\n',
    '    return pd.DataFrame(), "INSUFFICIENT EVIDENCE"\n',
    '\n',
    '\n',
    'def fit_conformal_cqr_intervals(\n',
    '    forecast_rows: pd.DataFrame,\n',
    '    settled_outcomes: pd.DataFrame,\n',
    '    *,\n',
    '    cutoff_utc: Any | None = None,\n',
    '    regime: str | None = None,\n',
    '    session: str | None = None,\n',
    '    minimum_samples: int = 30,\n',
    '    target_coverages: Sequence[float] = V8_TARGET_COVERAGES,\n',
    '    adaptive_alpha_state: Mapping[str, Any] | None = None,\n',
    ') -> tuple[pd.DataFrame, pd.DataFrame]:\n',
    '    """Return calibrated forecast intervals and compact horizon metadata.\n',
    '\n',
    '    The function is shadow-only. It never modifies raw path columns and never\n',
    '    consumes unresolved outcomes or evidence after ``cutoff_utc``.\n',
    '    """\n',
    '    if not isinstance(forecast_rows, pd.DataFrame) or forecast_rows.empty:\n',
    '        return pd.DataFrame(), pd.DataFrame()\n',
    '    forecasts = forecast_rows.copy(deep=False)\n',
    '    if "horizon_hours" not in forecasts:\n',
    '        forecasts["horizon_hours"] = np.arange(1, len(forecasts)+1)\n',
    '    forecasts["horizon_hours"] = pd.to_numeric(forecasts["horizon_hours"], errors="coerce").astype("Int64")\n',
    '    pred_col = next((c for c in ("raw_prediction","prediction","predicted_price","consensus","calibrated_prediction") if c in forecasts), None)\n',
    '    lo_col = next((c for c in ("raw_lower","lower","lower_bound") if c in forecasts), None)\n',
    '    hi_col = next((c for c in ("raw_upper","upper","upper_bound") if c in forecasts), None)\n',
    '    if pred_col is None and (lo_col is None or hi_col is None):\n',
    '        return pd.DataFrame(), pd.DataFrame()\n',
    '    if lo_col is None: forecasts["raw_lower"] = pd.to_numeric(forecasts[pred_col], errors="coerce"); lo_col = "raw_lower"\n',
    '    if hi_col is None: forecasts["raw_upper"] = pd.to_numeric(forecasts[pred_col], errors="coerce"); hi_col = "raw_upper"\n',
    '    forecasts["raw_lower_v8"] = np.minimum(pd.to_numeric(forecasts[lo_col], errors="coerce"), pd.to_numeric(forecasts[hi_col], errors="coerce"))\n',
    '    forecasts["raw_upper_v8"] = np.maximum(pd.to_numeric(forecasts[lo_col], errors="coerce"), pd.to_numeric(forecasts[hi_col], errors="coerce"))\n',
    '    settled = _v8_settled_outcomes(settled_outcomes, cutoff_utc=cutoff_utc)\n',
    '    metadata = []\n',
    '    state = dict(adaptive_alpha_state or {})\n',
    '    for horizon in forecasts["horizon_hours"].dropna().astype(int).unique():\n',
    '        rows, fallback = _conditioned_calibration_rows(settled, horizon=horizon, regime=regime, session=session, minimum_samples=minimum_samples)\n',
    '        mask = forecasts["horizon_hours"].astype("Int64") == horizon\n',
    '        for coverage in target_coverages:\n',
    '            suffix = int(round(float(coverage)*100))\n',
    '            if rows.empty:\n',
    '                forecasts.loc[mask, f"lower_{suffix}"] = np.nan\n',
    '                forecasts.loc[mask, f"upper_{suffix}"] = np.nan\n',
    '                metadata.append({"horizon_hours": horizon, "target_coverage": float(coverage), "achieved_rolling_coverage": None, "sample_count": 0, "interval_width": None, "interval_score": None, "calibration_age": None, "fallback_level": fallback, "status": "INSUFFICIENT EVIDENCE"})\n',
    '                continue\n',
    '            alpha_key = str(horizon)\n',
    '            alpha = float((state.get(alpha_key) or {}).get("alpha", 1.0 - float(coverage))) if isinstance(state.get(alpha_key), Mapping) else 1.0-float(coverage)\n',
    '            effective_coverage = min(.995, max(.50, 1.0-alpha))\n',
    '            q = _finite_sample_quantile(rows["nonconformity"], effective_coverage)\n',
    '            forecasts.loc[mask, f"lower_{suffix}"] = forecasts.loc[mask, "raw_lower_v8"] - q\n',
    '            forecasts.loc[mask, f"upper_{suffix}"] = forecasts.loc[mask, "raw_upper_v8"] + q\n',
    '            covered = ((rows["actual"] >= rows["raw_lower"]-q) & (rows["actual"] <= rows["raw_upper"]+q)).astype(float)\n',
    '            width = (rows["raw_upper"] - rows["raw_lower"] + 2*q).clip(lower=0)\n',
    '            interval_score = width + (2.0/max(1e-9,1.0-float(coverage))) * ((rows["raw_lower"]-q-rows["actual"]).clip(lower=0) + (rows["actual"]-(rows["raw_upper"]+q)).clip(lower=0))\n',
    '            latest_settle = rows["settlement_time_utc"].dropna().max() if "settlement_time_utc" in rows else pd.NaT\n',
    '            cutoff = pd.to_datetime(cutoff_utc, errors="coerce", utc=True)\n',
    '            age = int(max(0,(cutoff-latest_settle).total_seconds()//3600)) if pd.notna(cutoff) and pd.notna(latest_settle) else None\n',
    '            metadata.append({"horizon_hours": horizon, "target_coverage": float(coverage), "achieved_rolling_coverage": float(covered.mean()), "sample_count": int(len(rows)), "interval_width": float(width.mean()), "interval_score": float(interval_score.mean()), "calibration_age": age, "fallback_level": fallback, "status": "CALIBRATED", "nonconformity_quantile": q, "alpha": alpha})\n',
    '    # Enforce nesting and ordering without touching raw paths.\n',
    '    for lower_name, upper_name in (("lower_80","upper_80"),("lower_90","upper_90"),("lower_95","upper_95")):\n',
    '        if lower_name in forecasts and upper_name in forecasts:\n',
    '            lo = np.minimum(forecasts[lower_name], forecasts[upper_name]); hi = np.maximum(forecasts[lower_name], forecasts[upper_name]); forecasts[lower_name], forecasts[upper_name] = lo, hi\n',
    '    if all(c in forecasts for c in ("lower_80","lower_90","lower_95")):\n',
    '        forecasts["lower_90"] = np.minimum(forecasts["lower_90"], forecasts["lower_80"]); forecasts["lower_95"] = np.minimum(forecasts["lower_95"], forecasts["lower_90"])\n',
    '    if all(c in forecasts for c in ("upper_80","upper_90","upper_95")):\n',
    '        forecasts["upper_90"] = np.maximum(forecasts["upper_90"], forecasts["upper_80"]); forecasts["upper_95"] = np.maximum(forecasts["upper_95"], forecasts["upper_90"])\n',
    '    forecasts["v8_calibration_version"] = V8_CALIBRATION_VERSION\n',
    '    forecasts["v8_shadow_only"] = True\n',
    '    return forecasts.reset_index(drop=True), pd.DataFrame(metadata)\n',
    '\n',
    '\n',
    'def update_adaptive_conformal_alpha(\n',
    '    previous: Mapping[str, Any] | None,\n',
    '    *,\n',
    '    horizon_hours: int,\n',
    '    miss: bool,\n',
    '    target_coverage: float = 0.90,\n',
    '    learning_rate: float = 0.01,\n',
    '    alpha_min: float = 0.01,\n',
    '    alpha_max: float = 0.40,\n',
    '    confirmed_drift: bool = False,\n',
    ') -> dict[str, Any]:\n',
    '    """Bounded settlement-only alpha update; misses widen subsequent bands."""\n',
    '    previous = dict(previous or {})\n',
    '    key = str(int(horizon_hours)); current = previous.get(key) if isinstance(previous.get(key), Mapping) else {}\n',
    '    alpha_before = float(current.get("alpha", 1.0-float(target_coverage)))\n',
    '    lr = min(.05, max(.0001, float(learning_rate)))\n',
    '    # A miss lowers alpha -> higher effective coverage -> wider future interval.\n',
    '    alpha_after = alpha_before + lr * ((0.0 if miss else 1.0) - float(target_coverage))\n',
    '    if confirmed_drift:\n',
    '        alpha_after = .5 * alpha_after + .5 * (1.0-float(target_coverage))\n',
    '    alpha_after = float(min(alpha_max, max(alpha_min, alpha_after)))\n',
    '    updated = dict(previous)\n',
    '    updated[key] = {"alpha": alpha_after, "target_coverage": float(target_coverage), "updates": int(current.get("updates",0))+1, "misses": int(current.get("misses",0))+int(bool(miss)), "learning_rate": lr, "confirmed_drift": bool(confirmed_drift)}\n',
    '    return {"state": updated, "horizon_hours": int(horizon_hours), "alpha_before": alpha_before, "alpha_after": alpha_after, "miss": bool(miss), "learning_rate": lr, "version": V8_CALIBRATION_VERSION}\n',
]
