"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    metric_decision = str(scores.get("Decision") or "NO TRADE").upper()\n',
    '    tradeability = direction if direction in {"BUY", "SELL"} and metric_decision in _ALLOWED_FULL_METRIC_DECISIONS else "WAIT"\n',
    '    blockers = (\n',
    '        []\n',
    '        if tradeability in {"BUY", "SELL"}\n',
    '        else ["Full Metric direction is WAIT" if direction == "WAIT" else f"Full Metric decision is {metric_decision}"]\n',
    '    )\n',
    '\n',
    '    shared = dict(legacy_shared or {})\n',
    '    regime = dict(shared.get("regime") or {})\n',
    '    reliability = dict(shared.get("reliability") or shared.get("reliability_calibration") or {})\n',
    '    nlp = dict(shared.get("nlp") or {})\n',
    '    data_mining = dict(shared.get("data_mining") or {})\n',
    '    powerbi = dict(shared.get("powerbi") or {})\n',
    '    reliability_score = _num(reliability.get("score"), None)\n',
    '    if reliability_score is not None and reliability_score <= 1:\n',
    '        reliability_score *= 100.0\n',
    '    priority = _build_priority_table(\n',
    '        history,\n',
    '        latest_completed_h1_time=latest_time if pd.notna(latest_time) else None,\n',
    '        confirmation_table=confirmation_table,\n',
    '        data_quality_status=data_quality_status,\n',
    '        default_reliability=reliability_score,\n',
    '    )\n',
    '    top_two = _top_two_daily_candidates(priority)\n',
    '\n',
    '    reverse_history_raw = metric_result.get("history_by_factor") or {}\n',
    '    reverse_history = (\n',
    '        {str(name): _records(table) for name, table in reverse_history_raw.items()}\n',
    '        if isinstance(reverse_history_raw, Mapping)\n',
    '        else {}\n',
    '    )\n',
    '\n',
    '    snapshot = {\n',
    '        "symbol": "EURUSD",\n',
    '        "timeframe": "H1",\n',
    '        "latest_completed_h1_time": latest_time.isoformat() if pd.notna(latest_time) else None,\n',
    '        "last_close": _num(metrics.get("close"), _num(current_history.get("Close"))),\n',
    '        "current_major_regime": regime.get("current") or regime.get("major_regime") or "UNKNOWN",\n',
    '        "regime_start_time": regime.get("regime_start_time") or regime.get("start_time"),\n',
    '        "regime_age": regime.get("age_hours") or regime.get("regime_age"),\n',
    '        "regime_reliability": reliability_score if reliability_score is not None else regime.get("reliability"),\n',
    '        "master_score": _num(scores.get("Master /10"), 0.0),\n',
    '        "entry_score": _num(scores.get("Entry /10"), 0.0),\n',
    '        "buy_score": _num(scores.get("BUY Score"), 0.0),\n',
    '        "sell_score": _num(scores.get("SELL Score"), 0.0),\n',
    '        "hold_safety": _num(scores.get("Hold /10"), 0.0),\n',
    '        "tp_quality": _num(scores.get("TP /10"), 0.0),\n',
    '        "exit_risk": _num(scores.get("Exit Risk /10"), 10.0),\n',
    '        "pullback_readiness": (_num(metrics.get("pullback_readiness"), 0.0) or 0.0) / 10.0,\n',
    '        "trend_capacity_remaining": (100.0 - (_num(metrics.get("trend_capacity_used"), 100.0) or 100.0)) / 10.0,\n',
    '        "m1_confirmation": (_num(metrics.get("m1_confirm"), 0.0) or 0.0) / 10.0,\n',
    '        "m1_timing_status": "CONFIRM" if (_num(metrics.get("m1_confirm"), 0.0) or 0.0) >= 50 else "WAIT FOR CONFIRMATION",\n',
    '        "full_metric_direction": direction,\n',
    '        "full_metric_decision_label": metric_decision,\n',
    '        "tradeability_decision": tradeability,\n',
    '        "blocking_reasons": blockers,\n',
    '        "uncertainty": None,\n',
    '        "error_estimate": None,\n',
    '        "prediction_reliability": reliability_score,\n',
    '        "full_metric_current_row": {**current_history, **{k: _json_scalar(v) for k, v in scores.items()}},\n',
    '        "full_metric_history": _records(history.drop(columns=["_canonical_time"], errors="ignore")),\n',
    '        "reverse_10_current": _records(metric_result.get("reverse10")),\n',
    '        "reverse_10_history": reverse_history,\n',
    '        "canonical_priority_table": _records(priority.drop(columns=["_canonical_time"], errors="ignore")),\n',
    '        "top_two_daily_candidates": top_two,\n',
    '        "research_confirmation": data_mining,\n',
    '        "nlp_confirmation": nlp,\n',
    '        "knn_confirmation": {\n',
    '            "source": "existing KNN columns",\n',
    '            "available": bool(priority["KNN Score"].notna().any()) if not priority.empty else False,\n',
    '        },\n',
    '        "greedy_confirmation": {\n',
    '            "source": "existing Greedy columns",\n',
    '            "available": bool(priority["Greedy Score"].notna().any()) if not priority.empty else False,\n',
    '        },\n',
    '        "powerbi_confirmation": powerbi,\n',
    '    }\n',
    '    return {"snapshot": snapshot, "priority_table": priority, "top_two_daily_candidates": top_two}\n',
    '\n',
    '\n',
    'def _stamp_records(records: list[dict[str, Any]], identity: Mapping[str, Any]) -> list[dict[str, Any]]:\n',
    '    stamped: list[dict[str, Any]] = []\n',
    '    for row in records:\n',
    '        item = _json_record(row)\n',
    '        item.update(identity)\n',
    '        stamped.append(item)\n',
    '    return stamped\n',
    '\n',
    '\n',
    '\n',
    'def apply_canonical_confirmations(\n',
    '    authority: Mapping[str, Any], canonical_payload: Mapping[str, Any]\n',
    ') -> Dict[str, Any]:\n',
    '    """Apply validated downstream gates to the current Full Metric candidate.\n',
    '\n',
    '    The rank base and direction remain unchanged.  This second pass exists\n',
    '    because expected value, calibrated reliability, drift and NLP conflict are\n',
    '    available only after the existing decision-product confirmation engine has\n',
    '    completed. Historical rows without causal confirmation remain WATCH rather\n',
    "    than being upgraded with today's information.\n",
    '    """\n',
    '    result = dict(authority or {})\n',
    '    table = result.get("priority_table")\n',
    '    if not isinstance(table, pd.DataFrame) or table.empty:\n',
    '        return result\n',
    '    out = table.copy(deep=False)\n',
    '    latest = pd.to_datetime(\n',
    '        canonical_payload.get("latest_completed_candle_time"), utc=True, errors="coerce"\n',
    '    )\n',
    '    times = pd.to_datetime(_series_or_default(out, "Time", pd.NaT), utc=True, errors="coerce")\n',
    '    current_mask = times.eq(latest) if pd.notna(latest) else pd.Series(False, index=out.index)\n',
    '    final = canonical_payload.get("final_decision") or {}\n',
    '    reliability = canonical_payload.get("reliability") or {}\n',
    '    nlp = canonical_payload.get("nlp") or {}\n',
    '    quality = canonical_payload.get("data_quality") or {}\n',
    '    reliability_score = _num(reliability.get("score"), None)\n',
    '    expected_value = _num(final.get("expected_value"), None)\n',
    '    final_direction = _direction(final.get("directional_market_view"))\n',
    '    final_tradeability = _direction(final.get("tradeability_decision") or final.get("final_decision"))\n',
    '    conflict = str(nlp.get("conflict_level") or "NONE").upper()\n',
    '    quality_status = str(quality.get("status") or "UNKNOWN").upper()\n',
    '\n',
    '    if current_mask.any():\n',
    '        if reliability_score is not None:\n',
    '            out.loc[current_mask, "Reliability %"] = reliability_score\n',
    '        if expected_value is not None:\n',
    '            out.loc[current_mask, "Expected Value"] = expected_value\n',
    '        out.loc[current_mask, "NLP Confirmation"] = conflict\n',
    '        out.loc[current_mask, "Conflict Status"] = conflict\n',
    '        row_direction = out.loc[current_mask, "Direction"].astype(str).str.upper()\n',
    '        metric_allowed = out.loc[current_mask, "Full Metric Decision"].isin(_ALLOWED_FULL_METRIC_DECISIONS)\n',
    '        qualified = (\n',
    '            row_direction.isin(["BUY", "SELL"])\n',
    '            & metric_allowed\n',
    '            & row_direction.eq(final_direction)\n',
    '            & row_direction.eq(final_tradeability)\n',
    '            & (reliability_score is not None and reliability_score >= 45)\n',
    '            & (expected_value is not None and expected_value > 0)\n',
    '            & (not quality_status.startswith("FAIL"))\n',
    '            & (conflict not in {"CRITICAL", "SEVERE"})\n',
    '        )\n',
    '        if bool(qualified.any()):\n',
    '            out.loc[current_mask, "Qualification Status"] = "QUALIFIED ENTRY"\n',
    '            out.loc[current_mask, "Less Risky Bias"] = row_direction\n',
    '            out.loc[current_mask, "Blocking Reason"] = "Passed Full Metric and validated confirmation safety gates"\n',
    '        else:\n',
    '            blockers = list(final.get("blocking_reasons") or [])\n',
    '            if expected_value is None:\n',
    '                blockers.append("Expected value confirmation unavailable")\n',
    '            elif expected_value <= 0:\n',
    '                blockers.append("Expected value is not positive after cost")\n',
    '            if reliability_score is None:\n',
    '                blockers.append("Reliability confirmation unavailable")\n',
    '            elif reliability_score < 45:\n',
    '                blockers.append("Reliability below existing safe range")\n',
    '            if final_tradeability == "WAIT" and final_direction in {"BUY", "SELL"}:\n',
    '                blockers.append("Directional setup is currently blocked; tradeability is WAIT")\n',
    '            if quality_status.startswith("FAIL"):\n',
    '                blockers.append(f"Data quality is {quality_status}")\n',
    '            if conflict in {"CRITICAL", "SEVERE"}:\n',
    '                blockers.append(f"NLP conflict is {conflict}")\n',
    '            out.loc[current_mask, "Qualification Status"] = np.where(\n',
    '                row_direction.isin(["BUY", "SELL"]), "WATCH CANDIDATE", "NO ENTRY / WAIT"\n',
    '            )\n',
    '            out.loc[current_mask, "Less Risky Bias"] = "WAIT"\n',
    '            out.loc[current_mask, "Blocking Reason"] = "; ".join(dict.fromkeys(blockers)) or "Confirmation gate not passed"\n',
    '\n',
    '    status_order = {"QUALIFIED ENTRY": 0, "WATCH CANDIDATE": 1, "NO ENTRY / WAIT": 2, "NO ENTRY": 2}\n',
    '    out["_status_order"] = out["Qualification Status"].map(status_order).fillna(3)\n',
    '    out["_conflict_order"] = out["Conflict Status"].astype(str).str.upper().map(\n',
    '        lambda text: 3 if "CRITICAL" in text else 2 if "SEVERE" in text else 1 if "CONFLICT" in text else 0\n',
    '    )\n',
    '    out["_ev_order"] = pd.to_numeric(out["Expected Value"], errors="coerce").fillna(-np.inf)\n',
    '    out["_reliability_order"] = pd.to_numeric(out["Reliability %"], errors="coerce").fillna(0)\n',
    '    out = out.sort_values(\n',
    '        ["_status_order", "Priority Score", "_ev_order", "_reliability_order",\n',
    '         "_conflict_order", "Exit Risk /10", "Current Day", "Time"],\n',
    '        ascending=[True, False, False, False, True, True, False, False],\n',
    '        na_position="last", kind="stable",\n',
    '    ).drop(columns=["_status_order", "_conflict_order", "_ev_order", "_reliability_order"], errors="ignore").reset_index(drop=True)\n',
    '    out["Priority Rank"] = np.arange(1, len(out) + 1)\n',
    '    out["priority rank"] = out["Priority Rank"]\n',
    '    top_two = _top_two_daily_candidates(out)\n',
    '    result["priority_table"] = out\n',
    '    result["top_two_daily_candidates"] = top_two\n',
    '    snapshot = dict(result.get("snapshot") or {})\n',
    '    snapshot["canonical_priority_table"] = _records(out.drop(columns=["_canonical_time"], errors="ignore"))\n',
    '    snapshot["top_two_daily_candidates"] = top_two\n',
    '    result["snapshot"] = snapshot\n',
    '    return result\n',
    '\n',
    'def enrich_canonical_payload(payload: Dict[str, Any], authority: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    """Attach protected Full Metric fields and one canonical identity."""\n',
    '    snapshot = dict(authority.get("snapshot") or {})\n',
    '    identity = {\n',
    '        "run_id": payload.get("run_id"),\n',
    '        "calculation_generation": payload.get("calculation_generation"),\n',
    '        "data_signature": payload.get("data_signature"),\n',
    '        "latest_completed_h1_time": payload.get("latest_completed_candle_time"),\n',
    '        "latest_completed_candle_time": payload.get("latest_completed_candle_time"),\n',
    '        "symbol": payload.get("symbol"),\n',
    '        "timeframe": payload.get("timeframe"),\n',
    '        "source": payload.get("source"),\n',
    '    }\n',
    '    snapshot.update(identity)\n',
    '    snapshot["calculated_at"] = payload.get("created_at")\n',
    '    final = dict(payload.get("final_decision") or {})\n',
    '    snapshot["tradeability_decision"] = final.get(\n',
    '        "tradeability_decision", snapshot.get("tradeability_decision", "WAIT")\n',
    '    )\n',
    '    snapshot["blocking_reasons"] = final.get("blocking_reasons", snapshot.get("blocking_reasons", []))\n',
    '    snapshot["uncertainty"] = final.get("uncertainty_pct")\n',
    '    snapshot["error_estimate"] = final.get("error_estimate_pct")\n',
    '    snapshot["prediction_reliability"] = (payload.get("reliability") or {}).get("score")\n',
    '\n',
    '    priority_records = _stamp_records(_records(authority.get("priority_table")), identity)\n',
    '    top_two = _stamp_records(list(authority.get("top_two_daily_candidates") or []), identity)\n',
    '    history_records = _stamp_records(list(snapshot.get("full_metric_history") or []), identity)\n',
    '    reverse_current = _stamp_records(list(snapshot.get("reverse_10_current") or []), identity)\n',
    '    reverse_history = {\n',
    '        str(name): _stamp_records(list(rows or []), identity)\n',
    '        for name, rows in dict(snapshot.get("reverse_10_history") or {}).items()\n',
    '    }\n',
    '    snapshot["full_metric_history"] = history_records\n',
    '    snapshot["reverse_10_current"] = reverse_current\n',
    '    snapshot["reverse_10_history"] = reverse_history\n',
    '    snapshot["canonical_priority_table"] = priority_records\n',
    '    snapshot["top_two_daily_candidates"] = top_two\n',
    '\n',
    '    payload.update(snapshot)\n',
    '    payload["full_metric_snapshot"] = snapshot\n',
    '    payload["canonical_priority_table"] = priority_records\n',
    '    payload["priority_table"] = priority_records\n',
    '    payload["top_two_daily_candidates"] = top_two\n',
    '    # Stable canonical aliases let every route consume the same generation.\n',
    '    payload["current_regime"] = (payload.get("regime") or {}).get("major_regime") or snapshot.get("current_major_regime")\n',
    '    payload["alpha"] = (payload.get("regime") or {}).get("alpha")\n',
    '    payload["delta"] = (payload.get("regime") or {}).get("delta")\n',
    '    payload["powerbi_projection_result"] = payload.get("forecasts") or payload.get("powerbi_confirmation") or {}\n',
    '    payload["finder_priorities"] = priority_records\n',
    '    payload["nlp_result"] = payload.get("nlp") or snapshot.get("nlp_confirmation") or {}\n',
    '    payload["research_confirmation_result"] = payload.get("research_confirmation") or snapshot.get("research_confirmation") or {}\n',
    '    payload["conflict_state"] = (payload.get("nlp") or {}).get("conflict_level", "NONE")\n',
    '    payload["counter_trend_state"] = (payload.get("final_decision") or {}).get("counter_trend_state", "NONE")\n',
    '    payload["data_quality_state"] = payload.get("data_quality") or {}\n',
    '    payload["current_actionable_decision"] = (payload.get("final_decision") or {}).get("tradeability_decision", "WAIT")\n',
    '    payload["opportunity_candidates"] = top_two\n',
    '    payload["source_freshness_metadata"] = {**identity, "created_at": payload.get("created_at"), "expires_at": payload.get("expires_at")}\n',
    '    payload.setdefault("metadata", {})["primary_calculation_authority"] = "Full Metric Detail + History"\n',
    '    payload["metadata"]["confirmation_components_cannot_reverse_direction"] = True\n',
    '    payload["metadata"]["m1_role"] = "entry timing and confirmation only"\n',
    '    return payload\n',
]
