"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '                    frame[name] = pd.to_numeric(p[col], errors="coerce").reindex(frame.index, method="ffill", tolerance=pd.Timedelta(hours=2))\n',
    '            regime_col = next((c for c in ("Major Regime", "Regime", "current regime") if c in p), None)\n',
    '            if regime_col:\n',
    '                frame["regime_env"] = p[regime_col].astype(str).str.upper().reindex(frame.index, method="ffill", tolerance=pd.Timedelta(hours=2))\n',
    '    if "regime_env" not in frame:\n',
    '        frame["regime_env"] = np.where(frame["momentum_3h"] > 0, "BULL", np.where(frame["momentum_3h"] < 0, "BEAR", "RANGE_COMPRESSION"))\n',
    '    features = [c for c in ("return_1h", "range", "momentum_3h", "volatility_12h", "master", "entry", "exit_risk", "buy_score", "sell_score") if c in frame]\n',
    '    environment_masks: Dict[str, pd.Series] = {}\n',
    '    for value in ("ASIA", "LONDON", "LONDON_NY_OVERLAP"):\n',
    '        environment_masks[value] = frame["session"].eq(value)\n',
    '    for value in ("LOW_VOL", "NORMAL_VOL", "HIGH_VOL"):\n',
    '        environment_masks[value] = frame["vol_env"].eq(value)\n',
    '    for value in ("EARLIER", "RECENT"):\n',
    '        environment_masks[value] = frame["time_env"].eq(value)\n',
    '    regime_text = frame["regime_env"].astype(str).str.upper()\n',
    '    environment_masks["BULL_REGIME"] = regime_text.str.contains("BULL")\n',
    '    environment_masks["BEAR_REGIME"] = regime_text.str.contains("BEAR")\n',
    '    environment_masks["RANGE_COMPRESSION"] = regime_text.str.contains("RANGE|COMPRESS", regex=True)\n',
    '    feature_results: Dict[str, Any] = {}\n',
    '    scores: list[float] = []\n',
    '    for feature in features:\n',
    '        effects: list[float] = []\n',
    '        labels: list[str] = []\n',
    '        for label, mask in environment_masks.items():\n',
    '            corr = _spearman(frame.loc[mask, feature], frame.loc[mask, "target"])\n',
    '            if corr is not None:\n',
    '                effects.append(corr)\n',
    '                labels.append(label)\n',
    '        if len(effects) < 3:\n',
    '            continue\n',
    '        arr = np.asarray(effects)\n',
    '        nonzero = arr[np.abs(arr) >= .02]\n',
    '        sign_consistency = float(max(np.mean(nonzero >= 0), np.mean(nonzero <= 0))) if len(nonzero) else 0.5\n',
    '        dispersion = float(np.std(arr))\n',
    '        recent = effects[labels.index("RECENT")] if "RECENT" in labels else None\n',
    '        earlier = effects[labels.index("EARLIER")] if "EARLIER" in labels else None\n',
    '        recent_stability = 1.0 - min(1.0, abs(recent - earlier) / .5) if recent is not None and earlier is not None else 0.5\n',
    '        rank_consistency = max(0.0, 1.0 - dispersion / .35)\n',
    '        score = _clip(0.45 * sign_consistency + 0.30 * rank_consistency + 0.25 * recent_stability, 0.0, 1.0, .5)\n',
    '        feature_results[feature] = {\n',
    '            "effect_sign_consistency": sign_consistency, "rank_consistency": rank_consistency,\n',
    '            "environment_count": len(effects), "correlation_dispersion": dispersion,\n',
    '            "recent_vs_historical_stability": recent_stability, "invariance_reliability": score,\n',
    '            "effects": dict(zip(labels, effects)),\n',
    '        }\n',
    '        scores.append(score)\n',
    '    overall = float(np.mean(scores)) if scores else .5\n',
    '    support = _clip(.75 + .30 * overall, .75, 1.05, 1.0)\n',
    '    warning = "STABLE" if overall >= .70 else "WATCH" if overall >= .52 else "UNSTABLE"\n',
    '    return {\n',
    '        "version": "invariance_v1", "invariance_score": overall,\n',
    '        "stable_environment_count": int(sum(1 for x in feature_results.values() if x["invariance_reliability"] >= .65)),\n',
    '        "effect_sign_consistency": float(np.mean([x["effect_sign_consistency"] for x in feature_results.values()])) if feature_results else None,\n',
    '        "feature_stability_warning": warning, "invariant_support_weight": support,\n',
    '        "features": feature_results, "causality_claim": "NONE — robustness test only",\n',
    '    }\n',
    '\n',
    '\n',
    'def build_event_intensity(periodicity_frame: pd.DataFrame, canonical: Mapping[str, Any], settled: Optional[pd.DataFrame] = None) -> Dict[str, Any]:\n',
    '    if not isinstance(periodicity_frame, pd.DataFrame) or periodicity_frame.empty:\n',
    '        return {"version": "event_intensity_v1", "background_event_intensity": 0.0, "self_excited_intensity": 0.0, "total_event_intensity": 0.0, "event_decay_hours": 6.0, "next_1h_shock_probability": 0.0, "next_3h_shock_probability": 0.0, "event_cluster_level": "LOW"}\n',
    '    recent = periodicity_frame.tail(24 * 14)\n',
    '    candle_event = recent["periodicity_normalized_range"].abs().gt(2.5)\n',
    '    return_event = recent["periodicity_normalized_return"].abs().gt(2.5)\n',
    '    residual_event = recent["periodicity_normalized_residual"].abs().gt(2.5)\n',
    '    events = (candle_event | return_event | residual_event).astype(float)\n',
    '    transition = _prob(_mapping(canonical.get("regime")).get("transition_probability_3h"), 0.0) or 0.0\n',
    '    nlp = _mapping(canonical.get("nlp"))\n',
    '    news_boost = 1.0 if str(nlp.get("importance") or nlp.get("impact") or "").upper() in {"HIGH", "CRITICAL"} else 0.0\n',
    '    historical_event_boost = 0.0\n',
    '    if isinstance(settled, pd.DataFrame) and not settled.empty and "event_risk_status" in settled.columns:\n',
    '        recent_settled = settled.copy(deep=False)\n',
    '        order = pd.to_datetime(_series(recent_settled, "target_time", pd.NaT), errors="coerce", utc=True)\n',
    '        recent_settled = recent_settled.assign(__time=order).sort_values("__time").tail(336)\n',
    '        event_flags = recent_settled["event_risk_status"].astype(str).str.upper().str.contains("HIGH|CRITICAL|NEWS", regex=True, na=False).astype(float)\n',
    '        if len(event_flags):\n',
    '            event_ages = np.arange(len(event_flags) - 1, -1, -1, dtype=float)\n',
    '            event_weights = np.exp(-math.log(2.0) * event_ages / 6.0)\n',
    '            historical_event_boost = float(np.dot(event_flags.to_numpy(dtype=float), event_weights) / max(event_weights.sum(), 1e-9))\n',
    '    decay_hours = 6.0\n',
    '    ages = np.arange(len(events) - 1, -1, -1, dtype=float)\n',
    '    weights = np.exp(-math.log(2.0) * ages / decay_hours)\n',
    '    background = float(events.mean()) if len(events) else 0.0\n',
    '    self_excited = float(np.dot(events.to_numpy(dtype=float), weights) / max(weights.sum(), 1e-9))\n',
    '    total = max(0.0, background + 1.8 * self_excited + .35 * transition + .20 * news_boost + .35 * historical_event_boost)\n',
    '    p1 = float(1.0 - math.exp(-total))\n',
    '    p3 = float(1.0 - math.exp(-3.0 * total))\n',
    '    level = "LOW" if p1 < .20 else "MEDIUM" if p1 < .40 else "HIGH" if p1 < .65 else "CRITICAL"\n',
    '    return {\n',
    '        "version": "event_intensity_v1", "background_event_intensity": background,\n',
    '        "self_excited_intensity": self_excited, "total_event_intensity": total,\n',
    '        "event_decay_hours": decay_hours, "next_1h_shock_probability": p1,\n',
    '        "next_3h_shock_probability": p3, "event_cluster_level": level,\n',
    '        "input_event_count": int(events.sum()), "historical_news_event_intensity": historical_event_boost,\n',
    '    }\n',
    '\n',
    '\n',
    'def build_robust_expectancy(\n',
    '    canonical: Mapping[str, Any], selective: Mapping[str, Any], evt: Mapping[str, Any], event_intensity: Mapping[str, Any], proper: Mapping[str, Any], competing: Mapping[str, Any], periodicity: Optional[Mapping[str, Any]] = None\n',
    ') -> Dict[str, Any]:\n',
    '    final = _mapping(canonical.get("final_decision"))\n',
    '    risk = _mapping(canonical.get("risk"))\n',
    '    ordinary = _finite(final.get("expected_value"), None)\n',
    '    if ordinary is not None and abs(ordinary) < .05:\n',
    '        ordinary /= PIP\n',
    '    selected = _mapping(competing.get("selected"))\n',
    '    horizon = int(_finite(final.get("selected_horizon"), 3) or 3)\n',
    '    hrow = _mapping(_mapping(selected.get("horizons")).get(f"{horizon if horizon in RISK_HORIZONS else 3}h"))\n',
    '    p_tp = _prob(hrow.get("tp_first_probability"), None)\n',
    '    p_sl = _prob(hrow.get("sl_first_probability"), None)\n',
    '    gain = abs(_finite(risk.get("expected_favorable_movement"), 0.0) or 0.0)\n',
    '    loss = abs(_finite(risk.get("expected_adverse_movement"), 0.0) or 0.0)\n',
    '    if gain < .05:\n',
    '        gain /= PIP\n',
    '    if loss < .05:\n',
    '        loss /= PIP\n',
    '    cost = abs(_finite(risk.get("estimated_cost"), 1.0) or 1.0)\n',
    '    if cost < .05:\n',
    '        cost /= PIP\n',
    '    if ordinary is None and p_tp is not None and p_sl is not None:\n',
    '        ordinary = p_tp * gain - p_sl * loss - cost\n',
    '    ordinary = float(ordinary or 0.0)\n',
    '    n = int(hrow.get("effective_sample_count") or proper.get("sample_count") or 0)\n',
    '    drift = _prob(_mapping(canonical.get("drift")).get("severity"), 0.0) or 0.0\n',
    '    calibration = proper.get("path_calibration")\n',
    '    calibration_penalty = abs(float(calibration) - .80) if calibration is not None else .25\n',
    '    evt_penalty = _prob(evt.get("extreme_adverse_probability"), 0.0) or 0.0\n',
    '    event_penalty = _prob(event_intensity.get("next_1h_shock_probability"), 0.0) or 0.0\n',
    '    residual_shift = min(1.0, abs(float(_mapping(periodicity).get("periodicity_normalized_residual") or 0.0)) / 4.0)\n',
    '    skill_penalty = max(0.0, -float(proper.get("skill_vs_naive") or 0.0))\n',
    '    low_sample = min(1.0, 30.0 / max(n, 1))\n',
    '    ambiguity = _clip(.08 + .28 * low_sample + .16 * drift + .16 * calibration_penalty + .10 * evt_penalty + .14 * event_penalty + .05 * residual_shift + .03 * min(1.0, skill_penalty), .05, .85, .35)\n',
    '    downside_scale = max(loss, abs(ordinary), 1.0)\n',
    '    robust = ordinary - ambiguity * downside_scale\n',
    '    safety_buffer = max(0.5, .15 * cost)\n',
    '    passed = robust > cost + safety_buffer\n',
    '    return {\n',
    '        "version": "robust_expectancy_v1", "ordinary_expected_value": ordinary,\n',
    '        "robust_expected_value": robust, "ambiguity_radius": ambiguity,\n',
    '        "robustness_gap": ordinary - robust, "robust_entry_pass": bool(passed),\n',
    '        "cost_pips": cost, "safety_buffer_pips": safety_buffer, "effective_sample_count": n,\n',
    '        "residual_shift_penalty": residual_shift, "skill_penalty": skill_penalty,\n',
    '    }\n',
    '\n',
    '\n',
    'def build_risk_multiplier(\n',
    '    canonical: Mapping[str, Any], competing: Mapping[str, Any], evt: Mapping[str, Any], confidence: Mapping[str, Any], robust: Mapping[str, Any]\n',
    ') -> Dict[str, Any]:\n',
    '    final = _mapping(canonical.get("final_decision"))\n',
    '    risk = _mapping(canonical.get("risk"))\n',
    '    horizon = int(_finite(final.get("selected_horizon"), 3) or 3)\n',
    '    selected = _mapping(competing.get("selected"))\n',
    '    hrow = _mapping(_mapping(selected.get("horizons")).get(f"{horizon if horizon in RISK_HORIZONS else 3}h"))\n',
    '    p = _prob(hrow.get("tp_first_probability"), 0.0) or 0.0\n',
    '    q = _prob(hrow.get("sl_first_probability"), 0.0) or 0.0\n',
    '    gain = abs(_finite(risk.get("expected_favorable_movement"), 0.0) or 0.0)\n',
    '    loss = abs(_finite(risk.get("expected_adverse_movement"), 0.0) or 0.0)\n',
    '    if gain < .05:\n',
    '        gain /= PIP\n',
    '    if loss < .05:\n',
    '        loss /= PIP\n',
    '    b = gain / max(loss, 1e-9)\n',
    '    raw = (b * p - q) / max(b, 1e-9) if b > 0 else 0.0\n',
    '    n = int(hrow.get("effective_sample_count") or 0)\n',
    '    trust = str(confidence.get("trust_status") or "INSUFFICIENT_DATA")\n',
    '    reasons: list[str] = []\n',
    '    multiplier = max(0.0, raw)\n',
    '    if robust.get("robust_expected_value", 0.0) <= 0:\n',
    '        reasons.append("NO_POSITIVE_ROBUST_EXPECTANCY")\n',
    '    if n < 20:\n',
    '        reasons.append("INSUFFICIENT_HISTORY")\n',
    '    if trust in {"DEGRADED", "UNSTABLE", "INSUFFICIENT_DATA"}:\n',
    '        reasons.append("CALIBRATION_NOT_TRUSTED")\n',
    '    if bool(evt.get("extreme_risk_block")):\n',
    '        reasons.append("EXTREME_RISK_BLOCK")\n',
    '    drawdown = abs(_finite(risk.get("current_drawdown") or risk.get("drawdown_pct") or _mapping(canonical.get("portfolio")).get("current_drawdown_pct"), 0.0) or 0.0)\n',
    '    if drawdown > 1.0:\n',
    '        drawdown /= 100.0\n',
    '    if drawdown >= 0.10:\n',
    '        reasons.append("DRAWDOWN_SAFETY_BLOCK")\n',
    '    if reasons:\n',
    '        multiplier = 0.0\n',
    '    else:\n',
    '        evt_penalty = 1.0 - min(.75, _prob(evt.get("extreme_adverse_probability"), 0.0) or 0.0)\n',
    '        multiplier *= evt_penalty * max(0.25, 1.0 - 2.0 * drawdown)\n',
    '    constrained = _clip(multiplier, 0.0, .25, 0.0)\n',
    '    return {\n',
    '        "version": "risk_multiplier_v1", "raw_kelly_fraction": raw,\n',
    '        "risk_constrained_fraction": constrained, "display_risk_multiplier": constrained,\n',
    '        "position_risk_warning": "OK" if constrained > 0 else (reasons[0] if reasons else "ZERO_MULTIPLIER"),\n',
    '        "safety_reasons": reasons, "current_drawdown_fraction": drawdown, "leverage_recommendation": False, "automatic_trading": False,\n',
    '    }\n',
    '\n',
    '\n',
    'def _adjust_powerbi_bundle(bundle: Any, result: Mapping[str, Any]) -> Any:\n',
    '    if not isinstance(bundle, Mapping):\n',
    '        return bundle\n',
    '    out = deepcopy(dict(bundle))\n',
    '    summary = dict(_mapping(out.get("summary")))\n',
    '    proper = _mapping(result.get("proper_scoring"))\n',
    '    evt = _mapping(result.get("evt_tail"))\n',
    '    events = _mapping(result.get("event_intensity"))\n',
    '    invariance = _mapping(result.get("invariance"))\n',
    '    old_rel = _finite(summary.get("reliability_pct"), None)\n',
    '    if old_rel is not None:\n',
    '        modifier = float(proper.get("reliability_modifier") or 1.0) * float(invariance.get("invariant_support_weight") or 1.0)\n',
    '        if str(events.get("event_cluster_level")) in {"HIGH", "CRITICAL"}:\n',
    '            modifier *= .92\n',
    '        if evt.get("extreme_risk_block"):\n',
    '            modifier *= .85\n',
    '        summary["pre_research_reliability_pct"] = old_rel\n',
    '        summary["reliability_pct"] = _clip(old_rel * modifier, 0.0, 100.0, old_rel)\n',
    '    summary.update({\n',
    '        "crps_skill_vs_naive": proper.get("skill_vs_naive"), "joint_energy_score": proper.get("joint_energy_score"),\n',
    '        "extreme_risk_warning": bool(evt.get("extreme_risk_block")), "event_cluster_level": events.get("event_cluster_level"),\n',
    '        "research_risk_stack_version": VERSION,\n',
    '    })\n',
    '    out["summary"] = summary\n',
    '    out["research_risk_adjustments"] = _json_safe({\n',
    '        "proper_scoring": proper, "evt_tail": evt, "event_intensity": events,\n',
    '        "invariance": invariance, "robust_expectancy": result.get("robust_expectancy"),\n',
    '    })\n',
    '    main = out.get("main")\n',
    '    if isinstance(main, pd.DataFrame) and not main.empty:\n',
    '        adjusted = main.copy(deep=False)\n',
    '        point_col = next((c for c in ("main_path", "main path", "central", "prediction") if c in adjusted), None)\n',
    '        lower_col = next((c for c in ("lower_band", "lower band", "lower") if c in adjusted), None)\n',
    '        upper_col = next((c for c in ("upper_band", "upper band", "upper") if c in adjusted), None)\n',
    '        widening = 1.0\n',
    '        if str(events.get("event_cluster_level")) == "HIGH":\n',
    '            widening *= 1.12\n',
    '        elif str(events.get("event_cluster_level")) == "CRITICAL":\n',
    '            widening *= 1.25\n',
    '        if evt.get("evt_sample_sufficient"):\n',
    '            widening *= 1.0 + min(.20, (_prob(evt.get("extreme_adverse_probability"), 0.0) or 0.0) * .25)\n',
    '        if point_col and lower_col and upper_col and widening > 1.0:\n',
    '            point = pd.to_numeric(adjusted[point_col], errors="coerce")\n',
    '            lower = pd.to_numeric(adjusted[lower_col], errors="coerce")\n',
    '            upper = pd.to_numeric(adjusted[upper_col], errors="coerce")\n',
    '            adjusted[lower_col] = point - (point - lower).abs() * widening\n',
    '            adjusted[upper_col] = point + (upper - point).abs() * widening\n',
    '        out["main"] = adjusted\n',
    '    # Existing path weights are never refit here. When validation weakens, they\n',
    '    # are conservatively shrunk a small distance toward equal weights so one\n',
    '    # path cannot dominate. The central path update is capped to 25% of the\n',
    '    # bounded reweighted consensus.\n',
    '    path_weights = out.get("path_weights")\n',
    '    if isinstance(path_weights, pd.DataFrame) and not path_weights.empty:\n',
    '        weight_frame = path_weights.copy(deep=False)\n',
    '        path_cols = [name for name in ("red", "yellow", "blue") if name in weight_frame.columns]\n',
    '        skill = min(float(proper.get("skill_vs_naive") or 0.0), float(proper.get("skill_vs_drift") or 0.0))\n',
    '        invariance_score = float(invariance.get("invariance_score") or 0.5)\n',
    '        shrink = 0.0\n',
    '        if skill < 0:\n',
    '            shrink += min(0.12, abs(skill) * 0.08)\n',
    '        shrink += max(0.0, 0.70 - invariance_score) * 0.15\n',
    '        if str(events.get("event_cluster_level")) in {"HIGH", "CRITICAL"}:\n',
    '            shrink += 0.05\n',
    '        if evt.get("extreme_risk_block"):\n',
    '            shrink += 0.08\n',
    '        shrink = _clip(shrink, 0.0, 0.25, 0.0)\n',
    '        if path_cols and shrink > 0:\n',
    '            numeric = weight_frame[path_cols].apply(pd.to_numeric, errors="coerce").fillna(0.0).clip(lower=0.0)\n',
    '            active = numeric.gt(0.0)\n',
    '            active_count = active.sum(axis=1).replace(0, np.nan)\n',
    '            equal = active.div(active_count, axis=0).fillna(0.0)\n',
    '            revised_numeric = numeric * (1.0 - shrink) + equal * shrink\n',
    '            totals = revised_numeric.sum(axis=1).replace(0, np.nan)\n',
    '            revised_numeric = revised_numeric.div(totals, axis=0).fillna(numeric)\n',
    '            for column in path_cols:\n',
    '                weight_frame[column] = revised_numeric[column]\n',
    '            out["path_weights"] = weight_frame\n',
    '            latest_weights = revised_numeric.iloc[-1].to_dict()\n',
    '            out["research_bounded_weights"] = {k: float(v) for k, v in latest_weights.items()}\n',
    '            out["research_weight_shrinkage"] = shrink\n',
    '            raw = out.get("raw")\n',
    '            main = out.get("main")\n',
    '            if isinstance(raw, pd.DataFrame) and isinstance(main, pd.DataFrame) and not raw.empty and not main.empty and "main_path" in main.columns:\n',
    '                raw_reset = raw.reset_index(drop=True)\n',
    '                main_reset = main.copy(deep=False).reset_index(drop=True)\n',
    '                length = min(len(raw_reset), len(main_reset), len(revised_numeric))\n',
    '                consensus = np.zeros(length, dtype=float)\n',
    '                valid_weight = np.zeros(length, dtype=float)\n',
    '                for column in path_cols:\n',
    '                    path_col = f"{column}_path"\n',
    '                    if path_col not in raw_reset.columns:\n',
    '                        continue\n',
    '                    values = pd.to_numeric(raw_reset.loc[: length - 1, path_col], errors="coerce").to_numpy(dtype=float)\n',
    '                    weights_arr = revised_numeric.loc[: length - 1, column].to_numpy(dtype=float)\n',
    '                    mask = np.isfinite(values)\n',
    '                    consensus[mask] += values[mask] * weights_arr[mask]\n',
    '                    valid_weight[mask] += weights_arr[mask]\n',
    '                old_main = pd.to_numeric(main_reset.loc[: length - 1, "main_path"], errors="coerce").to_numpy(dtype=float)\n',
    '                usable = valid_weight > 0\n',
    '                consensus[usable] = consensus[usable] / valid_weight[usable]\n',
    '                bounded = old_main.copy()\n',
    '                bounded[usable] = old_main[usable] * 0.75 + consensus[usable] * 0.25\n',
    '                if "lower_band" in main_reset.columns and "upper_band" in main_reset.columns:\n',
    '                    lower = pd.to_numeric(main_reset.loc[: length - 1, "lower_band"], errors="coerce").to_numpy(dtype=float)\n',
    '                    upper = pd.to_numeric(main_reset.loc[: length - 1, "upper_band"], errors="coerce").to_numpy(dtype=float)\n',
    '                    bounded = np.minimum(np.maximum(bounded, lower), upper)\n',
    '                main_reset.loc[: length - 1, "main_path"] = bounded\n',
    '                out["main"] = main_reset\n',
    '    return out\n',
    '\n',
    '\n',
    'def _current_priority(canonical: Mapping[str, Any], priority_table: Any) -> str:\n',
    '    priority = _mapping(canonical.get("priority"))\n',
    '    label = priority.get("label") or priority.get("rank")\n',
    '    if label not in (None, ""):\n',
    '        return _priority_class(label)\n',
    '    if isinstance(priority_table, pd.DataFrame) and not priority_table.empty:\n',
    '        row = priority_table.iloc[0]\n',
    '        for col in ("Priority Label", "priority label", "Priority Rank 1-14", "Priority Rank"):\n',
    '            if col in row:\n',
    '                return _priority_class(row[col])\n',
    '    return "UNKNOWN"\n',
    '\n',
    '\n',
    'def _enrich_table(table: Any, periodicity_frame: pd.DataFrame, result: Mapping[str, Any], latest_time: Any) -> pd.DataFrame:\n',
    '    if not isinstance(table, pd.DataFrame) or table.empty:\n',
    '        return pd.DataFrame()\n',
    '    out = table.copy(deep=False)\n',
    '    tcol = next((c for c in ("Time", "time", "DateTime", "timestamp", "Date") if c in out), None)\n',
    '    if tcol and isinstance(periodicity_frame, pd.DataFrame) and not periodicity_frame.empty:\n',
    '        times = pd.to_datetime(out[tcol], errors="coerce", utc=True)\n',
    '        lookup = periodicity_frame[["periodicity_normalized_range", "periodicity_normalized_return"]].copy()\n',
    '        out["Periodicity Norm Vol"] = times.map(lookup["periodicity_normalized_range"])\n',
    '    else:\n',
    '        out["Periodicity Norm Vol"] = np.nan\n',
    '    latest = pd.to_datetime(latest_time, errors="coerce", utc=True)\n',
    '    current_mask = pd.Series(False, index=out.index)\n',
    '    if tcol and pd.notna(latest):\n',
    '        current_mask = pd.to_datetime(out[tcol], errors="coerce", utc=True).eq(latest)\n',
    '    if not current_mask.any() and len(out):\n',
    '        current_mask.iloc[0] = True\n',
    '    proper = _mapping(result.get("proper_scoring"))\n',
    '    competing = _mapping(result.get("competing_risk"))\n',
    '    selected = _mapping(competing.get("selected"))\n',
    '    final = _mapping(result.get("current_summary"))\n',
    '    h = int(final.get("selected_horizon") or 3)\n',
    '    riskrow = _mapping(_mapping(selected.get("horizons")).get(f"{h if h in RISK_HORIZONS else 3}h"))\n',
    '    values = {\n',
    '        "CRPS": proper.get(f"crps_h{h}") or proper.get("mean_crps"),\n',
    '        "Energy Score": proper.get("joint_energy_score"),\n',
    '        "TP First %": None if riskrow.get("tp_first_probability") is None else float(riskrow["tp_first_probability"]) * 100.0,\n',
    '        "SL First %": None if riskrow.get("sl_first_probability") is None else float(riskrow["sl_first_probability"]) * 100.0,\n',
    '        "Confidence Sequence": _mapping(result.get("confidence_sequence")).get("trust_status"),\n',
    '        "Required Confidence %": _mapping(result.get("selective_prediction")).get("required_confidence_threshold"),\n',
    '        "Invariance Score": _mapping(result.get("invariance")).get("invariance_score"),\n',
    '        "Robust EV pips": _mapping(result.get("robust_expectancy")).get("robust_expected_value"),\n',
    '        "Extreme Risk": "BLOCK" if _mapping(result.get("evt_tail")).get("extreme_risk_block") else "OK",\n',
    '    }\n',
    '    for col, value in values.items():\n',
    '        if col not in out:\n',
    '            out[col] = np.nan if isinstance(value, (int, float, np.number)) or value is None else ""\n',
    '        out.loc[current_mask, col] = value\n',
    '    return out\n',
    '\n',
    '\n',
    'def build_and_apply_research_risk_stack(\n',
    '    canonical: Mapping[str, Any], *, ohlc: Any, trust_store: Any,\n',
    '    priority_table: Any = None, calibrated_bundle: Any = None,\n',
    '    previous_cache: Optional[Mapping[str, Any]] = None,\n',
    '    precomputed_periodicity: Optional[Mapping[str, Any]] = None,\n',
    '    precomputed_periodicity_frame: Optional[pd.DataFrame] = None,\n',
    ') -> Tuple[Dict[str, Any], Dict[str, Any], pd.DataFrame, Any]:\n',
    '    payload = deepcopy(dict(canonical or {}))\n',
    '    settled = trust_store.frame(status="SETTLED", limit=20000) if trust_store is not None else pd.DataFrame()\n',
    '    if isinstance(precomputed_periodicity, Mapping) and isinstance(precomputed_periodicity_frame, pd.DataFrame) and not precomputed_periodicity_frame.empty:\n',
    '        periodicity, periodicity_frame = dict(precomputed_periodicity), precomputed_periodicity_frame\n',
    '    else:\n',
    '        periodicity, periodicity_frame = build_periodicity_normalization(ohlc, settled=settled)\n',
    '    proper = build_proper_scoring(settled, _mapping(previous_cache).get("proper_scoring"))\n',
    '    final = _mapping(payload.get("final_decision"))\n',
    '    regime = _mapping(payload.get("regime"))\n',
    '    current_direction = _direction(final.get("directional_market_view") or payload.get("full_metric_direction"))\n',
    '    latest = pd.to_datetime(payload.get("latest_completed_candle_time"), errors="coerce", utc=True)\n',
    '    current_session = _session(latest) if pd.notna(latest) else "UNKNOWN"\n',
    '    current_regime = str(regime.get("major_regime") or payload.get("current_major_regime") or "UNKNOWN")\n',
    '    priority_class = _current_priority(payload, priority_table)\n',
    '    current_confidence = final.get("calibrated_confidence")\n',
    '    competing, events = build_competing_risk(\n',
    '        settled, ohlc, current_regime=current_regime, current_session=current_session,\n',
    '        current_direction=current_direction, current_priority=priority_class, current_confidence=current_confidence,\n',
    '    )\n',
    '    db_path = getattr(trust_store, "db_path", None)\n',
    '    store = ResearchRiskStore(db_path)\n',
    '    confidence = build_confidence_sequences(settled, events, store)\n',
    '    selective = build_selective_prediction(\n',
    '        settled, current_direction=current_direction, current_session=current_session,\n',
    '        current_regime=current_regime, current_confidence=current_confidence,\n',
    '    )\n',
    '    invariance = build_invariance(ohlc, priority_table)\n',
    '    event_intensity = build_event_intensity(periodicity_frame, payload, settled)\n',
    '    evt = build_evt_tail(settled, periodicity_frame, payload)\n',
    '    robust = build_robust_expectancy(payload, selective, evt, event_intensity, proper, competing, periodicity)\n',
    '    risk_multiplier = build_risk_multiplier(payload, competing, evt, confidence, robust)\n',
    '    selected_horizon = int(_finite(final.get("selected_horizon"), 3) or 3)\n',
    '    selected_risk = _mapping(_mapping(_mapping(competing.get("selected")).get("horizons")).get(f"{selected_horizon if selected_horizon in RISK_HORIZONS else 3}h"))\n',
    '    result: Dict[str, Any] = {\n',
    '        "ok": True, "version": VERSION, "generated_at": _utc_now(),\n',
    '        "calculation_id": payload.get("canonical_calculation_id") or payload.get("run_id"),\n',
    '        "periodicity": periodicity, "proper_scoring": proper, "competing_risk": competing,\n',
    '        "confidence_sequence": confidence, "selective_prediction": selective, "evt_tail": evt,\n',
    '        "invariance": invariance, "risk_multiplier": risk_multiplier, "robust_expectancy": robust,\n',
    '        "event_intensity": event_intensity,\n',
    '        "current_summary": {\n',
    '            "direction": current_direction, "selected_horizon": selected_horizon,\n',
    '            "tp_first_probability": selected_risk.get("tp_first_probability"),\n',
    '            "sl_first_probability": selected_risk.get("sl_first_probability"),\n',
    '            "required_confidence_threshold": selective.get("required_confidence_threshold"),\n',
    '            "selective_prediction_pass": selective.get("selective_prediction_pass"),\n',
    '            "robust_expected_value": robust.get("robust_expected_value"),\n',
    '            "extreme_risk_block": evt.get("extreme_risk_block"),\n',
    '            "display_risk_multiplier": risk_multiplier.get("display_risk_multiplier"),\n',
    '        },\n',
    '        "performance_policy": {"settled_only": True, "causal_periodicity_shift": True, "fixed_threshold_grid": True, "no_new_direction_engine": True},\n',
    '    }\n',
    '\n',
]
