"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Lightweight research risk stack for the canonical EURUSD H1 transaction.\n',
    '\n',
    'The module is deliberately additive. It reads completed H1 data, settled\n',
    'forecast history and the protected Full Metric authority, then returns compact\n',
    'validation/risk modifiers. It never creates or reverses a direction. The only\n',
    'permitted decision change is a conservative downgrade to WAIT.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import json\n',
    'import math\n',
    'import os\n',
    'import sqlite3\n',
    'import threading\n',
    'from contextlib import contextmanager\n',
    'from copy import deepcopy\n',
    'from datetime import datetime, timezone\n',
    'from pathlib import Path\n',
    'from typing import Any, Dict, Iterable, Mapping, MutableMapping, Optional, Sequence, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'VERSION = "research-risk-stack-20260619-v1"\n',
    'PIP = 0.0001\n',
    'HORIZONS = (1, 2, 3, 4, 5, 6)\n',
    'RISK_HORIZONS = (1, 2, 3, 6)\n',
    'THRESHOLD_GRID = (50, 55, 60, 65, 70, 75, 80, 85, 90)\n',
    '_LOCK = threading.RLock()\n',
    'PROJECT_ROOT = Path(__file__).resolve().parents[1]\n',
    'DEFAULT_DB = PROJECT_ROOT / "data" / "quant_app.sqlite3"\n',
    '\n',
    '\n',
    'def _utc_now() -> str:\n',
    '    return datetime.now(timezone.utc).isoformat()\n',
    '\n',
    '\n',
    'def _finite(value: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    try:\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(value: Any, lo: float, hi: float, default: float = 0.0) -> float:\n',
    '    out = _finite(value, default)\n',
    '    return float(max(lo, min(hi, out if out is not None else default)))\n',
    '\n',
    '\n',
    'def _prob(value: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    out = _finite(value, default)\n',
    '    if out is None:\n',
    '        return None\n',
    '    if out > 1.0:\n',
    '        out /= 100.0\n',
    '    return _clip(out, 0.0, 1.0)\n',
    '\n',
    '\n',
    'def _mapping(value: Any) -> Mapping[str, Any]:\n',
    '    return value if isinstance(value, Mapping) else {}\n',
    '\n',
    '\n',
    'def _series(frame: pd.DataFrame, name: str, default: Any = np.nan) -> pd.Series:\n',
    '    """Return an index-aligned Series even when an optional ledger column is absent."""\n',
    '    if name in frame.columns:\n',
    '        value = frame[name]\n',
    '        return value if isinstance(value, pd.Series) else pd.Series(value, index=frame.index)\n',
    '    return pd.Series(default, index=frame.index)\n',
    '\n',
    '\n',
    'def _direction(value: Any) -> str:\n',
    '    text = str(value or "").upper()\n',
    '    if "BUY" in text or "BULL" in text or text == "UP":\n',
    '        return "BUY"\n',
    '    if "SELL" in text or "BEAR" in text or text == "DOWN":\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _session(ts: pd.Timestamp) -> str:\n',
    '    hour = int(ts.hour)\n',
    '    if 0 <= hour < 7:\n',
    '        return "ASIA"\n',
    '    if 7 <= hour < 12:\n',
    '        return "LONDON"\n',
    '    if 12 <= hour < 16:\n',
    '        return "LONDON_NY_OVERLAP"\n',
    '    if 16 <= hour < 21:\n',
    '        return "NEW_YORK"\n',
    '    return "LATE_NY"\n',
    '\n',
    '\n',
    'def _json_safe(value: Any) -> Any:\n',
    '    if isinstance(value, pd.DataFrame):\n',
    '        return [_json_safe(x) for x in value.to_dict("records")]\n',
    '    if isinstance(value, pd.Series):\n',
    '        return [_json_safe(x) for x in value.tolist()]\n',
    '    if isinstance(value, Mapping):\n',
    '        return {str(k): _json_safe(v) for k, v in value.items()}\n',
    '    if isinstance(value, (list, tuple)):\n',
    '        return [_json_safe(v) for v in value]\n',
    '    if isinstance(value, (np.integer,)):\n',
    '        return int(value)\n',
    '    if isinstance(value, (np.floating,)):\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else None\n',
    '    if isinstance(value, (pd.Timestamp, datetime)):\n',
    '        ts = pd.Timestamp(value)\n',
    '        if pd.isna(ts):\n',
    '            return None\n',
    '        ts = ts.tz_localize("UTC") if ts.tzinfo is None else ts.tz_convert("UTC")\n',
    '        return ts.isoformat()\n',
    '    try:\n',
    '        if pd.isna(value):\n',
    '            return None\n',
    '    except Exception:\n',
    '        pass\n',
    '    return value\n',
    '\n',
    '\n',
    'def _normalise_ohlc(frame: Any) -> pd.DataFrame:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame(columns=["open", "high", "low", "close"])\n',
    '    data = frame.copy(deep=False)\n',
    '    cmap = {str(c).strip().lower(): c for c in data.columns}\n',
    '    tcol = next((cmap[x] for x in ("time", "timestamp", "datetime", "date") if x in cmap), None)\n',
    '    required: Dict[str, Any] = {}\n',
    '    for name in ("open", "high", "low", "close"):\n',
    '        col = cmap.get(name) or cmap.get(name[0])\n',
    '        if col is None:\n',
    '            return pd.DataFrame(columns=["open", "high", "low", "close"])\n',
    '        required[name] = col\n',
    '    idx = pd.to_datetime(data[tcol] if tcol is not None else data.index, utc=True, errors="coerce")\n',
    '    out = pd.DataFrame(\n',
    '        {name: pd.to_numeric(data[col], errors="coerce").to_numpy() for name, col in required.items()},\n',
    '        index=pd.DatetimeIndex(idx),\n',
    '    )\n',
    '    volume_col = next((cmap[x] for x in ("tick_volume", "tick volume", "volume", "real_volume") if x in cmap), None)\n',
    '    if volume_col is not None:\n',
    '        out["volume"] = pd.to_numeric(data[volume_col], errors="coerce").to_numpy()\n',
    '    out = out.loc[~out.index.isna()].dropna(subset=["open", "high", "low", "close"]).sort_index()\n',
    '    out = out.loc[~out.index.duplicated(keep="last")]\n',
    '    return out\n',
    '\n',
    '\n',
    'def _causal_median(values: pd.Series, groups: pd.Series, minimum: int = 1) -> pd.Series:\n',
    '    shifted = values.groupby(groups, sort=False).shift(1)\n',
    '    return shifted.groupby(groups, sort=False).transform(lambda x: x.expanding(min_periods=minimum).median())\n',
    '\n',
    '\n',
    'def build_periodicity_normalization(\n',
    '    ohlc: Any,\n',
    '    *,\n',
    '    settled: Optional[pd.DataFrame] = None,\n',
    '    min_bucket: int = 8,\n',
    '    min_session: int = 16,\n',
    ') -> Tuple[Dict[str, Any], pd.DataFrame]:\n',
    '    data = _normalise_ohlc(ohlc)\n',
    '    if data.empty:\n',
    '        result = {\n',
    '            "version": "periodicity_v1", "status": "INSUFFICIENT_DATA", "hour_of_week": None,\n',
    '            "expected_hourly_volatility": None, "periodicity_normalized_return": 0.0,\n',
    '            "periodicity_normalized_range": 0.0, "periodicity_normalized_residual": 0.0,\n',
    '            "periodicity_sample_count": 0, "periodicity_reliability": 0.0,\n',
    '        }\n',
    '        return result, pd.DataFrame()\n',
    '\n',
    '    work = data.copy(deep=False)\n',
    '    ret = work["close"].pct_change()\n',
    '    abs_ret = ret.abs()\n',
    '    candle_range = (work["high"] - work["low"]).abs()\n',
    '    prev_close = work["close"].shift(1)\n',
    '    tr = pd.concat([(work["high"] - work["low"]).abs(), (work["high"] - prev_close).abs(), (work["low"] - prev_close).abs()], axis=1).max(axis=1)\n',
    '    atr = tr.rolling(14, min_periods=3).median()\n',
    '    volume = work.get("volume", pd.Series(1.0, index=work.index)).abs()\n',
    '    residual = pd.Series(np.nan, index=work.index, dtype=float)\n',
    '    if isinstance(settled, pd.DataFrame) and not settled.empty and {"target_time", "actual_close", "predicted_close"}.issubset(settled.columns):\n',
    '        rows = settled[["target_time", "actual_close", "predicted_close"]].copy(deep=False)\n',
    '        rows["time"] = pd.to_datetime(rows["target_time"], errors="coerce", utc=True)\n',
    '        rows["residual"] = (pd.to_numeric(rows["actual_close"], errors="coerce") - pd.to_numeric(rows["predicted_close"], errors="coerce")).abs()\n',
    '        med = rows.dropna(subset=["time", "residual"]).groupby("time", sort=False)["residual"].median()\n',
    '        residual = pd.Series(work.index.map(med), index=work.index, dtype=float)\n',
    '\n',
    '    how = pd.Series(work.index.weekday * 24 + work.index.hour, index=work.index, dtype=int)\n',
    '    sessions = pd.Series([_session(ts) for ts in work.index], index=work.index, dtype="object")\n',
    '    global_scales: Dict[str, pd.Series] = {}\n',
    '    raw_map = {"abs_return": abs_ret, "range": candle_range, "atr": atr, "volume": volume, "residual": residual}\n',
    '    scales: Dict[str, pd.Series] = {}\n',
    '    counts = how.groupby(how, sort=False).cumcount()\n',
    '    session_counts = sessions.groupby(sessions, sort=False).cumcount()\n',
    '    for name, values in raw_map.items():\n',
    '        values = pd.to_numeric(values, errors="coerce")\n',
    '        bucket = _causal_median(values, how, minimum=1)\n',
    '        session_med = _causal_median(values, sessions, minimum=1)\n',
    '        global_med = values.shift(1).rolling(24 * 30, min_periods=5).median()\n',
    '        expanding = values.shift(1).expanding(min_periods=1).median()\n',
    '        bucket = bucket.where(counts >= min_bucket)\n',
    '        session_med = session_med.where(session_counts >= min_session)\n',
    '        scale = bucket.fillna(session_med).fillna(global_med).fillna(expanding)\n',
    '        # A fixed domain-scale bootstrap is used only before any past sample\n',
    '        # exists. Using the full-series median here would leak future rows into\n',
    '        # the earliest buckets and would make historical values change when new\n',
    '        # candles are appended.\n',
    '        fixed_bootstrap = {\n',
    '            "abs_return": 1e-4, "range": 1e-4, "atr": 1e-4,\n',
    '            "volume": 1.0, "residual": 1e-4,\n',
    '        }.get(name, 1e-4)\n',
    '        scale = scale.fillna(fixed_bootstrap).clip(lower=max(fixed_bootstrap * 1e-6, 1e-12))\n',
    '        scales[name] = scale\n',
    '        global_scales[name] = global_med\n',
    '\n',
    '    norm = pd.DataFrame(index=work.index)\n',
    '    norm["hour_of_week"] = how\n',
    '    norm["expected_hourly_volatility"] = scales["abs_return"]\n',
    '    norm["periodicity_normalized_return"] = ret / scales["abs_return"]\n',
    '    norm["periodicity_normalized_range"] = candle_range / scales["range"]\n',
    '    norm["periodicity_normalized_atr"] = atr / scales["atr"]\n',
    '    norm["periodicity_normalized_volume"] = volume / scales["volume"]\n',
    '    norm["periodicity_normalized_residual"] = residual / scales["residual"]\n',
    '    norm["periodicity_sample_count"] = counts.astype(int)\n',
    '    norm["periodicity_reliability"] = (counts / max(float(min_bucket * 3), 1.0)).clip(0.0, 1.0)\n',
    '    norm = norm.replace([np.inf, -np.inf], np.nan)\n',
    '    for col in ("periodicity_normalized_return", "periodicity_normalized_range", "periodicity_normalized_atr", "periodicity_normalized_volume", "periodicity_normalized_residual"):\n',
    '        norm[col] = norm[col].fillna(0.0).clip(-20.0, 20.0)\n',
    '    latest = norm.iloc[-1]\n',
    '    result = {\n',
    '        "version": "periodicity_v1", "status": "READY",\n',
    '        "hour_of_week": int(latest["hour_of_week"]),\n',
    '        "expected_hourly_volatility": float(latest["expected_hourly_volatility"]),\n',
    '        "periodicity_normalized_return": float(latest["periodicity_normalized_return"]),\n',
    '        "periodicity_normalized_range": float(latest["periodicity_normalized_range"]),\n',
    '        "periodicity_normalized_residual": float(latest["periodicity_normalized_residual"]),\n',
    '        "periodicity_sample_count": int(latest["periodicity_sample_count"]),\n',
    '        "periodicity_reliability": float(latest["periodicity_reliability"]),\n',
    '        "fallback_policy": "hour-of-week shifted median → shifted session median → shifted global rolling median",\n',
    '        "causal_shift_applied": True,\n',
    '    }\n',
    '    return result, norm\n',
    '\n',
    '\n',
    'def _pinball(y: np.ndarray, q: np.ndarray, alpha: float) -> np.ndarray:\n',
    '    diff = y - q\n',
    '    return np.maximum(alpha * diff, (alpha - 1.0) * diff)\n',
    '\n',
    '\n',
    'def build_proper_scoring(settled: pd.DataFrame, previous: Optional[Mapping[str, Any]] = None) -> Dict[str, Any]:\n',
    '    result: Dict[str, Any] = {"version": "proper_scoring_v1", "status": "INSUFFICIENT_DATA"}\n',
    '    if not isinstance(settled, pd.DataFrame) or settled.empty:\n',
    '        result.update({f"crps_h{h}": None for h in HORIZONS})\n',
    '        result.update({"mean_crps": None, "joint_energy_score": None, "path_sharpness": None, "path_calibration": None, "skill_vs_naive": None, "skill_vs_drift": None, "sample_count": 0, "reliability_modifier": 1.0})\n',
    '        return result\n',
    '    frame = settled.copy(deep=False)\n',
    '    for col in ("actual_close", "predicted_close", "forecast_origin_price", "p10", "p25", "p50", "p75", "p90", "horizon"):\n',
    '        if col in frame:\n',
    '            frame[col] = pd.to_numeric(frame[col], errors="coerce")\n',
    '    quantile_cols = (("p10", .10), ("p25", .25), ("p50", .50), ("p75", .75), ("p90", .90))\n',
    '    crps_by_h: Dict[int, Optional[float]] = {}\n',
    '    samples_by_h: Dict[int, int] = {}\n',
    '    all_scores: list[float] = []\n',
    '    for h in HORIZONS:\n',
    '        group = frame.loc[frame.get("horizon", pd.Series(index=frame.index, dtype=float)).eq(h)]\n',
    '        valid = group.dropna(subset=["actual_close"] + [c for c, _ in quantile_cols if c in group.columns])\n',
    '        samples_by_h[h] = int(len(valid))\n',
    '        if len(valid) < 5 or any(c not in valid for c, _ in quantile_cols):\n',
    '            crps_by_h[h] = None\n',
    '            continue\n',
    '        y = valid["actual_close"].to_numpy(dtype=float)\n',
    '        losses = np.column_stack([_pinball(y, valid[c].to_numpy(dtype=float), a) for c, a in quantile_cols])\n',
    '        scores = 2.0 * losses.mean(axis=1)\n',
    '        crps_by_h[h] = float(np.mean(scores))\n',
    '        all_scores.extend(scores.tolist())\n',
    '\n',
    '    path_scores: list[float] = []\n',
    '    if "calculation_id" in frame:\n',
    '        for _, group in frame.dropna(subset=["actual_close"]).groupby("calculation_id", sort=False):\n',
    '            group = group.sort_values("horizon")\n',
    '            if len(group) < 2 or any(c not in group for c, _ in quantile_cols):\n',
    '                continue\n',
    '            actual = group["actual_close"].to_numpy(dtype=float)\n',
    '            scenarios = np.vstack([group[c].to_numpy(dtype=float) for c, _ in quantile_cols])\n',
    '            if not np.isfinite(scenarios).all() or not np.isfinite(actual).all():\n',
    '                continue\n',
    '            first = np.linalg.norm(scenarios - actual[None, :], axis=1).mean()\n',
    '            pair = np.linalg.norm(scenarios[:, None, :] - scenarios[None, :, :], axis=2).mean()\n',
    '            path_scores.append(float(first - 0.5 * pair))\n',
    '\n',
    '    width = None\n',
    '    coverage = None\n',
    '    if {"p10", "p90", "actual_close"}.issubset(frame.columns):\n',
    '        valid = frame.dropna(subset=["p10", "p90", "actual_close"])\n',
    '        if not valid.empty:\n',
    '            width = float((valid["p90"] - valid["p10"]).abs().mean())\n',
    '            coverage = float(((valid["actual_close"] >= valid["p10"]) & (valid["actual_close"] <= valid["p90"])).mean())\n',
    '    valid_pred = frame.dropna(subset=[c for c in ("actual_close", "predicted_close", "forecast_origin_price") if c in frame.columns])\n',
    '    model_mae = naive_mae = drift_mae = None\n',
    '    if {"actual_close", "predicted_close", "forecast_origin_price"}.issubset(valid_pred.columns) and len(valid_pred) >= 5:\n',
    '        model_mae = float((valid_pred["actual_close"] - valid_pred["predicted_close"]).abs().mean())\n',
    '        naive_mae = float((valid_pred["actual_close"] - valid_pred["forecast_origin_price"]).abs().mean())\n',
    '        ordered = valid_pred.sort_values([c for c in ("forecast_origin_time", "horizon") if c in valid_pred.columns])\n',
    '        signed = ordered["actual_close"] - ordered["forecast_origin_price"]\n',
    '        hist_drift = signed.groupby(ordered["horizon"] if "horizon" in ordered else pd.Series(1, index=ordered.index)).transform(lambda x: x.shift(1).expanding(min_periods=3).median()).fillna(0.0)\n',
    '        drift_pred = ordered["forecast_origin_price"] + hist_drift\n',
    '        drift_mae = float((ordered["actual_close"] - drift_pred).abs().mean())\n',
    '    skill_naive = None if model_mae is None or not naive_mae else float(1.0 - model_mae / naive_mae)\n',
    '    skill_drift = None if model_mae is None or not drift_mae else float(1.0 - model_mae / drift_mae)\n',
    '    mean_crps = float(np.mean(all_scores)) if all_scores else None\n',
    '    target_coverage = 0.80\n',
    '    calibration_quality = 0.5 if coverage is None else max(0.0, 1.0 - abs(coverage - target_coverage) / target_coverage)\n',
    '    skill_quality = np.mean([max(-1.0, min(1.0, x)) for x in (skill_naive, skill_drift) if x is not None]) if any(x is not None for x in (skill_naive, skill_drift)) else 0.0\n',
    '    raw_modifier = 1.0 + 0.025 * skill_quality + 0.015 * (calibration_quality - 0.5)\n',
    '    raw_modifier = _clip(raw_modifier, 0.94, 1.04, 1.0)\n',
    '    prev_modifier = _finite(_mapping(previous).get("reliability_modifier"), 1.0) or 1.0\n',
    '    modifier = _clip(0.75 * prev_modifier + 0.25 * raw_modifier, 0.94, 1.04, 1.0)\n',
    '    result.update({\n',
    '        **{f"crps_h{h}": crps_by_h.get(h) for h in HORIZONS},\n',
    '        "mean_crps": mean_crps,\n',
    '        "joint_energy_score": float(np.mean(path_scores)) if path_scores else None,\n',
    '        "path_sharpness": width,\n',
    '        "path_calibration": coverage,\n',
    '        "skill_vs_naive": skill_naive,\n',
    '        "skill_vs_drift": skill_drift,\n',
    '        "sample_count": int(len(valid_pred)),\n',
    '        "samples_by_horizon": samples_by_h,\n',
    '        "reliability_modifier": modifier,\n',
    '        "status": "READY" if len(valid_pred) >= 20 else "DEVELOPING",\n',
    '        "settled_only": True,\n',
    '    })\n',
    '    return result\n',
    '\n',
    '\n',
    'def _priority_class(value: Any) -> str:\n',
    '    text = str(value or "").upper()\n',
    '    for label in ("A+", "A", "B", "C", "AVOID"):\n',
    '        if label in text:\n',
    '            return label\n',
    '    number = _finite(value, None)\n',
    '    if number is not None:\n',
    '        if number <= 3:\n',
    '            return "A+"\n',
    '        if number <= 6:\n',
    '            return "A"\n',
    '        if number <= 9:\n',
    '            return "B"\n',
    '        if number <= 12:\n',
    '            return "C"\n',
    '    return "UNKNOWN"\n',
    '\n',
    '\n',
    'def _confidence_band(value: Any) -> str:\n',
    '    p = _prob(value, None)\n',
    '    if p is None:\n',
    '        return "UNKNOWN"\n',
    '    pct = p * 100.0\n',
    '    return "HIGH" if pct >= 75 else "MEDIUM" if pct >= 60 else "LOW"\n',
    '\n',
    '\n',
    'def _event_for_row(row: Mapping[str, Any], ohlc: pd.DataFrame, horizon: int) -> Dict[str, Any]:\n',
    '    origin = pd.to_datetime(row.get("forecast_origin_time"), errors="coerce", utc=True)\n',
    '    if pd.isna(origin):\n',
    '        return {"event": "CENSORED", "time": None}\n',
    '    direction = _direction(row.get("full_metric_direction"))\n',
    '    tp = _finite(row.get("selected_tp"), None)\n',
    '    sl = _finite(row.get("selected_sl"), None)\n',
    '    if direction not in {"BUY", "SELL"} or tp is None or sl is None:\n',
    '        return {"event": "CENSORED", "time": None}\n',
    '    end = origin + pd.Timedelta(hours=int(horizon))\n',
    '    segment = ohlc.loc[(ohlc.index > origin) & (ohlc.index <= end)]\n',
    '    if segment.empty or pd.Timestamp(segment.index[-1]) < end:\n',
    '        return {"event": "CENSORED", "time": None}\n',
    '    for step, (_, candle) in enumerate(segment.iterrows(), start=1):\n',
    '        if direction == "BUY":\n',
    '            tp_hit = float(candle["high"]) >= tp\n',
    '            sl_hit = float(candle["low"]) <= sl\n',
    '        else:\n',
    '            tp_hit = float(candle["low"]) <= tp\n',
    '            sl_hit = float(candle["high"]) >= sl\n',
    '        if tp_hit and sl_hit:\n',
    '            return {"event": "CENSORED", "time": step, "ambiguous_same_candle": True}\n',
    '        if tp_hit:\n',
    '            return {"event": "TP", "time": step}\n',
    '        if sl_hit:\n',
    '            return {"event": "SL", "time": step}\n',
    '    return {"event": "NEITHER", "time": int(min(len(segment), horizon))}\n',
    '\n',
    '\n',
    'def _risk_summary(records: pd.DataFrame, horizon: int) -> Dict[str, Any]:\n',
    '    if records.empty:\n',
    '        return {"tp_first_probability": None, "sl_first_probability": None, "neither_hit_probability": None, "median_time_to_tp": None, "median_time_to_sl": None, "effective_sample_count": 0, "censored_count": 0}\n',
    '    event_col = f"event_{horizon}h"\n',
    '    time_col = f"time_{horizon}h"\n',
    '    if event_col not in records:\n',
    '        return {"tp_first_probability": None, "sl_first_probability": None, "neither_hit_probability": None, "median_time_to_tp": None, "median_time_to_sl": None, "effective_sample_count": 0, "censored_count": 0}\n',
    '    valid = records.loc[records[event_col].isin(["TP", "SL", "NEITHER"])]\n',
    '    n = len(valid)\n',
    '    return {\n',
    '        "tp_first_probability": float(valid[event_col].eq("TP").mean()) if n else None,\n',
    '        "sl_first_probability": float(valid[event_col].eq("SL").mean()) if n else None,\n',
    '        "neither_hit_probability": float(valid[event_col].eq("NEITHER").mean()) if n else None,\n',
    '        "median_time_to_tp": float(valid.loc[valid[event_col].eq("TP"), time_col].median()) if valid[event_col].eq("TP").any() else None,\n',
    '        "median_time_to_sl": float(valid.loc[valid[event_col].eq("SL"), time_col].median()) if valid[event_col].eq("SL").any() else None,\n',
    '        "effective_sample_count": int(n),\n',
    '        "censored_count": int(records[event_col].eq("CENSORED").sum()),\n',
    '    }\n',
    '\n',
    '\n',
    'def build_competing_risk(\n',
    '    settled: pd.DataFrame,\n',
    '    ohlc: Any,\n',
    '    *,\n',
    '    current_regime: str,\n',
    '    current_session: str,\n',
    '    current_direction: str,\n',
    '    current_priority: str,\n',
    '    current_confidence: Any,\n',
    ') -> Tuple[Dict[str, Any], pd.DataFrame]:\n',
    '    data = _normalise_ohlc(ohlc)\n',
    '    base = {"version": "competing_risk_v1", "status": "INSUFFICIENT_DATA", "selected": {}, "by_direction": {}}\n',
    '    if data.empty or not isinstance(settled, pd.DataFrame) or settled.empty:\n',
    '        return base, pd.DataFrame()\n',
]
