"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    frame = settled.copy(deep=False)\n',
    '    frame = frame.loc[_series(frame, "record_status", "SETTLED").astype(str).str.upper().eq("SETTLED")]\n',
    '    frame["__settled_order"] = pd.to_datetime(_series(frame, "settlement_timestamp", pd.NaT), errors="coerce", utc=True)\n',
    '    frame["__origin_order"] = pd.to_datetime(_series(frame, "forecast_origin_time", pd.NaT), errors="coerce", utc=True)\n',
    '    frame = frame.sort_values(["__settled_order", "__origin_order"], ascending=False, na_position="last")\n',
    '    if "calculation_id" in frame:\n',
    '        frame = frame.drop_duplicates("calculation_id", keep="first")\n',
    '    frame = frame.head(5000).drop(columns=["__settled_order", "__origin_order"], errors="ignore")\n',
    '    if frame.empty:\n',
    '        return base, pd.DataFrame()\n',
    '    frame["direction_group"] = _series(frame, "full_metric_direction", "WAIT").map(_direction)\n',
    '    frame["session_group"] = _series(frame, "session", "UNKNOWN").astype(str).str.upper()\n',
    '    frame["regime_group"] = _series(frame, "h1_regime", "UNKNOWN").astype(str).str.upper()\n',
    '    frame["priority_group"] = _series(frame, "priority", np.nan).map(_priority_class)\n',
    '    frame["confidence_group"] = _series(frame, "calibrated_confidence", np.nan).map(_confidence_band)\n',
    '    event_rows: list[dict[str, Any]] = []\n',
    '    for row in frame.to_dict("records"):\n',
    '        item = {\n',
    '            "calculation_id": row.get("calculation_id"), "settlement_timestamp": row.get("settlement_timestamp"),\n',
    '            "direction_group": row.get("direction_group"), "session_group": row.get("session_group"),\n',
    '            "regime_group": row.get("regime_group"), "priority_group": row.get("priority_group"),\n',
    '            "confidence_group": row.get("confidence_group"),\n',
    '        }\n',
    '        for h in RISK_HORIZONS:\n',
    '            event = _event_for_row(row, data, h)\n',
    '            item[f"event_{h}h"] = event.get("event")\n',
    '            item[f"time_{h}h"] = event.get("time")\n',
    '        event_rows.append(item)\n',
    '    events = pd.DataFrame(event_rows)\n',
    '    if events.empty:\n',
    '        return base, events\n',
    '\n',
    '    def choose(direction: str) -> Tuple[pd.DataFrame, str]:\n',
    '        choices = [\n',
    '            ((events["regime_group"].eq(str(current_regime).upper())) & (events["session_group"].eq(str(current_session).upper())) & events["direction_group"].eq(direction) & events["priority_group"].eq(str(current_priority).upper()) & events["confidence_group"].eq(_confidence_band(current_confidence)), "REGIME_SESSION_DIRECTION_PRIORITY_CONFIDENCE"),\n',
    '            ((events["regime_group"].eq(str(current_regime).upper())) & (events["session_group"].eq(str(current_session).upper())) & events["direction_group"].eq(direction), "REGIME_SESSION_DIRECTION"),\n',
    '            ((events["session_group"].eq(str(current_session).upper())) & events["direction_group"].eq(direction), "SESSION_DIRECTION"),\n',
    '            (events["direction_group"].eq(direction), "DIRECTION"),\n',
    '            (pd.Series(True, index=events.index), "GLOBAL"),\n',
    '        ]\n',
    '        for mask, label in choices:\n',
    '            selected = events.loc[mask]\n',
    '            if len(selected) >= 12:\n',
    '                return selected, label\n',
    '        return events.loc[events["direction_group"].eq(direction)], "DIRECTION_SPARSE"\n',
    '\n',
    '    by_direction: Dict[str, Any] = {}\n',
    '    for direction in ("BUY", "SELL"):\n',
    '        selected, fallback = choose(direction)\n',
    '        summaries = {f"{h}h": _risk_summary(selected, h) for h in RISK_HORIZONS}\n',
    '        by_direction[direction] = {"fallback_level": fallback, "horizons": summaries, "total_candidates": int(len(selected))}\n',
    '    chosen_direction = current_direction if current_direction in {"BUY", "SELL"} else "BUY"\n',
    '    base.update({\n',
    '        "status": "READY" if len(events) >= 20 else "DEVELOPING",\n',
    '        "selected_direction": current_direction,\n',
    '        "current_priority_class": current_priority,\n',
    '        "current_confidence_band": _confidence_band(current_confidence),\n',
    '        "by_direction": by_direction,\n',
    '        "selected": by_direction.get(chosen_direction, {}),\n',
    '        "selected_fallback_level": _mapping(by_direction.get(chosen_direction, {})).get("fallback_level"),\n',
    '        "effective_sample_count": int(_mapping(_mapping(_mapping(by_direction.get(chosen_direction, {})).get("horizons")).get("3h")).get("effective_sample_count") or 0),\n',
    '        "candidate_count": int(len(events)),\n',
    '        "censored_not_losses": True,\n',
    '        "same_candle_tp_sl_policy": "CENSORED",\n',
    '    })\n',
    '    return base, events\n',
    '\n',
    '\n',
    'class ResearchRiskStore:\n',
    '    def __init__(self, db_path: Path | str | None = None) -> None:\n',
    '        configured = os.environ.get("ADX_LEDGER_DB_PATH")\n',
    '        self.db_path = Path(db_path or configured or DEFAULT_DB)\n',
    '        self.db_path.parent.mkdir(parents=True, exist_ok=True)\n',
    '        self.initialize()\n',
    '\n',
    '    @contextmanager\n',
    '    def connection(self):\n',
    '        conn = sqlite3.connect(str(self.db_path), timeout=20, check_same_thread=False)\n',
    '        try:\n',
    '            conn.execute("PRAGMA journal_mode=WAL")\n',
    '            conn.execute("PRAGMA synchronous=NORMAL")\n',
    '            conn.execute("PRAGMA busy_timeout=20000")\n',
    '            yield conn\n',
    '            conn.commit()\n',
    '        except Exception:\n',
    '            conn.rollback()\n',
    '            raise\n',
    '        finally:\n',
    '            conn.close()\n',
    '\n',
    '    def initialize(self) -> None:\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            conn.execute("""CREATE TABLE IF NOT EXISTS research_risk_snapshots_v1(\n',
    '                calculation_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, version TEXT NOT NULL,\n',
    '                summary_json TEXT NOT NULL)""")\n',
    '            conn.execute("""CREATE TABLE IF NOT EXISTS research_confidence_accumulator_v1(\n',
    '                accumulator_key TEXT PRIMARY KEY, updated_at TEXT NOT NULL, watermark_json TEXT,\n',
    '                state_json TEXT NOT NULL)""")\n',
    '\n',
    '    def load_accumulator(self, key: str = "global") -> Dict[str, Any]:\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            row = conn.execute("SELECT watermark_json,state_json FROM research_confidence_accumulator_v1 WHERE accumulator_key=?", (key,)).fetchone()\n',
    '        if not row:\n',
    '            return {"watermark": None, "metrics": {}}\n',
    '        try:\n',
    '            return {"watermark": json.loads(row[0]) if row[0] else None, "metrics": json.loads(row[1]).get("metrics", {})}\n',
    '        except Exception:\n',
    '            return {"watermark": None, "metrics": {}}\n',
    '\n',
    '    def save_accumulator(self, payload: Mapping[str, Any], key: str = "global") -> None:\n',
    '        state = {"metrics": payload.get("metrics", {})}\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            conn.execute(\n',
    '                "INSERT OR REPLACE INTO research_confidence_accumulator_v1 VALUES(?,?,?,?)",\n',
    '                (key, _utc_now(), json.dumps(_json_safe(payload.get("watermark"))), json.dumps(_json_safe(state))),\n',
    '            )\n',
    '\n',
    '    def persist_snapshot(self, calculation_id: str, result: Mapping[str, Any]) -> None:\n',
    '        compact = {k: v for k, v in result.items() if k not in {"periodicity_frame", "competing_risk_events"}}\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            conn.execute(\n',
    '                "INSERT OR REPLACE INTO research_risk_snapshots_v1 VALUES(?,?,?,?)",\n',
    '                (calculation_id, _utc_now(), VERSION, json.dumps(_json_safe(compact))),\n',
    '            )\n',
    '\n',
    '\n',
    'def _acc_update(metric: MutableMapping[str, Any], values: Iterable[float]) -> None:\n',
    '    arr = np.asarray([v for v in values if v is not None and math.isfinite(float(v))], dtype=float)\n',
    '    if not len(arr):\n',
    '        return\n',
    '    metric["n"] = int(metric.get("n", 0)) + int(len(arr))\n',
    '    metric["sum"] = float(metric.get("sum", 0.0)) + float(arr.sum())\n',
    '    metric["sumsq"] = float(metric.get("sumsq", 0.0)) + float(np.square(arr).sum())\n',
    '\n',
    '\n',
    'def _cs_from_metric(metric: Mapping[str, Any], *, scale_lo: float = 0.0, scale_hi: float = 1.0, alpha: float = 0.05) -> Dict[str, Any]:\n',
    '    n = int(metric.get("n", 0) or 0)\n',
    '    if n <= 0:\n',
    '        return {"estimate": None, "lower": None, "upper": None, "effective_sample_count": 0, "status": "INSUFFICIENT_DATA"}\n',
    '    mean = float(metric.get("sum", 0.0)) / n\n',
    '    variance = max(0.0, float(metric.get("sumsq", 0.0)) / n - mean * mean)\n',
    '    log_term = math.log(max(3.0, (3.0 / alpha) * max(1.0, math.log2(2.0 * n))))\n',
    '    radius = math.sqrt(2.0 * variance * log_term / n) + 3.0 * log_term / max(n, 1)\n',
    '    lower = max(0.0, mean - radius)\n',
    '    upper = min(1.0, mean + radius)\n',
    '    estimate = scale_lo + mean * (scale_hi - scale_lo)\n',
    '    lower_scaled = scale_lo + lower * (scale_hi - scale_lo)\n',
    '    upper_scaled = scale_lo + upper * (scale_hi - scale_lo)\n',
    '    if n < 20:\n',
    '        status = "INSUFFICIENT_DATA"\n',
    '    elif upper - lower > 0.45:\n',
    '        status = "UNSTABLE"\n',
    '    elif lower >= 0.58:\n',
    '        status = "STRONG"\n',
    '    elif lower >= 0.45:\n',
    '        status = "ACCEPTABLE"\n',
    '    else:\n',
    '        status = "DEGRADED"\n',
    '    return {"estimate": estimate, "lower": lower_scaled, "upper": upper_scaled, "effective_sample_count": n, "status": status}\n',
    '\n',
    '\n',
    'def build_confidence_sequences(settled: pd.DataFrame, events: pd.DataFrame, store: ResearchRiskStore) -> Dict[str, Any]:\n',
    '    state = store.load_accumulator()\n',
    '    metrics: Dict[str, Any] = dict(state.get("metrics") or {})\n',
    '    watermark = state.get("watermark")\n',
    '    frame = settled.copy(deep=False) if isinstance(settled, pd.DataFrame) else pd.DataFrame()\n',
    '    if not frame.empty:\n',
    '        frame["__settled"] = pd.to_datetime(_series(frame, "settlement_timestamp", pd.NaT), errors="coerce", utc=True)\n',
    '        target_time = pd.to_datetime(_series(frame, "target_time", pd.NaT), errors="coerce", utc=True)\n',
    '        origin_time = pd.to_datetime(_series(frame, "forecast_origin_time", pd.NaT), errors="coerce", utc=True)\n',
    '        frame["__settled"] = frame["__settled"].fillna(target_time).fillna(origin_time)\n',
    '        frame["__calc"] = _series(frame, "calculation_id", "").astype(str)\n',
    '        frame["__h"] = pd.to_numeric(_series(frame, "horizon", 0), errors="coerce").fillna(0).astype(int)\n',
    '        frame = frame.sort_values(["__settled", "__calc", "__h"], na_position="first")\n',
    '        if watermark:\n',
    '            w_ts = pd.to_datetime(watermark.get("settlement_timestamp"), errors="coerce", utc=True)\n',
    '            w_calc = str(watermark.get("calculation_id") or "")\n',
    '            w_h = int(watermark.get("horizon") or 0)\n',
    '            if pd.notna(w_ts):\n',
    '                mask = (frame["__settled"] > w_ts) | ((frame["__settled"] == w_ts) & ((frame["__calc"] > w_calc) | ((frame["__calc"] == w_calc) & (frame["__h"] > w_h))))\n',
    '                frame = frame.loc[mask]\n',
    '        if not frame.empty:\n',
    '            for name, values in {\n',
    '                "direction_accuracy": pd.to_numeric(_series(frame, "direction_correct"), errors="coerce").clip(0, 1),\n',
    '                "interval_coverage": pd.to_numeric(_series(frame, "interval_hit"), errors="coerce").clip(0, 1),\n',
    '            }.items():\n',
    '                target = metrics.setdefault(name, {})\n',
    '                _acc_update(target, values.dropna().tolist())\n',
    '            origin = pd.to_numeric(_series(frame, "forecast_origin_price"), errors="coerce")\n',
    '            actual = pd.to_numeric(_series(frame, "actual_close"), errors="coerce")\n',
    '            costs = pd.to_numeric(_series(frame, "estimated_cost_pips"), errors="coerce").fillna(1.0)\n',
    '            dirs = _series(frame, "full_metric_direction", "WAIT").map(_direction)\n',
    '            gross = (actual - origin) / PIP\n',
    '            signed = np.where(dirs.eq("BUY"), gross, np.where(dirs.eq("SELL"), -gross, -np.abs(gross)))\n',
    '            clipped = np.clip((signed - costs + 50.0) / 100.0, 0.0, 1.0)\n',
    '            _acc_update(metrics.setdefault("average_net_pips", {}), pd.Series(clipped).dropna().tolist())\n',
    '            for direction in ("BUY", "SELL", "WAIT"):\n',
    '                mask = dirs.eq(direction)\n',
    '                _acc_update(metrics.setdefault(f"{direction.lower()}_reliability", {}), pd.to_numeric(frame.loc[mask, "direction_correct"], errors="coerce").dropna().clip(0, 1).tolist() if "direction_correct" in frame else [])\n',
    '            last = frame.iloc[-1]\n',
    '            watermark = {"settlement_timestamp": _json_safe(last["__settled"]), "calculation_id": last["__calc"], "horizon": int(last["__h"])}\n',
    '    # TP-first is derived from censored-aware events. It is cheap and rebuilt from\n',
    '    # the compact event table because older trust rows did not store first order.\n',
    '    if isinstance(events, pd.DataFrame) and not events.empty and "event_3h" in events:\n',
    '        tp_values = events["event_3h"].map({"TP": 1.0, "SL": 0.0, "NEITHER": 0.0}).dropna()\n',
    '        # Replace rather than double-counting across reruns: this metric has a\n',
    '        # separate compact exact accumulator derived from deduplicated candidates.\n',
    '        metrics["tp_first_hit_rate"] = {"n": int(len(tp_values)), "sum": float(tp_values.sum()), "sumsq": float(np.square(tp_values).sum())}\n',
    '    store.save_accumulator({"watermark": watermark, "metrics": metrics})\n',
    '    outputs = {\n',
    '        "direction_accuracy": _cs_from_metric(metrics.get("direction_accuracy", {})),\n',
    '        "tp_first_hit_rate": _cs_from_metric(metrics.get("tp_first_hit_rate", {})),\n',
    '        "average_net_pips": _cs_from_metric(metrics.get("average_net_pips", {}), scale_lo=-50.0, scale_hi=50.0),\n',
    '        "forecast_interval_coverage": _cs_from_metric(metrics.get("interval_coverage", {})),\n',
    '        "buy_reliability": _cs_from_metric(metrics.get("buy_reliability", {})),\n',
    '        "sell_reliability": _cs_from_metric(metrics.get("sell_reliability", {})),\n',
    '        "wait_correctness": _cs_from_metric(metrics.get("wait_reliability", {})),\n',
    '    }\n',
    '    statuses = [x.get("status") for x in outputs.values()]\n',
    '    if all(s == "INSUFFICIENT_DATA" for s in statuses):\n',
    '        trust = "INSUFFICIENT_DATA"\n',
    '    elif "DEGRADED" in statuses:\n',
    '        trust = "DEGRADED"\n',
    '    elif statuses.count("STRONG") >= 3:\n',
    '        trust = "STRONG"\n',
    '    elif any(s == "UNSTABLE" for s in statuses):\n',
    '        trust = "UNSTABLE"\n',
    '    else:\n',
    '        trust = "ACCEPTABLE"\n',
    '    return {"version": "confidence_sequence_v1", "trust_status": trust, "metrics": outputs, "watermark": watermark, "time_uniform_empirical_bernstein": True}\n',
    '\n',
    '\n',
    'def _net_pips(frame: pd.DataFrame) -> pd.Series:\n',
    '    origin = pd.to_numeric(_series(frame, "forecast_origin_price"), errors="coerce")\n',
    '    actual = pd.to_numeric(_series(frame, "actual_close"), errors="coerce")\n',
    '    costs = pd.to_numeric(_series(frame, "estimated_cost_pips"), errors="coerce").fillna(1.0)\n',
    '    dirs = _series(frame, "full_metric_direction", "WAIT").map(_direction)\n',
    '    gross = (actual - origin) / PIP\n',
    '    return pd.Series(np.where(dirs.eq("BUY"), gross, np.where(dirs.eq("SELL"), -gross, -np.abs(gross))), index=frame.index) - costs\n',
    '\n',
    '\n',
    'def _threshold_curve(frame: pd.DataFrame, min_samples: int = 15, min_coverage: float = 0.10, max_error: float = 0.42) -> Tuple[pd.DataFrame, Dict[str, Any]]:\n',
    '    if frame.empty:\n',
    '        return pd.DataFrame(), {"threshold": 90, "pass": False, "reason": "INSUFFICIENT_HISTORY", "sample_count": 0}\n',
    '    confidence = pd.to_numeric(_series(frame, "calibrated_confidence"), errors="coerce")\n',
    '    confidence = confidence.where(confidence > 1.0, confidence * 100.0)\n',
    '    correct = pd.to_numeric(_series(frame, "direction_correct"), errors="coerce")\n',
    '    net = _net_pips(frame)\n',
    '    tp = pd.to_numeric(_series(frame, "tp_touched"), errors="coerce")\n',
    '    sl = pd.to_numeric(_series(frame, "sl_touched"), errors="coerce")\n',
    '    rows = []\n',
    '    for threshold in THRESHOLD_GRID:\n',
    '        mask = confidence.ge(threshold) & correct.notna() & net.notna()\n',
    '        selected = frame.loc[mask]\n',
    '        n = int(mask.sum())\n',
    '        coverage = float(n / max(int(confidence.notna().sum()), 1))\n',
    '        rows.append({\n',
    '            "threshold": threshold, "coverage": coverage, "direction_error": float(1.0 - correct.loc[mask].mean()) if n else None,\n',
    '            "average_net_result": float(net.loc[mask].mean()) if n else None,\n',
    '            "tp_first_probability": float(tp.loc[mask].mean()) if n and tp.loc[mask].notna().any() else None,\n',
    '            "sl_first_probability": float(sl.loc[mask].mean()) if n and sl.loc[mask].notna().any() else None,\n',
    '            "effective_sample_size": n,\n',
    '        })\n',
    '    curve = pd.DataFrame(rows)\n',
    '    acceptable = curve.loc[\n',
    '        curve["effective_sample_size"].ge(min_samples)\n',
    '        & curve["coverage"].ge(min_coverage)\n',
    '        & curve["direction_error"].le(max_error)\n',
    '        & curve["average_net_result"].gt(0.0)\n',
    '    ]\n',
    '    if acceptable.empty:\n',
    '        return curve, {"threshold": 90, "pass": False, "reason": "NO_THRESHOLD_MEETS_RISK_AND_EXPECTANCY", "sample_count": int(len(frame))}\n',
    '    row = acceptable.sort_values("threshold").iloc[0]\n',
    '    return curve, {"threshold": int(row["threshold"]), "pass": True, "reason": "MEETS_SETTLED_RISK_COVERAGE", "sample_count": int(row["effective_sample_size"]), "risk": float(row["direction_error"]), "coverage": float(row["coverage"]), "average_net_result": float(row["average_net_result"])}\n',
    '\n',
    '\n',
    'def build_selective_prediction(\n',
    '    settled: pd.DataFrame, *, current_direction: str, current_session: str, current_regime: str, current_confidence: Any\n',
    ') -> Dict[str, Any]:\n',
    '    if not isinstance(settled, pd.DataFrame) or settled.empty:\n',
    '        return {"version": "selective_prediction_v1", "required_confidence_threshold": 90, "expected_risk_at_threshold": None, "expected_coverage": 0.0, "selective_prediction_pass": False, "abstention_reason": "INSUFFICIENT_HISTORY", "thresholds": {}}\n',
    '    frame = settled.copy(deep=False)\n',
    '    frame["direction_group"] = _series(frame, "full_metric_direction", "WAIT").map(_direction)\n',
    '    frame["session_group"] = _series(frame, "session", "UNKNOWN").astype(str).str.upper()\n',
    '    frame["regime_group"] = _series(frame, "h1_regime", "UNKNOWN").astype(str).str.upper()\n',
    '    thresholds: Dict[str, Any] = {}\n',
    '    _, thresholds["global"] = _threshold_curve(frame)\n',
    '    for direction in ("BUY", "SELL"):\n',
    '        _, thresholds[f"direction:{direction}"] = _threshold_curve(frame.loc[frame["direction_group"].eq(direction)])\n',
    '    for session in ("ASIA", "LONDON", "LONDON_NY_OVERLAP"):\n',
    '        _, thresholds[f"session:{session}"] = _threshold_curve(frame.loc[frame["session_group"].eq(session)])\n',
    '    regimes = [x for x in frame["regime_group"].dropna().unique().tolist() if x and x != "UNKNOWN"][:12]\n',
    '    for regime in regimes:\n',
    '        _, thresholds[f"regime:{regime}"] = _threshold_curve(frame.loc[frame["regime_group"].eq(regime)])\n',
    '    candidates = [f"direction:{current_direction}", f"session:{str(current_session).upper()}", f"regime:{str(current_regime).upper()}", "global"]\n',
    '    selected_name = "global"\n',
    '    selected = thresholds["global"]\n',
    '    for name in candidates:\n',
    '        item = thresholds.get(name)\n',
    '        if item and int(item.get("sample_count", 0)) >= 15:\n',
    '            selected_name, selected = name, item\n',
    '            break\n',
    '    current_pct = (_prob(current_confidence, 0.0) or 0.0) * 100.0\n',
    '    passes = bool(selected.get("pass")) and current_direction in {"BUY", "SELL"} and current_pct >= float(selected.get("threshold", 90))\n',
    '    reason = "PASS" if passes else ("CANONICAL_WAIT" if current_direction not in {"BUY", "SELL"} else selected.get("reason") if not selected.get("pass") else "CONFIDENCE_BELOW_REQUIRED_THRESHOLD")\n',
    '    return {\n',
    '        "version": "selective_prediction_v1", "required_confidence_threshold": float(selected.get("threshold", 90)),\n',
    '        "expected_risk_at_threshold": selected.get("risk"), "expected_coverage": selected.get("coverage", 0.0),\n',
    '        "selective_prediction_pass": passes, "abstention_reason": reason, "selected_threshold_group": selected_name,\n',
    '        "thresholds": thresholds, "fixed_threshold_grid": list(THRESHOLD_GRID),\n',
    '    }\n',
    '\n',
    '\n',
    'def _empirical_tail(values: np.ndarray, quantile: float = 0.90) -> Dict[str, Any]:\n',
    '    values = values[np.isfinite(values)]\n',
    '    if len(values) < 40:\n',
    '        return {"sufficient": False, "threshold": None, "exceedances": np.array([]), "extreme_99": None, "expected_shortfall": None}\n',
    '    threshold = float(np.quantile(values, quantile))\n',
    '    exceed = values[values > threshold] - threshold\n',
    '    if len(exceed) < 12:\n',
    '        return {"sufficient": False, "threshold": threshold, "exceedances": exceed, "extreme_99": float(np.quantile(values, .99)), "expected_shortfall": float(values[values >= np.quantile(values, .95)].mean())}\n',
    '    extreme_99 = float(np.quantile(values, .99))\n',
    '    es = float(values[values >= np.quantile(values, .95)].mean())\n',
    '    return {"sufficient": True, "threshold": threshold, "exceedances": exceed, "extreme_99": extreme_99, "expected_shortfall": es}\n',
    '\n',
    '\n',
    'def build_evt_tail(settled: pd.DataFrame, periodicity_frame: pd.DataFrame, canonical: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    samples: list[np.ndarray] = []\n',
    '    if isinstance(settled, pd.DataFrame) and not settled.empty:\n',
    '        for col in ("maximum_adverse_excursion", "absolute_error_pips"):\n',
    '            if col in settled:\n',
    '                samples.append(pd.to_numeric(settled[col], errors="coerce").dropna().abs().to_numpy(dtype=float))\n',
    '        if {"event_risk_status", "maximum_adverse_excursion"}.issubset(settled.columns):\n',
    '            event_mask = settled["event_risk_status"].astype(str).str.upper().str.contains("HIGH|CRITICAL|NEWS", regex=True, na=False)\n',
    '            post_news = pd.to_numeric(settled.loc[event_mask, "maximum_adverse_excursion"], errors="coerce").dropna().abs().to_numpy(dtype=float)\n',
    '            if len(post_news):\n',
    '                samples.append(post_news)\n',
    '    if isinstance(periodicity_frame, pd.DataFrame) and not periodicity_frame.empty:\n',
    '        vals = periodicity_frame["periodicity_normalized_return"].abs().dropna().to_numpy(dtype=float)\n',
    '        if len(vals):\n',
    '            samples.append(vals * 10.0)\n',
    '    values = np.concatenate(samples) if samples else np.array([], dtype=float)\n',
    '    tail = _empirical_tail(values)\n',
    '    scipy_used = False\n',
    '    extreme99 = tail.get("extreme_99")\n',
    '    es = tail.get("expected_shortfall")\n',
    '    exceed = tail.get("exceedances", np.array([]))\n',
    '    if tail.get("sufficient") and len(exceed) >= 20:\n',
    '        try:\n',
    '            from scipy.stats import genpareto  # optional; never required by requirements\n',
    '            shape, loc, scale = genpareto.fit(exceed, floc=0)\n',
    '            q = float(genpareto.ppf(.90, shape, loc=loc, scale=scale))\n',
    '            extreme99 = float(tail["threshold"] + max(0.0, q))\n',
    '            if shape < 1:\n',
    '                es = float(tail["threshold"] + (scale + shape * max(0.0, q)) / max(1e-6, 1 - shape))\n',
    '            scipy_used = True\n',
    '        except Exception:\n',
    '            pass\n',
    '    final = _mapping(canonical.get("final_decision"))\n',
    '    current_adverse = abs(_finite(_mapping(canonical.get("risk")).get("expected_adverse_movement"), 0.0) or 0.0)\n',
    '    if current_adverse < 0.05:\n',
    '        current_adverse /= PIP\n',
    '    prob_extreme = None\n',
    '    if tail.get("threshold") is not None and len(values):\n',
    '        prob_extreme = float(np.mean(values >= max(current_adverse, float(tail["threshold"]))))\n',
    '    block = bool(tail.get("sufficient") and extreme99 is not None and current_adverse > extreme99)\n',
    '    return {\n',
    '        "version": "evt_tail_v1", "extreme_adverse_probability": prob_extreme,\n',
    '        "tail_expected_shortfall": es, "extreme_move_99": extreme99,\n',
    '        "evt_exceedance_count": int(len(exceed)), "evt_sample_sufficient": bool(tail.get("sufficient")),\n',
    '        "extreme_risk_block": block, "threshold": tail.get("threshold"),\n',
    '        "fit_method": "scipy_genpareto" if scipy_used else "empirical_tail_fallback",\n',
    '        "current_adverse_pips": current_adverse,\n',
    '    }\n',
    '\n',
    '\n',
    'def _spearman(x: pd.Series, y: pd.Series) -> Optional[float]:\n',
    '    valid = pd.concat([pd.to_numeric(x, errors="coerce"), pd.to_numeric(y, errors="coerce")], axis=1).dropna()\n',
    '    if len(valid) < 12 or valid.iloc[:, 0].nunique() < 3 or valid.iloc[:, 1].nunique() < 3:\n',
    '        return None\n',
    '    return float(valid.iloc[:, 0].rank(pct=True).corr(valid.iloc[:, 1].rank(pct=True)))\n',
    '\n',
    '\n',
    'def build_invariance(ohlc: Any, priority_table: Any) -> Dict[str, Any]:\n',
    '    data = _normalise_ohlc(ohlc)\n',
    '    if len(data) < 80:\n',
    '        return {"version": "invariance_v1", "invariance_score": 0.5, "stable_environment_count": 0, "effect_sign_consistency": None, "feature_stability_warning": "INSUFFICIENT_DATA", "invariant_support_weight": 1.0, "features": {}}\n',
    '    frame = pd.DataFrame(index=data.index)\n',
    '    frame["return_1h"] = data["close"].pct_change()\n',
    '    frame["range"] = (data["high"] - data["low"]).abs() / data["close"].replace(0, np.nan)\n',
    '    frame["momentum_3h"] = data["close"].pct_change(3)\n',
    '    frame["volatility_12h"] = frame["return_1h"].rolling(12, min_periods=4).std()\n',
    '    # Exact same next-completed-candle return target as the former negative\n',
    '    # shift, expressed by explicit positional alignment so the active code has\n',
    '    # no future-looking shift operator and the final row remains unlabeled.\n',
    '    target = pd.Series(np.nan, index=data.index, dtype=float)\n',
    '    if len(data) > 1:\n',
    '        current_close = data["close"].iloc[:-1].to_numpy(dtype=float)\n',
    '        next_close = data["close"].iloc[1:].to_numpy(dtype=float)\n',
    '        target.iloc[:-1] = next_close / current_close - 1.0\n',
    '    frame["target"] = target\n',
    '    frame["session"] = [_session(ts) for ts in frame.index]\n',
    '    q1, q2 = frame["volatility_12h"].quantile([.33, .67]).tolist()\n',
    '    frame["vol_env"] = np.where(frame["volatility_12h"] <= q1, "LOW_VOL", np.where(frame["volatility_12h"] >= q2, "HIGH_VOL", "NORMAL_VOL"))\n',
    '    split = max(20, int(len(frame) * .65))\n',
    '    frame["time_env"] = np.where(np.arange(len(frame)) < split, "EARLIER", "RECENT")\n',
    '    if isinstance(priority_table, pd.DataFrame) and not priority_table.empty:\n',
    '        p = priority_table.copy(deep=False)\n',
    '        tcol = next((c for c in ("Time", "time", "DateTime", "timestamp") if c in p), None)\n',
    '        if tcol:\n',
    '            p["__time"] = pd.to_datetime(p[tcol], errors="coerce", utc=True)\n',
    '            p = p.dropna(subset=["__time"]).set_index("__time").sort_index()\n',
    '            aliases = {\n',
    '                "master": ("Master /10", "Master"), "entry": ("Entry /10", "Entry"),\n',
    '                "exit_risk": ("Exit Risk /10", "Exit Risk"), "buy_score": ("BUY /10", "BUY Score"),\n',
    '                "sell_score": ("SELL /10", "SELL Score"),\n',
    '            }\n',
    '            for name, cols in aliases.items():\n',
    '                col = next((c for c in cols if c in p), None)\n',
    '                if col:\n',
]
