"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Ten-paper causal research calibration for the existing ADX Quant Pro pipeline.\n',
    '\n',
    'The layer is deliberately additive and Streamlit-independent.  It consumes only\n',
    'completed EURUSD H1 rows, the already-built canonical result, the existing\n',
    'PowerBI red/yellow/blue bundle, and settled prediction outcomes.  It never\n',
    'recalculates or replaces Full Metric History, the existing regime labels,\n',
    'KNN/Greedy formulas, NLP, or the central PowerBI path.\n',
    '\n',
    'Implemented ideas\n',
    '-----------------\n',
    '* Adaptive conformal coverage control under distribution shift.\n',
    '* Causal time-series conformal residual-vector bootstrapping.\n',
    '* Lightweight Bayesian online changepoint/run-length inference.\n',
    '* Adaptive estimation windows with drift-triggered shrink/growth.\n',
    '* Conditional model confidence sets and bounded dynamic model averaging.\n',
    '* PBO/DSR validation gates that return honest UNAVAILABLE states when required\n',
    '  configuration/return data do not exist.\n',
    '* Aleatoric/epistemic uncertainty separation.\n',
    '* Naive, drift, session-linear and DLinear-style challenger baselines.\n',
    '\n',
    'No heavy model is trained during rendering.  The public entry point is intended\n',
    'to run once inside Settings -> Run Calculation, after all protected calculations\n',
    'are complete and before atomic canonical publication.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from copy import deepcopy\n',
    'from dataclasses import dataclass\n',
    'from hashlib import sha256\n',
    'import json\n',
    'import math\n',
    'import os\n',
    'from pathlib import Path\n',
    'import sqlite3\n',
    'import threading\n',
    'import time\n',
    'from typing import Any, Dict, Iterable, Mapping, MutableMapping, Optional, Sequence\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'RESEARCH_VERSION = "ten-paper-causal-calibration-20260618-v1"\n',
    'RESEARCH_SCHEMA_VERSION = "adx-research-calibration-1.0.0"\n',
    'HORIZONS = (1, 2, 3, 4, 5, 6)\n',
    'TARGET_COVERAGE = 0.80\n',
    'PROJECT_ROOT = Path(__file__).resolve().parents[1]\n',
    'DEFAULT_DB_PATH = PROJECT_ROOT / "data" / "quant_app.sqlite3"\n',
    '_DB_LOCK = threading.RLock()\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Safe primitives and canonical completed data\n',
    '# ---------------------------------------------------------------------------\n',
    'def _finite(value: Any, default: Optional[float] = 0.0) -> Optional[float]:\n',
    '    try:\n',
    '        number = float(value)\n',
    '        return number if math.isfinite(number) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(value: Any, low: float, high: float, default: Optional[float] = None) -> float:\n',
    '    fallback = low if default is None else default\n',
    '    return float(max(low, min(high, _finite(value, fallback) or fallback)))\n',
    '\n',
    '\n',
    'def _normal_cdf(value: float) -> float:\n',
    '    return 0.5 * (1.0 + math.erf(float(value) / math.sqrt(2.0)))\n',
    '\n',
    '\n',
    'def _json_scalar(value: Any) -> Any:\n',
    '    if value is None or value is pd.NA or value is pd.NaT:\n',
    '        return None\n',
    '    if isinstance(value, pd.Timestamp):\n',
    '        ts = value\n',
    '        if pd.isna(ts):\n',
    '            return None\n',
    '        if ts.tzinfo is None:\n',
    '            ts = ts.tz_localize("UTC")\n',
    '        else:\n',
    '            ts = ts.tz_convert("UTC")\n',
    '        return ts.isoformat()\n',
    '    if isinstance(value, np.integer):\n',
    '        return int(value)\n',
    '    if isinstance(value, np.floating):\n',
    '        return float(value) if np.isfinite(value) else None\n',
    '    if isinstance(value, np.bool_):\n',
    '        return bool(value)\n',
    '    try:\n',
    '        if pd.isna(value):\n',
    '            return None\n',
    '    except Exception:\n',
    '        pass\n',
    '    return value\n',
    '\n',
    '\n',
    'def _json_safe(value: Any) -> Any:\n',
    '    if isinstance(value, Mapping):\n',
    '        return {str(k): _json_safe(v) for k, v in value.items()}\n',
    '    if isinstance(value, (list, tuple)):\n',
    '        return [_json_safe(v) for v in value]\n',
    '    if isinstance(value, np.ndarray):\n',
    '        return [_json_safe(v) for v in value.tolist()]\n',
    '    if isinstance(value, pd.DataFrame):\n',
    '        return [_json_safe(row) for row in value.to_dict("records")]\n',
    '    if isinstance(value, pd.Series):\n',
    '        return [_json_safe(v) for v in value.tolist()]\n',
    '    return _json_scalar(value)\n',
    '\n',
    '\n',
    'def _hash_payload(value: Any) -> str:\n',
    '    raw = json.dumps(_json_safe(value), sort_keys=True, separators=(",", ":"), ensure_ascii=False, default=str)\n',
    '    return sha256(raw.encode("utf-8", errors="ignore")).hexdigest()\n',
    '\n',
    '\n',
    'def _find_col(frame: pd.DataFrame, aliases: Iterable[str]) -> Optional[str]:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return None\n',
    '    normalized = {"".join(ch for ch in str(c).lower() if ch.isalnum()): c for c in frame.columns}\n',
    '    for alias in aliases:\n',
    '        key = "".join(ch for ch in str(alias).lower() if ch.isalnum())\n',
    '        if key in normalized:\n',
    '            return normalized[key]\n',
    '    for alias in aliases:\n',
    '        key = "".join(ch for ch in str(alias).lower() if ch.isalnum())\n',
    '        for name, column in normalized.items():\n',
    '            if key and key in name:\n',
    '                return column\n',
    '    return None\n',
    '\n',
    '\n',
    'def normalize_completed_ohlc(data: pd.DataFrame, latest_completed: Any = None) -> pd.DataFrame:\n',
    '    """Return a causal, sorted, de-duplicated completed-H1 frame.\n',
    '\n',
    "    No timestamps are invented, no future backfill is used, and the caller's\n",
    '    frame is not mutated.  ``latest_completed`` is the immutable canonical cutoff.\n',
    '    """\n',
    '    if not isinstance(data, pd.DataFrame) or data.empty:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close"])\n',
    '    t = _find_col(data, ("time", "datetime", "timestamp", "date"))\n',
    '    c = _find_col(data, ("close", "c"))\n',
    '    if t is None or c is None:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close"])\n',
    '    o = _find_col(data, ("open", "o")); h = _find_col(data, ("high", "h")); l = _find_col(data, ("low", "l"))\n',
    '    close = pd.to_numeric(data[c], errors="coerce")\n',
    '    out = pd.DataFrame({"time": pd.to_datetime(data[t], errors="coerce", utc=True), "close": close})\n',
    '    out["open"] = pd.to_numeric(data[o], errors="coerce") if o else close\n',
    '    out["high"] = pd.to_numeric(data[h], errors="coerce") if h else out[["open", "close"]].max(axis=1)\n',
    '    out["low"] = pd.to_numeric(data[l], errors="coerce") if l else out[["open", "close"]].min(axis=1)\n',
    '    out = out.dropna(subset=["time", "open", "high", "low", "close"])\n',
    '    out = out.sort_values("time", kind="stable").drop_duplicates("time", keep="last")\n',
    '    if latest_completed not in (None, ""):\n',
    '        cutoff = pd.to_datetime(latest_completed, errors="coerce", utc=True)\n',
    '        if pd.notna(cutoff):\n',
    '            out = out.loc[out["time"] <= cutoff]\n',
    '    out["high"] = out[["open", "high", "low", "close"]].max(axis=1)\n',
    '    out["low"] = out[["open", "high", "low", "close"]].min(axis=1)\n',
    '    return out.reset_index(drop=True)\n',
    '\n',
    '\n',
    'def data_hash(frame: pd.DataFrame) -> str:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return "NO_DATA"\n',
    '    selected = frame[[c for c in ("time", "open", "high", "low", "close") if c in frame.columns]]\n',
    '    return sha256(pd.util.hash_pandas_object(selected, index=False).values.tobytes()).hexdigest()\n',
    '\n',
    '\n',
    'def _calculation_id(canonical: Mapping[str, Any], frame_hash: str, latest: str, input_hash: str = "") -> str:\n',
    '    raw = "|".join([\n',
    '        str(canonical.get("symbol") or "EURUSD").upper(),\n',
    '        str(canonical.get("timeframe") or "H1").upper(),\n',
    '        str(latest), frame_hash, str(input_hash), RESEARCH_VERSION,\n',
    '    ])\n',
    '    return "RCALC-" + sha256(raw.encode("utf-8", errors="ignore")).hexdigest()[:24]\n',
    '\n',
    '\n',
    'def _session_label(value: Any) -> str:\n',
    '    ts = pd.to_datetime(value, errors="coerce", utc=True)\n',
    '    if pd.isna(ts):\n',
    '        return "UNKNOWN"\n',
    '    hour = int(ts.hour)\n',
    '    if 0 <= hour < 7:\n',
    '        return "ASIAN"\n',
    '    if 7 <= hour < 12:\n',
    '        return "LONDON"\n',
    '    if 12 <= hour < 16:\n',
    '        return "LONDON_NEW_YORK_OVERLAP"\n',
    '    if 16 <= hour < 21:\n',
    '        return "NEW_YORK"\n',
    '    return "OTHER"\n',
    '\n',
    '\n',
    'def _direction(value: Any) -> str:\n',
    '    text = str(value or "").upper()\n',
    '    if any(token in text for token in ("BUY", "BULL", "UP")):\n',
    '        return "BUY"\n',
    '    if any(token in text for token in ("SELL", "BEAR", "DOWN")):\n',
    '        return "SELL"\n',
    '    return "NEUTRAL"\n',
    '\n',
    '\n',
    'def _atr(frame: pd.DataFrame, window: int = 24) -> float:\n',
    '    if frame.empty:\n',
    '        return 0.0005\n',
    '    previous = frame["close"].shift(1)\n',
    '    tr = pd.concat([\n',
    '        (frame["high"] - frame["low"]).abs(),\n',
    '        (frame["high"] - previous).abs(),\n',
    '        (frame["low"] - previous).abs(),\n',
    '    ], axis=1).max(axis=1)\n',
    '    value = _finite(tr.tail(max(4, window)).median(), 0.0005)\n',
    '    return max(float(value or 0.0005), 1e-9)\n',
    '\n',
    '\n',
    'def purged_walk_forward_splits(\n',
    '    row_count: int, *, minimum_train: int = 96, validation_size: int = 24,\n',
    '    maximum_horizon: int = 6, embargo: Optional[int] = None,\n',
    ') -> list[Dict[str, Any]]:\n',
    '    """Create chronological validation splits with purge and embargo.\n',
    '\n',
    '    Training targets end before the validation feature window and an embargo of\n',
    '    at least the maximum forecast horizon separates consecutive validation uses.\n',
    '    """\n',
    '    count = max(0, int(row_count))\n',
    '    purge = max(1, int(maximum_horizon))\n',
    '    embargo_size = max(purge, int(embargo if embargo is not None else purge))\n',
    '    train_min = max(purge * 4, int(minimum_train))\n',
    '    valid_size = max(purge + 1, int(validation_size))\n',
    '    splits: list[Dict[str, Any]] = []\n',
    '    validation_start = train_min + purge\n',
    '    split_id = 0\n',
    '    while validation_start + valid_size <= count:\n',
    '        train_end_exclusive = validation_start - purge\n',
    '        validation_end_exclusive = validation_start + valid_size\n',
    '        splits.append({\n',
    '            "split_id": split_id,\n',
    '            "train_start": 0,\n',
    '            "train_end_exclusive": train_end_exclusive,\n',
    '            "validation_start": validation_start,\n',
    '            "validation_end_exclusive": validation_end_exclusive,\n',
    '            "purging_period": purge,\n',
    '            "embargo_period": embargo_size,\n',
    '            "maximum_forecast_horizon": purge,\n',
    '            "targets_overlap": False,\n',
    '        })\n',
    '        split_id += 1\n',
    '        validation_start = validation_end_exclusive + embargo_size\n',
    '    return splits\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 10: challenger baselines and causal walk-forward evaluation\n',
    '# ---------------------------------------------------------------------------\n',
    'def _linear_extrapolation(values: np.ndarray, horizon: int, lookback: int) -> np.ndarray:\n',
    '    values = np.asarray(values, dtype=float)\n',
    '    values = values[np.isfinite(values)]\n',
    '    if len(values) < 4:\n',
    '        return np.repeat(values[-1] if len(values) else 0.0, horizon)\n',
    '    use = values[-min(lookback, len(values)):]\n',
    '    x = np.arange(len(use), dtype=float)\n',
    '    slope, intercept = np.polyfit(x, use, 1)\n',
    '    future_x = np.arange(len(use), len(use) + horizon, dtype=float)\n',
    '    return intercept + slope * future_x\n',
    '\n',
    '\n',
    'def _baseline_paths(frame: pd.DataFrame, horizon: int = 6) -> Dict[str, list[float]]:\n',
    '    close = frame["close"].to_numpy(dtype=float)\n',
    '    anchor = float(close[-1])\n',
    '    atr = _atr(frame)\n',
    '    returns = pd.Series(close).pct_change().dropna()\n',
    '    recent_return = _finite(returns.tail(48).mean(), 0.0) or 0.0\n',
    '    recent_return = _clip(recent_return, -atr / max(abs(anchor), 1e-12), atr / max(abs(anchor), 1e-12), 0.0)\n',
    '\n',
    '    naive = np.repeat(anchor, horizon)\n',
    '    drift = np.asarray([anchor * (1.0 + recent_return * step) for step in range(1, horizon + 1)], dtype=float)\n',
    '\n',
    '    current_session = _session_label(frame["time"].iloc[-1])\n',
    '    current_hour = int(pd.Timestamp(frame["time"].iloc[-1]).hour)\n',
    '    session_returns: Dict[int, float] = {}\n',
    '    for step in range(1, horizon + 1):\n',
    '        values: list[float] = []\n',
    '        latest_origin = len(frame) - step - 1\n',
    '        for index in range(max(0, latest_origin - 1500), latest_origin + 1):\n',
    '            ts = frame["time"].iloc[index]\n',
    '            if _session_label(ts) != current_session:\n',
    '                continue\n',
    '            hour_distance = min((int(pd.Timestamp(ts).hour) - current_hour) % 24, (current_hour - int(pd.Timestamp(ts).hour)) % 24)\n',
    '            if hour_distance > 1:\n',
    '                continue\n',
    '            base = float(frame["close"].iloc[index])\n',
    '            target = float(frame["close"].iloc[index + step])\n',
    '            if base:\n',
    '                values.append(target / base - 1.0)\n',
    '        session_returns[step] = float(np.median(values)) if len(values) >= 12 else recent_return * step\n',
    '    session_linear = np.asarray([anchor * (1.0 + session_returns[step]) for step in range(1, horizon + 1)], dtype=float)\n',
    '\n',
    '    trend = pd.Series(close).rolling(24, min_periods=8).mean().to_numpy(dtype=float)\n',
    '    valid_trend = pd.Series(trend).dropna().to_numpy(dtype=float)\n',
    '    if len(valid_trend) < 8:\n',
    '        valid_trend = close.copy()\n',
    '    trend_full = pd.Series(trend).ffill().fillna(pd.Series(close)).to_numpy(dtype=float)\n',
    '    remainder = close - trend_full\n',
    '    trend_forecast = _linear_extrapolation(valid_trend, horizon, 96)\n',
    '    remainder_forecast = _linear_extrapolation(remainder, horizon, 48)\n',
    '    dlinear = trend_forecast + remainder_forecast\n',
    '\n',
    '    maximum_step = atr * 2.5\n',
    '    result: Dict[str, list[float]] = {}\n',
    '    for name, values in {\n',
    '        "naive_last_close": naive,\n',
    '        "drift": drift,\n',
    '        "session_linear": session_linear,\n',
    '        "dlinear_style": dlinear,\n',
    '    }.items():\n',
    '        bounded: list[float] = []\n',
    '        previous = anchor\n',
    '        for raw in values:\n',
    '            value = previous + _clip(float(raw) - previous, -maximum_step, maximum_step, 0.0)\n',
    '            value = max(value, 1e-9)\n',
    '            bounded.append(float(value)); previous = value\n',
    '        result[name] = bounded\n',
    '    return result\n',
    '\n',
    '\n',
    'def build_baseline_forecasts(frame: pd.DataFrame, horizon: int = 6) -> Dict[str, Any]:\n',
    '    market = normalize_completed_ohlc(frame)\n',
    '    if len(market) < 30:\n',
    '        return {"status": "INSUFFICIENT SAMPLE", "sample_size": int(len(market)), "paths": {}}\n',
    '    paths = _baseline_paths(market, horizon=horizon)\n',
    '    return {\n',
    '        "status": "VALID", "sample_size": int(len(market)), "anchor_price": float(market["close"].iloc[-1]),\n',
    '        "anchor_time": _json_scalar(market["time"].iloc[-1]), "paths": {name: [round(v, 8) for v in values] for name, values in paths.items()},\n',
    '        "causal_policy": "past-only rolling decomposition and same-session completed outcomes",\n',
    '    }\n',
    '\n',
    '\n',
    'def _walk_forward_baseline_vectors(\n',
    '    frame: pd.DataFrame, max_origins: int = 180,\n',
    ') -> tuple[np.ndarray, Dict[str, Dict[int, np.ndarray]], pd.DataFrame]:\n',
    '    """Causal walk-forward residual vectors and origin metadata.\n',
    '\n',
    '    Each origin uses only rows at or before that origin.  The metadata permits\n',
    '    condition-aware residual selection without breaking the H+1..H+6 vector.\n',
    '    """\n',
    '    market = normalize_completed_ohlc(frame)\n',
    '    if len(market) < 90:\n',
    '        return np.empty((0, 6), dtype=float), {}, pd.DataFrame()\n',
    '    start = max(60, len(market) - max_origins - max(HORIZONS))\n',
    '    vectors: list[list[float]] = []\n',
    '    metadata: list[Dict[str, Any]] = []\n',
    '    model_errors: Dict[str, Dict[int, list[float]]] = {\n',
    '        name: {h: [] for h in HORIZONS} for name in ("naive_last_close", "drift", "session_linear", "dlinear_style")\n',
    '    }\n',
    '    for origin in range(start, len(market) - max(HORIZONS)):\n',
    '        train = market.iloc[: origin + 1]\n',
    '        paths = _baseline_paths(train, horizon=max(HORIZONS))\n',
    '        dlinear_vector: list[float] = []\n',
    '        for h in HORIZONS:\n',
    '            actual = float(market["close"].iloc[origin + h])\n',
    '            for name, path in paths.items():\n',
    '                model_errors[name][h].append(actual - float(path[h - 1]))\n',
    '            dlinear_vector.append(actual - float(paths["dlinear_style"][h - 1]))\n',
    '        vectors.append(dlinear_vector)\n',
    '        returns = train["close"].pct_change()\n',
    '        rolling_vol = returns.rolling(24, min_periods=8).std(ddof=0).dropna()\n',
    '        current_vol = float(rolling_vol.iloc[-1]) if len(rolling_vol) else 0.0\n',
    '        past_vol = rolling_vol.iloc[:-1] if len(rolling_vol) > 1 else rolling_vol\n',
    '        q60 = float(past_vol.quantile(0.60)) if len(past_vol) >= 12 else current_vol\n',
    '        q85 = float(past_vol.quantile(0.85)) if len(past_vol) >= 12 else current_vol\n',
    '        vol_regime = "CALM" if current_vol <= q60 else "TURBULENT" if current_vol <= q85 else "CRISIS"\n',
    '        anchor = float(train["close"].iloc[-1])\n',
    '        direction = "BUY" if paths["dlinear_style"][-1] > anchor else "SELL" if paths["dlinear_style"][-1] < anchor else "NEUTRAL"\n',
    '        metadata.append({\n',
    '            "origin_time": _json_scalar(train["time"].iloc[-1]),\n',
    '            "session": _session_label(train["time"].iloc[-1]),\n',
    '            "volatility_regime": vol_regime,\n',
    '            "direction": direction,\n',
    '            "realized_volatility": current_vol,\n',
    '            "source": "DLINEAR_WALK_FORWARD_FALLBACK",\n',
    '        })\n',
    '    arrays = {name: {h: np.asarray(values, dtype=float) for h, values in per_h.items()} for name, per_h in model_errors.items()}\n',
    '    return np.asarray(vectors, dtype=float), arrays, pd.DataFrame(metadata)\n',
    '\n',
    'def _normalized_prediction_history(history: pd.DataFrame) -> pd.DataFrame:\n',
    '    """Normalize completed forecast outcomes without inventing unavailable fields."""\n',
    '    if not isinstance(history, pd.DataFrame) or history.empty:\n',
    '        return pd.DataFrame()\n',
    '    predicted_col = _find_col(history, ("predicted price", "pred close", "predicted close", "point forecast", "central"))\n',
    '    actual_col = _find_col(history, ("actual price", "actual close", "actual completed close"))\n',
    '    target_col = _find_col(history, ("actual time", "target time", "target completion time", "time"))\n',
    '    prediction_time_col = _find_col(history, ("prediction time", "prediction creation time", "created at"))\n',
    '    horizon_col = _find_col(history, ("horizon hours", "horizon"))\n',
    '    lower_col = _find_col(history, ("lower bound", "lower band", "predicted lower band"))\n',
    '    upper_col = _find_col(history, ("upper bound", "upper band", "predicted upper band"))\n',
    '    current_col = _find_col(history, ("current price", "anchor price"))\n',
    '    direction_col = _find_col(history, ("predicted direction", "direction"))\n',
    '    regime_col = _find_col(history, ("major regime", "directional regime", "regime"))\n',
    '    vol_col = _find_col(history, ("volatility regime",))\n',
    '    transition_col = _find_col(history, ("transition risk", "transition risk 0 100"))\n',
    '    disagreement_col = _find_col(history, ("path disagreement", "source spread"))\n',
    '    reliability_col = _find_col(history, ("reliability at prediction time", "reliability", "confidence"))\n',
    '    realized_vol_col = _find_col(history, ("realized volatility",))\n',
    '    calc_col = _find_col(history, ("calculation id", "run id", "prediction calculation id"))\n',
    '    if predicted_col is None or actual_col is None:\n',
    '        return pd.DataFrame()\n',
    '    target_time = pd.to_datetime(history[target_col], errors="coerce", utc=True) if target_col else pd.Series(pd.NaT, index=history.index)\n',
    '    prediction_time = pd.to_datetime(history[prediction_time_col], errors="coerce", utc=True) if prediction_time_col else pd.Series(pd.NaT, index=history.index)\n',
    '    out = pd.DataFrame({\n',
    '        "calculation_id": history[calc_col].astype(str) if calc_col else "UNKNOWN",\n',
    '        "prediction_time": prediction_time,\n',
    '        "predicted": pd.to_numeric(history[predicted_col], errors="coerce"),\n',
    '        "actual": pd.to_numeric(history[actual_col], errors="coerce"),\n',
    '        "target_time": target_time,\n',
    '        "horizon": pd.to_numeric(history[horizon_col], errors="coerce").fillna(1).astype(int) if horizon_col else 1,\n',
    '        "current_price": pd.to_numeric(history[current_col], errors="coerce") if current_col else np.nan,\n',
    '        "prediction_direction": history[direction_col].map(_direction) if direction_col else "NEUTRAL",\n',
    '        "directional_regime": history[regime_col].astype(str) if regime_col else "UNKNOWN",\n',
    '        "volatility_regime": history[vol_col].astype(str).str.upper() if vol_col else "UNKNOWN",\n',
    '        "transition_risk": pd.to_numeric(history[transition_col], errors="coerce") if transition_col else np.nan,\n',
    '        "path_disagreement": pd.to_numeric(history[disagreement_col], errors="coerce") if disagreement_col else np.nan,\n',
]
