"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '\n',
    '\n',
    'def _model_error_map(residual_bundle: Mapping[str, Any], calibrated_bundle: Optional[Mapping[str, Any]]) -> Dict[str, Dict[int, np.ndarray]]:\n',
    '    error_map: Dict[str, Dict[int, np.ndarray]] = {}\n',
    '    baseline = residual_bundle.get("baseline_errors") or {}\n',
    '    for model, values in baseline.items():\n',
    '        error_map[str(model)] = {int(h): np.asarray(arr, dtype=float) for h, arr in values.items()}\n',
    '    scalar = residual_bundle.get("scalar_bank")\n',
    '    if isinstance(scalar, pd.DataFrame) and not scalar.empty:\n',
    '        error_map["existing_system"] = {}\n',
    '        for h in HORIZONS:\n',
    '            error_map["existing_system"][h] = pd.to_numeric(scalar.loc[scalar["horizon"] == h, "residual"], errors="coerce").dropna().to_numpy(dtype=float)\n',
    '    bundle = calibrated_bundle if isinstance(calibrated_bundle, Mapping) else {}\n',
    '    audit = bundle.get("audit") if isinstance(bundle.get("audit"), Mapping) else {}\n',
    '    residual_samples = dict(audit.get("horizon_residual_samples") or {})\n',
    '    for path in ("red", "yellow", "blue"):\n',
    '        error_map[path] = {}\n',
    '        for h in HORIZONS:\n',
    '            error_map[path][h] = pd.to_numeric(pd.Series(residual_samples.get(f"{path}_H+{h}", [])), errors="coerce").dropna().to_numpy(dtype=float)\n',
    '    return error_map\n',
    '\n',
    '\n',
    'def conditional_method_confidence_set(\n',
    '    error_map: Mapping[str, Mapping[int, np.ndarray]], *, horizon: int, condition: str, minimum_sample: int = 12,\n',
    ') -> Dict[str, Any]:\n',
    '    records: list[Dict[str, Any]] = []\n',
    '    valid_losses: Dict[str, float] = {}\n',
    '    for model, per_h in error_map.items():\n',
    '        stats = _loss_stats(np.asarray(per_h.get(horizon, []), dtype=float))\n',
    '        loss = stats.get("mae")\n',
    '        if stats["sample_size"] >= minimum_sample and loss is not None:\n',
    '            valid_losses[str(model)] = float(loss)\n',
    '        records.append({\n',
    '            "condition": condition, "model_name": str(model), "accepted": False,\n',
    '            "average_loss": None if loss is None else round(float(loss), 10), "relative_loss": None,\n',
    '            "statistical_comparison_status": "INSUFFICIENT DATA" if stats["sample_size"] < minimum_sample else "PENDING",\n',
    '            "sample_size": int(stats["sample_size"]), "insufficient_data": bool(stats["sample_size"] < minimum_sample),\n',
    '        })\n',
    '    if not valid_losses:\n',
    '        return {"condition": condition, "horizon": horizon, "accepted_models": [], "records": records, "fallback_used": True, "status": "INSUFFICIENT DATA"}\n',
    '    best = min(valid_losses.values())\n',
    '    # Conservative equivalence margin approximates a confidence set without\n',
    '    # claiming superiority from a small noisy sample.\n',
    '    for row in records:\n',
    '        model = row["model_name"]\n',
    '        if model not in valid_losses:\n',
    '            continue\n',
    '        relative = valid_losses[model] / max(best, 1e-12) - 1.0\n',
    '        row["relative_loss"] = round(relative, 8)\n',
    '        sample = row["sample_size"]\n',
    '        margin = 0.12 + 0.35 / math.sqrt(max(sample, 1))\n',
    '        row["accepted"] = bool(relative <= margin)\n',
    '        row["statistical_comparison_status"] = "NOT STATISTICALLY INFERIOR" if row["accepted"] else "INFERIOR UNDER CURRENT CONDITION"\n',
    '    accepted = [row["model_name"] for row in records if row["accepted"]]\n',
    '    return {"condition": condition, "horizon": horizon, "accepted_models": accepted, "records": records, "fallback_used": False, "status": "VALID"}\n',
    '\n',
    '\n',
    'def _bounded_normalize(raw: Mapping[str, float], low: float = 0.03, high: float = 0.78) -> Dict[str, float]:\n',
    '    """Project positive scores onto a bounded probability simplex.\n',
    '\n',
    '    A clip-then-renormalize loop can violate the maximum again after the final\n',
    '    normalization.  The monotone bisection below solves\n',
    '    ``sum(clip(lambda * score_i, low, high)) == 1`` and therefore preserves all\n',
    '    bounds and the unit-sum invariant at the same time.\n',
    '    """\n',
    '    positive = {\n',
    '        str(k): max(float(v), 0.0)\n',
    '        for k, v in raw.items()\n',
    '        if math.isfinite(float(v)) and float(v) > 0\n',
    '    }\n',
    '    if not positive:\n',
    '        return {}\n',
    '    count = len(positive)\n',
    '    # Make the requested box feasible for small/large active model sets.\n',
    '    lower = min(max(float(low), 0.0), 1.0 / count)\n',
    '    upper = max(min(float(high), 1.0), 1.0 / count)\n',
    '    values = np.asarray(list(positive.values()), dtype=float)\n',
    '\n',
    '    def mass(multiplier: float) -> float:\n',
    '        return float(np.clip(multiplier * values, lower, upper).sum())\n',
    '\n',
    '    left, right = 0.0, 1.0\n',
    '    while mass(right) < 1.0:\n',
    '        right *= 2.0\n',
    '        if right > 1e18:  # Defensive fallback; feasibility is guaranteed above.\n',
    '            break\n',
    '    for _ in range(100):\n',
    '        middle = (left + right) / 2.0\n',
    '        if mass(middle) < 1.0:\n',
    '            left = middle\n',
    '        else:\n',
    '            right = middle\n',
    '    projected = np.clip(((left + right) / 2.0) * values, lower, upper)\n',
    '    # Floating-point correction is distributed only over coordinates with room.\n',
    '    difference = 1.0 - float(projected.sum())\n',
    '    for _ in range(count + 2):\n',
    '        if abs(difference) <= 1e-14:\n',
    '            break\n',
    '        if difference > 0:\n',
    '            eligible = np.where(projected < upper - 1e-14)[0]\n',
    '        else:\n',
    '            eligible = np.where(projected > lower + 1e-14)[0]\n',
    '        if len(eligible) == 0:\n',
    '            break\n',
    '        increment = difference / len(eligible)\n',
    '        projected[eligible] = np.clip(projected[eligible] + increment, lower, upper)\n',
    '        difference = 1.0 - float(projected.sum())\n',
    '    return {key: float(value) for key, value in zip(positive.keys(), projected)}\n',
    '\n',
    '\n',
    'def dynamic_model_averaging(\n',
    '    confidence_set: Mapping[str, Any], error_map: Mapping[str, Mapping[int, np.ndarray]], *,\n',
    '    horizon: int, previous: Optional[Mapping[str, Any]] = None, forgetting_factor: float = 0.92,\n',
    ') -> Dict[str, Any]:\n',
    '    accepted = list(confidence_set.get("accepted_models") or [])\n',
    '    eligible_fallback_used = False\n',
    '    valid_candidates = []\n',
    '    for model, per_h in error_map.items():\n',
    '        stats = _loss_stats(np.asarray(per_h.get(horizon, []), dtype=float))\n',
    '        if stats.get("mae") is not None and stats.get("sample_size", 0) >= 4:\n',
    '            valid_candidates.append((str(model), float(stats["mae"])))\n',
    '    valid_candidates.sort(key=lambda item: item[1])\n',
    '    # A one-model ensemble would violate the anti-concentration invariant and\n',
    '    # would falsely imply certainty.  Broaden to the nearest valid fallback\n',
    '    # condition/model when the strict confidence set contains fewer than two.\n',
    '    if len(accepted) < 2:\n',
    '        for model, _ in valid_candidates:\n',
    '            if model not in accepted:\n',
    '                accepted.append(model)\n',
    '            if len(accepted) >= 2:\n',
    '                break\n',
    '        eligible_fallback_used = True\n',
    '    losses = {}\n',
    '    samples = {}\n',
    '    for model in accepted:\n',
    '        stats = _loss_stats(np.asarray((error_map.get(model) or {}).get(horizon, []), dtype=float))\n',
    '        if stats.get("mae") is not None:\n',
    '            losses[model] = float(stats["mae"]); samples[model] = int(stats["sample_size"])\n',
    '    if len(losses) < 2:\n',
    '        return {\n',
    '            "status": "INSUFFICIENT DATA", "horizon": horizon, "weights": {}, "records": [],\n',
    '            "eligibility_fallback_used": eligible_fallback_used,\n',
    '            "unavailable_reason": "Need at least two eligible models to avoid a 100% single-model weight",\n',
    '        }\n',
    '    evidence_hash = _hash_payload({"horizon": horizon, "condition": confidence_set.get("condition"), "losses": losses, "samples": samples})\n',
    '    if isinstance(previous, Mapping) and previous.get("evidence_hash") == evidence_hash:\n',
    '        reused = deepcopy(dict(previous))\n',
    '        reused["cache_status"] = "REUSED_SAME_COMPLETED_EVIDENCE"\n',
    '        return reused\n',
    '    scale = max(float(np.median(list(losses.values()))), 1e-12)\n',
    '    probabilities = {model: math.exp(-loss / scale) for model, loss in losses.items()}\n',
    '    maximum = max(probabilities.values())\n',
    '    previous_records = {row.get("model_name"): row for row in ((previous or {}).get("records") or []) if isinstance(row, Mapping)}\n',
    '    active_scores: Dict[str, float] = {}\n',
    '    records: list[Dict[str, Any]] = []\n',
    '    for model, probability in probabilities.items():\n',
    '        old = previous_records.get(model) or {}\n',
    '        old_weight = float(old.get("updated_weight", 1.0 / len(probabilities)))\n',
    '        suppressed = bool(probability < maximum * 0.15 and samples.get(model, 0) >= 12)\n',
    '        score = forgetting_factor * old_weight + (1.0 - forgetting_factor) * probability\n',
    '        if not suppressed:\n',
    '            active_scores[model] = score\n',
    '        records.append({\n',
    '            "model_name": model, "condition": confidence_set.get("condition"), "previous_weight": round(old_weight, 8),\n',
    '            "updated_weight": 0.0, "conditional_loss": round(losses[model], 10),\n',
    '            "conditional_probability": round(probability, 10), "active": not suppressed, "suppressed": suppressed,\n',
    '            "suppression_reason": "Outside Dynamic Occam\'s Window" if suppressed else None,\n',
    '            "sample_size": samples.get(model, 0),\n',
    '            "reactivated": bool(old.get("suppressed") and not suppressed),\n',
    '        })\n',
    '    weights = _bounded_normalize(active_scores)\n',
    '    for row in records:\n',
    '        row["updated_weight"] = round(weights.get(row["model_name"], 0.0), 10)\n',
    '    return {\n',
    '        "status": "VALID", "horizon": horizon, "condition": confidence_set.get("condition"),\n',
    '        "weights": weights, "records": records, "weight_sum": round(sum(weights.values()), 12),\n',
    '        "forgetting_factor": forgetting_factor, "minimum_weight": 0.03, "maximum_weight": 0.78,\n',
    '        "evidence_hash": evidence_hash, "cache_status": "UPDATED",\n',
    '        "eligibility_fallback_used": eligible_fallback_used,\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Papers 7 and 8: PBO and DSR validation gates\n',
    '# ---------------------------------------------------------------------------\n',
    'def probability_backtest_overfitting(performance_matrix: Any, metric_used: str = "net_return") -> Dict[str, Any]:\n',
    '    matrix = np.asarray(performance_matrix, dtype=float)\n',
    '    if matrix.ndim != 2 or matrix.shape[0] < 4 or matrix.shape[1] < 4:\n',
    '        return {\n',
    '            "value": None, "status": "UNAVAILABLE", "unavailable_reason": "Need at least 4 chronological periods and 4 tested configurations",\n',
    '            "number_of_periods": int(matrix.shape[0]) if matrix.ndim == 2 else 0,\n',
    '            "number_of_configurations": int(matrix.shape[1]) if matrix.ndim == 2 else 0,\n',
    '            "split_count": 0, "metric_used": metric_used,\n',
    '        }\n',
    '    periods = matrix.shape[0]\n',
    '    split_size = periods // 2\n',
    '    split_count = 0; below_median = 0\n',
    '    # Deterministic symmetric chronological combinations, bounded for speed.\n',
    '    import itertools\n',
    '    combinations = list(itertools.combinations(range(periods), split_size))\n',
    '    if len(combinations) > 200:\n',
    '        positions = np.linspace(0, len(combinations) - 1, 200, dtype=int)\n',
    '        combinations = [combinations[i] for i in positions]\n',
    '    seen: set[tuple[int, ...]] = set()\n',
    '    for insample in combinations:\n',
    '        if insample in seen:\n',
    '            continue\n',
    '        outsample = tuple(i for i in range(periods) if i not in insample)\n',
    '        seen.add(insample); seen.add(outsample)\n',
    '        in_scores = np.nanmean(matrix[list(insample)], axis=0)\n',
    '        out_scores = np.nanmean(matrix[list(outsample)], axis=0)\n',
    '        if not np.isfinite(in_scores).any() or not np.isfinite(out_scores).any():\n',
    '            continue\n',
    '        winner = int(np.nanargmax(in_scores))\n',
    '        ranks = pd.Series(out_scores).rank(method="average", pct=True).to_numpy(dtype=float)\n',
    '        if ranks[winner] < 0.5:\n',
    '            below_median += 1\n',
    '        split_count += 1\n',
    '    if split_count == 0:\n',
    '        return {"value": None, "status": "UNAVAILABLE", "unavailable_reason": "No valid symmetric splits", "number_of_periods": periods, "number_of_configurations": matrix.shape[1], "split_count": 0, "metric_used": metric_used}\n',
    '    value = below_median / split_count\n',
    '    return {\n',
    '        "value": round(float(value), 8), "status": "VALID", "unavailable_reason": None,\n',
    '        "number_of_periods": periods, "number_of_configurations": matrix.shape[1], "split_count": split_count,\n',
    '        "metric_used": metric_used, "validation_label": "HIGH OVERFITTING RISK" if value > 0.50 else "WATCH" if value > 0.25 else "ACCEPTABLE",\n',
    '    }\n',
    '\n',
    '\n',
    'def deflated_sharpe_ratio(\n',
    '    strategy_returns: Optional[Sequence[float]], *, number_of_trials: Optional[int], sharpe_trials: Optional[Sequence[float]] = None,\n',
    ') -> Dict[str, Any]:\n',
    '    return_values = [] if strategy_returns is None else list(strategy_returns)\n',
    '    values = np.asarray(return_values, dtype=float)\n',
    '    values = values[np.isfinite(values)]\n',
    '    trials = int(number_of_trials or 0)\n',
    '    trial_sequence = [] if sharpe_trials is None else list(sharpe_trials)\n',
    '    trial_values = np.asarray(trial_sequence, dtype=float)\n',
    '    trial_values = trial_values[np.isfinite(trial_values)]\n',
    '    if len(values) < 30:\n',
    '        return {"raw_sharpe": None, "deflated_sharpe_statistic": None, "deflated_sharpe_probability": None, "number_of_trials": trials, "sample_size": int(len(values)), "skewness": None, "kurtosis": None, "validation_label": "UNAVAILABLE", "unavailable_reason": "Need at least 30 aligned actual strategy returns"}\n',
    '    if trials < 2 or len(trial_values) < 2:\n',
    '        return {"raw_sharpe": None, "deflated_sharpe_statistic": None, "deflated_sharpe_probability": None, "number_of_trials": trials, "sample_size": int(len(values)), "skewness": None, "kurtosis": None, "validation_label": "UNAVAILABLE", "unavailable_reason": "Need the number and Sharpe distribution of tested strategies/configurations"}\n',
    '    mean = float(np.mean(values)); std = float(np.std(values, ddof=1))\n',
    '    if std <= 0:\n',
    '        return {"raw_sharpe": None, "deflated_sharpe_statistic": None, "deflated_sharpe_probability": None, "number_of_trials": trials, "sample_size": int(len(values)), "skewness": None, "kurtosis": None, "validation_label": "UNAVAILABLE", "unavailable_reason": "Return variance is zero"}\n',
    '    centered = (values - mean) / std\n',
    '    skewness = float(np.mean(centered ** 3)); kurtosis = float(np.mean(centered ** 4))\n',
    '    raw_sharpe = mean / std * math.sqrt(252.0)\n',
    '    trial_std = max(float(np.std(trial_values, ddof=1)), 1e-12)\n',
    '    # Expected maximum Sharpe approximation under multiple testing.\n',
    '    expected_max = float(np.mean(trial_values) + trial_std * math.sqrt(2.0 * math.log(max(trials, 2))))\n',
    '    denominator = math.sqrt(max((1.0 - skewness * raw_sharpe + (kurtosis - 1.0) * raw_sharpe ** 2 / 4.0) / max(len(values) - 1, 1), 1e-12))\n',
    '    statistic = (raw_sharpe - expected_max) / denominator\n',
    '    probability = _normal_cdf(statistic)\n',
    '    return {\n',
    '        "raw_sharpe": round(raw_sharpe, 8), "deflated_sharpe_statistic": round(statistic, 8),\n',
    '        "deflated_sharpe_probability": round(probability, 8), "number_of_trials": trials,\n',
    '        "sample_size": int(len(values)), "skewness": round(skewness, 8), "kurtosis": round(kurtosis, 8),\n',
    '        "validation_label": "ACCEPT" if probability >= 0.95 else "WEAK" if probability >= 0.70 else "REJECT",\n',
    '        "unavailable_reason": None,\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 9: aleatoric / epistemic uncertainty\n',
    '# ---------------------------------------------------------------------------\n',
    'def uncertainty_scores(\n',
    '    frame: pd.DataFrame, conformal: Mapping[str, Any], calibrated_bundle: Optional[Mapping[str, Any]],\n',
    '    conditional_set: Mapping[str, Any], dma: Mapping[str, Any], changepoint: Mapping[str, Any], nlp: Optional[Mapping[str, Any]] = None,\n',
    ') -> Dict[str, Any]:\n',
    '    market = normalize_completed_ohlc(frame)\n',
    '    atr = _atr(market)\n',
    '    anchor = float(market["close"].iloc[-1]) if not market.empty else 1.0\n',
    '    returns = market["close"].pct_change().dropna()\n',
    '    realized = float(returns.tail(24).std(ddof=0)) if len(returns) else 0.0\n',
    '    range_ratio = float(((market["high"] - market["low"]).abs() / market["close"].replace(0, np.nan)).tail(24).median()) if not market.empty else 0.0\n',
    '    horizons = list(conformal.get("horizons") or [])\n',
    '    width = float(np.mean([(row.get("upper_band", anchor) - row.get("lower_band", anchor)) / max(abs(anchor), 1e-12) for row in horizons])) if horizons else 0.0\n',
    '    residual_count = int(conformal.get("residual_vector_count", 0) or 0)\n',
    '    nlp_importance = _clip((nlp or {}).get("importance", 0.0), 0.0, 1.0, 0.0)\n',
    '    aleatoric = _clip(100.0 * (0.32 * min(realized / 0.0025, 1.0) + 0.22 * min(range_ratio / 0.0035, 1.0) + 0.31 * min(width / 0.008, 1.0) + 0.15 * nlp_importance), 0, 100, 50)\n',
    '\n',
    '    bundle = calibrated_bundle if isinstance(calibrated_bundle, Mapping) else {}\n',
    '    summary = bundle.get("summary") if isinstance(bundle.get("summary"), Mapping) else {}\n',
    '    disagreement = 1.0 - _clip(summary.get("path_agreement_pct", 50.0), 0, 100, 50) / 100.0\n',
    '    eligible_count = len(conditional_set.get("accepted_models") or [])\n',
    '    sample_penalty = 1.0 - min(residual_count / 60.0, 1.0)\n',
    '    weights = list((dma.get("weights") or {}).values())\n',
    '    instability = float(np.std(weights) / max(np.mean(weights), 1e-12)) if len(weights) > 1 else (1.0 if not weights else 0.4)\n',
    '    transition = _clip(changepoint.get("transition_risk_0_100", 50.0), 0, 100, 50) / 100.0\n',
    '    epistemic = _clip(100.0 * (0.33 * disagreement + 0.25 * sample_penalty + 0.18 * min(instability, 1.0) + 0.14 * (1.0 if eligible_count == 0 else 1.0 / eligible_count) + 0.10 * transition), 0, 100, 50)\n',
    '    combined = _clip(0.54 * aleatoric + 0.46 * epistemic, 0, 100, 50)\n',
    '    if aleatoric >= epistemic + 12:\n',
    '        source = "MARKET"\n',
    '    elif epistemic >= aleatoric + 12:\n',
    '        source = "MODEL"\n',
    '    elif combined < 35:\n',
    '        source = "LOW"\n',
    '    else:\n',
    '        source = "BOTH"\n',
    '    explanation = {\n',
    '        "MARKET": "Observed volatility, ranges and empirical interval width dominate.",\n',
    '        "MODEL": "Model disagreement, weak conditional support or limited completed residuals dominate.",\n',
    '        "BOTH": "Market variability and model-knowledge uncertainty are both elevated.",\n',
    '        "LOW": "Both empirical market risk and model-knowledge uncertainty are currently contained.",\n',
    '    }[source]\n',
    '    return {\n',
    '        "aleatoric_uncertainty_0_100": round(aleatoric, 4), "epistemic_uncertainty_0_100": round(epistemic, 4),\n',
    '        "combined_uncertainty_0_100": round(combined, 4), "primary_uncertainty_source": source,\n',
    '        "explanation": explanation, "sample_size_status": "VALID" if residual_count >= 30 else "LIMITED",\n',
    '        "not_a_bayesian_guarantee": True,\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Validation, reliability, meta labels and canonical integration\n',
    '# ---------------------------------------------------------------------------\n',
    'def _baseline_skill(\n',
    '    residual_bundle: Mapping[str, Any], baseline_errors: Mapping[str, Mapping[int, np.ndarray]],\n',
    ') -> Dict[str, Any]:\n',
    '    scalar = residual_bundle.get("scalar_bank")\n',
    '    rows = []\n',
    '    for h in HORIZONS:\n',
    '        system_errors = np.asarray([], dtype=float)\n',
    '        if isinstance(scalar, pd.DataFrame) and not scalar.empty:\n',
    '            system_errors = pd.to_numeric(scalar.loc[scalar["horizon"] == h, "residual"], errors="coerce").dropna().to_numpy(dtype=float)\n',
    '        for baseline, per_h in baseline_errors.items():\n',
    '            base = np.asarray(per_h.get(h, []), dtype=float)\n',
    '            base = base[np.isfinite(base)]\n',
    '            if len(system_errors) < 8 or len(base) < 8:\n',
    '                rows.append({"baseline_name": baseline, "horizon": h, "system_error": None, "baseline_error": None, "skill_score": None, "direction_comparison": "UNAVAILABLE", "calibration_comparison": "UNAVAILABLE", "sample_size": min(len(system_errors), len(base)), "validation_status": "INSUFFICIENT DATA"})\n',
    '                continue\n',
    '            system_mae = float(np.mean(np.abs(system_errors))); baseline_mae = float(np.mean(np.abs(base)))\n',
    '            skill = 1.0 - system_mae / max(baseline_mae, 1e-12)\n',
    '            rows.append({"baseline_name": baseline, "horizon": h, "system_error": round(system_mae, 10), "baseline_error": round(baseline_mae, 10), "skill_score": round(skill, 8), "direction_comparison": "SYSTEM BETTER" if skill > 0 else "BASELINE BETTER" if skill < 0 else "EQUAL", "calibration_comparison": "NOT ENOUGH INTERVAL HISTORY", "sample_size": min(len(system_errors), len(base)), "validation_status": "VALID"})\n',
    '    valid = [row["skill_score"] for row in rows if row["skill_score"] is not None]\n',
    '    return {"rows": rows, "mean_skill_score": round(float(np.mean(valid)), 8) if valid else None, "status": "VALID" if valid else "INSUFFICIENT DATA"}\n',
    '\n',
    '\n',
    'def _research_reliability(\n',
    '    canonical: Mapping[str, Any], conformal: Mapping[str, Any], adaptive: Mapping[str, Any], uncertainty: Mapping[str, Any],\n',
    '    changepoint: Mapping[str, Any], confidence_set: Mapping[str, Any], baseline_skill: Mapping[str, Any], pbo: Mapping[str, Any], dsr: Mapping[str, Any],\n',
    ') -> Dict[str, Any]:\n',
    '    base = _clip((canonical.get("reliability") or {}).get("score", 50.0), 0, 100, 50)\n',
    '    existing_reliability = canonical.get("reliability") if isinstance(canonical.get("reliability"), Mapping) else {}\n',
    '    direction_accuracy = _finite(existing_reliability.get("direction_accuracy"), None)\n',
    '    if direction_accuracy is not None:\n',
    '        direction_accuracy = _clip(direction_accuracy * (100.0 if direction_accuracy <= 1.0 else 1.0), 0, 100, 50)\n',
    '    projection = canonical.get("probabilistic_projection") if isinstance(canonical.get("probabilistic_projection"), Mapping) else {}\n',
    '    model_agreement = _finite(\n',
    '        projection.get("path_agreement_pct", existing_reliability.get("model_agreement")), None\n',
    '    )\n',
    '    residual_count = int(conformal.get("residual_vector_count", 0) or 0)\n',
    '    data_quality = canonical.get("data_quality") if isinstance(canonical.get("data_quality"), Mapping) else {}\n',
    '    freshness_score = _finite(data_quality.get("score"), None)\n',
    '    if freshness_score is None:\n',
    '        stale = bool(canonical.get("stale") or (canonical.get("metadata") or {}).get("stale"))\n',
    '        freshness_score = 25.0 if stale else 100.0\n',
    '    validation = canonical.get("validation_metrics") if isinstance(canonical.get("validation_metrics"), Mapping) else {}\n',
    '    walk_forward = _finite(validation.get("walk_forward_stability_0_100"), None)\n',
    '    if walk_forward is None:\n',
    '        walk_forward = direction_accuracy\n',
    '    nlp = canonical.get("nlp") if isinstance(canonical.get("nlp"), Mapping) else {}\n',
    '    nlp_event_safety = 100.0 * (1.0 - _clip(nlp.get("importance", 0.0), 0, 1, 0.0))\n',
    '    observed_states = list((adaptive.get("states") or {}).values()) if isinstance(adaptive.get("states"), Mapping) else []\n',
    '    observed_coverage = [\n',
    '        100.0 * _clip(item.get("observed_coverage"), 0, 1, TARGET_COVERAGE)\n',
    '        for item in observed_states if isinstance(item, Mapping)\n',
    '    ]\n',
    '    components: Dict[str, Optional[float]] = {\n',
    '        "historical_direction_accuracy": direction_accuracy,\n',
    '        "conformal_interval_coverage": float(np.mean(observed_coverage)) if observed_coverage else None,\n',
    '        "adaptive_coverage_quality": _finite(adaptive.get("mean_coverage_quality_0_100"), None),\n',
    '        "model_agreement": None if model_agreement is None else _clip(model_agreement, 0, 100, 50),\n',
    '        "conditional_model_support": min(100.0, 25.0 * len(confidence_set.get("accepted_models") or [])),\n',
    '        "conditional_sample_size": _clip(100.0 * residual_count / 60.0, 0, 100, 0),\n',
    '        "data_freshness": _clip(freshness_score, 0, 100, 50),\n',
    '        "regime_stability": 100.0 - _clip(changepoint.get("transition_risk_0_100", 50), 0, 100, 50),\n',
    '        "transition_safety": 100.0 - _clip(changepoint.get("transition_risk_0_100", 50), 0, 100, 50),\n',
    '        "aleatoric_safety": 100.0 - _clip(uncertainty.get("aleatoric_uncertainty_0_100", 50), 0, 100, 50),\n',
    '        "epistemic_safety": 100.0 - _clip(uncertainty.get("epistemic_uncertainty_0_100", 50), 0, 100, 50),\n',
    '        "walk_forward_stability": None if walk_forward is None else _clip(walk_forward, 0, 100, 50),\n',
    '        "nlp_event_safety": _clip(nlp_event_safety, 0, 100, 100),\n',
    '    }\n',
    '    skill = _finite(baseline_skill.get("mean_skill_score"), None)\n',
    '    components["baseline_skill"] = None if skill is None else _clip(50.0 + 100.0 * skill, 0, 100, 50)\n',
    '    if pbo.get("value") is not None:\n',
    '        components["pbo_safety"] = 100.0 * (1.0 - _clip(pbo.get("value"), 0, 1, 0.5))\n',
    '    if dsr.get("deflated_sharpe_probability") is not None:\n',
    '        components["dsr_probability"] = 100.0 * _clip(dsr.get("deflated_sharpe_probability"), 0, 1, 0)\n',
    '    valid = [float(value) for value in components.values() if value is not None]\n',
    '    research_score = float(np.mean(valid)) if valid else 50.0\n',
    '    adjustment = _clip((research_score - 50.0) * 0.16, -8.0, 6.0, 0.0)\n',
    '    calibrated = _clip(base + adjustment, 0, 100, base)\n',
    '    label = "HIGH" if calibrated >= 72 else "MODERATE" if calibrated >= 50 else "LOW" if calibrated >= 35 else "CRITICAL"\n',
    '    return {\n',
    '        "base_existing_score": round(base, 4), "research_component_score": round(research_score, 4),\n',
    '        "bounded_adjustment": round(adjustment, 4), "calibrated_score_0_100": round(calibrated, 4),\n',
    '        "label": label, "components": {k: None if v is None else round(float(v), 4) for k, v in components.items()},\n',
    '        "modifier_bounds": [-8.0, 6.0], "full_metric_values_unchanged": True,\n',
    '    }\n',
    '\n',
    '\n',
    'def _meta_labels(canonical: Mapping[str, Any], uncertainty: Mapping[str, Any], changepoint: Mapping[str, Any], reliability: Mapping[str, Any], conformal: Mapping[str, Any]) -> Dict[str, str]:\n',
    '    final = canonical.get("final_decision") if isinstance(canonical.get("final_decision"), Mapping) else {}\n',
    '    direction = _direction(final.get("directional_market_view") or canonical.get("full_metric_direction"))\n',
    '    reliability_score = float(reliability.get("calibrated_score_0_100", 0.0))\n',
    '    transition = float(changepoint.get("transition_risk_0_100", 50.0))\n',
    '    combined = float(uncertainty.get("combined_uncertainty_0_100", 50.0))\n',
    '    path_support = "STRONG" if conformal.get("residual_vector_count", 0) >= 30 and combined < 50 else "WEAK" if combined < 68 else "CONFLICTED"\n',
    '    severe = sum([transition >= 78, combined >= 75, reliability_score < 35, path_support == "CONFLICTED"])\n',
    '    tradeability = "BLOCK" if severe >= 3 else "WAIT" if severe >= 2 else "TRADE"\n',
    '    timing = "NEXT HOUR" if transition >= 55 or combined >= 60 else "NOW"\n',
    '    risk = "HIGH" if combined >= 68 or transition >= 72 else "MEDIUM" if combined >= 42 else "LOW"\n',
    '    regime_support = "ALIGNED" if direction in {"BUY", "SELL"} and transition < 55 else "MIXED" if direction in {"BUY", "SELL"} else "OPPOSED"\n',
    '    nlp = canonical.get("nlp") if isinstance(canonical.get("nlp"), Mapping) else {}\n',
    '    event = "PROTECT" if _clip(nlp.get("importance", 0), 0, 1, 0) >= 0.75 else "CAUTION" if _clip(nlp.get("importance", 0), 0, 1, 0) >= 0.45 else "NORMAL"\n',
    '    return {\n',
    '        "direction": direction, "tradeability": tradeability, "timing": timing, "risk": risk,\n',
    '        "regime_support": regime_support, "path_support": path_support,\n',
]
