"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        "liquidity_event_condition": event, "uncertainty_source": str(uncertainty.get("primary_uncertainty_source", "BOTH")),\n',
    '    }\n',
    '\n',
    '\n',
    'def _update_bundle_bands(bundle: Optional[Mapping[str, Any]], conformal: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    result = deepcopy(dict(bundle or {}))\n',
    '    main = result.get("main")\n',
    '    rows = list(conformal.get("horizons") or [])\n',
    '    if isinstance(main, pd.DataFrame) and not main.empty and rows:\n',
    '        updated = main.copy(deep=True).reset_index(drop=True)\n',
    '        for index, row in enumerate(rows[: len(updated)]):\n',
    '            central = float(updated.loc[index, "main_path"]) if "main_path" in updated.columns else float(row["central"])\n',
    '            updated.loc[index, "lower_band"] = min(float(row["lower_band"]), central)\n',
    '            updated.loc[index, "upper_band"] = max(float(row["upper_band"]), central)\n',
    '            updated.loc[index, "band_width"] = max(central - float(updated.loc[index, "lower_band"]), float(updated.loc[index, "upper_band"]) - central)\n',
    '            for key in ("p10", "p25", "p50", "p75", "p90"):\n',
    '                updated.loc[index, key] = float(row[key])\n',
    '        result["main"] = updated\n',
    '        summary = dict(result.get("summary") or {})\n',
    '        summary.update({\n',
    '            "research_calibration_version": RESEARCH_VERSION,\n',
    '            "conformal_residual_vector_count": int(conformal.get("residual_vector_count", 0) or 0),\n',
    '            "adaptive_conformal_applied": True,\n',
    '            "central_path_preserved": bool(np.allclose(pd.to_numeric(main["main_path"], errors="coerce"), pd.to_numeric(updated["main_path"], errors="coerce"), equal_nan=True)) if "main_path" in main.columns else True,\n',
    '        })\n',
    '        result["summary"] = summary\n',
    '        audit = dict(result.get("audit") or {})\n',
    '        audit["ten_paper_research_calibration"] = _json_safe({k: v for k, v in conformal.items() if k != "scenarios"})\n',
    '        result["audit"] = audit\n',
    '    return result\n',
    '\n',
    '\n',
    'def validate_research_invariants(result: Mapping[str, Any]) -> Dict[str, bool]:\n',
    '    conformal = result.get("conformal_prediction") if isinstance(result.get("conformal_prediction"), Mapping) else {}\n',
    '    rows = list(conformal.get("horizons") or [])\n',
    '    quantile_ordering = all(row.get("p10") <= row.get("p25") <= row.get("p50") <= row.get("p75") <= row.get("p90") for row in rows)\n',
    '    bands = all(row.get("lower_band") <= row.get("central") <= row.get("upper_band") for row in rows)\n',
    '    dma = result.get("dynamic_model_averaging") if isinstance(result.get("dynamic_model_averaging"), Mapping) else {}\n',
    '    dma_groups = [dma]\n',
    '    dma_groups.extend(\n',
    '        group for group in (dma.get("by_horizon") or {}).values()\n',
    '        if isinstance(group, Mapping)\n',
    '    )\n',
    '    weight_sum = True\n',
    '    weight_bounds = True\n',
    '    for group in dma_groups:\n',
    '        weights = group.get("weights") or {}\n',
    '        if not weights:\n',
    '            continue\n',
    '        weight_sum = weight_sum and abs(sum(float(v) for v in weights.values()) - 1.0) <= 1e-8\n',
    '        minimum = float(group.get("minimum_weight", 0.0) or 0.0)\n',
    '        maximum = float(group.get("maximum_weight", 1.0) or 1.0)\n',
    '        weight_bounds = weight_bounds and all(\n',
    '            minimum - 1e-10 <= float(value) <= maximum + 1e-10\n',
    '            for value in weights.values()\n',
    '        )\n',
    '    probability_fields = []\n',
    '    for row in rows:\n',
    '        probability_fields.extend([row.get("probability_above_current_close"), row.get("probability_below_current_close")])\n',
    '    probability_fields.extend([conformal.get("tp_touch_probability"), conformal.get("sl_touch_probability")])\n',
    '    probabilities = all(value is None or 0.0 <= float(value) <= 1.0 for value in probability_fields)\n',
    '    uncertainties = result.get("uncertainty") if isinstance(result.get("uncertainty"), Mapping) else {}\n',
    '    score_bounds = all(0 <= float(uncertainties.get(key, 0)) <= 100 for key in ("aleatoric_uncertainty_0_100", "epistemic_uncertainty_0_100", "combined_uncertainty_0_100"))\n',
    '    change = result.get("bayesian_changepoint") if isinstance(result.get("bayesian_changepoint"), Mapping) else {}\n',
    '    change_probs = all(0 <= float(change.get(key, 0.0)) <= 1 for key in ("probability_change_now", "probability_change_last_3", "probability_change_last_6", "probability_structure_continues_one_more"))\n',
    '    return {\n',
    '        "quantile_ordering": quantile_ordering, "band_monotonicity": bands, "dynamic_weight_sum": weight_sum,\n',
    '        "dynamic_weight_bounds": weight_bounds,\n',
    '        "probabilities_in_range": probabilities and change_probs, "uncertainty_scores_in_range": score_bounds,\n',
    '        "central_path_preserved": bool(result.get("central_path_preserved", True)),\n',
    '    }\n',
    '\n',
    '\n',
    'def build_and_apply_research_layer(\n',
    '    canonical: Mapping[str, Any], *, ohlc: pd.DataFrame, calibrated_bundle: Optional[Mapping[str, Any]] = None,\n',
    '    prediction_history: Optional[pd.DataFrame] = None, settled_predictions: Optional[pd.DataFrame] = None,\n',
    '    previous_cache: Optional[Mapping[str, Any]] = None, strategy_returns: Optional[Sequence[float]] = None,\n',
    '    number_of_trials: Optional[int] = None, sharpe_trials: Optional[Sequence[float]] = None,\n',
    '    experiment_performance_matrix: Any = None,\n',
    ') -> tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any]]:\n',
    '    """Build all ten research integrations once and apply bounded canonical refinements."""\n',
    '    started = time.perf_counter()\n',
    '    payload = deepcopy(dict(canonical or {}))\n',
    '    latest = payload.get("latest_completed_candle_time") or ((payload.get("market") or {}).get("latest_completed_candle_time") if isinstance(payload.get("market"), Mapping) else None)\n',
    '    market = normalize_completed_ohlc(ohlc, latest_completed=latest)\n',
    '    if market.empty:\n',
    '        raise ValueError("Research calibration needs timestamped completed OHLC rows")\n',
    '    latest_text = str(_json_scalar(market["time"].iloc[-1]))\n',
    '    frame_hash = data_hash(market)\n',
    '    bundle_summary = dict((calibrated_bundle or {}).get("summary") or {}) if isinstance(calibrated_bundle, Mapping) else {}\n',
    '    input_descriptor = {\n',
    '        "frame_hash": frame_hash,\n',
    '        "latest_completed_h1": latest_text,\n',
    '        "symbol": payload.get("symbol"), "timeframe": payload.get("timeframe"),\n',
    '        "existing_reliability": (payload.get("reliability") or {}).get("score") if isinstance(payload.get("reliability"), Mapping) else None,\n',
    '        "regime": payload.get("regime"), "nlp": payload.get("nlp"),\n',
    '        "forecasts": payload.get("forecasts"),\n',
    '        "bundle_summary": bundle_summary,\n',
    '        "bundle_central_path": (calibrated_bundle.get("main")["main_path"].tolist() if isinstance(calibrated_bundle, Mapping) and isinstance(calibrated_bundle.get("main"), pd.DataFrame) and "main_path" in calibrated_bundle.get("main").columns else None),\n',
    '    }\n',
    '    research_input_hash = _hash_payload(input_descriptor)\n',
    '    calculation_id = _calculation_id(payload, frame_hash, latest_text, research_input_hash)\n',
    '    session = _session_label(market["time"].iloc[-1])\n',
    '    multiscale = payload.get("multiscale_regime") if isinstance(payload.get("multiscale_regime"), Mapping) else {}\n',
    '    volatility_regime = str(multiscale.get("current_volatility_regime") or "CALM").upper()\n',
    '\n',
    '    layer_meta: Dict[str, Any] = {}\n',
    '    def timed(name: str, function, *args, **kwargs):\n',
    '        t0 = time.perf_counter()\n',
    '        try:\n',
    '            value = function(*args, **kwargs)\n',
    '            layer_meta[name] = {"status": "SUCCESS", "duration_ms": round((time.perf_counter() - t0) * 1000.0, 3), "error_message": None}\n',
    '            return value\n',
    '        except Exception as exc:\n',
    '            layer_meta[name] = {"status": "FAILED", "duration_ms": round((time.perf_counter() - t0) * 1000.0, 3), "error_message": str(exc)[:500]}\n',
    '            raise\n',
    '\n',
    '    baselines = timed("baseline_forecasts", build_baseline_forecasts, market)\n',
    '    changepoint = timed("bayesian_changepoint", bayesian_online_changepoint, market)\n',
    '    transition_state = "HIGH_TRANSITION_RISK" if float(changepoint.get("transition_risk_0_100", 50)) >= 60 else "LOW_TRANSITION_RISK"\n',
    '    windows_previous = (previous_cache or {}).get("adaptive_windows") if isinstance(previous_cache, Mapping) else None\n',
    '    windows = timed("adaptive_windows", update_adaptive_windows, windows_previous, market, changepoint)\n',
    '    residual_window = int((((windows.get("states") or {}).get("prediction_residuals") or {}).get("current_window_size") or 180))\n',
    '    residuals = timed("residual_bank", build_residual_vectors, market, prediction_history, settled_predictions, max_origins=max(36, min(360, residual_window)))\n',
    '    adaptive_previous = (previous_cache or {}).get("adaptive_coverage") if isinstance(previous_cache, Mapping) else None\n',
    '    scalar_bank = residuals.get("scalar_bank") if isinstance(residuals.get("scalar_bank"), pd.DataFrame) else pd.DataFrame()\n',
    '    adaptive = timed("adaptive_conformal", update_adaptive_coverage, adaptive_previous, scalar_bank, current_volatility_regime=volatility_regime, current_session=session, transition_state=transition_state)\n',
    '    anchor = float(market["close"].iloc[-1])\n',
    '    central = _central_path(calibrated_bundle, payload, anchor)\n',
    '    current_direction = "BUY" if central[-1] > anchor else "SELL" if central[-1] < anchor else "NEUTRAL"\n',
    '    current_realized_volatility = float(_finite(market["close"].pct_change().tail(24).std(ddof=0), 0.0) or 0.0)\n',
    '    conformal = timed(\n',
    '        "time_series_conformal", conformal_scenarios, central, residuals,\n',
    '        seed_material=f"{calculation_id}|{frame_hash}|{latest_text}", adaptive_coverage=adaptive,\n',
    '        current_volatility_regime=volatility_regime, current_session=session,\n',
    '        transition_state=transition_state, anchor=anchor, current_direction=current_direction,\n',
    '        current_realized_volatility=current_realized_volatility,\n',
    '    )\n',
    '    error_map = _model_error_map(residuals, calibrated_bundle)\n',
    '    model_window = int((((windows.get("states") or {}).get("model_performance") or {}).get("current_window_size") or 300))\n',
    '    error_map = {model: {h: np.asarray(values, dtype=float)[-model_window:] for h, values in per_h.items()} for model, per_h in error_map.items()}\n',
    '    directional_regime = _direction((payload.get("regime") or {}).get("major_regime") if isinstance(payload.get("regime"), Mapping) else "")\n',
    '    condition_base = f"{volatility_regime}|{directional_regime}|{session}|{transition_state}"\n',
    '    conditional_by_horizon: Dict[str, Any] = {}\n',
    '    dma_by_horizon: Dict[str, Any] = {}\n',
    '    dma_previous_all = (previous_cache or {}).get("dynamic_model_averaging") if isinstance(previous_cache, Mapping) else None\n',
    '    previous_by_horizon = dict((dma_previous_all or {}).get("by_horizon") or {}) if isinstance(dma_previous_all, Mapping) else {}\n',
    '    for h in HORIZONS:\n',
    '        key = f"H+{h}"\n',
    '        conditional_by_horizon[key] = timed(\n',
    '            f"conditional_method_confidence_set_h{h}", conditional_method_confidence_set,\n',
    '            error_map, horizon=h, condition=f"{key}|{condition_base}",\n',
    '        )\n',
    '        dma_by_horizon[key] = timed(\n',
    '            f"dynamic_model_averaging_h{h}", dynamic_model_averaging,\n',
    '            conditional_by_horizon[key], error_map, horizon=h, previous=previous_by_horizon.get(key),\n',
    '        )\n',
    '    conditional = dict(conditional_by_horizon["H+3"]); conditional["by_horizon"] = conditional_by_horizon\n',
    '    conditional["requested_condition_grid"] = {\n',
    '        "horizons": list(HORIZONS), "volatility_regimes": ["CALM", "TURBULENT", "CRISIS"],\n',
    '        "directional_regimes": ["BULL", "BEAR", "RANGE"],\n',
    '        "sessions": ["ASIAN", "LONDON", "LONDON_NEW_YORK_OVERLAP"],\n',
    '        "transition_states": ["HIGH_TRANSITION_RISK", "LOW_TRANSITION_RISK"],\n',
    '        "active_condition": condition_base,\n',
    '        "fallback_policy": "Broaden condition and reduce confidence when completed conditional samples are insufficient",\n',
    '    }\n',
    '    dma = dict(dma_by_horizon["H+3"]); dma["by_horizon"] = dma_by_horizon\n',
    '    baseline_skill = timed("baseline_skill", _baseline_skill, residuals, residuals.get("baseline_errors") or {})\n',
    '    pbo_matrix = np.asarray(experiment_performance_matrix if experiment_performance_matrix is not None else np.empty((0, 0)), dtype=float)\n',
    '    pbo = timed("probability_backtest_overfitting", probability_backtest_overfitting, pbo_matrix)\n',
    '    dsr = timed("deflated_sharpe_ratio", deflated_sharpe_ratio, strategy_returns, number_of_trials=number_of_trials, sharpe_trials=sharpe_trials)\n',
    '    nlp = payload.get("nlp") if isinstance(payload.get("nlp"), Mapping) else {}\n',
    '    uncertainty = timed("uncertainty_separation", uncertainty_scores, market, conformal, calibrated_bundle, conditional, dma, changepoint, nlp)\n',
    '    research_reliability = timed("reliability_calibration", _research_reliability, payload, conformal, adaptive, uncertainty, changepoint, conditional, baseline_skill, pbo, dsr)\n',
    '    meta_labels = timed("meta_labels", _meta_labels, payload, uncertainty, changepoint, research_reliability, conformal)\n',
    '    upgraded_bundle = timed("projection_band_update", _update_bundle_bands, calibrated_bundle, conformal)\n',
    '\n',
    '    result: Dict[str, Any] = {\n',
    '        "version": RESEARCH_VERSION, "schema_version": RESEARCH_SCHEMA_VERSION,\n',
    '        "cache_version": RESEARCH_VERSION,\n',
    '        "canonical_calculation_id": calculation_id, "calculation_timestamp": latest_text,\n',
    '        "last_completed_h1_timestamp": latest_text, "data_hash": frame_hash,\n',
    '        "input_hash": _hash_payload({**input_descriptor, "central_path": central.tolist(), "version": RESEARCH_VERSION}),\n',
    '        "data_source_identity": str(payload.get("source") or "UNKNOWN"),\n',
    '        "symbol": str(payload.get("symbol") or "EURUSD"), "timeframe": str(payload.get("timeframe") or "H1"),\n',
    '        "row_count": int(len(market)), "stale": False, "stale_status": "CURRENT",\n',
    '        "error_message": None,\n',
    '        "session": session, "volatility_regime": volatility_regime, "transition_state": transition_state,\n',
    '        "baseline_forecasts": baselines, "baseline_skill": baseline_skill,\n',
    '        "conformal_prediction": conformal, "adaptive_coverage": adaptive,\n',
    '        "bayesian_changepoint": changepoint, "adaptive_windows": windows,\n',
    '        "conditional_method_confidence_set": conditional, "dynamic_model_averaging": dma,\n',
    '        "uncertainty": uncertainty, "pbo": pbo, "dsr": dsr,\n',
    '        "research_reliability": research_reliability, "meta_labels": meta_labels,\n',
    '        "validation_status": "VALID" if conformal.get("status") == "VALID" and changepoint.get("status") == "VALID" else "LIMITED DATA",\n',
    '        "layer_status": "SUCCESS",\n',
    '        "layer_execution_metadata": layer_meta,\n',
    '        "protected_full_metric_preserved": True, "central_path_preserved": True,\n',
    '        "causal_completed_candle_only": True, "future_rows_used": 0,\n',
    '        "validation_protocol": {\n',
    '            "walk_forward": True, "random_split": False, "fit_scalers_on_training_only": True,\n',
    '            "purged_splits": purged_walk_forward_splits(len(market), maximum_horizon=max(HORIZONS)),\n',
    '            "embargo_at_least_maximum_horizon": True,\n',
    '        },\n',
    '    }\n',
    '    deterministic_view = deepcopy(result)\n',
    '    deterministic_view.pop("layer_execution_metadata", None)\n',
    '    result["output_hash"] = _hash_payload(deterministic_view)\n',
    '    result["invariants"] = validate_research_invariants(result)\n',
    '    result["execution_duration_ms"] = round((time.perf_counter() - started) * 1000.0, 3)\n',
    '\n',
    '    payload["research_calibration"] = _json_safe(result)\n',
    '    payload["bayesian_changepoint"] = _json_safe(changepoint)\n',
    '    payload["adaptive_windows"] = _json_safe(windows)\n',
    '    payload["dynamic_model_weights"] = _json_safe(dma)\n',
    '    payload["conditional_accepted_model_set"] = _json_safe(conditional)\n',
    '    payload["conformal_residual_intervals"] = _json_safe(conformal)\n',
    '    payload["adaptive_coverage_state"] = _json_safe(adaptive)\n',
    '    payload["aleatoric_uncertainty"] = uncertainty["aleatoric_uncertainty_0_100"]\n',
    '    payload["epistemic_uncertainty"] = uncertainty["epistemic_uncertainty_0_100"]\n',
    '    payload["combined_uncertainty"] = uncertainty["combined_uncertainty_0_100"]\n',
    '    payload["baseline_forecasts"] = _json_safe(baselines)\n',
    '    payload["baseline_skill"] = _json_safe(baseline_skill)\n',
    '    payload["pbo"] = _json_safe(pbo); payload["dsr"] = _json_safe(dsr)\n',
    '    payload["meta_labels"] = {**dict(payload.get("meta_labels") or {}), **meta_labels}\n',
    '    payload["validation_status"] = result["validation_status"]\n',
    '    payload.setdefault("metadata", {})["research_calibration_version"] = RESEARCH_VERSION\n',
    '    payload["metadata"]["research_calculation_id"] = calculation_id\n',
    '    payload["metadata"]["research_output_hash"] = result["output_hash"]\n',
    '    payload["metadata"]["same_completed_data_deterministic"] = True\n',
    '    payload["metadata"]["research_layer_optional_fail_safe"] = True\n',
    '    existing_layers = payload.get("layer_execution_metadata")\n',
    '    if isinstance(existing_layers, list):\n',
    '        layer_rows = list(existing_layers)\n',
    '    elif isinstance(existing_layers, Mapping):\n',
    '        layer_rows = [{"layer": str(name), **dict(meta or {})} for name, meta in existing_layers.items()]\n',
    '    else:\n',
    '        layer_rows = []\n',
    '    layer_rows.extend({"layer": f"research.{name}", **dict(meta or {})} for name, meta in layer_meta.items())\n',
    '    payload["layer_execution_metadata"] = _json_safe(layer_rows)\n',
    '\n',
    '    reliability = payload.get("reliability") if isinstance(payload.get("reliability"), MutableMapping) else {}\n',
    '    if not isinstance(reliability, MutableMapping):\n',
    '        reliability = dict(reliability or {})\n',
    '    reliability.setdefault("existing_score_before_research", reliability.get("score"))\n',
    '    reliability.setdefault("existing_label_before_research", reliability.get("label"))\n',
    '    reliability["research_calibrated_score"] = research_reliability["calibrated_score_0_100"]\n',
    '    reliability["research_components"] = research_reliability["components"]\n',
    '    # Reliability is not a protected Full Metric formula.  Apply only the bounded\n',
    '    # research modifier while retaining the exact pre-research value for audit.\n',
    '    reliability["score"] = research_reliability["calibrated_score_0_100"]\n',
    '    reliability["label"] = research_reliability["label"]\n',
    '    reliability["calibration_source"] = "existing reliability plus bounded ten-paper research modifier"\n',
    '    payload["reliability"] = reliability\n',
    '\n',
    '    risk = payload.get("risk") if isinstance(payload.get("risk"), MutableMapping) else {}\n',
    '    risk = dict(risk or {})\n',
    '    risk["aleatoric_uncertainty_pct"] = uncertainty["aleatoric_uncertainty_0_100"]\n',
    '    risk["epistemic_uncertainty_pct"] = uncertainty["epistemic_uncertainty_0_100"]\n',
    '    risk["combined_uncertainty_pct"] = uncertainty["combined_uncertainty_0_100"]\n',
    '    payload["risk"] = risk\n',
    '\n',
    '    final = payload.get("final_decision") if isinstance(payload.get("final_decision"), MutableMapping) else {}\n',
    '    final = dict(final or {})\n',
    '    final["research_meta_labels"] = meta_labels\n',
    '    final["research_reliability"] = research_reliability["calibrated_score_0_100"]\n',
    '    existing_confidence = _finite(final.get("calibrated_confidence"), None)\n',
    '    if existing_confidence is not None:\n',
    '        final["pre_research_calibrated_confidence"] = float(existing_confidence)\n',
    '        final["calibrated_confidence"] = round(_clip(0.84 * float(existing_confidence) + 0.16 * research_reliability["calibrated_score_0_100"], 0, 100, float(existing_confidence)), 4)\n',
    '    final["projection_confidence_research_inputs"] = {\n',
    '        "coverage_quality": adaptive.get("mean_coverage_quality_0_100"),\n',
    '        "transition_risk": changepoint.get("transition_risk_0_100"),\n',
    '        "combined_uncertainty": uncertainty.get("combined_uncertainty_0_100"),\n',
    '        "baseline_skill": baseline_skill.get("mean_skill_score"),\n',
    '    }\n',
    '    severe_joint_block = meta_labels["tradeability"] == "BLOCK"\n',
    '    if severe_joint_block and str(final.get("final_decision", "WAIT")).upper() in {"BUY", "SELL"}:\n',
    '        final["pre_research_final_decision"] = final.get("final_decision")\n',
    '        final["final_decision"] = "WAIT"\n',
    '        final["tradeability_decision"] = "WAIT"\n',
    '        final["less_risky_decision"] = "WAIT"\n',
    '        blockers = list(final.get("blocking_reasons") or [])\n',
    '        blockers.append("Joint research gate: extreme transition/model/coverage uncertainty")\n',
    '        final["blocking_reasons"] = sorted(set(blockers))\n',
    '    payload["research_score_refinements"] = {\n',
    '        "protected_values_unchanged": True,\n',
    '        "master_score": {"protected": payload.get("master_score"), "research_confirmation_0_100": research_reliability.get("research_component_score")},\n',
    '        "entry_score": {"protected": payload.get("entry_score"), "joint_caution_penalty_0_10": round(min(2.0, 0.012 * float(changepoint.get("transition_risk_0_100", 0)) + 0.010 * float(uncertainty.get("epistemic_uncertainty_0_100", 0))), 4)},\n',
    '        "hold_score": {"protected": payload.get("hold_safety"), "run_length_stability_0_100": round(100.0 - float(changepoint.get("transition_risk_0_100", 50)), 4)},\n',
    '        "exit_risk": {"protected": payload.get("exit_risk"), "research_risk_pressure_0_100": round(0.45 * float(changepoint.get("transition_risk_0_100", 50)) + 0.35 * float(uncertainty.get("aleatoric_uncertainty_0_100", 50)) + 0.20 * float(uncertainty.get("epistemic_uncertainty_0_100", 50)), 4)},\n',
    '        "knn_neighbor_quality": {\n',
    '            "minimum_valid_neighbor_count": 12,\n',
    '            "conditioned_residual_support": conformal.get("conditioned_vector_sample_size"),\n',
    '            "out_of_distribution_status": "WATCH" if uncertainty.get("epistemic_uncertainty_0_100", 0) >= 60 else "SUPPORTED",\n',
    '            "adaptive_history_window": (((windows.get("states") or {}).get("knn_candidate_history") or {}).get("current_window_size")),\n',
    '        },\n',
    '        "greedy_inputs": {\n',
    '            "tp_probability": conformal.get("tp_touch_probability"), "sl_probability": conformal.get("sl_touch_probability"),\n',
    '            "expected_mfe": conformal.get("expected_maximum_favourable_excursion"), "expected_mae": conformal.get("expected_maximum_adverse_excursion"),\n',
    '            "transition_risk": changepoint.get("transition_risk_0_100"), "baseline_skill": baseline_skill.get("mean_skill_score"),\n',
    '            "aleatoric_uncertainty": uncertainty.get("aleatoric_uncertainty_0_100"), "epistemic_uncertainty": uncertainty.get("epistemic_uncertainty_0_100"),\n',
    '        },\n',
    '    }\n',
    '    payload["final_decision"] = final\n',
    '    return payload, result, upgraded_bundle\n',
    '\n',
    '\n',
    'def build_research_layer_fail_safe(\n',
    '    canonical: Mapping[str, Any], *, builder=build_and_apply_research_layer, **kwargs: Any,\n',
    ') -> tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any], Dict[str, Any]]:\n',
    '    """Preserve the previous valid payload when the optional layer fails."""\n',
    '    original = deepcopy(dict(canonical or {}))\n',
    '    original_bundle = deepcopy(dict(kwargs.get("calibrated_bundle") or {}))\n',
    '    try:\n',
    '        payload, result, bundle = builder(original, **kwargs)\n',
    '        return payload, result, bundle, {"ok": True, "status": "SUCCESS"}\n',
    '    except Exception as exc:\n',
    '        original.setdefault("metadata", {})["research_calibration_status"] = "FAILED SAFELY"\n',
    '        original["metadata"]["research_calibration_error"] = str(exc)[:500]\n',
    '        return original, {}, original_bundle, {"ok": False, "status": "FAILED SAFELY", "error": str(exc)[:500]}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Disk-backed state and experiment registry\n',
    '# ---------------------------------------------------------------------------\n',
    '@dataclass\n',
    'class ResearchStore:\n',
    '    db_path: Path | str = DEFAULT_DB_PATH\n',
    '\n',
    '    def __post_init__(self) -> None:\n',
    '        configured = os.environ.get("ADX_LEDGER_DB_PATH")\n',
    '        self.db_path = Path(configured or self.db_path)\n',
    '        self.db_path.parent.mkdir(parents=True, exist_ok=True)\n',
    '        self.initialize()\n',
    '\n',
    '    def _connect(self):\n',
    '        connection = sqlite3.connect(str(self.db_path), timeout=15, check_same_thread=False)\n',
    '        connection.execute("PRAGMA journal_mode=WAL")\n',
    '        connection.execute("PRAGMA synchronous=NORMAL")\n',
    '        connection.execute("PRAGMA busy_timeout=15000")\n',
    '        return connection\n',
    '\n',
    '    def initialize(self) -> None:\n',
    '        statements = [\n',
    '            """CREATE TABLE IF NOT EXISTS research_calibration_runs(\n',
    '                calculation_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, last_completed_h1 TEXT NOT NULL,\n',
    '                data_hash TEXT NOT NULL, input_hash TEXT NOT NULL, output_hash TEXT NOT NULL,\n',
    '                schema_version TEXT NOT NULL, result_json TEXT NOT NULL)""",\n',
    '            """CREATE TABLE IF NOT EXISTS research_conformal_predictions(\n',
    '                calculation_id TEXT NOT NULL, horizon INTEGER NOT NULL, prediction_time TEXT NOT NULL,\n',
    '                target_time TEXT NOT NULL, central REAL, lower_band REAL, upper_band REAL,\n',
    '                volatility_regime TEXT, session TEXT, transition_state TEXT, status TEXT NOT NULL,\n',
    '                target_coverage REAL, adaptive_correction REAL, calibration_sample_size INTEGER,\n',
    '                PRIMARY KEY(calculation_id, horizon))""",\n',
    '            """CREATE TABLE IF NOT EXISTS research_conformal_outcomes(\n',
    '                calculation_id TEXT NOT NULL, horizon INTEGER NOT NULL, prediction_time TEXT NOT NULL,\n',
    '                target_time TEXT NOT NULL, central REAL, lower_band REAL, upper_band REAL,\n',
    '                actual_completed_close REAL NOT NULL, inside_interval INTEGER NOT NULL,\n',
    '                target_coverage REAL, recent_observed_coverage REAL, coverage_error REAL,\n',
    '                adaptive_correction REAL, calibration_sample_size INTEGER, volatility_regime TEXT,\n',
    '                session TEXT, transition_state TEXT, settled_at TEXT NOT NULL,\n',
    '                PRIMARY KEY(calculation_id, horizon))""",\n',
    '            """CREATE TABLE IF NOT EXISTS research_experiments(\n',
    '                experiment_id TEXT PRIMARY KEY, configuration_hash TEXT NOT NULL, parameters_json TEXT,\n',
    '                feature_set_json TEXT, thresholds_json TEXT, model_weights_json TEXT, regime_settings_json TEXT,\n',
    '                training_period TEXT, validation_period TEXT, purging_period INTEGER, embargo_period INTEGER,\n',
    '                net_returns_json TEXT, mae REAL, rmse REAL, direction_accuracy REAL, calibration_error REAL,\n',
    '                sharpe REAL, selected INTEGER NOT NULL DEFAULT 0, rejected_reason TEXT, created_at TEXT NOT NULL)""",\n',
    '            """CREATE TABLE IF NOT EXISTS research_experiment_period_performance(\n',
    '                experiment_id TEXT NOT NULL, period_label TEXT NOT NULL, chronological_index INTEGER NOT NULL,\n',
    '                performance REAL NOT NULL, PRIMARY KEY(experiment_id, period_label))""",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_research_predictions_target ON research_conformal_predictions(target_time, status)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_research_outcomes_condition ON research_conformal_outcomes(horizon, volatility_regime, session, transition_state, target_time)",\n',
    '        ]\n',
    '        with _DB_LOCK, self._connect() as connection:\n',
    '            for statement in statements:\n',
    '                connection.execute(statement)\n',
    '            # Idempotent migration for databases created by an earlier build.\n',
    '            existing = {row[1] for row in connection.execute("PRAGMA table_info(research_conformal_predictions)").fetchall()}\n',
    '            for column, definition in (\n',
    '                ("target_coverage", "REAL"),\n',
    '                ("adaptive_correction", "REAL"),\n',
    '                ("calibration_sample_size", "INTEGER"),\n',
    '            ):\n',
    '                if column not in existing:\n',
    '                    connection.execute(f"ALTER TABLE research_conformal_predictions ADD COLUMN {column} {definition}")\n',
    '            connection.commit()\n',
    '\n',
    '    def persist_result(self, result: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '        calculation_id = str(result.get("canonical_calculation_id") or "")\n',
    '        if not calculation_id:\n',
    '            return {"ok": False, "reason": "missing calculation id"}\n',
    '        created = str(result.get("calculation_timestamp") or result.get("last_completed_h1_timestamp") or "")\n',
    '        conformal = result.get("conformal_prediction") if isinstance(result.get("conformal_prediction"), Mapping) else {}\n',
    '        with _DB_LOCK, self._connect() as connection:\n',
    '            connection.execute(\n',
    '                "INSERT OR REPLACE INTO research_calibration_runs VALUES(?,?,?,?,?,?,?,?)",\n',
    '                (calculation_id, created, str(result.get("last_completed_h1_timestamp")), str(result.get("data_hash")), str(result.get("input_hash")), str(result.get("output_hash")), str(result.get("schema_version")), json.dumps(_json_safe(result), ensure_ascii=False, default=str)),\n',
    '            )\n',
    '            prediction_time = pd.to_datetime(result.get("last_completed_h1_timestamp"), errors="coerce", utc=True)\n',
    '            for row in conformal.get("horizons") or []:\n',
    '                horizon = int(row.get("horizon") or 0)\n',
    '                target_time = prediction_time + pd.Timedelta(hours=horizon) if pd.notna(prediction_time) else pd.NaT\n',
    '                state_key = f"H+{horizon}|{result.get(\'volatility_regime\')}|{result.get(\'session\')}|{result.get(\'transition_state\')}"\n',
    '                coverage_state = dict(((result.get("adaptive_coverage") or {}).get("states") or {}).get(state_key) or {})\n',
    '                connection.execute(\n',
    '                    """INSERT OR REPLACE INTO research_conformal_predictions(\n',
    '                        calculation_id,horizon,prediction_time,target_time,central,lower_band,upper_band,\n',
    '                        volatility_regime,session,transition_state,status,target_coverage,adaptive_correction,\n',
    '                        calibration_sample_size) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",\n',
    '                    (calculation_id, horizon, str(prediction_time), str(target_time), _finite(row.get("central"), None),\n',
    '                     _finite(row.get("lower_band"), None), _finite(row.get("upper_band"), None),\n',
    '                     result.get("volatility_regime"), result.get("session"), result.get("transition_state"), "PENDING",\n',
    '                     _finite(coverage_state.get("target_coverage"), TARGET_COVERAGE),\n',
    '                     _finite(row.get("adaptive_correction"), 1.0), int(coverage_state.get("sample_size") or 0)),\n',
    '                )\n',
    '            connection.commit()\n',
    '        return {"ok": True, "status": "SQLITE", "calculation_id": calculation_id, "horizon_rows": len(conformal.get("horizons") or [])}\n',
    '\n',
]
