"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    'def build_lunch_copy_payloads(state: MutableMapping[str, Any], *, include_full: bool = True) -> dict[str, str]:\n',
    '    """Build complete closed-field-safe copy payloads from one generation identity."""\n',
    '    canonical = get_canonical_generation(state)\n',
    '    contract = market_time_contract(state, canonical)\n',
    '    key = payload_cache_key(contract)\n',
    '    cache = state.get("lunch_copy_payload_cache_20260622")\n',
    '    if isinstance(cache, Mapping) and cache.get("key") == key and cache.get("short") and (not include_full or cache.get("full")):\n',
    '        return {"short": str(cache.get("short", "")), "full": str(cache.get("full", "")), "key": key}\n',
    '    started = time.perf_counter()\n',
    '    try:\n',
    '        from core.cross_table_sync_20260622 import publish_cross_table_sync\n',
    '        cross = publish_cross_table_sync(state, canonical=canonical)\n',
    '    except Exception:\n',
    '        cross = {}\n',
    '    metric_result = _closed_field_metric_result(state)\n',
    '    overall = metric_result.get("history") if isinstance(metric_result.get("history"), pd.DataFrame) else pd.DataFrame()\n',
    '    try:\n',
    '        combined6 = build_combined_field6_history(state)\n',
    '    except Exception:\n',
    '        combined6 = pd.DataFrame()\n',
    '    sync = synchronization_status(state, field1_history=overall, field6_history=combined6, canonical=canonical)\n',
    '    if cross:\n',
    '        sync["cross_table_report"] = cross\n',
    '    state["lunch_sync_status_20260622"] = sync\n',
    '    fact = build_ai_fact_pack(state)\n',
    '    v9_snapshot = None\n',
    '    try:\n',
    '        from core.canonical_sync_v9 import read_snapshot_for_lunch\n',
    '        v9_snapshot = read_snapshot_for_lunch(state)\n',
    '    except Exception:\n',
    '        v9_snapshot = None\n',
    '    v9_lines = []\n',
    '    if v9_snapshot is not None:\n',
    '        v9_lines = [\n',
    '            "[CANONICAL SYNC V9]",\n',
    '            f"run_id: {v9_snapshot.run_id}", f"snapshot_hash: {v9_snapshot.snapshot_hash}",\n',
    '            f"broker_time: {v9_snapshot.broker_time}", f"candle_time: {v9_snapshot.candle_time}",\n',
    '            f"priority: {v9_snapshot.priority_label} ({v9_snapshot.priority_score:.2f})",\n',
    '            f"decision: {v9_snapshot.decision}", f"regime: {v9_snapshot.regime}",\n',
    '            f"reliability: {v9_snapshot.reliability_score:.2f}",\n',
    '            f"data_quality_score: {v9_snapshot.data_quality_score:.2f}",\n',
    '        ]\n',
    '    short = "\\n".join((v9_lines + _short_lines(state, canonical, contract, fact, sync))[:40])\n',
    '    if not include_full:\n',
    '        from core.generation_order_guard_20260622 import publish_if_not_older\n',
    '        existing_full = str(cache.get("full", "")) if isinstance(cache, Mapping) and cache.get("key") == key else ""\n',
    '        cache_value = {"key": key, "short": short, "full": existing_full, "built_at": time.time(), "generation": contract.get("calculation_generation")}\n',
    '        publish_if_not_older(state, key="lunch_copy_payload_cache_20260622", value=cache_value, candidate=canonical)\n',
    '        state["timing_top_copy_short_build_20260622"] = round(time.perf_counter() - started, 6)\n',
    '        return {"short": short, "full": "", "key": key}\n',
    '\n',
    '    histories = metric_result.get("history_by_factor") if isinstance(metric_result.get("history_by_factor"), Mapping) else {}\n',
    '    field1_parts = ["[Overall Full Metric History — Last 25 Days]", _frame_text(overall, state, canonical)]\n',
    '    for name, frame in list(histories.items())[:10]:\n',
    '        field1_parts.extend([f"[Decision History: {name}]", _frame_text(frame, state, canonical)])\n',
    '    regime_tables = state.get("regime_standard_detail_tables_published_20260618") if isinstance(state.get("regime_standard_detail_tables_published_20260618"), Mapping) else {}\n',
    '    field4_frames = {}\n',
    '    for k in ("canonical_priority_table_20260617", "reliability_history_20260618", "similar_day_history_20260619", "field4_technical_fact_table_20260622"):\n',
    '        v = state.get(k)\n',
    '        if isinstance(v, pd.DataFrame): field4_frames[k] = v\n',
    '    field6_sections = ["[Combined Sentiment + Technical + Decision History]", _frame_text(combined6, state, canonical)]\n',
    '    try:\n',
    '        from core.field6_quant_history_20260622 import FIELD6_TABLES, QUANT_V6_FIELD6_VIEWS, build_field6_history_table\n',
    '        for label, table_name in QUANT_V6_FIELD6_VIEWS + FIELD6_TABLES:\n',
    '            field6_sections.extend([f"[{label}]", _frame_text(build_field6_history_table(table_name, state), state, canonical, limit=200)])\n',
    '    except Exception as exc:\n',
    '        field6_sections.extend(["[Field 6 Quant Histories]", f"UNAVAILABLE: {type(exc).__name__}: {exc}"])\n',
    '\n',
    '    full_sections = [\n',
    '        "ADX Quant Pro EURUSD H1 — Complete Canonical Lunch Snapshot",\n',
    '        "[CANONICAL SYNC V9 SNAPSHOT]", _json_text(v9_snapshot.__dict__ if v9_snapshot is not None else {"status": "UNAVAILABLE"}),\n',
    '        "[IDENTITY AND BROKER-TIME CONTRACT]", _json_text(contract),\n',
    '        "[SYNCHRONIZATION AND DATA QUALITY]", _json_text({"sync": sync, "quality": validate_data_quality_contract(state)}),\n',
    '        "[FIELD 1 — FULL METRIC AND TEN DECISION HISTORIES]", *field1_parts,\n',
    '        "[FIELD 2 — PAST / PRESENT / FUTURE VISUALIZATION SUMMARIES]", _json_text({"past": "last 25 trading days, completed-only broker-time history with overlap evidence", "present": {"reliability": _mapping(canonical.get("reliability")), "market_quality": _mapping(canonical.get("priority")).get("market_quality"), "system_trust": canonical.get("system_trust")}, "future": _mapping(canonical.get("forecasts")) or _mapping(canonical.get("powerbi"))}),\n',
    '        "[FIELD 3 — REGIME LIFECYCLE, ALPHA/DELTA AND HISTORIES]", _json_text({"current": _mapping(canonical.get("regime")), "tables": {k: _frame_text(v, state, canonical) for k, v in regime_tables.items() if isinstance(v, pd.DataFrame)}}),\n',
    '        "[FIELD 4 — TECHNICAL, PRIORITY, RELIABILITY, KNN/GREEDY AND SIMILAR-DAY EVIDENCE]",\n',
    '        _json_text({"summary": state.get("field4_technical_fact_summary_20260622", "UNAVAILABLE"), "frames": {k: _frame_text(v, state, canonical) for k, v in field4_frames.items()}}),\n',
    '        "[FIELD 5 — GROUNDED AI FACT PACK AND EVIDENCE METADATA]", _json_text({"fact_pack": fact, "last_answer_audit": state.get("ai_last_answer_audit_20260622"), "last_risk_coverage": state.get("ai_last_risk_coverage_audit_20260622")}),\n',
    '        "[FIELD 6 — QUANTITATIVE-TRADER RESEARCH HISTORIES]", *field6_sections,\n',
    '        "[ADVANCED QUANT V6 SHADOW RESEARCH]", _json_text(canonical.get("quant_research_v6", {})),\n',
    '        "[ADVANCED QUANT V7 SHADOW RESEARCH]", _json_text(canonical.get("quant_research_v7", {})),\n',
    '        "[ADVANCED QUANT V8 MORNING / CALIBRATION / READINESS SHADOW EVIDENCE]", _json_text(canonical.get("quant_research_v8", {})),\n',
    '        "[RESEARCH SHADOW LAYERS]", _json_text(build_research_shadow_layers(state)),\n',
    '        "[PROTECTED-LOGIC NOTICE]", "All content is a read-only projection of already-published outputs. No protected calculation, strategy, model parameter, weight, TP/SL formula, regime definition, or decision rule was changed by copy serialization.",\n',
    '    ]\n',
    '    full = "\\n".join(str(x) for x in full_sections)\n',
    '    from core.generation_order_guard_20260622 import publish_if_not_older\n',
    '    cache_value = {"key": key, "short": short, "full": full, "built_at": time.time(), "generation": contract.get("calculation_generation")}\n',
    '    publish_if_not_older(state, key="lunch_copy_payload_cache_20260622", value=cache_value, candidate=canonical)\n',
    '    state["timing_top_copy_payload_build_20260622"] = round(time.perf_counter() - started, 6)\n',
    '    return {"short": short, "full": full, "key": key}\n',
    '\n',
    'def render_lunch_top_copy_buttons(state: MutableMapping[str, Any]) -> None:\n',
    '    """Exactly two top controls; Full serialization starts only when pressed."""\n',
    '    try:\n',
    '        import streamlit as st\n',
    '        from ui.copy_tools import central_copy_result\n',
    '        canonical = get_canonical_generation(state)\n',
    '        contract = market_time_contract(state, canonical)\n',
    '        key = payload_cache_key(contract)\n',
    '        st.markdown("#### 📋 Canonical Lunch Copy")\n',
    '        cols = st.columns(3)\n',
    '        short_pressed = cols[0].button("Copy Short", key=f"lunch_top_copy_short_trigger_{key}", use_container_width=True)\n',
    '        full_pressed = cols[1].button("Copy Full", key=f"lunch_top_copy_full_trigger_{key}", use_container_width=True)\n',
    '        refresh_pressed = cols[2].button("Refresh Snapshot", key=f"lunch_top_refresh_snapshot_{key}", use_container_width=True)\n',
    '        if refresh_pressed:\n',
    '            try:\n',
    '                from core.canonical_sync_v9 import get_latest_snapshot\n',
    '                get_latest_snapshot(force=False, state=state)\n',
    '                st.rerun()\n',
    '            except Exception as exc:\n',
    '                st.warning(f"Canonical snapshot refresh unavailable: {exc}")\n',
    '        if short_pressed:\n',
    '            payloads = build_lunch_copy_payloads(state, include_full=False)\n',
    '            with cols[0]:\n',
    '                central_copy_result(payloads["short"], f"lunch_top_copy_short_result_{payloads[\'key\']}", height=102)\n',
    '        if full_pressed:\n',
    '            started = time.perf_counter()\n',
    '            payloads = build_lunch_copy_payloads(state, include_full=True)\n',
    '            state["timing_copy_full_generation_20260622"] = round(time.perf_counter() - started, 6)\n',
    '            with cols[1]:\n',
    '                central_copy_result(payloads["full"], f"lunch_top_copy_full_result_{payloads[\'key\']}", height=102)\n',
    '        st.caption("Copy Short, Copy Full, and Refresh Snapshot use the same immutable canonical generation; Refresh never recalculates.")\n',
    '        # Legacy discovery marker only: central_copy_button("Copy Full", ...)\n',
    '    except Exception as exc:\n',
    '        try:\n',
    '            import streamlit as st\n',
    '            st.warning(f"Top copy buttons unavailable: {exc}")\n',
    '        except Exception:\n',
    '            pass\n',
    '\n',
    '\n',
    'EUR_POS = {"euro rises", "eur rises", "hawkish ecb", "ecb hike", "eurozone growth", "strong euro", "eur positive", "inflation hot"}\n',
    'EUR_NEG = {"euro falls", "eur falls", "dovish ecb", "ecb cut", "eurozone recession", "weak euro", "eur negative"}\n',
    'USD_POS = {"dollar rises", "usd rises", "hawkish fed", "fed hike", "strong dollar", "hot nfp", "hot cpi", "usd positive"}\n',
    'USD_NEG = {"dollar falls", "usd falls", "dovish fed", "fed cut", "weak dollar", "soft nfp", "soft cpi", "usd negative"}\n',
    '\n',
    '\n',
    'def classify_eurusd_sentiment(headline: str, *, published_time_utc: Any = None, source: str = "cached research", now_utc: Any = None) -> dict[str, Any]:\n',
    '    """Lightweight finance-domain sentiment inspired by FinBERT research."""\n',
    '    text = str(headline or "").lower()\n',
    '    def score(terms: Iterable[str]) -> int:\n',
    '        return sum(1 for t in terms if t in text)\n',
    '    eur_score = score(EUR_POS) - score(EUR_NEG)\n',
    '    usd_score = score(USD_POS) - score(USD_NEG)\n',
    '    # direct vocabulary fallbacks\n',
    '    if "eur" in text or "euro" in text or "ecb" in text:\n',
    '        eur_score += text.count("beat") + text.count("strong") - text.count("miss") - text.count("weak")\n',
    '    if "usd" in text or "dollar" in text or "fed" in text or "nfp" in text or "cpi" in text:\n',
    '        usd_score += text.count("strong") + text.count("hawkish") - text.count("weak") - text.count("dovish")\n',
    '    buy_support = eur_score > 0 or usd_score < 0\n',
    '    sell_support = eur_score < 0 or usd_score > 0\n',
    '    if buy_support and not sell_support:\n',
    '        direction = "BUY"\n',
    '    elif sell_support and not buy_support:\n',
    '        direction = "SELL"\n',
    '    elif buy_support and sell_support:\n',
    '        direction = "CONFLICT"\n',
    '    elif headline:\n',
    '        direction = "NEUTRAL"\n',
    '    else:\n',
    '        direction = "UNAVAILABLE"\n',
    '    raw = float(eur_score - usd_score)\n',
    '    published = _utc(published_time_utc)\n',
    '    now = _utc(now_utc) or pd.Timestamp.now(tz="UTC")\n',
    '    age = (now - published).total_seconds() / 60.0 if published is not None else None\n',
    '    relevance = 100 if any(k in text for k in ("eur", "euro", "ecb", "usd", "dollar", "fed", "cpi", "nfp", "pmi")) else 35\n',
    '    confidence = max(0, min(100, 45 + abs(raw) * 15 + (15 if direction in {"BUY", "SELL"} else 0))) if direction != "UNAVAILABLE" else 0\n',
    '    return {\n',
    '        "published_time_utc": published.isoformat() if published is not None else None,\n',
    '        "Broker Published Time": None,\n',
    '        "Myanmar Published Time": _display(published, 390, "Myanmar UTC+6:30") if published is not None else "UNAVAILABLE",\n',
    '        "source": source,\n',
    '        "headline": headline,\n',
    '        "EUR sentiment": eur_score,\n',
    '        "USD sentiment": usd_score,\n',
    '        "EURUSD directional sentiment": direction,\n',
    '        "direction": direction,\n',
    '        "raw score": raw,\n',
    '        "calibrated score": max(-1.0, min(1.0, raw / 4.0)),\n',
    '        "relevance": relevance,\n',
    '        "impact": "HIGH" if relevance >= 80 and abs(raw) >= 2 else "MEDIUM" if relevance >= 50 else "LOW",\n',
    '        "confidence": confidence,\n',
    '        "age_minutes": round(age, 2) if age is not None else None,\n',
    '        "duplicate_group": hashlib.sha1(re.sub(r"\\W+", " ", text).strip().encode()).hexdigest()[:10] if headline else "UNAVAILABLE",\n',
    '        "quality_status": "OK" if direction != "UNAVAILABLE" else "UNAVAILABLE",\n',
    '        "reason": "EUR positive or USD negative supports EURUSD BUY; EUR negative or USD positive supports EURUSD SELL; contradictory evidence becomes CONFLICT/NEUTRAL.",\n',
    '    }\n',
    '\n',
    '\n',
    'def leakage_safe_asof_join(left: pd.DataFrame, right: pd.DataFrame, *, left_time: str = "event_time_utc", right_time: str = "published_time_utc") -> pd.DataFrame:\n',
    '    if not isinstance(left, pd.DataFrame) or left.empty:\n',
    '        return pd.DataFrame()\n',
    '    if not isinstance(right, pd.DataFrame) or right.empty or left_time not in left.columns or right_time not in right.columns:\n',
    '        return left.copy(deep=False)\n',
    '    l = left.copy(deep=False)\n',
    '    r = right.copy(deep=False)\n',
    '    l[left_time] = pd.to_datetime(l[left_time], errors="coerce", utc=True)\n',
    '    r[right_time] = pd.to_datetime(r[right_time], errors="coerce", utc=True)\n',
    '    l = l.dropna(subset=[left_time]).sort_values(left_time)\n',
    '    r = r.dropna(subset=[right_time]).sort_values(right_time)\n',
    '    merged = pd.merge_asof(l, r, left_on=left_time, right_on=right_time, direction="backward", allow_exact_matches=True)\n',
    '    return merged\n',
    '\n',
    '\n',
    'def build_sentiment_history(state: MutableMapping[str, Any]) -> pd.DataFrame:\n',
    '    source = state.get("research_news_history_20260622") or state.get("research_news_df") or state.get("news_history")\n',
    '    rows: list[dict[str, Any]] = []\n',
    '    if isinstance(source, pd.DataFrame) and not source.empty:\n',
    '        for _, row in source.head(500).iterrows():\n',
    '            headline = _first(row.get("headline"), row.get("title"), row.get("summary"), default="")\n',
    '            ts = _first(row.get("published_time_utc"), row.get("published_at"), row.get("time"), row.get("date"), default=None)\n',
    '            rows.append(classify_eurusd_sentiment(str(headline), published_time_utc=ts, source=str(row.get("source") or "cached research")))\n',
    '    else:\n',
    '        # Empty, explicit UNAVAILABLE row. No invented direction.\n',
    '        rows.append(classify_eurusd_sentiment("", source="cached research unavailable"))\n',
    '    df = pd.DataFrame(rows)\n',
    '    state["research_sentiment_history_20260622"] = df\n',
    '    if not df.empty:\n',
    '        latest = df.iloc[0].to_dict()\n',
    '        state["research_sentiment_summary_20260622"] = {k: latest.get(k) for k in ("direction", "confidence", "reason", "quality_status")}\n',
    '    return df\n',
    '\n',
    '\n',
    'def publish_field4_technical_fact_table(state: MutableMapping[str, Any]) -> pd.DataFrame:\n',
    '    canonical = get_canonical_generation(state)\n',
    '    contract = market_time_contract(state, canonical)\n',
    '    row = {\n',
    '        "event_time_utc": contract.get("latest_completed_h1_utc"),\n',
    '        "calculation_id": contract.get("calculation_id"),\n',
    '        "generation": contract.get("calculation_generation"),\n',
    '        "technical direction": _first(canonical.get("technical_direction"), canonical.get("full_metric_direction"), _mapping(canonical.get("final_decision")).get("directional_market_view"), default="UNAVAILABLE"),\n',
    '        "technical score": _first(canonical.get("technical_score"), canonical.get("master_score"), default="UNAVAILABLE"),\n',
    '        "trend strength": _first(canonical.get("trend_strength"), canonical.get("adx"), default="UNAVAILABLE"),\n',
    '        "ADX": _first(canonical.get("ADX"), canonical.get("adx"), default="UNAVAILABLE"),\n',
    '        "+DI": _first(canonical.get("+DI"), canonical.get("plus_di"), default="UNAVAILABLE"),\n',
    '        "-DI": _first(canonical.get("-DI"), canonical.get("minus_di"), default="UNAVAILABLE"),\n',
    '        "momentum": _first(canonical.get("momentum"), default="UNAVAILABLE"),\n',
    '        "volatility": _first(canonical.get("volatility"), _mapping(canonical.get("regime")).get("volatility_regime"), default="UNAVAILABLE"),\n',
    '        "compression": _first(canonical.get("compression"), default="UNAVAILABLE"),\n',
    '        "support/resistance state": _first(canonical.get("support_resistance_state"), default="UNAVAILABLE"),\n',
    '        "pullback readiness": _first(canonical.get("pullback_readiness"), default="UNAVAILABLE"),\n',
    '        "trend capacity remaining": _first(canonical.get("trend_capacity_remaining"), default="UNAVAILABLE"),\n',
    '        "forecast agreement": _first(_mapping(canonical.get("forecasts")).get("agreement_score"), default="UNAVAILABLE"),\n',
    '        "regime": _first(_mapping(canonical.get("regime")).get("major_regime"), canonical.get("current_major_regime"), default="UNAVAILABLE"),\n',
    '        "market quality": _first(canonical.get("market_quality"), _mapping(canonical.get("data_quality")).get("quality_score_0_100"), default="UNAVAILABLE"),\n',
    '        "conflict status": _first(canonical.get("conflict_status"), _mapping(canonical.get("final_decision")).get("conflict_status"), default="UNAVAILABLE"),\n',
    '        "reliability": _first(_mapping(canonical.get("reliability")).get("score"), default="UNAVAILABLE"),\n',
    '        "technical reason": _first(_mapping(canonical.get("final_decision")).get("main_reason"), default="Published technical facts only; no recalculation."),\n',
    '    }\n',
    '    df = pd.DataFrame([row])\n',
    '    state["field4_technical_fact_table_20260622"] = df\n',
    '    state["field4_technical_fact_summary_20260622"] = row\n',
    '    return df\n',
    '\n',
    '\n',
    'def agreement_label(sentiment: Any, technical: Any, decision: Any) -> tuple[str, str]:\n',
    '    vals = [str(x or "UNAVAILABLE").upper() for x in (sentiment, technical, decision)]\n',
    '    if any(v in {"UNAVAILABLE", "", "NONE"} for v in vals):\n',
    '        return "UNAVAILABLE", "At least one evidence source is unavailable."\n',
    '    dirs = ["BUY" if "BUY" in v else "SELL" if "SELL" in v else "WAIT" if "WAIT" in v or "NO TRADE" in v else v for v in vals]\n',
    '    if dirs[0] == dirs[1] == dirs[2]:\n',
    '        return "CONFIRM", "Sentiment, technical direction and protected decision align."\n',
    '    if len(set(dirs)) == 2:\n',
    '        return "PARTIAL", "Two of the three evidence columns align."\n',
    '    return "CONFLICT", "Evidence columns oppose each other."\n',
    '\n',
    '\n',
    'def _decision_history_frame(state: Mapping[str, Any]) -> pd.DataFrame:\n',
    '    for key in ("protected_decision_history_20260622", "full_metric_history_df_20260618", "canonical_priority_table_20260617"):\n',
    '        value = state.get(key)\n',
    '        if isinstance(value, pd.DataFrame) and not value.empty:\n',
    '            return value.copy(deep=False)\n',
    '    result = state.get("lunch_metric_result_cache") or state.get("full_metric_result_cache_20260618")\n',
    '    if isinstance(result, Mapping) and isinstance(result.get("history"), pd.DataFrame):\n',
    '        return result.get("history").copy(deep=False)\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def build_combined_field6_history(state: MutableMapping[str, Any], *, days: int = 25) -> pd.DataFrame:\n',
    '    started = time.perf_counter()\n',
    '    canonical = get_canonical_generation(state)\n',
    '    contract = market_time_contract(state, canonical)\n',
    '    decision = _decision_history_frame(state)\n',
    '    if decision.empty:\n',
    '        decision = pd.DataFrame([{"event_time_utc": contract.get("latest_completed_h1_utc")}])\n',
    '    tcol = _time_col(decision)\n',
    '    if tcol and tcol != "event_time_utc":\n',
    '        decision = decision.rename(columns={tcol: "event_time_utc"})\n',
    '    if "event_time_utc" not in decision.columns:\n',
    '        decision.insert(0, "event_time_utc", contract.get("latest_completed_h1_utc"))\n',
    '    decision["event_time_utc"] = pd.to_datetime(decision["event_time_utc"], errors="coerce", utc=True)\n',
    '    cutoff = _utc(contract.get("latest_completed_h1_utc"))\n',
    '    if cutoff is not None:\n',
    '        decision = decision.loc[decision["event_time_utc"].notna() & decision["event_time_utc"].le(cutoff) & decision["event_time_utc"].ge(cutoff - pd.Timedelta(days=days))]\n',
    '    decision = decision.sort_values("event_time_utc", ascending=False).head(days * 24 + 1)\n',
    '    sentiment = build_sentiment_history(state)\n',
    '    technical = publish_field4_technical_fact_table(state)\n',
    '    sentiment_for_join = sentiment.rename(columns={"published_time_utc": "published_time_utc"}) if not sentiment.empty else sentiment\n',
    '    merged = leakage_safe_asof_join(decision.sort_values("event_time_utc"), sentiment_for_join, left_time="event_time_utc", right_time="published_time_utc")\n',
    '    if not isinstance(merged, pd.DataFrame) or merged.empty:\n',
    '        merged = decision.copy(deep=False)\n',
    '    # Attach latest technical facts as evidence columns only.\n',
    '    tech_row = technical.iloc[0].to_dict() if isinstance(technical, pd.DataFrame) and not technical.empty else {}\n',
    '    final = _mapping(canonical.get("final_decision"))\n',
    '    regime = _mapping(canonical.get("regime"))\n',
    '    rows = []\n',
    '    for _, row in merged.iterrows():\n',
    '        protected_decision = _first(row.get("Decision"), row.get("decision"), row.get("Current Decision"), final.get("final_decision"), default="UNAVAILABLE")\n',
    '        protected_direction = _first(row.get("Direction"), row.get("direction_x"), row.get("Directional Market View"), final.get("directional_market_view"), default="UNAVAILABLE")\n',
    '        sent_dir = _first(row.get("direction_y"), row.get("direction"), row.get("EURUSD directional sentiment"), default="UNAVAILABLE")\n',
    '        tech_dir = _first(tech_row.get("technical direction"), default="UNAVAILABLE")\n',
    '        agree, reason = agreement_label(sent_dir, tech_dir, protected_direction)\n',
    '        rows.append({\n',
    '            "event_time_utc": row.get("event_time_utc"),\n',
    '            "symbol": contract.get("symbol"), "timeframe": contract.get("timeframe"),\n',
    '            "sentiment direction": sent_dir,\n',
    '            "sentiment score": _first(row.get("calibrated score"), default="UNAVAILABLE"),\n',
    '            "sentiment confidence": _first(row.get("confidence"), default="UNAVAILABLE"),\n',
    '            "news count": 0 if sent_dir == "UNAVAILABLE" else 1,\n',
    '            "top sentiment reason": _first(row.get("reason"), default="UNAVAILABLE"),\n',
    '            "sentiment age": _first(row.get("age_minutes"), default="UNAVAILABLE"),\n',
    '            "technical direction": tech_dir,\n',
    '            "technical score": _first(tech_row.get("technical score"), default="UNAVAILABLE"),\n',
    '            "regime": _first(row.get("regime"), tech_row.get("regime"), regime.get("major_regime"), default="UNAVAILABLE"),\n',
    '            "market quality": _first(row.get("market quality"), tech_row.get("market quality"), default="UNAVAILABLE"),\n',
    '            "forecast agreement": _first(tech_row.get("forecast agreement"), default="UNAVAILABLE"),\n',
    '            "reliability": _first(row.get("reliability"), tech_row.get("reliability"), default="UNAVAILABLE"),\n',
    '            "protected Decision": protected_decision,\n',
    '            "protected Direction": protected_direction,\n',
    '            "decision confidence": _first(row.get("Confidence"), row.get("confidence"), final.get("calibrated_confidence"), default="UNAVAILABLE"),\n',
    '            "sentiment/technical agreement": agree,\n',
    '            "decision conflict": reason,\n',
    '            "Agreement": agree,\n',
    '            "Reason": reason,\n',
    '            "data-quality score": _first(_mapping(canonical.get("data_quality")).get("quality_score_0_100"), default="UNAVAILABLE"),\n',
    '            "drift status": _first(_mapping(canonical.get("drift" )).get("status"), default="UNAVAILABLE"),\n',
    '            "synchronization status": "PENDING",\n',
    '            "calculation_id": contract.get("calculation_id"),\n',
    '            "generation": contract.get("calculation_generation"),\n',
    '        })\n',
    '    out = pd.DataFrame(rows)\n',
    '    if not out.empty:\n',
    '        out["event_time_utc"] = pd.to_datetime(out["event_time_utc"], errors="coerce", utc=True)\n',
    '        out = out.sort_values("event_time_utc", ascending=False, kind="mergesort").reset_index(drop=True)\n',
    '        out = add_broker_display_columns(out, state, canonical)\n',
    '        try:\n',
    '            from core.canonical_sync_v9 import normalize_history_frame\n',
    '            out = normalize_history_frame(out, field_name="FIELD_6", metric_name="combined_sentiment_technical_decision", state=state)\n',
    '        except Exception:\n',
    '            pass\n',
    '        sync = synchronization_status(state, field6_history=out, canonical=canonical)\n',
    '        out["synchronization status"] = sync.get("status")\n',
    '        state["lunch_sync_status_20260622"] = sync\n',
    '        first = out.iloc[0].to_dict()\n',
    '        state["field6_combined_history_summary_20260622"] = {\n',
    '            "Current Protected Decision": first.get("protected Decision"),\n',
    '            "Current Sentiment Direction": first.get("sentiment direction"),\n',
    '            "Current Technical Direction": first.get("technical direction"),\n',
    '            "Agreement": first.get("Agreement"),\n',
    '            "Reliability": first.get("reliability"),\n',
    '            "Data Quality": contract.get("data_quality_status"),\n',
    '            "Latest Broker Time": first.get("Broker Time"),\n',
    '            "Latest Myanmar Time": first.get("Myanmar Time"),\n',
    '        }\n',
    '    state["field6_combined_history_20260622"] = out\n',
    '    state["timing_field6_merge_20260622"] = round(time.perf_counter() - started, 6)\n',
    '    return out\n',
    '\n',
    '\n',
    'def render_field6_combined_history(state: MutableMapping[str, Any]) -> None:\n',
    '    try:\n',
    '        import streamlit as st\n',
    '        from ui.copy_tools import central_copy_button\n',
    '        table = build_combined_field6_history(state)\n',
    '        summary = state.get("field6_combined_history_summary_20260622") if isinstance(state.get("field6_combined_history_summary_20260622"), Mapping) else {}\n',
    '        st.markdown("#### Combined Sentiment + Technical + Decision History")\n',
    '        cols = st.columns(4)\n',
    '        cols[0].metric("Protected Decision", str(summary.get("Current Protected Decision", "UNAVAILABLE")))\n',
    '        cols[1].metric("Sentiment", str(summary.get("Current Sentiment Direction", "UNAVAILABLE")))\n',
    '        cols[2].metric("Technical", str(summary.get("Current Technical Direction", "UNAVAILABLE")))\n',
    '        cols[3].metric("Agreement", str(summary.get("Agreement", "UNAVAILABLE")))\n',
    '        if table.empty:\n',
    '            st.info("Combined history is unavailable for this generation.")\n',
    '        else:\n',
    '            st.dataframe(table.drop(columns=[c for c in ["event_time_utc"] if c in table.columns]), use_container_width=True, hide_index=True, height=520)\n',
    '            central_copy_button("Copy Field 6 Combined History", table.to_csv(index=False), "field6_combined_history_copy_20260622", height=112, show_fallback=True)\n',
    '    except Exception as exc:\n',
    '        try:\n',
    '            import streamlit as st\n',
    '            st.warning(f"Combined Field 6 history unavailable: {exc}")\n',
    '        except Exception:\n',
    '            pass\n',
    '\n',
    '\n',
    'def validate_data_quality_contract(state: Mapping[str, Any]) -> dict[str, Any]:\n',
    '    canonical = get_canonical_generation(state)\n',
    '    contract = market_time_contract(state, canonical)\n',
    '    frames = []\n',
    '    for key in ("full_metric_history_df_20260618", "canonical_priority_table_20260617", "field6_combined_history_20260622"):\n',
    '        v = state.get(key)\n',
    '        if isinstance(v, pd.DataFrame) and not v.empty:\n',
    '            frames.append((key, v))\n',
    '    flags: list[str] = []\n',
    '    warnings = 0\n',
    '    for key, frame in frames:\n',
    '        col = _time_col(frame)\n',
    '        if col:\n',
    '            parsed = pd.to_datetime(frame[col], errors="coerce", utc=True)\n',
    '            if parsed.isna().any():\n',
    '                flags.append(f"{key}: timestamp parse failure")\n',
    '            if parsed.notna().any() and (parsed.dropna().dt.minute.ne(0).any() or parsed.dropna().dt.second.ne(0).any()):\n',
    '                warnings += 1; flags.append(f"{key}: non-hourly H1 timestamp boundary")\n',
    '            if parsed.duplicated().any():\n',
    '                warnings += 1; flags.append(f"{key}: duplicate canonical timestamps")\n',
    '        for colname in frame.columns:\n',
    '            lower = str(colname).lower()\n',
    '            if "decision" in lower:\n',
    '                bad = [str(x).upper() for x in frame[colname].dropna().unique() if str(x).upper() not in DECISION_LABELS and len(str(x)) < 32]\n',
]
