"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '                if bad:\n',
    '                    warnings += 1; flags.append(f"{key}: non-standard decision labels {bad[:4]}")\n',
    '    score = max(0, 100 - len(flags) * 10 - warnings * 3)\n',
    '    status = "PASS" if score >= 85 and not flags else "WARN" if score >= 60 else "FAIL"\n',
    '    return {\n',
    '        "quality_score_0_100": score,\n',
    '        "quality_status": status,\n',
    '        "quality_flags": flags,\n',
    '        "failed_check_count": len([f for f in flags if "failure" in f.lower() or "parse" in f.lower()]),\n',
    '        "warning_count": warnings,\n',
    '        "last_validated_at_utc": pd.Timestamp.now(tz="UTC").isoformat(),\n',
    '        "validator_version": "lunch-broker-sentiment-ai-history-20260622-v1",\n',
    '        "calculation_id": contract.get("calculation_id"),\n',
    '        "generation": contract.get("calculation_generation"),\n',
    '        "checks": ["Completeness", "Validity", "Uniqueness", "Timeliness", "Cross-table consistency", "Calculation-generation consistency", "Timestamp consistency", "Source consistency", "Range validity", "Leakage safety"],\n',
    '    }\n',
    '\n',
    '\n',
    'def build_research_shadow_layers(state: Mapping[str, Any]) -> dict[str, Any]:\n',
    '    canonical = get_canonical_generation(state)\n',
    '    validation = _mapping(canonical.get("validation_metrics"))\n',
    '    forecasts = _mapping(canonical.get("forecasts"))\n',
    '    return {\n',
    '        "adaptive_conformal_calibration": {\n',
    '            "recent_coverage": _first(validation.get("coverage"), default="UNAVAILABLE"),\n',
    '            "target_coverage": _first(validation.get("target_coverage"), default=0.90),\n',
    '            "miscoverage": _first(validation.get("miscoverage"), default="UNAVAILABLE"),\n',
    '            "calibrated_lower_upper_bands": _first(forecasts.get("calibrated_bands"), default="UNAVAILABLE"),\n',
    '            "interval_status": "EVIDENCE_ONLY",\n',
    '        },\n',
    '        "adwin_style_drift": {"drift_detected": _first(_mapping(canonical.get("drift")).get("detected"), default=False), "drift_time": _first(_mapping(canonical.get("drift")).get("time"), default="UNAVAILABLE"), "effective_current_window": "UNAVAILABLE", "pre_post_change_magnitude": "UNAVAILABLE"},\n',
    '        "horizon_contribution_analysis_inspired_by_tft": {f"H+{h}": {"existing_model_contribution": "UNAVAILABLE", "technical_contribution": "UNAVAILABLE", "regime_contribution": "UNAVAILABLE", "sentiment_contribution": "UNAVAILABLE", "dominant_factor": "UNAVAILABLE", "conflict_count": "UNAVAILABLE"} for h in range(1, 7)},\n',
    '        "shap_style_explanation": {"supporting": [], "opposing": [], "WAIT-causing factors": []},\n',
    '        "diebold_mariano_forecast_comparison": {"status": "UNAVAILABLE unless enough settled outcomes exist", "loss_function": "absolute_error", "statistic": "UNAVAILABLE", "p_value": "UNAVAILABLE", "sample_size": _first(validation.get("sample_size"), default="UNAVAILABLE")},\n',
    '        "white_reality_check_hansen_spa_metadata": {"candidate_rules_or_models": "UNAVAILABLE", "benchmark": "current protected production decision", "statistical_support": "UNAVAILABLE", "data_snooping_warning": True},\n',
    '        "deflated_sharpe_metadata": {"raw_sharpe": "UNAVAILABLE", "adjusted_evidence": "UNAVAILABLE", "estimated_effective_trials": "UNAVAILABLE", "skew": "UNAVAILABLE", "kurtosis": "UNAVAILABLE", "track_record_sufficiency": "UNAVAILABLE"},\n',
    '        "note": "All layers are read-only evidence and do not alter protected decisions, strategies, model weights, TP or SL logic.",\n',
    '    }\n',
    '\n',
    '\n',
    '__all__ = [\n',
    '    "market_time_contract", "latest_completed_h1_utc", "add_broker_display_columns", "synchronization_status",\n',
    '    "build_ai_fact_pack", "payload_cache_key", "build_lunch_copy_payloads", "render_lunch_top_copy_buttons",\n',
    '    "classify_eurusd_sentiment", "build_sentiment_history", "leakage_safe_asof_join",\n',
    '    "publish_field4_technical_fact_table", "build_combined_field6_history", "render_field6_combined_history",\n',
    '    "agreement_label", "validate_data_quality_contract", "build_research_shadow_layers", "get_canonical_generation",\n',
    ']\n',
]
