"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Causal multi-scale probabilistic enrichment for the existing ADX Quant Pro pipeline.\n',
    '\n',
    'This module is deliberately additive.  It does not replace Full Metric History,\n',
    'the directional regime engine, KNN/Greedy, NLP, or the red/yellow/blue PowerBI\n',
    'paths.  It adds a lightweight risk and calibration layer inspired by multi-scale\n',
    'MS-GARCH, TFT variable gating, N-BEATS decomposition and PatchTST patching.\n',
    '\n',
    'All calculations use timestamp-sorted completed rows at or before the canonical\n',
    'latest-completed H1 timestamp.  The central PowerBI path is never changed; only\n',
    'its uncertainty bands, confidence metadata and downstream tradeability gates are\n',
    'enriched.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from copy import deepcopy\n',
    'from dataclasses import dataclass\n',
    'from hashlib import sha256\n',
    'import json\n',
    'import math\n',
    'import time\n',
    'from typing import Any, Dict, Iterable, Mapping, MutableMapping, Optional, Sequence, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'UPGRADE_VERSION = "multiscale-probabilistic-upgrade-20260618-v1"\n',
    'SHARED_SCHEMA_VERSION = "adx-canonical-shared-result-3.0.0"\n',
    'VOL_STATES = ("CALM", "TURBULENT", "CRISIS")\n',
    'PATCH_SPECS = (("micro_3h", 3), ("session_6h", 6), ("daily_24h", 24), ("weekly_120h", 120))\n',
    '\n',
    '\n',
    'def _finite(value: Any, default: float = 0.0) -> float:\n',
    '    try:\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else float(default)\n',
    '    except Exception:\n',
    '        return float(default)\n',
    '\n',
    '\n',
    'def _clip(value: Any, low: float, high: float) -> float:\n',
    '    return float(max(low, min(high, _finite(value, low))))\n',
    '\n',
    '\n',
    'def _json_scalar(value: Any) -> Any:\n',
    '    if value is None or value is pd.NA or value is pd.NaT:\n',
    '        return None\n',
    '    if isinstance(value, (pd.Timestamp,)):\n',
    '        ts = pd.Timestamp(value)\n',
    '        if pd.isna(ts):\n',
    '            return None\n',
    '        if ts.tzinfo is None:\n',
    '            ts = ts.tz_localize("UTC")\n',
    '        else:\n',
    '            ts = ts.tz_convert("UTC")\n',
    '        return ts.isoformat()\n',
    '    if isinstance(value, (np.integer,)):\n',
    '        return int(value)\n',
    '    if isinstance(value, (np.floating,)):\n',
    '        return float(value) if np.isfinite(value) else None\n',
    '    if isinstance(value, (np.bool_,)):\n',
    '        return bool(value)\n',
    '    try:\n',
    '        if pd.isna(value):\n',
    '            return None\n',
    '    except Exception:\n',
    '        pass\n',
    '    return value\n',
    '\n',
    '\n',
    'def _json_safe(value: Any) -> Any:\n',
    '    if isinstance(value, Mapping):\n',
    '        return {str(k): _json_safe(v) for k, v in value.items()}\n',
    '    if isinstance(value, (list, tuple)):\n',
    '        return [_json_safe(v) for v in value]\n',
    '    if isinstance(value, np.ndarray):\n',
    '        return [_json_safe(v) for v in value.tolist()]\n',
    '    if isinstance(value, pd.DataFrame):\n',
    '        return [_json_safe(r) for r in value.to_dict("records")]\n',
    '    if isinstance(value, pd.Series):\n',
    '        return [_json_safe(v) for v in value.tolist()]\n',
    '    return _json_scalar(value)\n',
    '\n',
    '\n',
    'def _find_col(frame: pd.DataFrame, aliases: Iterable[str]) -> Optional[str]:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return None\n',
    '    normalized = {str(c).strip().lower().replace("_", " "): c for c in frame.columns}\n',
    '    for alias in aliases:\n',
    '        key = str(alias).strip().lower().replace("_", " ")\n',
    '        if key in normalized:\n',
    '            return normalized[key]\n',
    '    for alias in aliases:\n',
    '        key = str(alias).strip().lower().replace("_", " ")\n',
    '        for name, column in normalized.items():\n',
    '            if key and key in name:\n',
    '                return column\n',
    '    return None\n',
    '\n',
    '\n',
    'def _completed_market(data: pd.DataFrame, latest_completed: Any = None) -> pd.DataFrame:\n',
    '    """Return one sorted causal OHLC frame without inventing or back-filling rows."""\n',
    '    if not isinstance(data, pd.DataFrame) or data.empty:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close"])\n',
    '    t = _find_col(data, ("time", "datetime", "timestamp", "date"))\n',
    '    c = _find_col(data, ("close", "c"))\n',
    '    if t is None or c is None:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close"])\n',
    '    o = _find_col(data, ("open", "o")); h = _find_col(data, ("high", "h")); l = _find_col(data, ("low", "l"))\n',
    '    out = pd.DataFrame({\n',
    '        "time": pd.to_datetime(data[t], errors="coerce", utc=True),\n',
    '        "close": pd.to_numeric(data[c], errors="coerce"),\n',
    '    })\n',
    '    out["open"] = pd.to_numeric(data[o], errors="coerce") if o else out["close"]\n',
    '    out["high"] = pd.to_numeric(data[h], errors="coerce") if h else out[["open", "close"]].max(axis=1)\n',
    '    out["low"] = pd.to_numeric(data[l], errors="coerce") if l else out[["open", "close"]].min(axis=1)\n',
    '    out = out.dropna(subset=["time", "close"]).sort_values("time", kind="stable").drop_duplicates("time", keep="last")\n',
    '    if latest_completed not in (None, ""):\n',
    '        cutoff = pd.to_datetime(latest_completed, errors="coerce", utc=True)\n',
    '        if pd.notna(cutoff):\n',
    '            out = out.loc[out["time"] <= cutoff]\n',
    '    out["high"] = out[["open", "high", "close"]].max(axis=1)\n',
    '    out["low"] = out[["open", "low", "close"]].min(axis=1)\n',
    '    return out.reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _frame_hash(frame: pd.DataFrame, tail: int = 720) -> str:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return "NO_DATA"\n',
    '    use = frame.tail(tail)[[c for c in ("time", "open", "high", "low", "close") if c in frame.columns]].copy()\n',
    '    values = pd.util.hash_pandas_object(use, index=False).values.tobytes()\n',
    '    return sha256(values).hexdigest()\n',
    '\n',
    '\n',
    'def _canonical_calculation_id(canonical: Mapping[str, Any], market: pd.DataFrame) -> str:\n',
    '    raw = "|".join([\n',
    '        str(canonical.get("symbol") or "EURUSD").upper(),\n',
    '        str(canonical.get("timeframe") or "H1").upper(),\n',
    '        str(canonical.get("latest_completed_candle_time") or (market["time"].iloc[-1] if not market.empty else "")),\n',
    '        str(canonical.get("data_signature") or _frame_hash(market)),\n',
    '        UPGRADE_VERSION,\n',
    '    ])\n',
    '    return "CALC-" + sha256(raw.encode("utf-8", errors="ignore")).hexdigest()[:24]\n',
    '\n',
    '\n',
    'def _student_t_logpdf(z: np.ndarray, df: float = 7.0) -> np.ndarray:\n',
    '    # Constant terms cancel during softmax, so only the stable kernel is needed.\n',
    '    return -0.5 * (df + 1.0) * np.log1p(np.square(z) / df)\n',
    '\n',
    '\n',
    'def _softmax(logits: np.ndarray) -> np.ndarray:\n',
    '    if logits.size == 0:\n',
    '        return logits\n',
    '    shifted = logits - np.nanmax(logits, axis=-1, keepdims=True)\n',
    '    exp = np.exp(np.clip(shifted, -80.0, 80.0))\n',
    '    denom = np.sum(exp, axis=-1, keepdims=True)\n',
    '    return exp / np.where(denom <= 0, 1.0, denom)\n',
    '\n',
    '\n',
    'def _aggregate_scale(h1: pd.DataFrame, hours: int) -> pd.DataFrame:\n',
    '    if hours <= 1:\n',
    '        return h1.copy(deep=False)\n',
    '    if h1.empty:\n',
    '        return h1.copy()\n',
    '    work = h1.set_index("time")\n',
    '    rule = f"{hours}h" if hours < 24 else "1D"\n',
    '    agg = work.resample(rule, label="right", closed="right").agg(\n',
    '        open=("open", "first"), high=("high", "max"), low=("low", "min"), close=("close", "last"), count=("close", "count")\n',
    '    ).dropna(subset=["close"])\n',
    '    # Exclude incomplete aggregate buckets. FX daily bars may contain 23 hours\n',
    '    # around DST, so the daily minimum remains conservative rather than exact.\n',
    '    minimum = hours if hours < 24 else 20\n',
    '    agg = agg.loc[agg["count"] >= minimum].drop(columns=["count"]).reset_index()\n',
    '    return agg\n',
    '\n',
    '\n',
    'def _robust_returns(frame: pd.DataFrame) -> np.ndarray:\n',
    '    if frame.empty or len(frame) < 2:\n',
    '        return np.array([], dtype=float)\n',
    '    ret = np.log(pd.to_numeric(frame["close"], errors="coerce").replace(0, np.nan)).diff().dropna().to_numpy(dtype=float)\n',
    '    if len(ret) >= 12:\n',
    '        med = float(np.median(ret)); mad = float(np.median(np.abs(ret - med)))\n',
    '        scale = 1.4826 * mad\n',
    '        if scale > 1e-12:\n',
    '            ret = np.clip(ret, med - 8.0 * scale, med + 8.0 * scale)\n',
    '    return ret\n',
    '\n',
    '\n',
    'def _garch_variance(returns: np.ndarray) -> np.ndarray:\n',
    '    if len(returns) == 0:\n',
    '        return np.array([], dtype=float)\n',
    '    base = max(float(np.var(returns[: min(len(returns), 48)])), 1e-12)\n',
    '    alpha, beta = 0.10, 0.86\n',
    '    omega = max(base * (1.0 - alpha - beta), 1e-14)\n',
    '    variance = np.empty(len(returns), dtype=float)\n',
    '    variance[0] = base\n',
    '    for i in range(1, len(returns)):\n',
    '        variance[i] = omega + alpha * returns[i - 1] ** 2 + beta * variance[i - 1]\n',
    '    return np.maximum(variance, 1e-14)\n',
    '\n',
    '\n',
    'def _static_transition() -> np.ndarray:\n',
    '    return np.array([[0.965, 0.032, 0.003], [0.055, 0.900, 0.045], [0.018, 0.112, 0.870]], dtype=float)\n',
    '\n',
    '\n',
    'def _dynamic_transition(base: np.ndarray, shock: float) -> np.ndarray:\n',
    '    """Causal TVTP-like tilt toward higher states when a volatility shock rises."""\n',
    '    s = _clip(shock, -3.0, 5.0)\n',
    '    out = base.copy()\n',
    '    positive = max(s, 0.0); negative = max(-s, 0.0)\n',
    '    out[0, 1] += 0.025 * positive; out[0, 2] += 0.010 * positive; out[0, 0] -= 0.035 * positive\n',
    '    out[1, 2] += 0.025 * positive; out[1, 1] -= 0.020 * positive; out[1, 0] -= 0.005 * positive\n',
    '    out[2, 1] += 0.020 * negative; out[2, 2] -= 0.020 * negative\n',
    '    out = np.clip(out, 0.001, None)\n',
    '    return out / out.sum(axis=1, keepdims=True)\n',
    '\n',
    '\n',
    'def _filter_probabilities(returns: np.ndarray, allow_dynamic: bool) -> Tuple[np.ndarray, np.ndarray, bool, Dict[str, Any]]:\n',
    '    if len(returns) == 0:\n',
    '        p = np.array([[1 / 3, 1 / 3, 1 / 3]], dtype=float)\n',
    '        return p, np.array([1e-6, 2e-6, 4e-6]), False, {"selection": "insufficient_history"}\n',
    '    variance = _garch_variance(returns)\n',
    '    multipliers = np.array([0.55, 1.35, 3.40], dtype=float)\n',
    '    state_variance = np.maximum(variance[:, None] * multipliers[None, :], 1e-14)\n',
    '    z = returns[:, None] / np.sqrt(state_variance)\n',
    '    emissions = _softmax(_student_t_logpdf(z) - 0.5 * np.log(state_variance))\n',
    '    base = _static_transition()\n',
    '\n',
    '    vol = np.sqrt(variance)\n',
    '    vol_series = pd.Series(vol)\n',
    '    trailing = vol_series.rolling(48, min_periods=8).median().shift(1)\n',
    '    causal_fallback = vol_series.expanding(min_periods=1).median().shift(1)\n',
    '    trailing_med = trailing.fillna(causal_fallback).fillna(float(vol[0])).to_numpy(dtype=float)\n',
    '    shock = np.log(np.maximum(vol, 1e-12) / np.maximum(trailing_med, 1e-12))\n',
    '\n',
    '    def run(dynamic: bool) -> np.ndarray:\n',
    '        probs = np.empty_like(emissions)\n',
    '        prior = np.array([0.72, 0.24, 0.04], dtype=float)\n',
    '        for i in range(len(returns)):\n',
    '            transition = _dynamic_transition(base, shock[i]) if dynamic else base\n',
    '            prior = prior @ transition\n',
    '            post = prior * emissions[i]\n',
    '            total = float(post.sum())\n',
    '            prior = post / total if total > 0 else np.array([1 / 3] * 3)\n',
    '            probs[i] = prior\n',
    '        return probs\n',
    '\n',
    '    static_probs = run(False)\n',
    '    dynamic_probs = run(True) if allow_dynamic and len(returns) >= 120 else static_probs\n',
    '    selected_dynamic = False\n',
    '    diagnostics: Dict[str, Any] = {"static_log_loss": None, "dynamic_log_loss": None, "selection": "static"}\n',
    '    if allow_dynamic and len(returns) >= 120:\n',
    '        # Pseudo labels are determined only from trailing conditional variance,\n',
    '        # never future returns. The final 25% is held out for transition choice.\n',
    '        q1, q2 = np.quantile(vol[: max(60, int(len(vol) * 0.75))], [0.55, 0.88])\n',
    '        labels = np.where(vol <= q1, 0, np.where(vol <= q2, 1, 2))\n',
    '        start = max(60, int(len(vol) * 0.75))\n',
    '        idx = np.arange(start, len(vol))\n',
    '        if len(idx) >= 12:\n',
    '            eps = 1e-12\n',
    '            static_loss = float(-np.mean(np.log(np.clip(static_probs[idx, labels[idx]], eps, 1.0))))\n',
    '            dynamic_loss = float(-np.mean(np.log(np.clip(dynamic_probs[idx, labels[idx]], eps, 1.0))))\n',
    '            selected_dynamic = dynamic_loss + 1e-4 < static_loss\n',
    '            diagnostics.update({\n',
    '                "static_log_loss": round(static_loss, 8),\n',
    '                "dynamic_log_loss": round(dynamic_loss, 8),\n',
    '                "selection": "time_varying" if selected_dynamic else "static",\n',
    '                "out_of_sample_improvement": round(static_loss - dynamic_loss, 8),\n',
    '            })\n',
    '    probs = dynamic_probs if selected_dynamic else static_probs\n',
    '    if len(vol) >= 80:\n',
    '        train_end = max(60, int(len(vol) * 0.75))\n',
    '        q1, q2 = np.quantile(vol[:train_end], [0.55, 0.88])\n',
    '        labels = np.where(vol <= q1, 0, np.where(vol <= q2, 1, 2))\n',
    '        holdout = np.arange(train_end, len(vol))\n',
    '        if len(holdout):\n',
    '            diagnostics["out_of_sample_regime_classification_accuracy_pct"] = round(\n',
    '                float(np.mean(np.argmax(probs[holdout], axis=1) == labels[holdout]) * 100.0), 4\n',
    '            )\n',
    '            diagnostics["out_of_sample_rows"] = int(len(holdout))\n',
    '    expected_state_vol = np.sqrt(np.maximum(float(np.median(variance[-min(96, len(variance)):])), 1e-14) * multipliers)\n',
    '    return probs, expected_state_vol, selected_dynamic, diagnostics\n',
    '\n',
    '\n',
    'def _run_lengths(labels: np.ndarray) -> Tuple[list[int], int]:\n',
    '    if len(labels) == 0:\n',
    '        return [], 0\n',
    '    lengths: list[int] = []\n',
    '    current = 1\n',
    '    for i in range(1, len(labels)):\n',
    '        if labels[i] == labels[i - 1]:\n',
    '            current += 1\n',
    '        else:\n',
    '            lengths.append(current); current = 1\n',
    '    age = current\n',
    '    return lengths, age\n',
    '\n',
    '\n',
    'def _duration_stats(labels: np.ndarray, current_state: int) -> Dict[str, Any]:\n',
    '    lengths, age = _run_lengths(labels)\n',
    '    state_lengths: list[int] = []\n',
    '    if len(labels):\n',
    '        start = 0\n',
    '        for i in range(1, len(labels) + 1):\n',
    '            if i == len(labels) or labels[i] != labels[start]:\n',
    '                if int(labels[start]) == int(current_state) and i < len(labels):\n',
    '                    state_lengths.append(i - start)\n',
    '                start = i\n',
    '    if not state_lengths:\n',
    '        state_lengths = lengths[-20:] if lengths else [max(age, 1)]\n',
    '    arr = np.asarray(state_lengths, dtype=float)\n',
    '    median = float(np.median(arr)); p75 = float(np.quantile(arr, 0.75)); p25 = float(np.quantile(arr, 0.25))\n',
    '    # Empirical semi-Markov survival: P(duration >= age+h | duration >= age).\n',
    '    at_risk = arr[arr >= max(age, 1)]\n',
    '    def survive(h: int) -> float:\n',
    '        if len(at_risk):\n',
    '            return float(np.mean(at_risk >= age + h))\n',
    '        scale = max(median, 1.0)\n',
    '        return float(math.exp(-h / scale))\n',
    '    s1, s3, s6 = survive(1), survive(3), survive(6)\n',
    '    percentile = float(np.mean(arr <= age) * 100.0)\n',
    '    return {\n',
    '        "current_regime_age_candles": int(age),\n',
    '        "historical_median_duration_candles": round(median, 3),\n',
    '        "historical_p25_duration_candles": round(p25, 3),\n',
    '        "historical_p75_duration_candles": round(p75, 3),\n',
    '        "remaining_duration_range_candles": [max(0, int(math.floor(p25 - age))), max(0, int(math.ceil(p75 - age)))],\n',
    '        "duration_percentile_pct": round(percentile, 3),\n',
    '        "survival_probability_next_1": round(s1, 6),\n',
    '        "survival_probability_next_3": round(s3, 6),\n',
    '        "survival_probability_next_6": round(s6, 6),\n',
    '        "transition_probability_next_1": round(1.0 - s1, 6),\n',
    '        "transition_probability_next_3": round(1.0 - s3, 6),\n',
    '        "transition_probability_next_6": round(1.0 - s6, 6),\n',
    '        "duration_sample_count": int(len(arr)),\n',
    '    }\n',
    '\n',
    '\n',
    'def _scale_regime(frame: pd.DataFrame, scale: str, allow_dynamic: bool) -> Dict[str, Any]:\n',
    '    returns = _robust_returns(frame)\n',
    '    probs, ordered_vol, dynamic, diagnostics = _filter_probabilities(returns, allow_dynamic=allow_dynamic)\n',
    '    current = probs[-1]\n',
    '    state = int(np.argmax(current))\n',
    '    entropy = float(-np.sum(current * np.log(np.clip(current, 1e-12, 1.0))) / math.log(3.0))\n',
    '    labels = np.argmax(probs, axis=1)\n',
    '    duration = _duration_stats(labels, state)\n',
    '    one_step_transition = duration["transition_probability_next_1"]\n',
    '    probability_transition = 1.0 - float(current[state]) * (1.0 - one_step_transition)\n',
    '    stability = _clip(100.0 * (1.0 - 0.56 * entropy - 0.44 * probability_transition), 0.0, 100.0)\n',
    '    remaining = duration["remaining_duration_range_candles"]\n',
    '    if remaining[1] <= 1:\n',
    '        window = "Next 1–2 completed candles"\n',
    '    elif remaining[0] == remaining[1]:\n',
    '        window = f"Around next {remaining[0]} completed candles"\n',
    '    else:\n',
    '        lo = max(1, remaining[0]); hi = max(lo + 1, remaining[1])\n',
    '        window = f"Next {lo}–{hi} completed candles"\n',
    '    confidence_label = "HIGH" if stability >= 72 else "MODERATE" if stability >= 48 else "LOW"\n',
    '    return {\n',
    '        "scale": scale,\n',
    '        "probabilities": {name: round(float(current[i]), 8) for i, name in enumerate(VOL_STATES)},\n',
    '        "dominant_volatility_regime": VOL_STATES[state],\n',
    '        "normalized_shannon_entropy": round(entropy, 8),\n',
    '        "regime_confidence_pct": round(float(current[state]) * 100.0, 4),\n',
    '        "regime_stability_pct": round(stability, 4),\n',
    '        "regime_change_risk_pct": round(100.0 - stability, 4),\n',
    '        "duration_adjusted_transition_risk_pct": round(_clip(probability_transition * 100.0, 0, 100), 4),\n',
    '        "expected_state_volatility": {name: round(float(ordered_vol[i]), 10) for i, name in enumerate(VOL_STATES)},\n',
    '        "transition_model": "TIME_VARYING" if dynamic else "STATIC",\n',
    '        "transition_model_validation": diagnostics,\n',
    '        "estimated_transition_window": window,\n',
    '        "transition_window_confidence": confidence_label,\n',
    '        "sample_count": int(len(returns)),\n',
    '        **duration,\n',
    '    }\n',
    '\n',
    '\n',
    'def _multiscale_regime(market: pd.DataFrame) -> Dict[str, Any]:\n',
    '    frames = {\n',
    '        "H1": market,\n',
    '        "H4": _aggregate_scale(market, 4),\n',
    '        "D1": _aggregate_scale(market, 24),\n',
    '    }\n',
    '    scales = {\n',
    '        "D1": _scale_regime(frames["D1"], "D1", allow_dynamic=False),\n',
    '        "H4": _scale_regime(frames["H4"], "H4", allow_dynamic=True),\n',
    '        "H1": _scale_regime(frames["H1"], "H1", allow_dynamic=True),\n',
    '    }\n',
    '    p_d = np.array([scales["D1"]["probabilities"][s] for s in VOL_STATES], dtype=float)\n',
    '    p_4 = np.array([scales["H4"]["probabilities"][s] for s in VOL_STATES], dtype=float)\n',
    '    p_1 = np.array([scales["H1"]["probabilities"][s] for s in VOL_STATES], dtype=float)\n',
    '    joint = np.einsum("i,j,k->ijk", p_d, p_4, p_1).reshape(-1)\n',
    '    joint = joint / max(float(joint.sum()), 1e-12)\n',
    '    joint_records = []\n',
    '    idx = 0\n',
    '    for d in VOL_STATES:\n',
    '        for h4 in VOL_STATES:\n',
    '            for h1 in VOL_STATES:\n',
    '                joint_records.append({"state": f"D1_{d}|H4_{h4}|H1_{h1}", "probability": round(float(joint[idx]), 10)})\n',
    '                idx += 1\n',
    '    agreement = float((np.dot(p_d, p_4) + np.dot(p_d, p_1) + np.dot(p_4, p_1)) / 3.0 * 10.0)\n',
    '    dominant = max(joint_records, key=lambda x: x["probability"])\n',
    '    entropy = float(np.mean([scales[s]["normalized_shannon_entropy"] for s in ("D1", "H4", "H1")]))\n',
    '    transition = float(np.average([scales["D1"]["duration_adjusted_transition_risk_pct"], scales["H4"]["duration_adjusted_transition_risk_pct"], scales["H1"]["duration_adjusted_transition_risk_pct"]], weights=[0.45, 0.33, 0.22]))\n',
    '    current = scales["H1"]["dominant_volatility_regime"]\n',
    '    return {\n',
    '        "states": list(VOL_STATES),\n',
    '        "scales": scales,\n',
    '        "current_volatility_regime": current,\n',
    '        "combined_regime_label": current,\n',
    '        "multi_scale_agreement_score_0_10": round(_clip(agreement, 0, 10), 4),\n',
    '        "mean_normalized_entropy": round(entropy, 8),\n',
    '        "multi_scale_transition_risk_pct": round(_clip(transition, 0, 100), 4),\n',
    '        "joint_27_state_probabilities": joint_records,\n',
    '        "joint_probability_sum": round(float(joint.sum()), 12),\n',
    '        "dominant_joint_state": dominant["state"],\n',
    '        "dominant_joint_state_probability": dominant["probability"],\n',
    '        "routing_note": "Soft 27-state routing only; no standalone BUY/SELL signal.",\n',
    '    }\n',
    '\n',
    '\n',
]
