"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '            st.dataframe(show, use_container_width=True, hide_index=True)\n',
    '        else:\n',
    '            st.info("This table has no rows yet.")\n',
    '\n',
    '    history_by_factor = result.get("history_by_factor", {}) or {}\n',
    '    with st.expander("📂 Open / Close — Separate 10 factor history", expanded=False):\n',
    '        if not history_by_factor:\n',
    '            st.info("No factor history loaded yet.")\n',
    '        else:\n',
    '            names = list(history_by_factor.keys())\n',
    '            factor = st.selectbox("Factor", names, key="lunch_metric_factor_pick")\n',
    '            fdf = history_by_factor.get(factor)\n',
    '            if isinstance(fdf, pd.DataFrame) and not fdf.empty:\n',
    '                cols = [c for c in ["Scale /10", "Date", "Weekday", "Hour", "Decision", "Score /100", "Open", "Close", "ADX", "Pressure", "M1 Confirm /10", "Meaning"] if c in fdf.columns]\n',
    '                st.dataframe(_lunch_newest_first_table_v20260609(fdf[cols], int(max_rows)), use_container_width=True, hide_index=True)\n',
    '            else:\n',
    '                st.info("No rows for this factor.")\n',
    '\n',
    '    with st.expander("📆 Open / Close — Full metric detail history with regime changes", expanded=False):\n',
    '        st.caption("Built only after Run Calculating. Includes available metric history plus EURUSD regime change history with open/close.")\n',
    '        hist = result.get("history") if isinstance(result, dict) else None\n',
    '        if isinstance(hist, pd.DataFrame) and not hist.empty:\n',
    '            st.dataframe(_lunch_newest_first_table_v20260609(hist, int(max_rows)), use_container_width=True, hide_index=True)\n',
    '        else:\n',
    '            st.info("No metric history table is available in the current calculation result.")\n',
    '        try:\n',
    '            dvis = _clean_lunch_visual_df(limit=1500)\n',
    '            regime_summary2, regime_history2 = _detect_lunch_regime_changes(dvis, horizon=24)\n',
    '            if regime_summary2.get("ok"):\n',
    '                h1, h2 = st.columns(2)\n',
    '                h1.metric("Regime Change Day", regime_summary2.get("last_regime_change_day", "-"), f"{regime_summary2.get(\'days_since_last_change\', 0)} days ago")\n',
    '                h2.metric("Estimated Remaining", f"{regime_summary2.get(\'estimated_days_remaining\', 0)} days", regime_summary2.get("estimated_next_change_day", "-"))\n',
    '                st.dataframe(regime_history2, use_container_width=True, hide_index=True)\n',
    '        except Exception as exc:\n',
    '            st.caption(f"Regime detail unavailable: {exc}")\n',
    '\n',
    '    with st.expander("📋 Copy compact metric detail", expanded=False):\n',
    '        regime_summary = {}\n',
    '        regime_history = st.session_state.get("lunch_regime_history")\n',
    '        try:\n',
    '            dvis = _clean_lunch_visual_df(limit=1500)\n',
    '            regime_summary, regime_history = _detect_lunch_regime_changes(dvis, horizon=24)\n',
    '        except Exception:\n',
    '            regime_summary = {"ok": False}\n',
    '        if isinstance(regime_summary, dict) and regime_summary.get("ok"):\n',
    '            cm1, cm2 = st.columns(2)\n',
    '            cm1.metric("Last Regime Change Day", regime_summary.get("last_regime_change_day", "-"), f"{regime_summary.get(\'days_since_last_change\', 0)} days ago")\n',
    '            cm2.metric("Estimated Days Remaining", f"{regime_summary.get(\'estimated_days_remaining\', 0)}", regime_summary.get("estimated_next_change_day", "-"))\n',
    '        payload = {"scores": scores, "tables": table_choices, "rows_limited": int(max_rows), "regime": regime_summary}\n',
    '        try:\n',
    '            from core.pro_terminal_uiux import render_mobile_copy_button\n',
    '            import json\n',
    '            render_mobile_copy_button("Copy Compact Metric Detail", json.dumps(payload, indent=2, default=str), "lunch_compact_metric_copy")\n',
    '        except Exception:\n',
    '            st.json(payload)\n',
    '\n',
    '\n',
    '\n',
    'def _detect_lunch_regime_changes(d, horizon=24):\n',
    '    """Fast EURUSD-aligned regime detector + simple regime duration forecast.\n',
    '\n',
    '    Additive helper only: it reads the already-normalized Data Visualization\n',
    '    frame and does not mutate source data or trigger heavy metric engines.\n',
    '    """\n',
    '    import pandas as pd\n',
    '    import numpy as np\n',
    '    if d is None or not isinstance(d, pd.DataFrame) or d.empty or "close" not in d.columns:\n',
    '        return {"ok": False, "message": "No clean OHLC data."}, pd.DataFrame()\n',
    '    x = d.copy()\n',
    '    if "time" not in x.columns:\n',
    '        x["time"] = pd.date_range(end=pd.Timestamp.now(), periods=len(x), freq="h")\n',
    '    x["time"] = pd.to_datetime(x["time"], errors="coerce")\n',
    '    x["close"] = pd.to_numeric(x["close"], errors="coerce")\n',
    '    if "open" in x.columns:\n',
    '        x["open"] = pd.to_numeric(x["open"], errors="coerce")\n',
    '    else:\n',
    '        x["open"] = x["close"].shift(1).fillna(x["close"])\n',
    '    x = x.dropna(subset=["time", "close"]).sort_values("time").reset_index(drop=True)\n',
    '    if len(x) < 20:\n',
    '        return {"ok": False, "message": "Need at least 20 candles for regime analysis."}, pd.DataFrame()\n',
    '\n',
    '    close = x["close"].astype("float64")\n',
    '    ret = close.pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    trend = x["trend_gap_pct"] if "trend_gap_pct" in x.columns else close.ewm(span=12, adjust=False).mean().sub(close.ewm(span=48, adjust=False).mean()).div(close.replace(0, np.nan)).mul(100).fillna(0)\n',
    '    vol = x["volatility_pct"] if "volatility_pct" in x.columns else ret.rolling(36, min_periods=4).std().mul(100).fillna(0)\n',
    '    mom = ret.rolling(12, min_periods=3).mean().fillna(0)\n',
    '    vol_med = float(vol.rolling(144, min_periods=20).median().iloc[-1]) if len(vol) >= 20 else float(vol.median())\n',
    '    vol_hi = float(vol.rolling(144, min_periods=20).quantile(.70).iloc[-1]) if len(vol) >= 20 else float(vol.quantile(.70))\n',
    '\n',
    '    direction = np.where((trend > 0) & (mom >= 0), "BULL", np.where((trend < 0) & (mom <= 0), "BEAR", "RANGE"))\n',
    '    energy = np.where(vol >= max(vol_hi, vol_med * 1.2), "HIGH_VOL", np.where(vol <= max(vol_med * .72, 1e-9), "LOW_VOL", "NORMAL_VOL"))\n',
    '    x["regime"] = pd.Series(direction, index=x.index).astype(str) + "_" + pd.Series(energy, index=x.index).astype(str)\n',
    '    # Smooth one-candle noise so EURUSD H1 does not flip regime too easily.\n',
    '    # Pandas rolling().agg/apply only accepts numeric windows in many versions.\n',
    '    # Keep this string-safe so Streamlit never raises: DataError: No numeric types to aggregate.\n',
    '    regimes = x["regime"].astype(str).tolist()\n',
    '    smooth = []\n',
    '    for i in range(len(regimes)):\n',
    '        window = regimes[max(0, i - 2):i + 1]\n',
    '        vc = pd.Series(window, dtype="object").value_counts()\n',
    '        smooth.append(str(vc.index[0]) if not vc.empty else str(regimes[i]))\n',
    '    x["regime_smooth"] = pd.Series(smooth, index=x.index, dtype="object")\n',
    '    x["regime_changed"] = x["regime_smooth"].ne(x["regime_smooth"].shift(1))\n',
    '\n',
    '    changes = x.loc[x["regime_changed"]].copy()\n',
    '    if changes.empty:\n',
    '        changes = x.head(1).copy()\n',
    '    rows = []\n',
    '    idxs = list(changes.index)\n',
    '    for n, idx in enumerate(idxs):\n',
    '        end_idx = (idxs[n + 1] - 1) if n + 1 < len(idxs) else len(x) - 1\n',
    '        seg = x.loc[idx:end_idx]\n',
    '        start_time = pd.Timestamp(x.loc[idx, "time"])\n',
    '        end_time = pd.Timestamp(x.loc[end_idx, "time"])\n',
    '        duration_days = max((end_time - start_time).total_seconds() / 86400.0, 0.0)\n',
    '        rows.append({\n',
    '            "Regime Change Day": start_time.strftime("%Y-%m-%d"),\n',
    '            "Change Time": start_time.strftime("%Y-%m-%d %H:%M"),\n',
    '            "Regime": str(x.loc[idx, "regime_smooth"]),\n',
    '            "Open": round(float(seg["open"].iloc[0]), 5),\n',
    '            "Close": round(float(seg["close"].iloc[-1]), 5),\n',
    '            "Bars": int(len(seg)),\n',
    '            "Duration Days": round(duration_days, 2),\n',
    '            "Return %": round((float(seg["close"].iloc[-1]) / max(float(seg["open"].iloc[0]), 1e-12) - 1.0) * 100, 4),\n',
    '            "Avg Vol %": round(float(vol.loc[seg.index].mean()), 5),\n',
    '            "Avg Trend Gap %": round(float(trend.loc[seg.index].mean()), 5),\n',
    '            "Regime Score /10": round(float(max(0, min(10, 5 + abs(float(trend.loc[seg.index].mean())) * 0.35 + float(vol.loc[seg.index].mean()) * 0.55 + min(len(seg) / 48.0, 2.0)))), 2),\n',
    '        })\n',
    '    hist = pd.DataFrame(rows)\n',
    '    durations = pd.to_numeric(hist["Duration Days"], errors="coerce").dropna()\n',
    '    completed = durations.iloc[:-1] if len(durations) > 1 else durations\n',
    '    median_days = float(completed.median()) if len(completed) else max(float(horizon) / 24.0, 1.0)\n',
    '    last_row = hist.iloc[-1].to_dict()\n',
    '    last_change_time = pd.to_datetime(last_row.get("Change Time"), errors="coerce")\n',
    '    now_time = pd.Timestamp(x["time"].iloc[-1])\n',
    '    elapsed_days = max((now_time - last_change_time).total_seconds() / 86400.0, 0.0) if pd.notna(last_change_time) else 0.0\n',
    '    remaining_days = max(median_days - elapsed_days, 0.0)\n',
    '    predicted_change_time = now_time + pd.Timedelta(days=remaining_days)\n',
    '    current_regime = str(last_row.get("Regime", "UNKNOWN"))\n',
    '    stability = int(max(0, min(100, 100 - abs(float(trend.iloc[-1])) * 5 - float(vol.iloc[-1]) * 18 + min(elapsed_days / max(median_days, 1e-9), 1) * 20)))\n',
    '    current_score_10 = round(float(max(0, min(10, 5 + abs(float(trend.iloc[-1])) * 0.35 + float(vol.iloc[-1]) * 0.55 + min(elapsed_days / max(median_days, 1e-9), 1.0) * 2.0))), 2)\n',
    '    summary = {\n',
    '        "ok": True,\n',
    '        "current_regime": current_regime,\n',
    '        "last_regime_change_day": str(last_row.get("Regime Change Day", "")),\n',
    '        "last_regime_change_time": str(last_row.get("Change Time", "")),\n',
    '        "days_since_last_change": round(float(elapsed_days), 2),\n',
    '        "estimated_days_remaining": round(float(remaining_days), 2),\n',
    '        "estimated_next_change_day": predicted_change_time.strftime("%Y-%m-%d"),\n',
    '        "estimated_next_change_time": predicted_change_time.strftime("%Y-%m-%d %H:%M"),\n',
    '        "median_regime_days": round(float(median_days), 2),\n',
    '        "regime_stability_pct": stability,\n',
    '        "regime_score_10": current_score_10,\n',
    '        "history_rows": int(len(hist)),\n',
    '    }\n',
    '    return summary, hist.tail(80).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _clean_lunch_visual_df(limit=1500):\n',
    '    """Normalize shared EURUSD/OHLC data lazily; allow larger Lunch/Data Visualization migration runs."""\n',
    '    import pandas as pd\n',
    '    import streamlit as st\n',
    '    staging = st.session_state.get("calculation_staging_ohlc_df_20260617") if st.session_state.get("settings_calculation_lock_20260617") else None\n',
    '    df = staging if isinstance(staging, pd.DataFrame) and not staging.empty else st.session_state.get("last_df")\n',
    '    if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '        return pd.DataFrame()\n',
    '    limit = int(max(100, min(int(limit or 1500), 20000)))\n',
    '    sig = _lunch_df_signature()\n',
    '    try:\n',
    '        return _cached_clean_lunch_visual_df(df, limit, sig)\n',
    '    except Exception:\n',
    '        return _clean_lunch_visual_df_uncached(df, limit)\n',
    '\n',
    '\n',
    'def _clean_lunch_visual_df_uncached(df, limit=1500):\n',
    '    import pandas as pd\n',
    '    import numpy as np\n',
    '    d = _compact_ohlc_tail(df, rows=int(limit))\n',
    '    if d.empty or "close" not in d.columns:\n',
    '        return pd.DataFrame()\n',
    '    if "time" not in d.columns:\n',
    '        return pd.DataFrame()\n',
    '    d["time"] = pd.to_datetime(d["time"], errors="coerce")\n',
    '    for c in ["open", "high", "low", "close", "volume"]:\n',
    '        if c in d.columns:\n',
    '            d[c] = pd.to_numeric(d[c], errors="coerce").astype("float32")\n',
    '    d = d.dropna(subset=["time", "close"]).sort_values("time").drop_duplicates("time", keep="last").tail(limit).reset_index(drop=True)\n',
    '    if d.empty:\n',
    '        return d\n',
    '    close = d["close"].astype("float32")\n',
    '    prev_close = close.shift(1)\n',
    '    high = d["high"].astype("float32") if "high" in d.columns else close\n',
    '    low = d["low"].astype("float32") if "low" in d.columns else close\n',
    '    d["returns"] = close.pct_change().replace([np.inf, -np.inf], np.nan).fillna(0).astype("float32")\n',
    '    d["return_pct"] = (d["returns"] * 100).astype("float32")\n',
    '    tr = pd.concat([(high-low).abs(), (high-prev_close).abs(), (low-prev_close).abs()], axis=1).max(axis=1)\n',
    '    d["atr"] = tr.rolling(14, min_periods=2).mean().fillna(0).astype("float32")\n',
    '    delta = close.diff().fillna(0)\n',
    '    gain = delta.clip(lower=0).rolling(14, min_periods=2).mean()\n',
    '    loss = (-delta.clip(upper=0)).rolling(14, min_periods=2).mean().replace(0, np.nan)\n',
    '    d["rsi"] = (100 - (100 / (1 + gain / loss))).fillna(50).clip(0, 100).astype("float32")\n',
    '    d["rolling_mean"] = close.rolling(34, min_periods=4).mean().ffill().fillna(close).astype("float32")\n',
    '    d["rolling_std"] = close.rolling(34, min_periods=4).std().fillna(0).astype("float32")\n',
    '    d["ma_fast"] = close.ewm(span=12, adjust=False, min_periods=2).mean().astype("float32")\n',
    '    d["ma_slow"] = close.ewm(span=48, adjust=False, min_periods=4).mean().astype("float32")\n',
    '    d["ma_trend"] = close.ewm(span=144, adjust=False, min_periods=8).mean().ffill().fillna(close).astype("float32")\n',
    '    d["volatility_pct"] = d["return_pct"].rolling(36, min_periods=4).std().fillna(0).astype("float32")\n',
    '    d["range_pct"] = (((high - low) / close.replace(0, np.nan)) * 100).replace([np.inf, -np.inf], np.nan).fillna(d["return_pct"].abs()).astype("float32")\n',
    '    d["trend_gap_pct"] = (((d["ma_fast"] - d["ma_slow"]) / close.replace(0, np.nan)) * 100).replace([np.inf, -np.inf], np.nan).fillna(0).astype("float32")\n',
    '    d["trend"] = (((d["ma_fast"] - d["ma_slow"]) / d["atr"].replace(0, np.nan))).replace([np.inf, -np.inf], np.nan).fillna(0).clip(-5, 5).astype("float32")\n',
    '    score = 50 + d["return_pct"].rolling(8, min_periods=2).mean().fillna(0) * 190 + d["trend_gap_pct"] * 18 - d["volatility_pct"] * 10 + (d["rsi"] - 50) * .35\n',
    '    d["ml_score"] = score.clip(0, 100).astype("float32")\n',
    '    d["ml_bias"] = pd.Series(np.where(d["ml_score"] >= 56, "BUY", np.where(d["ml_score"] <= 44, "SELL", "WAIT")), dtype="category")\n',
    '    if "volume" in d.columns:\n',
    '        vm = d["volume"].rolling(48, min_periods=8).mean(); vs = d["volume"].rolling(48, min_periods=8).std().replace(0, np.nan)\n',
    '        d["volume_z"] = ((d["volume"] - vm) / vs).replace([np.inf, -np.inf], np.nan).fillna(0).clip(-5, 5).astype("float32")\n',
    '    else:\n',
    '        d["volume_z"] = np.float32(0)\n',
    '    q25, q75 = (float(d["volatility_pct"].quantile(.25)), float(d["volatility_pct"].quantile(.75))) if len(d) >= 20 else (0.0, 0.0)\n',
    '    d["risk_bucket"] = pd.Series(np.where(d["volatility_pct"] >= q75, "HIGH VOL", np.where(d["volatility_pct"] <= q25, "LOW VOL", "NORMAL")), dtype="category")\n',
    '    return d\n',
    '\n',
    '\n',
    'try:\n',
    '    import streamlit as st\n',
    '    _cached_clean_lunch_visual_df = st.cache_data(show_spinner=False, ttl=600)(_clean_lunch_visual_df_uncached)\n',
    'except Exception:\n',
    '    _cached_clean_lunch_visual_df = _clean_lunch_visual_df_uncached\n',
    '\n',
    '\n',
    'def _five_layer_powerbi_calculate(d, horizon=20):\n',
    '    import pandas as pd\n',
    '    import numpy as np\n',
    '    if d is None or d.empty or len(d) < 30:\n',
    '        return {"ok": False, "message": "Need at least 30 clean OHLC candles."}\n',
    '    try:\n',
    '        return _cached_five_layer_powerbi_calculate(d, int(horizon), _lunch_df_signature())\n',
    '    except Exception:\n',
    '        return _five_layer_powerbi_uncached(d, int(horizon), _lunch_df_signature())\n',
    '\n',
    '\n',
    'def _five_layer_powerbi_uncached(d, horizon=20, sig=None):\n',
    '    import pandas as pd\n',
    '    import numpy as np\n',
    '    horizon = int(max(5, min(int(horizon or 20), 60)))\n',
    '    x = d.tail(min(len(d), 3000))\n',
    '    close = x["close"].astype("float32")\n',
    '    ret = x["returns"].astype("float32") if "returns" in x else close.pct_change().fillna(0).astype("float32")\n',
    '    vol = x["volatility_pct"].astype("float32") if "volatility_pct" in x else (ret.rolling(36).std().fillna(0)*100).astype("float32")\n',
    '    trend = x["trend"].astype("float32") if "trend" in x else ret.rolling(20).mean().fillna(0).astype("float32")\n',
    '    rsi = x["rsi"].astype("float32") if "rsi" in x else pd.Series(50, index=x.index, dtype="float32")\n',
    '    rng = x["range_pct"].astype("float32") if "range_pct" in x else ret.abs().mul(100).astype("float32")\n',
    '    last_close = float(close.iloc[-1])\n',
    '    last_time = pd.Timestamp(x["time"].iloc[-1]) if "time" in x else pd.Timestamp.now()\n',
    '    tlast, vlast, rlast = float(trend.iloc[-1]), float(vol.iloc[-1]), float(rsi.iloc[-1])\n',
    '    mom12 = float(ret.tail(12).mean()); mom48 = float(ret.tail(48).mean()) if len(ret) >= 48 else mom12\n',
    '    bull_raw = 50 + tlast * 8 + mom12 * 14000 + mom48 * 9000 + (rlast - 50) * .38 - vlast * 1.8\n',
    '    bull_prob = int(max(1, min(99, bull_raw)))\n',
    '    bear_prob = 100 - bull_prob\n',
    '    range_prob = int(max(0, min(100, 100 - abs(bull_prob - 50) * 2)))\n',
    '    hmm_bull = int(max(0, min(100, bull_prob - range_prob * .22)))\n',
    '    hmm_bear = int(max(0, min(100, bear_prob - range_prob * .22)))\n',
    '    smoothed = close.ewm(alpha=.18, adjust=False).mean()\n',
    '    kalman_strength = float(max(0, min(10, abs((float(smoothed.iloc[-1]) - float(smoothed.iloc[-12 if len(smoothed) >= 12 else 0])) / max(last_close, 1e-9)) * 12000)))\n',
    '    bayes_conviction = float(max(0, min(10, abs(bull_prob - 50) / 5)))\n',
    '    wavelet_alignment = float(max(0, min(10, 5 + np.sign(mom12) * np.sign(mom48) * min(abs(mom12 + mom48) * 9000, 5))))\n',
    '    regime_score = round(float(max(0, min(10, (kalman_strength + bayes_conviction + wavelet_alignment) / 3))), 2)\n',
    '    current_regime = "BULL" if bull_prob >= 57 else "BEAR" if bull_prob <= 43 else "RANGE"\n',
    '\n',
    '    jump_sweep = float(max(0, min(10, (abs(float(ret.iloc[-1])) / max(float(ret.tail(80).std()), 1e-7)) * 2.2 + float(rng.iloc[-1]) * .9)))\n',
    '    flow_imbalance = float(max(-100, min(100, tlast * 12 + mom12 * 22000 + (rlast - 50) * .7)))\n',
    '    cross_venue = float(max(0, min(10, abs(float(close.iloc[-1] - close.rolling(8, min_periods=2).mean().iloc[-1])) / max(float(x.get("atr", pd.Series([0])).iloc[-1]), 1e-7))))\n',
    '    vacuum = float(max(0, min(10, (float(rng.tail(8).mean()) / max(float(rng.tail(80).median()), .0001)) * 3 + max(0, float(vol.iloc[-1] - vol.tail(80).median())) * 1.5)))\n',
    '    flow_score = round(float(max(0, min(10, jump_sweep * .25 + abs(flow_imbalance) / 100 * 3 + cross_venue * .2 + vacuum * .25))), 2)\n',
    '\n',
    '    model_scores = {\n',
    '        "XGBoost-style": 50 + mom12 * 15000 + tlast * 7 + (rlast-50)*.25,\n',
    '        "LightGBM-style": 50 + mom48 * 12000 + tlast * 6 - vlast * 1.2,\n',
    '        "CatBoost-style": 50 + (rlast-50)*.55 + mom12 * 9000,\n',
    '        "Random Forest-style": 50 + np.sign(mom12 + mom48) * min(abs(mom12 + mom48) * 10000, 28) + tlast * 4,\n',
    '    }\n',
    '    votes = []\n',
    '    for name, score in model_scores.items():\n',
    '        p = int(max(1, min(99, score)))\n',
    '        votes.append({"Model": name, "Vote": "BULL" if p >= 52 else "BEAR", "Bull Probability %": p, "Bear Probability %": 100-p})\n',
    '    vote_df = pd.DataFrame(votes)\n',
    '    bull_votes = int((vote_df["Vote"] == "BULL").sum()); bear_votes = int((vote_df["Vote"] == "BEAR").sum())\n',
    '    ensemble_prob = int(vote_df["Bull Probability %"].mean())\n',
    '    ensemble_score = round(max(0, min(10, ensemble_prob / 10)), 2)\n',
    '\n',
    '    lstm_proxy = 50 + mom48 * 16000 + tlast * 6\n',
    '    transformer_proxy = 50 + mom12 * 13000 + (rlast-50)*.28\n',
    '    cnn_proxy = 50 + float((ret.tail(5).gt(0).mean() - .5) * 42) + tlast * 3\n',
    '    ae_anomaly = float(max(0, min(10, abs(float(ret.iloc[-1])) / max(float(ret.tail(100).std()), 1e-7))))\n',
    '    deep_models = pd.DataFrame([\n',
    '        {"Model": "LSTM-style forecast proxy", "Output": "BULL" if lstm_proxy >= 50 else "BEAR", "Score /10": round(max(0,min(10,lstm_proxy/10)),2)},\n',
    '        {"Model": "Transformer-style forecast proxy", "Output": "BULL" if transformer_proxy >= 50 else "BEAR", "Score /10": round(max(0,min(10,transformer_proxy/10)),2)},\n',
    '        {"Model": "CNN pattern recognition proxy", "Output": "BULL" if cnn_proxy >= 50 else "BEAR", "Score /10": round(max(0,min(10,cnn_proxy/10)),2)},\n',
    '        {"Model": "Autoencoder anomaly detection proxy", "Output": "ANOMALY" if ae_anomaly >= 6 else "NORMAL", "Score /10": round(10-ae_anomaly if ae_anomaly < 10 else 0,2)},\n',
    '    ])\n',
    '    deep_score = round(float(deep_models["Score /10"].mean()), 2)\n',
    '\n',
    '    avg_drift = float(max(-.006, min(.006, mom12*.45 + mom48*.35 + (ensemble_prob-50)/100000 + tlast/12000)))\n',
    '    days = [5, 10, 20]\n',
    '    f_rows = []\n',
    '    for n in days:\n',
    '        pred = last_close * (1 + avg_drift * n)\n',
    '        width = max(float(ret.tail(120).std()), 1e-6) * (n ** .5) * 1.25\n',
    '        f_rows.append({"Horizon": f"{n}d", "LSTM Forecast": round(last_close*(1+(avg_drift*1.05)*n),5), "Transformer Forecast": round(last_close*(1+(avg_drift*.92)*n),5), "XGBoost Forecast": round(last_close*(1+(avg_drift*1.12)*n),5), "Prophet Fallback": round(last_close*(1+(avg_drift*.75)*n),5), "Low": round(pred*(1-width),5), "High": round(pred*(1+width),5)})\n',
    '    forecast_df = pd.DataFrame(f_rows)\n',
    '    forecast_conf = int(max(1, min(99, 62 + abs(ensemble_prob-50)*.35 + regime_score*2 - vlast*2.2 - ae_anomaly*1.3)))\n',
    '    forecast_score = round(max(0, min(10, forecast_conf/10)), 2)\n',
    '\n',
    '    # regime history newest first: today/latest data appears at the top, no heavy scrolling through old rows.\n',
    '    regime_raw = np.where((trend > .18) | (x["ml_score"] >= 56), "BULL", np.where((trend < -.18) | (x["ml_score"] <= 44), "BEAR", "RANGE"))\n',
    '    hist_base = x[["time","open","close"]].copy(); hist_base["Regime"] = pd.Series(regime_raw, dtype="category")\n',
    '    hist_base["Regime Score /10"] = (5 + trend.abs()*.8 + vol*.28 + (x["ml_score"]-50).abs()/14).clip(0,10).round(2).astype("float32")\n',
    '    changes = hist_base[hist_base["Regime"].astype(str).ne(hist_base["Regime"].astype(str).shift(1))].index.tolist() or [hist_base.index[0]]\n',
    '    segs=[]\n',
    '    for i, idx in enumerate(changes):\n',
    '        end_idx = (changes[i+1]-1) if i+1 < len(changes) else hist_base.index[-1]\n',
    '        seg = hist_base.loc[idx:end_idx]\n',
    '        days_in = max((pd.Timestamp(seg["time"].iloc[-1]) - pd.Timestamp(seg["time"].iloc[0])).total_seconds()/86400, 0)\n',
    '        segs.append({"Start": pd.Timestamp(seg["time"].iloc[0]), "Open": round(float(seg["open"].iloc[0]),5), "Close": round(float(seg["close"].iloc[-1]),5), "Regime": str(seg["Regime"].iloc[0]), "Regime Score /10": round(float(seg["Regime Score /10"].mean()),2), "Days In Regime": round(days_in,2)})\n',
    '    hist = pd.DataFrame(segs).sort_values("Start", ascending=False).head(60)\n',
    '    hist["Start"] = hist["Start"].dt.strftime("%Y-%m-%d %H:%M")\n',
    '    hist["Regime"] = hist["Regime"].astype("category")\n',
    '    current_days = float(hist.iloc[0]["Days In Regime"]) if not hist.empty else 0.0\n',
    '    completed = pd.to_numeric(hist["Days In Regime"], errors="coerce").iloc[1:]\n',
    '    med_days = float(completed.median()) if len(completed) else 5.0\n',
    '    days_remaining = max(med_days - current_days, 0.0)\n',
    '    next_change = last_time + pd.Timedelta(days=days_remaining)\n',
    '    master_score = round(float(max(0, min(10, regime_score*.22 + flow_score*.18 + ensemble_score*.24 + deep_score*.18 + forecast_score*.18))), 2)\n',
    '    return {"ok": True, "last_time": last_time, "last_close": last_close, "current_regime": current_regime, "master_score": master_score, "bull_probability": int(max(1,min(99,(bull_prob+ensemble_prob)//2))), "last_regime_change": str(hist.iloc[0]["Start"]) if not hist.empty else "-", "days_in_regime": round(current_days,2), "estimated_days_remaining": round(days_remaining,2), "predicted_next_regime_change": next_change.strftime("%Y-%m-%d %H:%M"), "layer1": {"HMM Bull %": hmm_bull, "HMM Bear %": hmm_bear, "HMM Range %": range_prob, "Kalman Trend Strength /10": round(kalman_strength,2), "Bayesian Conviction /10": round(bayes_conviction,2), "Wavelet Alignment /10": round(wavelet_alignment,2), "Regime Score /10": regime_score}, "layer2": {"Jump Sweep Score /10": round(jump_sweep,2), "Flow Imbalance": round(flow_imbalance,2), "Cross Venue Score /10": round(cross_venue,2), "Vacuum Score /10": round(vacuum,2), "Flow Score /10": flow_score}, "vote_df": vote_df, "layer3": {"Bull Votes": bull_votes, "Bear Votes": bear_votes, "Bull Probability %": ensemble_prob, "Ensemble Score /10": ensemble_score}, "deep_df": deep_models, "layer4": {"Deep AI Score /10": deep_score}, "forecast_df": forecast_df, "layer5": {"Forecast Confidence %": forecast_conf, "Forecast Score /10": forecast_score}, "history": hist}\n',
    '\n',
    '\n',
    'try:\n',
    '    import streamlit as st\n',
    '    _cached_five_layer_powerbi_calculate = st.cache_data(show_spinner=False, ttl=900)(_five_layer_powerbi_uncached)\n',
    'except Exception:\n',
    '    _cached_five_layer_powerbi_calculate = _five_layer_powerbi_uncached\n',
    '\n',
    '\n',
    'def _render_lunch_advanced_powerbi_ml_projection(d, horizon=20):\n',
    '    import pandas as pd\n',
    '    import streamlit as st\n',
    '    try:\n',
    '        import plotly.graph_objects as go\n',
    '        from plotly.subplots import make_subplots\n',
    '    except Exception as exc:\n',
    '        st.warning(f"Plotly is not available for advanced Power BI dashboard: {exc}")\n',
    '        return\n',
    '    result = st.session_state.get("lunch_5layer_powerbi_result")\n',
    '    if not isinstance(result, dict) or not result.get("ok"):\n',
    '        st.info("Click **Run Calculating** to calculate the 5 separate Power BI + ML layers.")\n',
    '        return\n',
    '\n',
    '    m = st.columns(7)\n',
    '    m[0].metric("Master Score", f"{result[\'master_score\']}/10")\n',
    '    m[1].metric("Bull Probability", f"{result[\'bull_probability\']}%")\n',
    '    m[2].metric("Regime", result["current_regime"])\n',
    '    m[3].metric("Last Regime Change", result["last_regime_change"])\n',
    '    m[4].metric("Days In Regime", result["days_in_regime"])\n',
    '    m[5].metric("Est. Days Remaining", result["estimated_days_remaining"])\n',
    '    m[6].metric("Predicted Next Change", result["predicted_next_regime_change"])\n',
    '\n',
    '    layer_names = ["Layer 1 Regime", "Layer 2 Flow", "Layer 3 Ensemble", "Layer 4 Deep AI", "Layer 5 Forecast"]\n',
    '    layer_scores = [result["layer1"]["Regime Score /10"], result["layer2"]["Flow Score /10"], result["layer3"]["Ensemble Score /10"], result["layer4"]["Deep AI Score /10"], result["layer5"]["Forecast Score /10"]]\n',
    '    fig = make_subplots(rows=2, cols=2, specs=[[{"type":"bar"},{"type":"indicator"}], [{"type":"scatter"},{"type":"table"}]], vertical_spacing=.12, horizontal_spacing=.08, subplot_titles=("5 Separate Layer Scores", "Master Score", "Recent Close / ML Bias", "Layer Details"))\n',
    '    fig.add_trace(go.Bar(x=layer_names, y=layer_scores, name="Score /10"), row=1, col=1)\n',
    '    fig.add_trace(go.Indicator(mode="gauge+number", value=float(result["master_score"]), gauge={"axis":{"range":[0,10]}}, title={"text":"Master /10"}), row=1, col=2)\n',
    '    show = d.tail(min(len(d), 700))\n',
    '    fig.add_trace(go.Scatter(x=show["time"], y=show["close"], mode="lines", name="EURUSD Close"), row=2, col=1)\n',
    '    if "ml_score" in show:\n',
    '        fig.add_trace(go.Scatter(x=show["time"], y=show["ml_score"], mode="lines", name="ML Score", yaxis="y3"), row=2, col=1)\n',
    '    detail_rows = []\n',
    '    for title, vals in [("Layer 1", result["layer1"]), ("Layer 2", result["layer2"]), ("Layer 3", result["layer3"]), ("Layer 4", result["layer4"]), ("Layer 5", result["layer5"] )]:\n',
    '        detail_rows.append([title, "<br>".join(f"{k}: {v}" for k, v in vals.items())])\n',
    '    fig.add_trace(go.Table(header={"values":["Layer", "Separate Outputs"]}, cells={"values":[[r[0] for r in detail_rows], [r[1] for r in detail_rows]], "height":28}), row=2, col=2)\n',
    '    fig.update_layout(height=760, margin=dict(l=6, r=6, t=50, b=6), legend=dict(orientation="h"), title="Advanced Power BI + ML Dashboard — 5 Separate Layer Results")\n',
    '    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False, "responsive": True})\n',
    '\n',
    '    c1, c2 = st.columns(2)\n',
    '    with c1:\n',
    '        st.markdown("#### Layer 1 — Regime Engine")\n',
    '        st.dataframe(pd.DataFrame([result["layer1"]]), use_container_width=True, hide_index=True)\n',
    '        st.markdown("#### Layer 3 — Prediction Ensemble Voting")\n',
    '        st.dataframe(result["vote_df"], use_container_width=True, hide_index=True)\n',
    '    with c2:\n',
    '        st.markdown("#### Layer 2 — Institutional Flow Engine")\n',
    '        st.dataframe(pd.DataFrame([result["layer2"]]), use_container_width=True, hide_index=True)\n',
    '        st.markdown("#### Layer 4 — Deep AI Layer")\n',
    '        st.dataframe(result["deep_df"], use_container_width=True, hide_index=True)\n',
    '    st.markdown("#### Layer 5 — Forecast Engine")\n',
    '    st.dataframe(result["forecast_df"], use_container_width=True, hide_index=True)\n',
    '    st.markdown("#### Regime History — newest first")\n',
    '    hist = result.get("history")\n',
    '    if isinstance(hist, pd.DataFrame) and not hist.empty:\n',
    '        st.dataframe(hist, use_container_width=True, hide_index=True, height=260)\n',
    '    st.session_state["lunch_prediction_export"] = {k: v for k, v in result.items() if k not in {"vote_df", "deep_df", "forecast_df", "history"}}\n',
    '    st.session_state["lunch_regime_history"] = hist\n',
    '\n',
    '\n',
    'def _apply_mobile_first_app_css_v20260609():\n',
    '    try:\n',
    '        import streamlit as st\n',
    '        st.markdown("""\n',
    '        <style>\n',
    '        @media (max-width: 780px){\n',
    '          .block-container{padding-top:.65rem!important;padding-left:.55rem!important;padding-right:.55rem!important;}\n',
    '          div[data-testid="stMetric"]{border-radius:18px;padding:10px 12px;background:rgba(255,255,255,.06);border:1px solid rgba(125,211,252,.22);box-shadow:0 8px 28px rgba(15,23,42,.10);}\n',
    '          div[data-testid="stDataFrame"]{border-radius:16px;overflow:hidden;}\n',
    '          .stButton>button{border-radius:999px!important;min-height:44px;font-weight:800!important;box-shadow:0 10px 24px rgba(14,165,233,.18);}\n',
    '          [data-testid="stHorizontalBlock"]{gap:.45rem;}\n',
    '        }\n',
    '        </style>\n',
    '        """, unsafe_allow_html=True)\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
]
