"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '\n',
    'def _render_lunch_data_visualization_inner_tab():\n',
    '    import streamlit as st\n',
    '    st.markdown("### 📊 Data Visualization")\n',
    '    st.caption("Phone-safe lazy dashboard: nothing calculates until Run Calculating is clicked; cached results are reused when changing tabs.")\n',
    '    c0, c1, c2 = st.columns([1.2, 1, 1])\n',
    '    with c0:\n',
    '        run = st.button("▶ Run Calculating", use_container_width=True, key="lunch_data_visual_run_calculating")\n',
    '    with c1:\n',
    '        rows_limit = st.slider("Rows used", 1000, 3000, int(st.session_state.get("lunch_bi_rows_limit", 1500)), 250, key="lunch_bi_rows_limit")\n',
    '    with c2:\n',
    '        horizon = st.slider("Forecast candles", 5, 60, int(st.session_state.get("lunch_bi_horizon", 20)), 5, key="lunch_bi_horizon")\n',
    '    sig = (_lunch_df_signature(), int(rows_limit), int(horizon), "five_layer_powerbi_v1")\n',
    '    if run:\n',
    '        st.session_state["lunch_bi_visual_ready"] = True\n',
    '        with st.spinner("Calculating…"):\n',
    '            d = _clean_lunch_visual_df(limit=rows_limit)\n',
    '            if d is None or d.empty or len(d) < 30:\n',
    '                st.warning("Not enough clean EURUSD OHLC data. Connect/refresh data first.")\n',
    '                _render_lunch_copy_refresh_bar()\n',
    '                return\n',
    '            st.session_state["lunch_5layer_powerbi_df"] = d\n',
    '            st.session_state["lunch_5layer_powerbi_sig"] = sig\n',
    '            st.session_state["lunch_5layer_powerbi_result"] = _five_layer_powerbi_calculate(d, horizon=horizon)\n',
    '        st.success("Calculation complete. Cached dashboard will reopen instantly until you press Run Calculating again.")\n',
    '    if not st.session_state.get("lunch_bi_visual_ready", False):\n',
    '        st.info("Press **Run Calculating** to build the 5-layer dashboard. Changing tabs will not recalculate it.")\n',
    '        _render_lunch_copy_refresh_bar()\n',
    '        return\n',
    '    d = st.session_state.get("lunch_5layer_powerbi_df")\n',
    '    if d is None or getattr(d, "empty", True):\n',
    '        d = _clean_lunch_visual_df(limit=rows_limit)\n',
    '        st.session_state["lunch_5layer_powerbi_df"] = d\n',
    '    _render_lunch_advanced_powerbi_ml_projection(d, horizon=horizon)\n',
    '    _render_lunch_copy_refresh_bar()\n',
    '\n',
    'def _render_doo_prime_inner_tab():\n',
    '    import streamlit as st\n',
    '    from core.styles import request_close_sidebar\n',
    '    st.markdown("### 🏦 Doo Prime")\n',
    '    st.caption("Doo Prime Analysis is now inside this Doo Prime inner tab, not beside Lunch.")\n',
    '    choices = [("Overview", "🏦"), ("Analysis", "⚡")]\n',
    '    current = st.session_state.get("doo_prime_inner_tab", "Overview")\n',
    '    if current not in [x[0] for x in choices]:\n',
    '        current = "Overview"\n',
    '        st.session_state["doo_prime_inner_tab"] = current\n',
    '    cols = st.columns(len(choices))\n',
    '    for i, (name, icon) in enumerate(choices):\n',
    '        with cols[i]:\n',
    '            label = f"✅ {icon} {name}" if current == name else f"{icon} {name}"\n',
    '            if st.button(label, key=f"doo_prime_inner_{name}", use_container_width=True):\n',
    '                st.session_state["doo_prime_inner_tab"] = name\n',
    '                current = name\n',
    '                request_close_sidebar()\n',
    '    if st.session_state.get("doo_prime_inner_tab", current) == "Analysis":\n',
    '        _render_doo_prime_analysis_inner_tab()\n',
    '    else:\n',
    '        try:\n',
    '            from .home_split.legacy import implementation as impl\n',
    '            impl.doo_prime_panel()\n',
    '        except Exception as exc:\n',
    '            with st.expander("Show Doo Prime inner tab error", expanded=True):\n',
    '                st.exception(exc)\n',
    '\n',
    'def _render_doo_prime_analysis_inner_tab():\n',
    '    import streamlit as st\n',
    '    try:\n',
    '        from .home_split.legacy import implementation as impl\n',
    '        impl.doo_prime_deep_analysis_panel()\n',
    '    except Exception as exc:\n',
    '        with st.expander("Show Doo Prime Analysis error", expanded=True):\n',
    '            st.exception(exc)\n',
    '\n',
    '\n',
    'def _home_inner_selector():\n',
    '    import streamlit as st\n',
    '    from core.styles import request_close_sidebar\n',
    '    # V26: Metric + Home are one first inner tab, but their functions are still\n',
    '    # rendered separately. Nothing is mathematically mixed.\n',
    '    choices = [("Lunch", "🍱"), ("Data Visualization", "📊"), ("Doo Prime", "🏦")]\n',
    '    current = st.session_state.get("home_inner_tab", "Lunch")\n',
    '    if current in ("Home", "Launcher", "🏠 Launcher", "Metric", "Home Dashboard", "Metric + Home", "Doo Prime Analysis"):\n',
    '        current = "Lunch"\n',
    '        st.session_state.home_inner_tab = current\n',
    '    if current not in [x[0] for x in choices]:\n',
    '        current = "Lunch"\n',
    '        st.session_state.home_inner_tab = current\n',
    '    cols = st.columns(len(choices))\n',
    '    for idx, (name, icon) in enumerate(choices):\n',
    '        with cols[idx]:\n',
    '            label = f"✅ {icon} {name}" if current == name else f"{icon} {name}"\n',
    '            if st.button(label, key=f"home_inner_{name}", use_container_width=True):\n',
    '                st.session_state.home_inner_tab = name\n',
    '                current = name\n',
    '                request_close_sidebar()\n',
    '    return st.session_state.get("home_inner_tab", current)\n',
    '\n',
    '\n',
    'def _render_metric_home_combined_inner_tab():\n',
    '    import streamlit as st\n',
    '    st.caption("Lunch tab: Run Calculating first, then Metric table, 010 Reverse Decision, Prediction, Copy/Refresh, then other fields.")\n',
    '    _render_metric_inner_tab()\n',
    '    with st.expander("🏠 Open / Close — Other Lunch fields", expanded=False):\n',
    '        _render_home_dashboard()\n',
    '\n',
    '\n',
    'def show():\n',
    '    install_safe_dataframe_patch()\n',
    '    from core.styles import request_close_sidebar\n',
    '    request_close_sidebar()\n',
    '    # Header removed so the Home inner-tab choice buttons are the first visible controls.\n',
    '    selected = _home_inner_selector()\n',
    '    if selected == "Lunch":\n',
    '        _render_metric_home_combined_inner_tab()\n',
    '    elif selected == "Data Visualization":\n',
    '        request_close_sidebar()\n',
    '        _render_lunch_data_visualization_inner_tab()\n',
    '    else:\n',
    '        request_close_sidebar()\n',
    '        _render_doo_prime_inner_tab()\n',
    "    render_tab_footer('Lunch')\n",
    '\n',
    '\n',
    '# =====================================================================\n',
    '# 2026-06-09 ADDITIVE UPGRADE\n',
    '# Data Visualization Pro+: original dashboard kept, new PowerBI + ML +\n',
    '# long-horizon regime detector added without touching old source logic.\n',
    '# =====================================================================\n',
    '\n',
    'def _major_regime_detector_v20260609(d, min_days=3.0, lookback_days=120, horizon=20):\n',
    '    """Long-horizon market-regime detector.\n',
    '\n',
    '    This intentionally does NOT flag 6-hour / intraday noise as a regime change.\n',
    '    It is for strategy-fitness monitoring: how many days the current major regime\n',
    '    has existed, estimated days left, and whether the strategy may need review.\n',
    '    """\n',
    '    import pandas as pd\n',
    '    import numpy as np\n',
    '\n',
    '    if d is None or not isinstance(d, pd.DataFrame) or d.empty or "close" not in d.columns:\n',
    '        return {"ok": False, "message": "No clean OHLC data."}, pd.DataFrame(), pd.DataFrame()\n',
    '\n',
    '    x = d.copy()\n',
    '    if "time" not in x.columns:\n',
    '        x["time"] = pd.date_range(end=pd.Timestamp.now(), periods=len(x), freq="h")\n',
    '    x["time"] = pd.to_datetime(x["time"], errors="coerce")\n',
    '    for c in ["open", "high", "low", "close", "volume"]:\n',
    '        if c in x.columns:\n',
    '            x[c] = pd.to_numeric(x[c], errors="coerce")\n',
    '    if "open" not in x.columns:\n',
    '        x["open"] = x["close"].shift(1).fillna(x["close"])\n',
    '    x = x.dropna(subset=["time", "close"]).sort_values("time").drop_duplicates("time", keep="last").reset_index(drop=True)\n',
    '    if len(x) < 80:\n',
    '        return {"ok": False, "message": "Need at least 80 candles for major-regime analysis."}, pd.DataFrame(), pd.DataFrame()\n',
    '\n',
    '    # Keep enough history, but do not overload phone UI.\n',
    '    last_time = pd.Timestamp(x["time"].iloc[-1])\n',
    '    cutoff = last_time - pd.Timedelta(days=float(max(30, lookback_days)))\n',
    '    x = x[x["time"] >= cutoff].reset_index(drop=True)\n',
    '    if len(x) < 80:\n',
    '        x = d.copy().tail(1500).reset_index(drop=True)\n',
    '        x["time"] = pd.to_datetime(x["time"], errors="coerce")\n',
    '        x["close"] = pd.to_numeric(x["close"], errors="coerce")\n',
    '        if "open" not in x.columns:\n',
    '            x["open"] = x["close"].shift(1).fillna(x["close"])\n',
    '\n',
    '    close = x["close"].astype(float)\n',
    '    ret = close.pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    ema_fast = close.ewm(span=48, adjust=False, min_periods=8).mean()\n',
    '    ema_slow = close.ewm(span=240, adjust=False, min_periods=24).mean()\n',
    '    trend_gap = ((ema_fast - ema_slow) / close.replace(0, np.nan) * 100).replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    trend_slope = ema_slow.pct_change(48).replace([np.inf, -np.inf], np.nan).fillna(0.0) * 100\n',
    '    vol = ret.rolling(96, min_periods=24).std().fillna(ret.rolling(24, min_periods=6).std()).fillna(0.0) * 100\n',
    '    vol_med = vol.rolling(480, min_periods=80).median().fillna(vol.median())\n',
    '    vol_q75 = vol.rolling(480, min_periods=80).quantile(.75).fillna(vol.quantile(.75))\n',
    '    vol_q35 = vol.rolling(480, min_periods=80).quantile(.35).fillna(vol.quantile(.35))\n',
    '\n',
    '    # Major regime label: direction + environment, not small signal changes.\n',
    '    direction = np.where((trend_gap > 0.018) & (trend_slope >= -0.010), "BULL",\n',
    '                 np.where((trend_gap < -0.018) & (trend_slope <= 0.010), "BEAR", "RANGE"))\n',
    '    environment = np.where(vol >= vol_q75, "EXPANSION", np.where(vol <= vol_q35, "COMPRESSION", "NORMAL"))\n',
    '    raw = pd.Series(direction, index=x.index).astype(str) + "_" + pd.Series(environment, index=x.index).astype(str)\n',
    '\n',
    '    # Persistence filter: 2-day modal label. This is what stops 6-hour regime flips.\n',
    '    min_bars = max(24, int(round(float(min_days) * 24)))\n',
    '    smooth_window = max(24, min(min_bars, 120))\n',
    '    smooth = raw.rolling(smooth_window, min_periods=max(12, smooth_window // 3)).apply(lambda s: 0, raw=False) if False else raw.copy()\n',
    '    labels = raw.astype(str).tolist()\n',
    '    smoothed = []\n',
    '    for i in range(len(labels)):\n',
    '        w = labels[max(0, i - smooth_window + 1): i + 1]\n',
    '        vc = pd.Series(w, dtype="object").value_counts()\n',
    '        smoothed.append(str(vc.index[0]) if not vc.empty else labels[i])\n',
    '    x["Major Regime"] = pd.Series(smoothed, index=x.index, dtype="object")\n',
    '    x["Regime Score /10"] = (5 + trend_gap.abs() * 35 + vol * 12 + trend_slope.abs() * 18).clip(0, 10).round(2)\n',
    '\n',
    '    change_idx = x.index[x["Major Regime"].ne(x["Major Regime"].shift(1))].tolist() or [0]\n',
    '    # Merge any segment shorter than min_days into the previous segment.\n',
    '    changed = True\n',
    '    while changed and len(change_idx) > 1:\n',
    '        changed = False\n',
    '        keep = [change_idx[0]]\n',
    '        for i in range(1, len(change_idx)):\n',
    '            prev = keep[-1]\n',
    '            end_prev = change_idx[i] - 1\n',
    '            prev_days = max((pd.Timestamp(x.loc[end_prev, "time"]) - pd.Timestamp(x.loc[prev, "time"])).total_seconds() / 86400.0, 0.0)\n',
    '            if prev_days < float(min_days):\n',
    '                changed = True\n',
    '                continue\n',
    '            keep.append(change_idx[i])\n',
    '        change_idx = keep\n',
    '\n',
    '    rows = []\n',
    '    for i, idx in enumerate(change_idx):\n',
    '        end_idx = (change_idx[i + 1] - 1) if i + 1 < len(change_idx) else len(x) - 1\n',
    '        seg = x.loc[idx:end_idx]\n',
    '        if seg.empty:\n',
    '            continue\n',
    '        start = pd.Timestamp(seg["time"].iloc[0]); end = pd.Timestamp(seg["time"].iloc[-1])\n',
    '        dur = max((end - start).total_seconds() / 86400.0, 0.0)\n',
    '        rows.append({\n',
    '            "Regime Change Day": start.strftime("%Y-%m-%d"),\n',
    '            "Change Time": start.strftime("%Y-%m-%d %H:%M"),\n',
    '            "Major Regime": str(seg["Major Regime"].iloc[0]),\n',
    '            "Open": round(float(seg["open"].iloc[0]), 5),\n',
    '            "Close": round(float(seg["close"].iloc[-1]), 5),\n',
    '            "Bars": int(len(seg)),\n',
    '            "Days In Regime": round(float(dur), 2),\n',
    '            "Return %": round((float(seg["close"].iloc[-1]) / max(float(seg["open"].iloc[0]), 1e-12) - 1.0) * 100, 4),\n',
    '            "Avg Vol %": round(float(vol.loc[seg.index].mean()), 5),\n',
    '            "Avg Trend Gap %": round(float(trend_gap.loc[seg.index].mean()), 5),\n',
    '            "Regime Score /10": round(float(seg["Regime Score /10"].mean()), 2),\n',
    '        })\n',
    '    hist = pd.DataFrame(rows)\n',
    '    if hist.empty:\n',
    '        return {"ok": False, "message": "No major regime segments built."}, pd.DataFrame(), pd.DataFrame()\n',
    '\n',
    '    current = hist.iloc[-1].to_dict()\n',
    '    current_days = float(current.get("Days In Regime", 0.0))\n',
    '    completed = pd.to_numeric(hist["Days In Regime"], errors="coerce").iloc[:-1].dropna()\n',
    '    # Use robust median; floor at min_days so estimate does not become intraday.\n',
    '    expected_days = max(float(completed.median()) if len(completed) else float(min_days) * 2.0, float(min_days))\n',
    '    days_left = max(expected_days - current_days, 0.0)\n',
    '    next_time = pd.Timestamp(x["time"].iloc[-1]) + pd.Timedelta(days=days_left)\n',
    '\n',
    '    # Estimate open/close for next regime window using current drift + forecast horizon.\n',
    '    recent_drift = float(ret.tail(max(24, int(horizon))).mean())\n',
    '    recent_std = float(ret.tail(240).std()) if len(ret) >= 50 else float(ret.std())\n',
    '    forecast_days = max(days_left, float(horizon) / 24.0, 1.0)\n',
    '    last_close = float(close.iloc[-1])\n',
    '    est_open = last_close\n',
    '    est_close = last_close * (1.0 + max(-0.015, min(0.015, recent_drift * 24.0 * forecast_days)))\n',
    '    est_low = min(est_open, est_close) * (1 - max(recent_std * (forecast_days ** 0.5) * 8, 0.0005))\n',
    '    est_high = max(est_open, est_close) * (1 + max(recent_std * (forecast_days ** 0.5) * 8, 0.0005))\n',
    '\n',
    '    status = "STRATEGY OK"\n',
    '    note = "Major regime still inside normal life-span. No strategy change is required from regime age alone."\n',
    '    if current_days >= expected_days * 1.35:\n',
    '        status = "REVIEW STRATEGY"\n',
    '        note = "Current major regime is older than normal. Review strategy assumptions, risk, and exit logic."\n',
    '    elif days_left <= max(1.0, expected_days * 0.15):\n',
    '        status = "WATCH TRANSITION"\n',
    '        note = "Major regime is near its typical age limit. Prepare for possible transition; do not overfit short-term noise."\n',
    '\n',
    '    summary = {\n',
    '        "ok": True,\n',
    '        "current_regime": str(current.get("Major Regime", "UNKNOWN")),\n',
    '        "last_regime_change_day": str(current.get("Regime Change Day", "-")),\n',
    '        "last_regime_change_time": str(current.get("Change Time", "-")),\n',
    '        "days_since_last_change": round(current_days, 2),\n',
    '        "expected_regime_days": round(expected_days, 2),\n',
    '        "estimated_days_remaining": round(days_left, 2),\n',
    '        "estimated_next_change_day": next_time.strftime("%Y-%m-%d"),\n',
    '        "estimated_next_change_time": next_time.strftime("%Y-%m-%d %H:%M"),\n',
    '        "estimated_price_open": round(float(est_open), 5),\n',
    '        "estimated_price_close": round(float(est_close), 5),\n',
    '        "estimated_price_low": round(float(est_low), 5),\n',
    '        "estimated_price_high": round(float(est_high), 5),\n',
    '        "regime_score_10": round(float(current.get("Regime Score /10", 0.0)), 2),\n',
    '        "strategy_status": status,\n',
    '        "strategy_note": note,\n',
    '        "min_regime_days_filter": round(float(min_days), 2),\n',
    '        "history_rows": int(len(hist)),\n',
    '    }\n',
    '\n',
    '    forecast = pd.DataFrame([\n',
    '        {"Item": "Estimated Price Open", "Value": summary["estimated_price_open"]},\n',
    '        {"Item": "Estimated Price Close", "Value": summary["estimated_price_close"]},\n',
    '        {"Item": "Estimated Price Low", "Value": summary["estimated_price_low"]},\n',
    '        {"Item": "Estimated Price High", "Value": summary["estimated_price_high"]},\n',
    '        {"Item": "Estimated Next Major Regime Change", "Value": summary["estimated_next_change_time"]},\n',
    '        {"Item": "Strategy Status", "Value": summary["strategy_status"]},\n',
    '    ])\n',
    '    return summary, hist.sort_values("Change Time", ascending=False).head(80).reset_index(drop=True), forecast\n',
    '\n',
    '\n',
    'def _detect_lunch_regime_changes(d, horizon=24):\n',
    '    """Override old short-term detector with major-regime detector."""\n',
    '    summary, hist, _forecast = _major_regime_detector_v20260609(d, min_days=3.0, lookback_days=180, horizon=horizon)\n',
    '    return summary, hist\n',
    '\n',
    '\n',
    'def _five_layer_powerbi_calculate(d, horizon=20):\n',
    '    """Override wrapper so Layer 5 also uses the major-regime detector output."""\n',
    '    try:\n',
    '        result = _five_layer_powerbi_uncached(d, int(horizon), _lunch_df_signature())\n',
    '    except Exception:\n',
    '        result = {"ok": False, "message": "5-layer calculation failed."}\n',
    '    if isinstance(result, dict) and result.get("ok"):\n',
    '        try:\n',
    '            summary, hist, forecast = _major_regime_detector_v20260609(d, min_days=3.0, lookback_days=180, horizon=horizon)\n',
    '            if summary.get("ok"):\n',
    '                result["current_regime"] = summary["current_regime"]\n',
    '                result["last_regime_change"] = summary["last_regime_change_time"]\n',
    '                result["days_in_regime"] = summary["days_since_last_change"]\n',
    '                result["estimated_days_remaining"] = summary["estimated_days_remaining"]\n',
    '                result["predicted_next_regime_change"] = summary["estimated_next_change_time"]\n',
    '                result["estimated_price_open"] = summary["estimated_price_open"]\n',
    '                result["estimated_price_close"] = summary["estimated_price_close"]\n',
    '                result["estimated_price_low"] = summary["estimated_price_low"]\n',
    '                result["estimated_price_high"] = summary["estimated_price_high"]\n',
    '                result["strategy_status"] = summary["strategy_status"]\n',
    '                result["strategy_note"] = summary["strategy_note"]\n',
    '                result["history"] = hist\n',
    '                result["major_regime_summary"] = summary\n',
    '                result["major_regime_forecast"] = forecast\n',
    '        except Exception as exc:\n',
    '            result["major_regime_warning"] = str(exc)\n',
    '    return result\n',
    '\n',
    '\n',
    'def _apply_mobile_first_app_css_v20260609():\n',
    '    try:\n',
    '        import streamlit as st\n',
    '        st.markdown("""\n',
    '        <style>\n',
    '        @media (max-width: 780px){\n',
    '          .block-container{padding-top:.65rem!important;padding-left:.55rem!important;padding-right:.55rem!important;}\n',
    '          div[data-testid="stMetric"]{border-radius:18px;padding:10px 12px;background:rgba(255,255,255,.06);border:1px solid rgba(125,211,252,.22);box-shadow:0 8px 28px rgba(15,23,42,.10);}\n',
    '          div[data-testid="stDataFrame"]{border-radius:16px;overflow:hidden;}\n',
    '          .stButton>button{border-radius:999px!important;min-height:44px;font-weight:800!important;box-shadow:0 10px 24px rgba(14,165,233,.18);}\n',
    '          [data-testid="stHorizontalBlock"]{gap:.45rem;}\n',
    '        }\n',
    '        </style>\n',
    '        """, unsafe_allow_html=True)\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '\n',
    'def _render_lunch_data_visualization_inner_tab():\n',
    '    import streamlit as st\n',
    '    import pandas as pd\n',
    '\n',
    '    st.markdown("### 📊 Data Visualization Pro+")\n',
    '    st.caption("Original advanced PowerBI + ML stays here. New tabs add major-regime strategy age, estimated days left, and estimated price open/close.")\n',
    '\n',
    '    top = st.columns([1.05, .9, .9, .9])\n',
    '    with top[0]:\n',
    '        run = st.button("▶ Run Calculating", use_container_width=True, key="lunch_data_visual_run_calculating_v20260609")\n',
    '    with top[1]:\n',
    '        rows_limit = st.slider("Rows used", 1000, 3000, int(st.session_state.get("lunch_bi_rows_limit_v2", 2000)), 250, key="lunch_bi_rows_limit_v2")\n',
    '    with top[2]:\n',
    '        horizon = st.slider("Forecast candles", 5, 60, int(st.session_state.get("lunch_bi_horizon_v2", 20)), 5, key="lunch_bi_horizon_v2")\n',
    '    with top[3]:\n',
    '        min_days = st.slider("Major regime min days", 2, 14, int(st.session_state.get("major_regime_min_days", 3)), 1, key="major_regime_min_days")\n',
    '\n',
    '    sig = (_lunch_df_signature(), int(rows_limit), int(horizon), int(min_days), "dataviz_pro_plus_20260609")\n',
    '    if run or st.session_state.get("lunch_bi_visual_sig") != sig:\n',
    '        st.session_state["lunch_bi_visual_ready"] = True\n',
    '        with st.spinner("Calculating Data Visualization Pro+…"):\n',
    '            d = _clean_lunch_visual_df(limit=rows_limit)\n',
    '            if d is None or d.empty or len(d) < 80:\n',
    '                st.warning("Not enough clean EURUSD OHLC data. Connect/refresh data first.")\n',
    '                _render_lunch_copy_refresh_bar()\n',
    '                return\n',
    '            result = _five_layer_powerbi_calculate(d, horizon=horizon)\n',
    '            major_summary, major_hist, major_forecast = _major_regime_detector_v20260609(d, min_days=float(min_days), lookback_days=180, horizon=horizon)\n',
    '            st.session_state["lunch_5layer_powerbi_df"] = d\n',
    '            st.session_state["lunch_5layer_powerbi_result"] = result\n',
    '            st.session_state["lunch_major_regime_summary"] = major_summary\n',
    '            st.session_state["lunch_major_regime_history"] = major_hist\n',
    '            st.session_state["lunch_major_regime_forecast"] = major_forecast\n',
    '            st.session_state["lunch_bi_visual_sig"] = sig\n',
    '        st.success("Calculation complete. Original dashboard + new major-regime tabs are cached.")\n',
    '\n',
    '    if not st.session_state.get("lunch_bi_visual_ready", False):\n',
    '        st.info("Press **Run Calculating**. Nothing heavy runs until you press it.")\n',
    '        _render_lunch_copy_refresh_bar()\n',
    '        return\n',
    '\n',
    '    d = st.session_state.get("lunch_5layer_powerbi_df")\n',
    '    result = st.session_state.get("lunch_5layer_powerbi_result")\n',
    '    summary = st.session_state.get("lunch_major_regime_summary", {})\n',
    '    hist = st.session_state.get("lunch_major_regime_history", pd.DataFrame())\n',
    '    forecast = st.session_state.get("lunch_major_regime_forecast", pd.DataFrame())\n',
    '\n',
    '    tabs = st.tabs([\n',
    '        "Original Advanced PowerBI + ML",\n',
    '        "Major Regime Detector",\n',
    '        "Estimated Price Open / Close",\n',
    '        "ST Metric + History",\n',
    '        "Copy"\n',
    '    ])\n',
    '\n',
    '    with tabs[0]:\n',
    '        _render_lunch_advanced_powerbi_ml_projection(d, horizon=horizon)\n',
    '\n',
    '    with tabs[1]:\n',
    '        st.markdown("#### Long-horizon regime detection — not 6-hour noise")\n',
    '        if not isinstance(summary, dict) or not summary.get("ok"):\n',
    '            st.warning((summary or {}).get("message", "Major regime detector unavailable."))\n',
    '        else:\n',
    '            c = st.columns(6)\n',
    '            c[0].metric("Current Major Regime", summary["current_regime"])\n',
    '            c[1].metric("Started", summary["last_regime_change_day"])\n',
    '            c[2].metric("Days So Far", summary["days_since_last_change"])\n',
    '            c[3].metric("Expected Days", summary["expected_regime_days"])\n',
    '            c[4].metric("Estimated Days Left", summary["estimated_days_remaining"])\n',
    '            c[5].metric("Status", summary["strategy_status"])\n',
    '            st.info(summary["strategy_note"])\n',
]
