"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '            increasing={"line":{"color":"#38BDF8", "width":2}, "fillcolor":"rgba(56,189,248,0.35)"},\n',
    '            decreasing={"line":{"color":"#7DD3FC", "width":2}, "fillcolor":"rgba(125,211,252,0.25)"},\n',
    '        ), row=1, col=1)\n',
    '        fig.add_vrect(x0=x["time"].iloc[-1], x1=predicted["time"].iloc[-1], fillcolor="rgba(56,189,248,0.08)", line_width=0, row=1, col=1)\n',
    '    if isinstance(light_path, pd.DataFrame) and not light_path.empty:\n',
    '        fig.add_trace(go.Scatter(\n',
    '            x=light_path["time"], y=light_path["path_close"], mode="lines+markers", name="LIGHT BLUE current-hour predicted path",\n',
    '            line={"color":"#7DD3FC", "width":4}, marker={"size":5, "color":"#BAE6FD"}\n',
    '        ), row=1, col=1)\n',
    '    if isinstance(projection_history, pd.DataFrame) and not projection_history.empty:\n',
    '        ph = projection_history.sort_values("projected_time").tail(500)\n',
    '        fig.add_trace(go.Scatter(\n',
    '            x=ph["projected_time"], y=ph["Projected Close"], mode="markers", name="Last 10D rolling ML projections",\n',
    '            marker={"size":4, "color":"rgba(125,211,252,0.45)"}\n',
    '        ), row=1, col=1)\n',
    '    if isinstance(backtest_hist, pd.DataFrame) and not backtest_hist.empty:\n',
    '        bh = backtest_hist.sort_values("time").tail(240)\n',
    '        fig.add_trace(go.Bar(x=bh["time"], y=bh["Close Error %"], name="Close prediction error %"), row=2, col=1)\n',
    '    fig.update_layout(height=860, margin=dict(l=6, r=6, t=58, b=8), xaxis_rangeslider_visible=False, legend=dict(orientation="h"), title="Advanced Power BI Candle + ML Projection — newest/current first, last 10 continuous days")\n',
    '    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False, "responsive": True})\n',
    '\n',
    '\n',
    'def _apply_mobile_first_app_css_v20260609():\n',
    '    try:\n',
    '        import streamlit as st\n',
    '        st.markdown("""\n',
    '        <style>\n',
    '        @media (max-width: 780px){\n',
    '          .block-container{padding-top:.65rem!important;padding-left:.55rem!important;padding-right:.55rem!important;}\n',
    '          div[data-testid="stMetric"]{border-radius:18px;padding:10px 12px;background:rgba(255,255,255,.06);border:1px solid rgba(125,211,252,.22);box-shadow:0 8px 28px rgba(15,23,42,.10);}\n',
    '          div[data-testid="stDataFrame"]{border-radius:16px;overflow:hidden;}\n',
    '          .stButton>button{border-radius:999px!important;min-height:44px;font-weight:800!important;box-shadow:0 10px 24px rgba(14,165,233,.18);}\n',
    '          [data-testid="stHorizontalBlock"]{gap:.45rem;}\n',
    '        }\n',
    '        </style>\n',
    '        """, unsafe_allow_html=True)\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '\n',
    'def _render_lunch_data_visualization_inner_tab():\n',
    '    import streamlit as st\n',
    '    import pandas as pd\n',
    '    import json\n',
    '\n',
    '    _apply_mobile_first_app_css_v20260609()\n',
    '    st.markdown("### 📊 Data Visualization — Advanced Power BI Price Candlestick + ML Projection")\n',
    '    st.caption("Migrated view: one main candlestick + ML projection first; all other analytics are folded into open/close sections. Heavy calculation runs only after you press Run Candlestick.")\n',
    '\n',
    '    top = st.columns([1.15, .85, .85, .85, .85])\n',
    '    with top[0]:\n',
    '        run = st.button("▶ Run Candlestick + ML Projection", use_container_width=True, key="lunch_data_visual_run_candlestick_ml_20260609")\n',
    '    with top[1]:\n',
    '        rows_limit = st.slider("Rows used from Lunch/Data Visualization", 1000, 20000, int(st.session_state.get("dv_pp_rows", 10000)), 500, key="dv_pp_rows")\n',
    '    with top[2]:\n',
    '        horizon = st.slider("Predicted candles", 6, 96, int(st.session_state.get("dv_pp_horizon", 36)), 6, key="dv_pp_horizon")\n',
    '    with top[3]:\n',
    '        min_days = st.slider("Regime min days", 3, 21, int(st.session_state.get("dv_pp_min_days", 5)), 1, key="dv_pp_min_days")\n',
    '    with top[4]:\n',
    '        bt_lookback = st.slider("Backtest candles", 60, 500, int(st.session_state.get("dv_pp_bt", 180)), 20, key="dv_pp_bt")\n',
    '\n',
    '    sig = (_lunch_df_signature(), int(rows_limit), int(horizon), int(min_days), int(bt_lookback), "dv_adv_price_candlestick_ml_migrated_20260609")\n',
    '    if run:\n',
    '        st.session_state["lunch_bi_visual_ready"] = True\n',
    '        with st.spinner("Calculating Advanced Power BI Price Candlestick + ML Projection from Lunch/Data Visualization data…"):\n',
    '            d = _clean_lunch_visual_df(limit=int(rows_limit))\n',
    '            d = _dv_prepare_ohlc_v20260609(d, limit=int(rows_limit))\n',
    '            if d.empty or len(d) < 120:\n',
    '                st.warning("Not enough clean OHLC data. Refresh/connect EURUSD or selected symbol first. Need at least 120 candles.")\n',
    '                _render_lunch_copy_refresh_bar()\n',
    '                return\n',
    '            base_result = _five_layer_powerbi_calculate(d, horizon=int(horizon))\n',
    '            predicted = _dv_predict_future_candles_v20260609(d, horizon=int(horizon))\n',
    '            bt_hist, bt_summary = _dv_prediction_vs_actual_history_v20260609(d, lookback=int(bt_lookback), horizon=1)\n',
    '            projection_history = _dv_dynamic_projection_history_v20260609(d, lookback_days=10, horizon=min(6, int(horizon)))\n',
    '            regime_summary, regime_hist = _dv_major_regime_detector_v20260609(d, min_days=float(min_days), lookback_days=240, horizon=int(horizon))\n',
    '            st.session_state["dv_pp_df"] = d\n',
    '            st.session_state["dv_pp_base_result"] = base_result\n',
    '            st.session_state["dv_pp_predicted"] = predicted\n',
    '            st.session_state["dv_pp_lightblue_path"] = _dv_build_lightblue_path_v20260609(_dv_last_continuous_days_v20260609(d, days=10), predicted)\n',
    '            st.session_state["dv_pp_projection_history"] = projection_history\n',
    '            st.session_state["dv_pp_bt_hist"] = _dv_sort_newest_first_v20260609(bt_hist)\n',
    '            st.session_state["dv_pp_bt_summary"] = bt_summary\n',
    '            st.session_state["dv_pp_regime_summary"] = regime_summary\n',
    '            st.session_state["dv_pp_regime_hist"] = _dv_sort_newest_first_v20260609(regime_hist)\n',
    '            st.session_state["dv_pp_sig"] = sig\n',
    '        st.success("Candlestick + ML projection complete. Other analytics are available below in open/close sections.")\n',
    '\n',
    '    if not st.session_state.get("lunch_bi_visual_ready", False):\n',
    '        st.info("Press **Run Candlestick + ML Projection**. Nothing heavy runs automatically before that.")\n',
    '        _render_lunch_copy_refresh_bar()\n',
    '        return\n',
    '\n',
    '    d = st.session_state.get("dv_pp_df", pd.DataFrame())\n',
    '    result = st.session_state.get("dv_pp_base_result", {})\n',
    '    predicted = st.session_state.get("dv_pp_predicted", pd.DataFrame())\n',
    '    bt_hist = st.session_state.get("dv_pp_bt_hist", pd.DataFrame())\n',
    '    projection_history = st.session_state.get("dv_pp_projection_history", pd.DataFrame())\n',
    '    lightblue_path = st.session_state.get("dv_pp_lightblue_path", pd.DataFrame())\n',
    '    bt_summary = st.session_state.get("dv_pp_bt_summary", {})\n',
    '    regime_summary = st.session_state.get("dv_pp_regime_summary", {})\n',
    '    regime_hist = st.session_state.get("dv_pp_regime_hist", pd.DataFrame())\n',
    '\n',
    '    st.markdown("#### 🕯️ Advanced Power BI Price Candlestick + ML Projection")\n',
    '    st.caption("Main migrated section: actual candles, blue predicted future candles, current-hour light-blue path, and rolling ML projection history.")\n',
    '\n',
    '    with st.container():\n',
    '        c = st.columns(6)\n',
    '        if isinstance(result, dict) and result.get("ok"):\n',
    '            c[0].metric("Master Score", f"{result.get(\'master_score\', \'-\')}/10")\n',
    '            c[1].metric("Bull Probability", f"{result.get(\'bull_probability\', \'-\')}%")\n',
    '        if isinstance(regime_summary, dict) and regime_summary.get("ok"):\n',
    '            c[2].metric("Current Regime", regime_summary.get("current_regime", "-"))\n',
    '            c[3].metric("Days In Regime", regime_summary.get("days_since_last_change", regime_summary.get("days_since_change", "-")))\n',
    '            c[4].metric("Est. Days Left", regime_summary.get("estimated_days_remaining", regime_summary.get("estimated_days_left", "-")))\n',
    '            c[5].metric("Strategy", regime_summary.get("strategy_status", "-"))\n',
    '        _dv_render_candle_powerbi_chart_v20260609(d, predicted, bt_hist, projection_history)\n',
    '        if isinstance(lightblue_path, pd.DataFrame) and not lightblue_path.empty:\n',
    '            st.markdown("#### Light-blue predicted path from latest/current candle")\n',
    '            st.dataframe(_dv_sort_newest_first_v20260609(lightblue_path), use_container_width=True, hide_index=True, height=220)\n',
    '        if isinstance(predicted, pd.DataFrame) and not predicted.empty:\n',
    '            st.markdown("#### BLUE predicted future candle table")\n',
    '            st.dataframe(_dv_sort_newest_first_v20260609(predicted), use_container_width=True, hide_index=True, height=260)\n',
    '        if isinstance(projection_history, pd.DataFrame) and not projection_history.empty:\n',
    '            st.markdown("#### Last 10 continuous days — rolling ML projection history")\n',
    '            st.dataframe(_dv_sort_newest_first_v20260609(projection_history), use_container_width=True, hide_index=True, height=320)\n',
    '\n',
    '    with st.expander("Open / Close — Original PowerBI + ML Projection", expanded=False):\n',
    '        # Keep your existing advanced dashboard visible.\n',
    '        try:\n',
    '            st.session_state["lunch_5layer_powerbi_result"] = result\n',
    '            st.session_state["lunch_5layer_powerbi_df"] = d\n',
    '            _render_lunch_advanced_powerbi_ml_projection(d, horizon=int(horizon))\n',
    '        except Exception as exc:\n',
    '            st.warning(f"Original PowerBI + ML renderer could not display: {exc}")\n',
    '            if isinstance(result, dict):\n',
    '                st.json({k: str(v) for k, v in result.items() if k not in {"vote_df", "deep_df", "forecast_df", "history"}})\n',
    '\n',
    '    with st.expander("Open / Close — Prediction vs Actual", expanded=False):\n',
    '        st.markdown("#### How previous predicted candle compared with what actually happened")\n',
    '        if bt_summary:\n',
    '            b = st.columns(4)\n',
    '            b[0].metric("Tested Candles", bt_summary.get("tested_candles", 0))\n',
    '            b[1].metric("Direction Accuracy", f"{bt_summary.get(\'direction_accuracy_pct\', 0)}%")\n',
    '            b[2].metric("Avg Close Error", f"{bt_summary.get(\'avg_abs_close_error_pct\', 0)}%")\n',
    '            b[3].metric("Last Test", bt_summary.get("last_test_time", "-"))\n',
    '        if isinstance(bt_hist, pd.DataFrame) and not bt_hist.empty:\n',
    '            st.dataframe(_dv_sort_newest_first_v20260609(bt_hist), use_container_width=True, hide_index=True, height=420)\n',
    '        else:\n',
    '            st.info("Need more history for prediction-vs-actual testing.")\n',
    '\n',
    '    with st.expander("Open / Close — Smooth Regime", expanded=False):\n',
    '        st.markdown("#### Smooth major-regime detector — less noise, more reliable structure change")\n',
    '        if isinstance(regime_summary, dict) and regime_summary.get("ok"):\n',
    '            r = st.columns(6)\n',
    '            r[0].metric("Current Regime", regime_summary.get("current_regime", "-"))\n',
    '            r[1].metric("Started", regime_summary.get("last_regime_change", "-"))\n',
    '            r[2].metric("Days So Far", regime_summary.get("days_since_last_change", regime_summary.get("days_since_change", "-")))\n',
    '            r[3].metric("Expected Days", regime_summary.get("expected_days", "-"))\n',
    '            r[4].metric("Estimated Days Left", regime_summary.get("estimated_days_remaining", regime_summary.get("estimated_days_left", "-")))\n',
    '            r[5].metric("Power", f"{regime_summary.get(\'regime_power_100\', \'-\')}/100")\n',
    '            st.info(regime_summary.get("strategy_note", ""))\n',
    '            st.caption(f"Noise filter: a regime must persist around {regime_summary.get(\'min_days_filter\', min_days)} days before it counts as a major structure change.")\n',
    '            st.dataframe(_dv_sort_newest_first_v20260609(regime_hist), use_container_width=True, hide_index=True, height=420)\n',
    '        else:\n',
    '            st.warning((regime_summary or {}).get("message", "Smooth regime detector unavailable."))\n',
    '\n',
    '    with st.expander("Open / Close — Copy Export", expanded=False):\n',
    '        payload = {\n',
    '            "smooth_regime_summary": regime_summary,\n',
    '            "prediction_backtest_summary": bt_summary,\n',
    '            "light_blue_current_hour_path": lightblue_path.to_dict("records") if isinstance(lightblue_path, pd.DataFrame) else [],\n',
    '            "last_10_continuous_days_dynamic_projection_history": projection_history.to_dict("records") if isinstance(projection_history, pd.DataFrame) else [],\n',
    '            "future_blue_predicted_candles": _dv_sort_newest_first_v20260609(predicted).to_dict("records") if isinstance(predicted, pd.DataFrame) else [],\n',
    '            "advanced_powerbi_ml_summary": {k: v for k, v in (result or {}).items() if k not in {"vote_df", "deep_df", "forecast_df", "history"}},\n',
    '        }\n',
    '        st.session_state["lunch_visualization_export"] = json.dumps(payload, indent=2, default=str)\n',
    '        try:\n',
    '            from core.pro_terminal_uiux import render_mobile_copy_button\n',
    '            render_mobile_copy_button("Copy Data Visualization Pro++", st.session_state["lunch_visualization_export"], "copy_dv_propp_candle_20260609")\n',
    '        except Exception:\n',
    '            st.json(payload)\n',
    '\n',
    '    _render_lunch_copy_refresh_bar()\n',
    '\n',
    '\n',
]
