"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Dinner/Morning display reorganization patch (2026-06-14).\n',
    '\n',
    'Display-only, non-destructive final wrapper:\n',
    '- Regime inner tab label becomes Dinner.\n',
    '- Doo Prime inner tab label becomes Morning.\n',
    '- Master Decision + Reliability + Priority Center and Final Synced Intelligence\n',
    '  are displayed inside Dinner under run-gated inner tabs.\n',
    '- AI Assistant is rendered inside Dinner with a ChatGPT-like local-only layout.\n',
    '- Data Analysis gets a current descriptive/predictive/prescriptive result table.\n',
    '- Lunch gets a red prediction-line warning/display layer using existing cached\n',
    '  projection and actual/error metrics only.\n',
    '\n',
    'No new prediction engine, no external API, no heavy neural network.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import json\n',
    'import math\n',
    'import re\n',
    'import time\n',
    'from typing import Any, Dict, Iterable, List, Optional\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    'import streamlit as st\n',
    '\n',
    'UNIQUE = "20260614_dinner_morning_data_final"\n',
    '\n',
    '\n',
    'def _num(v: Any, default: float = 0.0) -> float:\n',
    '    try:\n',
    '        if v is None or v == "":\n',
    '            return float(default)\n',
    '        if isinstance(v, str):\n',
    '            m = re.search(r"-?\\d+(?:\\.\\d+)?", v.replace(",", "").replace("%", ""))\n',
    '            v = m.group(0) if m else default\n',
    '        x = float(v)\n',
    '        return x if math.isfinite(x) else float(default)\n',
    '    except Exception:\n',
    '        return float(default)\n',
    '\n',
    '\n',
    'def _clip(v: Any, lo: float = 0.0, hi: float = 100.0) -> float:\n',
    '    return float(max(lo, min(hi, _num(v, lo))))\n',
    '\n',
    '\n',
    'def _fmt(v: Any, suffix: str = "") -> str:\n',
    '    try:\n',
    '        x = float(v)\n',
    '        if not math.isfinite(x):\n',
    '            return str(v)\n',
    '        if suffix == "%":\n',
    '            return f"{x:.1f}%"\n',
    '        if abs(x) >= 100:\n',
    '            return f"{x:.0f}{suffix}"\n',
    '        return f"{x:.2f}{suffix}"\n',
    '    except Exception:\n',
    '        return str(v)\n',
    '\n',
    '\n',
    'def _fmt_time(v: Any, default: str = "Not recorded") -> str:\n',
    '    try:\n',
    '        if v is None or pd.isna(v):\n',
    '            return default\n',
    '        return pd.Timestamp(v).strftime("%Y-%m-%d %H:%M")\n',
    '    except Exception:\n',
    '        text = str(v or "").strip()\n',
    '        return text or default\n',
    '\n',
    '\n',
    'def _norm(s: Any) -> str:\n',
    '    return re.sub(r"[^a-z0-9]+", "", str(s).lower())\n',
    '\n',
    '\n',
    'def _safe_json(obj: Any, rows: int = 120) -> str:\n',
    '    def conv(x: Any) -> Any:\n',
    '        if isinstance(x, pd.DataFrame):\n',
    '            return x.head(rows).to_dict("records")\n',
    '        if isinstance(x, pd.Series):\n',
    '            return x.head(rows).to_dict()\n',
    '        if isinstance(x, (pd.Timestamp, np.datetime64)):\n',
    '            return str(x)\n',
    '        if isinstance(x, dict):\n',
    '            return {str(k): conv(v) for k, v in x.items() if not str(k).startswith("_")}\n',
    '        if isinstance(x, (list, tuple)):\n',
    '            return [conv(v) for v in list(x)[:rows]]\n',
    '        if isinstance(x, (np.integer,)):\n',
    '            return int(x)\n',
    '        if isinstance(x, (np.floating,)):\n',
    '            y = float(x)\n',
    '            return y if math.isfinite(y) else None\n',
    '        return x\n',
    '    return json.dumps(conv(obj), indent=2, ensure_ascii=False, default=str)\n',
    '\n',
    '\n',
    'def _copy_button(label: str, text: str, key: str) -> None:\n',
    '    try:\n',
    '        from streamlit_copy_button import copy_button\n',
    '        copy_button(str(text), label, key=key)\n',
    '    except Exception:\n',
    '        try:\n',
    '            from core.pro_terminal_uiux import render_mobile_copy_button\n',
    '            render_mobile_copy_button(label, str(text), key)\n',
    '        except Exception:\n',
    '            st.text_area(label, str(text), height=180, key=key + "_fallback")\n',
    '\n',
    '\n',
    'def _find_col(df: pd.DataFrame, aliases: Iterable[str]) -> Optional[str]:\n',
    '    if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '        return None\n',
    '    nmap = {_norm(c): c for c in df.columns}\n',
    '    for a in aliases:\n',
    '        na = _norm(a)\n',
    '        if na in nmap:\n',
    '            return nmap[na]\n',
    '    for nk, col in nmap.items():\n',
    '        for a in aliases:\n',
    '            na = _norm(a)\n',
    '            if na and na in nk:\n',
    '                return col\n',
    '    return None\n',
    '\n',
    '\n',
    'def _market_df(limit: int = 7000) -> pd.DataFrame:\n',
    '    for key in ["dv_pp_df", "last_df", "lunch_visual_df", "home_df", "custom_h1_df", "full_metric_history_df"]:\n',
    '        obj = st.session_state.get(key)\n',
    '        if isinstance(obj, pd.DataFrame) and not obj.empty:\n',
    '            d = obj.copy().tail(int(limit)).reset_index(drop=True)\n',
    '            break\n',
    '    else:\n',
    '        return pd.DataFrame()\n',
    '    low = {_norm(c): c for c in d.columns}\n',
    '    ren = {}\n',
    '    for src, dst in {"datetime": "time", "timestamp": "time", "date": "time", "o": "open", "h": "high", "l": "low", "c": "close"}.items():\n',
    '        if src in low and dst not in d.columns:\n',
    '            ren[low[src]] = dst\n',
    '    if ren:\n',
    '        d = d.rename(columns=ren)\n',
    '    if "time" not in d.columns:\n',
    '        # Operational analysis must not manufacture H1 timestamps. A not-ready\n',
    '        # result is safer than a synthetic row that could become a decision.\n',
    '        return pd.DataFrame()\n',
    '    d["time"] = pd.to_datetime(d["time"], errors="coerce")\n',
    '    for col in ["open", "high", "low", "close"]:\n',
    '        if col not in d.columns:\n',
    '            d[col] = d.get("close", np.nan)\n',
    '        d[col] = pd.to_numeric(d[col], errors="coerce")\n',
    '    return d.dropna(subset=["time", "close"]).sort_values("time").drop_duplicates("time", keep="last").reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _direction_from_regime(regime: Any) -> str:\n',
    '    s = str(regime or "").upper()\n',
    '    if "BULL" in s or s == "BUY":\n',
    '        return "BUY"\n',
    '    if "BEAR" in s or s == "SELL":\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _regime_score(regime: Any) -> float:\n',
    '    s = str(regime or "").upper()\n',
    '    if "BULL" in s or s == "BUY":\n',
    '        return 1.0\n',
    '    if "BEAR" in s or s == "SELL":\n',
    '        return -1.0\n',
    '    if "COMPRESSION" in s:\n',
    '        return 0.25\n',
    '    return 0.0\n',
    '\n',
    '\n',
    'def _ctx(ns: dict, force: bool = False) -> Dict[str, Any]:\n',
    '    builder = ns.get("build_reliability_control_center_20260614")\n',
    '    if callable(builder) and (force or bool(st.session_state.get("metric_run_calculate", False))):\n',
    '        try:\n',
    '            return builder(force=force) or {}\n',
    '        except TypeError:\n',
    '            try:\n',
    '                return builder(force) or {}\n',
    '            except Exception:\n',
    '                pass\n',
    '        except Exception:\n',
    '            pass\n',
    '    obj = st.session_state.get("reliability_control_center_20260614")\n',
    '    return obj if isinstance(obj, dict) else {}\n',
    '\n',
    '\n',
    'def _rctx(ns: dict, force: bool = False) -> Dict[str, Any]:\n',
    '    builder = ns.get("build_regime_context_20260614")\n',
    '    if callable(builder) and (force or bool(st.session_state.get("metric_run_calculate", False)) or isinstance(st.session_state.get("regime_context_20260614"), dict)):\n',
    '        try:\n',
    '            return builder(force=force) or {}\n',
    '        except TypeError:\n',
    '            try:\n',
    '                return builder(force) or {}\n',
    '            except Exception:\n',
    '                pass\n',
    '        except Exception:\n',
    '            pass\n',
    '    obj = st.session_state.get("regime_context_20260614")\n',
    '    return obj if isinstance(obj, dict) else {}\n',
    '\n',
    '\n',
    'def _regime_metrics(ns: dict) -> Dict[str, Any]:\n',
    '    r = _rctx(ns, False)\n',
    '    m = r.get("metrics", {}) if isinstance(r, dict) else {}\n',
    '    return m if isinstance(m, dict) else {}\n',
    '\n',
    '\n',
    'def _priority_table_from_state(ctx: Dict[str, Any]) -> pd.DataFrame:\n',
    '    # Every priority display is a subset of the one Full Metric-ranked table.\n',
    '    canonical = st.session_state.get("canonical_priority_table_20260617")\n',
    '    if isinstance(canonical, pd.DataFrame) and not canonical.empty:\n',
    '        return canonical\n',
    '    for key in ["three_center_priority_sorted_20260614", "reliability_dynamic_priority_table_20260614"]:\n',
    '        obj = st.session_state.get(key)\n',
    '        if isinstance(obj, pd.DataFrame) and not obj.empty:\n',
    '            return obj.copy()\n',
    '    if isinstance(ctx, dict):\n',
    '        rec = ctx.get("priority_table_preview", [])\n',
    '        if rec:\n',
    '            try:\n',
    '                return pd.DataFrame(rec)\n',
    '            except Exception:\n',
    '                pass\n',
    '    pack = st.session_state.get("final_synced_research_merge_pack_20260612") or st.session_state.get("final_merged_intelligence_pack_20260612")\n',
    '    if isinstance(pack, dict):\n',
    '        obj = pack.get("priority_1_to_14")\n',
    '        if not isinstance(obj, pd.DataFrame) or obj.empty:\n',
    '            obj = pack.get("knn_greedy_priority")\n',
    '        if isinstance(obj, pd.DataFrame) and not obj.empty:\n',
    '            return obj.copy()\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _analysis_result_dataframe(ns: Optional[dict] = None) -> pd.DataFrame:\n',
    '    ns = ns or {}\n',
    '    d = _market_df(3000)\n',
    '    ctx = _ctx(ns, False) if ns else {}\n',
    '    rctx = _rctx(ns, False) if ns else {}\n',
    '    m = rctx.get("metrics", {}) if isinstance(rctx, dict) else {}\n',
    '    summary = ctx.get("summary", {}) if isinstance(ctx, dict) else {}\n',
    '    quality = ctx.get("data_quality_market_feed_health", {}) if isinstance(ctx, dict) else {}\n',
    '    fresh = ctx.get("model_decay_forecast_freshness", {}) if isinstance(ctx, dict) else {}\n',
    '    pack = st.session_state.get("final_synced_research_merge_pack_20260612") or st.session_state.get("final_merged_intelligence_pack_20260612")\n',
    '    pred_dir = "WAIT"\n',
    '    pred_conf = fresh.get("Prediction Freshness", fresh.get("Decayed Confidence Score", 0)) if isinstance(fresh, dict) else 0\n',
    '    if isinstance(pack, dict) and pack:\n',
    '        pred_dir = str(pack.get("master_direction", pack.get("prediction_direction", pred_dir)))\n',
    '        pred_conf = pack.get("projection_confidence", pred_conf)\n',
    '    if pred_dir == "WAIT":\n',
    '        pred = st.session_state.get("dv_pp_predicted", pd.DataFrame())\n',
    '        if isinstance(pred, pd.DataFrame) and not pred.empty and not d.empty:\n',
    '            ccol = _find_col(pred, ["Accuracy Adjusted Price", "Predicted Close", "Projected Close", "close"])\n',
    '            if ccol:\n',
    '                y = pd.to_numeric(pred[ccol], errors="coerce").dropna()\n',
    '                if not y.empty:\n',
    '                    last_close = float(d["close"].iloc[-1])\n',
    '                    pred_dir = "BUY" if float(y.iloc[-1]) > last_close else "SELL" if float(y.iloc[-1]) < last_close else "WAIT"\n',
    '    regime = m.get("Current Regime", st.session_state.get("current_regime", "-"))\n',
    '    regime_dir = m.get("Regime Direction", _direction_from_regime(regime))\n',
    '    reliability = _num(m.get("Regime Reliable Score", summary.get("Forecast Robustness Score", 0)), 0)\n',
    '    shift = _num(m.get("Transition Risk %", 0), 0)\n',
    '    data_score = _num(quality.get("Data Quality Score", 0), 0) if isinstance(quality, dict) else 0\n',
    '    last_close = round(float(d["close"].iloc[-1]), 5) if not d.empty else "-"\n',
    '    rows = [\n',
    '        {\n',
    '            "Analysis Type": "Descriptive Analysis",\n',
    '            "Current Market/System Status": f"Last close {last_close}; current regime {regime}; data quality {_fmt(data_score, \'%\')}",\n',
    '            "System Reading": f"Regime direction {regime_dir}; shift risk {_fmt(shift, \'%\')}",\n',
    '            "Reliability / Score": _fmt(reliability, "%"),\n',
    '            "Action Use": "Read market condition only; do not enter from descriptive data alone.",\n',
    '        },\n',
    '        {\n',
    '            "Analysis Type": "Predictive Analysis",\n',
    '            "Current Market/System Status": f"Existing forecast direction {pred_dir}; regime forecast {m.get(\'Regime Forecast\', \'-\')}",\n',
    '            "System Reading": str(m.get("Regime Prediction", f"{pred_dir} prediction vs {regime_dir} regime")),\n',
    '            "Reliability / Score": _fmt(pred_conf if _num(pred_conf, 0) else reliability, "%"),\n',
    '            "Action Use": "Use existing forecast/error metrics only; confirm with priority and risk before action.",\n',
    '        },\n',
    '        {\n',
    '            "Analysis Type": "Prescriptive Analysis",\n',
    '            "Current Market/System Status": "Decision rule combines regime, priority, reliability, exit risk, and shift risk.",\n',
    '            "System Reading": "FOLLOW bias" if reliability >= 70 and shift < 50 and regime_dir in {"BUY", "SELL"} else "WAIT / reduce size / avoid" if reliability < 60 or shift >= 55 else "Small size only after confirmation",\n',
    '            "Reliability / Score": _fmt(max(0.0, min(100.0, reliability - max(0.0, shift - 45) * 0.6)), "%"),\n',
    '            "Action Use": "Prescriptive result for current system status; it does not replace your original calculations.",\n',
    '        },\n',
    '    ]\n',
    '    return pd.DataFrame(rows)\n',
    '\n',
    '\n',
    'def render_data_analysis_result_table_20260614(source: str = "research") -> None:\n',
    '    """Public helper imported by Research/Data Analysis renderers."""\n',
    '    with st.expander("📊 Open / Close — Current Result Table: Descriptive + Predictive + Prescriptive + Diagnostic", expanded=True):\n',
    '        st.caption("Uses current existing session data only. No API, no new model, no duplicate heavy calculation.")\n',
    '        st.dataframe(_analysis_result_dataframe({}), use_container_width=True, hide_index=True, height=190)\n',
    '        try:\n',
    '            from core.advanced_analytics_20260615 import build_diagnostic_analysis_table, build_sampling_estimating_hypothesis_tables, build_data_mining_extension_tables\n',
    '            st.markdown("##### Diagnostic Analysis")\n',
    '            st.dataframe(build_diagnostic_analysis_table(), use_container_width=True, hide_index=True, height=260)\n',
    '            stats = build_sampling_estimating_hypothesis_tables()\n',
    '            cube = build_data_mining_extension_tables().get("cube")\n',
    '            st.markdown("##### Sampling / Estimating / Hypothesis Testing / 3D Data Cube")\n',
    '            sub = st.tabs(["Sampling", "Estimating", "Hypothesis", "3D Data Cube"] )\n',
    '            with sub[0]:\n',
    '                st.dataframe(stats.get("sampling"), use_container_width=True, hide_index=True, height=220)\n',
    '            with sub[1]:\n',
    '                st.dataframe(stats.get("estimating"), use_container_width=True, hide_index=True, height=200)\n',
    '            with sub[2]:\n',
    '                st.dataframe(stats.get("hypothesis"), use_container_width=True, hide_index=True, height=220)\n',
    '            with sub[3]:\n',
    '                st.dataframe(cube, use_container_width=True, hide_index=True, height=300)\n',
    '        except Exception as exc:\n',
    '            st.caption(f"Diagnostic analysis skipped safely: {exc}")\n',
    '\n',
    '\n',
    'def _regime_projection_source(ns: dict) -> pd.DataFrame:\n',
    '    r = _rctx(ns, False)\n',
    '    hist = r.get("history", pd.DataFrame()) if isinstance(r, dict) else pd.DataFrame()\n',
    '    m = r.get("metrics", {}) if isinstance(r, dict) else {}\n',
    '    rows: List[Dict[str, Any]] = []\n',
    '    if isinstance(hist, pd.DataFrame) and not hist.empty:\n',
    '        work = hist.copy().tail(48)\n',
    '        tcol = _find_col(work, ["End", "End Time", "time", "Datetime", "Date", "Start"])\n',
    '        rcol = _find_col(work, ["Regime", "Major Regime", "Current Regime", "H1 Regime"])\n',
    '        conf_col = _find_col(work, ["Avg Confidence", "Regime Confidence", "Confidence"])\n',
    '        rel_col = _find_col(work, ["Avg Reliability", "Regime Reliability", "Reliability"])\n',
    '        shift_col = _find_col(work, ["Shift Risk", "Transition Risk"])\n',
    '        if tcol and rcol:\n',
    '            for _, row in work.iterrows():\n',
    '                rows.append({\n',
    '                    "time": pd.to_datetime(row.get(tcol), errors="coerce"),\n',
    '                    "regime": row.get(rcol),\n',
    '                    "path": _regime_score(row.get(rcol)),\n',
    '                    "confidence": _clip(row.get(conf_col) if conf_col else m.get("Regime Confidence %", 55), 0, 100),\n',
    '                    "reliability": _clip(row.get(rel_col) if rel_col else m.get("Regime Reliable Score", 55), 0, 100),\n',
    '                    "shift_risk": _clip(row.get(shift_col) if shift_col else m.get("Transition Risk %", 45), 0, 100),\n',
    '                })\n',
    '    if not rows:\n',
    '        d = _market_df(500)\n',
    '        if not d.empty:\n',
    '            c = d["close"].astype(float)\n',
    '            ma12 = c.rolling(12, min_periods=3).mean()\n',
    '            ma48 = c.rolling(48, min_periods=10).mean()\n',
    '            reg = np.where(ma12 > ma48, "BULL_DERIVED", np.where(ma12 < ma48, "BEAR_DERIVED", "RANGE_DERIVED"))\n',
    '            tail = d.tail(90).copy()\n',
    '            for i, (_, row) in enumerate(tail.iterrows()):\n',
    '                rr = reg[row.name] if row.name < len(reg) else "RANGE_DERIVED"\n',
    '                rows.append({\n',
    '                    "time": row["time"],\n',
    '                    "regime": rr,\n',
    '                    "path": _regime_score(rr),\n',
    '                    "confidence": _clip(m.get("Regime Confidence %", 55), 0, 100),\n',
    '                    "reliability": _clip(m.get("Regime Reliable Score", 55), 0, 100),\n',
    '                    "shift_risk": _clip(m.get("Transition Risk %", 45), 0, 100),\n',
    '                })\n',
    '    out = pd.DataFrame(rows)\n',
    '    if out.empty:\n',
    '        return out\n',
    '    out = out.dropna(subset=["time"]).sort_values("time").reset_index(drop=True)\n',
    '    out["previous_path"] = out["path"].shift(1)\n',
    '    return out\n',
    '\n',
    '\n',
    'def _render_powerbi_regime_projection(ns: dict) -> None:\n',
    '    st.markdown("#### 📈 PowerBI Regime Projection")\n',
    '    try:\n',
    '        from core.regime_sync_20260617 import canonical_regime_snapshot\n',
    '        _snap = canonical_regime_snapshot(days=25)\n',
    '        _mc = st.columns(4)\n',
    '        _mc[0].metric("Current Regime", _snap.get("regime", "-"), _snap.get("regime_validation", "FALSE / WATCH"))\n',
    '        _mc[1].metric("Regime Start", _fmt_time(_snap.get("regime_start")))\n',
    '        _mc[2].metric("Regime End", _snap.get("regime_end_display", "OPEN / CURRENT"))\n',
    '        _err = _snap.get("avg_error_pct")\n',
    '        _err_text = f"{float(_err):.5f}%" if _err is not None else "N/A"\n',
    '        _err_kind = "proxy" if _snap.get("error_is_proxy") else "actual"\n',
    '        _mc[3].metric("Avg Error (Proxy)" if _snap.get("error_is_proxy") else "Avg Error", _err_text, f"{int(_snap.get(\'error_samples\',0))} samples • {_err_kind}" if _err is not None else "Run prediction-vs-actual backtest")\n',
    '    except Exception:\n',
    '        pass\n',
    '    st.caption("Current regime path, previous regime path, expected next regime path, confidence/reliability line, and shift-risk band. Existing regime/history/forecast calculations only.")\n',
    '    c1, c2 = st.columns([1.0, 2.2])\n',
    '    horizon = c1.slider("Expected path H1", 6, 24, 12, 6, key=f"regime_projection_horizon_{UNIQUE}")\n',
    '    c2.caption("Auto-loaded from the Settings-published generation. Display-only projection transform; no inner Run button or new prediction engine.")\n',
    '    try:\n',
    '        from core.advanced_analytics_20260615 import render_regime_alpha_delta_metrics\n',
    '        render_regime_alpha_delta_metrics(ns, key="powerbi_regime_projection")\n',
    '    except Exception as exc:\n',
    '        st.caption(f"Regime Alpha/Delta skipped safely: {exc}")\n',
    '    if not bool(st.session_state.get("metric_run_calculate", False)) and not isinstance(st.session_state.get("regime_context_20260614"), dict):\n',
    '        try:\n',
    '            from core.system_wide_completion_20260618 import readiness_message\n',
    '            st.info(readiness_message(st.session_state, "Regime History"))\n',
    '        except Exception:\n',
    '            st.info("The published regime projection is unavailable. Open Settings → Errors / Fix Fast.")\n',
    '        return\n',
    '    src = _regime_projection_source(ns)\n',
    '    if src.empty:\n',
    '        try:\n',
    '            from core.system_wide_completion_20260618 import readiness_message\n',
    '            st.info(readiness_message(st.session_state, "Regime History"))\n',
    '        except Exception:\n',
    '            st.info("No published regime history is available. Open Settings → Errors / Fix Fast.")\n',
    '        return\n',
    '    m = _regime_metrics(ns)\n',
    '    last_t = pd.to_datetime(src["time"].iloc[-1], errors="coerce")\n',
    '    if pd.isna(last_t):\n',
    '        last_t = pd.Timestamp.now().floor("h")\n',
    '    forecast_dir = str(m.get("Forecast Direction", "WAIT"))\n',
    '    next_regime = m.get("Regime Forecast") or m.get("Regime Prediction") or forecast_dir\n',
    '    next_score = _regime_score(forecast_dir if forecast_dir in {"BUY", "SELL", "WAIT"} else next_regime)\n',
    '    if next_score == 0:\n',
    '        next_score = float(src["path"].iloc[-1])\n',
    '    shift = _clip(m.get("Transition Risk %", src["shift_risk"].tail(1).iloc[0] if "shift_risk" in src else 45), 0, 100)\n',
    '    future = pd.DataFrame({\n',
    '        "time": [last_t + pd.Timedelta(hours=i) for i in range(1, int(horizon) + 1)],\n',
    '        "expected_path": [next_score for _ in range(int(horizon))],\n',
    '        "upper_band": [min(1.4, next_score + shift / 100.0) for _ in range(int(horizon))],\n',
    '        "lower_band": [max(-1.4, next_score - shift / 100.0) for _ in range(int(horizon))],\n',
    '        "confidence": [_clip(m.get("Regime Confidence %", src["confidence"].tail(1).iloc[0]), 0, 100) for _ in range(int(horizon))],\n',
    '        "reliability": [_clip(m.get("Regime Reliable Score", src["reliability"].tail(1).iloc[0]), 0, 100) for _ in range(int(horizon))],\n',
    '        "shift_risk": [shift for _ in range(int(horizon))],\n',
]
