"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        try:\n',
    '            st.rerun()\n',
    '        except Exception:\n',
    '            pass\n',
    '    return selected\n',
    '\n',
    'def install(ns: dict) -> None:\n',
    '    if ns.get("_dinner_morning_data_patch_installed_20260614"):\n',
    '        return\n',
    '    prev_data = ns.get("_render_lunch_data_visualization_inner_tab")\n',
    '    prev_research = ns.get("_render_home_research_inner_20260612")\n',
    '    prev_morning = ns.get("_render_doo_prime_inner_tab")\n',
    '    footer = ns.get("render_tab_footer")\n',
    '    prev_full_copy = ns.get("_build_lunch_all_copy_text")\n',
    '    prev_short_copy = ns.get("_build_short_necessary_copy_text")\n',
    '\n',
    '    def _full_copy_with_dinner() -> str:\n',
    '        base = prev_full_copy() if callable(prev_full_copy) else ""\n',
    '        payload = {\n',
    '            "Dinner Regime Metrics": _regime_metrics(ns),\n',
    '            "Data Analysis Current Result Table": _analysis_result_dataframe(ns),\n',
    '            "AI Assistant Last Answer": st.session_state.get("ai_lite_last_answer_summary_20260614", "No AI answer yet."),\n',
    '        }\n',
    '        return str(base) + "\\n\\nDINNER / MORNING / DATA ANALYSIS DISPLAY PATCH 20260614\\n" + "=" * 78 + "\\n" + _safe_json(payload)\n',
    '\n',
    '    def _short_copy_with_dinner() -> str:\n',
    '        base = prev_short_copy() if callable(prev_short_copy) else ""\n',
    '        table = _analysis_result_dataframe(ns)\n',
    '        return str(base) + "\\n\\nDINNER CURRENT ANALYSIS TABLE\\n" + table.to_string(index=False)\n',
    '\n',
    '    if callable(prev_full_copy):\n',
    '        ns["_build_lunch_all_copy_text"] = _full_copy_with_dinner\n',
    '    if callable(prev_short_copy):\n',
    '        ns["_build_short_necessary_copy_text"] = _short_copy_with_dinner\n',
    '\n',
    '    def _show_final_reorganized() -> None:\n',
    '        try:\n',
    '            from core.streamlit_safe_dataframe import install_safe_dataframe_patch\n',
    '            install_safe_dataframe_patch()\n',
    '        except Exception:\n',
    '            pass\n',
    '        try:\n',
    '            from core.styles import request_close_sidebar\n',
    '            request_close_sidebar()\n',
    '        except Exception:\n',
    '            pass\n',
    '        selected = _selector()\n',
    '        if selected == "Lunch":\n',
    '            _render_lunch_reorganized(ns)\n',
    '        elif selected == "Dinner":\n',
    '            _render_dinner(ns, prev_data)\n',
    '        elif selected == "Research":\n',
    '            if callable(prev_research):\n',
    '                prev_research()\n',
    '            else:\n',
    '                try:\n',
    '                    import tabs.research as research\n',
    '                    research.show()\n',
    '                except Exception as exc:\n',
    '                    st.error("Research / Data Analysis could not load safely.")\n',
    '                    st.exception(exc)\n',
    '        elif selected == "Morning":\n',
    '            st.markdown("### 🌅 Morning — Doo Prime")\n',
    '            st.caption("Former Doo Prime tab. Source logic is unchanged; only the tab label is renamed.")\n',
    '            if callable(prev_morning):\n',
    '                prev_morning()\n',
    '            else:\n',
    '                st.info("Morning / Doo Prime source is not available in this ZIP.")\n',
    '        if callable(footer):\n',
    '            try:\n',
    '                footer("Lunch")\n',
    '            except Exception:\n',
    '                pass\n',
    '\n',
    '    ns["show"] = _show_final_reorganized\n',
    '    ns["render_data_analysis_result_table_20260614"] = render_data_analysis_result_table_20260614\n',
    '    ns["_dinner_morning_data_patch_installed_20260614"] = True\n',
]
