"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        bounds[1].metric("Main Projection", f"{float(latest_red.get(\'main_path\', 0) or 0):.5f}" if not latest_red.empty else "N/A")\n',
    '        bounds[2].metric("Upper Bound", f"{float(latest_red.get(\'upper_band\', 0) or 0):.5f}" if not latest_red.empty else "N/A")\n',
    '        bounds[3].metric("Band Coverage", f"{float(calibration_summary.get(\'estimated_band_coverage_pct\', 0) or 0):.1f}%", "Empirical estimate")\n',
    '\n',
    '        vertical_points = calibrated_main[[c for c in ["step", "time", "lower_band", "main_path", "upper_band"] if c in calibrated_main.columns]].copy() if isinstance(calibrated_main, pd.DataFrame) else pd.DataFrame()\n',
    '        if "step" not in vertical_points.columns:\n',
    '            vertical_points.insert(0, "step", range(1, len(vertical_points) + 1))\n',
    '        if not alpha_df.empty:\n',
    '            alpha_cols = alpha_df[[c for c in ["step", "alpha_diff_pips", "delta_point_pips"] if c in alpha_df.columns]].copy()\n',
    '            vertical_points = vertical_points.merge(alpha_cols, on="step", how="left")\n',
    '        vertical_points = vertical_points.rename(columns={\n',
    '            "step": "Horizon Point", "time": "Projection Time", "lower_band": "Lower Bound",\n',
    '            "main_path": "Projected Price", "upper_band": "Upper Bound",\n',
    '            "alpha_diff_pips": "Alpha Point (pips)", "delta_point_pips": "Delta Point (pips)",\n',
    '        })\n',
    '        st.session_state["lunch_powerbi_vertical_projection_points_20260617"] = vertical_points\n',
    '\n',
    '        if err is None:\n',
    '            st.warning("Reliability warning: prediction-vs-actual error is unavailable. Run the backtest before treating projection accuracy as verified.")\n',
    '        elif error_proxy:\n',
    '            st.warning(\n',
    '                f"Accuracy is not verified yet: {err:.5f}% is a recent-H1 volatility proxy, not completed prediction-vs-actual error. "\n',
    '                "Run the PowerBI backtest before treating the path as accuracy-tested."\n',
    '            )\n',
    '        elif err > 0.08 or (acc and acc < 52):\n',
    '            st.warning(f"Reliability warning: close-error {err:.4f}% and direction accuracy {acc:.1f}%. Treat the red/yellow paths as weaker until actual/error improves.")\n',
    '        else:\n',
    '            st.success(f"Reliability OK: close-error {err:.4f}% and direction accuracy {acc:.1f}% from existing actual/error metrics.")\n',
    '\n',
    '        try:\n',
    '            import plotly.graph_objects as go\n',
    '            view = d.tail(110)\n',
    '            fig = go.Figure()\n',
    '            fig.add_trace(go.Candlestick(x=view["time"], open=view["open"], high=view["high"], low=view["low"], close=view["close"], name="Actual H1 candles"))\n',
    '\n',
    '            # Reliability-calibrated MAIN path and empirically expanding bands.\n',
    '            if isinstance(calibrated_main, pd.DataFrame) and not calibrated_main.empty:\n',
    '                anchor_time = pd.Timestamp(d["time"].iloc[-1])\n',
    '                anchor_close = float(d["close"].iloc[-1])\n',
    '                anchored_times = [anchor_time] + list(calibrated_main["time"])\n',
    '                fig.add_trace(go.Scatter(x=anchored_times, y=[anchor_close] + list(calibrated_main["upper_band"]), mode="lines", name="Calibrated upper band", line={"color": "rgba(124,58,237,.45)", "dash": "dash"}))\n',
    '                fig.add_trace(go.Scatter(x=anchored_times, y=[anchor_close] + list(calibrated_main["lower_band"]), mode="lines", name="Calibrated lower band", line={"color": "rgba(124,58,237,.45)", "dash": "dash"}, fill="tonexty", fillcolor="rgba(124,58,237,.09)"))\n',
    '                fig.add_trace(go.Scatter(x=anchored_times, y=[anchor_close] + list(calibrated_main["main_path"]), mode="lines+markers", name="MAIN reliability-weighted path", line={"color": "#111827", "width": 5, "shape": "spline", "smoothing": 1.0}, marker={"size": 7}))\n',
    '\n',
    '            # RED/YELLOW/BLUE retain their identities but are shrinkage-calibrated\n',
    '            # toward the shared main path when reliability or agreement is weak.\n',
    '            if not red_display.empty:\n',
    '                fig.add_trace(go.Scatter(x=[pd.Timestamp(d["time"].iloc[-1])] + list(red_display["time"]), y=[float(d["close"].iloc[-1])] + list(red_display["path"]), mode="lines+markers", name="RED calibrated model path", line={"color": "#DC2626", "width": 3}, marker={"size": 5}))\n',
    '            if isinstance(smooth_red, pd.DataFrame) and not smooth_red.empty:\n',
    '                fig.add_trace(go.Scatter(x=[pd.Timestamp(d["time"].iloc[-1])] + list(smooth_red["time"]), y=[float(d["close"].iloc[-1])] + list(smooth_red["red_path"]), mode="lines", name="RED smooth calibrated path", line={"color": "#EF4444", "width": 4, "shape": "spline", "smoothing": 1.05}))\n',
    '            last_time = pd.Timestamp(d["time"].iloc[-1])\n',
    '            last_close = float(d["close"].iloc[-1])\n',
    '            if not yellow_display.empty:\n',
    '                fig.add_trace(go.Scatter(x=[last_time] + list(yellow_display["time"]), y=[last_close] + list(yellow_display["path"]), mode="lines+markers", name="YELLOW calibrated current path", line={"color": "#FACC15", "width": 4}, marker={"color": "#FACC15", "size": 8, "line": {"color": "#111827", "width": 1}}))\n',
    '            if not blue_display.empty:\n',
    '                fig.add_trace(go.Scatter(x=[last_time] + list(blue_display["time"]), y=[last_close] + list(blue_display["path"]), mode="lines+markers", name="BLUE calibrated previous path", line={"color": "#2563EB", "width": 3, "dash": "dot"}, marker={"color": "#2563EB", "size": 6}))\n',
    '\n',
    '            # Alpha/Delta: vertical candle-time points, not horizontal or y2 lines.\n',
    '            if not alpha_df.empty:\n',
    '                alpha_row = alpha_df.sort_values("abs_alpha", ascending=False).iloc[0]\n',
    '                delta_row = alpha_df.sort_values("abs_delta", ascending=False).iloc[0]\n',
    '                for label, row, dash, symbol in [("Alpha Point", alpha_row, "dot", "star"), ("Delta Point", delta_row, "dash", "diamond")]:\n',
    '                    xval = row.get("yellow_time")\n',
    '                    yval = row.get("yellow_path")\n',
    '                    try:\n',
    '                        fig.add_vline(x=xval, line_dash=dash, line_width=2, opacity=.82, annotation_text=label, annotation_position="top")\n',
    '                    except Exception:\n',
    '                        pass\n',
    '                    try:\n',
    '                        fig.add_trace(go.Scatter(x=[xval], y=[yval], mode="markers+text", name=label, text=[label], textposition="top center", marker={"size": 13, "symbol": symbol}))\n',
    '                    except Exception:\n',
    '                        pass\n',
    '\n',
    '            fig.update_layout(\n',
    '                height=660,\n',
    '                margin=dict(l=4, r=4, t=52, b=4),\n',
    '                title="PowerBI Price Projection — calibrated MAIN + upper/lower bands + RED/YELLOW/BLUE paths",\n',
    '                xaxis_rangeslider_visible=False,\n',
    '                yaxis=dict(title="Price"),\n',
    '                legend=dict(orientation="h"),\n',
    '            )\n',
    '            st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False, "responsive": True})\n',
    '        except Exception as exc:\n',
    '            st.warning(f"Chart skipped safely: {exc}")\n',
    '\n',
    '        with st.expander("Open / Close — Vertical Alpha / Delta + Lower / Upper Bounds", expanded=True):\n',
    '            st.caption("Each projected H1 point is shown vertically with its lower bound, projected price, upper bound, Alpha point and Delta point. The chart whiskers use the same lower/upper values.")\n',
    '            if isinstance(vertical_points, pd.DataFrame) and not vertical_points.empty:\n',
    '                st.dataframe(vertical_points, use_container_width=True, hide_index=True, height=300)\n',
    '            else:\n',
    '                st.info("Vertical projection points are not ready yet.")\n',
    '\n',
    '        with st.expander("Open / Close — Prediction line source tables", expanded=False):\n',
    '            st.markdown("##### Calibrated MAIN path + empirical bands")\n',
    '            st.dataframe(calibrated_main.head(80), use_container_width=True, hide_index=True, height=220)\n',
    '            st.markdown("##### RED calibrated source")\n',
    '            st.dataframe(red_display.head(80), use_container_width=True, hide_index=True, height=220)\n',
    '            if not yellow_display.empty:\n',
    '                st.markdown("##### YELLOW calibrated current source")\n',
    '                st.dataframe(yellow_display.head(80), use_container_width=True, hide_index=True, height=220)\n',
    '            if not blue_display.empty:\n',
    '                st.markdown("##### BLUE calibrated previous-candle source")\n',
    '                st.dataframe(blue_display.head(80), use_container_width=True, hide_index=True, height=220)\n',
    '            if not alpha_df.empty:\n',
    '                st.markdown("##### GREEN alpha difference table")\n',
    '                st.dataframe(alpha_df.head(80), use_container_width=True, hide_index=True, height=220)\n',
    '\n',
    '\n',
    'def _render_lunch_reorganized(ns: dict) -> None:\n',
    '    st.markdown("### 🍱 Lunch — Metric + Price Projection Center")\n',
    '    st.caption("Lunch keeps metric/history and the red prediction-line display. Master reliability and Final Synced Intelligence have moved to Dinner.")\n',
    '    try:\n',
    '        import tabs.final_three_center_upgrade_20260614 as three\n',
    '        three._render_metric_detail_section(ns)\n',
    '    except Exception as exc:\n',
    '        st.error("Lunch metric/history section could not render safely.")\n',
    '        st.exception(exc)\n',
    '    _render_lunch_red_prediction_line()\n',
    '    with st.expander("📌 Open / Close — Lunch placement note", expanded=False):\n',
    '        st.write("Master Decision + Reliability + Priority Center and Final Synced Intelligence are now in **Dinner → Combine Logic**. Original source logic is still visible there at the last place.")\n',
    '\n',
    '\n',
    'def _render_final_synced_intelligence(ns: dict, prev_data) -> None:\n',
    '    renderer = ns.get("_render_final_synced_intelligence_inner_20260612")\n',
    '    if callable(renderer):\n',
    '        renderer()\n',
    '        return\n',
    '    with st.expander("🧠 Open / Close — Final Synced Intelligence: ML Tables + KNN/Greedy + News/NLP + Quant Structure + Research", expanded=False):\n',
    '        st.caption("Original source is preserved below. This fallback shows cached data without rerunning hidden calculations.")\n',
    '        pack = st.session_state.get("final_synced_research_merge_pack_20260612") or st.session_state.get("final_merged_intelligence_pack_20260612")\n',
    '        if isinstance(pack, dict) and pack:\n',
    '            pr = pack.get("priority_1_to_14")\n',
    '            if not isinstance(pr, pd.DataFrame) or pr.empty:\n',
    '                pr = pack.get("knn_greedy_priority")\n',
    '            cols = st.columns(5)\n',
    '            cols[0].metric("Master Regime", pack.get("master_regime", "-"))\n',
    '            cols[1].metric("Master Direction", pack.get("master_direction", "WAIT"))\n',
    '            cols[2].metric("Forecast Conf", _fmt(pack.get("projection_confidence", 0), "%"))\n',
    '            cols[3].metric("News Sync", (pack.get("news_nlp", {}) if isinstance(pack.get("news_nlp", {}), dict) else {}).get("news_sync", "-"))\n',
    '            cols[4].metric("Structure", (pack.get("quant_structure", {}) if isinstance(pack.get("quant_structure", {}), dict) else {}).get("quant_structure_score", "-"))\n',
    '            if isinstance(pr, pd.DataFrame) and not pr.empty:\n',
    '                st.dataframe(pr, use_container_width=True, hide_index=True, height=320)\n',
    '            _copy_button("Copy Cached Final Synced Intelligence", _safe_json(pack), f"copy_cached_final_synced_{UNIQUE}")\n',
    '        else:\n',
    '            st.info("Run the original Data Visualization synced intelligence source from the Advanced Details section below.")\n',
    '\n',
    '\n',
    'def _render_original_data_last(ns: dict, prev_data) -> None:\n',
    '    with st.expander("📦 Open / Close — Original Data / Advanced Details at Last Place", expanded=False):\n',
    '        st.caption("This preserved original renderer now reads the same main Settings run automatically. No separate Run or Load button is shown anywhere in the Regime/Dinner workflow.")\n',
    '        ready = bool(st.session_state.get("metric_run_calculate", False))\n',
    '        if ready and callable(prev_data):\n',
    '            try:\n',
    '                # Existing renderer reads the caches already primed by Settings.\n',
    '                # It is not allowed to create a separate canonical run.\n',
    '                st.session_state["dinner_load_original_advanced_details_20260614"] = True\n',
    '                prev_data()\n',
    '            except Exception as exc:\n',
    '                st.error("Original Data Visualization / Final Synced Intelligence source failed safely.")\n',
    '                with st.expander("Open / Close — technical detail", expanded=False):\n',
    '                    st.code(str(exc))\n',
    '        elif not ready:\n',
    '            try:\n',
    '                from core.system_wide_completion_20260618 import readiness_message\n',
    '                st.info(readiness_message(st.session_state, "Research Data Analysis"))\n',
    '            except Exception:\n',
    '                st.info("Use Settings → Run Calculation + Open Lunch once.")\n',
    '        else:\n',
    '            st.info("Original Data Visualization source is not available in this ZIP.")\n',
    '        with st.expander("Open / Close — Session source keys for audit", expanded=False):\n',
    '            keys = [k for k in st.session_state.keys() if any(x in str(k).lower() for x in ["regime", "priority", "reliability", "powerbi", "projection", "synced", "research"])]\n',
    '            st.dataframe(pd.DataFrame({"Source Key": sorted(map(str, keys))}), use_container_width=True, hide_index=True, height=260)\n',
    '\n',
    '\n',
    'def _render_priority_decision_reliability(ns: dict) -> None:\n',
    '    try:\n',
    '        import tabs.final_three_center_upgrade_20260614 as three\n',
    '        three._render_master_center(ns)\n',
    '    except Exception as exc:\n',
    '        st.error("Priority + Decision + Reliability KNN/Greedy center could not render safely.")\n',
    '        st.exception(exc)\n',
    '    ctx = _ctx(ns, False)\n',
    '    ptab = _priority_table_from_state(ctx)\n',
    '    if isinstance(ptab, pd.DataFrame) and not ptab.empty:\n',
    '        with st.expander("📌 Open / Close — Priority + Decision + Reliability KNN/Greedy table", expanded=False):\n',
    '            st.dataframe(ptab.head(120), use_container_width=True, hide_index=True, height=360)\n',
    '\n',
    '\n',
    'def _render_chatgpt_style_ai() -> None:\n',
    '    st.markdown("### 🤖 AI Assistant — Dinner Local Chat")\n',
    '    st.caption("ChatGPT-like layout. Local NLP + fuzzy matching + history matching only. Regime-aware, priority-aware, reliability-aware. No API, no heavy neural network.")\n',
    '    try:\n',
    '        import tabs.ai_assistant_lite as ai\n',
    '    except Exception as exc:\n',
    '        st.error("AI Assistant source could not load safely.")\n',
    '        st.exception(exc)\n',
    '        return\n',
    '    try:\n',
    '        ai._inject_mobile_css()\n',
    '    except Exception:\n',
    '        pass\n',
    '    ctx = ai.build_ai_context_from_existing_data()\n',
    '    try:\n',
    '        from core.canonical_runtime_20260617 import get_canonical, shared_from_runtime\n',
    '        from core.ai_canonical_grounding_20260618 import build_ai_grounding\n',
    '        canonical = get_canonical(st.session_state)\n',
    '        shared_runtime = shared_from_runtime(st.session_state)\n',
    '        ai_component = shared_runtime.get("ai_grounding", {}) if isinstance(shared_runtime, dict) else {}\n',
    '        canonical_grounding = build_ai_grounding(canonical, ai_component)\n',
    '        if isinstance(ctx, dict):\n',
    '            ctx["canonical_grounding_20260618"] = canonical_grounding\n',
    '            current = ctx.setdefault("current", {})\n',
    '            current.update({\n',
    '                "decision": canonical_grounding.get("current_canonical_decision", "WAIT"),\n',
    '                "direction": canonical_grounding.get("directional_market_view", "WAIT"),\n',
    '                "regime": canonical_grounding.get("current_regime", "UNKNOWN"),\n',
    '                "entry_permission": canonical_grounding.get("entry_permission", "NO ENTRY / WAIT"),\n',
    '                "less_risky_decision": canonical_grounding.get("less_risky_decision", "WAIT"),\n',
    '            })\n',
    '    except Exception:\n',
    '        canonical_grounding = {}\n',
    '    if "ai_lite_messages" not in st.session_state:\n',
    '        st.session_state["ai_lite_messages"] = []\n',
    '    if not st.session_state["ai_lite_messages"]:\n',
    '        st.session_state["ai_lite_messages"].append({"role": "assistant", "content": "Ask about regime, priority, reliability, TP, exit risk, or next H1 bias. I use only local system data.", "meta": {}})\n',
    '    st.markdown(\n',
    '        """\n',
    '        <style>\n',
    '        .dinner-chat-shell{border:1px solid rgba(15,23,42,.10);border-radius:22px;padding:.75rem;background:linear-gradient(180deg,rgba(248,250,252,.96),rgba(239,246,255,.86));box-shadow:0 12px 34px rgba(15,23,42,.06);}\n',
    '        .dinner-chat-meta{font-size:.82rem;color:#475569;padding:.55rem .75rem;border-radius:16px;background:rgba(255,255,255,.70);margin-bottom:.7rem;}\n',
    '        @media(max-width:780px){.dinner-chat-shell{padding:.55rem;border-radius:18px}.dinner-chat-meta{font-size:.76rem}}\n',
    '        </style>\n',
    '        """,\n',
    '        unsafe_allow_html=True,\n',
    '    )\n',
    '    cur = ctx.get("current", {}) if isinstance(ctx, dict) else {}\n',
    '    st.markdown(\n',
    '        f"<div class=\'dinner-chat-shell\'><div class=\'dinner-chat-meta\'>EURUSD H1 • Decision <b>{cur.get(\'decision\',\'-\')}</b> • Direction <b>{cur.get(\'direction\',\'-\')}</b> • Regime <b>{cur.get(\'regime\',\'-\')}</b> • Entry {cur.get(\'entry_score\',\'-\')} • Exit Risk {cur.get(\'exit_risk\',\'-\')}</div></div>",\n',
    '        unsafe_allow_html=True,\n',
    '    )\n',
    '    chat_box = st.container(height=420, border=True)\n',
    '    with chat_box:\n',
    '        for msg in st.session_state.get("ai_lite_messages", [])[-18:]:\n',
    '            role = str(msg.get("role", "assistant"))\n',
    '            with st.chat_message("user" if role == "user" else "assistant"):\n',
    '                st.markdown(str(msg.get("content", "")))\n',
    '    labels = ["Use typed question"]\n',
    '    label_to_item: Dict[str, Dict[str, Any]] = {"Use typed question": {"question": "", "category": "Free Chat"}}\n',
    '    for item in getattr(ai, "PREPARED_QUESTION_PATTERNS", []):\n',
    '        q = str(item.get("question", "")).strip()\n',
    '        if not q:\n',
    '            continue\n',
    '        cat = str(item.get("category", "All Questions"))\n',
    '        label = f"{cat} — {q}"\n',
    '        if label in label_to_item:\n',
    '            label = f"{label} #{len(label_to_item)}"\n',
    '        labels.append(label)\n',
    '        label_to_item[label] = item\n',
    '    st.markdown("#### Ask at bottom")\n',
    '    selected = st.selectbox("One selector", labels, key=f"dinner_ai_selector_{UNIQUE}")\n',
    '    typed = st.text_area("One question input", height=74, key=f"dinner_ai_input_{UNIQUE}", placeholder="Type: what is current regime risk, best hour, TP for sell, exit now or hold, why priority changed...")\n',
    '    send = st.button("🚀 Send / Analyze", key=f"dinner_ai_send_{UNIQUE}", use_container_width=True)\n',
    '    if send:\n',
    '        selected_item = label_to_item.get(selected, {})\n',
    '        prompt = str(typed or "").strip() or str(selected_item.get("question", "What should I do now?")).strip()\n',
    '        if not prompt:\n',
    '            prompt = "What should I do now?"\n',
    '        category = "Free Chat" if typed.strip() else str(selected_item.get("category", "Prepared Question"))\n',
    '        parsed = ai.local_ai_detect_intent(prompt)\n',
    '        # A selected prepared question already has an explicit tested intent.\n',
    '        # Preserve it so 1,000 similar variants do not collapse to one fuzzy answer.\n',
    '        if not typed.strip() and selected_item.get("intent"):\n',
    '            parsed["intent"] = str(selected_item.get("intent"))\n',
    '            parsed["intent_label"] = ai.INTENT_REGISTRY.get(parsed["intent"], {}).get("label", parsed["intent"])\n',
    '            parsed["matched_prepared_question"] = str(selected_item.get("question", prompt))\n',
    '            parsed["intent_source"] = "prepared-question-exact"\n',
    '            for field in ("pattern_id", "answer_rule", "category", "pattern", "keywords"):\n',
    '                if selected_item.get(field) not in (None, ""):\n',
    '                    parsed[field] = selected_item.get(field)\n',
    '        parsed["selected_question_category"] = category\n',
    '        parsed["answer_mode"] = "Auto"\n',
    '        answer = ai.local_ai_generate_answer(parsed, ctx)\n',
    '        try:\n',
    '            answer = ai.apply_prepared_question_focus_20260618(answer, parsed, ctx)\n',
    '        except Exception:\n',
    '            pass\n',
    '        try:\n',
    '            answer = ai._apply_answer_mode(answer, "Auto", parsed, ctx)\n',
    '        except Exception:\n',
    '            pass\n',
    '        try:\n',
    '            from core.ai_canonical_grounding_20260618 import format_grounded_answer\n',
    '            answer = format_grounded_answer(canonical_grounding, answer, question=prompt)\n',
    '        except Exception:\n',
    '            pass\n',
    '        # Add current reliability/regime/priority awareness using existing state.\n',
    '        warnings = []\n',
    '        try:\n',
    '            risk = ai._risk_level(cur)\n',
    '            if str(risk).upper() in {"HIGH", "DANGER", "AVOID"}:\n',
    '                warnings.append(f"Risk: {risk}")\n',
    '        except Exception:\n',
    '            pass\n',
    '        regime = cur.get("regime")\n',
    '        direction = cur.get("direction")\n',
    '        if regime:\n',
    '            warnings.append(f"Regime-aware: {regime}")\n',
    '        if direction:\n',
    '            warnings.append(f"Priority/decision-aware direction: {direction}")\n',
    '        missing = ctx.get("missing_fields", []) if isinstance(ctx, dict) else []\n',
    '        if missing:\n',
    '            warnings.append(f"Missing fields: {len(missing)}")\n',
    '        if warnings:\n',
    '            answer = answer + "\\n\\nReliability-aware note: " + " • ".join(map(str, warnings))\n',
    '        st.session_state["ai_lite_messages"].append({"role": "user", "content": prompt, "meta": {"category": category}})\n',
    '        st.session_state["ai_lite_messages"].append({"role": "assistant", "content": answer, "meta": parsed})\n',
    '        st.session_state["ai_lite_messages"] = st.session_state["ai_lite_messages"][-32:]\n',
    '        try:\n',
    '            ai._store_question_memory(prompt, parsed.get("normalized_question", ""), parsed.get("intent", "nearest_answer_fallback"), answer)\n',
    '        except Exception:\n',
    '            pass\n',
    '        try:\n',
    '            st.session_state["ai_lite_last_copy_payload"] = ai._copy_payload(prompt, parsed, answer, ctx, category, "Auto")\n',
    '            st.session_state["ai_lite_last_answer_summary_20260614"] = st.session_state["ai_lite_last_copy_payload"]\n',
    '        except Exception:\n',
    '            st.session_state["ai_lite_last_answer_summary_20260614"] = answer\n',
    '        try:\n',
    '            from core.styles import request_close_sidebar\n',
    '            request_close_sidebar()\n',
    '        except Exception:\n',
    '            pass\n',
    '        st.rerun()\n',
    '    c1, c2 = st.columns(2)\n',
    '    with c1:\n',
    '        _copy_button("📋 Copy Last AI Answer", st.session_state.get("ai_lite_last_copy_payload", "No AI answer yet."), f"dinner_copy_last_ai_{UNIQUE}")\n',
    '    with c2:\n',
    '        if st.button("🧹 Clear Chat", key=f"dinner_ai_clear_{UNIQUE}", use_container_width=True):\n',
    '            st.session_state["ai_lite_messages"] = []\n',
    '            st.session_state["ai_lite_last_copy_payload"] = "No AI answer yet."\n',
    '            st.rerun()\n',
    '\n',
    '\n',
    'def _render_dinner(ns: dict, prev_data) -> None:\n',
    '    """Legacy callable retained with the new two-choice Dinner layout."""\n',
    '    st.markdown("### 🌙 Dinner — Regime + Synced Intelligence Center")\n',
    '    options = ["Regime + Combined Logic", "AI Assistant"]\n',
    '    active = st.session_state.get("dinner_active_inner_20260615", "Regime + Combined Logic")\n',
    '    if active not in options:\n',
    '        active = "Regime + Combined Logic"\n',
    '    try:\n',
    '        from ui.stable_ui_libs_20260615 import segmented_choice\n',
    '        active = segmented_choice(\n',
    '            "Dinner workspace",\n',
    '            options,\n',
    '            key="dinner_active_inner_20260615",\n',
    '            default=active,\n',
    '        )\n',
    '    except Exception:\n',
    '        active = st.selectbox("Dinner workspace", options, index=options.index(active), key=f"dinner_inner_select_{UNIQUE}")\n',
    '        st.session_state["dinner_active_inner_20260615"] = active\n',
    '    if active == "AI Assistant":\n',
    '        _render_chatgpt_style_ai()\n',
    '    else:\n',
    '        from tabs.dinner_unified_center_20260617 import render_dinner_unified_center\n',
    '        render_dinner_unified_center(ns, prev_data)\n',
    '\n',
    '\n',
    'def _selector() -> str:\n',
    '    """Stable top page selector.\n',
    '\n',
    '    Fixes the old locked state where Dinner was visually selected but Lunch\n',
    '    content still rendered.  One selection now writes to active_page,\n',
    '    tab_choice, home_inner_tab, and fast-tab state, then reruns immediately.\n',
    '    """\n',
    '    choices = [("Lunch", "🍱"), ("Dinner", "🌙"), ("Research", "🎓"), ("Morning", "🌅")]\n',
    '    aliases = {"Regime": "Dinner", "Dinner Tab": "Dinner", "Doo Prime": "Morning", "Morning Tab": "Morning", "AI Assistant": "Dinner", "AI Assistant Lite": "Dinner", "Data Visualization": "Lunch", "Home": "Lunch"}\n',
    '    current = st.session_state.get("active_page", st.session_state.get("home_inner_tab", "Lunch"))\n',
    '    current = aliases.get(str(current), str(current))\n',
    '    names = [name for name, _ in choices]\n',
    '    if current not in names:\n',
    '        current = aliases.get(str(st.session_state.get("home_inner_tab", "Lunch")), "Lunch")\n',
    '    if current not in names:\n',
    '        current = "Lunch"\n',
    '    st.session_state["home_inner_tab"] = current\n',
    '    selected = current\n',
    '    try:\n',
    '        from ui.safe_tab_switch_20260615 import safe_tab_choice\n',
    '        selected = safe_tab_choice(\n',
    '            label="Home / Lunch tab choice",\n',
    '            options=names,\n',
    '            icons=["box-seam", "moon", "search", "sun"],\n',
    '            state_key="home_inner_tab",\n',
    '            widget_key=f"safe_home_inner_tab_switch_{UNIQUE}",\n',
    '            default=current,\n',
    '            horizontal=True,\n',
    '            rerun_on_change=False,\n',
    '        )\n',
    '    except Exception:\n',
    '        cols = st.columns(len(choices))\n',
    '        for i, (name, icon) in enumerate(choices):\n',
    '            active = selected == name\n',
    '            if cols[i].button(("✅ " if active else "") + f"{icon} {name}", key=f"selector_{i}_{UNIQUE}", use_container_width=True):\n',
    '                selected = name\n',
    '\n',
    '    selected = aliases.get(str(selected), str(selected))\n',
    '    if selected not in names:\n',
    '        selected = "Lunch"\n',
    '\n',
    '    # Main bug fix: the visible selector and actual router now use the same page key.\n',
    '    if (\n',
    '        st.session_state.get("active_page") != selected\n',
    '        or st.session_state.get("tab_choice") != selected\n',
    '        or st.session_state.get("home_inner_tab") != selected\n',
    '    ):\n',
    '        st.session_state["home_inner_tab"] = selected\n',
    '        st.session_state["active_page"] = selected\n',
    '        st.session_state["tab_choice"] = selected\n',
    '        st.session_state["active_subpage"] = ""\n',
    '        st.session_state["ui_navigation_click_ts"] = time.time()\n',
    '        st.session_state["fast_tab_switch_active"] = True\n',
]
