"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    })\n',
    '    try:\n',
    '        import plotly.graph_objects as go\n',
    '        fig = go.Figure()\n',
    '        fig.add_trace(go.Scatter(x=src["time"], y=src["path"], mode="lines+markers", name="Current regime path", line={"shape": "hv", "width": 3}))\n',
    '        fig.add_trace(go.Scatter(x=src["time"], y=src["previous_path"], mode="lines", name="Previous regime path", line={"dash": "dot", "width": 2}))\n',
    '        fig.add_trace(go.Scatter(x=future["time"], y=future["upper_band"], mode="lines", name="Shift-risk upper band", line={"dash": "dash"}, showlegend=True))\n',
    '        fig.add_trace(go.Scatter(x=future["time"], y=future["lower_band"], mode="lines", name="Shift-risk lower band", line={"dash": "dash"}, fill="tonexty", showlegend=True))\n',
    '        fig.add_trace(go.Scatter(x=future["time"], y=future["expected_path"], mode="lines+markers", name="Expected next regime path", line={"width": 4, "shape": "spline", "smoothing": 1.05}))\n',
    '        fig.add_trace(go.Scatter(x=src["time"], y=src["confidence"], mode="lines", name="Confidence %", yaxis="y2"))\n',
    '        fig.add_trace(go.Scatter(x=src["time"], y=src["reliability"], mode="lines", name="Reliability %", yaxis="y2"))\n',
    '        try:\n',
    '            from core.alpha_delta_points_20260615 import add_alpha_delta_vertical_markers\n',
    '            current_path = src[["time", "path"]].rename(columns={"path": "Blue Path"})\n',
    '            expected_path = future[["time", "expected_path"]].rename(columns={"expected_path": "Red Path"})\n',
    '            fig = add_alpha_delta_vertical_markers(fig, current_path, expected_path, blue_label="Blue Path", red_label="Red Path", key="regime_blue_red")\n',
    '        except Exception:\n',
    '            pass\n',
    '        fig.update_layout(\n',
    '            height=520,\n',
    '            margin=dict(l=4, r=4, t=42, b=4),\n',
    '            xaxis_title="H1 time",\n',
    '            yaxis=dict(title="Regime path", tickvals=[-1, 0, 1], ticktext=["BEAR", "RANGE", "BULL"], range=[-1.45, 1.45]),\n',
    '            yaxis2=dict(title="Confidence/Reliability %", overlaying="y", side="right", range=[0, 100]),\n',
    '            legend=dict(orientation="h"),\n',
    '        )\n',
    '        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False, "responsive": True})\n',
    '    except Exception as exc:\n',
    '        st.warning(f"Regime projection chart could not render; table view is shown instead. {exc}")\n',
    '    try:\n',
    '        from core.alpha_delta_points_20260615 import render_alpha_delta_point_panel\n',
    '        current_path = src[["time", "path"]].rename(columns={"path": "Blue Path"})\n',
    '        expected_path = future[["time", "expected_path"]].rename(columns={"expected_path": "Red Path"})\n',
    '        render_alpha_delta_point_panel(current_path, expected_path, key="regime_blue_red", title="Regime Alpha / Delta Data Point", blue_label="Blue Path", red_label="Red Path")\n',
    '    except Exception as exc:\n',
    '        st.caption(f"Regime alpha/delta data point skipped safely: {exc}")\n',
    '    show = pd.concat([src.tail(30), future.rename(columns={"expected_path": "path"})], ignore_index=True, sort=False)\n',
    '    with st.expander("Open / Close — PowerBI Regime Projection data table", expanded=False):\n',
    '        st.dataframe(show, use_container_width=True, hide_index=True, height=320)\n',
    '\n',
    '\n',
    'def _build_red_projection_from_lunch_data_v20260615(d: pd.DataFrame, horizon: int = 6) -> pd.DataFrame:\n',
    '    """Lightweight fallback red display from currently entered Lunch OHLC data.\n',
    '\n',
    '    It is a visual/error-adjusted path only. It uses existing OHLC momentum,\n',
    '    volatility, and any cached reliability/error metrics. It does not train or\n',
    '    add a heavy model and does not change the original PowerBI calculation.\n',
    '    """\n',
    '    if not isinstance(d, pd.DataFrame) or d.empty or "close" not in d.columns:\n',
    '        return pd.DataFrame()\n',
    '    x = d.copy().tail(260).reset_index(drop=True)\n',
    '    if "time" not in x.columns:\n',
    '        x["time"] = pd.date_range(end=pd.Timestamp.now().floor("h"), periods=len(x), freq="h")\n',
    '    x["time"] = pd.to_datetime(x["time"], errors="coerce")\n',
    '    for col in ["open", "high", "low", "close"]:\n',
    '        if col not in x.columns:\n',
    '            x[col] = x.get("close", np.nan)\n',
    '        x[col] = pd.to_numeric(x[col], errors="coerce")\n',
    '    x = x.dropna(subset=["time", "close"]).sort_values("time").reset_index(drop=True)\n',
    '    if len(x) < 8:\n',
    '        return pd.DataFrame()\n',
    '    close = x["close"].astype(float)\n',
    '    ret = close.pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    mom_3 = float(ret.tail(3).mean()) if len(ret) else 0.0\n',
    '    mom_12 = float(ret.tail(12).mean()) if len(ret) >= 4 else mom_3\n',
    '    ema_fast = close.ewm(span=min(12, max(3, len(close)//4)), adjust=False).mean()\n',
    '    ema_slow = close.ewm(span=min(48, max(6, len(close)//2)), adjust=False).mean()\n',
    '    trend_gap = float((ema_fast.iloc[-1] - ema_slow.iloc[-1]) / max(abs(close.iloc[-1]), 1e-12)) if len(close) >= 6 else 0.0\n',
    '    # Existing reliability/error data, if available, dampens the visual path.\n',
    '    bt = st.session_state.get("dv_pp_bt_summary", {})\n',
    '    err_pct = _num(bt.get("avg_abs_close_error_pct", 0) if isinstance(bt, dict) else 0, 0)\n',
    '    acc_pct = _num(bt.get("direction_accuracy_pct", 0) if isinstance(bt, dict) else 0, 0)\n',
    '    reliability = 55.0\n',
    '    for key in ["Forecast Reliability %", "Prediction Reliability", "Reliability", "reliability"]:\n',
    '        for obj in [st.session_state.get("reliability_control_center_20260614"), st.session_state.get("regime_context_20260614"), st.session_state.get("three_center_priority_summary_20260614")]:\n',
    '            if isinstance(obj, dict) and key in obj:\n',
    '                reliability = _clip(obj.get(key), 0, 100)\n',
    '                break\n',
    '    if acc_pct:\n',
    '        reliability = max(0.0, min(100.0, (reliability + acc_pct) / 2.0))\n',
    '    damp = max(0.25, min(1.0, reliability / 100.0)) * max(0.45, 1.0 - min(abs(err_pct), 0.25))\n',
    '    raw_drift = mom_3 * 0.45 + mom_12 * 0.35 + trend_gap / 180.0\n',
    '    drift = max(-0.0025, min(0.0025, raw_drift)) * damp\n',
    '    try:\n',
    '        diffs = x["time"].diff().dropna()\n',
    '        step = diffs.median() if len(diffs) else pd.Timedelta(hours=1)\n',
    '        if pd.isna(step) or step.total_seconds() <= 0:\n',
    '            step = pd.Timedelta(hours=1)\n',
    '    except Exception:\n',
    '        step = pd.Timedelta(hours=1)\n',
    '    last_time = pd.Timestamp(x["time"].iloc[-1])\n',
    '    prev = float(close.iloc[-1])\n',
    '    if "high" in x.columns and "low" in x.columns:\n',
    '        atr = float((x["high"] - x["low"]).tail(48).median())\n',
    '    else:\n',
    '        atr = abs(prev) * 0.0004\n',
    '    if not math.isfinite(atr) or atr <= 0:\n',
    '        atr = abs(prev) * 0.0004\n',
    '    rows: List[Dict[str, Any]] = []\n',
    '    for i in range(1, int(max(3, min(horizon, 24))) + 1):\n',
    '        wave = math.sin(i / 2.7) * (atr / max(abs(prev), 1e-12)) * 0.11 * damp\n',
    '        red_close = prev * (1.0 + drift * (0.96 ** (i - 1)) + wave)\n',
    '        band = atr * (1.0 + i / 10.0) * (1.15 if reliability < 55 else 0.90)\n',
    '        rows.append({\n',
    '            "time": last_time + step * i,\n',
    '            "Accuracy Adjusted Price": round(float(red_close), 6),\n',
    '            "Predicted Close": round(float(red_close), 6),\n',
    '            "Upper Band": round(float(red_close + band), 6),\n',
    '            "Lower Band": round(float(red_close - band), 6),\n',
    '            "Reliability %": round(float(reliability), 2),\n',
    '            "Source": "Lunch OHLC fallback red display",\n',
    '            "Step": int(i),\n',
    '        })\n',
    '        prev = float(red_close)\n',
    '    out = pd.DataFrame(rows)\n',
    '    st.session_state["lunch_red_projection_fallback_20260615"] = out\n',
    '    return out\n',
    '\n',
    '\n',
    'def _yellow_projection_from_lunch_data_v20260615(d: pd.DataFrame, horizon: int = 6, anchor_offset: int = 0, mode: str = "Balanced", risk_filter: str = "Medium") -> pd.DataFrame:\n',
    '    """Lightweight yellow/previous projection from existing OHLC.\n',
    '\n',
    '    This first reuses the existing Home yellow builder when available. If that\n',
    '    builder is not loaded, it falls back to the same simple momentum/ATR display\n',
    '    transform used by the previous yellow section. It does not train a new model.\n',
    '    """\n',
    '    if not isinstance(d, pd.DataFrame) or d.empty:\n',
    '        return pd.DataFrame()\n',
    '    x = d.copy().sort_values("time").reset_index(drop=True)\n',
    '    for col in ["open", "high", "low", "close"]:\n',
    '        if col not in x.columns:\n',
    '            x[col] = x.get("close", np.nan)\n',
    '        x[col] = pd.to_numeric(x[col], errors="coerce")\n',
    '    x["time"] = pd.to_datetime(x["time"], errors="coerce")\n',
    '    x = x.dropna(subset=["time", "close"]).reset_index(drop=True)\n',
    '    if len(x) < 12:\n',
    '        return pd.DataFrame()\n',
    '    anchor_idx = max(0, len(x) - 1 - int(max(0, anchor_offset)))\n',
    '    if anchor_idx < 6:\n',
    '        return pd.DataFrame()\n',
    '    sub = x.iloc[: anchor_idx + 1].copy()\n',
    '\n',
    '    # Prefer the existing yellow builder that the main PowerBI tab already uses.\n',
    '    try:\n',
    '        import tabs.home as home\n',
    '        build = home.__dict__.get("_build_last_candle_yellow_6h_projection_v5")\n',
    '        if callable(build):\n',
    '            fut = build(sub, horizon=int(horizon), mode=mode, risk_filter=risk_filter)\n',
    '            if isinstance(fut, pd.DataFrame) and not fut.empty:\n',
    '                out = fut.copy()\n',
    '                tcol = _find_col(out, ["time", "Future Time", "Datetime"])\n',
    '                ycol = _find_col(out, ["Yellow Predicted Close", "Predicted Close", "Projected Close", "close"])\n',
    '                ucol = _find_col(out, ["Upper Risk Band", "Upper Band", "upper"])\n',
    '                lcol = _find_col(out, ["Lower Risk Band", "Lower Band", "lower"])\n',
    '                if tcol and ycol:\n',
    '                    res = pd.DataFrame({\n',
    '                        "step": range(1, len(out) + 1),\n',
    '                        "time": pd.to_datetime(out[tcol], errors="coerce"),\n',
    '                        "path": pd.to_numeric(out[ycol], errors="coerce"),\n',
    '                        "upper": pd.to_numeric(out[ucol], errors="coerce") if ucol else np.nan,\n',
    '                        "lower": pd.to_numeric(out[lcol], errors="coerce") if lcol else np.nan,\n',
    '                    }).dropna(subset=["time", "path"])\n',
    '                    res["anchor_time"] = pd.Timestamp(sub["time"].iloc[-1])\n',
    '                    res["anchor_price"] = float(sub["close"].iloc[-1])\n',
    '                    return res.reset_index(drop=True)\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '    close = sub["close"].astype(float).ffill()\n',
    '    high = sub["high"].astype(float).ffill() if "high" in sub else close\n',
    '    low = sub["low"].astype(float).ffill() if "low" in sub else close\n',
    '    ret = close.pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    if mode == "Trend follow":\n',
    '        base_ret = float(ret.ewm(span=6, adjust=False).mean().iloc[-1])\n',
    '    elif mode == "Pullback safer":\n',
    '        base_ret = float(ret.ewm(span=12, adjust=False).mean().iloc[-1]) * 0.45\n',
    '    else:\n',
    '        base_ret = float(ret.ewm(span=9, adjust=False).mean().iloc[-1]) * 0.75\n',
    '    risk_mult = {"Low": 0.55, "Medium": 0.80, "High": 1.00}.get(str(risk_filter), 0.80)\n',
    '    base_ret *= risk_mult\n',
    '    atr = float((high - low).rolling(14, min_periods=4).mean().ffill().fillna((high - low).mean()).iloc[-1] or 0)\n',
    '    if not math.isfinite(atr) or atr <= 0:\n',
    '        atr = abs(float(close.iloc[-1])) * 0.00035\n',
    '    last_time = pd.Timestamp(sub["time"].iloc[-1])\n',
    '    price = float(close.iloc[-1])\n',
    '    try:\n',
    '        step_delta = sub["time"].diff().dropna().median()\n',
    '        if pd.isna(step_delta) or step_delta.total_seconds() <= 0:\n',
    '            step_delta = pd.Timedelta(hours=1)\n',
    '    except Exception:\n',
    '        step_delta = pd.Timedelta(hours=1)\n',
    '    rows = []\n',
    '    for step in range(1, int(max(1, min(horizon, 24))) + 1):\n',
    '        damp = 1.0 / (1.0 + step * 0.10)\n',
    '        pred = price * (1.0 + base_ret * step * damp)\n',
    '        band = atr * (0.35 + step * 0.10) * risk_mult\n',
    '        rows.append({\n',
    '            "step": int(step),\n',
    '            "time": last_time + step_delta * step,\n',
    '            "path": round(float(pred), 6),\n',
    '            "upper": round(float(pred + band), 6),\n',
    '            "lower": round(float(pred - band), 6),\n',
    '            "anchor_time": last_time,\n',
    '            "anchor_price": price,\n',
    '        })\n',
    '    return pd.DataFrame(rows)\n',
    '\n',
    '\n',
    'def _normalize_price_projection_v20260615(proj: pd.DataFrame, d: pd.DataFrame, horizon: int = 6) -> pd.DataFrame:\n',
    '    if not isinstance(proj, pd.DataFrame) or proj.empty:\n',
    '        return pd.DataFrame()\n',
    '    tcol = _find_col(proj, ["time", "Future Time", "Datetime", "Date"])\n',
    '    ccol = _find_col(proj, ["Accuracy Adjusted Price", "Predicted Close", "Projected Close", "close", "Projected Path"])\n',
    '    ucol = _find_col(proj, ["Upper Band", "upper", "Predicted High", "Projection High", "Upper Risk Band"])\n',
    '    lcol = _find_col(proj, ["Lower Band", "lower", "Predicted Low", "Projection Low", "Lower Risk Band"])\n',
    '    if not (tcol and ccol):\n',
    '        return pd.DataFrame()\n',
    '    p = pd.DataFrame({\n',
    '        "step": range(1, len(proj) + 1),\n',
    '        "time": pd.to_datetime(proj[tcol], errors="coerce"),\n',
    '        "path": pd.to_numeric(proj[ccol], errors="coerce"),\n',
    '    })\n',
    '    if ucol:\n',
    '        p["upper"] = pd.to_numeric(proj[ucol], errors="coerce")\n',
    '    else:\n',
    '        p["upper"] = np.nan\n',
    '    if lcol:\n',
    '        p["lower"] = pd.to_numeric(proj[lcol], errors="coerce")\n',
    '    else:\n',
    '        p["lower"] = np.nan\n',
    '    p = p.dropna(subset=["time", "path"]).sort_values("time").reset_index(drop=True).head(int(max(1, horizon)))\n',
    '    if p.empty:\n',
    '        return p\n',
    '    try:\n',
    '        atr = float((pd.to_numeric(d["high"], errors="coerce") - pd.to_numeric(d["low"], errors="coerce")).tail(48).median())\n',
    '    except Exception:\n',
    '        atr = 0.0\n',
    '    if not math.isfinite(atr) or atr <= 0:\n',
    '        atr = abs(float(p["path"].iloc[0])) * 0.00035\n',
    '    for i in p.index:\n',
    '        step = int(p.loc[i, "step"])\n',
    '        if pd.isna(p.loc[i, "upper"]):\n',
    '            p.loc[i, "upper"] = float(p.loc[i, "path"]) + atr * (0.85 + step / 10.0)\n',
    '        if pd.isna(p.loc[i, "lower"]):\n',
    '            p.loc[i, "lower"] = float(p.loc[i, "path"]) - atr * (0.85 + step / 10.0)\n',
    '    return p\n',
    '\n',
    '\n',
    'def _smooth_price_path_v20260615(p: pd.DataFrame, value_col: str = "path", out_col: str = "smooth") -> pd.DataFrame:\n',
    '    if not isinstance(p, pd.DataFrame) or p.empty or "time" not in p.columns or value_col not in p.columns:\n',
    '        return pd.DataFrame()\n',
    '    if len(p) < 2:\n',
    '        return pd.DataFrame({"time": p["time"], out_col: p[value_col]})\n',
    '    rows: List[Dict[str, Any]] = []\n',
    '    for i in range(len(p) - 1):\n',
    '        t0, t1 = p["time"].iloc[i], p["time"].iloc[i + 1]\n',
    '        y0, y1 = float(p[value_col].iloc[i]), float(p[value_col].iloc[i + 1])\n',
    '        for j in range(4):\n',
    '            u = j / 4.0\n',
    '            s = u * u * (3 - 2 * u)\n',
    '            rows.append({"time": t0 + (t1 - t0) * u, out_col: y0 + (y1 - y0) * s})\n',
    '    rows.append({"time": p["time"].iloc[-1], out_col: float(p[value_col].iloc[-1])})\n',
    '    return pd.DataFrame(rows)\n',
    '\n',
    '\n',
    'def _regime_meta_for_red_chart_v20260615() -> Dict[str, Any]:\n',
    '    try:\n',
    '        from core.regime_sync_20260617 import canonical_regime_snapshot\n',
    '        snap = canonical_regime_snapshot(days=25)\n',
    '        return {\n',
    '            "current_regime": snap.get("regime", "-"),\n',
    '            "regime_start_display": _fmt_time(snap.get("regime_start")),\n',
    '            "regime_end_display": snap.get("regime_end_display", "OPEN / CURRENT"),\n',
    '            "avg_error_pct": snap.get("avg_error_pct"),\n',
    '            "error_samples": int(snap.get("error_samples", 0) or 0),\n',
    '            "error_is_proxy": bool(snap.get("error_is_proxy", False)),\n',
    '            "regime_validation": snap.get("regime_validation", "FALSE / WATCH"),\n',
    '            "reliability": float(snap.get("reliability", 0)),\n',
    '            "direction_accuracy_pct": snap.get("direction_accuracy_pct"),\n',
    '            "error_method": snap.get("error_method", ""),\n',
    '        }\n',
    '    except Exception:\n',
    '        return {"current_regime":"-", "regime_start_display":"Not recorded", "regime_end_display":"OPEN / CURRENT", "avg_error_pct":None, "error_samples":0, "error_is_proxy":False, "regime_validation":"FALSE / WATCH", "reliability":0.0, "direction_accuracy_pct":None, "error_method":""}\n',
    '\n',
    '\n',
    'def _render_lunch_red_prediction_line() -> None:\n',
    '    with st.expander("🔴 Open / Close — Lunch Red Prediction Line: smoother + error-adjusted + reliability warning", expanded=True):\n',
    '        st.caption("Full version: red error-adjusted path + red bands, yellow current path + yellow bands, blue dotted previous-candle predicted path, and green alpha difference line. Uses existing cached projections or current Lunch OHLC fallback only.")\n',
    '        d = _market_df(420)\n',
    '        if d.empty:\n',
    '            st.info("Enter/connect Lunch OHLC data first. After Lunch data exists, this section builds the red/yellow/blue/green display without opening the heavy original PowerBI renderer.")\n',
    '            return\n',
    '\n',
    '        cols = st.columns([.9, .9, .9, 1.15])\n',
    '        with cols[0]:\n',
    '            horizon = st.slider("Path candles", 3, 12, int(st.session_state.get("lunch_red_projection_horizon_20260615", 6) or 6), 1, key="lunch_red_projection_horizon_slider_20260615")\n',
    '            st.session_state["lunch_red_projection_horizon_20260615"] = int(horizon)\n',
    '        with cols[1]:\n',
    '            mode = st.selectbox("Yellow mode", ["Balanced", "Trend follow", "Pullback safer"], index=["Balanced", "Trend follow", "Pullback safer"].index(str(st.session_state.get("lunch_red_yellow_mode_20260615", "Balanced"))) if str(st.session_state.get("lunch_red_yellow_mode_20260615", "Balanced")) in ["Balanced", "Trend follow", "Pullback safer"] else 0, key="lunch_red_yellow_mode_20260615")\n',
    '        with cols[2]:\n',
    '            risk_filter = st.selectbox("Risk filter", ["Low", "Medium", "High"], index=["Low", "Medium", "High"].index(str(st.session_state.get("lunch_red_yellow_risk_20260615", "Medium"))) if str(st.session_state.get("lunch_red_yellow_risk_20260615", "Medium")) in ["Low", "Medium", "High"] else 1, key="lunch_red_yellow_risk_20260615")\n',
    '        with cols[3]:\n',
    '            st.metric("Data rows", len(d))\n',
    '\n',
    '        pack = st.session_state.get("final_synced_research_merge_pack_20260612") or st.session_state.get("final_merged_intelligence_pack_20260612")\n',
    '        proj = pd.DataFrame()\n',
    '        if isinstance(pack, dict):\n',
    '            for key in ["accuracy_adjusted_projection", "red_projection", "prediction_projection", "future_blue_predicted_candles"]:\n',
    '                val = pack.get(key)\n',
    '                if isinstance(val, pd.DataFrame) and not val.empty:\n',
    '                    proj = val.copy()\n',
    '                    break\n',
    '        if proj.empty:\n',
    '            pred = st.session_state.get("dv_pp_predicted", pd.DataFrame())\n',
    '            if isinstance(pred, pd.DataFrame) and not pred.empty:\n',
    '                proj = pred.copy()\n',
    '        if proj.empty:\n',
    '            proj = _build_red_projection_from_lunch_data_v20260615(d, horizon=int(horizon))\n',
    '            if isinstance(proj, pd.DataFrame) and not proj.empty:\n',
    '                st.success("Showing red prediction line from current Lunch data. Original synced PowerBI can overwrite it after you run the original projection.")\n',
    '        red = _normalize_price_projection_v20260615(proj, d, horizon=int(horizon))\n',
    '        if red.empty:\n',
    '            st.info("Projection table does not expose clean time/price columns yet.")\n',
    '            return\n',
    '\n',
    '        yellow = _yellow_projection_from_lunch_data_v20260615(d, horizon=int(horizon), anchor_offset=0, mode=str(mode), risk_filter=str(risk_filter))\n',
    '        blue_prev = _yellow_projection_from_lunch_data_v20260615(d, horizon=int(horizon), anchor_offset=1, mode=str(mode), risk_filter=str(risk_filter))\n',
    '        if yellow.empty:\n',
    '            st.warning("Yellow current path could not be built yet; need more clean candles.")\n',
    '        if blue_prev.empty:\n',
    '            st.warning("Blue dotted previous-candle path could not be built yet; need at least one previous candle and enough history.")\n',
    '\n',
    '        # Accuracy/reliability calibration uses only existing path outputs,\n',
    '        # completed prediction-vs-actual history, regime reliability and robust\n',
    '        # OHLC statistics. It adds no model and never replaces source caches.\n',
    '        try:\n',
    '            from core.powerbi_path_calibration_20260617 import calibrate_projection_bundle\n',
    '            regime_meta = _regime_meta_for_red_chart_v20260615()\n',
    '            calibration = calibrate_projection_bundle(\n',
    '                d,\n',
    '                red=red,\n',
    '                yellow=yellow,\n',
    '                blue=blue_prev,\n',
    '                horizon=int(horizon),\n',
    '                bt_history=st.session_state.get("dv_pp_bt_hist", pd.DataFrame()),\n',
    '                bt_summary=st.session_state.get("dv_pp_bt_summary", {}),\n',
    '                regime_reliability=regime_meta.get("reliability"),\n',
    '                current_regime=regime_meta.get("current_regime"),\n',
    '                transition_or_conflict=regime_meta.get("regime_validation"),\n',
    '                source_data_timestamp=d["time"].iloc[-1] if "time" in d.columns else None,\n',
    '            )\n',
    '        except Exception as exc:\n',
    '            calibration = {"ok": False, "message": str(exc)}\n',
    '        calibrated_main = calibration.get("main", pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n',
    '        red_display = calibration.get("red", pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n',
    '        yellow_display = calibration.get("yellow", pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n',
    '        blue_display = calibration.get("blue", pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n',
    '        if isinstance(red_display, pd.DataFrame) and not red_display.empty:\n',
    '            red_display = red_display.rename(columns={"red_path": "path"})\n',
    '        else:\n',
    '            red_display = red[[c for c in ("step", "time", "path") if c in red.columns]].copy()\n',
    '        if isinstance(yellow_display, pd.DataFrame) and not yellow_display.empty:\n',
    '            yellow_display = yellow_display.rename(columns={"yellow_path": "path"})\n',
    '        else:\n',
    '            yellow_display = yellow[[c for c in ("step", "time", "path") if c in yellow.columns]].copy() if not yellow.empty else pd.DataFrame()\n',
    '        if isinstance(blue_display, pd.DataFrame) and not blue_display.empty:\n',
    '            blue_display = blue_display.rename(columns={"blue_path": "path"})\n',
    '        else:\n',
    '            blue_display = blue_prev[[c for c in ("step", "time", "path") if c in blue_prev.columns]].copy() if not blue_prev.empty else pd.DataFrame()\n',
    '        st.session_state["powerbi_calibrated_bundle_20260617"] = calibration\n',
    '\n',
    '        smooth_red = _smooth_price_path_v20260615(red_display, "path", "red_path")\n',
    '        bt = st.session_state.get("dv_pp_bt_summary", {})\n',
    '        err = _num(bt.get("avg_abs_close_error_pct", 0) if isinstance(bt, dict) else 0, 0)\n',
    '        acc = _num(bt.get("direction_accuracy_pct", 0) if isinstance(bt, dict) else 0, 0)\n',
    '        reliability = float(red.get("Reliability %", pd.Series([55])).iloc[0]) if "Reliability %" in red.columns and len(red) else (acc or 55.0)\n',
    '\n',
    '        alpha_df = pd.DataFrame()\n',
    '        alpha_label = "-"\n',
    '        delta_label = "-"\n',
    '        if not yellow_display.empty and not blue_display.empty:\n',
    '            y = yellow_display[["step", "time", "path"]].rename(columns={"path": "yellow_path", "time": "yellow_time"})\n',
    '            b = blue_display[["step", "time", "path"]].rename(columns={"path": "blue_path", "time": "blue_time"})\n',
    '            alpha_df = y.merge(b, on="step", how="inner")\n',
    '            if not alpha_df.empty:\n',
    '                alpha_df["alpha_diff_pips"] = (pd.to_numeric(alpha_df["yellow_path"], errors="coerce") - pd.to_numeric(alpha_df["blue_path"], errors="coerce")) * 10000.0\n',
    '                alpha_df["delta_point_pips"] = pd.to_numeric(alpha_df["alpha_diff_pips"], errors="coerce").diff().fillna(0.0)\n',
    '                alpha_df["abs_alpha"] = alpha_df["alpha_diff_pips"].abs()\n',
    '                alpha_df["abs_delta"] = alpha_df["delta_point_pips"].abs()\n',
    '                # Pick the strongest absolute alpha/delta candle-time points for vertical markers.\n',
    '                alpha_row = alpha_df.sort_values("abs_alpha", ascending=False).iloc[0]\n',
    '                delta_row = alpha_df.sort_values("abs_delta", ascending=False).iloc[0]\n',
    '                alpha_label = f"H+{int(alpha_row.get(\'step\', 0))} / {float(alpha_row.get(\'alpha_diff_pips\', 0)):.1f} pips"\n',
    '                delta_label = f"H+{int(delta_row.get(\'step\', 0))} / {float(delta_row.get(\'delta_point_pips\', 0)):.1f}"\n',
    '                st.session_state["lunch_red_chart_alpha_20260615"] = alpha_df\n',
    '\n',
    '        meta = _regime_meta_for_red_chart_v20260615()\n',
    '        meta_error = meta.get("avg_error_pct")\n',
    '        err = float(meta_error) if meta_error is not None else None\n',
    '        calibration_summary = calibration.get("summary", {}) if isinstance(calibration, dict) else {}\n',
    '        reliability = float(calibration_summary.get("reliability_pct", meta.get("reliability", reliability)) or 0)\n',
    '        meta_acc = calibration_summary.get("direction_accuracy_pct", meta.get("direction_accuracy_pct"))\n',
    '        if meta_acc is not None:\n',
    '            acc = _num(meta_acc, acc)\n',
    '        m = st.columns(7)\n',
    '        m[0].metric("Current Regime", meta.get("current_regime", "-"), meta.get("regime_validation", "FALSE / WATCH"))\n',
    '        m[1].metric("Regime Start", meta.get("regime_start_display", "Not recorded"))\n',
    '        m[2].metric("Regime End", meta.get("regime_end_display", "OPEN / CURRENT"))\n',
    '        m[3].metric("Path Reliability", f"{reliability:.1f}%", f"Agreement {float(calibration_summary.get(\'path_agreement_pct\', 0) or 0):.1f}%")\n',
    '        calibrated_error = calibration_summary.get("median_abs_error_pct")\n',
    '        if calibrated_error is not None:\n',
    '            err = float(calibrated_error)\n',
    '        error_proxy = bool(calibration_summary.get("error_is_proxy", meta.get("error_is_proxy")))\n',
    '        error_samples = int(calibration_summary.get("error_samples", meta.get("error_samples", 0)) or 0)\n',
    '        m[4].metric("Avg Error (Proxy)" if error_proxy else "Avg Error", f"{err:.5f}%" if err is not None else "N/A", f"{error_samples} samples • {\'proxy\' if error_proxy else \'actual\'}" if err is not None else "Run prediction-vs-actual backtest")\n',
    '        m[5].metric("Alpha Point", alpha_label)\n',
    '        m[6].metric("Delta Point", delta_label)\n',
    '        latest_red = calibrated_main.iloc[-1] if isinstance(calibrated_main, pd.DataFrame) and not calibrated_main.empty else pd.Series(dtype=object)\n',
    '        bounds = st.columns(4)\n',
    '        bounds[0].metric("Lower Bound", f"{float(latest_red.get(\'lower_band\', 0) or 0):.5f}" if not latest_red.empty else "N/A")\n',
]
