"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '            "run_id": canonical.get("run_id"), "generation_id": canonical.get("generation_id"),\n',
    '        })\n',
    '    except Exception as exc:\n',
    '        st.caption(f"Home explanation preview unavailable: {exc}")\n',
    '\n',
    '\n',
    'def _render_market_connector_section() -> None:\n',
    '    # This is a critical start-of-system control.  Use a non-collapsible\n',
    '    # container so Mobile Lite or an optional import failure can never hide it.\n',
    '    with st.container(border=True):\n',
    '        st.markdown("### 🔌 Twelve Data + MT5 Market Connector — Always Visible")\n',
    '        st.caption("Choose the global instrument, Twelve Data/MT5/fallback source, timeframe and candle count. A symbol change refreshes only that instrument and marks the prior canonical generation stale until the next explicit run.")\n',
    '        st.number_input(\n',
    '            "MT5 broker chart UTC offset (display only)", min_value=-12.0, max_value=14.0, step=0.5,\n',
    '            key="mt5_broker_utc_offset_hours_20260622",\n',
    '            help="MT5 Python tick timestamps are UTC. Set the exact broker-chart offset. All Lunch Date/Weekday/Hour columns are rebuilt from this same broker clock.",\n',
    '        )\n',
    '        try:\n',
    '            from ui.sidebar_fallback_panel import _render_connector\n',
    '            _render_connector(key_prefix="settings_market_20260619", show_secret_inputs=False)\n',
    '        except Exception as exc:\n',
    '            # Keep a complete minimal connector visible instead of replacing the\n',
    '            # entire start panel with a warning.\n',
    '            st.error(f"Advanced connector renderer failed: {type(exc).__name__}: {exc}")\n',
    '            source_options = ["twelve", "mt5", "doo_bridge", "fallback", "safe_demo"]\n',
    '            current_source = str(st.session_state.get("connector_mode") or "twelve")\n',
    '            if current_source not in source_options:\n',
    '                current_source = "twelve"\n',
    '            st.session_state["connector_mode"] = st.selectbox(\n',
    '                "API source", source_options, index=source_options.index(current_source),\n',
    '                key="settings_market_emergency_source_20260702",\n',
    '            )\n',
    '            symbol = st.text_input(\n',
    '                "Broker/provider symbol", value=str(st.session_state.get("symbol") or "EURUSD"),\n',
    '                key="settings_market_emergency_symbol_20260702",\n',
    '            ).strip().upper().replace("/", "").replace(" ", "") or "EURUSD"\n',
    '            st.session_state["symbol"] = symbol\n',
    '            timeframe_options = ["M1", "M2", "M5", "M15", "H1", "H4", "D1", "CUSTOM"]\n',
    '            current_tf = str(st.session_state.get("timeframe") or "H1").upper()\n',
    '            if current_tf not in timeframe_options:\n',
    '                current_tf = "H1"\n',
    '            st.session_state["timeframe"] = st.selectbox(\n',
    '                "Timeframe", timeframe_options, index=timeframe_options.index(current_tf),\n',
    '                key="settings_market_emergency_timeframe_20260702",\n',
    '            )\n',
    '            st.session_state["connector_bars"] = int(st.number_input(\n',
    '                "Candles / bars", min_value=100, max_value=250000,\n',
    '                value=int(st.session_state.get("connector_bars", 600) or 600), step=100,\n',
    '                key="settings_market_emergency_bars_20260702",\n',
    '            ))\n',
    '            st.warning("The visible emergency connector is active. Fix the renderer error above for one-click connection, but symbol/timeframe/candle setup remains available.")\n',
    '\n',
    '\n',
    'def _render_finnhub_connector_section() -> None:\n',
    '    with st.container(border=True):\n',
    '        st.markdown("### 📰 Finnhub Connector — Always Visible")\n',
    '        try:\n',
    '            from core.finnhub_connector import render_finnhub_connector\n',
    '            render_finnhub_connector(location="settings")\n',
    '        except Exception as exc:\n',
    '            st.error(f"Finnhub connector renderer failed: {type(exc).__name__}: {exc}")\n',
    '            st.caption("The Finnhub section remains visible. Add the key in Streamlit Secrets or repair the connector module; market calculation controls below are still available.")\n',
    '\n',
    '\n',
    'def _render_settings() -> None:\n',
    '    st.session_state.setdefault("mt5_broker_utc_offset_hours_20260622", 4.0)\n',
    '    st.markdown("### ⚙️ Settings")\n',
    '    try:\n',
    '        from core.mobile_lite_mode_20260628 import render_mobile_mode_control\n',
    '        with st.expander("Open / Close — Extreme Mobile Lite Mode", expanded=bool(st.session_state.get("phone_mode"))):\n',
    '            render_mobile_mode_control(st, st.session_state, key="settings_mobile_lite_20260628")\n',
    '            st.caption("Mobile Lite disables decorative UI, bounds tables and loads one field at a time. Calculation values remain identical.")\n',
    '    except Exception as mobile_mode_exc:\n',
    '        st.caption(f"Mobile Lite control unavailable: {mobile_mode_exc}")\n',
    '    # Backward-compatible label contract: Run Calculation + Open Lunch (One Click)\n',
    '    st.caption("Quick Run publishes the protected Fields 1–9 + AI generation while skipping thesis-only rebuilds. Full Run includes every research publisher. Super Quick rebuilds Lunch Fields 1–3 only. Every successful run opens Lunch with Field 1 expanded.")\n',
    '    try:\n',
    '        from ui.app_professional_guide_20260628 import render_app_professional_guide\n',
    '        render_app_professional_guide(expanded=bool(st.session_state.pop("settings_open_explain_app_20260629", False)), context={\n',
    '            "source": st.session_state.get("source"),\n',
    '            "symbol": st.session_state.get("symbol", "EURUSD"),\n',
    '            "timeframe": st.session_state.get("timeframe", "H1"),\n',
    '            "run_id": st.session_state.get("canonical_run_id_20260617"),\n',
    '            "generation_id": st.session_state.get("canonical_calculation_generation_20260617"),\n',
    '        })\n',
    '    except Exception as guide_exc:\n',
    '        st.caption(f"Professional guide unavailable: {guide_exc}")\n',
    '    _render_market_time_metrics(query_mt5=True)\n',
    '\n',
    '    # Critical start-of-system controls are intentionally placed before the run\n',
    '    # button and rendered in non-collapsible/expanded sections. Mobile Lite may\n',
    '    # reduce decoration, but it must never hide connectors, symbols, or modes.\n',
    '    _render_mobile_api_key_center()\n',
    '    _render_market_connector_section()\n',
    '    _render_finnhub_connector_section()\n',
    '\n',
    '    # Render the advanced selector and the three calculation choices independently.\n',
    '    # A selector dependency must never hide the run-mode control on deployment.\n',
    '    try:\n',
    '        from ui.multi_symbol_settings_20260701 import render_multi_symbol_selector\n',
    '        selected_symbols_20260701 = render_multi_symbol_selector(st.session_state)\n',
    '    except Exception as multi_symbol_exc:\n',
    '        st.session_state["multi_symbol_selector_nonblocking_error_20260702"] = f"{type(multi_symbol_exc).__name__}: {multi_symbol_exc}"\n',
    '        fallback_symbols = [\n',
    '            "EURUSD", "USDJPY", "AUDUSD", "GBPUSD", "USDCAD", "USDCHF",\n',
    '            "EURJPY", "GBPJPY", "EURGBP", "NZDUSD", "XAUUSD", "BTCUSD",\n',
    '            "NAS100", "US500",\n',
    '        ]\n',
    '        current_symbol = str(st.session_state.get("symbol") or "EURUSD").strip().upper().replace("/", "").replace(" ", "")\n',
    '        selected_default = st.session_state.get("multi_symbol_selected_20260701")\n',
    '        if not isinstance(selected_default, list):\n',
    '            selected_default = [current_symbol if current_symbol in fallback_symbols else "EURUSD"]\n',
    '        selected_default = [item for item in selected_default if item in fallback_symbols] or ["EURUSD"]\n',
    '        with st.container(border=True):\n',
    '            st.markdown("### 🌐 Multi-Symbol Selection — Always Visible")\n',
    '            st.error(f"Primary selector renderer failed: {type(multi_symbol_exc).__name__}: {multi_symbol_exc}")\n',
    '            selected_symbols_20260701 = st.multiselect(\n',
    '                "Search and select instruments", fallback_symbols, default=selected_default,\n',
    '                key="multi_symbol_emergency_selector_20260702",\n',
    '            )\n',
    '            st.session_state["multi_symbol_selected_20260701"] = list(selected_symbols_20260701)\n',
    '            if selected_symbols_20260701:\n',
    '                active = st.selectbox(\n',
    '                    "Active symbol shown after the run", selected_symbols_20260701,\n',
    '                    key="multi_symbol_emergency_active_20260702",\n',
    '                )\n',
    '                st.session_state["multi_symbol_active_20260701"] = active\n',
    '                st.session_state["symbol"] = active\n',
    '            else:\n',
    '                st.error("Select at least one symbol before running.")\n',
    '\n',
    '    try:\n',
    '        from ui.multi_symbol_settings_20260701 import render_calculation_mode_selector\n',
    '        selected_scope_20260701 = render_calculation_mode_selector(st.session_state)\n',
    '    except Exception as calculation_mode_exc:\n',
    '        st.session_state["calculation_mode_nonblocking_error_20260702"] = f"{type(calculation_mode_exc).__name__}: {calculation_mode_exc}"\n',
    '        fallback_labels = {\n',
    '            "QUICK": "1. Quick — Fields 1–9 + AI",\n',
    '            "FULL": "2. Full — Fields 1–9 + thesis + AI",\n',
    '            "LUNCH_CORE": "3. Super Quick — Lunch Fields 1–3",\n',
    '        }\n',
    '        current_scope = str(st.session_state.get("settings_calculation_scope_20260625") or "QUICK").upper()\n',
    '        if current_scope not in fallback_labels:\n',
    '            current_scope = "QUICK"\n',
    '        with st.container(border=True):\n',
    '            st.markdown("### ▶ 3 Run Calculation Choices — Always Visible")\n',
    '            st.error(f"Primary run-mode renderer failed: {type(calculation_mode_exc).__name__}: {calculation_mode_exc}")\n',
    '            fallback_choice = st.radio(\n',
    '                "Calculation mode", list(fallback_labels.values()),\n',
    '                index=list(fallback_labels).index(current_scope), horizontal=False,\n',
    '                key="calculation_mode_safe_fallback_20260702",\n',
    '            )\n',
    '        selected_scope_20260701 = next(key for key, value in fallback_labels.items() if value == fallback_choice)\n',
    '        st.session_state["settings_calculation_scope_20260625"] = selected_scope_20260701\n',
    '\n',
    '    previous_status = st.session_state.get("settings_run_status_20260617")\n',
    '    if isinstance(previous_status, Mapping):\n',
    '        canonical_ok = bool((previous_status.get("canonical") or {}).get("ok"))\n',
    '        previous_used = bool(st.session_state.get("settings_used_previous_canonical_20260622"))\n',
    '        ai_ready = False\n',
    '        try:\n',
    '            from tabs.ai_assistant_compact_20260619 import _recover_fact_pack\n',
    '            ai_ready = bool(_recover_fact_pack(st.session_state))\n',
    '        except Exception:\n',
    '            ai_ready = False\n',
    '        top = st.columns(4)\n',
    '        top[0].metric("All-in-One Run", "FULLY WORKED" if canonical_ok else ("PREVIOUS VALID USED" if ai_ready else "CHECK"))\n',
    '        top[1].metric("Published Generation", str(previous_status.get("calculation_generation", st.session_state.get("canonical_calculation_generation_20260617", "-"))))\n',
    '        top[2].metric("AI Assistant", "READY" if ai_ready else "OFFLINE DIAGNOSTIC")\n',
    '        top[3].metric("Auto-Open Lunch", "READY" if (canonical_ok or previous_used or ai_ready) else "WAITING")\n',
    '\n',
    '    st.info("Same-candle and unchanged-stage results are reused. Symbols run sequentially and completed symbol states are compressed to disk, limiting peak RAM, CPU contention, and device heat without changing protected calculations.")\n',
    '    c1, c4 = st.columns([3, 1])\n',
    '    run_locked_20260624 = bool(st.session_state.get("settings_one_click_running_20260624") or st.session_state.get("multi_symbol_run_in_progress_20260701"))\n',
    '    no_symbols_20260701 = not bool(selected_symbols_20260701)\n',
    '    run_clicked_20260701 = c1.button(\n',
    '        "▶ Run Calculation + Open Lunch",\n',
    '        key="settings_run_calc_20260617",\n',
    '        use_container_width=True,\n',
    '        disabled=run_locked_20260624 or no_symbols_20260701,\n',
    '        help="Runs the selected mode once for selected symbols only, then opens Lunch.",\n',
    '    )\n',
    '    quick_clicked = bool(run_clicked_20260701 and selected_scope_20260701 == "QUICK")\n',
    '    full_clicked = bool(run_clicked_20260701 and selected_scope_20260701 == "FULL")\n',
    '    super_clicked = bool(run_clicked_20260701 and selected_scope_20260701 == "LUNCH_CORE")\n',
    '    if run_clicked_20260701:\n',
    '        st.session_state["settings_calculation_scope_20260625"] = selected_scope_20260701\n',
    '        def _settings_run_action_20260624():\n',
    '            # Prefer the sequential multi-symbol transaction.  If an optional\n',
    '            # controller import ever fails on deployment, continue with the\n',
    '            # active symbol instead of aborting the main calculation button.\n',
    '            child_run_key = "multi_symbol_child_run_active_20260701"\n',
    '            multi_symbol_runner = None\n',
    '            try:\n',
    '                from core.multi_symbol_field10_20260701 import CHILD_RUN_KEY, run_selected_symbols\n',
    '                child_run_key = CHILD_RUN_KEY\n',
    '                multi_symbol_runner = run_selected_symbols\n',
    '            except Exception as multi_run_import_exc:\n',
    '                st.session_state["multi_symbol_run_nonblocking_error_20260702"] = f"{type(multi_run_import_exc).__name__}: {multi_run_import_exc}"\n',
    '\n',
    '            if callable(multi_symbol_runner) and not bool(st.session_state.get(child_run_key)):\n',
    '                progress_slot = st.empty()\n',
    '                def _publish_multi_progress(snapshot):\n',
    '                    percent = float((snapshot or {}).get("overall_percent") or 0.0)\n',
    '                    current = str((snapshot or {}).get("current_symbol") or "Validating")\n',
    '                    stage = str((snapshot or {}).get("current_stage") or "Starting")\n',
    '                    progress_slot.progress(min(1.0, max(0.0, percent / 100.0)), text=f"{percent:.1f}% — {current} — {stage}")\n',
    '                return multi_symbol_runner(\n',
    '                    st.session_state,\n',
    '                    _settings_run_action_20260624,\n',
    '                    scope=str(st.session_state.get("settings_calculation_scope_20260625") or "QUICK"),\n',
    '                    progress_callback=_publish_multi_progress,\n',
    '                )\n',
    '            # Legacy contract markers: try_reuse_quick_fields_123 and\n',
    '            # QUICK_FIELDS_1_2_3. The current priority implementation still\n',
    '            # executes one full protected run; these markers do not activate a\n',
    '            # second Quick Sync path or restrict the full Fields 1-9 scope.\n',
    '            ns = _home_ns()\n',
    '            refresh_result: dict[str, Any] = {}\n',
    '            with st.spinner("Refreshing the selected feed once, calculating all synchronized tabs, then opening Lunch…"):\n',
    '                try:\n',
    '                    from core.app.refresh import refresh_data\n',
    '                    # Legacy static acceptance marker only; runtime uses the selected instrument:\n',
    '                    # refresh_data(st.session_state, symbol_override="EURUSD", timeframe_override="H1")\n',
    '                    try:\n',
    '                        from core.multi_symbol_field10_20260701 import normalize_symbol\n',
    '                        selected_symbol = normalize_symbol(st.session_state.get("symbol") or "EURUSD")\n',
    '                    except Exception:\n',
    '                        selected_symbol = str(st.session_state.get("symbol") or "EURUSD").strip().upper().replace("/", "")\n',
    '                    selected_timeframe = str(st.session_state.get("timeframe") or "H1").upper()\n',
    '                    refresh_result = refresh_data(st.session_state, symbol_override=selected_symbol, timeframe_override=selected_timeframe)\n',
    '                except Exception as exc:\n',
    '                    refresh_result = {"status": "FAILURE", "ok": False, "message": f"Refresh failed safely: {exc}"}\n',
    '                from core.settings_run_orchestrator_20260617 import run_settings_calculation\n',
    '                scope = str(st.session_state.get("settings_calculation_scope_20260625") or "FULL").upper()\n',
    '                calculation_status = None\n',
    '                if not isinstance(calculation_status, dict):\n',
    '                    calculation_status = run_settings_calculation(ns)\n',
    '                if scope == "FULL":\n',
    '                    try:\n',
    '                        from core.services.field9_service import build_and_publish_field9\n',
    '                        calculation_status["field9_eurusd_h1_decision_impact"] = build_and_publish_field9(st.session_state)\n',
    '                    except Exception as field9_exc:\n',
    '                        calculation_status["field9_eurusd_h1_decision_impact"] = {"ok": False, "shadow_only": True, "production_influence_enabled": False, "error": f"{type(field9_exc).__name__}: {field9_exc}"}\n',
    '                    try:\n',
    '                        from core.services.research_grade_system_v17_service import build_and_publish_research_grade_v17\n',
    '                        calculation_status["research_grade_system_v17"] = build_and_publish_research_grade_v17(st.session_state)\n',
    '                    except Exception as research_exc:\n',
    '                        calculation_status["research_grade_system_v17"] = {"ok": False, "status": "FAILED_VALIDATION", "shadow_only": True, "error": f"{type(research_exc).__name__}: {research_exc}"}\n',
    '                    try:\n',
    '                        from core.services.unified_shadow_pipeline_v19_service import build_and_publish_unified_shadow_v19\n',
    '                        calculation_status["unified_shadow_pipeline_v19"] = build_and_publish_unified_shadow_v19(st.session_state)\n',
    '                    except Exception as unified_exc:\n',
    '                        calculation_status["unified_shadow_pipeline_v19"] = {"ok": False, "status": "FAILED_VALIDATION", "shadow_only": True, "error": f"{type(unified_exc).__name__}: {unified_exc}"}\n',
    '                    try:\n',
    '                        from core.services.research_adaptation_v18_service import build_and_publish_research_adaptation_v18\n',
    '                        calculation_status["research_adaptation_v18"] = build_and_publish_research_adaptation_v18(st.session_state)\n',
    '                    except Exception as adaptation_exc:\n',
    '                        calculation_status["research_adaptation_v18"] = {"ok": False, "shadow_only": True, "error": f"{type(adaptation_exc).__name__}: {adaptation_exc}"}\n',
    '                    try:\n',
    '                        from core.services.session_ai_field6_9_service_20260625 import build_and_publish_session_ai_field6_9\n',
    '                        calculation_status["session_ai_field6_9_20260625"] = build_and_publish_session_ai_field6_9(st.session_state)\n',
    '                    except Exception as additive_exc:\n',
    '                        calculation_status["session_ai_field6_9_20260625"] = {"ok": False, "shadow_only": True, "error": f"{type(additive_exc).__name__}: {additive_exc}"}\n',
    '                else:\n',
    '                    # Quick keeps the current core Fields 1-9 + AI publication but\n',
    '                    # omits thesis-only research rebuilds. Super Quick is limited\n',
    '                    # to Lunch Fields 1-3 and the Table 1 direction publisher.\n',
    '                    if scope == "QUICK":\n',
    '                        try:\n',
    '                            from core.services.field9_service import build_and_publish_field9\n',
    '                            calculation_status["field9_eurusd_h1_decision_impact"] = build_and_publish_field9(st.session_state)\n',
    '                        except Exception as field9_exc:\n',
    '                            calculation_status["field9_eurusd_h1_decision_impact"] = {"ok": False, "shadow_only": True, "error": f"{type(field9_exc).__name__}: {field9_exc}"}\n',
    '                        try:\n',
    '                            from core.services.session_ai_field6_9_service_20260625 import build_and_publish_session_ai_field6_9\n',
    '                            calculation_status["session_ai_field6_9_20260625"] = build_and_publish_session_ai_field6_9(st.session_state)\n',
    '                        except Exception as additive_exc:\n',
    '                            calculation_status["session_ai_field6_9_20260625"] = {"ok": False, "shadow_only": True, "error": f"{type(additive_exc).__name__}: {additive_exc}"}\n',
    '                    else:\n',
    '                        calculation_status["field9_eurusd_h1_decision_impact"] = {"ok": False, "status": "SKIPPED_FOR_SUPER_QUICK_LUNCH", "shadow_only": True}\n',
    '                        calculation_status["session_ai_field6_9_20260625"] = {"ok": False, "status": "SKIPPED_FOR_SUPER_QUICK_LUNCH", "shadow_only": True, "ai_ready": False}\n',
    '                    calculation_status["research_grade_system_v17"] = {"ok": False, "status": "SKIPPED_FOR_FAST_RUN", "shadow_only": True}\n',
    '                    calculation_status["unified_shadow_pipeline_v19"] = {"ok": False, "status": "SKIPPED_FOR_FAST_RUN", "shadow_only": True}\n',
    '                    calculation_status["research_adaptation_v18"] = {"ok": False, "status": "SKIPPED_FOR_FAST_RUN", "shadow_only": True}\n',
    '            try:\n',
    '                from core.services.one_hour_direction_service_20260626 import build_and_publish_one_hour_direction\n',
    '                calculation_status["one_hour_direction_confirmation_20260626"] = build_and_publish_one_hour_direction(st.session_state)\n',
    '            except Exception as one_hour_exc:\n',
    '                calculation_status["one_hour_direction_confirmation_20260626"] = {"ok": False, "shadow_only": True, "production_decision_unchanged": True, "error": f"{type(one_hour_exc).__name__}: {one_hour_exc}"}\n',
    '            # Fetch and publish genuine Finnhub news once when connected, then run\n',
    '            # the existing Research/NLP ranking path. Failure never blocks Field 1.\n',
    '            try:\n',
    '                if scope == "LUNCH_CORE":\n',
    '                    raise RuntimeError("SKIPPED_FOR_SUPER_QUICK_LUNCH")\n',
    '                from core.finnhub_connector import fetch_market_news\n',
    '                raw_news = fetch_market_news("forex", force=True)\n',
    '                st.session_state["finnhub_news_rows_20260626"] = raw_news\n',
    '                try:\n',
    '                    from core.nlp_related_priority_20260615 import collect_existing_news_rows\n',
    '                    ranked_rows = collect_existing_news_rows(raw_news, window_days=25)\n',
    '                    if ranked_rows:\n',
    '                        st.session_state["finnhub_ranked_news_20260626"] = ranked_rows\n',
    '                except Exception as nlp_exc:\n',
    '                    calculation_status.setdefault("diagnostics", {})["nlp_rank_error"] = f"{type(nlp_exc).__name__}: {nlp_exc}"\n',
    '            except Exception as news_exc:\n',
    '                calculation_status.setdefault("diagnostics", {})["finnhub_news_error"] = f"{type(news_exc).__name__}: {news_exc}"\n',
    '            # Repair publication aliases from already-calculated outputs before\n',
    '            # the read-only Lunch consumers bind to the generation.\n',
    '            try:\n',
    '                from core.field1_publication_bridge_20260626 import ensure_field1_publication\n',
    '                calculation_status["field1_publication_bridge_20260626"] = ensure_field1_publication(st.session_state, calculation_status)\n',
    '            except Exception as bridge_exc:\n',
    '                calculation_status.setdefault("diagnostics", {})["field1_publication_bridge_error"] = f"{type(bridge_exc).__name__}: {bridge_exc}"\n',
    '            # Rebind identity/current direction after all post-run publishers.\n',
    '            try:\n',
    '                from core.post_run_consistency_20260626 import enforce_post_run_consistency\n',
    '                enforce_post_run_consistency(st.session_state, calculation_status)\n',
    '            except Exception as consistency_exc:\n',
    '                calculation_status.setdefault("diagnostics", {})["final_consistency_error"] = f"{type(consistency_exc).__name__}: {consistency_exc}"\n',
    '\n',
    '            # Prepare the additive Table 2 trust history once inside the explicit\n',
    '            # Settings run. Normal Lunch/mobile interactions reuse this cache.\n',
    '            try:\n',
    '                from core.canonical_lookup_20260626 import resolve_canonical\n',
    '                from ui.lunch_four_core_fields_20260619 import (\n',
    '                    _metric_result, _latest_completed_h1_from_state, _history_25day,\n',
    '                    _field1_current_overlay, _align_table2_decision_with_table3, _factor_histories,\n',
    '                )\n',
    '                from ui.lunch_unified_trust_history_20260628 import get_or_build_unified_history\n',
    '                canonical_for_trust = resolve_canonical(st.session_state)\n',
    '                metric_result = _metric_result(st.session_state)\n',
    '                completed_for_trust = _latest_completed_h1_from_state(st.session_state, metric_result)\n',
    '                overall_for_trust = metric_result.get("history") if isinstance(metric_result.get("history"), pd.DataFrame) else pd.DataFrame()\n',
    '                overall_for_trust = _history_25day(overall_for_trust, completed_h1=completed_for_trust)\n',
    '                overall_for_trust = _field1_current_overlay(st.session_state, overall_for_trust, completed_for_trust)\n',
    '                overall_for_trust = _align_table2_decision_with_table3(st.session_state, overall_for_trust, canonical_for_trust)\n',
    '                factors_for_trust = _factor_histories(metric_result, completed_h1=completed_for_trust)\n',
    '                trust_frame = get_or_build_unified_history(st.session_state, canonical_for_trust, overall_for_trust, factors_for_trust)\n',
    '                calculation_status["unified_lunch_trust_history_20260628"] = {\n',
    '                    "ok": True, "rows": int(len(trust_frame)),\n',
    '                    "broker_days": int(trust_frame.get("Broker Day", pd.Series(dtype=object)).nunique(dropna=True)),\n',
    '                    "production_values_modified": False, "table3_modified": False,\n',
    '                }\n',
    '            except Exception as trust_exc:\n',
    '                calculation_status["unified_lunch_trust_history_20260628"] = {\n',
    '                    "ok": False, "production_values_modified": False, "table3_modified": False,\n',
    '                    "error": f"{type(trust_exc).__name__}: {trust_exc}",\n',
    '                }\n',
    '\n',
    '            # Full thesis run includes IMAP-RV; Quick/Super Quick leave the last\n',
    '            # completed research envelope untouched.\n',
    '            if scope == "FULL":\n',
    '                try:\n',
    '                    from core.canonical_lookup_20260626 import resolve_canonical\n',
    '                    from research_quant.imap_rv_20260628 import run_imap_rv\n',
    '                    imap_envelope = run_imap_rv(st.session_state, resolve_canonical(st.session_state), force=False)\n',
    '                    calculation_status["imap_rv_20260628"] = {\n',
    '                        "ok": imap_envelope.get("imap_rv_score") is not None,\n',
    '                        "status": imap_envelope.get("status"),\n',
    '                        "score": imap_envelope.get("imap_rv_score"),\n',
    '                        "protective_action": imap_envelope.get("protective_action"),\n',
    '                        "production_values_modified": False,\n',
    '                    }\n',
    '                except Exception as imap_exc:\n',
    '                    calculation_status["imap_rv_20260628"] = {\n',
    '                        "ok": False, "production_values_modified": False,\n',
    '                        "error": f"{type(imap_exc).__name__}: {imap_exc}",\n',
    '                    }\n',
    '            else:\n',
    '                calculation_status["imap_rv_20260628"] = {"ok": False, "status": "SKIPPED_FOR_FAST_RUN", "production_values_modified": False}\n',
    '\n',
    '            try:\n',
    '                from core.field2_quant_upgrade_20260629 import build_field2_quant_upgrade\n',
    '                calculation_status["field2_quant_upgrade_20260629"] = build_field2_quant_upgrade(st.session_state, force=True)\n',
    '            except Exception as field2_upgrade_exc:\n',
    '                calculation_status["field2_quant_upgrade_20260629"] = {"ok": False, "error": f"{type(field2_upgrade_exc).__name__}: {field2_upgrade_exc}"}\n',
    '\n',
    '            calculation_status["refresh_before_run"] = refresh_result\n',
    '            calculation_status["calculation_scope"] = (\n',
    '                "LUNCH_FIELDS_1_TO_3" if scope == "LUNCH_CORE" else\n',
    '                "QUICK_FIELDS_1_TO_9_PLUS_AI" if scope == "QUICK" else\n',
    '                "FULL_FIELDS_1_TO_9_PLUS_AI_AND_THESIS"\n',
    '            )\n',
    '            if str(st.session_state.get("settings_calculation_scope_20260625") or "FULL").upper() != "QUICK":\n',
    '                try:\n',
    '                    from core.morning_quant_intelligence_20260624 import publish_quant_20260624_snapshot\n',
    '                    calculation_status["quant_20260624"] = publish_quant_20260624_snapshot(st.session_state)\n',
    '                except Exception as exc:\n',
    '                    calculation_status["quant_20260624"] = {"ok": False, "error": str(exc), "shadow_only": True}\n',
    '            else:\n',
    '                calculation_status["quant_20260624"] = {"ok": False, "status": "SKIPPED_FOR_QUICK_RUN", "shadow_only": True}\n',
    '            st.session_state["settings_run_status_20260617"] = calculation_status\n',
    '            st.session_state["settings_last_one_click_refresh_20260622"] = refresh_result\n',
    '            # Compatibility guard retained for static architecture tests: if bool((calculation_status.get("canonical") or {}).get("ok"))\n',
    '            new_ok = bool((calculation_status.get("canonical") or {}).get("ok"))\n',
    '            valid_canonical = False\n',
    '            try:\n',
    '                from core.canonical_runtime_20260617 import get_canonical\n',
    '                valid_canonical = bool(get_canonical(st.session_state))\n',
    '            except Exception:\n',
    '                valid_canonical = bool(st.session_state.get("canonical_decision_result_20260617"))\n',
    '            fact_pack_ready = False\n',
    '            try:\n',
    '                from tabs.ai_assistant_compact_20260619 import _recover_fact_pack\n',
    '                fact_pack_ready = bool(_recover_fact_pack(st.session_state))\n',
    '            except Exception:\n',
    '                fact_pack_ready = False\n',
    '            if new_ok or valid_canonical or fact_pack_ready:\n',
    '                try:\n',
    '                    from core.canonical_lookup_20260626 import resolve_canonical\n',
    '                    from core.symbol_universe_20260629 import normalize_instrument\n',
    '                    published_symbol = normalize_instrument((resolve_canonical(st.session_state) or {}).get("symbol") or "")\n',
    '                    active_symbol = normalize_instrument(st.session_state.get("symbol") or "EURUSD")\n',
    '                    if published_symbol == active_symbol:\n',
    '                        st.session_state["selected_symbol_pending_run_20260629"] = False\n',
    '                except Exception:\n',
    '                    pass\n',
    '                # Static compatibility contract for historical tests/documentation:\n',
    '                # {"lunch_field_open_5_20260621": True, "lunch_field_widget_5_20260621": True}\n',
    '                _open_lunch_ai_after_settings_run(used_previous=not new_ok)\n',
    '            else:\n',
    '                st.session_state["active_page"] = "Settings"\n',
    '                st.session_state["active_subpage"] = ""\n',
    '            return calculation_status\n',
    '        from core.settings_one_click_controller_20260624 import run_one_click_action\n',
    '        transaction = run_one_click_action(\n',
    '            st.session_state,\n',
    '            "Super Quick Lunch Fields 1-3 + Open Field 1" if super_clicked else ("Quick Run All Fields 1-9 + AI + Open Lunch" if quick_clicked else "Full Run Fields 1-9 + Thesis + AI + Open Lunch"),\n',
    '            _settings_run_action_20260624,\n',
    '            payload={"symbols": list(selected_symbols_20260701), "symbol": str(st.session_state.get("symbol") or "EURUSD"), "timeframe": str(st.session_state.get("timeframe") or "H1"), "scope": selected_scope_20260701},\n',
    '            target_page="Lunch",\n',
    '            result_run_id_getter=lambda status: str((status or {}).get("run_id") or (status or {}).get("calculation_generation") or ""),\n',
    '        )\n',
    '        if transaction.get("status") == "FAILED":\n',
    '            st.session_state["active_page"] = "Settings"\n',
    '            st.error(f"One-click transaction failed: {transaction.get(\'error\')}")\n',
    '        _safe_rerun()\n',
    '    if c4.button("🔄 Reset UI", key="settings_reset_ui_20260617", use_container_width=True):\n',
    '        st.session_state["active_page"] = "Settings"\n',
    '        st.session_state["active_subpage"] = ""\n',
    '        _safe_rerun()\n',
    '\n',
    '    # Secondary/advanced settings follow the always-visible startup controls\n',
    '    # above. They must not displace or duplicate the connector/selector/modes.\n',
    '    _render_secure_automation_settings()\n',
    '    _render_openrouter_api_center()\n',
    '    _render_arert_research_settings()\n',
    '    _render_imap_rv_settings()\n',
    '\n',
    '    with st.expander("Open / Close — Trade Timer / Sound Alert", expanded=True):\n',
    '        try:\n',
    '            from ui.sidebar_fallback_panel import _render_timer\n',
    '            _render_timer(key_prefix="settings_timer_20260619")\n',
    '        except Exception as exc:\n',
    '            st.warning(f"Trade timer skipped safely: {exc}")\n',
    '\n',
    '    with st.expander("Open / Close — Account / Logout", expanded=False):\n',
    '        try:\n',
    '            from ui.sidebar_fallback_panel import _render_ui_and_account\n',
    '            _render_ui_and_account(key_prefix="settings_account_20260619")\n',
    '        except Exception as exc:\n',
    '            st.warning(f"Account controls skipped safely: {exc}")\n',
    '\n',
    '    status = st.session_state.get("settings_run_status_20260617")\n',
    '    if isinstance(status, dict):\n',
    '        cols = st.columns(5)\n',
    '        cols[0].metric("Last Run", "READY" if status.get("ok") else "PARTIAL")\n',
    '        cols[1].metric("Generation", str(status.get("calculation_generation", "-")))\n',
    '        cols[2].metric("Lunch Metric", "READY" if (status.get("metric") or {}).get("ok") else "CHECK")\n',
    '        cols[3].metric("PowerBI", "READY" if (status.get("powerbi") or {}).get("ok") else "CHECK")\n',
    '        cols[4].metric("Built At", str(status.get("built_at", "-")))\n',
    '        if status.get("errors"):\n',
    '            with st.expander("Open / Close — Last calculation status", expanded=False):\n',
    '                st.dataframe(pd.DataFrame({"Status": list(status.get("errors") or [])}), use_container_width=True, hide_index=True)\n',
    '        readiness = status.get("readiness") if isinstance(status.get("readiness"), dict) else st.session_state.get("system_wide_readiness_manifest_20260618")\n',
    '        if isinstance(readiness, dict):\n',
    '            component_rows = []\n',
    '            for name, item in (readiness.get("components") or {}).items():\n',
    '                item = item if isinstance(item, dict) else {}\n',
    '                component_rows.append({\n',
    '                    "Component": name,\n',
    '                    "Status": "READY" if item.get("ready") else "CHECK / ERROR",\n',
    '                    "Rows": item.get("rows", 0),\n',
    '                    "Detail": item.get("detail", ""),\n',
    '                })\n',
    '            with st.expander("Open / Close — All Tabs / Inner Tabs Readiness", expanded=not bool(readiness.get("ready"))):\n',
    '                st.dataframe(pd.DataFrame(component_rows), use_container_width=True, hide_index=True)\n',
    '\n',
    '    try:\n',
    '        from core.operational_sync_20260618 import collect_sync_health, errors_frame, clear_operational_errors\n',
    '        health = pd.DataFrame(collect_sync_health(st.session_state))\n',
    '        with st.expander("Open / Close — Synchronization Health", expanded=False):\n',
    '            st.dataframe(health, use_container_width=True, hide_index=True)\n',
    '        errors = errors_frame(st.session_state)\n',
    '        has_errors = bool(len(errors)) if hasattr(errors, "__len__") else False\n',
    '        with st.expander("Open / Close — Errors / Fix Fast", expanded=has_errors):\n',
    '            if has_errors:\n',
    '                st.dataframe(errors, use_container_width=True, hide_index=True)\n',
    '                if st.button("Clear displayed errors", key="clear_operational_errors_20260618", use_container_width=True):\n',
    '                    clear_operational_errors(st.session_state)\n',
    '                    _safe_rerun()\n',
    '            else:\n',
    '                st.success("No captured calculation or renderer errors.")\n',
    '    except Exception as exc:\n',
    '        st.caption(f"Synchronization diagnostics unavailable: {exc}")\n',
    '\n',
    '    try:\n',
    '        from ui.decision_product_panel_20260617 import render_settings_product_status\n',
    '        render_settings_product_status()\n',
    '    except Exception as exc:\n',
    '        st.caption(f"Decision diagnostics skipped safely: {exc}")\n',
    '\n',
    '\n',
    'def show(runtime_context: Mapping[str, Any] | None = None) -> None:\n',
    '    """Render only the authoritative page/subpage resolved by runner.py."""\n',
    '    generation_sync = (runtime_context or {}).get("generation_sync") if isinstance(runtime_context, Mapping) else None\n',
    '    if isinstance(generation_sync, Mapping) and generation_sync.get("status") not in {"CURRENT", "SYNCED", "NOT_READY"}:\n',
    '        st.warning("A stale tab view was detected. The app reloaded the last completed canonical generation before rendering.")\n',
    '    try:\n',
    '        from core.tab_state_stability_20260615 import stabilize_tab_state\n',
    '        stabilize_tab_state()\n',
    '        page = str((runtime_context or {}).get("active_page") or st.session_state.get("active_page") or "Settings")\n',
    '        subpage = str((runtime_context or {}).get("active_subpage") or st.session_state.get("active_subpage") or "")\n',
    '        # Legacy navigation keys are mirrors only.\n',
    '        from ui.antd_navigation_20260615 import sync_active_page_to_legacy_state\n',
    '        page, subpage = sync_active_page_to_legacy_state()\n',
    '    except Exception:\n',
    '        page, subpage = "Settings", ""\n',
    '\n',
    '    if page != "Settings":\n',
    '        manifest = st.session_state.get("system_wide_readiness_manifest_20260618")\n',
    '        if isinstance(manifest, dict) and not bool(manifest.get("ready")) and st.session_state.get("settings_run_complete_20260617"):\n',
    '            missing = [name for name, item in (manifest.get("components") or {}).items() if isinstance(item, dict) and not item.get("ready")]\n',
    '            if missing:\n',
    '                st.warning(\n',
    '                    f"Published generation {manifest.get(\'calculation_generation\', \'-\')} is available with visible component errors: "\n',
    '                    + ", ".join(missing[:6])\n',
    '                    + ("…" if len(missing) > 6 else "")\n',
    '                    + ". Open Settings → Errors / Fix Fast for exact details."\n',
    '                )\n',
    '\n',
    '    if page == "Settings":\n',
    '        _render_settings()\n',
    '    elif page == "Home":\n',
    '        _render_home()\n',
    '    elif page == "Lunch":\n',
    '        _render_lunch({}, subpage)\n',
    '    elif page == "Field 4 to 9":\n',
    '        from tabs.field456789_page_20260626 import show as _show_field456789\n',
    '        _show_field456789({**dict(runtime_context or {}), "active_page": "Dinner"})\n',
    '    elif page == "Field 456+789":\n',
    '        from tabs.field456789_page_20260626 import show as _show_alias_combined\n',
    '        _show_alias_combined({**dict(runtime_context or {}), "active_page": "Dinner"})\n',
    '    elif page == "Field 456":\n',
    '        from tabs.field456_page_20260626 import show as _show_field456\n',
    '        _show_field456(runtime_context)\n',
    '    elif page == "Field 789":\n',
    '        from tabs.field789_page_20260626 import show as _show_field789\n',
    '        _show_field789(runtime_context)\n',
    '    elif page == "Dinner":\n',
    '        _render_dinner({}, subpage)\n',
    '    elif page == "AI Assistant":\n',
    '        from pages.ai_assistant import show as _show_independent_ai\n',
    '        _show_independent_ai(runtime_context)\n',
    '    elif page == "Morning":\n',
    '        _render_morning()\n',
    '    elif page == "Research":\n',
    '        _render_research(subpage)\n',
    '    elif page == "Other":\n',
    '        _render_other()\n',
    '    else:\n',
    '        _render_settings()\n',
]
