"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Final synchronized page router (updated 2026-06-17).\n',
    '\n',
    'Only the selected top-level page and selected inner page are imported/rendered.\n',
    'All renderers consume the canonical runtime adapter already created by runner.py;\n',
    'none of them may trigger a second shared calculation during the same rerun.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from typing import Any, Mapping\n',
    '\n',
    'import pandas as pd\n',
    'import streamlit as st\n',
    '\n',
    '\n',
    'def _safe_rerun() -> None:\n',
    '    try:\n',
    '        st.rerun()\n',
    '    except Exception:\n',
    '        try:\n',
    '            st.experimental_rerun()\n',
    '        except Exception:\n',
    '            pass\n',
    '\n',
    '\n',
    'def _sync_shared(force: bool = False) -> dict:\n',
    '    """Compatibility name: read the already-published adapter, never rebuild it."""\n',
    '    del force\n',
    '    try:\n',
    '        from core.canonical_runtime_20260617 import shared_from_runtime\n',
    '        return shared_from_runtime(st.session_state)\n',
    '    except Exception:\n',
    '        value = st.session_state.get("adx_shared_calc_result_20260615") or st.session_state.get("shared_calc_result")\n',
    '        return value if isinstance(value, dict) else {}\n',
    '\n',
    '\n',
    'def _safe_component(label: str, fn, *args, **kwargs):\n',
    '    try:\n',
    '        if callable(fn):\n',
    '            return fn(*args, **kwargs)\n',
    '        st.dataframe(pd.DataFrame([{"Component": label, "Status": "Renderer unavailable"}]), use_container_width=True, hide_index=True)\n',
    '    except Exception as exc:\n',
    '        try:\n',
    '            from core.operational_sync_20260618 import record_operational_error\n',
    '            record_operational_error(st.session_state, label, exc, stage="render")\n',
    '        except Exception:\n',
    '            pass\n',
    '        st.warning(f"{label} skipped safely; remaining components are still available.")\n',
    '        with st.expander(f"Open / Close — {label} error", expanded=True):\n',
    '            st.code(str(exc))\n',
    '            st.caption("The error was added to Settings → Errors / Fix Fast.")\n',
    '    return None\n',
    '\n',
    '\n',
    'def _render_chatgpt_style_ai():\n',
    '    """Backward-compatible Dinner AI name, now backed by the compact fact pack."""\n',
    '    from tabs.ai_assistant_compact_20260619 import render_compact_ai_assistant\n',
    '    return render_compact_ai_assistant()\n',
    '\n',
    '\n',
    'def _home_ns() -> dict:\n',
    '    try:\n',
    '        import tabs.home as home\n',
    '        return home.__dict__\n',
    '    except Exception:\n',
    '        return {}\n',
    '\n',
    '\n',
    'def _prev_data(ns: dict):\n',
    '    return ns.get("_render_lunch_data_visualization_inner_tab")\n',
    '\n',
    '\n',
    'def _prev_morning(ns: dict):\n',
    '    return ns.get("_render_doo_prime_inner_tab")\n',
    '\n',
    '\n',
    'def _canonical_priority_table() -> pd.DataFrame:\n',
    '    table = st.session_state.get("canonical_priority_table_20260617")\n',
    '    if isinstance(table, pd.DataFrame) and not table.empty:\n',
    '        return table\n',
    '    try:\n',
    '        from core.canonical_runtime_20260617 import get_canonical\n',
    '        canonical = get_canonical(st.session_state)\n',
    '        records = canonical.get("priority_table") if isinstance(canonical, dict) else None\n',
    '        if isinstance(records, list) and records:\n',
    '            return pd.DataFrame.from_records(records)\n',
    '    except Exception:\n',
    '        pass\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _display_priority_table(table: pd.DataFrame, *, height: int = 440) -> None:\n',
    '    if table.empty:\n',
    '        try:\n',
    '            from core.system_wide_completion_20260618 import readiness_message\n',
    '            message = readiness_message(st.session_state, "Lunch Priority")\n',
    '        except Exception:\n',
    '            message = "The published priority table is unavailable. Open Settings → Errors / Fix Fast."\n',
    '        st.dataframe(pd.DataFrame([{"Status": message}]), use_container_width=True, hide_index=True)\n',
    '        return\n',
    '    phone = bool(st.session_state.get("phone_mode", False))\n',
    '    # Limit only the rendered view; the full canonical table remains cached.\n',
    '    display_rows = 48 if phone else 240\n',
    '    try:\n',
    '        from ui.table_ordering_20260618 import priority_view\n',
    '        show = priority_view(table, row_limit=display_rows)\n',
    '    except Exception:\n',
    '        # Safe fallback still keeps the highest ranked rows. Never use tail()\n',
    '        # after a descending sort because that exposes old backtest candles.\n',
    '        show = table.head(display_rows).reset_index(drop=True)\n',
    '    st.dataframe(show, use_container_width=True, hide_index=True, height=height)\n',
    '\n',
    '\n',
    'def _render_lunch(ns: dict, subpage: str) -> None:\n',
    '    if not subpage:\n',
    '        from tabs.final_lunch_upgrade_20260617 import render_lunch_quick_decision\n',
    '        # One authoritative Lunch surface: eight closed-first core fields.\n',
    '        _safe_component("Lunch Eight Principal Fields", render_lunch_quick_decision)\n',
    '        return\n',
    '\n',
    '    st.markdown(f"### 🍱 Lunch — {subpage}")\n',
    '    if subpage == "Full Metric Details + History":\n',
    '        from tabs.final_three_center_upgrade_20260614 import _render_metric_detail_section\n',
    '        _safe_component("Full Metric Details + History", _render_metric_detail_section, ns or _home_ns())\n',
    '    elif subpage == "PowerBI Projection":\n',
    '        # Dedicated cached-only renderer: opening this inner page imports no\n',
    '        # legacy Home module chain and performs no prediction/calibration work.\n',
    '        from ui.powerbi_cached_renderer_20260619 import render_cached_powerbi_projection\n',
    '        _safe_component("PowerBI Price Prediction Projection", render_cached_powerbi_projection)\n',
    '        try:\n',
    '            from ui.decision_product_panel_20260617 import render_powerbi_canonical_details\n',
    '            render_powerbi_canonical_details()\n',
    '        except Exception as exc:\n',
    '            st.caption(f"Validated projection details skipped safely: {exc}")\n',
    '    elif subpage == "Priority + Decision + Reliability":\n',
    '        ns = ns or _home_ns()\n',
    '        from tabs.dinner_morning_data_patch_20260614 import _render_priority_decision_reliability\n',
    '        _safe_component("Priority + Decision + Reliability", _render_priority_decision_reliability, ns)\n',
    '        renderer = ns.get("render_reliability_control_center_20260614")\n',
    '        if callable(renderer):\n',
    '            _safe_component("Reliability Control Center", renderer)\n',
    '    elif subpage == "Finder":\n',
    '        from ui.finder_canonical_view_20260619 import render_finder_canonical_view\n',
    '        _safe_component("Finder — Canonical Full Metric Priority", render_finder_canonical_view, state=st.session_state)\n',
    '    else:\n',
    '        from tabs.final_lunch_upgrade_20260617 import render_lunch_quick_decision\n',
    '        _safe_component("Lunch Quick Synced Decision", render_lunch_quick_decision)\n',
    '\n',
    '    try:\n',
    '        from tabs.final_lunch_upgrade_20260617 import render_lunch_25day_backtest_expander\n',
    '        render_lunch_25day_backtest_expander(key_suffix=str(subpage))\n',
    '    except Exception as exc:\n',
    '        st.caption(f"25-day Lunch Regime + NLP history table skipped safely: {exc}")\n',
    '\n',
    '\n',
    'def _render_dinner(ns: dict, subpage: str) -> None:\n',
    '    """Render all original Fields 4–9 from one already-published canonical generation."""\n',
    '    st.markdown("### 🌙 Dinner — Fields 4–9 Integrated Workspace")\n',
    '    st.caption("Read-only rendering of the current canonical generation. Opening Dinner never starts a heavy calculation.")\n',
    '    from tabs.field456789_page_20260626 import show as show_dinner\n',
    '    _safe_component("Dinner Fields 4–9", show_dinner, {"active_page": "Dinner", "active_subpage": subpage})\n',
    '\n',
    'def _render_morning() -> None:\n',
    '    st.markdown("### 🌅 Morning — Doo Prime")\n',
    '    st.caption("Morning remains closed-first. The legacy Home module chain is imported only after the true load switch is enabled.")\n',
    '    if not st.toggle("Open / Close — Load Morning Workspace", value=False, key="morning_true_load_gate_20260620"):\n',
    '        st.info("Morning is ready but not instantiated. Opening or closing other tabs performs no Morning calculation.")\n',
    '        return\n',
    '    ns = _home_ns()\n',
    '    _safe_component("Morning / Doo Prime", _prev_morning(ns))\n',
    '\n',
    '\n',
    'def _render_research(subpage: str) -> None:\n',
    '    st.markdown("### 🎓 Research")\n',
    '    if subpage in {"Research AI Assistant", "AI Assistant"}:\n',
    '        try:\n',
    '            from tabs.ai_assistant_lite import render_ai_assistant_lite_tab\n',
    '            _safe_component("AI Assistant", render_ai_assistant_lite_tab)\n',
    '        except Exception as exc:\n',
    '            st.warning(f"AI Assistant skipped safely: {exc}")\n',
    '        return\n',
    '    if subpage == "KNN / Greedy":\n',
    '        _display_priority_table(_canonical_priority_table(), height=430)\n',
    '        return\n',
    '    if subpage == "Quant Structure":\n',
    '        pack = st.session_state.get("final_synced_research_merge_pack_20260612") or st.session_state.get("final_merged_intelligence_pack_20260612") or {}\n',
    '        quant = pack.get("quant_structure", {}) if isinstance(pack, dict) else {}\n',
    '        if isinstance(quant, dict):\n',
    '            st.dataframe(pd.DataFrame([{"Metric": k, "Value": str(v)} for k, v in quant.items()]), use_container_width=True, hide_index=True)\n',
    '        elif isinstance(quant, pd.DataFrame):\n',
    '            st.dataframe(quant, use_container_width=True, hide_index=True)\n',
    '        else:\n',
    '            try:\n',
    '                from core.system_wide_completion_20260618 import readiness_message\n',
    '                message = readiness_message(st.session_state, "Research Data Analysis")\n',
    '            except Exception:\n',
    '                message = "The published Quant Structure is unavailable. Open Settings → Errors / Fix Fast."\n',
    '            st.dataframe(pd.DataFrame([{"Status": message}]), use_container_width=True, hide_index=True)\n',
    '        return\n',
    '    # After the Settings full calculation has published a canonical generation,\n',
    '    # Research opens directly. It remains read-only and starts no calculation.\n',
    '    canonical_ready = bool(st.session_state.get("canonical_result_20260617") or st.session_state.get("canonical_decision_result_20260617") or st.session_state.get("last_valid_canonical_decision_result_20260617"))\n',
    '    if not canonical_ready:\n',
    '        st.info("Run Full Calculation in Settings once to publish the shared research generation.")\n',
    '        return\n',
    '    try:\n',
    '        import tabs.research as research\n',
    '        _safe_component("Research", research.show)\n',
    '    except Exception as exc:\n',
    '        st.warning(f"Research skipped safely: {exc}")\n',
    '\n',
    '\n',
    'def _render_other() -> None:\n',
    '    try:\n',
    '        import tabs.other as other\n',
    '        _safe_component("Other", other.show)\n',
    '    except Exception as exc:\n',
    '        st.warning(f"Other workspace skipped safely: {exc}")\n',
    '\n',
    '\n',
    '\n',
    '\n',
    '\n',
    'def _render_secure_automation_settings() -> None:\n',
    '    from core.secure_api_startup_20260619 import initialize_secure_settings, secure_secret_status\n',
    '    initialize_secure_settings(st.session_state)\n',
    '    secret_state = secure_secret_status(st.session_state)\n',
    '    st.markdown("### 🔐 Secure API + Automatic Startup")\n',
    '    c1, c2 = st.columns(2)\n',
    '    c1.metric("Finnhub API", "CONFIGURED" if secret_state.get("finnhub_configured") else "NOT CONFIGURED", str(secret_state.get("finnhub_source", "")))\n',
    '    c2.metric("Second Market API", "CONFIGURED" if secret_state.get("second_api_configured") else "NOT CONFIGURED", str(secret_state.get("second_api_source", "")))\n',
    '    st.caption("Stored secrets remain server-side. The secure design never autofills their actual values into an input field or sends them to the browser.")\n',
    '    st.toggle("Use securely stored API keys", key="use_secure_api_keys_20260619")\n',
    '    st.toggle("Automatically connect APIs after login (connection only)", key="auto_connect_after_login_20260619")\n',
    '    st.session_state["auto_calculate_new_h1_20260619"] = False\n',
    '    st.session_state["open_lunch_after_auto_run_20260619"] = False\n',
    '    st.info("Automatic calculation is disabled. Only the Settings ‘Run Calculation + Open Lunch’ button can publish a new all-tab generation.")\n',
    '    st.number_input(\n',
    '        "Auto-run cooldown (minutes)", min_value=1, max_value=60, step=1,\n',
    '        key="auto_run_cooldown_minutes_20260619",\n',
    '        help="The generation lock, latest-H1 guard and cooldown prevent duplicate Cloud calculations.",\n',
    '    )\n',
    '    startup = st.session_state.get("secure_startup_status_20260619")\n',
    '    if isinstance(startup, Mapping):\n',
    '        st.caption(\n',
    '            f"Startup guard: {startup.get(\'status\', \'NO_ACTION\')} · latest H1 {startup.get(\'latest_h1\') or \'-\'} · "\n',
    '            f"published H1 {startup.get(\'published_h1\') or \'-\'}"\n',
    '        )\n',
    '\n',
    '\n',
    'def _save_and_connect_twelve_callback(widget_key: str) -> None:\n',
    '    """Atomically save, validate and connect from one click."""\n',
    '    from core.transaction_guard_v8_20260622 import begin_transaction, finish_transaction\n',
    '\n',
    '    token = begin_transaction(st.session_state, "api_save_connect", payload={"widget": widget_key})\n',
    '    if not token.get("accepted"):\n',
    '        return\n',
    '    try:\n',
    '        key = str(st.session_state.get(widget_key, "") or "").strip()\n',
    '        if not key:\n',
    '            try:\n',
    '                from core.connector_state_machine_20260621 import fail\n',
    '                fail(st.session_state, "market_connector_20260621", "Enter a Twelve Data API key first.")\n',
    '            except Exception:\n',
    '                pass\n',
    '            return\n',
    '        st.session_state["twelve_api_key"] = key\n',
    '        st.session_state["connector_mode"] = "twelve"\n',
    '        from core.navigation_parts.connection import _connect_now\n',
    '        outcome = _connect_now("Twelve Data Save + Validate + Connect", quick=True)\n',
    '        st.session_state["twelve_one_click_connect_result_20260628"] = outcome\n',
    '    finally:\n',
    '        finish_transaction(st.session_state, "api_save_connect", token=str(token.get("token") or ""))\n',
    '\n',
    '\n',
    'def _render_mobile_api_key_center() -> None:\n',
    '    """Secure status plus optional, blank temporary replacement fields."""\n',
    '    st.markdown("""\n',
    '    <style>\n',
    '    @media (max-width: 780px) {\n',
    '      div[data-testid="stTextInput"] input,\n',
    '      div[data-testid="stTextArea"] textarea {\n',
    '        font-size: 16px !important; min-height: 48px !important;\n',
    '        -webkit-user-select: text !important; user-select: text !important;\n',
    '        -webkit-touch-callout: default !important; touch-action: manipulation !important;\n',
    '      }\n',
    '      div[data-testid="stTextArea"] textarea {min-height: 76px !important; overflow-wrap: anywhere !important;}\n',
    '      div[data-testid="stButton"] button {min-height: 46px !important; white-space: normal !important;}\n',
    '    }\n',
    '    </style>\n',
    '    """, unsafe_allow_html=True)\n',
    '    st.markdown("### 🔑 Temporary API Key Replacement")\n',
    '    st.caption("These blank fields are optional session-only replacements. Streamlit Secrets are never shown or copied into them.")\n',
    '\n',
    '    twelve_generation = int(st.session_state.get("settings_mobile_twelve_generation_20260619", 0) or 0)\n',
    '    with st.expander("Open / Close — Replace Second / Twelve Data API Key", expanded=True):\n',
    '        value = st.text_area(\n',
    '            "Twelve Data API key — mobile paste box", value="",\n',
    '            key=f"settings_mobile_twelve_api_key_paste_20260619_{twelve_generation}", height=76,\n',
    '            placeholder="Optional: paste a temporary replacement key for this session",\n',
    '            help="The stored Streamlit Secret is intentionally never autofilled here.",\n',
    '        )\n',
    '        c1, c2 = st.columns(2)\n',
    '        c1.button(\n',
    '            "Save Key + Auto-Connect (One Click)", key="settings_mobile_save_twelve_20260619", use_container_width=True,\n',
    "            disabled=not bool(str(value or '').strip()), on_click=_save_and_connect_twelve_callback,\n",
    '            args=(f"settings_mobile_twelve_api_key_paste_20260619_{twelve_generation}",),\n',
    '        )\n',
    '        if c2.button("Clear Temporary Twelve Key", key="settings_mobile_clear_twelve_20260619", use_container_width=True):\n',
    '            st.session_state["twelve_api_key"] = ""\n',
    '            st.session_state["settings_mobile_twelve_generation_20260619"] = twelve_generation + 1\n',
    '            st.success("Temporary replacement cleared. The server-side secret, if configured, remains available.")\n',
    '            _safe_rerun()\n',
    '\n',
    '\n',
    '\n',
    'def _render_openrouter_api_center() -> None:\n',
    '    """One-click OpenRouter connector with secret auto-discovery."""\n',
    '    from services.openrouter_backend_20260628 import (\n',
    '        MODEL_KEY, SESSION_KEY, configuration_status, validate_connection,\n',
    '    )\n',
    '    with st.expander("Open / Close — AI API / OpenRouter Connector", expanded=True):\n',
    '        st.caption(\n',
    '            "Use a server-side Streamlit Secret for automatic startup configuration, or paste a temporary session-only replacement. "\n',
    '            "The key is never displayed, added to prompts, or stored in the runtime cache."\n',
    '        )\n',
    '        generation = int(st.session_state.get("openrouter_widget_generation_20260628", 0) or 0)\n',
    '        key_widget = f"openrouter_key_input_20260628_{generation}"\n',
    '        model_widget = f"openrouter_model_input_20260628_{generation}"\n',
    '        st.text_input(\n',
    '            "OpenRouter API key — temporary session replacement", type="password", value="", key=key_widget,\n',
    '            placeholder="Optional when OPENROUTER_API_KEY is already in Streamlit Secrets",\n',
    '        )\n',
    '        st.text_input(\n',
    '            "OpenRouter model", value=str(st.session_state.get(MODEL_KEY) or "openrouter/auto"), key=model_widget,\n',
    '            help="openrouter/auto is the default. You may enter another OpenRouter model slug.",\n',
    '        )\n',
    '        configured = configuration_status(st.session_state)\n',
    '        # Auto-validate a secret once per session. A failure is visible but never\n',
    '        # blocks the deterministic local assistant or the trading application.\n',
    '        if configured.get("configured") and not st.session_state.get("openrouter_auto_validation_attempted_20260628"):\n',
    '            st.session_state["openrouter_auto_validation_attempted_20260628"] = True\n',
    '            validate_connection(st.session_state)\n',
    '            configured = configuration_status(st.session_state)\n',
    '        cols = st.columns(4)\n',
    '        cols[0].metric("Configured", "YES" if configured.get("configured") else "NO")\n',
    '        cols[1].metric("Connection", "CONNECTED" if configured.get("connected") else str(configured.get("status") or "NOT CHECKED"))\n',
    '        cols[2].metric("Credential Source", str(configured.get("source") or "Not configured"))\n',
    '        cols[3].metric("Model", str(configured.get("model") or "openrouter/auto")[:28])\n',
    '        b1, b2 = st.columns(2)\n',
    '        if b1.button("Save + Connect OpenRouter (One Click)", key="openrouter_save_connect_20260628", use_container_width=True):\n',
    '            temporary = str(st.session_state.get(key_widget) or "").strip()\n',
    '            if temporary:\n',
    '                st.session_state[SESSION_KEY] = temporary\n',
    '            st.session_state[MODEL_KEY] = str(st.session_state.get(model_widget) or "openrouter/auto").strip() or "openrouter/auto"\n',
    '            result = validate_connection(st.session_state)\n',
    '            if result.get("ok"):\n',
    '                st.success("OpenRouter connected. The AI Assistant will use it first and fall back safely if a request fails.")\n',
    '            else:\n',
    '                st.error(str(result.get("message") or result.get("status") or "OpenRouter connection failed."))\n',
    '        if b2.button("Clear Temporary OpenRouter Key", key="openrouter_clear_temporary_20260628", use_container_width=True):\n',
    '            st.session_state.pop(SESSION_KEY, None)\n',
    '            st.session_state.pop("openrouter_connection_status_20260628", None)\n',
    '            st.session_state["openrouter_widget_generation_20260628"] = generation + 1\n',
    '            _safe_rerun()\n',
    '\n',
    '\n',
    'def _render_market_time_metrics(*, query_mt5: bool = True) -> dict[str, Any]:\n',
    '    """Show feed freshness without starting a calculation."""\n',
    '    try:\n',
    '        from core.market_time_freshness_20260622 import market_time_snapshot\n',
    '        snap = market_time_snapshot(st.session_state, query_mt5=query_mt5)\n',
    '    except Exception as exc:\n',
    '        snap = {"status": "CHECK", "current_utc_display": "Unavailable", "broker_clock_display": "Unavailable", "latest_loaded_display": "Unavailable", "lag_minutes": None, "source": "UNKNOWN", "error": str(exc)}\n',
    '    cols = st.columns(5)\n',
    '    cols[0].metric("Feed Freshness", str(snap.get("status") or "CHECK"), str(snap.get("source") or "DISCONNECTED"))\n',
    '    cols[1].metric("Current UTC", str(snap.get("current_utc_display") or "-").replace(" UTC", ""))\n',
    '    cols[2].metric("MT5 Latest Tick", str(snap.get("mt5_tick_display") or "Not available").replace(" UTC", ""))\n',
    '    cols[3].metric("Broker Clock", str(snap.get("broker_clock_display") or "Not available"))\n',
    '    lag = snap.get("lag_minutes")\n',
    '    has_loaded_candle = bool(snap.get("latest_loaded_broker_display"))\n',
    '    delta = f"{lag:g} min behind current bar" if isinstance(lag, (int, float)) else "Waiting for connected data"\n',
    '    latest_display = str(snap.get("latest_loaded_broker_display") or "Not available yet")\n',
    '    cols[4].metric("Latest Candle — Broker", latest_display, delta, delta_color="off" if not has_loaded_candle else "normal")\n',
    '    st.caption("MetaTrader tick timestamps are normalized to UTC for calculations. Visible candle time uses the configured broker offset; Myanmar time remains a separate UTC+6:30 display.")\n',
    '    return snap\n',
    '\n',
    '\n',
    'def _open_lunch_ai_after_settings_run(*, used_previous: bool = False) -> None:\n',
    '    phone = bool(st.session_state.get("phone_mode", False))\n',
    '    updates = {\n',
    '        "active_page": "Lunch", "tab_choice": "Lunch", "active_subpage": "", "lunch_active_subpage": "",\n',
    '        "lunch_bi_visual_ready": True, "show_restored_powerbi_20260617": True,\n',
    '        "load_original_powerbi_from_antd_lunch_20260615": True,\n',
    '        "settings_auto_open_lunch_20260617": True,\n',
    '        "lunch_calculation_completed_notice_20260621": True,\n',
    '        "lunch_active_field_selector_20260624": "All Lunch fields closed",\n',
    '        "lunch_active_field_selector_20260624__pending": "All Lunch fields closed",\n',
    '        # Legacy static marker only: "lunch_active_field_selector_20260624": "1. Open / Close — Full Metric 25-Day History + Decision Tables"\n',
    '        # The Settings run navigates to Lunch but leaves every large field closed.\n',
    '        "lunch_field_open_5_20260621": False,\n',
    '        "lunch_scroll_to_field5_20260622": False,\n',
    '        "settings_used_previous_canonical_20260622": bool(used_previous),\n',
    '    }\n',
    '    updates.update({\n',
    '        "lunch_field_open_1_20260621": False, "lunch_field_widget_1_20260621": False,\n',
    '        "lunch_field_open_2_20260621": False, "lunch_field_widget_2_20260621": False,\n',
    '        "lunch_field_open_3_20260621": False, "lunch_field_widget_3_20260621": False,\n',
    '        "lunch_field_open_4_20260621": False, "lunch_field_widget_4_20260621": False,\n',
    '        "lunch_field_open_5_20260621": False, "lunch_field_widget_5_20260621": False,\n',
    '        "lunch_field_open_6_20260621": False, "lunch_field_widget_6_20260621": False,\n',
    '        "lunch_scroll_to_field5_20260622": False,\n',
    '    })\n',
    '    try:\n',
    '        from core.navigation_authority_20260625 import navigate_to\n',
    '        navigate_to(st.session_state, "Lunch", "", None)\n',
    '    except Exception:\n',
    '        pass\n',
    '    st.session_state.update(updates)\n',
    '\n',
    'def _render_arert_research_settings() -> None:\n',
    '    """Explicit-only ARERT runner; normal Streamlit reruns only render cache."""\n',
    '    from research_quant.arert_lab import MODULE_CATALOG, STATE_KEY, run_arert_research\n',
    '\n',
    '    with st.expander("Open / Close — Dinner Master’s / PhD ARERT Research", expanded=True):\n',
    '        st.caption(\n',
    '            "Runs a separate research layer from the latest frozen completed canonical snapshot. "\n',
    '            "It never overwrites Lunch production calculations. Repeated same-candle modules reuse cache."\n',
    '        )\n',
    '        options = [f"{number:02d} — {name}" for number, (name, _field) in MODULE_CATALOG.items()]\n',
    '        selected_labels = st.multiselect(\n',
    '            "Select Dinner research modules",\n',
    '            options,\n',
    '            default=[options[-1]],\n',
    '            key="arert_selected_modules_20260628",\n',
    '        )\n',
    '        full_col, selected_col = st.columns(2)\n',
    '        full_clicked = full_col.button(\n',
    '            "Run Full Dinner Thesis Research + Open Dinner",\n',
    '            key="run_full_dinner_thesis_research_20260628",\n',
    '            use_container_width=True,\n',
    '        )\n',
    '        selected_clicked = selected_col.button(\n',
    '            "Run Selected Dinner Research Module",\n',
    '            key="run_selected_dinner_research_20260628",\n',
    '            use_container_width=True,\n',
    '        )\n',
    '        if full_clicked or selected_clicked:\n',
    '            try:\n',
    '                from core.canonical_lookup_20260626 import resolve_canonical\n',
    '                canonical = resolve_canonical(st.session_state)\n',
    '            except Exception:\n',
    '                canonical = {}\n',
    '            if not isinstance(canonical, Mapping) or not canonical:\n',
    '                st.error("No valid completed canonical snapshot is available. Run the protected Lunch calculation first.")\n',
    '            else:\n',
    '                selected = list(MODULE_CATALOG)\n',
    '                if selected_clicked:\n',
    '                    selected = []\n',
    '                    for label in selected_labels:\n',
    '                        try:\n',
    '                            selected.append(int(str(label).split("—", 1)[0].strip()))\n',
    '                        except Exception:\n',
    '                            continue\n',
    '                    if not selected:\n',
    '                        st.warning("Select at least one Dinner research module.")\n',
    '                        return\n',
    '                with st.spinner("Running the selected completed-candle ARERT research modules…"):\n',
    '                    envelope = run_arert_research(st.session_state, canonical, selected)\n',
    '                st.session_state["arert_last_settings_run_20260628"] = {\n',
    '                    "status": envelope.get("status"),\n',
    '                    "selected_modules": envelope.get("selected_modules"),\n',
    '                    "metadata": envelope.get("metadata"),\n',
    '                    "database": envelope.get("database"),\n',
    '                }\n',
    '                try:\n',
    '                    from core.navigation_authority_20260625 import navigate_to\n',
    '                    navigate_to(st.session_state, "Dinner", "", None)\n',
    '                except Exception:\n',
    '                    st.session_state["active_page"] = "Dinner"\n',
    '                    st.session_state["tab_choice"] = "Dinner"\n',
    '                    st.session_state["active_subpage"] = ""\n',
    '                _safe_rerun()\n',
    '\n',
    '        last = st.session_state.get("arert_last_settings_run_20260628")\n',
    '        envelope = st.session_state.get(STATE_KEY)\n',
    '        if isinstance(last, Mapping):\n',
    '            cols = st.columns(4)\n',
    '            cols[0].metric("ARERT Status", str(last.get("status") or "—"))\n',
    '            cols[1].metric("Modules Cached", str(len((envelope or {}).get("modules", {}))) if isinstance(envelope, Mapping) else "0")\n',
    '            metadata = last.get("metadata") if isinstance(last.get("metadata"), Mapping) else {}\n',
    '            cols[2].metric("Broker Candle", str(metadata.get("completed_broker_candle") or "—"))\n',
    '            database = last.get("database") if isinstance(last.get("database"), Mapping) else {}\n',
    '            cols[3].metric("Research DB", "READY" if database.get("ok") else "CHECK")\n',
    '\n',
    '\n',
    '\n',
    'def _render_imap_rv_settings() -> None:\n',
    '    """Explicit-only IMAP-RV runner; normal reruns render cached evidence only."""\n',
    '    from research_quant.imap_rv_20260628 import STATE_KEY, run_imap_rv\n',
    '\n',
    '    with st.expander("Open / Close — IMAP-RV Thesis Research", expanded=False):\n',
    '        st.caption(\n',
    '            "Information Mining, Attention, Path-Memory and Research Validity. "\n',
    '            "This is a separate research prototype and never overwrites protected Lunch values."\n',
    '        )\n',
    '        force = st.checkbox("Force rebuild for the same completed candle", value=False, key="imap_rv_force_20260628")\n',
    '        if st.button("Run IMAP-RV Research + Open Dinner", key="run_imap_rv_20260628", use_container_width=True):\n',
    '            try:\n',
    '                from core.canonical_lookup_20260626 import resolve_canonical\n',
    '                canonical = resolve_canonical(st.session_state)\n',
    '            except Exception:\n',
    '                canonical = {}\n',
    '            if not isinstance(canonical, Mapping) or not canonical:\n',
    '                st.error("No completed canonical generation is available. Run the protected calculation first.")\n',
    '            else:\n',
    '                with st.spinner("Running completed-candle IMAP-RV research…"):\n',
    '                    envelope = run_imap_rv(st.session_state, canonical, force=bool(force))\n',
    '                st.session_state["imap_rv_last_settings_run_20260628"] = {\n',
    '                    "status": envelope.get("status"), "score": envelope.get("imap_rv_score"),\n',
    '                    "protective_action": envelope.get("protective_action"), "metadata": envelope.get("metadata"),\n',
    '                }\n',
    '                try:\n',
    '                    from core.navigation_authority_20260625 import navigate_to\n',
    '                    navigate_to(st.session_state, "Dinner", "", None)\n',
    '                except Exception:\n',
    '                    st.session_state["active_page"] = "Dinner"\n',
    '                    st.session_state["tab_choice"] = "Dinner"\n',
    '                    st.session_state["active_subpage"] = ""\n',
    '                _safe_rerun()\n',
    '        envelope = st.session_state.get(STATE_KEY)\n',
    '        if isinstance(envelope, Mapping):\n',
    '            cols = st.columns(4)\n',
    '            score = envelope.get("imap_rv_score")\n',
    '            cols[0].metric("IMAP-RV", "N/A" if score is None else f"{float(score):.1f}/100")\n',
    '            cols[1].metric("Protective Action", str(envelope.get("protective_action") or "NO TRADE"))\n',
    '            cols[2].metric("Cache", str(envelope.get("cache_status") or "—"))\n',
    '            db = envelope.get("database") if isinstance(envelope.get("database"), Mapping) else {}\n',
    '            cols[3].metric("Research DB", "READY" if db.get("ok") else "CHECK")\n',
    '\n',
    'def _render_home() -> None:\n',
    '    """Lightweight Home page with global identity and Explain-this-App shortcut."""\n',
    '    st.markdown("## 🏠 ADX Quant Pro — Home")\n',
    '    st.caption("Select an instrument globally, review the current publication identity, or open the full app explanation. Home never runs heavy calculations.")\n',
    '    try:\n',
    '        from ui.global_symbol_selector_20260629 import render_global_symbol_selector\n',
    '        render_global_symbol_selector(st.session_state, key_prefix="home_20260629", auto_refresh_library=True)\n',
    '    except Exception as exc:\n',
    '        st.warning(f"Global symbol selector unavailable: {exc}")\n',
    '    canonical = {}\n',
    '    try:\n',
    '        from core.canonical_lookup_20260626 import resolve_canonical\n',
    '        canonical = resolve_canonical(st.session_state) or {}\n',
    '    except Exception:\n',
    '        canonical = st.session_state.get("canonical_result_20260617") or {}\n',
    '    cols = st.columns(4)\n',
    '    cols[0].metric("Published Symbol", str(canonical.get("symbol") or "—"))\n',
    '    cols[1].metric("Published Timeframe", str(canonical.get("timeframe") or "—"))\n',
    '    cols[2].metric("Run ID", str(canonical.get("run_id") or canonical.get("canonical_calculation_id") or "—")[:24])\n',
    '    cols[3].metric("Status", "RUN NEEDED" if st.session_state.get("selected_symbol_pending_run_20260629") else "READY")\n',
    '    if st.button("📘 Open Settings → Explain this App", key="home_open_explain_app_20260629", use_container_width=True):\n',
    '        st.session_state["settings_open_explain_app_20260629"] = True\n',
    '        try:\n',
    '            from core.navigation_authority_20260625 import navigate_to\n',
    '            navigate_to(st.session_state, "Settings", "", None)\n',
    '        except Exception:\n',
    '            st.session_state["active_page"] = "Settings"\n',
    '            st.session_state["tab_choice"] = "Settings"\n',
    '            st.session_state["active_subpage"] = ""\n',
    '        _safe_rerun()\n',
    '    try:\n',
    '        from ui.app_professional_guide_20260628 import render_app_professional_guide\n',
    '        render_app_professional_guide(expanded=False, context={\n',
    '            "source": st.session_state.get("source"), "symbol": st.session_state.get("symbol", "EURUSD"),\n',
    '            "timeframe": st.session_state.get("timeframe", "H1"),\n',
]
