-- Idempotent compact Quant V6 schema.
CREATE TABLE IF NOT EXISTS quant_research_v6_run(calculation_id TEXT NOT NULL,generation_id TEXT NOT NULL,event_time_utc TEXT,status TEXT NOT NULL,method_count INTEGER NOT NULL DEFAULT 0,sample_count INTEGER NOT NULL DEFAULT 0,runtime_ms REAL,peak_traced_memory_mb REAL,serialized_result_bytes INTEGER,logic_version TEXT NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(calculation_id,generation_id));
CREATE INDEX IF NOT EXISTS idx_qv6_run_event ON quant_research_v6_run(event_time_utc DESC);
CREATE INDEX IF NOT EXISTS idx_qv6_run_generation ON quant_research_v6_run(generation_id);
CREATE TABLE IF NOT EXISTS quant_research_v6_method_results(calculation_id TEXT NOT NULL,generation_id TEXT NOT NULL,event_time_utc TEXT,method_id TEXT NOT NULL,status TEXT NOT NULL,sample_count INTEGER NOT NULL DEFAULT 0,horizon_hours INTEGER NOT NULL DEFAULT 0,score REAL,logic_version TEXT NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(calculation_id,generation_id,method_id,horizon_hours));
CREATE INDEX IF NOT EXISTS idx_qv6_method_event ON quant_research_v6_method_results(event_time_utc DESC);
CREATE INDEX IF NOT EXISTS idx_qv6_method_generation ON quant_research_v6_method_results(generation_id,method_id);
CREATE TABLE IF NOT EXISTS quant_research_v6_market_history(event_time_utc TEXT NOT NULL,broker_time TEXT,myanmar_time TEXT,calculation_id TEXT NOT NULL,generation_id TEXT NOT NULL,symbol TEXT NOT NULL,timeframe TEXT NOT NULL,source TEXT,completed_status TEXT,session TEXT,london_active INTEGER,new_york_active INTEGER,london_new_york_overlap INTEGER,close REAL,return_1 REAL,candle_range REAL,volatility REAL,spread REAL,slippage REAL,expected_move REAL,regime TEXT,protected_decision TEXT,master_score REAL,entry_score REAL,hold_score REAL,tp_quality REAL,exit_risk REAL,trend_capacity REAL,forecast_direction TEXT,forecast_confidence REAL,realized_direction TEXT,direction_correct INTEGER,absolute_forecast_error REAL,signal_survival_probability REAL,churn_risk REAL,drift_state TEXT,data_quality_status TEXT,synchronization_status TEXT,gap_flag TEXT,logic_version TEXT NOT NULL,PRIMARY KEY(event_time_utc,symbol,timeframe,calculation_id,generation_id));
CREATE INDEX IF NOT EXISTS idx_qv6_market_event ON quant_research_v6_market_history(event_time_utc DESC);
CREATE INDEX IF NOT EXISTS idx_qv6_market_identity ON quant_research_v6_market_history(symbol,timeframe,event_time_utc DESC);
CREATE INDEX IF NOT EXISTS idx_qv6_market_calc ON quant_research_v6_market_history(calculation_id,generation_id);
CREATE INDEX IF NOT EXISTS idx_qv6_market_session ON quant_research_v6_market_history(session,london_new_york_overlap);
CREATE INDEX IF NOT EXISTS idx_qv6_market_settled ON quant_research_v6_market_history(completed_status,direction_correct);
