"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '            "Conflict between pressure and regime?",\n',
    '            "Should I wait because signals disagree?",\n',
    '            "Check regime prediction agreement",\n',
    '            "Counter trend risk now",\n',
    '            "Is this trade against regime?",\n',
    '        ], ["conflict", "regime", "prediction", "agree", "counter trend"]),\n',
    '        ("Confidence / Quality", "regime_bias_check", [\n',
    '            "What does regime say now?",\n',
    '            "Current regime bias check",\n',
    '            "Bull bear range direction now",\n',
    '            "Is regime bullish bearish or range?",\n',
    '            "Regime filter buy sell wait",\n',
    '            "Should I follow regime or prediction?",\n',
    '            "Major regime direction now",\n',
    '            "Regime says wait or trade?",\n',
    '            "What side does current regime prefer?",\n',
    '            "Regime behavior in simple words",\n',
    '        ], ["regime", "bull", "bear", "range", "bias"]),\n',
    '    ]\n',
    '    out: List[Dict[str, Any]] = []\n',
    '    seen = set()\n',
    '    for category, intent, questions, keywords in packs:\n',
    '        for q in questions:\n',
    '            nq = _plain_normalize_question_pattern(q)\n',
    '            if nq in seen:\n',
    '                continue\n',
    '            seen.add(nq)\n',
    '            out.append({\n',
    '                "category": category,\n',
    '                "question": q,\n',
    '                "intent": intent,\n',
    '                "keywords": keywords,\n',
    '                "pattern": nq,\n',
    '            })\n',
    '    return out\n',
    '\n',
    '\n',
    'PREPARED_QUESTION_PATTERNS: List[Dict[str, Any]] = _build_prepared_question_patterns()\n',
    '\n',
    '\n',
    'def _extend_1000_question_patterns_20260614(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:\n',
    '    """Add 1000 lightweight local question patterns.\n',
    '\n',
    '    This is data only, not a model. Patterns feed the existing NLP similarity\n',
    '    engine so typing "en"/"entry"/"tp"/"regime" quickly surfaces relevant\n',
    '    choices without button clutter.\n',
    '    """\n',
    '    bases = [\n',
    '        ("Entry / Scalp", "scalp_entry_now", "entry", ["entry", "enter", "en", "scalp", "now"]),\n',
    '        ("TP / Target", "entry_with_tp_plan", "tp", ["tp", "target", "take profit", "price zone"]),\n',
    '        ("Protect / Exit", "protect_existing_position", "exit", ["exit", "protect", "close", "reduce"]),\n',
    '        ("Bias / Direction", "less_risky_bias", "bias", ["bias", "buy", "sell", "direction"]),\n',
    '        ("Prediction", "next_1h_bias", "prediction", ["prediction", "forecast", "next", "path"]),\n',
    '        ("History / Similar Setup", "history_similar_setup", "history", ["history", "similar", "knn", "greedy"]),\n',
    '        ("Confidence / Quality", "quality_confidence_check", "quality", ["quality", "confidence", "reliability", "accuracy"]),\n',
    '        ("Confidence / Quality", "prediction_conflict_check", "conflict", ["conflict", "regime", "counter trend"]),\n',
    '        ("Confidence / Quality", "regime_bias_check", "regime", ["regime", "bull", "bear", "range"]),\n',
    '        ("Data Analysis", "recommended_action", "analysis", ["descriptive", "predictive", "prescriptive"]),\n',
    '        ("System / Controls", "system_feature_status", "system", ["sidebar", "menu", "settings", "api", "nlp", "llm", "phone", "finder", "research"]),\n',
    '    ]\n',
    '    templates = [\n',
    '        "{topic} check now", "{topic} quality now", "{topic} risk now", "{topic} score now",\n',
    '        "{topic} best hour", "{topic} safest hour", "{topic} next 1h", "{topic} next 2h",\n',
    '        "{topic} next 6h", "{topic} with current regime", "{topic} with history", "{topic} with powerbi",\n',
    '        "{topic} with market quality", "{topic} with reliability", "{topic} with forecast agreement",\n',
    '        "{topic} if exit risk high", "{topic} if confidence weak", "{topic} during london",\n',
    '        "{topic} during ny overlap", "{topic} for eurusd h1",\n',
    '    ]\n',
    '    out, seen = list(rows), {_plain_normalize_question_pattern(str(x.get("question", ""))) for x in rows}\n',
    '    for pack_id in range(5):\n',
    '        for category, intent, topic, keywords in bases:\n',
    '            for tpl_id, tpl in enumerate(templates):\n',
    '                q = tpl.format(topic=topic)\n',
    '                if pack_id:\n',
    '                    q = f"{q} scenario {pack_id + 1}"\n',
    '                pat = _plain_normalize_question_pattern(q)\n',
    '                if pat in seen:\n',
    '                    continue\n',
    '                seen.add(pat)\n',
    '                out.append({"category": category, "question": q, "intent": intent, "keywords": keywords, "pattern": pat})\n',
    '                if len(out) >= len(rows) + 1000:\n',
    '                    return out\n',
    '    return out\n',
    '\n',
    '\n',
    'PREPARED_QUESTION_PATTERNS = _extend_1000_question_patterns_20260614(PREPARED_QUESTION_PATTERNS)\n',
    '\n',
    '\n',
    'def _answer_rule_for_intent_20260615(intent: str) -> str:\n',
    '    """Human-readable answer rule for every prepared question pattern.\n',
    '\n',
    '    The rule is display metadata only. It tells the local assistant how each\n',
    '    choice-box question should be answered without adding a new model or API.\n',
    '    """\n',
    '    rules = {\n',
    '        "scalp_entry_now": "Answer with less-risky BUY/SELL side first, then entry quality, exit-risk warning, and tight TP only if side is clean.",\n',
    '        "sell_entry_tp": "Answer with SELL TP1/TP2 zones from lower band/path, then confidence and invalidation warning.",\n',
    '        "buy_entry_tp": "Answer with BUY TP1/TP2 zones from upper band/path, then confidence and invalidation warning.",\n',
    '        "entry_with_tp_plan": "Detect BUY/SELL/entry price from text; give side-specific TP plan only when current metrics support it.",\n',
    '        "less_risky_bias": "Use half-threshold BUY/SELL evidence and triple-threshold WAIT filter; explain regime, pressure, prediction, and risk votes.",\n',
    '        "hold_bias_next_1h": "Answer hold/protect for next hour using safer side, exit risk, forecast confidence, and current pressure.",\n',
    '        "next_30min_prediction": "Use H1 proxy only; show estimated direction/zone and warn that this is not an M1/M5 model.",\n',
    '        "next_1h_bias": "Use next path point and current regime/pressure; answer BUY/SELL unless triple WAIT filter blocks it.",\n',
    '        "next_2h_bias": "Use first two path points plus exit risk; answer target reach proxy and safer side.",\n',
    '        "next_6h_bias": "Use six-hour path/expected move plus regime stability; answer direction, probability proxy, and risk.",\n',
    '        "history_similar_setup": "Mine existing cached history/KNN/Greedy rows and compare similar regime, hour, score, and risk.",\n',
    '        "protect_existing_position": "Prioritize risk protection, partial close, invalidation, and hold/exit decision from existing metrics.",\n',
    '        "quality_confidence_check": "Explain reliability, accuracy/error, missing data, and whether confidence is strong enough for action.",\n',
    '        "prediction_conflict_check": "Detect regime/prediction/news conflict and reduce confidence; prefer protect/WAIT only on real conflict.",\n',
    '        "regime_bias_check": "Explain BULL/BEAR/RANGE regime direction, age/stability, and whether it supports BUY/SELL.",\n',
    '        "recommended_action": "Give descriptive + predictive + prescriptive answer using existing calculations; no new prediction engine.",\n',
    '        "system_feature_status": "Answer the exact menu, sidebar, API, phone, Finder, Research, copy or workspace question from current app state; never force BUY/SELL advice.",\n',
    '    }\n',
    '    return rules.get(str(intent or ""), "Answer from existing EURUSD H1 metrics, explain uncertainty, avoid external API/model claims, and keep the result actionable.")\n',
    '\n',
    '\n',
    'def _ensure_question_pattern_rules_20260615(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:\n',
    '    out: List[Dict[str, Any]] = []\n',
    '    seen = set()\n',
    '    for idx, item in enumerate(rows):\n',
    '        row = dict(item) if isinstance(item, dict) else {"question": str(item)}\n',
    '        q = _safe_str(row.get("question"), f"prepared question {idx+1}")\n',
    '        pat = _plain_normalize_question_pattern(row.get("pattern") or q)\n',
    '        if not pat or pat in seen:\n',
    '            continue\n',
    '        seen.add(pat)\n',
    '        intent = _safe_str(row.get("intent"), "recommended_action")\n',
    '        row["pattern"] = pat\n',
    '        row["intent"] = intent\n',
    '        row["answer_rule"] = _answer_rule_for_intent_20260615(intent)\n',
    '        row["answer_mode"] = "Auto / Enter-to-answer"\n',
    '        row["pattern_id"] = f"Q{len(out)+1:04d}"\n',
    '        out.append(row)\n',
    '    return out\n',
    '\n',
    '\n',
    'PREPARED_QUESTION_PATTERNS = _ensure_question_pattern_rules_20260615(PREPARED_QUESTION_PATTERNS)\n',
    'QUESTION_CATEGORIES: List[str] = [\n',
    '    "Entry / Scalp", "TP / Target", "Bias / Direction", "Prediction",\n',
    '    "History / Similar Setup", "Protect / Exit", "Confidence / Quality", "System / Controls", "All Questions",\n',
    ']\n',
    '\n',
    'VOCAB = sorted(set(\n',
    '    list(TRADING_WORDS)\n',
    '    + [word for meta in INTENT_REGISTRY.values() for phrase in meta.get("keywords", []) + meta.get("phrases", []) for word in str(phrase).split()]\n',
    '    + [word for words in SYNONYM_GROUPS.values() for phrase in words for word in phrase.split()]\n',
    '    + [word for item in PREPARED_QUESTION_PATTERNS for word in str(item.get("pattern", "")).split()]\n',
    '))\n',
    '\n',
    '\n',
    'def normalize_question(text: str) -> str:\n',
    '    q = (text or "").lower().strip()\n',
    '    for pat, repl in TYPO_REPLACEMENTS:\n',
    '        q = re.sub(pat, repl, q)\n',
    '    q = re.sub(r"[^a-z0-9\\.\\s]+", " ", q)\n',
    '    q = re.sub(r"\\s+", " ", q).strip()\n',
    '    # Very small token-level correction against known trading vocabulary.\n',
    '    fixed: List[str] = []\n',
    '    for tok in q.split():\n',
    '        if re.fullmatch(r"\\d+(?:\\.\\d+)?", tok) or len(tok) <= 2 or tok in VOCAB:\n',
    '            fixed.append(tok)\n',
    '            continue\n',
    '        match = difflib.get_close_matches(tok, VOCAB, n=1, cutoff=0.78)\n',
    '        fixed.append(match[0] if match else tok)\n',
    '    q = " ".join(fixed)\n',
    '    for pat, repl in TYPO_REPLACEMENTS:\n',
    '        q = re.sub(pat, repl, q)\n',
    '    return re.sub(r"\\s+", " ", q).strip()\n',
    '\n',
    '\n',
    'def _extract_prices(text: str) -> List[float]:\n',
    '    vals = []\n',
    '    for m in re.finditer(r"(?<!\\d)(\\d\\.\\d{3,6})(?!\\d)", text or ""):\n',
    '        x = _num(m.group(1))\n',
    '        if x is not None:\n',
    '            vals.append(x)\n',
    '    return vals[:4]\n',
    '\n',
    '\n',
    'def _detect_horizon(cleaned: str) -> Dict[str, Any]:\n',
    '    if re.search(r"\\b30\\s*(?:min|minute|minutes)\\b", cleaned):\n',
    '        return {"label": "30 min", "hours": 0.5}\n',
    '    m = re.search(r"\\b(1|2|3|4|5|6|12|24)\\s*(?:hour|hours|hr|hrs)\\b", cleaned)\n',
    '    if m:\n',
    '        h = int(m.group(1))\n',
    '        return {"label": f"{h} hour" + ("s" if h != 1 else ""), "hours": float(h)}\n',
    '    if "today" in cleaned:\n',
    '        return {"label": "today", "hours": 24.0}\n',
    '    if "next session" in cleaned or "session" in cleaned:\n',
    '        return {"label": "next session", "hours": 6.0}\n',
    '    return {"label": "current H1", "hours": 1.0}\n',
    '\n',
    '\n',
    'def _contains_any(q: str, phrases: Iterable[str]) -> bool:\n',
    '    return any(p in q for p in phrases)\n',
    '\n',
    '\n',
    'def _synonym_hits(q: str) -> int:\n',
    '    hits = 0\n',
    '    for group in SYNONYM_GROUPS.values():\n',
    '        if any(term in q for term in group):\n',
    '            hits += 1\n',
    '    return hits\n',
    '\n',
    '\n',
    'def _trading_word_hits(q: str) -> int:\n',
    '    return sum(1 for w in TRADING_WORDS if w in q)\n',
    '\n',
    '\n',
    'def _similar(a: str, b: str) -> float:\n',
    '    """Robust short-text similarity for messy phone typing.\n',
    '\n',
    '    Uses normal sequence ratio + token-sort/token-set overlap.  This improves\n',
    '    recognition when the user types words in a different order, misses small\n',
    '    words, or uses noisy spelling.\n',
    '    """\n',
    '    try:\n',
    '        a = re.sub(r"\\s+", " ", str(a or "").lower().strip())\n',
    '        b = re.sub(r"\\s+", " ", str(b or "").lower().strip())\n',
    '        if not a or not b:\n',
    '            return 0.0\n',
    '        seq = difflib.SequenceMatcher(None, a, b).ratio()\n',
    '        at = [x for x in a.split() if x]\n',
    '        bt = [x for x in b.split() if x]\n',
    '        aset, bset = set(at), set(bt)\n',
    '        inter = len(aset & bset)\n',
    '        union = max(1, len(aset | bset))\n',
    '        jacc = inter / union\n',
    '        contain = 0.0\n',
    '        if a in b or b in a:\n',
    '            contain = min(len(a), len(b)) / max(len(a), len(b))\n',
    '        token_sort = difflib.SequenceMatcher(None, " ".join(sorted(at)), " ".join(sorted(bt))).ratio()\n',
    '        # token_set rewards same important words even when filler words differ\n',
    '        token_set = inter / max(1, min(len(aset), len(bset)))\n',
    '        return float(max(seq, token_sort * 0.96, jacc * 0.92, token_set * 0.88, contain * 0.95))\n',
    '    except Exception:\n',
    '        return 0.0\n',
    '\n',
    '\n',
    'def _question_memory() -> List[Dict[str, Any]]:\n',
    '    mem = st.session_state.get("ai_lite_question_memory", [])\n',
    '    return mem if isinstance(mem, list) else []\n',
    '\n',
    '\n',
    'def _store_question_memory(raw: str, normalized: str, intent: str, answer: str) -> None:\n',
    '    mem = _question_memory()\n',
    '    mem.append({"raw": raw, "normalized": normalized, "intent": intent, "answer": answer})\n',
    '    st.session_state["ai_lite_question_memory"] = mem[-MAX_CHAT_MEMORY:]\n',
    '    amem = st.session_state.get("ai_lite_answer_memory", [])\n',
    '    if not isinstance(amem, list):\n',
    '        amem = []\n',
    '    amem.append(answer)\n',
    '    st.session_state["ai_lite_answer_memory"] = amem[-MAX_CHAT_MEMORY:]\n',
    '\n',
    '\n',
    'def local_ai_detect_intent(user_question: str) -> Dict[str, Any]:\n',
    '    raw = user_question or ""\n',
    '    cleaned = normalize_question(raw)\n',
    '    prices = _extract_prices(cleaned)\n',
    '    horizon = _detect_horizon(cleaned)\n',
    '    side = "BUY" if re.search(r"\\b(?:buy|long|bull)\\b", cleaned) else "SELL" if re.search(r"\\b(?:sell|short|bear)\\b", cleaned) else None\n',
    '\n',
    '    scores: Dict[str, float] = {}\n',
    '    best_example = ""\n',
    '    best_example_sim = 0.0\n',
    '    for intent, meta in INTENT_REGISTRY.items():\n',
    '        score = 0.0\n',
    '        phrases = meta.get("phrases", [])\n',
    '        keywords = meta.get("keywords", [])\n',
    '        examples = meta.get("examples", [])\n',
    '        score += sum(14.0 for p in phrases if p in cleaned)\n',
    '        score += sum(5.0 for k in keywords if k in cleaned)\n',
    '        if _contains_any(cleaned, keywords):\n',
    '            score += 5.0\n',
    '        score += min(14.0, _synonym_hits(cleaned) * 2.0)\n',
    '        score += min(10.0, _trading_word_hits(cleaned) * 0.9)\n',
    '        if prices and intent in {"sell_entry_tp", "buy_entry_tp", "entry_with_tp_plan", "recommended_action"}:\n',
    '            score += 6.0\n',
    '        if horizon["label"] != "current H1" and intent in {"next_30min_prediction", "next_1h_bias", "next_2h_bias", "next_6h_bias", "hold_bias_next_1h"}:\n',
    '            score += 10.0\n',
    '        for ex in examples:\n',
    '            sim = _similar(cleaned, normalize_question(ex))\n',
    '            if sim > best_example_sim:\n',
    '                best_example_sim = sim\n',
    '                best_example = ex\n',
    '            score += sim * 44.0\n',
    '        scores[intent] = score\n',
    '\n',
    '    # Prepared Question Box patterns also feed the NLP scorer.  This makes\n',
    '    # dropdown/search patterns and free-typed messy questions share the same\n',
    '    # local recognition path.\n',
    '    prepared_best = {"ratio": 0.0, "question": "", "intent": None}\n',
    '    for item in PREPARED_QUESTION_PATTERNS:\n',
    '        intent_key = _safe_str(item.get("intent"), "")\n',
    '        if intent_key not in scores:\n',
    '            continue\n',
    '        pattern = _safe_str(item.get("pattern"), "")\n',
    '        if not pattern:\n',
    '            continue\n',
    '        ratio = _similar(cleaned, pattern)\n',
    '        if ratio > prepared_best["ratio"]:\n',
    '            prepared_best = {"ratio": ratio, "question": item.get("question", ""), "intent": intent_key}\n',
    '        kw_hits = sum(1 for kw in item.get("keywords", []) if _plain_normalize_question_pattern(kw) in cleaned)\n',
    '        phrase_hit = 1 if pattern and (pattern in cleaned or cleaned in pattern) else 0\n',
    '        scores[intent_key] += (ratio * 30.0) + min(12.0, kw_hits * 2.2) + (18.0 if phrase_hit else 0.0)\n',
    '\n',
    '    # Strong direct rule boosts.\n',
    '    if "take profit" in cleaned and "sell" in cleaned:\n',
    '        scores["sell_entry_tp"] += 55\n',
    '    if "take profit" in cleaned and "buy" in cleaned:\n',
    '        scores["buy_entry_tp"] += 55\n',
    '    if ("scalp" in cleaned or "quick trade" in cleaned or "fast entry" in cleaned) and ("entry" in cleaned or "now" in cleaned):\n',
    '        scores["scalp_entry_now"] += 70\n',
    '    if "30 min" in cleaned:\n',
    '        scores["next_30min_prediction"] += 70\n',
    '    if "1 hour" in cleaned and "hold" in cleaned:\n',
    '        scores["hold_bias_next_1h"] += 55\n',
    '    if "1 hour" in cleaned and "hold" not in cleaned:\n',
    '        scores["next_1h_bias"] += 35\n',
    '    if "2 hours" in cleaned:\n',
    '        scores["next_2h_bias"] += 45\n',
    '    if "6 hours" in cleaned:\n',
    '        scores["next_6h_bias"] += 45\n',
    '    if "buy or sell" in cleaned and ("safer" in cleaned or "less risky" in cleaned):\n',
    '        scores["less_risky_bias"] += 70\n',
    '    if re.search(r"\\bshould i buy\\b", cleaned) or re.search(r"\\bshould i sell\\b", cleaned):\n',
    '        scores["recommended_action"] += 65\n',
    '    if "similar" in cleaned or "history" in cleaned or "backtest" in cleaned:\n',
    '        scores["history_similar_setup"] += 45\n',
    '    if "quality" in cleaned or "confidence" in cleaned or "reliability" in cleaned or "accuracy" in cleaned:\n',
    '        scores["quality_confidence_check"] += 45\n',
    '    if "recognition" in cleaned or "grammar" in cleaned or "text similarity" in cleaned:\n',
    '        scores["nearest_answer_fallback"] += 28\n',
    '        scores["history_similar_setup"] += 18\n',
    '    system_terms = (\n',
    '        "sidebar", "menu", "setting", "settings", "phone ui", "api status", "nlp api",\n',
    '        "llm", "copy short", "copy full", "finder", "research tab", "other tab",\n',
    '        "engine", "train data", "pre original", "backtest", "profile", "question pattern",\n',
    '        "opens first", "startup page",\n',
    '    )\n',
    '    if any(term in cleaned for term in system_terms):\n',
    '        scores["system_feature_status"] += 82\n',
    '    if "descriptive" in cleaned or "predictive" in cleaned or "prescriptive" in cleaned or "analysis" in cleaned:\n',
    '        scores["recommended_action"] += 22\n',
    '        scores["quality_confidence_check"] += 16\n',
    '    if "data not given" in cleaned or "nlp did not find" in cleaned or "not found" in cleaned:\n',
    '        scores["nearest_answer_fallback"] += 65\n',
    '        scores["history_similar_setup"] += 25\n',
    '    if "regime" in cleaned and "prediction" in cleaned:\n',
    '        scores["prediction_conflict_check"] += 55\n',
    '    if prices and ("entry" in cleaned or "position" in cleaned):\n',
    '        if side == "SELL":\n',
    '            scores["sell_entry_tp"] += 38\n',
    '        elif side == "BUY":\n',
    '            scores["buy_entry_tp"] += 38\n',
    '        else:\n',
    '            scores["entry_with_tp_plan"] += 24\n',
    '    if "within" in cleaned and prices and ("target" in cleaned or "take profit" in cleaned or "reach" in cleaned):\n',
    '        scores["history_similar_setup"] += 18\n',
    '        scores["quality_confidence_check"] += 12\n',
    '\n',
    '    # Similar question memory.\n',
    '    memory_best = {"ratio": 0.0, "intent": None, "raw": ""}\n',
    '    for item in _question_memory():\n',
    '        old = _safe_str(item.get("normalized", ""), "")\n',
    '        if not old:\n',
    '            continue\n',
    '        ratio = _similar(cleaned, old)\n',
    '        if ratio > memory_best["ratio"]:\n',
    '            memory_best = {"ratio": ratio, "intent": item.get("intent"), "raw": item.get("raw", "")}\n',
    '    if memory_best["intent"] in scores and memory_best["ratio"] >= 0.55:\n',
    '        scores[str(memory_best["intent"])] += memory_best["ratio"] * 35.0\n',
    '\n',
    '    intent, top_score = max(scores.items(), key=lambda kv: kv[1])\n',
    '    score_pct = max(0.0, min(100.0, top_score))\n',
    '    if score_pct < 24:\n',
    '        intent = "nearest_answer_fallback"\n',
    '    elif score_pct < 38 and best_example_sim < 0.45 and memory_best["ratio"] < 0.45:\n',
    '        intent = "nearest_answer_fallback"\n',
    '\n',
    '    # High-precision semantic overrides prevent the 1,000-pattern library from\n',
    '    # turning factual system questions into unrelated BUY/SELL advice.\n',
    '    trade_words = ("buy", "sell", "entry", "enter", "trade", "hold", "position", "tp", "target", "bias", "direction", "safer", "less risky")\n',
    '    asks_trade = any(word in cleaned for word in trade_words)\n',
    '    system_terms = (\n',
    '        "sidebar", "menu", "setting", "settings", "phone ui", "api", "nlp", "llm",\n',
    '        "copy short", "copy full", "finder", "research", "other tab", "engine",\n',
    '        "train data", "pre original", "backtest", "profile", "question pattern",\n',
    '        "opens first", "startup page",\n',
    '    )\n',
    '    if not asks_trade and any(word in cleaned for word in system_terms):\n',
    '        intent = "system_feature_status"\n',
    '        score_pct = max(score_pct, 98.0)\n',
    '    elif not asks_trade and any(word in cleaned for word in ("prediction error", "average error", "avg error", "accuracy", "reliability", "confidence", "correctness")):\n',
    '        intent = "quality_confidence_check"\n',
    '        score_pct = max(score_pct, 96.0)\n',
    '    elif not asks_trade and "regime" in cleaned:\n',
    '        intent = "regime_bias_check"\n',
    '        score_pct = max(score_pct, 94.0)\n',
    '    elif not asks_trade and any(word in cleaned for word in ("data source", "latest data", "data update", "rows loaded", "how many rows", "api status")):\n',
    '        intent = "nearest_answer_fallback"\n',
    '        score_pct = max(score_pct, 92.0)\n',
    '\n',
    '    sim_score = max(best_example_sim, float(memory_best.get("ratio") or 0.0), float(prepared_best.get("ratio") or 0.0))\n',
    '    match_strength = "strong" if sim_score >= 0.75 or score_pct >= 72 else "medium" if sim_score >= 0.55 or score_pct >= 45 else "weak"\n',
    '    return {\n',
    '        "question": raw,\n',
    '        "raw_question": raw,\n',
    '        "normalized_question": cleaned,\n',
    '        "intent": intent,\n',
    '        "intent_label": INTENT_REGISTRY.get(intent, {}).get("label", "nearest useful answer"),\n',
    '        "confidence_of_intent": round(score_pct / 100.0, 2),\n',
    '        "intent_score": round(score_pct, 1),\n',
    '        "similarity_score": round(sim_score * 100, 1),\n',
    '        "neural_nlp_intent_score": round(min(100.0, score_pct * 0.82 + sim_score * 18.0), 1),\n',
    '        "deep_learning_similarity_score": round(min(100.0, sim_score * 86.0 + (score_pct / 100.0) * 14.0), 1),\n',
    '        "match_strength": match_strength,\n',
    '        "similar_question": memory_best.get("raw") or prepared_best.get("question") or best_example,\n',
    '        "target_price": prices[0] if prices else None,\n',
    '        "prices": prices,\n',
]
