"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Local AI Assistant Lite for the Home/Lunch tab.\n',
    '\n',
    'This module is intentionally local-only:\n',
    '- no OpenAI API\n',
    '- no paid/external AI API\n',
    '- no new ML model or prediction engine\n',
    '- uses existing Streamlit session metrics/history only\n',
    '\n',
    'The assistant is a tolerant local NLP + lightweight data-mining layer for\n',
    'EURUSD H1 day-trading explanations. It must explain the system decision, not\n',
    'override it.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import difflib\n',
    'import json\n',
    'import math\n',
    'import re\n',
    'import requests\n',
    'from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    'import streamlit as st\n',
    '\n',
    'UNIQUE = "20260612_ai_lite_nlp_v3"\n',
    'MAX_HISTORY_SCAN = 200\n',
    'MAX_CHAT_MEMORY = 20\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Safe helpers\n',
    '# ---------------------------------------------------------------------------\n',
    'def _num(v: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    try:\n',
    '        if v is None or v == "":\n',
    '            return default\n',
    '        if isinstance(v, str):\n',
    '            cleaned = v.replace("%", "").replace(",", "").strip()\n',
    '            if cleaned in {"-", "na", "n/a", "none"}:\n',
    '                return default\n',
    '            v = cleaned\n',
    '        x = float(v)\n',
    '        return x if math.isfinite(x) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _safe_str(v: Any, default: str = "-") -> str:\n',
    '    try:\n',
    '        if v is None:\n',
    '            return default\n',
    '        if isinstance(v, float) and not math.isfinite(v):\n',
    '            return default\n',
    '        s = str(v).strip()\n',
    '        return s if s else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _fmt_num(v: Any, digits: int = 5, default: str = "-") -> str:\n',
    '    x = _num(v)\n',
    '    if x is None:\n',
    '        return default\n',
    '    if abs(x) < 10:\n',
    '        return f"{x:.{digits}f}"\n',
    '    return f"{x:.1f}"\n',
    '\n',
    '\n',
    'def _fmt_score(v: Any, default: str = "-") -> str:\n',
    '    x = _num(v)\n',
    '    if x is None:\n',
    '        return default\n',
    '    return f"{x:.2f}"\n',
    '\n',
    '\n',
    'def _is_df(obj: Any) -> bool:\n',
    '    return isinstance(obj, pd.DataFrame) and not obj.empty\n',
    '\n',
    '\n',
    'def _norm_key(k: Any) -> str:\n',
    '    return re.sub(r"[^a-z0-9]+", "", str(k).lower())\n',
    '\n',
    '\n',
    'def _json_safe(obj: Any, rows: int = 40) -> Any:\n',
    '    try:\n',
    '        if isinstance(obj, pd.DataFrame):\n',
    '            return obj.head(rows).to_dict("records")\n',
    '        if isinstance(obj, pd.Series):\n',
    '            return obj.to_dict()\n',
    '        if isinstance(obj, (pd.Timestamp, np.datetime64)):\n',
    '            return str(obj)\n',
    '        if isinstance(obj, dict):\n',
    '            return {str(k): _json_safe(v, rows) for k, v in obj.items() if k != "flat"}\n',
    '        if isinstance(obj, (list, tuple)):\n',
    '            return [_json_safe(v, rows) for v in list(obj)[:rows]]\n',
    '        if isinstance(obj, (np.integer,)):\n',
    '            return int(obj)\n',
    '        if isinstance(obj, (np.floating,)):\n',
    '            y = float(obj)\n',
    '            return y if math.isfinite(y) else None\n',
    '        return obj\n',
    '    except Exception:\n',
    '        return str(obj)\n',
    '\n',
    '\n',
    'def _flat_dict(obj: Any, prefix: str = "", depth: int = 0, limit: int = 900) -> Dict[str, Any]:\n',
    '    out: Dict[str, Any] = {}\n',
    '    if depth > 5 or len(out) > limit:\n',
    '        return out\n',
    '    if isinstance(obj, dict):\n',
    '        for k, v in obj.items():\n',
    '            if len(out) >= limit:\n',
    '                break\n',
    '            key = f"{prefix}.{k}" if prefix else str(k)\n',
    '            if isinstance(v, dict):\n',
    '                out.update(_flat_dict(v, key, depth + 1, limit))\n',
    '            elif not isinstance(v, pd.DataFrame):\n',
    '                out[key] = v\n',
    '    return out\n',
    '\n',
    '\n',
    'def _find_col(df: pd.DataFrame, aliases: Iterable[str]) -> Optional[str]:\n',
    '    if not _is_df(df):\n',
    '        return None\n',
    '    norm = {_norm_key(c): c for c in df.columns}\n',
    '    for alias in aliases:\n',
    '        n = _norm_key(alias)\n',
    '        if n in norm:\n',
    '            return norm[n]\n',
    '    for ncol, col in norm.items():\n',
    '        for alias in aliases:\n',
    '            na = _norm_key(alias)\n',
    '            if na and na in ncol:\n',
    '                return col\n',
    '    return None\n',
    '\n',
    '\n',
    'def _last_value_from_df(df: pd.DataFrame, aliases: Iterable[str]) -> Any:\n',
    '    if not _is_df(df):\n',
    '        return None\n',
    '    col = _find_col(df, aliases)\n',
    '    if not col:\n',
    '        return None\n',
    '    try:\n',
    '        vals = df[col].dropna()\n',
    '        if vals.empty:\n',
    '            return None\n',
    '        return vals.iloc[-1]\n',
    '    except Exception:\n',
    '        return None\n',
    '\n',
    '\n',
    'def _find_value(flat: Dict[str, Any], aliases: Iterable[str], default: Any = None) -> Any:\n',
    '    norm = {_norm_key(k): v for k, v in flat.items()}\n',
    '    for alias in aliases:\n',
    '        na = _norm_key(alias)\n',
    '        if na in norm:\n',
    '            return norm[na]\n',
    '    for k, v in norm.items():\n',
    '        for alias in aliases:\n',
    '            na = _norm_key(alias)\n',
    '            if na and na in k:\n',
    '                return v\n',
    '    return default\n',
    '\n',
    '\n',
    'def _direction_from_regime(regime: Any) -> str:\n',
    '    s = _safe_str(regime, "").upper()\n',
    '    if "BEAR" in s:\n',
    '        return "SELL"\n',
    '    if "BULL" in s:\n',
    '        return "BUY"\n',
    '    if "RANGE" in s or "SIDE" in s or "COMPRESSION" in s:\n',
    '        return "WAIT"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _first_df(keys: Iterable[str]) -> pd.DataFrame:\n',
    '    for key in keys:\n',
    '        try:\n',
    '            obj = st.session_state.get(key)\n',
    '            if _is_df(obj):\n',
    '                return obj.copy()\n',
    '        except Exception:\n',
    '            continue\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _collect_dataframes() -> Dict[str, pd.DataFrame]:\n',
    '    # Return references only; do not copy every dataframe on mobile.\n',
    '    dfs: Dict[str, pd.DataFrame] = {}\n',
    '    try:\n',
    '        for k, v in list(st.session_state.items()):\n',
    '            if _is_df(v):\n',
    '                dfs[str(k)] = v\n',
    '    except Exception:\n',
    '        pass\n',
    '    return dfs\n',
    '\n',
    '\n',
    'def _select_best_df(name_tokens: Sequence[str], column_tokens: Sequence[str]) -> pd.DataFrame:\n',
    '    best_key = ""\n',
    '    best_score = -1\n',
    '    best_df = pd.DataFrame()\n',
    '    for key, df in _collect_dataframes().items():\n',
    '        score = 0\n',
    '        low_key = key.lower()\n',
    '        low_cols = " ".join(map(str, df.columns)).lower()\n',
    '        score += sum(3 for t in name_tokens if t in low_key)\n',
    '        score += sum(1 for t in column_tokens if t in low_cols)\n',
    '        if score > best_score:\n',
    '            best_key, best_df, best_score = key, df.copy(), score\n',
    '    return best_df if best_score > 0 else pd.DataFrame()\n',
    '\n',
    '\n',
    'def _find_value_any(flat: Dict[str, Any], df_list: Sequence[pd.DataFrame], aliases: Iterable[str], default: Any = None) -> Any:\n',
    '    v = _find_value(flat, aliases, None)\n',
    '    if v is not None:\n',
    '        return v\n',
    '    for df in df_list:\n',
    '        v = _last_value_from_df(df, aliases)\n',
    '        if v is not None:\n',
    '            return v\n',
    '    return default\n',
    '\n',
    '\n',
    'def _extract_prediction_path(flat: Dict[str, Any], predicted_df: pd.DataFrame, ohlc_df: pd.DataFrame) -> Dict[str, Any]:\n',
    '    path: List[float] = []\n',
    '    high_vals: List[float] = []\n',
    '    low_vals: List[float] = []\n',
    '\n',
    '    list_aliases = [\n',
    '        "prediction_path", "predicted_path", "blue_future_path", "lightblue_path",\n',
    '        "future_path", "forecast_path", "yellow_latest_path",\n',
    '    ]\n',
    '    raw_path = _find_value(flat, list_aliases, None)\n',
    '    if isinstance(raw_path, (list, tuple)):\n',
    '        for item in raw_path[:10]:\n',
    '            if isinstance(item, dict):\n',
    '                val = _find_value(item, ["close", "price", "predicted_close", "estimated_price_close"], None)\n',
    '            else:\n',
    '                val = item\n',
    '            x = _num(val)\n',
    '            if x is not None:\n',
    '                path.append(x)\n',
    '\n',
    '    if _is_df(predicted_df):\n',
    '        ccol = _find_col(predicted_df, ["close", "predicted_close", "forecast_close", "path_close", "price", "estimated_price_close"])\n',
    '        hcol = _find_col(predicted_df, ["high", "upper", "upper_band", "Upper Bound", "predicted_high"])\n',
    '        lcol = _find_col(predicted_df, ["low", "lower", "lower_band", "Lower Bound", "predicted_low"])\n',
    '        try:\n',
    '            if ccol:\n',
    '                path = [float(x) for x in pd.to_numeric(predicted_df[ccol], errors="coerce").dropna().head(10).tolist()]\n',
    '            if hcol:\n',
    '                high_vals = [float(x) for x in pd.to_numeric(predicted_df[hcol], errors="coerce").dropna().head(10).tolist()]\n',
    '            if lcol:\n',
    '                low_vals = [float(x) for x in pd.to_numeric(predicted_df[lcol], errors="coerce").dropna().head(10).tolist()]\n',
    '        except Exception:\n',
    '            pass\n',
    '\n',
    '    upper = _num(_find_value(flat, ["upper_band", "predicted_high", "estimated_price_high", "high_band"], None))\n',
    '    lower = _num(_find_value(flat, ["lower_band", "predicted_low", "estimated_price_low", "low_band"], None))\n',
    '    if upper is None and high_vals:\n',
    '        upper = max(high_vals)\n',
    '    if lower is None and low_vals:\n',
    '        lower = min(low_vals)\n',
    '\n',
    '    last_close = None\n',
    '    if _is_df(ohlc_df):\n',
    '        ccol = _find_col(ohlc_df, ["close", "c"])\n',
    '        if ccol:\n',
    '            try:\n',
    '                last_close = float(pd.to_numeric(ohlc_df[ccol], errors="coerce").dropna().iloc[-1])\n',
    '            except Exception:\n',
    '                last_close = None\n',
    '\n',
    '    if not path:\n',
    '        est_close = _num(_find_value(flat, ["estimated_price_close", "forecast_close", "next_close"], None))\n',
    '        if est_close is not None:\n',
    '            path = [est_close]\n',
    '    if not path and last_close is not None:\n',
    '        path = [last_close]\n',
    '\n',
    '    direction = "WAIT"\n',
    '    if last_close is not None and path:\n',
    '        if path[0] > last_close:\n',
    '            direction = "BUY"\n',
    '        elif path[0] < last_close:\n',
    '            direction = "SELL"\n',
    '    return {"path": path, "upper_band": upper, "lower_band": lower, "last_close": last_close, "path_direction": direction}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Context builder with aliases\n',
    '# ---------------------------------------------------------------------------\n',
    'def build_ai_context_from_existing_data() -> Dict[str, Any]:\n',
    '    """Collect existing metrics/history with many aliases and no hard failures."""\n',
    '    flat: Dict[str, Any] = {}\n',
    '\n',
    '    known_dict_keys = [\n',
    '        "dv_pp_base_result", "lunch_5layer_powerbi_result", "dv_pp_regime_summary",\n',
    '        "dv_pp_bt_summary", "final_merged_intelligence_pack_20260612",\n',
    '        "final_synced_research_merge_pack_20260612", "nylo_unified_home_sync_20260612",\n',
    '        "news_nlp_knn_greedy_pack_20260612", "quant_structure_pack_20260612",\n',
    '        "research_pack_20260612", "ai_lite_context", "home_context", "metric_context",\n',
    '        "data_visualization_context", "powerbi_context", "last_result", "current_result",\n',
    '    ]\n',
    '    for key in known_dict_keys:\n',
    '        val = st.session_state.get(key)\n',
    '        if isinstance(val, dict):\n',
    '            flat.update(_flat_dict(val, key))\n',
    '\n',
    '    try:\n',
    '        for k, v in list(st.session_state.items()):\n',
    '            if isinstance(v, dict) and len(flat) < 3500:\n',
    '                flat.update(_flat_dict(v, str(k)))\n',
    '            elif isinstance(v, (str, int, float, bool)) and len(str(v)) < 160:\n',
    '                flat[str(k)] = v\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '    ohlc_df = _first_df(["dv_pp_df", "lunch_5layer_powerbi_df", "last_df", "ohlc_df", "df"])\n',
    '    predicted_df = _first_df(["dv_pp_predicted", "dv_pp_lightblue_path", "prediction_path_df", "predicted_df", "forecast_df"])\n',
    '    history_df = _first_df(["history_df", "full_metric_history_df", "dv_pp_bt_hist", "ny_london_overlap_hourly_history_v6", "ny_london_overlap_history", "lunch_history_df"])\n',
    '    regime_history_df = _first_df(["regime_history_df", "dv_pp_regime_hist", "major_regime_history_df"])\n',
    '    overlap_history_df = _first_df(["overlap_history_df", "ny_london_overlap_hourly_history_v6", "ny_london_overlap_history", "ny_london_overlap_hourly_history_v5"])\n',
    '    prediction_history_df = _first_df(["prediction_history_df", "dv_pp_bt_hist", "dv_pp_projection_history", "prediction_vs_actual_history_df"])\n',
    '\n',
    '    if not _is_df(history_df):\n',
    '        history_df = _select_best_df(["history", "metric"], ["time", "decision", "score", "entry", "risk"])\n',
    '    if not _is_df(regime_history_df):\n',
    '        regime_history_df = _select_best_df(["regime"], ["time", "regime", "direction"])\n',
    '    if not _is_df(prediction_history_df):\n',
    '        prediction_history_df = _select_best_df(["prediction", "backtest", "actual"], ["actual", "pred", "error", "close"])\n',
    '\n',
    '    df_list = [ohlc_df, predicted_df, history_df, regime_history_df, overlap_history_df, prediction_history_df]\n',
    '    pred = _extract_prediction_path(flat, predicted_df, ohlc_df)\n',
    '\n',
    '    regime = _find_value_any(flat, df_list, ["regime", "current_regime", "unified_regime", "PowerBI regime", "major_regime", "regime_direction", "master_regime"], "-")\n',
    '    direction = _find_value_any(flat, df_list, ["direction", "Direction", "master_direction", "bias", "system_bias", "forecast_direction"], None)\n',
    '    if not direction or _safe_str(direction) == "-":\n',
    '        direction = _direction_from_regime(regime)\n',
    '\n',
    '    current: Dict[str, Any] = {\n',
    '        "symbol": _find_value_any(flat, df_list, ["symbol", "Symbol", "ticker"], "EURUSD"),\n',
    '        "timeframe": _find_value_any(flat, df_list, ["timeframe", "Timeframe", "tf"], "H1"),\n',
    '        "decision": _find_value_any(flat, df_list, ["decision", "Decision", "system_decision", "master_decision", "final_decision", "best_current_opportunity"], "data not available yet"),\n',
    '        "direction": _safe_str(direction, "WAIT").upper(),\n',
    '        "regime": _safe_str(regime, "-"),\n',
    '        "regime_direction": _direction_from_regime(regime),\n',
    '        "entry_score": _num(_find_value_any(flat, df_list, ["entry_score", "entry", "Entry Score", "Entry /10", "Entry Strength", "entry_strength", "Entry Pressure"])),\n',
    '        "tp_score": _num(_find_value_any(flat, df_list, ["tp_score", "TP Score", "TP /10", "TP Quality", "target_quality", "tp_quality"])),\n',
    '        "exit_risk": _num(_find_value_any(flat, df_list, ["exit_risk", "Exit Risk", "Exit Risk /10", "risk_score", "Exit Risk Score"])),\n',
    '        "master_score": _num(_find_value_any(flat, df_list, ["master_score", "Master Score", "Master /10", "master /10", "Score /10"])),\n',
    '        "hold_score": _num(_find_value_any(flat, df_list, ["hold_score", "Hold Score", "Hold /10", "Hold Safety"])),\n',
    '        "buy_pressure": _num(_find_value_any(flat, df_list, ["buy_pressure", "BUY Pressure", "Buy Pressure", "BUY Pressure /10"])),\n',
    '        "sell_pressure": _num(_find_value_any(flat, df_list, ["sell_pressure", "SELL Pressure", "Sell Pressure", "SELL Pressure /10"])),\n',
    '        "prediction_direction": _safe_str(_find_value_any(flat, df_list, ["prediction_direction", "forecast_direction", "Prediction Direction", "Forecast Direction"], pred.get("path_direction", "-")), "-").upper(),\n',
    '        "forecast_confidence": _num(_find_value_any(flat, df_list, ["forecast_confidence", "Forecast Confidence", "Forecast Confidence %", "confidence_pct", "confidence" ])),\n',
    '        "prediction_vs_actual_error": _num(_find_value_any(flat, df_list, ["prediction_vs_actual_error", "prediction_error_pct", "Prediction vs Actual Close Error %", "avg_abs_close_error_pct", "close_error_pct"])),\n',
    '        "direction_accuracy": _num(_find_value_any(flat, df_list, ["direction_accuracy", "direction_accuracy_pct", "Direction Accuracy %"])),\n',
    '        "knn_priority": _find_value_any(flat, df_list, ["knn_priority", "KNN Priority", "KNN Rank"], None),\n',
    '        "greedy_priority": _find_value_any(flat, df_list, ["greedy_priority", "Greedy Priority", "Greedy Rank"], None),\n',
    '        "market_quality": _num(_find_value_any(flat, df_list, ["market_quality", "market_quality_score", "Market Quality Score", "quality_score"])),\n',
    '        "best_opportunity_rows": _find_value_any(flat, df_list, ["best_opportunity_rows", "best_rows", "best_entry_opportunity_rows"], None),\n',
    '        "last_close": pred.get("last_close"),\n',
    '        "prediction_path": pred.get("path", []),\n',
    '        "upper_band": pred.get("upper_band"),\n',
    '        "lower_band": pred.get("lower_band"),\n',
    '        "predicted_high": _num(_find_value_any(flat, df_list, ["predicted_high", "estimated_price_high", "prediction_high"], pred.get("upper_band"))),\n',
    '        "predicted_low": _num(_find_value_any(flat, df_list, ["predicted_low", "estimated_price_low", "prediction_low"], pred.get("lower_band"))),\n',
    '        "estimated_price_open": _num(_find_value_any(flat, df_list, ["estimated_price_open", "prediction_open", "forecast_open"])),\n',
    '        "estimated_price_close": _num(_find_value_any(flat, df_list, ["estimated_price_close", "prediction_close", "forecast_close"], pred.get("path", [None])[0] if pred.get("path") else None)),\n',
    '    }\n',
    '\n',
    '    # Last time/current hour from available OHLC/history tables.\n',
    '    for df in [ohlc_df, history_df, overlap_history_df, prediction_history_df]:\n',
    '        if _is_df(df):\n',
    '            tcol = _find_col(df, ["time", "datetime", "timestamp", "date"])\n',
    '            if tcol:\n',
    '                try:\n',
    '                    ts = pd.to_datetime(df[tcol], errors="coerce").dropna().iloc[-1]\n',
    '                    current["last_time"] = str(ts)\n',
    '                    current["current_hour"] = int(ts.hour)\n',
    '                    break\n',
    '                except Exception:\n',
    '                    pass\n',
    '\n',
    '    missing_fields = []\n',
    '    for key in ["entry_score", "tp_score", "exit_risk", "buy_pressure", "sell_pressure", "forecast_confidence", "last_close", "upper_band", "lower_band"]:\n',
    '        if current.get(key) in (None, "", "-"):\n',
    '            missing_fields.append(key)\n',
    '\n',
    '    data_available = any(current.get(k) is not None for k in ["entry_score", "tp_score", "exit_risk", "last_close", "forecast_confidence"]) or any(_is_df(x) for x in df_list)\n',
    '    return {\n',
    '        "data_available": bool(data_available),\n',
    '        "current": current,\n',
    '        "flat": flat,\n',
    '        "ohlc_df": ohlc_df,\n',
    '        "predicted_df": predicted_df,\n',
    '        "history_df": history_df,\n',
    '        "regime_history_df": regime_history_df,\n',
    '        "overlap_history_df": overlap_history_df,\n',
    '        "prediction_history_df": prediction_history_df,\n',
    '        "missing_fields": missing_fields,\n',
    '        "missing_message": "Click Run Calculation first for stronger context; available fields are still used.",\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Local NLP / grammar recognition / similar-question matching\n',
    '# ---------------------------------------------------------------------------\n',
    'TYPO_REPLACEMENTS: List[Tuple[str, str]] = [\n',
    '    (r"\\bnlp\\s+didnot\\s+foud\\b", "nlp did not find"),\n',
    '    (r"\\bnlp\\s+not\\s+found\\b", "nlp did not find"),\n',
    '    (r"\\bdata\\s+not\\s+gave\\b", "data not given"),\n',
    '    (r"\\bdidnot\\b", "did not"),\n',
    '    (r"\\bfoud\\b", "find"),\n',
    '    (r"\\bfoudn\\b", "found"),\n',
]
