"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        "horizon": horizon,\n',
    '        "hours": horizon.get("hours"),\n',
    '        "direction_keyword": side,\n',
    '        "required_data_source": "existing Home/Lunch/Data Visualization metrics + history",\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Lightweight data mining functions\n',
    '# ---------------------------------------------------------------------------\n',
    'def _metric(c: Dict[str, Any], name: str, fallback: float = 0.0) -> float:\n',
    '    return float(_num(c.get(name), fallback) or fallback)\n',
    '\n',
    '\n',
    'def find_similar_setup_proxy(context: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    c = context.get("current", {})\n',
    '    hist = context.get("history_df", pd.DataFrame())\n',
    '    if not _is_df(hist):\n',
    '        return {"available": False, "insight": "No exact setup history; using current score/band proxy."}\n',
    '    df = hist.tail(MAX_HISTORY_SCAN).copy()\n',
    '    num_map = {\n',
    '        "entry_score": ["entry_score", "Entry Score", "Entry /10", "Entry Strength", "Entry Pressure"],\n',
    '        "tp_score": ["tp_score", "TP Score", "TP /10", "TP Quality"],\n',
    '        "exit_risk": ["exit_risk", "Exit Risk", "Exit Risk /10"],\n',
    '        "buy_pressure": ["buy_pressure", "BUY Pressure", "Buy Pressure"],\n',
    '        "sell_pressure": ["sell_pressure", "SELL Pressure", "Sell Pressure"],\n',
    '        "forecast_confidence": ["forecast_confidence", "Forecast Confidence", "confidence"],\n',
    '    }\n',
    '    cols = {k: _find_col(df, aliases) for k, aliases in num_map.items()}\n',
    '    rows: List[Dict[str, Any]] = []\n',
    '    for idx, row in df.iterrows():\n',
    '        dist = 0.0\n',
    '        used = 0\n',
    '        for key, col in cols.items():\n',
    '            if not col:\n',
    '                continue\n',
    '            a = _num(c.get(key))\n',
    '            b = _num(row.get(col))\n',
    '            if a is None or b is None:\n',
    '                continue\n',
    '            scale = 100.0 if max(abs(a), abs(b)) > 15 else 10.0\n',
    '            dist += min(1.0, abs(a - b) / max(1.0, scale))\n',
    '            used += 1\n',
    '        bonus = 0.0\n',
    '        row_txt = " ".join(map(str, row.values)).upper()\n',
    '        if c.get("regime") and _safe_str(c.get("regime")).upper() in row_txt:\n',
    '            bonus += 0.12\n',
    '        if c.get("direction") and _safe_str(c.get("direction")).upper() in row_txt:\n',
    '            bonus += 0.08\n',
    '        if used:\n',
    '            sim = max(0.0, 1.0 - dist / used + bonus)\n',
    '            rows.append({"idx": int(idx) if isinstance(idx, (int, np.integer)) else len(rows), "similarity": round(min(sim, 1.0) * 100, 1), "row": row})\n',
    '    if not rows:\n',
    '        return {"available": False, "insight": "History exists but matching columns were not found; using current metrics proxy."}\n',
    '    top = sorted(rows, key=lambda x: x["similarity"], reverse=True)[:5]\n',
    '    avg = sum(x["similarity"] for x in top) / len(top)\n',
    '    label = "strong" if avg >= 75 else "medium" if avg >= 55 else "weak"\n',
    '    return {"available": True, "count": len(top), "avg_similarity": round(avg, 1), "label": label, "top_rows": top,\n',
    '            "insight": f"Similar setup proxy: {len(top)} recent rows matched with {label} similarity ({avg:.0f}%)."}\n',
    '\n',
    '\n',
    'def mine_similar_hour(context: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    c = context.get("current", {})\n',
    '    hour = c.get("current_hour")\n',
    '    df = context.get("overlap_history_df", pd.DataFrame())\n',
    '    if not _is_df(df):\n',
    '        df = context.get("history_df", pd.DataFrame())\n',
    '    if not _is_df(df) or hour is None:\n',
    '        return {"available": False, "insight": "No same-hour history; using current H1 snapshot."}\n',
    '    work = df.tail(MAX_HISTORY_SCAN).copy()\n',
    '    hcol = _find_col(work, ["hour", "Hour"])\n',
    '    tcol = _find_col(work, ["time", "datetime", "timestamp", "date"])\n',
    '    if not hcol and tcol:\n',
    '        try:\n',
    '            work["_ai_hour"] = pd.to_datetime(work[tcol], errors="coerce").dt.hour\n',
    '            hcol = "_ai_hour"\n',
    '        except Exception:\n',
    '            hcol = None\n',
    '    if not hcol:\n',
    '        return {"available": False, "insight": "History has no hour column; using non-hour setup proxy."}\n',
    '    try:\n',
    '        same = work[pd.to_numeric(work[hcol], errors="coerce") == float(hour)].tail(30)\n',
    '    except Exception:\n',
    '        same = pd.DataFrame()\n',
    '    if same.empty:\n',
    '        return {"available": False, "insight": f"No recent rows for hour {hour}; use current setup only."}\n',
    '    scol = _find_col(same, ["score", "Score", "Score /10", "Master Score", "Entry Pressure"])\n',
    '    avg_score = None\n',
    '    if scol:\n',
    '        vals = pd.to_numeric(same[scol], errors="coerce").dropna()\n',
    '        if not vals.empty:\n',
    '            avg_score = float(vals.mean())\n',
    '    label = "good" if avg_score is not None and avg_score >= 7 else "watch" if avg_score is not None and avg_score >= 5 else "unclear"\n',
    '    return {"available": True, "hour": hour, "rows": int(len(same)), "avg_score": avg_score,\n',
    '            "insight": f"Same-hour mining: {len(same)} recent rows for hour {hour}; hour quality is {label}."}\n',
    '\n',
    '\n',
    'def mine_regime_behavior(context: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    c = context.get("current", {})\n',
    '    regime = _safe_str(c.get("regime"), "-")\n',
    '    df = context.get("regime_history_df", pd.DataFrame())\n',
    '    regime_dir = _direction_from_regime(regime)\n',
    '    if not _is_df(df):\n',
    '        return {"available": False, "insight": f"Regime proxy: {regime} points to {regime_dir}, but regime history table is not available."}\n',
    '    work = df.tail(MAX_HISTORY_SCAN)\n',
    '    rcol = _find_col(work, ["regime", "current_regime", "major_regime"])\n',
    '    dcol = _find_col(work, ["direction", "bias", "Decision", "decision"])\n',
    '    count = len(work)\n',
    '    if rcol:\n',
    '        try:\n',
    '            same = work[work[rcol].astype(str).str.upper().str.contains(re.escape(regime.upper()), na=False)]\n',
    '            count = len(same) if len(same) else count\n',
    '            work = same if len(same) else work\n',
    '        except Exception:\n',
    '            pass\n',
    '    common = regime_dir\n',
    '    if dcol and len(work):\n',
    '        try:\n',
    '            common = str(work[dcol].astype(str).str.upper().value_counts().idxmax())\n',
    '        except Exception:\n',
    '            common = regime_dir\n',
    '    return {"available": True, "rows": int(count), "favored": common,\n',
    '            "insight": f"Regime history: current {regime} recently favored {common} across {count} available rows."}\n',
    '\n',
    '\n',
    'def mine_prediction_error(context: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    c = context.get("current", {})\n',
    '    df = context.get("prediction_history_df", pd.DataFrame())\n',
    '    err = _num(c.get("prediction_vs_actual_error"))\n',
    '    acc = _num(c.get("direction_accuracy"))\n',
    '    if _is_df(df):\n',
    '        ecol = _find_col(df, ["error", "close_error", "avg_abs_close_error_pct", "prediction_vs_actual_error"])\n',
    '        acol = _find_col(df, ["direction_accuracy", "accuracy", "Direction Accuracy %"])\n',
    '        try:\n',
    '            if ecol:\n',
    '                vals = pd.to_numeric(df[ecol], errors="coerce").dropna().tail(30)\n',
    '                if not vals.empty:\n',
    '                    err = float(vals.mean())\n',
    '            if acol:\n',
    '                vals = pd.to_numeric(df[acol], errors="coerce").dropna().tail(30)\n',
    '                if not vals.empty:\n',
    '                    acc = float(vals.mean())\n',
    '        except Exception:\n',
    '            pass\n',
    '    reliability = "normal"\n',
    '    if acc is not None and acc < 48:\n',
    '        reliability = "weak"\n',
    '    elif err is not None and err > 0.08:\n',
    '        reliability = "weak"\n',
    '    elif acc is not None and acc >= 55:\n',
    '        reliability = "better"\n',
    '    detail = []\n',
    '    if err is not None:\n',
    '        detail.append(f"avg error {err:.4g}")\n',
    '    if acc is not None:\n',
    '        detail.append(f"direction accuracy {acc:.1f}%")\n',
    '    if not detail:\n',
    '        detail.append("no exact prediction-error rows")\n',
    '    return {"available": bool(_is_df(df) or err is not None or acc is not None), "reliability": reliability, "error": err, "accuracy": acc,\n',
    '            "insight": "Prediction mining: " + ", ".join(detail) + f"; reliability is {reliability}."}\n',
    '\n',
    '\n',
    'def mine_tp_reach_proxy(context: Dict[str, Any], side: str) -> Dict[str, Any]:\n',
    '    c = context.get("current", {})\n',
    '    side = (side or "WAIT").upper()\n',
    '    path = c.get("prediction_path") or []\n',
    '    path_vals = [_num(x) for x in path]\n',
    '    path_vals = [x for x in path_vals if x is not None]\n',
    '    last_close = _num(c.get("last_close"))\n',
    '    upper = _num(c.get("upper_band") or c.get("predicted_high"))\n',
    '    lower = _num(c.get("lower_band") or c.get("predicted_low"))\n',
    '    tp_score = _metric(c, "tp_score", 5)\n',
    '    conf = _metric(c, "forecast_confidence", 50)\n',
    '\n',
    '    if side == "SELL":\n',
    '        tp1 = lower if lower is not None else min(path_vals) if path_vals else (last_close - 0.0008 if last_close else None)\n',
    '        tp2 = (min(path_vals) if path_vals else None) or (tp1 - 0.0005 if tp1 else None)\n',
    '    elif side == "BUY":\n',
    '        tp1 = upper if upper is not None else max(path_vals) if path_vals else (last_close + 0.0008 if last_close else None)\n',
    '        tp2 = (max(path_vals) if path_vals else None) or (tp1 + 0.0005 if tp1 else None)\n',
    '    else:\n',
    '        tp1 = None\n',
    '        tp2 = None\n',
    '    support = "strong" if tp_score >= 6.5 and conf >= 58 else "medium" if tp_score >= 5 else "weak"\n',
    '    zone = "-"\n',
    '    if tp1 is not None:\n',
    '        zone = f"TP1 {_fmt_num(tp1)}"\n',
    '        if tp2 is not None and abs(float(tp2) - float(tp1)) > 0.00002 and support != "weak":\n',
    '            zone += f" / TP2 {_fmt_num(tp2)}"\n',
    '    return {"available": tp1 is not None, "side": side, "tp1": tp1, "tp2": tp2, "support": support,\n',
    '            "zone": zone, "insight": f"TP reach proxy for {side}: {zone}; support is {support}."}\n',
    '\n',
    '\n',
    'def mine_priority_rows(context: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    c = context.get("current", {})\n',
    '    rows_obj = c.get("best_opportunity_rows")\n',
    '    if isinstance(rows_obj, pd.DataFrame) and not rows_obj.empty:\n',
    '        return {"available": True, "insight": f"Priority mining: best opportunity table has {len(rows_obj)} rows; read top row first."}\n',
    '    if isinstance(rows_obj, list) and rows_obj:\n',
    '        return {"available": True, "insight": f"Priority mining: {len(rows_obj)} best opportunity rows found; use row 1 first."}\n',
    '    knn = c.get("knn_priority")\n',
    '    greedy = c.get("greedy_priority")\n',
    '    if knn is not None or greedy is not None:\n',
    '        return {"available": True, "insight": f"Priority mining: KNN={_safe_str(knn, \'-\')} / Greedy={_safe_str(greedy, \'-\')}."}\n',
    '    return {"available": False, "insight": "No KNN/Greedy priority row found; using score and regime proxy."}\n',
    '\n',
    '\n',
    'def _analysis_mining_summary(context: Dict[str, Any], side: Optional[str] = None) -> str:\n',
    '    """Short descriptive/predictive/prescriptive insight using existing data only.\n',
    '\n',
    '    This is not a new prediction engine. It summarizes the already-computed\n',
    '    metrics/path/history so the text input answer always has a useful local\n',
    '    analytics explanation.\n',
    '    """\n',
    '    c = context.get("current", {})\n',
    '    try:\n',
    '        decision = _safe_str(c.get("decision"), "-")\n',
    '        regime = _safe_str(c.get("regime"), "-")\n',
    '        pressure = _pressure_bias(c)\n',
    '        safer, reason = _safer_bias(c)\n',
    '        side = (side or safer or "WAIT").upper()\n',
    '        pred_side = _safe_str(c.get("prediction_direction"), "-").upper()\n',
    '        path = c.get("prediction_path") or []\n',
    '        last_close = _num(c.get("last_close"))\n',
    '        next_price = _num(path[0]) if path else _num(c.get("estimated_price_close"))\n',
    '        band = ""\n',
    '        if c.get("lower_band") is not None or c.get("upper_band") is not None:\n',
    '            band = f", band {_fmt_num(c.get(\'lower_band\'))}-{_fmt_num(c.get(\'upper_band\'))}"\n',
    '        if next_price is not None and last_close is not None:\n',
    '            projected = "BUY/up" if next_price > last_close else "SELL/down" if next_price < last_close else "flat/WAIT"\n',
    '            predictive = f"predictive={projected} {_fmt_num(last_close)}→{_fmt_num(next_price)}{band}"\n',
    '        else:\n',
    '            predictive = f"predictive={pred_side if pred_side in {\'BUY\',\'SELL\'} else \'path not ready\'}{band}"\n',
    '        acc = _num(c.get("direction_accuracy"))\n',
    '        err = _num(c.get("prediction_vs_actual_error"))\n',
    '        accuracy = []\n',
    '        if acc is not None:\n',
    '            accuracy.append(f"accuracy {acc:.1f}%")\n',
    '        if err is not None:\n',
    '            accuracy.append(f"error {err:.4g}")\n',
    '        acc_txt = ", ".join(accuracy) if accuracy else "accuracy proxy from current scores"\n',
    '        action = "WAIT/PROTECT" if _risk_level(c) == "HIGH" or safer == "WAIT" else f"{side} allowed only if system decision agrees"\n',
    '        return (\n',
    '            f"Descriptive={decision}/{regime}/pressure {pressure}; "\n',
    '            f"{predictive}; prescriptive={action}; {acc_txt}."\n',
    '        )\n',
    '    except Exception:\n',
    '        return "Descriptive/predictive/prescriptive proxy used from available metrics."\n',
    '\n',
    '\n',
    'def fallback_mining(context: Dict[str, Any], side: Optional[str] = None) -> Dict[str, Any]:\n',
    '    checks = [\n',
    '        find_similar_setup_proxy(context),\n',
    '        mine_similar_hour(context),\n',
    '        mine_regime_behavior(context),\n',
    '        mine_prediction_error(context),\n',
    '        mine_priority_rows(context),\n',
    '    ]\n',
    '    if side:\n',
    '        checks.insert(2, mine_tp_reach_proxy(context, side))\n',
    '    summary = _analysis_mining_summary(context, side)\n',
    '    for chk in checks:\n',
    '        if chk.get("available"):\n',
    '            chk = dict(chk)\n',
    '            base = _safe_str(chk.get("insight"), "")\n',
    '            chk["insight"] = (summary + " " + base).strip()\n',
    '            return chk\n',
    '    c = context.get("current", {})\n',
    '    parts = []\n',
    '    if c.get("prediction_path"):\n',
    '        parts.append("prediction path")\n',
    '    if c.get("upper_band") or c.get("lower_band"):\n',
    '        parts.append("upper/lower band")\n',
    '    if c.get("tp_score") is not None:\n',
    '        parts.append("TP quality")\n',
    '    if c.get("exit_risk") is not None:\n',
    '        parts.append("exit risk")\n',
    '    if c.get("forecast_confidence") is not None:\n',
    '        parts.append("forecast confidence")\n',
    '    if c.get("regime"):\n',
    '        parts.append("regime direction")\n',
    '    if c.get("buy_pressure") is not None or c.get("sell_pressure") is not None:\n',
    '        parts.append("buy/sell pressure")\n',
    '    if c.get("entry_score") is not None:\n',
    '        parts.append("entry score")\n',
    '    if c.get("decision"):\n',
    '        parts.append("system decision")\n',
    '    summary = _analysis_mining_summary(context, side)\n',
    '    return {"available": bool(parts), "insight": summary + " Fallback proxy used: " + (", ".join(parts[:5]) if parts else "no strong data yet") + "."}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Decision / answer engine\n',
    '# ---------------------------------------------------------------------------\n',
    'def _pressure_bias(c: Dict[str, Any]) -> str:\n',
    '    buy = _num(c.get("buy_pressure"))\n',
    '    sell = _num(c.get("sell_pressure"))\n',
    '    if buy is not None and sell is not None:\n',
    '        if buy >= sell + 0.18:\n',
    '            return "BUY"\n',
    '        if sell >= buy + 0.18:\n',
    '            return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _safer_bias(c: Dict[str, Any]) -> Tuple[str, str]:\n',
    '    """AI text-bias helper with less oversimplified WAIT behavior.\n',
    '\n',
    '    This only affects the local assistant explanation. Trading calculations,\n',
    '    KNN/Greedy, ML tables, and prediction logic are unchanged. BUY/SELL evidence\n',
    '    thresholds are intentionally lighter, while WAIT requires stronger danger or\n',
    '    multiple mixed signals.\n',
    '    """\n',
    '    regime_bias = _direction_from_regime(c.get("regime"))\n',
    '    pressure = _pressure_bias(c)\n',
    '    prediction = _safe_str(c.get("prediction_direction"), "-").upper()\n',
    '    exit_risk = _metric(c, "exit_risk", 5)\n',
    '    entry = _metric(c, "entry_score", 5)\n',
    '    conf = _metric(c, "forecast_confidence", 50)\n',
    '\n',
    '    # WAIT is now harder: only severe risk or very weak entry blocks BUY/SELL\n',
    '    # wording. This prevents the assistant from answering WAIT for every noisy\n',
    '    # situation while still protecting high-risk setups.\n',
    '    if exit_risk >= 8.2 or entry < 3.4:\n',
    '        return "WAIT", "Severe exit risk or very weak entry score makes aggressive entry unsafe."\n',
    '\n',
    '    votes = {"BUY": 0.0, "SELL": 0.0, "WAIT": 0.0}\n',
    '    if regime_bias in {"BUY", "SELL"}:\n',
    '        votes[regime_bias] += 1.6\n',
    '    else:\n',
    '        votes["WAIT"] += 0.35\n',
    '    if pressure in {"BUY", "SELL"}:\n',
    '        votes[pressure] += 1.8\n',
    '    else:\n',
    '        votes["WAIT"] += 0.25\n',
    '    if prediction in {"BUY", "SELL"}:\n',
    '        votes[prediction] += 1.05\n',
    '    elif prediction == "WAIT":\n',
    '        votes["WAIT"] += 0.25\n',
    '    if conf < 35:\n',
    '        votes["WAIT"] += 0.55\n',
    '    elif conf >= 50:\n',
    '        # Confidence supports the strongest non-WAIT side instead of defaulting\n',
    '        # to WAIT in normal noise.\n',
    '        side = max(["BUY", "SELL"], key=lambda k: votes[k])\n',
    '        votes[side] += 0.35\n',
    '\n',
    '    # Entry score and exit risk lightly shape side confidence but do not override\n',
    '    # the existing trading system decision.\n',
    '    if entry >= 4.8 and exit_risk <= 7.2:\n',
    '        side = pressure if pressure in {"BUY", "SELL"} else regime_bias if regime_bias in {"BUY", "SELL"} else prediction\n',
    '        if side in {"BUY", "SELL"}:\n',
    '            votes[side] += 0.55\n',
    '    if exit_risk >= 7.2 or entry < 4.2:\n',
    '        votes["WAIT"] += 0.75\n',
    '\n',
    '    best_side = "BUY" if votes["BUY"] >= votes["SELL"] else "SELL"\n',
    '    # WAIT must beat the best side by a large margin to win. In mixed noise, the\n',
    '    # assistant returns the less-risky BUY/SELL side with a warning.\n',
    '    if votes["WAIT"] >= max(votes["BUY"], votes["SELL"]) * 3.0 and votes["WAIT"] >= 2.2:\n',
    '        return "WAIT", f"WAIT won only after triple-standard filter: regime={regime_bias}, pressure={pressure}, prediction={prediction}."\n',
    '    if max(votes["BUY"], votes["SELL"]) > 0:\n',
    '        return best_side, f"Less-risky side={best_side}; votes BUY={votes[\'BUY\']:.2f}, SELL={votes[\'SELL\']:.2f}, WAIT={votes[\'WAIT\']:.2f}; regime={regime_bias}, pressure={pressure}, prediction={prediction}, confidence={_fmt_score(conf)}."\n',
    '    return "WAIT", f"No BUY/SELL evidence detected: regime={regime_bias}, pressure={pressure}, prediction={prediction}."\n',
    '\n',
    'def _entry_quality(c: Dict[str, Any], side: str) -> str:\n',
    '    entry = _metric(c, "entry_score", 5)\n',
    '    exit_risk = _metric(c, "exit_risk", 5)\n',
    '    conf = _metric(c, "forecast_confidence", 50)\n',
    '    pressure = _pressure_bias(c)\n',
    '    side = (side or "WAIT").upper()\n',
    '    if side == "WAIT" or exit_risk >= 8.2 or entry < 3.6:\n',
    '        return "RISKY"\n',
    '    if entry >= 5.8 and exit_risk <= 6.8 and conf >= 48 and pressure in {side, "WAIT"}:\n',
    '        return "GOOD"\n',
    '    return "MEDIUM"\n',
    '\n',
    '\n',
    'def _risk_level(c: Dict[str, Any]) -> str:\n',
    '    er = _metric(c, "exit_risk", 5)\n',
    '    entry = _metric(c, "entry_score", 5)\n',
    '    acc = _num(c.get("direction_accuracy"))\n',
    '    if er >= 7 or entry < 4.8 or (acc is not None and acc < 45):\n',
    '        return "HIGH"\n',
    '    if er >= 5.5 or entry < 6:\n',
    '        return "MEDIUM"\n',
    '    return "LOW/MEDIUM"\n',
    '\n',
    '\n',
    'def _confidence_score(parsed: Dict[str, Any], c: Dict[str, Any], mining: Dict[str, Any]) -> Tuple[int, str]:\n',
    '    score = 38 + int(parsed.get("intent_score", 0) * 0.25)\n',
    '    if c.get("forecast_confidence") is not None:\n',
    '        score += min(18, max(0, int((_metric(c, "forecast_confidence", 50) - 40) * 0.45)))\n',
    '    if c.get("entry_score") is not None:\n',
    '        score += 5\n',
    '    if c.get("exit_risk") is not None:\n',
    '        score += 5\n',
    '    if mining.get("available"):\n',
    '        score += 8\n',
    '    if len(c.get("prediction_path") or []) >= 1:\n',
    '        score += 5\n',
    '    if parsed.get("match_strength") == "weak":\n',
    '        score -= 8\n',
    '    if _risk_level(c) == "HIGH":\n',
    '        score -= 8\n',
    '    score = max(20, min(88, score))\n',
    '    label = "HIGH" if score >= 72 else "MEDIUM" if score >= 50 else "LOW"\n',
    '    return score, label\n',
    '\n',
    '\n',
    'def _tp_zone_text(context: Dict[str, Any], side: str, include_entry_prompt: bool, entry_price: Optional[float] = None) -> str:\n',
    '    proxy = mine_tp_reach_proxy(context, side)\n',
    '    zone = proxy.get("zone", "-")\n',
    '    if entry_price is not None:\n',
    '        zone += f" from entry {_fmt_num(entry_price)}"\n',
    '    if include_entry_prompt and entry_price is None:\n',
    '        zone += ". For exact TP, tell me your entry price."\n',
    '    return zone\n',
    '\n',
    '\n',
]
