"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    (r"\\bgave\\s+me\\b", "give me"),\n',
    '    (r"\\bgave\\b", "give"),\n',
    '    (r"\\bans\\b", "answer"),\n',
    '    (r"\\bansw(?:er)?e?r?\\b", "answer"),\n',
    '    (r"\\bwhta\\b", "what"), (r"\\bhwta\\b", "what"), (r"\\bwhats\\b", "what is"),\n',
    '    (r"\\bquation\\b", "question"), (r"\\bquestoin\\b", "question"),\n',
    '    (r"\\bseel\\b", "sell"), (r"\\bselll\\b", "sell"), (r"\\bsel\\b", "sell"),\n',
    '    (r"\\bbuuy\\b", "buy"), (r"\\bbuu?y\\b", "buy"),\n',
    '    (r"\\bscalop\\b", "scalp"), (r"\\bscalpinh\\b", "scalping"),\n',
    '    (r"\\bentery\\b", "entry"), (r"\\benter\\b", "entry"),\n',
    '    (r"\\bprdiction\\b", "prediction"), (r"\\bpredicytion\\b", "prediction"), (r"\\bpredicion\\b", "prediction"),\n',
    '    (r"\\bpredective\\b", "predictive"), (r"\\bpredictve\\b", "predictive"),\n',
    '    (r"\\bpreseriptive\\b", "prescriptive"), (r"\\bprescriptve\\b", "prescriptive"),\n',
    '    (r"\\banalyssi\\b", "analysis"), (r"\\banalysisis\\b", "analysis"),\n',
    '    (r"\\brecognization\\b", "recognition"), (r"\\btext\\s+similar\\s+result\\b", "similar question result"),\n',
    '    (r"\\bgrammer\\b", "grammar"), (r"\\bgrmr\\b", "grammar"),\n',
    '    (r"\\briskly\\b", "risky"), (r"\\bless\\s+risk\\b", "less risky"),\n',
    '    (r"\\bnxt\\b", "next"), (r"\\bshuld\\b", "should"), (r"\\bshoud\\b", "should"),\n',
    '    (r"\\bu\\[grade\\b", "upgrade"), (r"\\buograde\\b", "upgrade"), (r"\\bupfgrad\\b", "upgrade"),\n',
    '    (r"\\bt/p\\b", "take profit"), (r"\\btp\\b", "take profit"),\n',
    '    (r"\\b1\\s*h\\b", "1 hour"), (r"\\b2\\s*h\\b", "2 hours"), (r"\\b6\\s*h\\b", "6 hours"),\n',
    '    (r"\\b30\\s*m\\b", "30 min"), (r"\\b30\\s*mins\\b", "30 min"),\n',
    '    (r"\\bnxt\\s*(\\d+)\\s*h\\b", r"next \\1 hours"),\n',
    '    (r"\\bnext(\\d+)h\\b", r"next \\1 hours"),\n',
    '    (r"\\bwithin\\s*(\\d+)\\s*h\\b", r"within \\1 hours"),\n',
    '    (r"\\bhourss\\b", "hours"),\n',
    '    (r"\\bminuite\\b", "minute"), (r"\\bminits?\\b", "minutes"),\n',
    '    (r"\\bpricce\\b", "price"), (r"\\bpritce\\b", "price"),\n',
    '    (r"\\bforcast\\b", "forecast"), (r"\\bforcase\\b", "forecast"),\n',
    '    (r"\\bconfidance\\b", "confidence"), (r"\\breliabel\\b", "reliable"), (r"\\breliabilityy\\b", "reliability"),\n',
    '    (r"\\bhistroy\\b", "history"), (r"\\bmatchig\\b", "matching"), (r"\\bsimliar\\b", "similar"),\n',
    '    (r"\\brecog(?:niz|nis)ation\\b", "recognition"), (r"\\bquestionn\\b", "question"),\n',
    '    (r"\\binputt\\b", "input"), (r"\\binpout\\b", "input"),\n',
    '    (r"\\bclsoe\\b", "close"), (r"\\bside\\s*bar\\b", "sidebar"),\n',
    ']\n',
    '\n',
    'SYNONYM_GROUPS: Dict[str, List[str]] = {\n',
    '    "safer": ["safer", "less risky", "low risk", "better protect", "safe side"],\n',
    '    "scalp": ["scalp", "scalping", "quick trade", "short trade", "fast entry"],\n',
    '    "take_profit": ["take profit", "target", "exit target", "profit target", "tp"],\n',
    '    "exit": ["exit", "close", "protect", "cut", "reduce"],\n',
    '    "bias": ["bias", "direction", "side", "buy or sell"],\n',
    '    "prediction": ["prediction", "forecast", "next move", "projected path", "price prediction"],\n',
    '    "quality": ["quality", "confidence", "reliability", "score"],\n',
    '    "history": ["history", "similar setup", "past result", "backtest", "previous rows", "similar result", "matching history", "history match"],\n',
    '    "analysis": ["analysis", "descriptive", "predictive", "prescriptive", "recognition", "grammar", "similarity", "text similarity"],\n',
    '}\n',
    '\n',
    'TRADING_WORDS = {\n',
    '    "scalp", "scalping", "entry", "hold", "bias", "less risky", "safer", "buy", "sell",\n',
    '    "take profit", "target", "exit", "protect", "wait", "regime", "prediction",\n',
    '    "conflict", "history", "similar", "quality", "confidence", "next", "hour", "today",\n',
    '    "analysis", "descriptive", "predictive", "prescriptive", "recognition", "grammar", "similarity", "accuracy",\n',
    '}\n',
    '\n',
    'INTENT_REGISTRY: Dict[str, Dict[str, Any]] = {\n',
    '    "scalp_entry_now": {\n',
    '        "label": "scalp entry now",\n',
    '        "examples": ["i want to scalp entry now what entry buy or sell and what take profit", "scalp entry now", "quick trade now buy or sell", "fast entry now with target"],\n',
    '        "keywords": ["scalp", "scalping", "quick trade", "fast entry", "entry now", "now", "buy", "sell", "take profit"],\n',
    '        "phrases": ["scalp entry now", "quick trade now", "fast entry now"],\n',
    '    },\n',
    '    "next_30min_prediction": {\n',
    '        "label": "next 30 minute H1 proxy prediction",\n',
    '        "examples": ["what next 30 min price prediction", "next 30 min forecast", "30 minute next move"],\n',
    '        "keywords": ["30 min", "30 minute", "prediction", "forecast", "price", "next move"],\n',
    '        "phrases": ["next 30 min", "30 min prediction", "30 minute prediction"],\n',
    '    },\n',
    '    "next_1h_bias": {\n',
    '        "label": "next 1 hour bias",\n',
    '        "examples": ["next 1 hour bias", "what bias next 1 hour", "next hour buy or sell"],\n',
    '        "keywords": ["1 hour", "next hour", "bias", "direction", "buy", "sell"],\n',
    '        "phrases": ["next 1 hour", "next hour bias", "1 hour bias"],\n',
    '    },\n',
    '    "next_2h_bias": {\n',
    '        "label": "next 2 hours bias",\n',
    '        "examples": ["next 2 hours bias", "2 hours direction", "two hour buy or sell"],\n',
    '        "keywords": ["2 hours", "bias", "direction", "buy", "sell"],\n',
    '        "phrases": ["next 2 hours", "2 hours bias"],\n',
    '    },\n',
    '    "next_6h_bias": {\n',
    '        "label": "next 6 hours bias",\n',
    '        "examples": ["next 6 hours bias", "6 hours direction", "six hour buy or sell"],\n',
    '        "keywords": ["6 hours", "bias", "direction", "buy", "sell"],\n',
    '        "phrases": ["next 6 hours", "6 hours bias"],\n',
    '    },\n',
    '    "sell_entry_tp": {\n',
    '        "label": "take profit for sell entry",\n',
    '        "examples": ["what is take profit for my sell entry", "tp for sell", "sell entry target"],\n',
    '        "keywords": ["sell", "take profit", "target", "entry"],\n',
    '        "phrases": ["take profit for sell", "sell entry", "sell target"],\n',
    '    },\n',
    '    "buy_entry_tp": {\n',
    '        "label": "take profit for buy entry",\n',
    '        "examples": ["what is take profit for my buy entry", "tp for buy", "buy entry target"],\n',
    '        "keywords": ["buy", "take profit", "target", "entry"],\n',
    '        "phrases": ["take profit for buy", "buy entry", "buy target"],\n',
    '    },\n',
    '    "hold_bias_next_1h": {\n',
    '        "label": "hold bias for next 1 hour",\n',
    '        "examples": ["what bias is less risky to hold for next 1 hour", "hold next hour bias", "should i hold next 1 hour"],\n',
    '        "keywords": ["hold", "next 1 hour", "1 hour", "less risky", "bias", "safer"],\n',
    '        "phrases": ["hold next hour", "hold for next 1 hour", "less risky to hold"],\n',
    '    },\n',
    '    "less_risky_bias": {\n',
    '        "label": "less risky BUY or SELL bias",\n',
    '        "examples": ["buy or sell safer", "what bias less risky", "less risky bias now", "which side safer"],\n',
    '        "keywords": ["safer", "less risky", "low risk", "bias", "buy", "sell", "side"],\n',
    '        "phrases": ["buy or sell safer", "less risky bias", "which side safer"],\n',
    '    },\n',
    '    "recommended_action": {\n',
    '        "label": "recommended action card",\n',
    '        "examples": ["what should i do now", "recommended action", "should i buy now", "should i sell now", "action now"],\n',
    '        "keywords": ["should", "recommend", "action", "now", "buy", "sell", "wait", "protect"],\n',
    '        "phrases": ["should i buy now", "should i sell now", "what should i do"],\n',
    '    },\n',
    '    "entry_with_tp_plan": {\n',
    '        "label": "entry with TP plan",\n',
    '        "examples": ["entry with tp plan", "give entry and take profit plan", "entry point and target"],\n',
    '        "keywords": ["entry", "take profit", "plan", "target", "buy", "sell"],\n',
    '        "phrases": ["entry with take profit", "entry and target", "entry plan"],\n',
    '    },\n',
    '    "protect_existing_position": {\n',
    '        "label": "protect existing position",\n',
    '        "examples": ["protect my existing position", "exit now or wait", "hold or protect", "should i cut or reduce"],\n',
    '        "keywords": ["protect", "existing", "position", "exit", "close", "cut", "reduce", "hold"],\n',
    '        "phrases": ["protect position", "exit now or wait", "hold or protect"],\n',
    '    },\n',
    '    "quick_trade_summary": {\n',
    '        "label": "quick trade summary",\n',
    '        "examples": ["quick trade summary", "short summary", "necessary short copy", "summary now"],\n',
    '        "keywords": ["summary", "short", "quick", "necessary", "copy"],\n',
    '        "phrases": ["quick summary", "short summary", "necessary short"],\n',
    '    },\n',
    '    "prediction_conflict_check": {\n',
    '        "label": "prediction conflict check",\n',
    '        "examples": ["regime and prediction conflict", "prediction direction conflict", "regime says bear but prediction up"],\n',
    '        "keywords": ["prediction", "regime", "conflict", "direction", "disagree"],\n',
    '        "phrases": ["regime conflict", "prediction conflict", "direction conflict"],\n',
    '    },\n',
    '    "regime_bias_check": {\n',
    '        "label": "regime bias check",\n',
    '        "examples": ["regime bias", "what regime says", "bull bear range direction"],\n',
    '        "keywords": ["regime", "bias", "bull", "bear", "range", "direction"],\n',
    '        "phrases": ["regime bias", "what regime"],\n',
    '    },\n',
    '    "history_similar_setup": {\n',
    '        "label": "similar history setup",\n',
    '        "examples": ["similar result for now", "what answer from history like this setup", "similar past setup", "history like now"],\n',
    '        "keywords": ["history", "similar", "past", "setup", "backtest", "previous"],\n',
    '        "phrases": ["similar result", "similar setup", "history like this setup"],\n',
    '    },\n',
    '    "quality_confidence_check": {\n',
    '        "label": "quality and confidence check",\n',
    '        "examples": ["quality confidence now", "answer confidence", "data quality", "prediction reliability"],\n',
    '        "keywords": ["quality", "confidence", "reliability", "accuracy", "error", "data quality"],\n',
    '        "phrases": ["data quality", "answer confidence", "prediction reliability"],\n',
    '    },\n',
    '    "system_feature_status": {\n',
    '        "label": "system feature, menu, API or workspace status",\n',
    '        "examples": [\n',
    '            "is the sidebar restored", "where is phone ui", "is nlp api connected",\n',
    '            "what is in other tab", "how many question patterns", "is finder updated",\n',
    '            "what page opens first", "where is ai assistant now",\n',
    '        ],\n',
    '        "keywords": [\n',
    '            "sidebar", "menu", "setting", "settings", "phone ui", "api", "nlp", "llm",\n',
    '            "copy short", "copy full", "finder", "research", "other tab", "engine",\n',
    '            "train data", "pre original", "backtest", "profile", "question patterns",\n',
    '        ],\n',
    '        "phrases": [\n',
    '            "sidebar restored", "phone ui", "nlp api", "other tab", "question patterns",\n',
    '            "opens first", "copy short", "copy full",\n',
    '        ],\n',
    '    },\n',
    '    "nearest_answer_fallback": {\n',
    '        "label": "nearest useful answer based on available data",\n',
    '        "examples": ["data not gave because nlp not found question", "nlp not found", "give useful answer", "question not detected"],\n',
    '        "keywords": ["nlp", "not found", "question", "answer", "data", "useful"],\n',
    '        "phrases": ["nlp not found", "data not gave", "nearest useful answer"],\n',
    '    },\n',
    '}\n',
    '\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Prepared Question Box library (100+ local question patterns)\n',
    '# ---------------------------------------------------------------------------\n',
    'def _plain_normalize_question_pattern(text: str) -> str:\n',
    '    q = (text or "").lower().strip()\n',
    '    for pat, repl in TYPO_REPLACEMENTS:\n',
    '        try:\n',
    '            q = re.sub(pat, repl, q)\n',
    '        except Exception:\n',
    '            pass\n',
    '    q = re.sub(r"[^a-z0-9\\.\\s]+", " ", q)\n',
    '    return re.sub(r"\\s+", " ", q).strip()\n',
    '\n',
    '\n',
    'def _build_prepared_question_patterns() -> List[Dict[str, Any]]:\n',
    '    """Compact prepared-question library for dropdown/search.\n',
    '\n',
    '    This is intentionally local/static: no API, no model, no file writes.\n',
    '    It gives the Question Box 100+ reusable patterns without showing a wall of\n',
    '    buttons on mobile.\n',
    '    """\n',
    '    packs: List[Tuple[str, str, List[str], List[str]]] = [\n',
    '        ("Entry / Scalp", "scalp_entry_now", [\n',
    '            "Is scalp entry allowed now?",\n',
    '            "Can I scalp entry now?",\n',
    '            "I want scalp entry now buy or sell and TP",\n',
    '            "Quick scalp now which side is safer?",\n',
    '            "Fast entry now buy or sell?",\n',
    '            "Should I enter now or wait?",\n',
    '            "Is entry score strong enough for scalp?",\n',
    '            "What side is safer for short trade now?",\n',
    '            "Give me quick entry idea with tight TP",\n',
    '            "Can I take small scalp on current H1?",\n',
    '            "Is current market clean for entry?",\n',
    '            "Should I avoid entry because exit risk is high?",\n',
    '            "Entry now with current regime filter",\n',
    '            "Scalp only if TP is tight, is it okay?",\n',
    '            "What is the safest entry side right now?",\n',
    '            "Can I enter after pullback?",\n',
    '            "Is BUY scalp better than SELL scalp?",\n',
    '            "Is SELL scalp better than BUY scalp?",\n',
    '            "What entry quality now good medium or risky?",\n',
    '            "Give me no API local scalp answer now",\n',
    '        ], ["entry", "scalp", "quick", "fast", "now", "buy", "sell", "tp"]),\n',
    '        ("TP / Target", "sell_entry_tp", [\n',
    '            "What is TP for my sell entry?",\n',
    '            "TP for sell entry without exact entry price",\n',
    '            "Sell entry target zone now",\n',
    '            "Give SELL TP1 and TP2",\n',
    '            "Where should I take profit for sell?",\n',
    '            "Approximate TP for short position",\n',
    '            "Sell target using lower band",\n',
    '            "Can sell reach lower band?",\n',
    '            "What lower price zone is safer for sell TP?",\n',
    '            "Sell TP if I entered at 1.15610",\n',
    '            "TP for my seel entry",\n',
    '            "Take profit plan for SELL now",\n',
    '            "Conservative TP for sell",\n',
    '            "Extended TP for sell if confidence supports",\n',
    '            "Should I close sell at TP1 or hold TP2?",\n',
    '        ], ["sell", "tp", "take profit", "target", "lower", "short"]),\n',
    '        ("TP / Target", "buy_entry_tp", [\n',
    '            "What is TP for my buy entry?",\n',
    '            "TP for buy entry without exact entry price",\n',
    '            "Buy entry target zone now",\n',
    '            "Give BUY TP1 and TP2",\n',
    '            "Where should I take profit for buy?",\n',
    '            "Approximate TP for long position",\n',
    '            "Buy target using upper band",\n',
    '            "Can buy reach upper band?",\n',
    '            "What upper price zone is safer for buy TP?",\n',
    '            "Buy TP if I entered at 1.15610",\n',
    '            "Take profit plan for BUY now",\n',
    '            "Conservative TP for buy",\n',
    '            "Extended TP for buy if confidence supports",\n',
    '            "Should I close buy at TP1 or hold TP2?",\n',
    '            "TP zone for buy based on prediction path",\n',
    '        ], ["buy", "tp", "take profit", "target", "upper", "long"]),\n',
    '        ("Bias / Direction", "less_risky_bias", [\n',
    '            "BUY or SELL safer?",\n',
    '            "What bias is less risky now?",\n',
    '            "Which side is safer now buy or sell?",\n',
    '            "Less risky bias for current H1",\n',
    '            "What direction has lower risk?",\n',
    '            "Is buy safer than sell now?",\n',
    '            "Is sell safer than buy now?",\n',
    '            "What side should I avoid?",\n',
    '            "What bias should I follow today?",\n',
    '            "What is the safest side based on pressure?",\n',
    '            "What direction is system bias?",\n',
    '            "Should I wait because buy and sell are mixed?",\n',
    '            "Current bias from regime and pressure",\n',
    '            "Safer side with exit risk included",\n',
    '            "Buy pressure versus sell pressure which wins?",\n',
    '            "What side is better protect?",\n',
    '            "What bias is low risk now?",\n',
    '            "Side check with current decision",\n',
    '            "Direction check using only existing metrics",\n',
    '            "Nearest useful buy sell answer",\n',
    '        ], ["bias", "direction", "safer", "less risky", "buy", "sell"]),\n',
    '        ("Bias / Direction", "hold_bias_next_1h", [\n',
    '            "What bias is less risky to hold for next 1 hour?",\n',
    '            "Should I hold next 1 hour?",\n',
    '            "Hold bias next hour",\n',
    '            "Is it safe to hold for 1 hour?",\n',
    '            "Next hour hold or protect?",\n',
    '            "Can I hold buy for next hour?",\n',
    '            "Can I hold sell for next hour?",\n',
    '            "Hold current position with current risk?",\n',
    '            "One hour safer hold side",\n',
    '            "Should I reduce position before next hour?",\n',
    '            "What bias for hold nxt 1h",\n',
    '            "whta bias less risky hold nxt 1h",\n',
    '        ], ["hold", "1 hour", "next hour", "bias", "protect"]),\n',
    '        ("Prediction", "next_30min_prediction", [\n',
    '            "What next 30 min price prediction?",\n',
    '            "What nxt 30m price?",\n',
    '            "Next 30 minute forecast using H1 proxy",\n',
    '            "30 min direction from H1 data",\n',
    '            "Next half hour buy or sell?",\n',
    '            "Projected price zone for next 30 min",\n',
    '            "Where can price go in 30 min?",\n',
    '            "Is next 30 min likely up or down?",\n',
    '            "30 min prediction path from current H1",\n',
    '            "Short term forecast next 30 minutes",\n',
    '            "Next 30 min estimated zone with band",\n',
    '            "30m price prediction without lower timeframe model",\n',
    '            "Should I scalp based on next 30 min proxy?",\n',
    '            "What is next 30 min close estimate?",\n',
    '            "30 min H1 proxy confidence",\n',
    '        ], ["30 min", "30m", "prediction", "forecast", "price", "h1"]),\n',
    '        ("Prediction", "next_1h_bias", [\n',
    '            "Next 1 hour bias",\n',
    '            "What is next 1H direction?",\n',
    '            "Next hour buy or sell?",\n',
    '            "Where price may go in next 1 hour?",\n',
    '            "H1 next candle bias",\n',
    '            "Next 1 hour price zone",\n',
    '            "Should I wait next hour?",\n',
    '            "Forecast for next hour using prediction path",\n',
    '            "Next hour projected close",\n',
    '            "1 hour confidence check",\n',
    '        ], ["1 hour", "next hour", "prediction", "bias", "h1"]),\n',
    '        ("Prediction", "next_2h_bias", [\n',
    '            "Next 2 hours bias",\n',
    '            "What is next 2H direction?",\n',
    '            "Can price reach target within 2 hours?",\n',
    '            "2 hours buy or sell safer?",\n',
    '            "Next 2 hours forecast from H1 path",\n',
    '            "Should I hold trade for 2 hours?",\n',
    '            "2h estimated price zone",\n',
    '            "Two hour direction and risk",\n',
    '            "Next two candles bias",\n',
    '            "2 hours TP reach proxy",\n',
    '        ], ["2 hours", "2h", "forecast", "bias", "tp"]),\n',
    '        ("Prediction", "next_6h_bias", [\n',
    '            "Next 6 hours bias",\n',
    '            "What is next 6H direction?",\n',
    '            "Can price reach target within 6 hours?",\n',
    '            "6 hours buy or sell safer?",\n',
    '            "Next 6 hours forecast from H1 path",\n',
    '            "Should I hold trade for 6 hours?",\n',
    '            "6h estimated price zone",\n',
    '            "Six hour direction and risk",\n',
    '            "Next six candles bias",\n',
    '            "6 hours TP reach probability proxy",\n',
    '        ], ["6 hours", "6h", "forecast", "bias", "tp"]),\n',
    '        ("History / Similar Setup", "history_similar_setup", [\n',
    '            "Find similar setup from history",\n',
    '            "Similar result for now",\n',
    '            "What answer from history like this setup?",\n',
    '            "Show similar hour analysis",\n',
    '            "What happened last time with same setup?",\n',
    '            "Use data mining to compare current setup",\n',
    '            "History check for current bias",\n',
    '            "Backtest-like similar row answer",\n',
    '            "Today rows say buy or sell?",\n',
    '            "Last 24h similar setup insight",\n',
    '            "Regime history behavior now",\n',
    '            "Same hour history quality",\n',
    '            "KNN Greedy priority row insight",\n',
    '            "Find previous rows like current entry score",\n',
    '            "Past result with same exit risk",\n',
    '            "Similar setup TP reach proxy",\n',
    '            "What history says about current regime?",\n',
    '            "Use full metric history for answer",\n',
    '            "Compare now with overlap history",\n',
    '            "Data mining answer only from existing history",\n',
    '        ], ["history", "similar", "backtest", "same hour", "regime", "knn", "greedy"]),\n',
    '        ("Protect / Exit", "protect_existing_position", [\n',
    '            "Should I protect my position now?",\n',
    '            "Exit now or wait?",\n',
    '            "Hold or protect current trade?",\n',
    '            "Should I close partial?",\n',
    '            "Should I reduce risk now?",\n',
    '            "Protect sell position or hold?",\n',
    '            "Protect buy position or hold?",\n',
    '            "Is exit risk too high?",\n',
    '            "Should I cut trade if prediction weak?",\n',
    '            "When should I exit if bias changes?",\n',
    '            "Should I move stop or take partial?",\n',
    '            "Protect profit with current system decision",\n',
    '            "Do I need emergency exit?",\n',
    '            "Risk is high what should I do?",\n',
    '            "Should I wait instead of adding entry?",\n',
    '            "What invalidates current trade idea?",\n',
    '            "Exit plan based on lower and upper band",\n',
    '            "Protect existing position using H1 metrics",\n',
    '        ], ["protect", "exit", "close", "reduce", "hold", "risk", "position"]),\n',
    '        ("Confidence / Quality", "quality_confidence_check", [\n',
    '            "Quality confidence now",\n',
    '            "How reliable is this answer?",\n',
    '            "Is prediction reliability weak?",\n',
    '            "Check direction accuracy",\n',
    '            "Is forecast confidence enough?",\n',
    '            "Is market quality good enough?",\n',
    '            "Prediction error mining now",\n',
    '            "Should confidence be lowered?",\n',
    '            "Is data quality strong or weak?",\n',
    '            "What missing data affects answer?",\n',
    '            "Can I trust current prediction path?",\n',
    '            "Is TP score strong enough?",\n',
    '            "Is entry score strong enough?",\n',
    '            "Explain confidence using existing metrics",\n',
    '            "What is the main weak point in the data?",\n',
    '            "Accuracy and error check for prediction",\n',
    '            "Quality check before entry",\n',
    '            "Confidence check before holding",\n',
    '        ], ["quality", "confidence", "reliability", "accuracy", "error", "score"]),\n',
    '        ("Confidence / Quality", "prediction_conflict_check", [\n',
    '            "Is regime conflicting with prediction?",\n',
    '            "Regime and prediction conflict check",\n',
    '            "Prediction says buy but regime says bear",\n',
    '            "Prediction says sell but regime says bull",\n',
    '            "Do regime and forecast agree?",\n',
]
