"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    'def _recommendation_card(c: Dict[str, Any], side: str, tp_text: str, reason: str) -> str:\n',
    '    risk = _risk_level(c)\n',
    '    system_decision = _safe_str(c.get("decision"), "-").upper()\n',
    '    side = (side or "WAIT").upper()\n',
    '    action = "WAIT"\n',
    '    if "PROTECT" in system_decision or risk == "HIGH":\n',
    '        action = "PROTECT" if "PROTECT" in system_decision else "WATCH"\n',
    '    elif side == "BUY":\n',
    '        action = "BUY allowed"\n',
    '    elif side == "SELL":\n',
    '        action = "SELL allowed"\n',
    '    if "EXIT" in system_decision:\n',
    '        action = "EXIT PARTIAL"\n',
    '    what_change = "lower exit risk + stronger entry/forecast agreement" if action in {"WAIT", "WATCH", "PROTECT"} else "opposite pressure spike or regime/prediction conflict"\n',
    '    return (\n',
    '        f"**Recommendation card**\\n"\n',
    '        f"- Action: **{action}**\\n"\n',
    '        f"- Bias: **{side}**\\n"\n',
    '        f"- TP idea: {tp_text}\\n"\n',
    '        f"- Risk level: **{risk}**\\n"\n',
    '        f"- Why: {reason}\\n"\n',
    '        f"- What would change the answer: {what_change}"\n',
    '    )\n',
    '\n',
    '\n',
    'def _format_answer(parsed: Dict[str, Any], direct: str, safer: str, tp: str, mining: str, risk: str, confidence: str, card: Optional[str] = None) -> str:\n',
    '    """Build a relevant answer instead of forcing trading sections everywhere."""\n',
    '    interpreted = parsed.get("intent_label", "nearest useful answer")\n',
    '    sim = parsed.get("similarity_score", 0)\n',
    '    prefix = "Nearest useful answer based on available data. " if parsed.get("match_strength") == "weak" else ""\n',
    '    normalized = _safe_str(parsed.get("normalized_question"), "").lower()\n',
    '    trade_terms = ("buy", "sell", "entry", "enter", "trade", "hold", "position", "tp", "target", "bias", "direction", "safer", "less risky", "exit", "protect")\n',
    '    trade_intents = {\n',
    '        "scalp_entry_now", "next_30min_prediction", "next_1h_bias", "next_2h_bias",\n',
    '        "next_6h_bias", "hold_bias_next_1h", "less_risky_bias", "sell_entry_tp",\n',
    '        "buy_entry_tp", "recommended_action", "entry_with_tp_plan",\n',
    '        "protect_existing_position", "prediction_conflict_check",\n',
    '    }\n',
    '    is_trade_answer = parsed.get("intent") in trade_intents or any(term in normalized for term in trade_terms)\n',
    '\n',
    '    sections = [\n',
    '        f"**Interpreted question:** {interpreted}",\n',
    '        f"**Direct answer:** {prefix}{direct}",\n',
    '    ]\n',
    '    if is_trade_answer and _safe_str(safer, "").lower() not in {"", "not applicable", "not applicable to this question"}:\n',
    '        sections.append(f"**Safer bias:** {safer}")\n',
    '    if is_trade_answer and _safe_str(tp, "").lower() not in {"", "not applicable", "not applicable to this question"}:\n',
    '        sections.append(f"**TP / price zone:** {tp}")\n',
    '    if mining:\n',
    '        sections.append(f"**Data insight:** {mining}")\n',
    '    if is_trade_answer and risk:\n',
    '        sections.append(f"**Main risk:** {risk}")\n',
    '    if confidence:\n',
    '        sections.append(f"**Answer confidence:** {confidence}")\n',
    '\n',
    '    body = "\\n\\n".join(sections)\n',
    '    if sim:\n',
    '        body += f"\\n\\nSimilar question match: {sim:.0f}% ({parsed.get(\'match_strength\',\'weak\')})."\n',
    '    if card and is_trade_answer:\n',
    '        body += "\\n\\n" + card\n',
    '    body += (\n',
    '        "\\n\\n_System decision still controls; this assistant explains synchronized existing metrics._"\n',
    '        if is_trade_answer else\n',
    '        "\\n\\n_This answer uses the current app state and synchronized data only._"\n',
    '    )\n',
    '    return body\n',
    '\n',
    '\n',
    'def _system_feature_status_answer(context: Dict[str, Any]) -> Tuple[str, str]:\n',
    '    """Answer app-control questions from live session state, not trading bias."""\n',
    '    try:\n',
    '        rows = len(st.session_state.get("last_df")) if st.session_state.get("last_df") is not None else 0\n',
    '    except Exception:\n',
    '        rows = 0\n',
    '    active_page = _safe_str(\n',
    '        st.session_state.get("active_page") or st.session_state.get("page") or st.session_state.get("tab_choice"),\n',
    '        "Settings",\n',
    '    )\n',
    '    market_source = _safe_str(st.session_state.get("source"), "DISCONNECTED")\n',
    '    nlp_connected = bool(st.session_state.get("nlp_api_connected", False))\n',
    '    nlp_model = _safe_str(st.session_state.get("nlp_api_model"), "-")\n',
    '    patterns = len(PREPARED_QUESTION_PATTERNS)\n',
    '    direct = (\n',
    '        f"Active page is **{active_page}**. The native sidebar backup and compact sticky menu are available. "\n',
    '        f"The **Other** workspace contains Engine, Train Data, Database/Pre Original, Backtest and Profile. "\n',
    '        f"Market API is **{market_source}** with **{rows:,}** loaded rows. "\n',
    '        f"NLP/LLM is **{\'CONNECTED\' if nlp_connected else \'OFF\'}** using model **{nlp_model}**. "\n',
    '        f"The question box currently has **{patterns:,}** prepared patterns and routes system questions separately from trading advice."\n',
    '    )\n',
    '    insight = (\n',
    '        "Settings is the fresh-session startup page; Phone UI is controlled inside the menu; "\n',
    '        "Home, Data Visualization and AI Assistant are not separate top-level menu buttons. "\n',
    '        "AI Assistant remains available inside Research and answers through local patterns or the configured LLM connection."\n',
    '    )\n',
    '    return direct, insight\n',
    '\n',
    '\n',
    'def local_ai_generate_answer(parsed: Dict[str, Any], context: Dict[str, Any]) -> str:\n',
    '    c = context.get("current", {})\n',
    '    intent = parsed.get("intent", "nearest_answer_fallback")\n',
    '    target_price = _num(parsed.get("target_price"))\n',
    '    requested_side = parsed.get("direction_keyword")\n',
    '    safer_side, reason = _safer_bias(c)\n',
    '    if intent == "sell_entry_tp":\n',
    '        safer_side = "SELL"\n',
    '    elif intent == "buy_entry_tp":\n',
    '        safer_side = "BUY"\n',
    '    elif requested_side in {"BUY", "SELL"} and intent in {"recommended_action", "entry_with_tp_plan"}:\n',
    '        # User asked a side; still compare with system safer side in the direct answer.\n',
    '        pass\n',
    '\n',
    '    mining = fallback_mining(context, safer_side if safer_side in {"BUY", "SELL"} else None)\n',
    '    conf_score, conf_label = _confidence_score(parsed, c, mining)\n',
    '    confidence = f"{conf_label} ({conf_score}/100)"\n',
    '    risk = _risk_level(c) + f" — Exit Risk={_fmt_score(c.get(\'exit_risk\'))}, Entry={_fmt_score(c.get(\'entry_score\'))}."\n',
    '    entry_price = target_price if target_price and intent in {"sell_entry_tp", "buy_entry_tp", "entry_with_tp_plan"} else None\n',
    '\n',
    '    if intent == "system_feature_status":\n',
    '        direct, insight = _system_feature_status_answer(context)\n',
    '        return _format_answer(parsed, direct, "Not applicable", "Not applicable", insight, "", confidence)\n',
    '\n',
    '    if intent == "scalp_entry_now":\n',
    '        quality = _entry_quality(c, safer_side)\n',
    '        tp_text = _tp_zone_text(context, safer_side, False)\n',
    '        if safer_side == "WAIT":\n',
    '            direct = f"Scalp is not clean now. Entry quality is {quality}; WAIT or protect is safer."\n',
    '        else:\n',
    '            direct = f"Scalp side: **{safer_side}**; entry quality **{quality}**. Keep TP tight because this is H1-based."\n',
    '        card = _recommendation_card(c, safer_side, tp_text, reason)\n',
    '        return _format_answer(parsed, direct, safer_side, tp_text, mining.get("insight", "Using fallback proxy."), risk, confidence, card)\n',
    '\n',
    '    if intent == "next_30min_prediction":\n',
    '        path = c.get("prediction_path") or []\n',
    '        next_price = _num(path[0]) if path else _num(c.get("estimated_price_close"))\n',
    '        direction = "WAIT"\n',
    '        last_close = _num(c.get("last_close"))\n',
    '        if next_price is not None and last_close is not None:\n',
    '            direction = "BUY" if next_price > last_close else "SELL" if next_price < last_close else "WAIT"\n',
    '        zone = f"H1 proxy next zone: close {_fmt_num(last_close)} → projected {_fmt_num(next_price)}; band {_fmt_num(c.get(\'lower_band\'))}–{_fmt_num(c.get(\'upper_band\'))}."\n',
    '        direct = f"Likely short-term direction is **{direction}**, but 30 min is estimated from H1 data, not a separate lower-timeframe model."\n',
    '        return _format_answer(parsed, direct, direction, zone, mining.get("insight", "Using H1 prediction path proxy."), risk, confidence)\n',
    '\n',
    '    if intent in {"next_1h_bias", "next_2h_bias", "next_6h_bias", "hold_bias_next_1h", "less_risky_bias"}:\n',
    '        horizon = parsed.get("horizon", {}).get("label", "current H1")\n',
    '        tp_text = _tp_zone_text(context, safer_side, False) if safer_side in {"BUY", "SELL"} else "WAIT: no clean TP zone until bias improves."\n',
    '        direct = f"For {horizon}, safer side is **{safer_side}**. {reason}"\n',
    '        if intent == "hold_bias_next_1h":\n',
    '            direct = f"For holding next 1 hour, **{safer_side}** is safer; avoid adding size if exit risk rises. {reason}"\n',
    '        card = _recommendation_card(c, safer_side, tp_text, reason)\n',
    '        return _format_answer(parsed, direct, safer_side, tp_text, mining.get("insight", "Using current H1 proxy."), risk, confidence, card)\n',
    '\n',
    '    if intent in {"sell_entry_tp", "buy_entry_tp"}:\n',
    '        side = "SELL" if intent == "sell_entry_tp" else "BUY"\n',
    '        tp_text = _tp_zone_text(context, side, True, entry_price)\n',
    '        pressure = _pressure_bias(c)\n',
    '        direct = f"Approximate {side} TP zone is shown below. Exact TP needs your entry price. System decision still controls before holding or adding."\n',
    '        safer = side if safer_side == side or pressure == side else f"{safer_side} by system proxy; requested side is {side}"\n',
    '        mining2 = fallback_mining(context, side)\n',
    '        card = _recommendation_card(c, side if safer_side == side else safer_side, tp_text, reason)\n',
    '        return _format_answer(parsed, direct, safer, tp_text, mining2.get("insight", mining.get("insight", "Using TP proxy.")), risk, confidence, card)\n',
    '\n',
    '    if intent == "recommended_action":\n',
    '        user_side = requested_side or safer_side\n',
    '        tp_text = _tp_zone_text(context, user_side, False) if user_side in {"BUY", "SELL"} else "WAIT; no clean TP zone."\n',
    '        if requested_side and requested_side != safer_side:\n',
    '            direct = f"You asked about **{requested_side}**, but safer proxy is **{safer_side}**. Avoid forcing {requested_side} unless system metrics improve."\n',
    '        else:\n',
    '            direct = f"Recommended action is based on system metrics: **{safer_side} / {(\'PROTECT\' if _risk_level(c) == \'HIGH\' else \'WATCH\')}**."\n',
    '        card = _recommendation_card(c, safer_side, tp_text, reason)\n',
    '        return _format_answer(parsed, direct, safer_side, tp_text, mining.get("insight", "Using current metrics."), risk, confidence, card)\n',
    '\n',
    '    if intent == "entry_with_tp_plan":\n',
    '        side = requested_side or safer_side\n',
    '        tp_text = _tp_zone_text(context, side, True, entry_price) if side in {"BUY", "SELL"} else "WAIT; no clean entry/TP plan."\n',
    '        quality = _entry_quality(c, side)\n',
    '        direct = f"Entry plan: **{side}** only if system decision allows; entry quality is **{quality}**."\n',
    '        card = _recommendation_card(c, side, tp_text, reason)\n',
    '        return _format_answer(parsed, direct, side, tp_text, mining.get("insight", "Using current metrics."), risk, confidence, card)\n',
    '\n',
    '    if intent == "protect_existing_position":\n',
    '        direct = "Protect first if profit exists or exit risk is high. Consider partial close/protect rather than adding new entry."\n',
    '        tp_text = _tp_zone_text(context, safer_side, False) if safer_side in {"BUY", "SELL"} else "Protect/WAIT; TP zone weak."\n',
    '        card = _recommendation_card(c, safer_side, tp_text, reason)\n',
    '        return _format_answer(parsed, direct, safer_side, tp_text, mining.get("insight", "Using current risk proxy."), risk, confidence, card)\n',
    '\n',
    '    if intent == "prediction_conflict_check":\n',
    '        regime_side = _direction_from_regime(c.get("regime"))\n',
    '        pred_side = _safe_str(c.get("prediction_direction"), "-").upper()\n',
    '        conflict = pred_side in {"BUY", "SELL"} and regime_side in {"BUY", "SELL"} and pred_side != regime_side\n',
    '        direct = "Conflict exists; reduce confidence and prefer WAIT/PROTECT." if conflict else "No strong regime/prediction conflict detected."\n',
    '        tp_text = _tp_zone_text(context, safer_side, False) if safer_side in {"BUY", "SELL"} else "No clean TP while conflict/WAIT."\n',
    '        return _format_answer(parsed, direct, safer_side, tp_text, mine_prediction_error(context).get("insight", mining.get("insight", "Using prediction proxy.")), risk, confidence)\n',
    '\n',
    '    if intent == "regime_bias_check":\n',
    '        normalized = _safe_str(parsed.get("normalized_question"), "").lower()\n',
    '        asks_trade = any(term in normalized for term in ("buy", "sell", "entry", "trade", "hold", "position", "tp", "target", "bias", "direction", "safer", "less risky"))\n',
    '        regime_side = _safe_str(c.get("regime_direction"), "").upper()\n',
    '        if regime_side not in {"BUY", "SELL", "WAIT"}:\n',
    '            regime_side = _direction_from_regime(c.get("regime"))\n',
    '        direct = f"Current major regime is **{c.get(\'regime\',\'-\')}**. Its synchronized regime direction is **{regime_side}**."\n',
    '        if not asks_trade:\n',
    '            return _format_answer(parsed, direct, "Not applicable to this question", "Not applicable", mine_regime_behavior(context).get("insight", mining.get("insight", "Using regime history.")), risk, confidence)\n',
    '        direct += " Use pressure, reliability and exit risk as confirmation before entry."\n',
    '        tp_text = _tp_zone_text(context, regime_side, False) if regime_side in {"BUY", "SELL"} else "RANGE/WAIT: no clean TP until direction confirms."\n',
    '        return _format_answer(parsed, direct, regime_side, tp_text, mine_regime_behavior(context).get("insight", mining.get("insight", "Using regime proxy.")), risk, confidence)\n',
    '\n',
    '    if intent == "history_similar_setup":\n',
    '        sim = find_similar_setup_proxy(context)\n',
    '        direct = sim.get("insight", "No exact history result; nearest current proxy used.")\n',
    '        tp_text = _tp_zone_text(context, safer_side, False) if safer_side in {"BUY", "SELL"} else "WAIT until stronger history/score support."\n',
    '        return _format_answer(parsed, direct, safer_side, tp_text, sim.get("insight", mining.get("insight", "Using fallback.")), risk, confidence)\n',
    '\n',
    '    if intent == "quality_confidence_check":\n',
    '        pe = mine_prediction_error(context)\n',
    '        missing = context.get("missing_fields", [])\n',
    '        direct = (\n',
    '            f"Prediction error is **{_safe_str(c.get(\'prediction_vs_actual_error\'), \'-\')}%**, "\n',
    '            f"direction accuracy is **{_safe_str(c.get(\'direction_accuracy\'), \'-\')}%**, "\n',
    '            f"forecast confidence is **{_safe_str(c.get(\'forecast_confidence\'), \'-\')}%**, "\n',
    '            f"and prediction reliability is **{pe.get(\'reliability\',\'normal\')}**."\n',
    '        )\n',
    '        if missing:\n',
    '            direct += f" Missing/weak fields: {\', \'.join(missing[:5])}."\n',
    '        return _format_answer(parsed, direct, "Not applicable to this question", "Not applicable", pe.get("insight", mining.get("insight", "Using current context.")), risk, confidence)\n',
    '\n',
    '    # Context-sensitive nearest fallback. Non-trading questions no longer receive\n',
    '    # an unrelated BUY/SELL answer. Trading bias is shown only when the question\n',
    '    # actually asks about direction, entry, holding, TP or action.\n',
    '    normalized = _safe_str(parsed.get("normalized_question"), "").lower()\n',
    '    trading_terms = ("buy", "sell", "entry", "enter", "trade", "hold", "tp", "target", "direction", "bias", "position")\n',
    '    is_trading_question = any(term in normalized for term in trading_terms)\n',
    '    if "regime" in normalized:\n',
    '        direct = f"Current major regime is **{c.get(\'regime\',\'-\')}**. Regime direction is **{_direction_from_regime(c.get(\'regime\'))}** and should be checked against prediction reliability."\n',
    '    elif any(term in normalized for term in ("error", "accuracy", "reliability", "correct")):\n',
    '        direct = f"Prediction error is **{_safe_str(c.get(\'prediction_vs_actual_error\'),\'-\')}%**, direction accuracy **{_safe_str(c.get(\'direction_accuracy\'),\'-\')}%**, and forecast confidence **{_safe_str(c.get(\'forecast_confidence\'),\'-\')}%**."\n',
    '    elif any(term in normalized for term in ("data", "row", "source", "update", "latest")):\n',
    '        direct = f"The answer is grounded in the latest loaded {_safe_str(c.get(\'symbol\'),\'EURUSD\')} {_safe_str(c.get(\'timeframe\'),\'H1\')} session data. Missing fields: {\', \'.join(context.get(\'missing_fields\', []) or []) or \'none detected\'}."\n',
    '    elif is_trading_question:\n',
    '        direct = f"For this trading question, current system decision is **{c.get(\'decision\',\'-\')}**, direction **{c.get(\'direction\',\'-\')}**, regime **{c.get(\'regime\',\'-\')}**, with **{_risk_level(c)}** risk."\n',
    '    else:\n',
    '        direct = f"I interpreted this as **{parsed.get(\'intent_label\',\'general system question\')}**. The most relevant current values are decision **{c.get(\'decision\',\'-\')}**, regime **{c.get(\'regime\',\'-\')}**, forecast confidence **{_safe_str(c.get(\'forecast_confidence\'),\'-\')}%**, and data availability **{\'ready\' if context.get(\'data_available\') else \'needs calculation\'}**."\n',
    '    if is_trading_question:\n',
    '        tp_text = _tp_zone_text(context, safer_side, False) if safer_side in {"BUY", "SELL"} else "WAIT; no clean TP zone."\n',
    '        card = _recommendation_card(c, safer_side, tp_text, reason)\n',
    '        return _format_answer(parsed, direct, safer_side, tp_text, mining.get("insight", "Using context-sensitive fallback."), risk, confidence, card)\n',
    '    return _format_answer(parsed, direct, "Not applicable to this question", "Not applicable", mining.get("insight", "Using context-sensitive system data."), risk, confidence)\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# UI / copy helpers\n',
    '# ---------------------------------------------------------------------------\n',
    'def _context_snapshot_text(ctx: Dict[str, Any]) -> str:\n',
    '    c = ctx.get("current", {})\n',
    '    keys = [\n',
    '        "symbol", "timeframe", "decision", "direction", "regime", "entry_score", "tp_score",\n',
    '        "exit_risk", "buy_pressure", "sell_pressure", "forecast_confidence", "last_close",\n',
    '        "upper_band", "lower_band", "direction_accuracy", "prediction_vs_actual_error",\n',
    '    ]\n',
    '    return " | ".join(f"{k}={_safe_str(c.get(k), \'-\') if not isinstance(c.get(k), list) else len(c.get(k))}" for k in keys)\n',
    '\n',
    '\n',
    'def _copy_payload(\n',
    '    raw: str,\n',
    '    parsed: Dict[str, Any],\n',
    '    answer: str,\n',
    '    ctx: Dict[str, Any],\n',
    '    selected_category: str = "-",\n',
    '    answer_mode: str = "Auto",\n',
    ') -> str:\n',
    '    return (\n',
    '        "AI ASSISTANT LITE COPY\\n"\n',
    '        "======================\\n"\n',
    '        f"Selected question category: {selected_category or \'-\'}\\n"\n',
    '        f"Answer mode: {answer_mode or \'Auto\'}\\n"\n',
    '        f"Raw question: {raw}\\n"\n',
    '        f"Normalized question: {parsed.get(\'normalized_question\',\'\')}\\n"\n',
    '        f"Interpreted intent: {parsed.get(\'intent\')} — {parsed.get(\'intent_label\')}\\n"\n',
    '        f"Similarity score: {parsed.get(\'similarity_score\')}% ({parsed.get(\'match_strength\')})\\n"\n',
    '        f"Context snapshot: {_context_snapshot_text(ctx)}\\n"\n',
    '        f"Missing data fields: {\', \'.join(ctx.get(\'missing_fields\', []) or []) or \'-\'}\\n\\n"\n',
    '        f"Final answer:\\n{answer}\\n"\n',
    '    )\n',
    '\n',
    '\n',
    'def _copy_button(label: str, text: str, key: str) -> None:\n',
    '    try:\n',
    '        from streamlit_copy_button import copy_button\n',
    '        copy_button(text, label, key=key)\n',
    '    except Exception:\n',
    '        try:\n',
    '            from core.pro_terminal_uiux import render_mobile_copy_button\n',
    '            render_mobile_copy_button(label, text, key)\n',
    '        except Exception:\n',
    '            st.text_area(label, text, height=120, key=key + "_fallback")\n',
    '\n',
    '\n',
    'def _full_chat_copy(ctx: Dict[str, Any]) -> str:\n',
    '    lines = ["AI ASSISTANT LITE FULL CHAT", "===========================", f"Context snapshot: {_context_snapshot_text(ctx)}", ""]\n',
    '    for item in st.session_state.get("ai_lite_messages", []):\n',
    '        role = _safe_str(item.get("role", "user"), "user").upper()\n',
    '        content = _safe_str(item.get("content", ""), "")\n',
    '        meta = item.get("meta", {}) if isinstance(item, dict) else {}\n',
    '        if meta:\n',
    '            lines.append(\n',
    '                f"{role}: {content}\\n"\n',
    '                f"[category={meta.get(\'selected_question_category\',\'-\')}; mode={meta.get(\'answer_mode\',\'Auto\')}; "\n',
    '                f"normalized={meta.get(\'normalized_question\',\'\')}; intent={meta.get(\'intent\',\'\')}; "\n',
    '                f"similarity={meta.get(\'similarity_score\',\'-\')}%]"\n',
    '            )\n',
    '        else:\n',
    '            lines.append(f"{role}: {content}")\n',
    '        lines.append("")\n',
    '    return "\\n".join(lines)\n',
    '\n',
    '\n',
    'def _inject_mobile_css() -> None:\n',
    '    st.markdown(\n',
    '        """\n',
    '        <style>\n',
    '        .ai-lite-shell{border:1px solid rgba(59,130,246,.18);border-radius:18px;padding:12px 13px;background:linear-gradient(135deg,rgba(255,255,255,.94),rgba(239,246,255,.72));box-shadow:0 10px 24px rgba(15,23,42,.07);margin:.35rem 0 .55rem 0;}\n',
    '        .ai-lite-header{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:4px;}\n',
    '        .ai-lite-title{font-weight:900;font-size:1.04rem;color:#0f172a;}\n',
    '        .ai-lite-badge{font-size:.74rem;font-weight:800;border-radius:999px;background:#dbeafe;color:#1e3a8a;padding:4px 9px;white-space:nowrap;}\n',
    '        .ai-lite-context{font-size:.84rem;line-height:1.35;color:#334155;}\n',
    '        .ai-lite-warning{font-size:.78rem;color:#7c2d12;background:#ffedd5;border-radius:12px;padding:8px 10px;margin:.45rem 0;}\n',
    '        .ai-lite-chip-label{font-size:.76rem;font-weight:800;color:#475569;margin:.2rem 0 .1rem 0;}\n',
    '        .ai-lite-qbox{border:1px solid rgba(14,165,233,.18);border-radius:16px;padding:10px 11px;background:rgba(248,250,252,.84);margin:.35rem 0 .55rem 0;}\n',
    '        .ai-lite-qbox-title{font-weight:900;color:#0f172a;font-size:.93rem;margin-bottom:2px;}\n',
    '        .ai-lite-qbox-note{font-size:.76rem;color:#64748b;line-height:1.25;margin-bottom:4px;}\n',
    '        .ai-lite-smart{font-size:.78rem;background:#eef6ff;border-radius:12px;padding:7px 9px;color:#334155;margin:.15rem 0 .35rem 0;}\n',
    '        .ai-lite-smart-input-head{font-size:.83rem;line-height:1.28;color:#334155;border:1px solid rgba(14,165,233,.16);border-radius:16px;background:linear-gradient(135deg,rgba(239,246,255,.94),rgba(255,255,255,.78));padding:9px 10px;margin:.35rem 0 .25rem 0;box-shadow:0 8px 18px rgba(15,23,42,.045);}\n',
    '        .ai-lite-smart-input-head b{font-weight:950;color:#0f172a;}\n',
    '        .ai-lite-smart-input-head span{font-size:.76rem;color:#64748b;}\n',
    '        .ai-lite-recognition-card{font-size:.78rem;line-height:1.32;color:#334155;border:1px solid rgba(34,197,94,.18);border-radius:14px;background:linear-gradient(135deg,rgba(240,253,244,.90),rgba(239,246,255,.76));padding:8px 10px;margin:.18rem 0 .35rem 0;}\n',
    '        .ai-lite-recognition-card b{color:#0f172a;font-weight:950}.ai-lite-recognition-card span{font-weight:900;color:#0369a1;}\n',
    '        div[data-testid="stButton"] button{min-height:31px!important;border-radius:999px!important;font-weight:800!important;padding:.14rem .44rem!important;font-size:.78rem!important;}\n',
    '        textarea, input{font-size:15px!important;}\n',
    '        .ai-lite-shadow-suggestions{border:1px solid rgba(14,165,233,.16);border-radius:14px;background:linear-gradient(135deg,rgba(248,250,252,.90),rgba(239,246,255,.76));padding:7px 9px;margin:.15rem 0 .35rem 0;box-shadow:0 7px 18px rgba(15,23,42,.045);}\n',
    '        .ai-lite-shadow-title{font-size:.73rem;font-weight:950;color:#0369a1;margin-bottom:3px;}\n',
    '        .ai-lite-shadow-row{font-size:.74rem;color:#334155;margin:2px 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}\n',
    '        .ai-lite-compact-note{font-size:.72rem;color:#64748b;line-height:1.25;}\n',
    '        section[data-testid="stSidebar"]{max-width:285px;}\n',
    '        @media(max-width:780px){\n',
    '          .ai-lite-shell{padding:10px;border-radius:16px;margin:.22rem 0 .42rem 0;}\n',
    '          .ai-lite-title{font-size:.98rem}.ai-lite-context{font-size:.80rem}.ai-lite-warning{font-size:.74rem;padding:7px 9px;}\n',
    '          .ai-lite-qbox{padding:8px 9px;border-radius:14px}.ai-lite-qbox-title{font-size:.88rem}.ai-lite-qbox-note{font-size:.72rem;}\n',
    '          div[data-testid="stMetric"]{padding:.15rem 0!important;}\n',
    '          div[data-testid="stButton"] button{min-height:44px;font-size:.86rem;padding:.28rem .55rem;}\n',
    '          .stChatMessage{padding:.25rem .35rem!important;margin:.15rem 0!important;}\n',
    '          [data-testid="stVerticalBlock"]{gap:.35rem!important;}\n',
    '        }\n',
    '        </style>\n',
    '        """,\n',
    '        unsafe_allow_html=True,\n',
    '    )\n',
    '    # Sidebar stability: no DOM close script here. Native Streamlit + main-page menu handle open/close.\n',
    '\n',
    '\n',
    'def _filter_prepared_questions(category: str, search: str, limit: int = 80) -> List[Dict[str, Any]]:\n',
    '    category = category or "All Questions"\n',
    '    cleaned_search = _plain_normalize_question_pattern(search or "")\n',
    '    alias_map = {\n',
    '        "en": "entry", "ent": "entry", "enter": "entry",\n',
    '        "tp": "take profit target", "sl": "stop loss risk",\n',
    '        "reg": "regime", "pred": "prediction", "hist": "history similar",\n',
    '        "risk": "risk exit protect", "qual": "quality confidence reliability",\n',
    '    }\n',
    '    if cleaned_search in alias_map:\n',
    '        cleaned_search = alias_map[cleaned_search]\n',
    '    terms = [t for t in cleaned_search.split() if t]\n',
    '    rows: List[Tuple[float, Dict[str, Any]]] = []\n',
    '    for item in PREPARED_QUESTION_PATTERNS:\n',
    '        if category != "All Questions" and item.get("category") != category:\n',
    '            continue\n',
    '        pattern = _safe_str(item.get("pattern"), "")\n',
    '        keywords = " ".join(map(str, item.get("keywords", []))).lower()\n',
    '        if not cleaned_search:\n',
    '            score = 1.0\n',
    '        else:\n',
    '            score = _similar(cleaned_search, pattern)\n',
    '            score += sum(0.25 for t in terms if t in pattern or t in keywords)\n',
    '            if cleaned_search in pattern:\n',
    '                score += 0.8\n',
    '        if score > 0.18 or not cleaned_search:\n',
    '            rows.append((score, item))\n',
    '    rows.sort(key=lambda x: x[0], reverse=True)\n',
    '    return [item for _, item in rows[:limit]]\n',
    '\n',
    '\n',
    'def _smart_question_suggestions(ctx: Dict[str, Any]) -> List[str]:\n',
    '    c = ctx.get("current", {})\n',
    '    suggestions: List[str] = []\n',
    '    exit_risk = _metric(c, "exit_risk", 5)\n',
    '    entry = _metric(c, "entry_score", 5)\n',
    '    buy = _num(c.get("buy_pressure"))\n',
    '    sell = _num(c.get("sell_pressure"))\n',
    '    conf = _metric(c, "forecast_confidence", 50)\n',
    '    tp = _metric(c, "tp_score", 5)\n',
    '    regime_side = _direction_from_regime(c.get("regime"))\n',
    '    pred_side = _safe_str(c.get("prediction_direction"), "-").upper()\n',
    '    has_history = any(_is_df(ctx.get(k, pd.DataFrame())) for k in ["history_df", "regime_history_df", "overlap_history_df", "prediction_history_df"])\n',
    '\n',
    '    def add(q: str) -> None:\n',
    '        if q not in suggestions and len(suggestions) < 3:\n',
    '            suggestions.append(q)\n',
    '\n',
    '    if exit_risk >= 6.5:\n',
    '        add("Should I protect my position now?")\n',
    '    if entry >= 6.5 and exit_risk < 6.5:\n',
    '        add("Is scalp entry allowed now?")\n',
    '    if buy is not None and sell is not None and buy > sell:\n',
    '        add("Is BUY safer now?")\n',
    '    if buy is not None and sell is not None and sell > buy:\n',
    '        add("Is SELL safer now?")\n',
    '    if conf < 50:\n',
    '        add("Should I wait instead of entering?")\n',
    '    if tp >= 6.2:\n',
    '        add("What TP zone is safer?")\n',
    '    if regime_side in {"BUY", "SELL"} and pred_side in {"BUY", "SELL"} and regime_side != pred_side:\n',
    '        add("Is regime conflicting with prediction?")\n',
]
