"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        ])\n',
    '    else:\n',
    '        m1, m2, m3, m4 = st.columns(4)\n',
    '        m1.metric("Data", "READY" if ctx.get("data_available") else "Need Run")\n',
    '        m2.metric("Answer Router", "Exact Question")\n',
    '        m3.metric("NLP / LLM", "CONNECTED" if nlp_connected else "LOCAL FALLBACK")\n',
    '        m4.metric("Question Patterns", f"{pattern_count:,}")\n',
    '\n',
    '    # Result is intentionally above choice box and input field.\n',
    '    st.markdown("### ✅ AI Result Display")\n',
    '    result_text = _latest_ai_result_text()\n',
    '    st.markdown(result_text)\n',
    '    _ai_20260615_copy_row(ctx)\n',
    '\n',
    '    options = ["Chat", "Local NLP", "Data Mining", "Deep Analysis", "History"]\n',
    '    if callable(tab_choice):\n',
    '        active = tab_choice("AI inner navigation", options, f"ai_inner_tabs_{UNIQUE}_20260615", default="Chat")\n',
    '    else:\n',
    '        active = st.radio("AI inner navigation", options, horizontal=True, key=f"ai_inner_tabs_radio_{UNIQUE}_20260615")\n',
    '\n',
    '    if active == "Chat":\n',
    '        _ai_20260615_render_chat(ctx)\n',
    '    elif active == "Local NLP":\n',
    '        _ai_20260615_render_local_nlp(ctx)\n',
    '    elif active == "Data Mining":\n',
    '        _ai_20260615_render_data_mining(ctx)\n',
    '    elif active == "Deep Analysis":\n',
    '        _ai_20260615_render_deep_analysis(ctx)\n',
    '    elif active == "History":\n',
    '        _ai_20260615_render_history(ctx)\n',
    '\n',
    '# =====================================================================\n',
    '# 2026-06-15 CENTRAL SHARED SYNC + AI GROUNDING PATCH\n',
    '# Non-destructive wrapper: local AI reads the shared result and cannot override\n',
    '# Regime, Priority, PowerBI/Prediction, Reliability, or Data Quality.\n',
    '# =====================================================================\n',
    'try:\n',
    '    from core.canonical_runtime_20260617 import shared_from_runtime as _adx_shared_from_runtime_20260617\n',
    '    from core.adx_shared_sync_20260615 import ground_ai_answer_text as _adx_ground_ai_answer_20260615\n',
    '\n',
    '    def _adx_ensure_shared_20260615() -> Dict[str, Any]:\n',
    '        return _adx_shared_from_runtime_20260617(st.session_state)\n',
    '\n',
    '    _ai_lite_original_build_context_20260615 = build_ai_context_from_existing_data\n',
    '    def build_ai_context_from_existing_data() -> Dict[str, Any]:  # type: ignore[no-redef]\n',
    '        """Read the compact fact pack first; never scan full project history."""\n',
    '        try:\n',
    '            from core.compact_canonical_20260619 import get_ai_fact_pack, compact_ai_context\n',
    '            fact_pack = get_ai_fact_pack(st.session_state)\n',
    '            if fact_pack:\n',
    '                return compact_ai_context(fact_pack)\n',
    '        except Exception:\n',
    '            pass\n',
    '        try:\n',
    '            shared = _adx_ensure_shared_20260615()\n',
    '            g = shared.get("ai_grounding", {}) if isinstance(shared, dict) and isinstance(shared.get("ai_grounding"), dict) else {}\n',
    '            canonical = shared.get("canonical", {}) if isinstance(shared, dict) and isinstance(shared.get("canonical"), dict) else {}\n',
    '            if g and canonical:\n',
    '                scores = g.get("full_metric_scores", {}) if isinstance(g.get("full_metric_scores"), dict) else {}\n',
    '                prediction_range = g.get("prediction_range", {}) if isinstance(g.get("prediction_range"), dict) else {}\n',
    '                current: Dict[str, Any] = {\n',
    '                    "symbol": g.get("symbol", "EURUSD"),\n',
    '                    "timeframe": g.get("timeframe", "H1"),\n',
    '                    "direction": g.get("directional_market_view", "WAIT"),\n',
    '                    "regime_direction": g.get("directional_market_view", "WAIT"),\n',
    '                    "tradeability_decision": g.get("tradeability_decision", "WAIT"),\n',
    '                    "less_risky_decision": g.get("less_risky_decision", "WAIT"),\n',
    '                    "regime": g.get("regime", "UNKNOWN"),\n',
    '                    "prediction_direction": g.get("prediction_direction", "WAIT"),\n',
    '                    "selected_horizon": g.get("selected_horizon", 3),\n',
    '                    "entry_score": scores.get("entry"),\n',
    '                    "master_score": scores.get("master"),\n',
    '                    "buy_pressure": scores.get("buy"),\n',
    '                    "sell_pressure": scores.get("sell"),\n',
    '                    "hold_score": scores.get("hold"),\n',
    '                    "tp_score": scores.get("tp"),\n',
    '                    "exit_risk": scores.get("exit_risk"),\n',
    '                    "forecast_confidence": (canonical.get("final_decision") or {}).get("calibrated_confidence"),\n',
    '                    "prediction_reliability": g.get("reliability_score"),\n',
    '                    "prediction_vs_actual_error": g.get("error_estimate"),\n',
    '                    "uncertainty": g.get("uncertainty"),\n',
    '                    "last_close": canonical.get("last_close") or (canonical.get("market") or {}).get("current_price"),\n',
    '                    "forecast_close": prediction_range.get("point"),\n',
    '                    "estimated_price_close": prediction_range.get("point"),\n',
    '                    "upper_band": prediction_range.get("upper"),\n',
    '                    "lower_band": prediction_range.get("lower"),\n',
    '                    "blocking_reasons": list(g.get("blocking_reasons") or []),\n',
    '                    "best_opportunity_rows": list(g.get("top_two_daily_candidates") or []),\n',
    '                    "last_time": g.get("latest_completed_h1_time"),\n',
    '                    "run_id": g.get("run_id"),\n',
    '                    "calculation_generation": g.get("calculation_generation"),\n',
    '                    "data_signature": g.get("data_signature"),\n',
    '                }\n',
    '                # Keep this explicit assignment for compatibility and to make the\n',
    '                # first AI decision auditable against Lunch/Finder/Dinner.\n',
    '                current["decision"] = g.get("decision", "DATA NOT READY")\n',
    '                history_df = pd.DataFrame(canonical.get("full_metric_history") or [])\n',
    '                priority_df = shared.get("hourly_priority_table")\n',
    '                if not isinstance(priority_df, pd.DataFrame):\n',
    '                    priority_df = pd.DataFrame(canonical.get("canonical_priority_table") or [])\n',
    '                forecasts = ((canonical.get("forecasts") or {}).get("horizons") or {})\n',
    '                predicted_df = pd.DataFrame([\n',
    '                    {"horizon": key, **value}\n',
    '                    for key, value in forecasts.items() if isinstance(value, dict)\n',
    '                ])\n',
    '                missing_fields = [\n',
    '                    key for key in ("entry_score", "tp_score", "exit_risk", "last_close", "forecast_confidence")\n',
    '                    if current.get(key) in (None, "", "-")\n',
    '                ]\n',
    '                return {\n',
    '                    "data_available": True,\n',
    '                    "current": current,\n',
    '                    "flat": {},\n',
    '                    "ohlc_df": pd.DataFrame(),\n',
    '                    "predicted_df": predicted_df,\n',
    '                    "history_df": history_df,\n',
    '                    "regime_history_df": pd.DataFrame(),\n',
    '                    "overlap_history_df": priority_df,\n',
    '                    "prediction_history_df": pd.DataFrame(),\n',
    '                    "missing_fields": missing_fields,\n',
    '                    "missing_message": "Canonical calculation is ready.",\n',
    '                    "shared_calc_result": shared,\n',
    '                    "ai_grounding": g,\n',
    '                    "reliability_calibration": shared.get("reliability", {}),\n',
    '                    "prediction_feedback": shared.get("prediction_feedback", {}),\n',
    '                    "regime_alpha_delta": shared.get("regime_alpha_delta", {}),\n',
    '                    "data_quality": canonical.get("data_quality", {}),\n',
    '                    "read_only_canonical": True,\n',
    '                }\n',
    '        except Exception:\n',
    '            pass\n',
    '        # Legacy context is available only before the first valid canonical run;\n',
    '        # it cannot publish or override an operational answer.\n',
    '        return _ai_lite_original_build_context_20260615()\n',
    '\n',
    '    _ai_lite_original_generate_answer_20260615 = local_ai_generate_answer\n',
    '    def local_ai_generate_answer(parsed: Dict[str, Any], context: Dict[str, Any]) -> str:  # type: ignore[no-redef]\n',
    '        answer = _ai_lite_original_generate_answer_20260615(parsed, context)\n',
    '        try:\n',
    '            question = str(parsed.get("raw_question") or parsed.get("normalized_question") or "") if isinstance(parsed, dict) else ""\n',
    '            return _adx_ground_ai_answer_20260615(answer, question)\n',
    '        except Exception:\n',
    '            return answer\n',
    '\n',
    '    def show() -> None:\n',
    '        return render_ai_assistant_lite_tab()\n',
    'except Exception:\n',
    '    def show() -> None:\n',
    '        return render_ai_assistant_lite_tab()\n',
]
