"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '                q = finite_or_none(caviar_q.get("quantile_forecast"))\n',
    '                if q is not None:\n',
    '                    v = max(1e-12, -q)\n',
    '                    tail = losses.dropna()\n',
    '                    exceed = tail.loc[tail >= v]\n',
    '                    if len(exceed):\n',
    '                        e = max(v, float(exceed.mean()))\n',
    '                        scores = [fz0_positive_loss_score(float(loss), v, e, alpha) for loss in tail.iloc[-600:]]\n',
    '                        candidates.append({"candidate": "caviar_plus_empirical_es", "mean_joint_score": float(np.mean(scores)), "settled_sample_count": len(scores), "available": True})\n',
    '                candidates.extend([\n',
    '                    {"candidate": "existing_forecast_distribution_tail", "mean_joint_score": None, "settled_sample_count": 0, "available": False, "reason": "No aligned settled distribution tail supplied."},\n',
    '                ])\n',
    '                ranked = sorted([x for x in candidates if x.get("available") and x.get("mean_joint_score") is not None], key=lambda x: (x["mean_joint_score"], x["candidate"]))\n',
    '                levels[f"{alpha:.2f}"] = {"ranking": ranked, "all_candidates": candidates, "winner": ranked[0]["candidate"] if ranked else None}\n',
    '            rankings[str(horizon)] = levels\n',
    '        return method_contract(\n',
    '            identity,\n',
    '            method_name="FISSLER_ZIEGEL_JOINT_VAR_ES_SCORE",\n',
    '            method_version=FZ_FORMULA_VERSION,\n',
    '            sample_count=int(sum(len(_horizon_returns(frame, h).dropna()) for h in HORIZONS)),\n',
    '            minimum_sample_required=minimum,\n',
    '            fallback_level="AVAILABLE_CANDIDATES_ONLY",\n',
    '            reliability_status="SUPPORTED",\n',
    '            assumption_status="CORRECTED_DOMAIN_CONDITIONS_ENFORCED",\n',
    '            limitations=(\n',
    '                "The FZ0 score is used only when 0<alpha<1 and ES>=VaR>0 under the positive-loss convention.",\n',
    '                "Candidate promotion requires settled chronological evidence; RMSE is not used for ES ranking.",\n',
    '                "Lower joint score is comparative evidence, not a guarantee of future tail calibration.",\n',
    '            ),\n',
    '            status="AVAILABLE",\n',
    '            loss_convention="Positive values are adverse losses; VaR is a positive threshold; ES>=VaR.",\n',
    '            exact_score_formula="I(loss>=VaR)*(loss-VaR)/(alpha*ES) + VaR/ES + log(ES) - 1",\n',
    '            formula_version=FZ_FORMULA_VERSION,\n',
    '            correction_conditions={"alpha_open_interval": True, "es_not_smaller_than_var": True, "positive_finite_es": True, "settled_chronological_outcomes_only": True},\n',
    '            rankings=rankings,\n',
    '        )\n',
    '    except Exception as exc:\n',
    '        return unavailable_contract(identity, "FISSLER_ZIEGEL_JOINT_VAR_ES_SCORE", FZ_FORMULA_VERSION, exc, minimum_sample_required=minimum)\n',
    '\n',
    '\n',
    'def cvar_risk_budget(\n',
    '    frame: pd.DataFrame,\n',
    '    identity: ResearchIdentity,\n',
    '    canonical: Mapping[str, Any],\n',
    '    *,\n',
    '    transaction_cost_return: float = 0.0,\n',
    ') -> dict[str, Any]:\n',
    '    minimum = 80\n',
    '    try:\n',
    '        final = canonical.get("final_decision") if isinstance(canonical.get("final_decision"), Mapping) else {}\n',
    '        direction = str(final.get("directional_market_view") or final.get("final_decision") or "WAIT").upper()\n',
    '        existing = finite_or_none(final.get("display_risk_multiplier"))\n',
    '        if existing is None:\n',
    '            existing = finite_or_none((canonical.get("risk_plan") or {}).get("risk_multiplier"))\n',
    '        existing = float(np.clip(existing if existing is not None else 1.0, 0.0, 1.0))\n',
    '        horizon = int(final.get("selected_horizon") or 1)\n',
    '        horizon = horizon if horizon in HORIZONS else 1\n',
    '        returns_h = _horizon_returns(frame, horizon).dropna()\n',
    '        if len(returns_h) < minimum:\n',
    '            raise ValueError(f"CVaR scenarios require at least {minimum} settled horizon returns.")\n',
    '        if direction == "BUY":\n',
    '            unit_losses = -returns_h.to_numpy(dtype=float)\n',
    '        elif direction == "SELL":\n',
    '            unit_losses = returns_h.to_numpy(dtype=float)\n',
    '        else:\n',
    '            unit_losses = np.abs(returns_h.to_numpy(dtype=float))\n',
    '        alpha = 0.95\n',
    '        base_var = float(np.quantile(unit_losses, alpha))\n',
    '        base_tail = unit_losses[unit_losses >= base_var]\n',
    '        base_cvar = float(np.mean(base_tail)) if len(base_tail) else base_var\n',
    '        max_cvar = max(base_cvar, 1e-12)\n',
    '        daily_room = finite_or_none((canonical.get("risk_plan") or {}).get("daily_risk_room"))\n',
    '        daily_room = float(daily_room) if daily_room is not None and daily_room > 0 else max_cvar\n',
    '        evaluations: list[dict[str, Any]] = []\n',
    '        permitted: list[float] = []\n',
    '        for multiplier in (0.00, 0.25, 0.50, 0.75, 1.00):\n',
    '            adjusted = unit_losses * multiplier + abs(float(transaction_cost_return)) * multiplier\n',
    '            var = float(np.quantile(adjusted, alpha))\n',
    '            tail = adjusted[adjusted >= var]\n',
    '            cvar = float(np.mean(tail)) if len(tail) else var\n',
    '            expected = float(np.mean(adjusted))\n',
    '            consumption = safe_div(cvar, daily_room, 0.0)\n',
    '            within_existing = multiplier <= existing + 1e-12\n',
    '            satisfies = bool(within_existing and cvar <= max_cvar * existing + 1e-12 and (consumption or 0.0) <= 1.0 + 1e-12)\n',
    '            if satisfies:\n',
    '                permitted.append(multiplier)\n',
    '            evaluations.append({\n',
    '                "risk_multiplier": multiplier,\n',
    '                "expected_loss": expected,\n',
    '                "empirical_var": var,\n',
    '                "empirical_cvar": cvar,\n',
    '                "worst_supported_loss": float(np.max(adjusted)),\n',
    '                "effective_sample_count": len(adjusted),\n',
    '                "fallback_level": "GLOBAL_HORIZON",\n',
    '                "transaction_cost_adjusted_loss": expected,\n',
    '                "daily_risk_room_consumption": consumption,\n',
    '                "satisfies_limits": satisfies,\n',
    '            })\n',
    '        selected = max(permitted) if permitted else 0.0\n',
    '        selected = min(selected, existing)\n',
    '        return method_contract(\n',
    '            identity,\n',
    '            method_name="ROCKAFELLAR_URYASEV_CVAR_RISK_BUDGET",\n',
    '            method_version=CVAR_VERSION,\n',
    '            horizon_hours=horizon,\n',
    '            condition_key=f"{direction}|H{horizon}",\n',
    '            sample_count=len(unit_losses),\n',
    '            minimum_sample_required=minimum,\n',
    '            fallback_level="GLOBAL_HORIZON",\n',
    '            reliability_status="SUPPORTED",\n',
    '            assumption_status="EMPIRICAL_SCENARIO_ADAPTATION",\n',
    '            limitations=(\n',
    '                "Historical analogue scenarios use a hierarchical fallback; current package evidence may fall back to global horizon.",\n',
    '                "The selected multiplier is advisory shadow evidence and cannot increase existing risk or place an order.",\n',
    '            ),\n',
    '            status="AVAILABLE",\n',
    '            protected_direction=direction,\n',
    '            existing_risk_multiplier=existing,\n',
    '            selected_risk_multiplier=selected,\n',
    '            risk_multiplier_increased=False,\n',
    '            evaluations=evaluations,\n',
    '            scenario_hierarchy_used="direction+horizon -> global horizon fallback",\n',
    '            order_placement_allowed=False,\n',
    '        )\n',
    '    except Exception as exc:\n',
    '        final = canonical.get("final_decision") if isinstance(canonical.get("final_decision"), Mapping) else {}\n',
    '        original = finite_or_none(final.get("display_risk_multiplier"))\n',
    '        result = unavailable_contract(identity, "ROCKAFELLAR_URYASEV_CVAR_RISK_BUDGET", CVAR_VERSION, exc, minimum_sample_required=minimum)\n',
    '        result.update({"original_protected_risk_multiplier": original, "protected_result_preserved": True, "warning": "CVaR evidence failed safely; protected result was not changed."})\n',
    '        return result\n',
    '\n',
    '\n',
    'def _piecewise_pit(levels: np.ndarray, values: np.ndarray, realized: float) -> float:\n',
    '    # Explicit linear tails between (value_0 - scale, 0) and first quantile,\n',
    '    # and last quantile to (value_last + scale, 1).\n',
    '    scale = max(float(np.std(values)), abs(float(values[-1] - values[0])), 1e-6)\n',
    '    x = np.r_[values[0] - 2.0 * scale, values, values[-1] + 2.0 * scale]\n',
    '    p = np.r_[0.0, levels, 1.0]\n',
    '    return float(np.interp(realized, x, p, left=0.0, right=1.0))\n',
    '\n',
    '\n',
    'def density_pit_diagnostics(frame: pd.DataFrame, identity: ResearchIdentity, *, window: int = 240) -> dict[str, Any]:\n',
    '    minimum = window + 60\n',
    '    try:\n',
    '        horizon_outputs: dict[str, Any] = {}\n',
    '        for horizon in HORIZONS:\n',
    '            realized = _horizon_returns(frame, horizon)\n',
    '            records: list[dict[str, Any]] = []\n',
    '            for i in range(window, len(frame) - horizon):\n',
    '                past = realized.iloc[max(0, i - window):i].dropna().to_numpy(dtype=float)\n',
    '                actual = finite_or_none(realized.iloc[i])\n',
    '                if len(past) < max(60, window // 2) or actual is None:\n',
    '                    continue\n',
    '                original = np.quantile(past, QUANTILE_LEVELS).astype(float)\n',
    '                rearranged = np.maximum.accumulate(original)\n',
    '                severity = float(np.max(rearranged - original))\n',
    '                scale = float(np.std(past)) or 1e-12\n',
    '                severe = severity > 0.5 * scale\n',
    '                if severe:\n',
    '                    continue\n',
    '                pit = _piecewise_pit(np.asarray(QUANTILE_LEVELS, dtype=float), rearranged, actual)\n',
    '                epsilon = 1e-8\n',
    '                clipped = min(max(pit, epsilon), 1.0 - epsilon)\n',
    '                records.append({\n',
    '                    "forecast_origin_time": frame["time"].iloc[i].isoformat(),\n',
    '                    "settled_target_time": frame["time"].iloc[i + horizon].isoformat(),\n',
    '                    "pit_value": pit,\n',
    '                    "transformed_normal_score": norm_ppf(clipped, epsilon),\n',
    '                    "original_quantiles": original.tolist(),\n',
    '                    "rearranged_quantiles": rearranged.tolist(),\n',
    '                    "crossing_severity": severity,\n',
    '                    "cdf_construction_status": "MONOTONE" if severity <= 1e-15 else "MINOR_CROSSING_REARRANGED",\n',
    '                })\n',
    '            pits = np.asarray([r["pit_value"] for r in records], dtype=float)\n',
    '            if len(pits) < 40:\n',
    '                horizon_outputs[str(horizon)] = {"status": "INSUFFICIENT_SAMPLE", "sample_count": len(pits), "records_tail": records[-20:]}\n',
    '                continue\n',
    '            autocorr: dict[str, float | None] = {}\n',
    '            for lag in range(1, 7):\n',
    '                if len(pits) <= lag or np.std(pits[:-lag]) <= 1e-12 or np.std(pits[lag:]) <= 1e-12:\n',
    '                    autocorr[str(lag)] = None\n',
    '                else:\n',
    '                    autocorr[str(lag)] = float(np.corrcoef(pits[:-lag], pits[lag:])[0, 1])\n',
    '            hist, edges = np.histogram(pits, bins=np.linspace(0.0, 1.0, 11))\n',
    '            horizon_outputs[str(horizon)] = {\n',
    '                "status": "AVAILABLE",\n',
    '                "sample_count": len(pits),\n',
    '                "pit_mean": float(np.mean(pits)),\n',
    '                "pit_variance": float(np.var(pits, ddof=1)),\n',
    '                "uniformity_histogram": hist.tolist(),\n',
    '                "histogram_edges": edges.tolist(),\n',
    '                "tail_concentration": float(np.mean((pits < 0.05) | (pits > 0.95))),\n',
    '                "autocorrelation_lag_1_to_6": autocorr,\n',
    '                "condition_level_diagnostics": {"GLOBAL": {"sample_count": len(pits), "mean": float(np.mean(pits)), "variance": float(np.var(pits, ddof=1))}},\n',
    '                "records_tail": records[-60:],\n',
    '                "all_pit_values": pits.tolist(),\n',
    '            }\n',
    '        available = [x for x in horizon_outputs.values() if x.get("status") == "AVAILABLE"]\n',
    '        return method_contract(\n',
    '            identity,\n',
    '            method_name="DIEBOLD_GUNTHER_TAY_PIT_DIAGNOSTICS",\n',
    '            method_version=DENSITY_VERSION,\n',
    '            sample_count=max([int(x.get("sample_count", 0)) for x in horizon_outputs.values()] or [0]),\n',
    '            minimum_sample_required=minimum,\n',
    '            fallback_level="ROLLING_EMPIRICAL_QUANTILE_CDF",\n',
    '            reliability_status="SUPPORTED" if available else "INSUFFICIENT_SAMPLE",\n',
    '            assumption_status="CAUSAL_SETTLED_DENSITY_DIAGNOSTIC",\n',
    '            limitations=(\n',
    '                "The CDF uses causal rolling quantiles and monotone piecewise-linear interpolation with explicit finite tails.",\n',
    '                "Severe quantile crossing is not silently repaired; those PIT observations are excluded with status evidence.",\n',
    '                "Overlapping horizons can induce serial dependence, which is separately diagnosed.",\n',
    '            ),\n',
    '            status="AVAILABLE" if available else "INSUFFICIENT_SAMPLE",\n',
    '            horizons=horizon_outputs,\n',
    '        )\n',
    '    except Exception as exc:\n',
    '        return unavailable_contract(identity, "DIEBOLD_GUNTHER_TAY_PIT_DIAGNOSTICS", DENSITY_VERSION, exc, minimum_sample_required=minimum)\n',
    '\n',
    '\n',
    'def berkowitz_test_from_pits(pits: Sequence[float]) -> dict[str, Any]:\n',
    '    epsilon = 1e-8\n',
    '    p = np.asarray([min(max(float(x), epsilon), 1.0 - epsilon) for x in pits if math.isfinite(float(x))], dtype=float)\n',
    '    z = np.asarray([norm_ppf(x, epsilon) for x in p], dtype=float)\n',
    '    n = len(z)\n',
    '    if n < 25:\n',
    '        return {"status": "INSUFFICIENT_SAMPLE", "sample_count": n, "small_sample_warning": True}\n',
    '    null_ll = float(np.sum(-0.5 * (math.log(2.0 * math.pi) + z * z)))\n',
    '    y, x = z[1:], z[:-1]\n',
    '    x_mean, y_mean = float(np.mean(x)), float(np.mean(y))\n',
    '    denominator = float(np.sum((x - x_mean) ** 2))\n',
    '    rho = float(np.sum((x - x_mean) * (y - y_mean)) / denominator) if denominator > 1e-12 else 0.0\n',
    '    rho = float(np.clip(rho, -0.995, 0.995))\n',
    '    mu = float((y_mean - rho * x_mean) / (1.0 - rho)) if abs(1.0 - rho) > 1e-8 else y_mean\n',
    '    residuals = y - mu - rho * (x - mu)\n',
    '    variance = float(max(np.mean(residuals ** 2), 1e-12))\n',
    '    alternative_ll = float(np.sum(-0.5 * (math.log(2.0 * math.pi * variance) + (residuals ** 2) / variance)))\n',
    '    lr = max(0.0, 2.0 * (alternative_ll - null_ll))\n',
    '    p_value, source = chi_square_sf(lr, 3)\n',
    '    if p_value is None:\n',
    '        status = "WARNING"\n',
    '    elif p_value < 0.01:\n',
    '        status = "FAIL"\n',
    '    elif p_value < 0.05:\n',
    '        status = "WARNING"\n',
    '    else:\n',
    '        status = "PASS"\n',
    '    return {\n',
    '        "status": status,\n',
    '        "null_log_likelihood": null_ll,\n',
    '        "alternative_log_likelihood": alternative_ll,\n',
    '        "lr_statistic": lr,\n',
    '        "degrees_of_freedom": 3,\n',
    '        "approximate_p_value": p_value,\n',
    '        "p_value_source": source,\n',
    '        "estimated_mean": mu,\n',
    '        "estimated_variance": variance,\n',
    '        "estimated_rho": rho,\n',
    '        "sample_count": n,\n',
    '        "small_sample_warning": n < 100,\n',
    '        "pit_clip_epsilon": epsilon,\n',
    '    }\n',
    '\n',
    '\n',
    'def berkowitz_density_tests(identity: ResearchIdentity, pit_result: Mapping[str, Any]) -> dict[str, Any]:\n',
    '    try:\n',
    '        horizons: dict[str, Any] = {}\n',
    '        for horizon in HORIZONS:\n',
    '            pit_h = (pit_result.get("horizons") or {}).get(str(horizon)) or {}\n',
    '            pits = pit_h.get("all_pit_values") or []\n',
    '            horizons[str(horizon)] = berkowitz_test_from_pits(pits)\n',
    '        statuses = [x.get("status") for x in horizons.values()]\n',
    '        overall = "FAIL" if "FAIL" in statuses else ("WARNING" if "WARNING" in statuses else ("PASS" if "PASS" in statuses else "INSUFFICIENT_SAMPLE"))\n',
    '        return method_contract(\n',
    '            identity,\n',
    '            method_name="BERKOWITZ_DENSITY_TEST",\n',
    '            method_version=BERKOWITZ_VERSION,\n',
    '            sample_count=max([int(x.get("sample_count", 0)) for x in horizons.values()] or [0]),\n',
    '            minimum_sample_required=25,\n',
    '            fallback_level="SCIPY_OR_DOCUMENTED_CRITICAL_VALUE",\n',
    '            reliability_status=overall,\n',
    '            assumption_status="GAUSSIAN_AR1_ALTERNATIVE_DIAGNOSTIC",\n',
    '            limitations=(\n',
    '                "PIT clipping uses only a documented numerical epsilon and does not hide poor forecasts.",\n',
    '                "The Gaussian AR(1) alternative is a calibration diagnostic, not a complete density model.",\n',
    '                "A failure can lower density trust or recommend WAIT but cannot replace an existing forecast path.",\n',
    '            ),\n',
    '            status=overall,\n',
    '            horizons=horizons,\n',
    '            allowed_effects=["LOWER_DENSITY_TRUST", "CALIBRATION_WARNING", "LOWER_SHADOW_READINESS", "RECOMMEND_WAIT"],\n',
    '            forecast_path_replacement_allowed=False,\n',
    '        )\n',
    '    except Exception as exc:\n',
    '        return unavailable_contract(identity, "BERKOWITZ_DENSITY_TEST", BERKOWITZ_VERSION, exc, minimum_sample_required=25)\n',
    '\n',
    '\n',
    'def build_tail_density_stack(\n',
    '    frame: pd.DataFrame,\n',
    '    identity: ResearchIdentity,\n',
    '    *,\n',
    '    volatility_stack: Mapping[str, Any] | None = None,\n',
    '    canonical: Mapping[str, Any] | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    canonical = canonical or {}\n',
    '    caviar = caviar_shadow_quantiles(frame, identity)\n',
    '    taylor = taylor_semiparametric_var_es(frame, identity, caviar, volatility_stack=volatility_stack, canonical=canonical)\n',
    '    joint = joint_var_es_scoring(frame, identity, caviar, taylor)\n',
    '    cvar = cvar_risk_budget(frame, identity, canonical)\n',
    '    pit = density_pit_diagnostics(frame, identity)\n',
    '    berkowitz = berkowitz_density_tests(identity, pit)\n',
    '    return {\n',
    '        "version": VERSION,\n',
    '        "caviar": caviar,\n',
    '        "joint_var_es": joint,\n',
    '        "taylor_var_es": taylor,\n',
    '        "cvar_risk_budget": cvar,\n',
    '        "density_pit": pit,\n',
    '        "berkowitz": berkowitz,\n',
    '    }\n',
    '\n',
    '\n',
    '__all__ = [\n',
    '    "VERSION", "quantile_loss", "caviar_shadow_quantiles", "fz0_positive_loss_score",\n',
    '    "taylor_semiparametric_var_es", "joint_var_es_scoring", "cvar_risk_budget",\n',
    '    "density_pit_diagnostics", "berkowitz_test_from_pits", "berkowitz_density_tests",\n',
    '    "build_tail_density_stack",\n',
    ']\n',
]
