"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Research-grounded, bounded Similar-Day Intelligence for EURUSD H1.\n',
    '\n',
    'This module is calculation-only and has no Streamlit import.  It consumes the\n',
    'already validated completed-H1 frame and the canonical result being built by\n',
    'the Settings transaction.  Renderers only read its published payload.\n',
    '\n',
    'Practical concepts implemented without heavy dependencies:\n',
    '- low-cost feature screening and robust historical-only scaling;\n',
    '- matrix-profile-style subsequence joins and MPdist-inspired robust distance;\n',
    '- narrow-band DTW with LB-Keogh and early abandoning;\n',
    '- k-Shape-style z-normalized shape comparison;\n',
    '- compact catch22-style statistical characteristics;\n',
    '- rolling-origin baseline validation;\n',
    '- bounded deterministic cache identity and atomic SQLite persistence.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from collections import OrderedDict\n',
    'from dataclasses import asdict\n',
    'from datetime import date, datetime, timedelta, timezone\n',
    'import hashlib\n',
    'import json\n',
    'import math\n',
    'from pathlib import Path\n',
    'import sqlite3\n',
    'import time\n',
    'from typing import Any, Iterable, Mapping, MutableMapping, Sequence\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'from core.similar_day_config_20260619 import CONFIG, SimilarDayConfig\n',
    '\n',
    '\n',
    'DB_PATH = Path(__file__).resolve().parents[1] / "data" / "adx_similarity_store.sqlite3"\n',
    'CACHE_STATE_KEY = "similar_day_bounded_cache_20260619"\n',
    'ACTIVE_STATE_KEY = "similar_day_intelligence_20260619"\n',
    'STORE_SCHEMA_VERSION = "1.0.0"\n',
    'PIP_FACTOR = 10_000.0\n',
    '\n',
    '_TIME_ALIASES = ("time", "timestamp", "datetime", "date", "candle time", "candle_time")\n',
    '_OHLC_ALIASES = {\n',
    '    "open": ("open", "o"),\n',
    '    "high": ("high", "h"),\n',
    '    "low": ("low", "l"),\n',
    '    "close": ("close", "c"),\n',
    '    "volume": ("volume", "tick_volume", "tick volume", "real_volume", "v"),\n',
    '}\n',
    '_METRIC_ALIASES = {\n',
    '    "master_score": ("master score", "master_score", "master /10", "master/10"),\n',
    '    "entry_score": ("entry score", "entry_score", "entry /10", "entry/10"),\n',
    '    "hold_safety": ("hold safety", "hold_safety", "hold /10", "hold/10"),\n',
    '    "exit_risk": ("exit risk", "exit_risk", "exit risk /10", "exit risk/10"),\n',
    '    "tp_quality": ("tp quality", "tp_quality", "tp /10", "tp/10"),\n',
    '    "trend_capacity": ("trend capacity remaining", "trend_capacity_remaining", "trend capacity"),\n',
    '    "buy_pressure": ("buy pressure", "buy_pressure", "buy score", "buy_score"),\n',
    '    "sell_pressure": ("sell pressure", "sell_pressure", "sell score", "sell_score"),\n',
    '    "market_quality": ("market quality", "market_quality", "data quality score"),\n',
    '    "forecast_agreement": ("forecast agreement", "forecast_agreement", "path agreement"),\n',
    '    "reliability": ("reliability", "reliability %", "regime reliability"),\n',
    '    "compression": ("compression", "compression score", "compression_score"),\n',
    '    "adx": ("adx", "adx value"),\n',
    '    "plus_di": ("+di", "plus_di", "plus di"),\n',
    '    "minus_di": ("-di", "minus_di", "minus di"),\n',
    '}\n',
    '_TEXT_ALIASES = {\n',
    '    "h1_regime": ("h1 regime", "h1_regime", "major regime", "regime"),\n',
    '    "h4_regime": ("h4 regime", "h4_regime"),\n',
    '    "d1_regime": ("d1 regime", "d1_regime"),\n',
    '    "decision": ("historical decision", "decision", "current decision", "prediction direction"),\n',
    '    "less_risky_decision": ("historical less-risky decision", "less risky decision", "less-risky bias", "less_risky_decision"),\n',
    '    "conflict_status": ("conflict status", "conflict_status"),\n',
    '    "counter_trend": ("counter trend", "counter-trend", "counter_trend"),\n',
    '}\n',
    '\n',
    '\n',
    'def _utc_now_iso() -> str:\n',
    '    return datetime.now(timezone.utc).isoformat()\n',
    '\n',
    '\n',
    'def _json_safe(value: Any) -> Any:\n',
    '    if isinstance(value, Mapping):\n',
    '        return {str(k): _json_safe(v) for k, v in value.items()}\n',
    '    if isinstance(value, (list, tuple)):\n',
    '        return [_json_safe(v) for v in value]\n',
    '    if isinstance(value, (np.integer,)):\n',
    '        return int(value)\n',
    '    if isinstance(value, (np.floating,)):\n',
    '        value = float(value)\n',
    '        return None if not math.isfinite(value) else value\n',
    '    if isinstance(value, (pd.Timestamp, datetime, date)):\n',
    '        return pd.Timestamp(value).isoformat()\n',
    '    if pd.isna(value) if not isinstance(value, (str, bytes, Mapping, list, tuple)) else False:\n',
    '        return None\n',
    '    return value\n',
    '\n',
    '\n',
    'def _norm_name(value: Any) -> str:\n',
    '    return " ".join(str(value).strip().lower().replace("_", " ").replace("-", " ").split())\n',
    '\n',
    '\n',
    'def _find_column(frame: pd.DataFrame, aliases: Sequence[str]) -> str | None:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return None\n',
    '    lookup = {_norm_name(c): str(c) for c in frame.columns}\n',
    '    for alias in aliases:\n',
    '        if _norm_name(alias) in lookup:\n',
    '            return lookup[_norm_name(alias)]\n',
    '    return None\n',
    '\n',
    '\n',
    'def _safe_float(value: Any, default: float = 0.0) -> float:\n',
    '    try:\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(value: Any, low: float = 0.0, high: float = 100.0) -> float:\n',
    '    return float(np.clip(_safe_float(value), low, high))\n',
    '\n',
    '\n',
    'def _direction_from_pips(pips: Any, threshold: float = 0.5) -> str:\n',
    '    if pips is None or not math.isfinite(_safe_float(pips, float("nan"))):\n',
    '        return "Unavailable"\n',
    '    value = float(pips)\n',
    '    if value > threshold:\n',
    '        return "BUY"\n',
    '    if value < -threshold:\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _broad_regime(value: Any) -> str:\n',
    '    text = str(value or "UNKNOWN").upper()\n',
    '    if "BULL" in text or text in {"BUY", "UP", "LONG"}:\n',
    '        return "BULL"\n',
    '    if "BEAR" in text or text in {"SELL", "DOWN", "SHORT"}:\n',
    '        return "BEAR"\n',
    '    if any(token in text for token in ("RANGE", "COMPRESS", "SIDEWAY", "NEUTRAL", "WAIT")):\n',
    '        return "RANGE"\n',
    '    return "UNKNOWN"\n',
    '\n',
    '\n',
    'def _normalize_decision(value: Any) -> str:\n',
    '    text = str(value or "WAIT").upper()\n',
    '    if "BUY" in text or "LONG" in text:\n',
    '        return "BUY"\n',
    '    if "SELL" in text or "SHORT" in text:\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _weighted_median(values: Sequence[float], weights: Sequence[float]) -> float | None:\n',
    '    pairs = [(float(v), max(0.0, float(w))) for v, w in zip(values, weights) if v is not None and math.isfinite(float(v)) and float(w) > 0]\n',
    '    if not pairs:\n',
    '        return None\n',
    '    pairs.sort(key=lambda item: item[0])\n',
    '    total = sum(w for _, w in pairs)\n',
    '    threshold = total / 2.0\n',
    '    running = 0.0\n',
    '    for value, weight in pairs:\n',
    '        running += weight\n',
    '        if running >= threshold:\n',
    '            return value\n',
    '    return pairs[-1][0]\n',
    '\n',
    '\n',
    'def _score_from_distance(distance: float, scale: float = 1.0) -> float:\n',
    '    if not math.isfinite(distance):\n',
    '        return 0.0\n',
    '    return _clip(100.0 * math.exp(-max(0.0, distance) / max(scale, 1e-9)))\n',
    '\n',
    '\n',
    'def _z_normalize(values: Sequence[float]) -> np.ndarray:\n',
    '    arr = np.asarray(values, dtype=np.float32)\n',
    '    if arr.size == 0:\n',
    '        return arr\n',
    '    mean = float(np.nanmean(arr))\n',
    '    std = float(np.nanstd(arr))\n',
    '    if not math.isfinite(std) or std < 1e-8:\n',
    '        return np.zeros_like(arr, dtype=np.float32)\n',
    '    return ((arr - mean) / std).astype(np.float32, copy=False)\n',
    '\n',
    '\n',
    'def _resample_path(values: Sequence[float], points: int = 8) -> np.ndarray:\n',
    '    arr = np.asarray(values, dtype=np.float32)\n',
    '    if arr.size == 0:\n',
    '        return np.zeros(points, dtype=np.float32)\n',
    '    if arr.size == 1:\n',
    '        return np.repeat(arr, points).astype(np.float32)\n',
    '    x_old = np.linspace(0.0, 1.0, arr.size)\n',
    '    x_new = np.linspace(0.0, 1.0, points)\n',
    '    return np.interp(x_new, x_old, arr).astype(np.float32)\n',
    '\n',
    '\n',
    'def _sliding_windows(values: Sequence[float], window: int) -> np.ndarray:\n',
    '    arr = np.asarray(values, dtype=np.float32)\n',
    '    window = max(2, min(int(window), int(arr.size)))\n',
    '    if arr.size < window:\n',
    '        return np.empty((0, window), dtype=np.float32)\n',
    '    try:\n',
    '        windows = np.lib.stride_tricks.sliding_window_view(arr, window)\n',
    '    except Exception:\n',
    '        windows = np.vstack([arr[i : i + window] for i in range(arr.size - window + 1)])\n',
    '    means = windows.mean(axis=1, keepdims=True)\n',
    '    stds = windows.std(axis=1, keepdims=True)\n',
    '    stds = np.where(stds < 1e-8, 1.0, stds)\n',
    '    return ((windows - means) / stds).astype(np.float32, copy=False)\n',
    '\n',
    '\n',
    'def matrix_profile_style_distance(a: Sequence[float], b: Sequence[float]) -> float:\n',
    '    """Symmetric AB-join-like subsequence distance for short intraday paths."""\n',
    '    a_arr, b_arr = np.asarray(a, dtype=np.float32), np.asarray(b, dtype=np.float32)\n',
    '    if min(a_arr.size, b_arr.size) < 4:\n',
    '        return float("inf")\n',
    '    window = max(4, min(8, min(a_arr.size, b_arr.size) // 2 or 4))\n',
    '    aw, bw = _sliding_windows(a_arr, window), _sliding_windows(b_arr, window)\n',
    '    if aw.size == 0 or bw.size == 0:\n',
    '        return float("inf")\n',
    '    distances = np.sqrt(np.mean((aw[:, None, :] - bw[None, :, :]) ** 2, axis=2))\n',
    '    profile_ab = distances.min(axis=1)\n',
    '    profile_ba = distances.min(axis=0)\n',
    '    return float(np.mean(np.concatenate([profile_ab, profile_ba])))\n',
    '\n',
    '\n',
    'def mpdist_inspired_distance(a: Sequence[float], b: Sequence[float]) -> float:\n',
    '    """Robust MPdist-inspired quantile of bidirectional join profiles."""\n',
    '    a_arr, b_arr = np.asarray(a, dtype=np.float32), np.asarray(b, dtype=np.float32)\n',
    '    if min(a_arr.size, b_arr.size) < 4:\n',
    '        return float("inf")\n',
    '    window = max(4, min(8, min(a_arr.size, b_arr.size) // 2 or 4))\n',
    '    aw, bw = _sliding_windows(a_arr, window), _sliding_windows(b_arr, window)\n',
    '    if aw.size == 0 or bw.size == 0:\n',
    '        return float("inf")\n',
    '    distances = np.sqrt(np.mean((aw[:, None, :] - bw[None, :, :]) ** 2, axis=2))\n',
    '    joined = np.sort(np.concatenate([distances.min(axis=1), distances.min(axis=0)]))\n',
    '    index = min(len(joined) - 1, max(0, int(math.ceil(0.10 * len(joined))) - 1))\n',
    '    return float(joined[index])\n',
    '\n',
    '\n',
    'def lb_keogh(a: Sequence[float], b: Sequence[float], window: int) -> float:\n',
    '    aa = np.asarray(a, dtype=np.float32)\n',
    '    bb = np.asarray(b, dtype=np.float32)\n',
    '    if aa.size == 0 or bb.size == 0:\n',
    '        return float("inf")\n',
    '    radius = max(1, int(window))\n',
    '    total = 0.0\n',
    '    for i, value in enumerate(aa):\n',
    '        lo = max(0, i - radius)\n',
    '        hi = min(bb.size, i + radius + 1)\n',
    '        if lo >= hi:\n',
    '            continue\n',
    '        lower, upper = float(np.min(bb[lo:hi])), float(np.max(bb[lo:hi]))\n',
    '        if value > upper:\n',
    '            total += float((value - upper) ** 2)\n',
    '        elif value < lower:\n',
    '            total += float((value - lower) ** 2)\n',
    '    return math.sqrt(total / max(1, aa.size))\n',
    '\n',
    '\n',
    'def constrained_dtw_distance(\n',
    '    a: Sequence[float], b: Sequence[float], *, window: int | None = None, max_cost: float | None = None\n',
    ') -> float:\n',
    '    """Narrow Sakoe-Chiba DTW with row-level early abandoning."""\n',
    '    aa, bb = np.asarray(a, dtype=np.float32), np.asarray(b, dtype=np.float32)\n',
    '    n, m = int(aa.size), int(bb.size)\n',
    '    if n == 0 or m == 0:\n',
    '        return float("inf")\n',
    '    radius = max(abs(n - m), int(window if window is not None else math.ceil(max(n, m) * CONFIG.dtw_window_ratio)), 1)\n',
    '    previous = np.full(m + 1, np.inf, dtype=np.float64)\n',
    '    previous[0] = 0.0\n',
    '    abandon_total = None if max_cost is None else float(max_cost) ** 2 * max(n, m)\n',
    '    for i in range(1, n + 1):\n',
    '        current = np.full(m + 1, np.inf, dtype=np.float64)\n',
    '        start, stop = max(1, i - radius), min(m, i + radius)\n',
    '        row_min = np.inf\n',
    '        for j in range(start, stop + 1):\n',
    '            cost = float((aa[i - 1] - bb[j - 1]) ** 2)\n',
    '            current[j] = cost + min(current[j - 1], previous[j], previous[j - 1])\n',
    '            row_min = min(row_min, current[j])\n',
    '        if abandon_total is not None and row_min > abandon_total:\n',
    '            return float("inf")\n',
    '        previous = current\n',
    '    total = previous[m]\n',
    '    return math.sqrt(float(total) / max(n, m)) if math.isfinite(total) else float("inf")\n',
    '\n',
    '\n',
    'def _normalise_ohlc(frame: pd.DataFrame, latest_completed: Any = None) -> tuple[pd.DataFrame, dict[str, Any]]:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame(), {"status": "UNAVAILABLE", "warnings": ["No OHLC frame supplied"]}\n',
    '    source = frame\n',
    '    time_col = _find_column(source, _TIME_ALIASES)\n',
    '    if time_col is None and isinstance(source.index, pd.DatetimeIndex):\n',
    '        work = source.reset_index().rename(columns={source.index.name or "index": "time"})\n',
    '        time_col = "time"\n',
    '    elif time_col is not None:\n',
    '        selected = [time_col]\n',
    '        for aliases in _OHLC_ALIASES.values():\n',
    '            col = _find_column(source, aliases)\n',
    '            if col and col not in selected:\n',
    '                selected.append(col)\n',
    '        work = source.loc[:, selected].copy(deep=False)\n',
    '    else:\n',
    '        return pd.DataFrame(), {"status": "UNAVAILABLE", "warnings": ["A timestamp column is required"]}\n',
    '\n',
    '    rename: dict[str, str] = {time_col: "time"}\n',
    '    for canonical, aliases in _OHLC_ALIASES.items():\n',
    '        col = _find_column(work, aliases)\n',
    '        if col:\n',
    '            rename[col] = canonical\n',
    '    work = work.rename(columns=rename)\n',
    '    required = {"time", "open", "high", "low", "close"}\n',
    '    missing = sorted(required.difference(work.columns))\n',
    '    if missing:\n',
    '        return pd.DataFrame(), {"status": "UNAVAILABLE", "warnings": ["Missing OHLC columns: " + ", ".join(missing)]}\n',
    '\n',
    '    parsed = pd.to_datetime(work["time"], errors="coerce", utc=True)\n',
    '    invalid_times = int(parsed.isna().sum())\n',
    '    original_valid = parsed.dropna()\n',
    '    unsorted = bool(not original_valid.is_monotonic_increasing)\n',
    '    original_valid_frame = pd.DataFrame({"time": original_valid})\n',
    '    unsorted_dates = []\n',
    '    if not original_valid_frame.empty:\n',
    '        original_valid_frame["date"] = original_valid_frame["time"].dt.date\n',
    '        unsorted_dates = sorted(\n',
    '            d.isoformat() for d, group in original_valid_frame.groupby("date", sort=False)\n',
    '            if not group["time"].is_monotonic_increasing\n',
    '        )\n',
    '    duplicate_mask = original_valid.duplicated(keep=False)\n',
    '    duplicate_times = set(original_valid[duplicate_mask].astype("int64").tolist())\n',
    '    duplicate_dates = sorted({pd.Timestamp(v, tz="UTC").date().isoformat() for v in duplicate_times})\n',
    '    work = work.assign(time=parsed).dropna(subset=["time"])\n',
    '    for column in ("open", "high", "low", "close", "volume"):\n',
    '        if column in work.columns:\n',
    '            work[column] = pd.to_numeric(work[column], errors="coerce")\n',
    '    work = work.dropna(subset=["open", "high", "low", "close"])\n',
    '    future_rows_removed = 0\n',
    '    if latest_completed not in (None, ""):\n',
    '        boundary = pd.to_datetime(latest_completed, errors="coerce", utc=True)\n',
    '        if pd.notna(boundary):\n',
    '            future_rows_removed = int((work["time"] > boundary).sum())\n',
    '            work = work.loc[work["time"] <= boundary]\n',
    '    work = work.sort_values("time", kind="mergesort")\n',
    '    before = len(work)\n',
    '    work = work.drop_duplicates(subset=["time"], keep="last")\n',
    '    duplicates_removed = before - len(work)\n',
    '    work = work.reset_index(drop=True)\n',
    '    if "volume" not in work.columns:\n',
    '        work["volume"] = np.nan\n',
    '    for column in ("open", "high", "low", "close", "volume"):\n',
    '        work[column] = work[column].astype(np.float32, copy=False)\n',
    '    warnings: list[str] = []\n',
    '    if invalid_times:\n',
    '        warnings.append(f"{invalid_times} invalid timestamps removed")\n',
    '    if unsorted:\n',
    '        warnings.append("Input timestamps were unsorted and were normalized")\n',
    '    if duplicates_removed:\n',
    '        warnings.append(f"{duplicates_removed} duplicate timestamps removed")\n',
    '    if future_rows_removed:\n',
    '        warnings.append(f"{future_rows_removed} rows later than the canonical completed candle were excluded")\n',
    '    return work, {\n',
    '        "status": "GOOD" if not warnings else "CHECK",\n',
    '        "warnings": warnings,\n',
    '        "unsorted_input": unsorted,\n',
    '        "duplicates_removed": duplicates_removed,\n',
    '        "duplicate_dates": duplicate_dates,\n',
    '        "unsorted_dates": unsorted_dates,\n',
    '        "future_rows_removed": future_rows_removed,\n',
    '        "rows": int(len(work)),\n',
    '    }\n',
    '\n',
    '\n',
    'def _technical_frame(frame: pd.DataFrame) -> pd.DataFrame:\n',
    '    work = frame.loc[:, [c for c in ("time", "open", "high", "low", "close", "volume") if c in frame.columns]].copy(deep=False)\n',
    '    close = work["close"].astype(np.float64)\n',
    '    high = work["high"].astype(np.float64)\n',
    '    low = work["low"].astype(np.float64)\n',
    '    previous_close = close.shift(1)\n',
    '    true_range = pd.concat([(high - low).abs(), (high - previous_close).abs(), (low - previous_close).abs()], axis=1).max(axis=1)\n',
    '    atr = true_range.rolling(14, min_periods=2).mean()\n',
    '    up_move = high.diff()\n',
    '    down_move = -low.diff()\n',
    '    plus_dm = pd.Series(np.where((up_move > down_move) & (up_move > 0), up_move, 0.0), index=work.index)\n',
    '    minus_dm = pd.Series(np.where((down_move > up_move) & (down_move > 0), down_move, 0.0), index=work.index)\n',
    '    tr_sum = true_range.rolling(14, min_periods=2).sum().replace(0, np.nan)\n',
    '    plus_di = 100.0 * plus_dm.rolling(14, min_periods=2).sum() / tr_sum\n',
    '    minus_di = 100.0 * minus_dm.rolling(14, min_periods=2).sum() / tr_sum\n',
    '    dx = 100.0 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0, np.nan)\n',
    '    adx = dx.rolling(14, min_periods=2).mean()\n',
    '    candle_range = (high - low).replace(0, np.nan)\n',
    '    pressure = ((close - work["open"].astype(np.float64)) / candle_range).clip(-1, 1)\n',
    '    returns = np.log(close.replace(0, np.nan)).diff()\n',
    '    work = work.assign(\n',
    '        log_return=returns.astype(np.float32),\n',
    '        true_range=true_range.astype(np.float32),\n',
    '        atr=atr.astype(np.float32),\n',
    '        plus_di=plus_di.astype(np.float32),\n',
    '        minus_di=minus_di.astype(np.float32),\n',
    '        adx=adx.astype(np.float32),\n',
    '        pressure=pressure.astype(np.float32),\n',
    '    )\n',
    '    return work\n',
    '\n',
    '\n',
    'def _approx_entropy(values: np.ndarray, bins: int = 6) -> float:\n',
    '    arr = np.asarray(values, dtype=np.float64)\n',
    '    if arr.size < 3 or np.nanstd(arr) < 1e-12:\n',
    '        return 0.0\n',
    '    hist, _ = np.histogram(arr[np.isfinite(arr)], bins=bins)\n',
    '    probs = hist[hist > 0] / max(1, hist.sum())\n',
    '    return float(-(probs * np.log(probs)).sum() / math.log(max(2, bins)))\n',
    '\n',
    '\n',
    'def _autocorr_lag1(values: np.ndarray) -> float:\n',
    '    arr = np.asarray(values, dtype=np.float64)\n',
    '    if arr.size < 3 or np.nanstd(arr[:-1]) < 1e-12 or np.nanstd(arr[1:]) < 1e-12:\n',
    '        return 0.0\n',
    '    return float(np.corrcoef(arr[:-1], arr[1:])[0, 1])\n',
]
