"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '            st.session_state[NEWS_STATE] = []\n',
    '            st.session_state[NEWS_TIME_STATE] = 0.0\n',
    '            safe = _redact(result.get("message", "Connection failed"), clean)\n',
    '            st.session_state[ERROR_STATE] = safe\n',
    '            fail(st.session_state, CONNECTION_PREFIX, safe)\n',
    '        return result\n',
    '    except Exception as exc:\n',
    '        safe = _redact(exc, clean)\n',
    '        st.session_state[CONNECTED_STATE] = False\n',
    '        st.session_state[ERROR_STATE] = safe\n',
    '        fail(st.session_state, CONNECTION_PREFIX, safe)\n',
    '        return {"ok": False, "message": safe, "availability": "UNAVAILABLE"}\n',
    '\n',
    '\n',
    'def test_connection(candidate_key: str = "") -> Dict[str, Any]:\n',
    '    """One-click idempotent test; a valid candidate is saved and connected."""\n',
    '    initialize_finnhub_state()\n',
    '    from core.connector_state_machine_20260621 import begin, fail, succeed\n',
    '    if not begin(st.session_state, CONNECTION_PREFIX):\n',
    '        return {"ok": False, "duplicate_blocked": True, "message": "Finnhub connection is already in progress.", "availability": "CONNECTING"}\n',
    '    candidate = normalize_api_key(candidate_key)\n',
    '    key = candidate or get_session_key()\n',
    '    try:\n',
    '        if not key:\n',
    '            result = {"ok": False, "message": "Enter a Finnhub API key first.", "availability": "UNAVAILABLE"}\n',
    '        else:\n',
    '            result = validate_connection(key)\n',
    '        st.session_state[LAST_TEST_STATE] = _utc_now_text()\n',
    '        st.session_state[AVAILABILITY_STATE] = result.get("availability", "UNKNOWN")\n',
    '        if result.get("ok"):\n',
    '            _apply_success(key, result)\n',
    '            succeed(st.session_state, CONNECTION_PREFIX, str(result.get("message") or "Finnhub connected."))\n',
    '        else:\n',
    '            st.session_state[CONNECTED_STATE] = bool(get_session_key() and st.session_state.get(CONNECTED_STATE))\n',
    '            safe = _redact(result.get("message"), key)\n',
    '            st.session_state[ERROR_STATE] = safe\n',
    '            fail(st.session_state, CONNECTION_PREFIX, safe)\n',
    '        return result\n',
    '    except Exception as exc:\n',
    '        safe = _redact(exc, key)\n',
    '        st.session_state[ERROR_STATE] = safe\n',
    '        fail(st.session_state, CONNECTION_PREFIX, safe)\n',
    '        return {"ok": False, "message": safe, "availability": "UNAVAILABLE"}\n',
    '\n',
    '\n',
    'def disconnect() -> None:\n',
    '    initialize_finnhub_state()\n',
    '    for key in (KEY_STATE, CLIENT_STATE, VALIDATION_STATE):\n',
    '        st.session_state[key] = ""\n',
    '    st.session_state[CONNECTED_STATE] = False\n',
    '    st.session_state[AVAILABILITY_STATE] = "DISCONNECTED"\n',
    '    st.session_state[ERROR_STATE] = ""\n',
    '    st.session_state[NEWS_MODE_STATE] = "forex"\n',
    '    st.session_state[NEWS_STATE] = []\n',
    '    st.session_state[NEWS_TIME_STATE] = 0.0\n',
    '    st.session_state["finnhub_clear_widget_pending"] = True\n',
    '    try:\n',
    '        from core.connector_state_machine_20260621 import disconnect as mark_disconnected\n',
    '        mark_disconnected(st.session_state, CONNECTION_PREFIX, "Finnhub disconnected for this session.")\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '\n',
    'def _safe_news_rows(payload: Any, *, category: str) -> List[Dict[str, Any]]:\n',
    '    rows = payload if isinstance(payload, list) else []\n',
    '    safe_rows: List[Dict[str, Any]] = []\n',
    '    for row in rows[:250]:\n',
    '        if not isinstance(row, dict):\n',
    '            continue\n',
    '        safe_rows.append({\n',
    '            "id": row.get("id"),\n',
    '            "headline": str(row.get("headline") or ""),\n',
    '            "summary": str(row.get("summary") or ""),\n',
    '            "source": str(row.get("source") or "Finnhub"),\n',
    '            "url": str(row.get("url") or ""),\n',
    '            "datetime": row.get("datetime"),\n',
    '            "category": str(row.get("category") or category),\n',
    '            "related": str(row.get("related") or ""),\n',
    '            "image": str(row.get("image") or ""),\n',
    '        })\n',
    '    return safe_rows\n',
    '\n',
    '\n',
    'def fetch_market_news(category: str = "forex", *, force: bool = False, ttl_seconds: int = 900) -> List[Dict[str, Any]]:\n',
    '    """Fetch and merge existing Finnhub categories into a retained 25-day cache.\n',
    '\n',
    '    Refreshes never replace a larger valid cache with one article.  The existing\n',
    '    forex/general endpoints are merged, deduplicated and newest-sorted.\n',
    '    """\n',
    '    initialize_finnhub_state()\n',
    '    key = get_session_key()\n',
    '    if not key or not st.session_state.get(CONNECTED_STATE):\n',
    '        cached = st.session_state.get(NEWS_STATE, [])\n',
    '        return cached if isinstance(cached, list) else []\n',
    '    cached = st.session_state.get(NEWS_STATE, [])\n',
    '    cached = cached if isinstance(cached, list) else []\n',
    '    age = time.time() - float(st.session_state.get(NEWS_TIME_STATE, 0.0) or 0.0)\n',
    '    if not force and cached and age < max(60, int(ttl_seconds)):\n',
    '        return cached\n',
    '\n',
    '    requested = str(category or "forex").strip().lower() or "forex"\n',
    '    preferred = str(st.session_state.get(NEWS_MODE_STATE, "forex") or "forex")\n',
    '    categories: List[str] = []\n',
    '    for item in (requested if preferred == "forex" else preferred, "forex", "general"):\n',
    '        if item and item not in categories:\n',
    '            categories.append(item)\n',
    '\n',
    '    fresh: List[Dict[str, Any]] = []\n',
    '    last_error: Optional[Exception] = None\n',
    '    successful_category = ""\n',
    '    for current_category in categories:\n',
    '        try:\n',
    '            payload = _request_json("news", key, {"category": current_category, "minId": 0})\n',
    '            rows = _safe_news_rows(payload, category=current_category)\n',
    '            fresh.extend(rows)\n',
    '            successful_category = successful_category or current_category\n',
    '        except FinnhubRequestError as exc:\n',
    '            last_error = exc\n',
    '            if exc.auth_invalid:\n',
    '                st.session_state[CONNECTED_STATE] = False\n',
    '                st.session_state[AVAILABILITY_STATE] = "UNAVAILABLE"\n',
    '                break\n',
    '            if exc.rate_limited:\n',
    '                st.session_state[AVAILABILITY_STATE] = "RATE_LIMITED"\n',
    '                break\n',
    '            continue\n',
    '        except Exception as exc:\n',
    '            last_error = exc\n',
    '            continue\n',
    '\n',
    '    combined = fresh + cached\n',
    '    cutoff = int(time.time()) - 25 * 86400\n',
    '    seen: set[str] = set()\n',
    '    merged: List[Dict[str, Any]] = []\n',
    '    for row in sorted(combined, key=lambda r: int(r.get("datetime") or 0), reverse=True):\n',
    '        if not isinstance(row, dict):\n',
    '            continue\n',
    '        timestamp = int(row.get("datetime") or 0)\n',
    '        if timestamp and timestamp < cutoff:\n',
    '            continue\n',
    '        fingerprint = str(row.get("id") or row.get("url") or (str(row.get("headline") or "").strip().lower() + "|" + str(row.get("source") or "").strip().lower()))\n',
    '        if not fingerprint or fingerprint in seen:\n',
    '            continue\n',
    '        seen.add(fingerprint); merged.append(row)\n',
    '        if len(merged) >= 250:\n',
    '            break\n',
    '    if merged:\n',
    '        st.session_state[NEWS_STATE] = merged\n',
    '        st.session_state[NEWS_TIME_STATE] = time.time()\n',
    '        st.session_state[NEWS_MODE_STATE] = successful_category or requested\n',
    '        st.session_state[ERROR_STATE] = ""\n',
    '        st.session_state[AVAILABILITY_STATE] = "AVAILABLE"\n',
    '        return merged\n',
    '    st.session_state[ERROR_STATE] = _redact(last_error or "Finnhub news request returned no articles", key)\n',
    '    return cached\n',
    '\n',
    '\n',
    'def _safe_rerun() -> None:\n',
    '    if "research_inner_tab" in st.session_state:\n',
    '        st.session_state["research_inner_tab"] = st.session_state.get("research_inner_tab", "Data Analysis")\n',
    '    try:\n',
    '        st.rerun()\n',
    '    except Exception:\n',
    '        try:\n',
    '            st.experimental_rerun()\n',
    '        except Exception:\n',
    '            pass\n',
    '\n',
    '\n',
    'def _connect_button_callback(widget_key: str) -> None:\n',
    '    candidate = normalize_api_key(st.session_state.get(widget_key, ""))\n',
    '    connect(candidate or get_session_key())\n',
    '\n',
    '\n',
    'def _test_button_callback(widget_key: str) -> None:\n',
    '    test_connection(normalize_api_key(st.session_state.get(widget_key, "")))\n',
    '\n',
    '\n',
    'def _disconnect_button_callback(generation: int) -> None:\n',
    '    disconnect()\n',
    '    st.session_state["finnhub_widget_generation"] = int(generation) + 1\n',
    '\n',
    '\n',
    'def render_finnhub_connector(*, location: str = "sidebar") -> None:\n',
    '    """Render secure status plus an optional temporary replacement field."""\n',
    '    initialize_finnhub_state()\n',
    '    if st.session_state.pop("finnhub_clear_widget_pending", False):\n',
    '        for k in list(st.session_state.keys()):\n',
    '            if str(k).startswith("finnhub_key_input_"):\n',
    '                st.session_state.pop(k, None)\n',
    '    status = connection_status()\n',
    '    generation = int(st.session_state.get("finnhub_widget_generation", 0) or 0)\n',
    '    widget_key = f"finnhub_key_input_{location}_{generation}"\n',
    '    stored_key = get_session_key()\n',
    '    try:\n',
    '        from core.secure_api_startup_20260619 import secure_secret_status\n',
    '        secret_state = secure_secret_status(st.session_state)\n',
    '    except Exception:\n',
    '        secret_state = {"finnhub_configured": bool(stored_key), "finnhub_source": "Temporary session replacement" if stored_key else "Not configured"}\n',
    '\n',
    '    st.markdown("#### Finnhub API Connector")\n',
    '    if secret_state.get("finnhub_configured"):\n',
    '        st.success(f"Finnhub API: ✅ Configured securely ({secret_state.get(\'finnhub_source\', \'server-side\')})")\n',
    '    else:\n',
    '        st.info("Finnhub API: not configured. Add it to Streamlit Secrets or use a temporary replacement below.")\n',
    '    st.caption("The actual key is never placed into a widget value, export, log, URL, copy payload, or browser storage.")\n',
    '\n',
    '    replace_key = st.toggle(\n',
    '        "Use temporary replacement Finnhub key",\n',
    '        value=(str(location).lower() == "settings"),\n',
    '        key=f"finnhub_replace_toggle_{location}",\n',
    '        help="Use only to replace/test the server-side key for this session. The stored secret remains hidden.",\n',
    '    )\n',
    '    candidate = ""\n',
    '    if replace_key:\n',
    '        if str(location).lower() == "settings":\n',
    '            candidate = st.text_area(\n',
    '                "Finnhub API key — mobile paste box",\n',
    '                key=widget_key,\n',
    '                height=74,\n',
    '                placeholder="Long press here, paste a temporary replacement token, then press Connect",\n',
    '                help="This field is intentionally blank and never autofills a stored secret.",\n',
    '            )\n',
    '        else:\n',
    '            candidate = st.text_input(\n',
    '                "Finnhub API key", type="password", key=widget_key,\n',
    '                placeholder="Paste a temporary replacement token",\n',
    '            )\n',
    '    typed_key = normalize_api_key(candidate)\n',
    '    effective_key = typed_key or stored_key\n',
    '    connector_state = str(status.get("state") or "DISCONNECTED")\n',
    '    c1, c2 = st.columns(2)\n',
    '    c1.button(\n',
    '        "Save + Validate + Connect (One Click)" if replace_key else "Validate + Connect (One Click)",\n',
    '        key=f"finnhub_connect_{location}", use_container_width=True,\n',
    '        disabled=not bool(effective_key) or connector_state == "CONNECTING",\n',
    '        on_click=_connect_button_callback, args=(widget_key,),\n',
    '    )\n',
    '    c2.button(\n',
    '        "Disconnect session", key=f"finnhub_disconnect_{location}", use_container_width=True,\n',
    '        disabled=connector_state == "CONNECTING" or not bool(status.get("connected") or st.session_state.get(KEY_STATE)),\n',
    '        on_click=_disconnect_button_callback, args=(generation,),\n',
    '    )\n',
    '\n',
    '    status = connection_status()\n',
    '    m1, m2 = st.columns(2)\n',
    '    m1.metric("Connection", str(status.get("state") or ("CONNECTED" if status["connected"] else "DISCONNECTED")))\n',
    '    m2.metric("API", status.get("availability", "UNKNOWN"))\n',
    '    endpoint = str(status.get("validation_endpoint") or "")\n',
    '    if endpoint:\n',
    '        st.caption(f"Validated with: {endpoint.replace(\'_\', \' \').title()} · News mode: {status.get(\'news_mode\', \'forex\').title()}")\n',
    '    st.caption(f"Last successful connection: {status.get(\'last_success\', \'Never\')}")\n',
    '    st.caption(f"Last test attempt: {status.get(\'last_test\', \'Never\')}")\n',
    '    if status.get("error"):\n',
    '        st.warning(_redact(status["error"], effective_key))\n',
    '        availability = str(status.get("availability") or "")\n',
    '        if availability == "RATE_LIMITED":\n',
    '            st.caption("Wait about one minute, then press Connect once. The key is not automatically treated as invalid.")\n',
    '        elif availability == "PLAN_RESTRICTED":\n',
    '            st.caption("The key was not marked invalid. Check the Finnhub account plan or use cached/local NLP.")\n',
    '        else:\n',
    '            st.caption("Copy only the token value from the Finnhub dashboard, without quotes or a label, then press Connect once.")\n',
    '\n',
    'def render_finnhub_status_compact(*, location: str = "sidebar") -> None:\n',
    '    """Display connection status only; API-key entry remains in Settings."""\n',
    '    del location\n',
    '    initialize_finnhub_state()\n',
    '    status = connection_status()\n',
    '    c1, c2 = st.columns(2)\n',
    '    c1.metric("Finnhub", "CONNECTED" if status.get("connected") else "DISCONNECTED")\n',
    '    c2.metric("API", status.get("availability", "UNKNOWN"))\n',
    '    st.caption("Configure or change the Finnhub API key in Settings. This compact panel never renders a key input.")\n',
    '    st.caption(f"Last successful connection: {status.get(\'last_success\', \'Never\')}")\n',
    '    if status.get("error"):\n',
    '        st.warning(_redact(str(status.get("error")), get_session_key()))\n',
]
