"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        peak = max(peak, positive / sigma, abs(negative) / sigma)\n',
    '    return _clip(0.55 * (mean_shift / 3.0) + 0.45 * (peak / 6.0))\n',
    '\n',
    '\n',
    'def build_transition_risk(frame: pd.DataFrame) -> dict[str, Any]:\n',
    '    if frame.empty or len(frame) < 36:\n',
    '        return {"value": 0.5, "status": "WATCH", "fallback": "INSUFFICIENT SAMPLE", "version": SUPPORT_VERSION}\n',
    '    numeric_sources = {\n',
    '        "master": frame["master"], "entry": frame["entry"], "alpha": frame["alpha"], "delta": frame["delta"],\n',
    '        "alpha_delta_state": frame["alpha"] * frame["delta"], "pressure_balance": frame["pressure_balance"],\n',
    '        "reliability": frame["reliability"], "periodicity_normalized_return": frame["return_1h"],\n',
    '        "periodicity_normalized_range": frame.get("periodicity_normalized_range", pd.Series(0.0, index=frame.index)),\n',
    '        "periodicity_normalized_residual": frame.get("periodicity_normalized_residual", pd.Series(0.0, index=frame.index)),\n',
    '    }\n',
    '    structural_components = {name: _structural_strength(series) for name, series in numeric_sources.items()}\n',
    '    structural_break = float(np.mean(sorted(structural_components.values(), reverse=True)[:4]))\n',
    '\n',
    '    categorical = {\n',
    '        "direction_changes": frame["direction"], "regime_transitions": frame["regime"],\n',
    '        "alpha_sign": np.sign(frame["alpha"]), "delta_sign": np.sign(frame["delta"]),\n',
    '        "alpha_delta_disagreement": np.sign(frame["alpha"] * frame["delta"]),\n',
    '        "pressure_instability": pd.cut(frame["pressure_balance"], [-np.inf, -1, 1, np.inf], labels=["SELL", "BALANCED", "BUY"]),\n',
    '        "reliability_instability": pd.cut(frame["reliability"], [-np.inf, 45, 65, np.inf], labels=["LOW", "MID", "HIGH"]),\n',
    '    }\n',
    '    entropy_components: dict[str, float] = {}\n',
    '    for name, values in categorical.items():\n',
    '        series = pd.Series(values).reset_index(drop=True)\n',
    '        recent = series.tail(24)\n',
    '        baseline = series.iloc[:-24].tail(120)\n',
    '        recent_entropy = _entropy(recent)\n',
    '        baseline_entropy = _entropy(baseline)\n',
    '        max_entropy = math.log2(max(2, int(series.nunique(dropna=True))))\n',
    '        increase = max(0.0, recent_entropy - baseline_entropy)\n',
    '        entropy_components[name] = _clip(increase / max(max_entropy, 1e-12))\n',
    '    entropy_increase = float(np.mean(sorted(entropy_components.values(), reverse=True)[:4]))\n',
    '\n',
    '    recent_regime = frame["regime"].tail(24).astype(str)\n',
    '    base_regime = frame["regime"].iloc[:-24].tail(120).astype(str)\n',
    '    recent_transitions = float(recent_regime.ne(recent_regime.shift()).mean())\n',
    '    base_transitions = float(base_regime.ne(base_regime.shift()).mean()) if len(base_regime) else recent_transitions\n',
    '    current_run = 1\n',
    '    for value in reversed(frame["regime"].astype(str).tolist()[:-1]):\n',
    '        if value == str(frame["regime"].iloc[-1]):\n',
    '            current_run += 1\n',
    '        else:\n',
    '            break\n',
    '    lifecycle = _clip(0.65 * max(0.0, recent_transitions - base_transitions) * 4.0 + 0.35 * (1.0 / max(1.0, current_run / 12.0)))\n',
    '    value = _clip(0.50 * structural_break + 0.30 * entropy_increase + 0.20 * lifecycle)\n',
    '    status = "STABLE" if value < 0.40 else "WATCH" if value < 0.60 else "PROTECT" if value < 0.75 else "WAIT"\n',
    '    return {\n',
    '        "version": SUPPORT_VERSION, "value": round(value, 4), "status": status,\n',
    '        "structural_break_strength": round(structural_break, 4), "entropy_increase": round(entropy_increase, 4),\n',
    '        "regime_lifecycle_risk": round(lifecycle, 4), "current_regime_run_hours": int(current_run),\n',
    '        "structural_components": {k: round(v, 4) for k, v in structural_components.items()},\n',
    '        "entropy_components": {k: round(v, 4) for k, v in entropy_components.items()},\n',
    '        "formula": "50% structural break + 30% entropy increase + 20% regime lifecycle risk",\n',
    '    }\n',
    '\n',
    '\n',
    'def _atr(frame: pd.DataFrame, window: int = 14) -> pd.Series:\n',
    '    previous = frame["close"].shift(1)\n',
    '    tr = pd.concat([\n',
    '        (frame["high"] - frame["low"]).abs(), (frame["high"] - previous).abs(), (frame["low"] - previous).abs(),\n',
    '    ], axis=1).max(axis=1)\n',
    '    rolling = tr.rolling(window, min_periods=3).median()\n',
    '    causal_fallback = tr.expanding(min_periods=1).median()\n',
    '    return rolling.fillna(causal_fallback).ffill().fillna(0.0)\n',
    '\n',
    '\n',
    'def _triple_barrier_row(data: pd.DataFrame, index: int, horizon: int) -> Optional[dict[str, Any]]:\n',
    '    end = index + int(horizon)\n',
    '    if index < 0 or end >= len(data):\n',
    '        return None\n',
    '    row = data.iloc[index]\n',
    '    direction = str(row.get("direction", "WAIT"))\n',
    '    decision = str(row.get("decision_label", "NO TRADE")).upper()\n',
    '    if direction not in {"BUY", "SELL"} or decision not in _ALLOWED_DECISIONS:\n',
    '        return None\n',
    '    entry = float(row["close"])\n',
    '    atr_value = max(float(row.get("atr", 0.0) or 0.0), abs(entry) * 0.00025)\n',
    '    tp_score = _clip(float(row.get("tp", 0.0) or 0.0) / 10.0)\n',
    '    exit_risk = _clip(float(row.get("exit_risk", 10.0) or 10.0) / 10.0)\n',
    '    favourable_distance = atr_value * (0.80 + 0.80 * tp_score)\n',
    '    adverse_distance = atr_value * (0.65 + 0.70 * exit_risk)\n',
    '    future = data.iloc[index + 1:end + 1]\n',
    '    favourable_hit = adverse_hit = None\n',
    '    for offset, candle in enumerate(future.itertuples(index=False), start=1):\n',
    '        high = float(getattr(candle, "high")); low = float(getattr(candle, "low"))\n',
    '        if direction == "BUY":\n',
    '            fav = high >= entry + favourable_distance\n',
    '            adv = low <= entry - adverse_distance\n',
    '        else:\n',
    '            fav = low <= entry - favourable_distance\n',
    '            adv = high >= entry + adverse_distance\n',
    '        if favourable_hit is None and fav:\n',
    '            favourable_hit = offset\n',
    '        if adverse_hit is None and adv:\n',
    '            adverse_hit = offset\n',
    '    outcome = _movement_outcome(data, index, horizon, direction) or {"signed_move": 0.0, "favourable": 0.0, "adverse": 0.0}\n',
    '    if favourable_hit is not None and (adverse_hit is None or favourable_hit < adverse_hit):\n',
    '        barrier = "FAVOURABLE"; actionable = 1\n',
    '    elif adverse_hit is not None and (favourable_hit is None or adverse_hit <= favourable_hit):\n',
    '        barrier = "ADVERSE"; actionable = 0\n',
    '    else:\n',
    '        barrier = "TIME_POSITIVE" if outcome["signed_move"] > 0 else "TIME_NON_POSITIVE"\n',
    '        actionable = int(outcome["signed_move"] > 0)\n',
    '    return {\n',
    '        "time": row["time"], "direction": direction, "regime": str(row.get("regime", "UNKNOWN")),\n',
    '        "session": str(row.get("session", "UNKNOWN")), "horizon": int(horizon), "barrier": barrier,\n',
    '        "actionable": actionable, "signed_move": float(outcome["signed_move"]),\n',
    '        "maximum_favourable_excursion": float(outcome["favourable"]),\n',
    '        "maximum_adverse_excursion": float(outcome["adverse"]),\n',
    '        "net_excursion": float(outcome["favourable"] - outcome["adverse"]),\n',
    '        "favourable_barrier": favourable_distance / max(entry, 1e-12),\n',
    '        "adverse_barrier": adverse_distance / max(entry, 1e-12),\n',
    '        "settled_at": data.iloc[end]["time"],\n',
    '    }\n',
    '\n',
    '\n',
    'def _summarize_actionability(data: pd.DataFrame, history: pd.DataFrame) -> dict[str, Any]:\n',
    '    if data.empty:\n',
    '        return {"current_label": "WAIT", "status": "INSUFFICIENT EVIDENCE", "history": []}\n',
    '    current = data.iloc[-1]\n',
    '    direction = str(current.get("direction", "WAIT"))\n',
    '    current_group = history[\n',
    '        (history.get("direction", pd.Series(dtype=str)) == direction)\n',
    '        & (history.get("regime", pd.Series(dtype=str)).astype(str) == str(current.get("regime", "UNKNOWN")))\n',
    '    ] if not history.empty else pd.DataFrame()\n',
    '    scope = "REGIME_DIRECTION"\n',
    '    if len(current_group) < 12 and not history.empty:\n',
    '        current_group = history[history["direction"] == direction]\n',
    '        scope = "DIRECTION"\n',
    '    if len(current_group) < 12:\n',
    '        current_group = history\n',
    '        scope = "EURUSD_H1_GLOBAL"\n',
    '    primary_group = current_group[pd.to_numeric(current_group.get("horizon"), errors="coerce").isin([2, 3])] if not current_group.empty else current_group\n',
    '    if primary_group.empty:\n',
    '        primary_group = current_group\n',
    '    sample_count = int(pd.to_datetime(primary_group.get("time"), utc=True, errors="coerce").nunique()) if not primary_group.empty else 0\n',
    '    actionable_rate = float(primary_group["actionable"].mean()) if sample_count else 0.0\n',
    '    expected_value = float(primary_group["net_excursion"].median()) if sample_count else None\n',
    '    if direction not in {"BUY", "SELL"}:\n',
    '        label = "WAIT"\n',
    '    elif sample_count < 12:\n',
    '        label = "WATCH"\n',
    '    elif actionable_rate >= 0.62 and (expected_value or 0.0) > 0:\n',
    '        label = "QUALIFIED ENTRY"\n',
    '    elif actionable_rate >= 0.52 and (expected_value or 0.0) >= 0:\n',
    '        label = "CONDITIONAL ENTRY"\n',
    '    elif actionable_rate < 0.40:\n',
    '        label = "PROTECT"\n',
    '    else:\n',
    '        label = "WATCH"\n',
    '    ordered = history.sort_values(["time", "horizon"], ascending=[False, True], kind="stable") if not history.empty else history\n',
    '    return {\n',
    '        "version": SUPPORT_VERSION, "current_label": label, "status": "VALID" if sample_count >= 12 else "INSUFFICIENT EVIDENCE",\n',
    '        "sample_count": sample_count, "scope": scope, "actionable_probability": round(actionable_rate, 4),\n',
    '        "expected_value": None if expected_value is None else round(expected_value, 8),\n',
    '        "primary_time_barriers": [2, 3], "evaluation_horizons": [1, 2, 3, 6],\n',
    '        "history": _records(ordered, 2400),\n',
    '    }\n',
    '\n',
    '\n',
    'def build_triple_barrier_actionability(frame: pd.DataFrame) -> dict[str, Any]:\n',
    '    if frame.empty:\n',
    '        return {"current_label": "WAIT", "status": "INSUFFICIENT EVIDENCE", "history": []}\n',
    '    data = frame.copy()\n',
    '    data["atr"] = _atr(data)\n',
    '    rows = [\n',
    '        item\n',
    '        for index in range(len(data))\n',
    '        for horizon in HORIZONS\n',
    '        for item in [_triple_barrier_row(data, index, horizon)]\n',
    '        if item is not None\n',
    '    ]\n',
    '    return _summarize_actionability(data, pd.DataFrame(rows))\n',
    '\n',
    '\n',
    'def _incremental_triple_barrier_actionability(\n',
    '    frame: pd.DataFrame, previous: Mapping[str, Any], previous_latest: pd.Timestamp\n',
    ') -> dict[str, Any]:\n',
    '    data = frame.copy()\n',
    '    data["atr"] = _atr(data)\n',
    '    history = pd.DataFrame(list(previous.get("history") or []))\n',
    '    if not history.empty:\n',
    '        history["time"] = pd.to_datetime(history["time"], utc=True, errors="coerce")\n',
    '        history["settled_at"] = pd.to_datetime(history["settled_at"], utc=True, errors="coerce")\n',
    '        history = history.dropna(subset=["time", "settled_at"])\n',
    '    new_rows: list[dict[str, Any]] = []\n',
    '    for end_index, settled_time in enumerate(pd.to_datetime(data["time"], utc=True, errors="coerce")):\n',
    '        if pd.isna(settled_time) or settled_time <= previous_latest:\n',
    '            continue\n',
    '        for horizon in HORIZONS:\n',
    '            item = _triple_barrier_row(data, end_index - horizon, horizon)\n',
    '            if item is not None:\n',
    '                new_rows.append(item)\n',
    '    if new_rows:\n',
    '        history = pd.concat([history, pd.DataFrame(new_rows)], ignore_index=True)\n',
    '    if not history.empty:\n',
    '        earliest = pd.to_datetime(data["time"].iloc[0], utc=True, errors="coerce")\n',
    '        latest = pd.to_datetime(data["time"].iloc[-1], utc=True, errors="coerce")\n',
    '        history["time"] = pd.to_datetime(history["time"], utc=True, errors="coerce")\n',
    '        history["settled_at"] = pd.to_datetime(history["settled_at"], utc=True, errors="coerce")\n',
    '        history = history[history["time"].ge(earliest) & history["settled_at"].le(latest)]\n',
    '        history = history.drop_duplicates(["time", "horizon"], keep="last")\n',
    '    result = _summarize_actionability(data, history)\n',
    '    result["incremental_settlements_added"] = int(len(new_rows))\n',
    '    return result\n',
    '\n',
    'def _fracdiff_weights(d: float, threshold: float = 1e-4, max_size: int = 200) -> np.ndarray:\n',
    '    weights = [1.0]\n',
    '    for k in range(1, max_size):\n',
    '        value = -weights[-1] * (d - k + 1) / k\n',
    '        if abs(value) < threshold:\n',
    '            break\n',
    '        weights.append(value)\n',
    '    return np.asarray(weights[::-1], dtype=float)\n',
    '\n',
    '\n',
    'def _fractional_difference(series: pd.Series, d: float) -> pd.Series:\n',
    '    values = pd.to_numeric(series, errors="coerce")\n',
    '    weights = _fracdiff_weights(d)\n',
    '    width = len(weights)\n',
    '    result = pd.Series(np.nan, index=values.index, dtype=float)\n',
    '    array = values.to_numpy(dtype=float)\n',
    '    for index in range(width - 1, len(array)):\n',
    '        window = array[index - width + 1:index + 1]\n',
    '        if np.isfinite(window).all():\n',
    '            result.iloc[index] = float(np.dot(weights, window))\n',
    '    return result\n',
    '\n',
    '\n',
    'def _adf_pvalue(series: pd.Series) -> Optional[float]:\n',
    '    values = pd.to_numeric(series, errors="coerce").dropna()\n',
    '    if len(values) < 40:\n',
    '        return None\n',
    '    try:\n',
    '        from statsmodels.tsa.stattools import adfuller\n',
    '        return float(adfuller(values.to_numpy(dtype=float), maxlag=1, regression="c", autolag=None)[1])\n',
    '    except Exception:\n',
    '        # Deterministic proxy when statsmodels is unavailable: high lag-1\n',
    '        # autocorrelation is treated as non-stationary.\n',
    '        correlation = values.autocorr(lag=1)\n',
    '        if pd.isna(correlation):\n',
    '            return None\n',
    '        return float(max(0.0, min(1.0, (abs(float(correlation)) - 0.65) / 0.35)))\n',
    '\n',
    '\n',
    'def build_fractional_support(frame: pd.DataFrame) -> dict[str, Any]:\n',
    '    if frame.empty or len(frame) < 80:\n',
    '        return {"enabled": False, "weight": 0.0, "reason": "INSUFFICIENT SAMPLE", "version": SUPPORT_VERSION}\n',
    '    log_close = np.log(pd.to_numeric(frame["close"], errors="coerce").replace(0, np.nan))\n',
    '    split = max(50, int(len(log_close) * 0.8))\n',
    '    candidates = []\n',
    '    for d in (0.2, 0.4, 0.6, 0.8, 1.0):\n',
    '        transformed = _fractional_difference(log_close, d)\n',
    '        train = transformed.iloc[:split]\n',
    '        test = transformed.iloc[split:]\n',
    '        aligned = pd.concat([log_close, transformed], axis=1).dropna()\n',
    '        memory = float(aligned.iloc[:, 0].corr(aligned.iloc[:, 1])) if len(aligned) >= 20 else 0.0\n',
    '        pvalue = _adf_pvalue(train)\n',
    '        train_std = float(train.dropna().std(ddof=0)) if train.notna().sum() >= 10 else np.nan\n',
    '        test_std = float(test.dropna().std(ddof=0)) if test.notna().sum() >= 5 else np.nan\n',
    '        stability = 1.0 - min(1.0, abs(test_std - train_std) / max(abs(train_std), 1e-12)) if math.isfinite(train_std) and math.isfinite(test_std) else 0.0\n',
    '        valid = pvalue is not None and pvalue <= 0.10 and memory >= 0.55 and stability >= 0.35\n',
    '        score = (1.0 - min(1.0, pvalue or 1.0)) * 0.45 + max(0.0, memory) * 0.35 + stability * 0.20\n',
    '        candidates.append({"d": d, "adf_pvalue": pvalue, "memory_correlation": memory, "oos_stability": stability, "valid": valid, "score": score})\n',
    '    valid = [item for item in candidates if item["valid"]]\n',
    '    selected = sorted(valid, key=lambda item: (item["d"], -item["score"]))[0] if valid else None\n',
    '    return {\n',
    '        "version": SUPPORT_VERSION, "enabled": bool(selected), "weight": 0.15 if selected else 0.0,\n',
    '        "selected_d": selected["d"] if selected else None,\n',
    '        "reason": "OOS_VALIDATED_SUPPORT" if selected else "VALIDATION_FAILED_WEIGHT_ZERO",\n',
    '        "candidates": [\n',
    '            {k: (round(v, 6) if isinstance(v, float) else v) for k, v in item.items()}\n',
    '            for item in candidates\n',
    '        ],\n',
    '    }\n',
    '\n',
    '\n',
    'def build_duplicate_evidence_control(frame: pd.DataFrame) -> dict[str, Any]:\n',
    '    if frame.empty:\n',
    '        return {"status": "INSUFFICIENT SAMPLE", "duplicate_penalty": 0.0, "families": {}}\n',
    '    family_columns = {\n',
    '        "regime_alpha_delta": ["alpha", "delta"],\n',
    '        "price_pressure": ["return_1h", "pressure_balance"],\n',
    '        "reliability_protection": ["reliability", "exit_risk"],\n',
    '        "full_metric_scores": ["master", "entry", "hold", "tp"],\n',
    '    }\n',
    '    families: dict[str, Any] = {}\n',
    '    duplicate_pairs = 0\n',
    '    total_pairs = 0\n',
    '    for family, columns in family_columns.items():\n',
    '        available = [column for column in columns if column in frame]\n',
    '        correlations = frame[available].apply(pd.to_numeric, errors="coerce").corr().abs() if len(available) >= 2 else pd.DataFrame()\n',
    '        pairs = []\n',
    '        for i, left in enumerate(available):\n',
    '            for right in available[i + 1:]:\n',
    '                value = _finite(correlations.loc[left, right], 0.0) if not correlations.empty else 0.0\n',
    '                total_pairs += 1\n',
    '                duplicate = bool(value is not None and value >= 0.85)\n',
    '                duplicate_pairs += int(duplicate)\n',
    '                pairs.append({"left": left, "right": right, "abs_correlation": round(float(value or 0.0), 4), "duplicate": duplicate})\n',
    '        stability_values = []\n',
    '        for column in available:\n',
    '            series = pd.to_numeric(frame[column], errors="coerce").dropna()\n',
    '            if len(series) >= 30:\n',
    '                midpoint = len(series) // 2\n',
    '                left_std = float(series.iloc[:midpoint].std(ddof=0)); right_std = float(series.iloc[midpoint:].std(ddof=0))\n',
    '                stability_values.append(1.0 - min(1.0, abs(right_std - left_std) / max(abs(left_std), 1e-12)))\n',
    '        stability = float(np.mean(stability_values)) if stability_values else 0.5\n',
    '        cap = {"regime_alpha_delta": 0.22, "price_pressure": 0.18, "reliability_protection": 0.25, "full_metric_scores": 0.0}.get(family, 0.15)\n',
    '        # Full Metric authority is reported but remains outside the supporting\n',
    '        # evidence competition and therefore has a zero supporting cap.\n',
    '        families[family] = {"cap": cap, "stability": round(stability, 4), "correlated_pairs": pairs}\n',
    '    penalty = duplicate_pairs / max(1, total_pairs)\n',
    '    return {\n',
    '        "version": SUPPORT_VERSION, "status": "ACTIVE", "duplicate_penalty": round(penalty, 4),\n',
    '        "duplicate_pairs": int(duplicate_pairs), "evaluated_pairs": int(total_pairs), "families": families,\n',
    '        "full_metric_authority_excluded_from_competition": True,\n',
    '    }\n',
    '\n',
    '\n',
    'def _distribution_stats(values: pd.Series) -> dict[str, Any]:\n',
    '    series = pd.to_numeric(values, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()\n',
    '    if series.empty:\n',
    '        return {"sample_count": 0}\n',
    '    return {\n',
    '        "sample_count": int(len(series)), "mean": float(series.mean()), "median": float(series.median()),\n',
    '        "standard_deviation": float(series.std(ddof=0)), "p10": float(series.quantile(0.10)),\n',
    '        "p25": float(series.quantile(0.25)), "p75": float(series.quantile(0.75)), "p90": float(series.quantile(0.90)),\n',
    '        "skewness": float(series.skew()) if len(series) >= 3 else 0.0,\n',
    '        "tail_loss_frequency": float((series < series.quantile(0.10)).mean()),\n',
    '    }\n',
    '\n',
    '\n',
    'def build_regime_conditioned_distributions(frame: pd.DataFrame, actionability: Mapping[str, Any], transition: Mapping[str, Any]) -> dict[str, Any]:\n',
    '    history = pd.DataFrame(list(actionability.get("history") or []))\n',
    '    if history.empty:\n',
    '        return {"status": "INSUFFICIENT SAMPLE", "horizons": {}, "version": SUPPORT_VERSION}\n',
    '    current = frame.iloc[-1]\n',
    '    direction = str(current.get("direction", "WAIT")); regime = str(current.get("regime", "UNKNOWN")); session = str(current.get("session", "UNKNOWN"))\n',
    '    transition_state = str(transition.get("status", "WATCH"))\n',
    '    results: dict[str, Any] = {}\n',
    '    for horizon in HORIZONS:\n',
    '        base = history[pd.to_numeric(history.get("horizon"), errors="coerce") == horizon]\n',
    '        scopes = [\n',
    '            (base[(base["direction"] == direction) & (base["regime"] == regime) & (base["session"] == session)], "REGIME_SESSION_DIRECTION"),\n',
    '            (base[(base["direction"] == direction) & (base["regime"] == regime)], "REGIME_DIRECTION"),\n',
    '            (base[(base["direction"] == direction) & (base["session"] == session)], "SESSION_DIRECTION"),\n',
    '            (base[base["direction"] == direction], "DIRECTION"), (base, "EURUSD_H1_GLOBAL"),\n',
    '        ]\n',
    '        selected = pd.DataFrame(); scope = "NONE"\n',
    '        for candidate, label in scopes:\n',
    '            if len(candidate) >= 12:\n',
    '                selected = candidate; scope = label; break\n',
    '        if selected.empty:\n',
    '            selected = base; scope = "SMALL_SAMPLE_GLOBAL"\n',
    '        stats = _distribution_stats(selected.get("signed_move", pd.Series(dtype=float)))\n',
    '        stats.update({\n',
    '            "scope": scope, "transition_state": transition_state,\n',
    '            "maximum_favourable_excursion": _finite(pd.to_numeric(selected.get("maximum_favourable_excursion"), errors="coerce").max(), None),\n',
    '            "maximum_adverse_excursion": _finite(pd.to_numeric(selected.get("maximum_adverse_excursion"), errors="coerce").max(), None),\n',
    '            "median_favourable_excursion": _finite(pd.to_numeric(selected.get("maximum_favourable_excursion"), errors="coerce").median(), None),\n',
    '            "median_adverse_excursion": _finite(pd.to_numeric(selected.get("maximum_adverse_excursion"), errors="coerce").median(), None),\n',
    '            "shrinkage_applied": scope not in {"REGIME_SESSION_DIRECTION", "REGIME_DIRECTION"},\n',
    '        })\n',
    '        results[f"{horizon}h"] = {key: (round(value, 8) if isinstance(value, float) else value) for key, value in stats.items()}\n',
    '    overall_status = "VALID" if str(actionability.get("status", "")).upper() == "VALID" else "INSUFFICIENT SAMPLE"\n',
    '    return {"version": SUPPORT_VERSION, "status": overall_status, "horizons": results}\n',
    '\n',
    '\n',
    'def _source_signature(frame: pd.DataFrame) -> str:\n',
    '    if frame.empty:\n',
    '        return "empty"\n',
    '    columns = [column for column in (\n',
    '        "time", "open", "high", "low", "close", "direction", "decision_label",\n',
    '        "master", "entry", "hold", "tp", "exit_risk", "buy_pressure", "sell_pressure",\n',
    '    ) if column in frame.columns]\n',
    '    payload = frame.tail(8)[columns].to_json(date_format="iso", orient="records", double_precision=12)\n',
    '    return sha256(payload.encode("utf-8", errors="ignore")).hexdigest()[:24]\n',
    '\n',
    '\n',
    'def _restore_evidence_frame(records: Any) -> pd.DataFrame:\n',
    '    frame = pd.DataFrame(list(records or []))\n',
    '    if frame.empty:\n',
    '        return frame\n',
    '    frame["time"] = pd.to_datetime(frame.get("time"), utc=True, errors="coerce")\n',
    '    numeric = (\n',
    '        "open", "high", "low", "close", "volume", "master", "entry", "hold", "tp", "exit_risk",\n',
    '        "buy_pressure", "sell_pressure", "reliability", "alpha", "delta", "expected_value_existing",\n',
    '        "pressure_balance", "return_1h",\n',
    '    )\n',
    '    for column in numeric:\n',
    '        if column in frame.columns:\n',
    '            frame[column] = pd.to_numeric(frame[column], errors="coerce")\n',
    '    return frame.dropna(subset=["time"]).sort_values("time", kind="stable").drop_duplicates("time", keep="last").tail(600).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _cache_records(frame: pd.DataFrame) -> list[dict[str, Any]]:\n',
    '    if frame.empty:\n',
    '        return []\n',
    '    return [\n',
    '        {str(key): _json_value(value) for key, value in row.items()}\n',
    '        for row in frame.tail(600).to_dict("records")\n',
    '    ]\n',
    '\n',
    '\n',
    'def _sequence_key(sequence: Sequence[str]) -> str:\n',
    '    return sha256("\x1f".join(sequence).encode("utf-8", errors="ignore")).hexdigest()[:20]\n',
    '\n',
    '\n',
    'def _fresh_incremental_state(frame: pd.DataFrame) -> dict[str, Any]:\n',
    '    numeric_columns = ("close", "return_1h", "master", "entry", "alpha", "delta", "pressure_balance", "reliability")\n',
    '    moments: dict[str, Any] = {}\n',
    '    for column in numeric_columns:\n',
    '        values = pd.to_numeric(frame.get(column), errors="coerce").dropna()\n',
    '        count = int(len(values)); total = float(values.sum()) if count else 0.0; sum_sq = float(np.square(values).sum()) if count else 0.0\n',
    '        mean = total / count if count else None\n',
    '        variance = max(0.0, sum_sq / count - mean * mean) if count and mean is not None else None\n',
]
