"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Causal supporting evidence for the protected EURUSD H1 Full Metric authority.\n',
    '\n',
    'The functions in this module never calculate an independent market direction.\n',
    'They consume the protected Full Metric history and completed H1 OHLC rows, then\n',
    'return confirmation/protection evidence that can only confirm or force WAIT.\n',
    'The implementation is intentionally deterministic, bounded to the latest 600\n',
    'completed H1 rows, and independent of Streamlit so it can be tested directly.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from collections import Counter\n',
    'from dataclasses import dataclass\n',
    'from hashlib import sha256\n',
    'import math\n',
    'from typing import Any, Dict, Iterable, Mapping, Optional, Sequence, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'SUPPORT_VERSION = "causal-quant-support-20260618-v1"\n',
    'WINDOWS = {"lower_1d": 24, "medium_5d": 120, "higher_25d": 600}\n',
    'HORIZONS = (1, 2, 3, 6)\n',
    '_ALLOWED_DECISIONS = {"STRONG", "ALLOWED"}\n',
    '\n',
    '\n',
    'def _finite(value: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    try:\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(value: Any, low: float = 0.0, high: float = 1.0, default: float = 0.0) -> float:\n',
    '    number = _finite(value, default)\n',
    '    return max(low, min(high, float(default if number is None else number)))\n',
    '\n',
    '\n',
    'def _direction(value: Any) -> str:\n',
    '    text = str(value or "").upper()\n',
    '    if "BUY" in text or "BULL" in text or text == "UP":\n',
    '        return "BUY"\n',
    '    if "SELL" in text or "BEAR" in text or text == "DOWN":\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _json_value(value: Any) -> Any:\n',
    '    if value is pd.NA or value is pd.NaT:\n',
    '        return None\n',
    '    if isinstance(value, pd.Timestamp):\n',
    '        if pd.isna(value):\n',
    '            return None\n',
    '        ts = value.tz_localize("UTC") if value.tzinfo is None else value.tz_convert("UTC")\n',
    '        return ts.isoformat()\n',
    '    if isinstance(value, np.integer):\n',
    '        return int(value)\n',
    '    if isinstance(value, np.floating):\n',
    '        return float(value) if np.isfinite(value) else None\n',
    '    if isinstance(value, np.bool_):\n',
    '        return bool(value)\n',
    '    try:\n',
    '        if pd.isna(value):\n',
    '            return None\n',
    '    except Exception:\n',
    '        pass\n',
    '    return value\n',
    '\n',
    '\n',
    'def _records(frame: pd.DataFrame, limit: int = 600) -> list[dict[str, Any]]:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return []\n',
    '    return [\n',
    '        {str(key): _json_value(value) for key, value in row.items()}\n',
    '        for row in frame.head(limit).to_dict("records")\n',
    '    ]\n',
    '\n',
    '\n',
    'def _find_column(frame: pd.DataFrame, aliases: Sequence[str]) -> Optional[str]:\n',
    '    cmap = {str(column).strip().lower(): column for column in frame.columns}\n',
    '    for alias in aliases:\n',
    '        key = alias.strip().lower()\n',
    '        if key in cmap:\n',
    '            return cmap[key]\n',
    '    for alias in aliases:\n',
    '        key = alias.strip().lower()\n',
    '        for lower, original in cmap.items():\n',
    '            if key in lower:\n',
    '                return original\n',
    '    return None\n',
    '\n',
    '\n',
    'def _normalize_ohlc(frame: Any) -> pd.DataFrame:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close", "volume"])\n',
    '    raw = frame.copy(deep=False)\n',
    '    tcol = _find_column(raw, ("time", "timestamp", "datetime", "date"))\n',
    '    if tcol is None:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close", "volume"])\n',
    '    out = pd.DataFrame({"time": pd.to_datetime(raw[tcol], utc=True, errors="coerce")})\n',
    '    for name, aliases in {\n',
    '        "open": ("open", "o"), "high": ("high", "h"),\n',
    '        "low": ("low", "l"), "close": ("close", "c"),\n',
    '        "volume": ("volume", "tick_volume", "vol"),\n',
    '        "expected_hourly_volatility": ("expected_hourly_volatility",),\n',
    '        "periodicity_normalized_return": ("periodicity_normalized_return",),\n',
    '        "periodicity_normalized_range": ("periodicity_normalized_range",),\n',
    '        "periodicity_normalized_residual": ("periodicity_normalized_residual",),\n',
    '        "periodicity_reliability": ("periodicity_reliability",),\n',
    '    }.items():\n',
    '        col = _find_column(raw, aliases)\n',
    '        out[name] = pd.to_numeric(raw[col], errors="coerce") if col is not None else np.nan\n',
    '    out = out.dropna(subset=["time", "open", "high", "low", "close"])\n',
    '    out = out.sort_values("time", kind="stable").drop_duplicates("time", keep="last")\n',
    '    out = out.tail(600).reset_index(drop=True)\n',
    '    return out\n',
    '\n',
    '\n',
    'def _metric_frame(priority_table: Any) -> pd.DataFrame:\n',
    '    if not isinstance(priority_table, pd.DataFrame) or priority_table.empty:\n',
    '        return pd.DataFrame()\n',
    '    raw = priority_table.copy(deep=False)\n',
    '    tcol = _find_column(raw, ("time", "candle time", "latest_completed_candle_time", "datetime", "timestamp"))\n',
    '    if tcol is None:\n',
    '        return pd.DataFrame()\n',
    '    raw["time"] = pd.to_datetime(raw[tcol], utc=True, errors="coerce")\n',
    '    raw = raw.dropna(subset=["time"]).sort_values("time", kind="stable").drop_duplicates("time", keep="last")\n',
    '    return raw.tail(600).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _score_series(frame: pd.DataFrame, aliases: Sequence[str], default: float = np.nan) -> pd.Series:\n',
    '    col = _find_column(frame, aliases)\n',
    '    if col is None:\n',
    '        return pd.Series(default, index=frame.index, dtype=float)\n',
    '    return pd.to_numeric(frame[col], errors="coerce")\n',
    '\n',
    '\n',
    'def _text_series(frame: pd.DataFrame, aliases: Sequence[str], default: str = "") -> pd.Series:\n',
    '    col = _find_column(frame, aliases)\n',
    '    if col is None:\n',
    '        return pd.Series(default, index=frame.index, dtype=object)\n',
    '    return frame[col].astype(str)\n',
    '\n',
    '\n',
    'def _prepare_evidence_frame(ohlc: Any, priority_table: Any, context: Optional[Mapping[str, Any]] = None) -> pd.DataFrame:\n',
    '    market = _normalize_ohlc(ohlc)\n',
    '    metric = _metric_frame(priority_table)\n',
    '    if market.empty or metric.empty:\n',
    '        return pd.DataFrame()\n',
    '    merged = pd.merge_asof(\n',
    '        market.sort_values("time"), metric.sort_values("time"), on="time",\n',
    '        direction="backward", tolerance=pd.Timedelta(minutes=5), suffixes=("", "__metric"),\n',
    '    )\n',
    '    merged = merged.dropna(subset=["time", "close"]).reset_index(drop=True)\n',
    '    merged["direction"] = _text_series(merged, ("Direction", "prediction direction", "Less Risky Bias"), "WAIT").map(_direction)\n',
    '    merged["decision_label"] = _text_series(merged, ("Full Metric Decision", "Decision", "Qualification Status"), "NO TRADE").str.upper()\n',
    '    merged["regime"] = _text_series(merged, ("Regime", "Current Regime", "Major Regime", "current_major_regime"), "UNKNOWN")\n',
    '    merged["master"] = _score_series(merged, ("Master /10", "Master Score", "master_score"), 0.0).fillna(0.0)\n',
    '    merged["entry"] = _score_series(merged, ("Entry /10", "Entry Score", "entry_score"), 0.0).fillna(0.0)\n',
    '    merged["hold"] = _score_series(merged, ("Hold /10", "Hold Safety", "hold_score"), 0.0).fillna(0.0)\n',
    '    merged["tp"] = _score_series(merged, ("TP /10", "TP Score", "tp_score"), 0.0).fillna(0.0)\n',
    '    merged["exit_risk"] = _score_series(merged, ("Exit Risk /10", "Exit Risk", "exit_risk"), 10.0).fillna(10.0)\n',
    '    merged["buy_pressure"] = _score_series(merged, ("BUY /10", "BUY Score", "buy_score", "buy pressure"), 0.0).fillna(0.0)\n',
    '    merged["sell_pressure"] = _score_series(merged, ("SELL /10", "SELL Score", "sell_score", "sell pressure"), 0.0).fillna(0.0)\n',
    '    merged["reliability"] = _score_series(merged, ("Reliability %", "Reliability", "prediction_reliability"), 50.0).fillna(50.0)\n',
    '    merged["conflict"] = _text_series(merged, ("Conflict Status", "conflict status", "NLP Confirmation"), "NONE").str.upper()\n',
    '    merged["alpha"] = _score_series(merged, ("Alpha", "alpha", "Regime Alpha"), np.nan)\n',
    '    merged["delta"] = _score_series(merged, ("Delta", "delta", "Regime Delta"), np.nan)\n',
    '    merged["expected_value_existing"] = _score_series(merged, ("Expected Value", "expected_value", "EV"), np.nan)\n',
    '\n',
    '    ctx = dict(context or {})\n',
    '    regime_ctx = dict(ctx.get("regime") or {}) if isinstance(ctx.get("regime"), Mapping) else {}\n',
    '    current_regime = regime_ctx.get("major_regime") or regime_ctx.get("current") or ctx.get("current_regime")\n',
    '    if current_regime:\n',
    '        merged.loc[merged.index[-1], "regime"] = str(current_regime)\n',
    '    for key in ("alpha", "delta"):\n',
    '        value = _finite(regime_ctx.get(key), _finite(ctx.get(key), None))\n',
    '        if value is not None:\n',
    '            merged.loc[merged.index[-1], key] = value\n',
    '    merged["alpha"] = merged["alpha"].ffill().fillna(0.0)\n',
    '    merged["delta"] = merged["delta"].ffill().fillna(0.0)\n',
    '    merged["pressure_balance"] = merged["buy_pressure"] - merged["sell_pressure"]\n',
    '    merged["raw_return_1h"] = merged["close"].pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    periodic_return = pd.to_numeric(merged.get("periodicity_normalized_return"), errors="coerce")\n',
    '    merged["return_1h"] = periodic_return.where(periodic_return.notna(), merged["raw_return_1h"]).fillna(0.0)\n',
    '    merged["periodicity_normalized_range"] = pd.to_numeric(merged.get("periodicity_normalized_range"), errors="coerce").fillna(0.0)\n',
    '    merged["periodicity_normalized_residual"] = pd.to_numeric(merged.get("periodicity_normalized_residual"), errors="coerce").fillna(0.0)\n',
    '    merged["session"] = merged["time"].dt.hour.map(\n',
    '        lambda hour: "ASIA" if hour < 7 else "LONDON" if hour < 12 else "LONDON_NY_OVERLAP" if hour < 16 else "NEW_YORK" if hour < 21 else "LATE"\n',
    '    )\n',
    '    return merged.tail(600).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _bucket(value: float, low: float = 4.5, high: float = 6.5) -> str:\n',
    '    if value < low:\n',
    '        return "LOW"\n',
    '    if value < high:\n',
    '        return "MEDIUM"\n',
    '    return "HIGH"\n',
    '\n',
    '\n',
    'def _signed_bucket(value: float, weak: float = 0.05, strong: float = 0.25) -> str:\n',
    '    if value >= strong:\n',
    '        return "POS_STRONG"\n',
    '    if value > weak:\n',
    '        return "POS_WEAK"\n',
    '    if value <= -strong:\n',
    '        return "NEG_STRONG"\n',
    '    if value < -weak:\n',
    '        return "NEG_WEAK"\n',
    '    return "FLAT"\n',
    '\n',
    '\n',
    'def _state_tokens(frame: pd.DataFrame) -> pd.Series:\n',
    '    tokens = []\n',
    '    for _, row in frame.iterrows():\n',
    '        alpha = float(row.get("alpha", 0.0) or 0.0)\n',
    '        delta = float(row.get("delta", 0.0) or 0.0)\n',
    '        relationship = "ALIGNED" if alpha * delta > 0 else "DIVERGENT" if alpha * delta < 0 else "NEUTRAL"\n',
    '        pressure = float(row.get("pressure_balance", 0.0) or 0.0)\n',
    '        pressure_label = "BUY_HIGH" if pressure >= 2 else "SELL_HIGH" if pressure <= -2 else "BALANCED"\n',
    '        conflict = "CONFLICT" if any(x in str(row.get("conflict", "")).upper() for x in ("CONFLICT", "CRITICAL", "SEVERE")) else "CLEAR"\n',
    '        tokens.append("|".join([\n',
    '            str(row.get("regime", "UNKNOWN")).upper(), str(row.get("direction", "WAIT")),\n',
    '            f"MASTER_{_bucket(float(row.get(\'master\', 0) or 0))}", f"ENTRY_{_bucket(float(row.get(\'entry\', 0) or 0))}",\n',
    '            f"HOLD_{_bucket(float(row.get(\'hold\', 0) or 0))}", f"ALPHA_{_signed_bucket(alpha)}",\n',
    '            f"DELTA_{_signed_bucket(delta)}", f"AD_{relationship}", pressure_label,\n',
    '            f"EXIT_{_bucket(10-float(row.get(\'exit_risk\', 10) or 10))}",\n',
    '            f"REL_{_bucket(float(row.get(\'reliability\', 50) or 50)/10)}", conflict,\n',
    '            str(row.get("session", "UNKNOWN")),\n',
    '        ]))\n',
    '    return pd.Series(tokens, index=frame.index, dtype=object)\n',
    '\n',
    '\n',
    'def _token_similarity(a: Sequence[str], b: Sequence[str]) -> float:\n',
    '    if len(a) != len(b) or not a:\n',
    '        return 0.0\n',
    '    scores = []\n',
    '    for left, right in zip(a, b):\n',
    '        lp = left.split("|")\n',
    '        rp = right.split("|")\n',
    '        size = max(len(lp), len(rp), 1)\n',
    '        scores.append(sum(x == y for x, y in zip(lp, rp)) / size)\n',
    '    return float(np.mean(scores))\n',
    '\n',
    '\n',
    'def _movement_outcome(frame: pd.DataFrame, index: int, horizon: int, direction: str) -> Optional[dict[str, float]]:\n',
    '    end = index + int(horizon)\n',
    '    if direction not in {"BUY", "SELL"} or index < 0 or end >= len(frame):\n',
    '        return None\n',
    '    entry = float(frame.loc[index, "close"])\n',
    '    future = frame.iloc[index + 1:end + 1]\n',
    '    if future.empty or not math.isfinite(entry) or entry == 0:\n',
    '        return None\n',
    '    final = float(future["close"].iloc[-1])\n',
    '    if direction == "BUY":\n',
    '        signed_move = (final - entry) / entry\n',
    '        favourable = (float(future["high"].max()) - entry) / entry\n',
    '        adverse = (entry - float(future["low"].min())) / entry\n',
    '    else:\n',
    '        signed_move = (entry - final) / entry\n',
    '        favourable = (entry - float(future["low"].min())) / entry\n',
    '        adverse = (float(future["high"].max()) - entry) / entry\n',
    '    return {\n',
    '        "signed_move": float(signed_move), "success": float(signed_move > 0),\n',
    '        "favourable": max(0.0, float(favourable)), "adverse": max(0.0, float(adverse)),\n',
    '    }\n',
    '\n',
    '\n',
    'def _pattern_window(frame: pd.DataFrame, window_rows: int, sequence_length: int = 3) -> dict[str, Any]:\n',
    '    if len(frame) < sequence_length + 8:\n',
    '        return {"status": "INSUFFICIENT EVIDENCE", "sample_count": 0, "pattern_confirmation": "NEUTRAL", "confidence": 0.0}\n',
    '    data = frame.tail(window_rows).reset_index(drop=True)\n',
    '    tokens = _state_tokens(data)\n',
    '    current_seq = tokens.tail(sequence_length).tolist()\n',
    '    current_direction = str(data.iloc[-1]["direction"])\n',
    '    current_end = len(data) - 1\n',
    '    candidates: list[tuple[int, float]] = []\n',
    "    # Past-only: the candidate's 6H outcome must be fully settled before the\n",
    '    # current sequence begins.\n',
    '    latest_candidate_end = current_end - sequence_length - max(HORIZONS)\n',
    '    for end in range(sequence_length - 1, latest_candidate_end + 1):\n',
    '        candidate_seq = tokens.iloc[end - sequence_length + 1:end + 1].tolist()\n',
    '        similarity = _token_similarity(current_seq, candidate_seq)\n',
    '        if similarity >= 0.78:\n',
    '            candidates.append((end, similarity))\n',
    '    outcomes: dict[int, list[dict[str, float]]] = {h: [] for h in HORIZONS}\n',
    '    recencies: list[float] = []\n',
    '    similarities: list[float] = []\n',
    '    for end, similarity in candidates:\n',
    '        direction = str(data.loc[end, "direction"])\n',
    '        if direction != current_direction or direction not in {"BUY", "SELL"}:\n',
    '            continue\n',
    '        age = max(1, current_end - end)\n',
    '        recencies.append(math.exp(-age / max(24.0, window_rows / 2.0)))\n',
    '        similarities.append(similarity)\n',
    '        for horizon in HORIZONS:\n',
    '            item = _movement_outcome(data, end, horizon, direction)\n',
    '            if item is not None:\n',
    '                outcomes[horizon].append(item)\n',
    '    sample_count = min((len(items) for items in outcomes.values()), default=0)\n',
    '    if sample_count < 5:\n',
    '        return {\n',
    '            "status": "INSUFFICIENT EVIDENCE", "sample_count": int(sample_count),\n',
    '            "pattern_support": round(sample_count / max(1, len(data)), 6),\n',
    '            "current_pattern_similarity": round(float(np.mean(similarities)) if similarities else 0.0, 4),\n',
    '            "pattern_confirmation": "NEUTRAL", "confidence": 0.0,\n',
    '            "minimum_sample_required": 5, "sequence_length": sequence_length,\n',
    '        }\n',
    '    success = {h: float(np.mean([x["success"] for x in outcomes[h]])) for h in HORIZONS}\n',
    '    favourable_values = [x["favourable"] for h in HORIZONS for x in outcomes[h]]\n',
    '    adverse_values = [x["adverse"] for h in HORIZONS for x in outcomes[h]]\n',
    '    outcome_consistency = float(np.mean(list(success.values())))\n',
    '    sample_strength = min(1.0, sample_count / max(12.0, window_rows * 0.08))\n',
    '    recency_quality = float(np.mean(recencies)) if recencies else 0.0\n',
    '    median_favourable = float(np.median(favourable_values)) if favourable_values else 0.0\n',
    '    median_adverse = float(np.median(adverse_values)) if adverse_values else 0.0\n',
    '    movement_quality = median_favourable / max(median_favourable + median_adverse, 1e-12)\n',
    '    confidence = 0.35 * outcome_consistency + 0.25 * sample_strength + 0.20 * recency_quality + 0.20 * movement_quality\n',
    '    if confidence >= 0.67 and outcome_consistency >= 0.58:\n',
    '        confirmation = "CONFIRM"\n',
    '    elif confidence >= 0.52 and outcome_consistency >= 0.52:\n',
    '        confirmation = "WEAK CONFIRM"\n',
    '    elif outcome_consistency < 0.35 and sample_strength >= 0.8:\n',
    '        confirmation = "WAIT"\n',
    '    elif outcome_consistency < 0.42 and sample_strength >= 0.6:\n',
    '        confirmation = "PROTECT"\n',
    '    else:\n',
    '        confirmation = "NEUTRAL"\n',
    '    return {\n',
    '        "status": "VALID", "sample_count": int(sample_count),\n',
    '        "pattern_support": round(sample_count / max(1, len(data)), 6),\n',
    '        "pattern_recency": round(recency_quality, 4),\n',
    '        "1h_directional_success": round(success[1], 4),\n',
    '        "2h_directional_success": round(success[2], 4),\n',
    '        "3h_directional_success": round(success[3], 4),\n',
    '        "6h_directional_success": round(success[6], 4),\n',
    '        "median_favourable_movement": round(median_favourable, 8),\n',
    '        "median_adverse_movement": round(median_adverse, 8),\n',
    '        "maximum_favourable_excursion": round(max(favourable_values, default=0.0), 8),\n',
    '        "maximum_adverse_excursion": round(max(adverse_values, default=0.0), 8),\n',
    '        "outcome_consistency": round(outcome_consistency, 4),\n',
    '        "current_pattern_similarity": round(float(np.mean(similarities)) if similarities else 0.0, 4),\n',
    '        "sample_strength": round(sample_strength, 4), "movement_quality": round(movement_quality, 4),\n',
    '        "confidence": round(confidence, 4), "pattern_confirmation": confirmation,\n',
    '        "sequence_length": sequence_length, "minimum_sample_required": 5,\n',
    '        "future_rows_used_for_current_input": 0,\n',
    '    }\n',
    '\n',
    '\n',
    'def build_pattern_memory(frame: pd.DataFrame) -> dict[str, Any]:\n',
    '    results = {name: _pattern_window(frame, rows) for name, rows in WINDOWS.items()}\n',
    '    valid = [item for item in results.values() if item.get("status") == "VALID"]\n',
    '    if not valid:\n',
    '        overall = "NEUTRAL"\n',
    '        confidence = 0.0\n',
    '    else:\n',
    '        weights = np.array([0.20, 0.30, 0.50][-len(valid):], dtype=float)\n',
    '        weights = weights / weights.sum()\n',
    '        confidence = float(np.sum([float(item.get("confidence", 0.0)) * weight for item, weight in zip(valid, weights)]))\n',
    '        statuses = [str(item.get("pattern_confirmation", "NEUTRAL")) for item in valid]\n',
    '        if "WAIT" in statuses:\n',
    '            overall = "WAIT"\n',
    '        elif "PROTECT" in statuses:\n',
    '            overall = "PROTECT"\n',
    '        elif statuses.count("CONFIRM") >= 2 or ("CONFIRM" in statuses and confidence >= 0.65):\n',
    '            overall = "CONFIRM"\n',
    '        elif any(status in {"CONFIRM", "WEAK CONFIRM"} for status in statuses):\n',
    '            overall = "WEAK CONFIRM"\n',
    '        else:\n',
    '            overall = "NEUTRAL"\n',
    '    reference = valid[-1] if valid else results.get("higher_25d", {})\n',
    '    return {\n',
    '        "version": SUPPORT_VERSION, "windows": results,\n',
    '        "pattern_confirmation": overall, "pattern_confidence": round(confidence, 4),\n',
    '        "sample_count": int(reference.get("sample_count", 0) or 0),\n',
    '        "pattern_support": reference.get("pattern_support", 0.0),\n',
    '        "pattern_recency": reference.get("pattern_recency", 0.0),\n',
    '        "1h_directional_success": reference.get("1h_directional_success"),\n',
    '        "2h_directional_success": reference.get("2h_directional_success"),\n',
    '        "3h_directional_success": reference.get("3h_directional_success"),\n',
    '        "6h_directional_success": reference.get("6h_directional_success"),\n',
    '        "median_favourable_movement": reference.get("median_favourable_movement"),\n',
    '        "median_adverse_movement": reference.get("median_adverse_movement"),\n',
    '        "maximum_favourable_excursion": reference.get("maximum_favourable_excursion"),\n',
    '        "maximum_adverse_excursion": reference.get("maximum_adverse_excursion"),\n',
    '        "outcome_consistency": reference.get("outcome_consistency"),\n',
    '        "current_pattern_similarity": reference.get("current_pattern_similarity", 0.0),\n',
    '        "future_rows_used_for_current_input": 0,\n',
    '        "causal_policy": "past-only occurrences whose outcomes settled before current sequence",\n',
    '    }\n',
    '\n',
    '\n',
    'def _entropy(values: Iterable[Any]) -> float:\n',
    '    series = pd.Series(list(values)).dropna().astype(str)\n',
    '    if series.empty:\n',
    '        return 0.0\n',
    '    probabilities = series.value_counts(normalize=True).to_numpy(dtype=float)\n',
    '    return float(-(probabilities * np.log2(np.maximum(probabilities, 1e-12))).sum())\n',
    '\n',
    '\n',
    'def _structural_strength(series: pd.Series) -> float:\n',
    '    values = pd.to_numeric(series, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()\n',
    '    if len(values) < 36:\n',
    '        return 0.0\n',
    '    recent_n = min(12, max(6, len(values) // 8))\n',
    '    recent = values.tail(recent_n)\n',
    '    baseline = values.iloc[:-recent_n].tail(120)\n',
    '    if len(baseline) < 24:\n',
    '        return 0.0\n',
    '    sigma = float(baseline.std(ddof=0))\n',
    '    if sigma <= 1e-12:\n',
    '        return 0.0\n',
    '    mean_shift = abs(float(recent.mean() - baseline.mean())) / sigma\n',
    '    centered = recent.to_numpy(dtype=float) - float(baseline.mean())\n',
    '    threshold = max(0.5 * sigma, 1e-12)\n',
    '    positive = negative = peak = 0.0\n',
    '    for value in centered:\n',
    '        positive = max(0.0, positive + value - threshold)\n',
    '        negative = min(0.0, negative + value + threshold)\n',
]
