"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '                continue\n',
    '            direction = _direction(row.get("full_metric_direction"))\n',
    '            actual_direction = "BUY" if actual > origin_price else "SELL" if actual < origin_price else "WAIT"\n',
    '            correct = int(direction == actual_direction)\n',
    '            abs_pips = abs(actual - predicted) / pip\n',
    '            segment = frame.loc[(frame.index > origin_ts) & (frame.index <= actual_time)]\n',
    '            if segment.empty:\n',
    '                segment = eligible.head(1)\n',
    '            high = float(segment["high"].max())\n',
    '            low = float(segment["low"].min())\n',
    '            if direction == "BUY":\n',
    '                mfe = max(0.0, (high - origin_price) / pip)\n',
    '                mae = max(0.0, (origin_price - low) / pip)\n',
    '            elif direction == "SELL":\n',
    '                mfe = max(0.0, (origin_price - low) / pip)\n',
    '                mae = max(0.0, (high - origin_price) / pip)\n',
    '            else:\n',
    '                mfe = 0.0\n',
    '                mae = max(abs(high - origin_price), abs(origin_price - low)) / pip\n',
    '            lower = _finite(row.get("lower_band"), None)\n',
    '            upper = _finite(row.get("upper_band"), None)\n',
    '            interval_hit = int(lower is not None and upper is not None and lower <= actual <= upper)\n',
    '            tp = _finite(row.get("selected_tp"), None)\n',
    '            sl = _finite(row.get("selected_sl"), None)\n',
    '            tp_hit = int(tp is not None and ((direction == "BUY" and high >= tp) or (direction == "SELL" and low <= tp)))\n',
    '            sl_hit = int(sl is not None and ((direction == "BUY" and low <= sl) or (direction == "SELL" and high >= sl)))\n',
    '            self._execute(\n',
    '                """\n',
    '                UPDATE settled_forecast_ledger_v3 SET actual_close=?,absolute_error_pips=?,squared_error=?,direction_correct=?,\n',
    '                    interval_hit=?,maximum_favorable_excursion=?,maximum_adverse_excursion=?,tp_touched=?,sl_touched=?,\n',
    "                    record_status='SETTLED',settlement_timestamp=?\n",
    "                WHERE calculation_id=? AND horizon=? AND record_status='PENDING'\n",
    '                """,\n',
    '                (actual, abs_pips, abs_pips ** 2, correct, interval_hit, mfe, mae, tp_hit, sl_hit, _utc_now(), row.get("calculation_id"), int(row.get("horizon") or 1)),\n',
    '            )\n',
    '            self._execute(\n',
    '                """\n',
    '                UPDATE forecast_method_ledger_v3 SET actual_close=?,absolute_error=ABS(predicted_close-?),\n',
    '                    squared_error=(predicted_close-?)*(predicted_close-?),\n',
    "                    directional_loss=CASE WHEN predicted_direction=(CASE WHEN ?>? THEN 'BUY' WHEN ?<? THEN 'SELL' ELSE 'WAIT' END) THEN 0 ELSE 1 END,\n",
    "                    record_status='SETTLED',settlement_timestamp=?\n",
    "                WHERE calculation_id=? AND horizon=? AND record_status='PENDING'\n",
    '                """,\n',
    '                (actual, actual, actual, actual, actual, origin_price, actual, origin_price, _utc_now(), row.get("calculation_id"), int(row.get("horizon") or 1)),\n',
    '            )\n',
    '            settled += 1\n',
    '        return {"ok": True, "settled": settled, "invalid": invalid, "pending": max(0, len(rows) - settled - invalid), "latest_completed": latest.isoformat()}\n',
    '\n',
    '    def _method_forecasts(self, canonical: Mapping[str, Any], ohlc: pd.DataFrame, horizon: int, point: Optional[float], origin: float) -> dict[str, Optional[float]]:\n',
    '        frame = normalize_completed_ohlc(ohlc)\n',
    '        close = frame["close"] if not frame.empty else pd.Series(dtype=float)\n',
    '        returns = close.diff()\n',
    '        recent_drift = float(returns.tail(12).median()) if len(returns.dropna()) else 0.0\n',
    '        ewma_drift = float(returns.ewm(span=12, adjust=False).mean().iloc[-1]) if len(returns.dropna()) else 0.0\n',
    '        session_drift = recent_drift\n',
    '        if not frame.empty:\n',
    '            sessions = pd.Series([_session(ts) for ts in frame.index], index=frame.index)\n',
    '            current_session = _session(frame.index[-1])\n',
    '            session_moves = close.diff().loc[sessions.eq(current_session)].dropna().tail(80)\n',
    '            if len(session_moves):\n',
    '                session_drift = float(session_moves.median())\n',
    '        full_metric_row = _mapping(canonical.get("full_metric_current_row"))\n',
    '        fm_point = _finite(\n',
    '            full_metric_row.get(f"H+{horizon} Predicted Close")\n',
    '            or full_metric_row.get("Predicted Close")\n',
    '            or full_metric_row.get("Prediction"),\n',
    '            None,\n',
    '        )\n',
    '        return {\n',
    '            "FULL_METRIC_FORECAST": fm_point,\n',
    '            "POWERBI_COMBINED_PATH": point,\n',
    '            "LAST_CLOSE": origin,\n',
    '            "RECENT_DRIFT": origin + recent_drift * horizon,\n',
    '            "SESSION_BASELINE": origin + session_drift * horizon,\n',
    '            "LIGHTWEIGHT_CHALLENGER": origin + ewma_drift * horizon,\n',
    '        }\n',
    '\n',
    '    def record_forecasts(self, canonical: Mapping[str, Any], ohlc: pd.DataFrame) -> Dict[str, Any]:\n',
    '        calc_id = _text(canonical.get("canonical_calculation_id") or canonical.get("run_id"))\n',
    '        if not calc_id:\n',
    '            return {"ok": False, "inserted": 0, "message": "Missing calculation ID"}\n',
    '        created = _utc(canonical.get("created_at")) or pd.Timestamp.now(tz="UTC")\n',
    '        origin_time = _utc(canonical.get("latest_completed_candle_time")) or created.floor("h")\n',
    '        market = _mapping(canonical.get("market"))\n',
    '        origin_price = _finite(canonical.get("last_close") or market.get("current_price"), None)\n',
    '        if origin_price is None:\n',
    '            return {"ok": False, "inserted": 0, "message": "Missing forecast origin price"}\n',
    '        final = _mapping(canonical.get("final_decision"))\n',
    '        regime = _mapping(canonical.get("regime"))\n',
    '        data_quality = _mapping(canonical.get("data_quality"))\n',
    '        drift = _mapping(canonical.get("drift"))\n',
    '        nlp = _mapping(canonical.get("nlp"))\n',
    '        priority = _mapping(canonical.get("priority"))\n',
    '        authority_direction = _direction(final.get("directional_market_view") or canonical.get("full_metric_direction"))\n',
    '        calculation_version = _text(canonical.get("calculation_version"), "unknown")\n',
    '        h1_regime = _text(regime.get("major_regime") or canonical.get("current_major_regime"), "UNKNOWN")\n',
    '        h4_regime = _text(regime.get("middle_standard_regime"), h1_regime)\n',
    '        d1_regime = _text(regime.get("higher_standard_regime"), h4_regime)\n',
    '        selected_tp = _finite(canonical.get("selected_tp") or _mapping(canonical.get("risk")).get("selected_tp"), None)\n',
    '        selected_sl = _finite(canonical.get("selected_sl") or _mapping(canonical.get("risk")).get("selected_sl"), None)\n',
    '        cost_pips = _finite(_mapping(canonical.get("risk")).get("estimated_cost"), None)\n',
    '        pip = float(TRUST_CONFIG["pip_size"])\n',
    '        if cost_pips is not None and abs(cost_pips) < 0.05:\n',
    '            cost_pips = abs(cost_pips) / pip\n',
    '        if cost_pips is None:\n',
    '            cost_pips = float(TRUST_CONFIG["default_cost_pips"]) + float(TRUST_CONFIG["safety_buffer_pips"])\n',
    '        inserted = methods_inserted = 0\n',
    '        for horizon in HORIZONS:\n',
    '            forecast = _forecast(canonical, horizon)\n',
    '            if not forecast:\n',
    '                continue\n',
    '            target = _utc(forecast.get("due_time")) or origin_time + pd.Timedelta(hours=horizon)\n',
    '            point = _finite(forecast.get("point_forecast"), None)\n',
    '            quantiles = _extract_quantiles(canonical, horizon, forecast)\n',
    '            direction = _direction(forecast.get("direction") or authority_direction)\n',
    '            raw = _safe_probability(forecast.get(f"{direction.lower()}_probability_raw"))\n',
    '            calibrated = _safe_probability(forecast.get(f"{direction.lower()}_probability_calibrated"))\n',
    '            blocker_list = list(forecast.get("blocking_reasons") or final.get("blocking_reasons") or [])\n',
    '            values = (\n',
    '                calc_id, calculation_version, origin_time.isoformat(), origin_price, target.isoformat(), horizon,\n',
    '                _session(origin_time), d1_regime, h4_regime, h1_regime, _finite(regime.get("age_hours"), None),\n',
    '                _safe_probability(regime.get("transition_probability_3h") or regime.get("transition_probability_1h")),\n',
    '                authority_direction, _text(final.get("final_decision"), "WAIT"), _text(final.get("tradeability_decision"), "WAIT"),\n',
    '                raw, calibrated, _safe_probability(forecast.get("buy_probability_raw")), _safe_probability(forecast.get("sell_probability_raw")),\n',
    '                _safe_probability(forecast.get("wait_probability_raw")), _safe_probability(forecast.get("buy_probability_calibrated")),\n',
    '                _safe_probability(forecast.get("sell_probability_calibrated")), _safe_probability(forecast.get("wait_probability_calibrated")),\n',
    '                _safe_probability(forecast.get("threshold")), _finite(forecast.get("expected_value"), None),\n',
    '                _finite(forecast.get("expected_gain"), None), _finite(forecast.get("expected_loss"), None), cost_pips,\n',
    '                point, quantiles["p10"], quantiles["p25"], quantiles["p50"], quantiles["p75"], quantiles["p90"],\n',
    '                _finite(forecast.get("lower_bound"), None), _finite(forecast.get("upper_bound"), None),\n',
    '                None, None, None, None, None, None, None, None, None, selected_tp, selected_sl,\n',
    '                _text(final.get("main_reason"), ""), _text(blocker_list[0] if blocker_list else "", ""),\n',
    '                _text(data_quality.get("status"), "UNKNOWN"), _text(drift.get("status"), "UNKNOWN"),\n',
    '                _text(nlp.get("conflict_level"), "UNKNOWN"), _finite(forecast.get("priority_score") or priority.get("score"), None),\n',
    '                _finite(forecast.get("knn_score") or priority.get("knn_score"), None), _finite(forecast.get("greedy_score") or priority.get("greedy_score"), None),\n',
    '                _safe_probability(_mapping(canonical.get("forecasts")).get("agreement_score")), "PENDING", None, created.isoformat(),\n',
    '                _text(canonical.get("source"), "UNKNOWN"), SCHEMA_VERSION,\n',
    '            )\n',
    '            sql = """\n',
    '                INSERT OR IGNORE INTO settled_forecast_ledger_v3(\n',
    '                    calculation_id,calculation_version,forecast_origin_time,forecast_origin_price,target_time,horizon,\n',
    '                    session,d1_regime,h4_regime,h1_regime,regime_age,regime_transition_risk,full_metric_direction,\n',
    '                    final_decision,tradeability_status,raw_confidence,calibrated_confidence,raw_buy_probability,\n',
    '                    raw_sell_probability,raw_wait_probability,calibrated_buy_probability,calibrated_sell_probability,\n',
    '                    calibrated_wait_probability,required_probability_threshold,expected_value_after_costs,\n',
    '                    expected_favorable_movement,expected_adverse_movement,estimated_cost_pips,predicted_close,\n',
    '                    p10,p25,p50,p75,p90,lower_band,upper_band,actual_close,absolute_error_pips,squared_error,\n',
    '                    direction_correct,interval_hit,maximum_favorable_excursion,maximum_adverse_excursion,tp_touched,\n',
    '                    sl_touched,selected_tp,selected_sl,main_reason,strongest_blocker,data_quality_status,drift_status,\n',
    '                    event_risk_status,priority,knn_score,greedy_rank,model_agreement,record_status,settlement_timestamp,\n',
    '                    created_at,source,schema_version\n',
    '                ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n',
    '            """\n',
    '            inserted += max(0, int(self._execute(sql, values)))\n',
    '            for method, method_point in self._method_forecasts(canonical, ohlc, horizon, point, origin_price).items():\n',
    '                if method_point is None:\n',
    '                    continue\n',
    '                method_direction = "BUY" if method_point > origin_price else "SELL" if method_point < origin_price else "WAIT"\n',
    '                methods_inserted += max(0, int(self._execute(\n',
    '                    """\n',
    '                    INSERT OR IGNORE INTO forecast_method_ledger_v3(\n',
    '                        calculation_id,calculation_version,forecast_origin_time,target_time,horizon,method,predicted_close,\n',
    '                        predicted_direction,record_status,created_at\n',
    "                    ) VALUES (?,?,?,?,?,?,?,?, 'PENDING', ?)\n",
    '                    """,\n',
    '                    (calc_id, calculation_version, origin_time.isoformat(), target.isoformat(), horizon, method, method_point, method_direction, created.isoformat()),\n',
    '                )))\n',
    '        return {"ok": True, "inserted": inserted, "method_rows": methods_inserted, "calculation_id": calc_id}\n',
    '\n',
    '    def frame(self, *, status: Optional[str] = None, limit: int = 10000) -> pd.DataFrame:\n',
    '        clauses = []\n',
    '        params: list[Any] = []\n',
    '        if status:\n',
    '            clauses.append("record_status=?")\n',
    '            params.append(status)\n',
    '        params.append(int(limit))\n',
    '        where = " WHERE " + " AND ".join(clauses) if clauses else ""\n',
    '        rows = self._execute(\n',
    '            f"SELECT * FROM settled_forecast_ledger_v3{where} ORDER BY forecast_origin_time DESC,horizon ASC LIMIT ?",\n',
    '            params,\n',
    '            fetch=True,\n',
    '        )\n',
    '        return pd.DataFrame(rows)\n',
    '\n',
    '    def method_frame(self, *, status: str = "SETTLED", limit: int = 50000) -> pd.DataFrame:\n',
    '        rows = self._execute(\n',
    '            "SELECT * FROM forecast_method_ledger_v3 WHERE record_status=? ORDER BY forecast_origin_time ASC LIMIT ?",\n',
    '            (status, int(limit)),\n',
    '            fetch=True,\n',
    '        )\n',
    '        return pd.DataFrame(rows)\n',
    '\n',
    '    def pending_count(self) -> int:\n',
    '        rows = self._execute("SELECT COUNT(*) AS n FROM settled_forecast_ledger_v3 WHERE record_status=\'PENDING\'", fetch=True)\n',
    '        return int(rows[0]["n"]) if rows else 0\n',
    '\n',
    '    def persist_snapshot(self, calculation_id: str, summary: Mapping[str, Any]) -> None:\n',
    '        self._execute(\n',
    '            """\n',
    '            INSERT OR REPLACE INTO trust_validation_snapshots_v3(\n',
    '                calculation_id,created_at,calculation_version,settled_sample_count,trust_classification,summary_json,schema_version\n',
    '            ) VALUES (?,?,?,?,?,?,?)\n',
    '            """,\n',
    '            (\n',
    '                calculation_id, _utc_now(), _text(summary.get("calculation_version")), int(summary.get("settled_sample_count") or 0),\n',
    '                _text(summary.get("trust_classification"), "INSUFFICIENT"), _json(summary), SCHEMA_VERSION,\n',
    '            ),\n',
    '        )\n',
    '\n',
    '\n',
    'def _calibration_metrics(probabilities: pd.Series, outcomes: pd.Series) -> Dict[str, Any]:\n',
    '    p = pd.to_numeric(probabilities, errors="coerce")\n',
    '    y = pd.to_numeric(outcomes, errors="coerce")\n',
    '    valid = p.notna() & y.notna()\n',
    '    p = p.loc[valid].clip(1e-6, 1 - 1e-6)\n',
    '    y = y.loc[valid].clip(0, 1)\n',
    '    n = int(len(p))\n',
    '    if n < int(TRUST_CONFIG["minimum_calibration_samples"]):\n',
    '        return {\n',
    '            "status": "DEVELOPING", "sample_count": n, "brier_score": None, "expected_calibration_error": None,\n',
    '            "maximum_calibration_error": None, "calibration_slope": None, "calibration_intercept": None,\n',
    '            "reliability_bins": [], "message": "Calibration developing — insufficient settled samples",\n',
    '        }\n',
    '    brier = float(np.mean((p.to_numpy() - y.to_numpy()) ** 2))\n',
    '    bins = []\n',
    '    ece = mce = 0.0\n',
    '    for low in np.linspace(0, 0.9, 10):\n',
    '        high = low + 0.1\n',
    '        mask = (p >= low) & (p < high if high < 1 else p <= high)\n',
    '        count = int(mask.sum())\n',
    '        if not count:\n',
    '            continue\n',
    '        mean_p = float(p.loc[mask].mean())\n',
    '        mean_y = float(y.loc[mask].mean())\n',
    '        gap = abs(mean_p - mean_y)\n',
    '        ece += gap * count / n\n',
    '        mce = max(mce, gap)\n',
    '        bins.append({"lower": round(low, 2), "upper": round(high, 2), "count": count, "mean_probability": mean_p, "observed_rate": mean_y})\n',
    '    x = np.log(p.to_numpy() / (1 - p.to_numpy()))\n',
    '    slope = intercept = None\n',
    '    if np.std(x) > 1e-12:\n',
    '        try:\n',
    '            slope, intercept = np.polyfit(x, y.to_numpy(), 1)\n',
    '            slope, intercept = float(slope), float(intercept)\n',
    '        except Exception:\n',
    '            pass\n',
    '    return {\n',
    '        "status": "VALID", "sample_count": n, "brier_score": brier,\n',
    '        "expected_calibration_error": float(ece), "maximum_calibration_error": float(mce),\n',
    '        "calibration_slope": slope, "calibration_intercept": intercept, "reliability_bins": bins,\n',
    '        "message": "Settled out-of-sample calibration",\n',
    '    }\n',
    '\n',
    '\n',
    'def _diebold_mariano(loss_a: np.ndarray, loss_b: np.ndarray, horizon: int) -> Dict[str, Any]:\n',
    '    mask = np.isfinite(loss_a) & np.isfinite(loss_b)\n',
    '    d = loss_a[mask] - loss_b[mask]\n',
    '    n = len(d)\n',
    '    if n < int(TRUST_CONFIG["minimum_dm_samples"]):\n',
    '        return {"status": "UNAVAILABLE", "sample_count": n, "reason": "Need aligned settled forecasts"}\n',
    '    mean_d = float(np.mean(d))\n',
    '    centered = d - mean_d\n',
    '    lag_max = max(0, min(int(horizon) - 1, n // 5))\n',
    '    variance = float(np.var(centered, ddof=1))\n',
    '    for lag in range(1, lag_max + 1):\n',
    '        covariance = float(np.sum(centered[lag:] * centered[:-lag]) / n)\n',
    '        variance += 2.0 * (1.0 - lag / (lag_max + 1)) * covariance\n',
    '    variance = max(variance / n, 1e-12)\n',
    '    statistic = mean_d / math.sqrt(variance)\n',
    '    p_value = math.erfc(abs(statistic) / math.sqrt(2.0))\n',
    '    preferred = "METHOD_A" if mean_d < 0 else "METHOD_B" if mean_d > 0 else "TIE"\n',
    '    return {"status": "SIGNIFICANT" if p_value < 0.05 else "NOT_SIGNIFICANT", "sample_count": n, "statistic": statistic, "p_value": p_value, "preferred": preferred}\n',
    '\n',
    '\n',
    'def _spa_equivalent(methods: pd.DataFrame, benchmark: str = "LAST_CLOSE") -> Dict[str, Any]:\n',
    '    if methods.empty:\n',
    '        return {"status": "UNAVAILABLE", "sample_count": 0, "reason": "No settled method forecasts"}\n',
    '    pivot = methods.pivot_table(index=["calculation_id", "horizon"], columns="method", values="absolute_error", aggfunc="first")\n',
    '    if benchmark not in pivot.columns:\n',
    '        return {"status": "UNAVAILABLE", "sample_count": 0, "reason": "Benchmark unavailable"}\n',
    '    candidates = [c for c in pivot.columns if c != benchmark]\n',
    '    if not candidates:\n',
    '        return {"status": "UNAVAILABLE", "sample_count": 0, "reason": "No challenger methods"}\n',
    '    aligned = pivot[[benchmark] + candidates].dropna()\n',
    '    n = len(aligned)\n',
    '    if n < int(TRUST_CONFIG["minimum_spa_samples"]):\n',
    '        return {"status": "UNAVAILABLE", "sample_count": n, "reason": "Insufficient aligned settled forecasts"}\n',
    '    differentials = {c: aligned[benchmark].to_numpy() - aligned[c].to_numpy() for c in candidates}\n',
    '    means = {c: float(np.mean(v)) for c, v in differentials.items()}\n',
    '    best = max(means, key=means.get)\n',
    '    observed = means[best]\n',
    '    rng = np.random.default_rng(20260619)\n',
    '    centered = {c: v - np.mean(v) for c, v in differentials.items()}\n',
    '    boot = []\n',
    '    block = max(2, int(round(n ** (1 / 3))))\n',
    '    for _ in range(600):\n',
    '        indices: list[int] = []\n',
    '        while len(indices) < n:\n',
    '            start = int(rng.integers(0, n))\n',
    '            indices.extend([(start + j) % n for j in range(block)])\n',
    '        indices = indices[:n]\n',
    '        boot.append(max(float(np.mean(v[indices])) for v in centered.values()))\n',
    '    p_value = float((1 + sum(x >= observed for x in boot)) / (len(boot) + 1))\n',
    '    return {\n',
    '        "status": "SUPERIOR" if observed > 0 and p_value < 0.05 else "NOT_PROVEN",\n',
    '        "sample_count": n, "best_method": best, "benchmark": benchmark,\n',
    '        "mean_loss_improvement": observed, "p_value": p_value,\n',
    '        "test": "block-bootstrap SPA-equivalent on aligned absolute-error losses",\n',
    '    }\n',
    '\n',
    '\n',
    'def _dsr(net_pips: np.ndarray, trial_sharpes: np.ndarray) -> Dict[str, Any]:\n',
    '    values = net_pips[np.isfinite(net_pips)]\n',
    '    trials = trial_sharpes[np.isfinite(trial_sharpes)]\n',
    '    if len(values) < 30:\n',
    '        return {"status": "UNAVAILABLE", "sample_size": int(len(values)), "reason": "Need at least 30 aligned net returns"}\n',
    '    if len(trials) < 2:\n',
    '        return {"status": "UNAVAILABLE", "sample_size": int(len(values)), "number_of_tested_configurations": int(len(trials)), "reason": "Need at least two genuine tested configurations"}\n',
    '    std = float(np.std(values, ddof=1))\n',
    '    if std <= 1e-12:\n',
    '        return {"status": "UNAVAILABLE", "sample_size": int(len(values)), "reason": "Zero return variance"}\n',
    '    mean = float(np.mean(values))\n',
    '    z = (values - mean) / std\n',
    '    skew = float(np.mean(z ** 3))\n',
    '    kurt = float(np.mean(z ** 4))\n',
    '    raw_sharpe = mean / std * math.sqrt(252.0)\n',
    '    trial_std = max(float(np.std(trials, ddof=1)), 1e-12)\n',
    '    expected_max = float(np.mean(trials) + trial_std * math.sqrt(2.0 * math.log(max(len(trials), 2))))\n',
    '    denom = math.sqrt(max((1.0 - skew * raw_sharpe + (kurt - 1.0) * raw_sharpe ** 2 / 4.0) / max(len(values) - 1, 1), 1e-12))\n',
    '    statistic = (raw_sharpe - expected_max) / denom\n',
    '    probability = 0.5 * (1.0 + math.erf(statistic / math.sqrt(2.0)))\n',
    '    return {\n',
    '        "status": "ACCEPT" if probability >= 0.95 else "WEAK" if probability >= 0.70 else "REJECT",\n',
    '        "raw_sharpe": raw_sharpe, "deflated_sharpe_probability": probability, "sample_size": int(len(values)),\n',
    '        "skewness": skew, "kurtosis": kurt, "number_of_tested_configurations": int(len(trials)),\n',
    '    }\n',
    '\n',
    '\n',
    'def _pbo(frame: pd.DataFrame) -> Dict[str, Any]:\n',
    '    if frame.empty or "calculation_version" not in frame:\n',
    '        return {"status": "UNAVAILABLE", "reason": "No genuine configuration history", "tested_configuration_count": 0, "fold_count": 0}\n',
    '    configs = sorted(frame["calculation_version"].dropna().astype(str).unique())\n',
    '    min_configs = int(TRUST_CONFIG["minimum_pbo_configurations"])\n',
    '    if len(configs) < min_configs:\n',
    '        return {"status": "UNAVAILABLE", "reason": "Need at least two genuinely tested configurations", "tested_configuration_count": len(configs), "fold_count": 0}\n',
    '    data = frame.sort_values("forecast_origin_time").copy()\n',
    '    folds = np.array_split(np.arange(len(data)), max(int(TRUST_CONFIG["minimum_pbo_folds"]), min(8, len(data) // 25)))\n',
    '    ranks = []\n',
    '    usable = 0\n',
    '    for test_idx in folds:\n',
    '        if len(test_idx) < 5:\n',
    '            continue\n',
    '        train_idx = np.setdiff1d(np.arange(len(data)), test_idx)\n',
    '        train = data.iloc[train_idx]\n',
    '        test = data.iloc[test_idx]\n',
    '        train_scores = train.groupby("calculation_version")["net_pips"].mean()\n',
    '        test_scores = test.groupby("calculation_version")["net_pips"].mean()\n',
    '        common = train_scores.index.intersection(test_scores.index)\n',
    '        if len(common) < min_configs:\n',
    '            continue\n',
    '        best = train_scores.loc[common].idxmax()\n',
    '        rank = float(test_scores.loc[common].rank(pct=True, ascending=True).loc[best])\n',
    '        ranks.append(rank)\n',
    '        usable += 1\n',
    '    if usable < int(TRUST_CONFIG["minimum_pbo_folds"]):\n',
    '        return {"status": "UNAVAILABLE", "reason": "Insufficient chronological folds with multiple configurations", "tested_configuration_count": len(configs), "fold_count": usable}\n',
    '    probability = float(np.mean(np.asarray(ranks) <= 0.5))\n',
    '    return {"status": "VALID", "probability_of_backtest_overfitting": probability, "tested_configuration_count": len(configs), "fold_count": usable, "validation_status": "REJECT" if probability > 0.5 else "ACCEPT"}\n',
    '\n',
    '\n',
    'def aggregate_trust(store: TrustHistoryStore) -> Dict[str, Any]:\n',
    '    frame = store.frame(status="SETTLED", limit=50000)\n',
    '    if frame.empty:\n',
    '        return {\n',
    '            "schema_version": SCHEMA_VERSION, "settled_sample_count": 0, "pending_sample_count": store.pending_count(),\n',
    '            "trust_classification": "INSUFFICIENT", "message": "Calibration developing — insufficient settled samples",\n',
    '            "groups": [], "calibration": {}, "interval": {}, "pbo": {"status": "UNAVAILABLE"},\n',
    '            "dsr": {"status": "UNAVAILABLE"}, "dm": [], "spa": {"status": "UNAVAILABLE"},\n',
    '        }\n',
    '    numeric_cols = [\n',
    '        "forecast_origin_price", "actual_close", "absolute_error_pips", "squared_error", "direction_correct", "interval_hit",\n',
    '        "maximum_favorable_excursion", "maximum_adverse_excursion", "tp_touched", "sl_touched", "expected_value_after_costs",\n',
    '        "estimated_cost_pips", "raw_confidence", "calibrated_confidence", "lower_band", "upper_band", "predicted_close",\n',
    '    ]\n',
    '    for col in numeric_cols:\n',
    '        if col in frame:\n',
    '            frame[col] = pd.to_numeric(frame[col], errors="coerce")\n',
    '    frame["forecast_origin_time"] = pd.to_datetime(frame["forecast_origin_time"], utc=True, errors="coerce")\n',
    '    frame["signed_gross_pips"] = [\n',
    '        _signed_pips(float(o), float(a), _direction(d)) if pd.notna(o) and pd.notna(a) else np.nan\n',
    '        for o, a, d in zip(frame["forecast_origin_price"], frame["actual_close"], frame["full_metric_direction"])\n',
    '    ]\n',
    '    frame["net_pips"] = frame["signed_gross_pips"] - frame["estimated_cost_pips"].fillna(float(TRUST_CONFIG["default_cost_pips"]) + float(TRUST_CONFIG["safety_buffer_pips"]))\n',
    '    frame["interval_width_pips"] = (frame["upper_band"] - frame["lower_band"]).abs() / float(TRUST_CONFIG["pip_size"])\n',
    '    groups = []\n',
    '    group_cols = ["h1_regime", "h4_regime", "d1_regime", "session", "horizon", "full_metric_direction", "calculation_version"]\n',
    '    for keys, group in frame.groupby(group_cols, dropna=False):\n',
    '        n = len(group)\n',
    '        net = group["net_pips"].dropna().to_numpy(dtype=float)\n',
    '        wins = net[net > 0]\n',
    '        losses = net[net < 0]\n',
    '        equity = np.cumsum(net) if len(net) else np.array([])\n',
    '        drawdown = float(np.max(np.maximum.accumulate(equity) - equity)) if len(equity) else None\n',
    '        pf = float(np.sum(wins) / abs(np.sum(losses))) if len(losses) and abs(np.sum(losses)) > 1e-12 else None\n',
    '        cal = _calibration_metrics(group["calibrated_confidence"], group["direction_correct"])\n',
    '        coverage = float(group["interval_hit"].mean()) if group["interval_hit"].notna().any() else None\n',
    '        width = float(group["interval_width_pips"].mean()) if group["interval_width_pips"].notna().any() else None\n',
    '        if n >= int(TRUST_CONFIG["validated_min_samples"]) and np.nanmean(net) > 0 and (cal.get("expected_calibration_error") is None or cal.get("expected_calibration_error") <= TRUST_CONFIG["acceptable_ece"]):\n',
    '            trust = "VALIDATED"\n',
    '        elif np.nanmean(net) < 0:\n',
    '            trust = "REJECTED"\n',
    '        elif n >= int(TRUST_CONFIG["developing_min_samples"]):\n',
    '            trust = "DEVELOPING"\n',
    '        else:\n',
    '            trust = "INSUFFICIENT"\n',
    '        groups.append({\n',
    '            **dict(zip(group_cols, keys if isinstance(keys, tuple) else (keys,))),\n',
    '            "settled_sample_count": n, "opportunity_coverage": float((group["tradeability_status"].isin(["BUY", "SELL"])).mean()),\n',
    '            "trade_frequency": float((group["final_decision"].isin(["BUY", "SELL"])).mean()),\n',
    '            "direction_accuracy": float(group["direction_correct"].mean()), "average_net_pips": float(np.nanmean(net)) if len(net) else None,\n',
]
