"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Immutable settled-forecast ledger and trust validation for EURUSD H1.\n',
    '\n',
    'The store is additive and shares the existing SQLite database. Original\n',
    'forecast fields are inserted once and are never overwritten. Settlement updates\n',
    'only outcome fields after the target H1 candle is fully available.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import json\n',
    'import math\n',
    'import os\n',
    'import sqlite3\n',
    'import threading\n',
    'from contextlib import contextmanager\n',
    'from datetime import datetime, timezone\n',
    'from pathlib import Path\n',
    'from typing import Any, Dict, Iterable, Mapping, Optional, Sequence\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'from core.trust_config_20260619 import TRUST_CONFIG\n',
    '\n',
    'PROJECT_ROOT = Path(__file__).resolve().parents[1]\n',
    'DEFAULT_DB_PATH = PROJECT_ROOT / "data" / "quant_app.sqlite3"\n',
    '_LOCK = threading.RLock()\n',
    'SCHEMA_VERSION = "adx-trust-history-3.0.0"\n',
    'CALCULATION_VERSION = "trust-validation-20260619-v1"\n',
    'HORIZONS = (1, 2, 3, 6)\n',
    '\n',
    '\n',
    'def _utc_now() -> str:\n',
    '    return datetime.now(timezone.utc).isoformat()\n',
    '\n',
    '\n',
    'def _finite(value: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    try:\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _text(value: Any, default: str = "") -> str:\n',
    '    return default if value in (None, "") else str(value)\n',
    '\n',
    '\n',
    'def _utc(value: Any) -> Optional[pd.Timestamp]:\n',
    '    try:\n',
    '        ts = pd.Timestamp(value)\n',
    '        if pd.isna(ts):\n',
    '            return None\n',
    '        return ts.tz_localize("UTC") if ts.tzinfo is None else ts.tz_convert("UTC")\n',
    '    except Exception:\n',
    '        return None\n',
    '\n',
    '\n',
    'def _iso(value: Any) -> Optional[str]:\n',
    '    ts = _utc(value)\n',
    '    return ts.isoformat() if ts is not None else None\n',
    '\n',
    '\n',
    'def _direction(value: Any) -> str:\n',
    '    text = str(value or "").upper()\n',
    '    if "BUY" in text or "BULL" in text or text == "UP":\n',
    '        return "BUY"\n',
    '    if "SELL" in text or "BEAR" in text or text == "DOWN":\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _session(ts: pd.Timestamp) -> str:\n',
    '    hour = int(ts.hour)\n',
    '    if 0 <= hour < 7:\n',
    '        return "ASIA"\n',
    '    if 7 <= hour < 12:\n',
    '        return "LONDON"\n',
    '    if 12 <= hour < 16:\n',
    '        return "LONDON_NY_OVERLAP"\n',
    '    if 16 <= hour < 21:\n',
    '        return "NEW_YORK"\n',
    '    return "LATE_NY"\n',
    '\n',
    '\n',
    'def normalize_completed_ohlc(frame: Any) -> pd.DataFrame:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame(columns=["open", "high", "low", "close"])\n',
    '    data = frame.copy(deep=False)\n',
    '    cmap = {str(c).strip().lower(): c for c in data.columns}\n',
    '    tcol = next((cmap[x] for x in ("time", "timestamp", "datetime", "date") if x in cmap), None)\n',
    '    cols: dict[str, Any] = {}\n',
    '    for name in ("open", "high", "low", "close"):\n',
    '        col = cmap.get(name) or cmap.get(name[0])\n',
    '        if col is None:\n',
    '            return pd.DataFrame(columns=["open", "high", "low", "close"])\n',
    '        cols[name] = col\n',
    '    idx = pd.to_datetime(data[tcol] if tcol is not None else data.index, utc=True, errors="coerce")\n',
    '    out = pd.DataFrame(\n',
    '        {name: pd.to_numeric(data[col], errors="coerce").to_numpy() for name, col in cols.items()},\n',
    '        index=pd.DatetimeIndex(idx),\n',
    '    )\n',
    '    out = out.loc[~out.index.isna()].dropna().sort_index()\n',
    '    out = out.loc[~out.index.duplicated(keep="last")]\n',
    '    return out\n',
    '\n',
    '\n',
    'def _mapping(value: Any) -> Mapping[str, Any]:\n',
    '    return value if isinstance(value, Mapping) else {}\n',
    '\n',
    '\n',
    'def _forecast(canonical: Mapping[str, Any], horizon: int) -> Mapping[str, Any]:\n',
    '    return _mapping(_mapping(_mapping(canonical.get("forecasts")).get("horizons")).get(f"{horizon}h"))\n',
    '\n',
    '\n',
    'def _extract_quantiles(canonical: Mapping[str, Any], horizon: int, forecast: Mapping[str, Any]) -> dict[str, Optional[float]]:\n',
    '    result = {"p10": None, "p25": None, "p50": None, "p75": None, "p90": None}\n',
    '    for key in result:\n',
    '        result[key] = _finite(forecast.get(key) or forecast.get(key.upper()), None)\n',
    '    probabilistic = _mapping(canonical.get("probabilistic_projection"))\n',
    '    candidates = probabilistic.get("horizons") or probabilistic.get("quantiles") or probabilistic.get("projection")\n',
    '    if isinstance(candidates, Mapping):\n',
    '        row = _mapping(candidates.get(f"{horizon}h") or candidates.get(str(horizon)) or candidates.get(horizon))\n',
    '        for key in result:\n',
    '            if result[key] is None:\n',
    '                result[key] = _finite(row.get(key) or row.get(key.upper()), None)\n',
    '    if result["p50"] is None:\n',
    '        result["p50"] = _finite(forecast.get("point_forecast"), None)\n',
    '    if result["p10"] is None:\n',
    '        result["p10"] = _finite(forecast.get("lower_bound"), None)\n',
    '    if result["p90"] is None:\n',
    '        result["p90"] = _finite(forecast.get("upper_bound"), None)\n',
    '    return result\n',
    '\n',
    '\n',
    'def _signed_pips(origin: float, actual: float, direction: str) -> float:\n',
    '    pip = float(TRUST_CONFIG["pip_size"])\n',
    '    raw = (actual - origin) / pip\n',
    '    return raw if direction == "BUY" else -raw if direction == "SELL" else -abs(raw)\n',
    '\n',
    '\n',
    'def _safe_probability(value: Any) -> Optional[float]:\n',
    '    v = _finite(value, None)\n',
    '    if v is None:\n',
    '        return None\n',
    '    if v > 1.0:\n',
    '        v /= 100.0\n',
    '    return max(0.0, min(1.0, v))\n',
    '\n',
    '\n',
    'def _json(value: Any) -> str:\n',
    '    return json.dumps(value, ensure_ascii=False, default=str)\n',
    '\n',
    '\n',
    'class TrustHistoryStore:\n',
    '    def __init__(self, db_path: Path | str | None = None) -> None:\n',
    '        configured = os.environ.get("ADX_LEDGER_DB_PATH")\n',
    '        self.db_path = Path(db_path or configured or DEFAULT_DB_PATH)\n',
    '        self.db_path.parent.mkdir(parents=True, exist_ok=True)\n',
    '        self.last_error = ""\n',
    '        self.initialize()\n',
    '\n',
    '    @contextmanager\n',
    '    def connection(self):\n',
    '        conn = sqlite3.connect(str(self.db_path), timeout=20, check_same_thread=False)\n',
    '        conn.row_factory = sqlite3.Row\n',
    '        try:\n',
    '            conn.execute("PRAGMA journal_mode=WAL")\n',
    '            conn.execute("PRAGMA synchronous=NORMAL")\n',
    '            conn.execute("PRAGMA busy_timeout=20000")\n',
    '            conn.execute("PRAGMA foreign_keys=ON")\n',
    '            yield conn\n',
    '            conn.commit()\n',
    '        except Exception:\n',
    '            conn.rollback()\n',
    '            raise\n',
    '        finally:\n',
    '            conn.close()\n',
    '\n',
    '    def _execute(self, sql: str, params: Sequence[Any] = (), *, fetch: bool = False, many: bool = False) -> Any:\n',
    '        last: Optional[Exception] = None\n',
    '        for attempt in range(5):\n',
    '            try:\n',
    '                with _LOCK, self.connection() as conn:\n',
    '                    cur = conn.executemany(sql, params) if many else conn.execute(sql, tuple(params))\n',
    '                    return [dict(row) for row in cur.fetchall()] if fetch else cur.rowcount\n',
    '            except sqlite3.OperationalError as exc:\n',
    '                last = exc\n',
    '                if "locked" not in str(exc).lower() or attempt == 4:\n',
    '                    raise\n',
    '                import time\n',
    '                time.sleep(0.12 * (attempt + 1))\n',
    '        raise RuntimeError(str(last or "database operation failed"))\n',
    '\n',
    '    def initialize(self) -> None:\n',
    '        statements = [\n',
    '            """\n',
    '            CREATE TABLE IF NOT EXISTS settled_forecast_ledger_v3 (\n',
    '                calculation_id TEXT NOT NULL,\n',
    '                calculation_version TEXT NOT NULL,\n',
    '                forecast_origin_time TEXT NOT NULL,\n',
    '                forecast_origin_price REAL,\n',
    '                target_time TEXT NOT NULL,\n',
    '                horizon INTEGER NOT NULL,\n',
    '                session TEXT,\n',
    '                d1_regime TEXT,\n',
    '                h4_regime TEXT,\n',
    '                h1_regime TEXT,\n',
    '                regime_age REAL,\n',
    '                regime_transition_risk REAL,\n',
    '                full_metric_direction TEXT,\n',
    '                final_decision TEXT,\n',
    '                tradeability_status TEXT,\n',
    '                raw_confidence REAL,\n',
    '                calibrated_confidence REAL,\n',
    '                raw_buy_probability REAL,\n',
    '                raw_sell_probability REAL,\n',
    '                raw_wait_probability REAL,\n',
    '                calibrated_buy_probability REAL,\n',
    '                calibrated_sell_probability REAL,\n',
    '                calibrated_wait_probability REAL,\n',
    '                required_probability_threshold REAL,\n',
    '                expected_value_after_costs REAL,\n',
    '                expected_favorable_movement REAL,\n',
    '                expected_adverse_movement REAL,\n',
    '                estimated_cost_pips REAL,\n',
    '                predicted_close REAL,\n',
    '                p10 REAL,\n',
    '                p25 REAL,\n',
    '                p50 REAL,\n',
    '                p75 REAL,\n',
    '                p90 REAL,\n',
    '                lower_band REAL,\n',
    '                upper_band REAL,\n',
    '                actual_close REAL,\n',
    '                absolute_error_pips REAL,\n',
    '                squared_error REAL,\n',
    '                direction_correct INTEGER,\n',
    '                interval_hit INTEGER,\n',
    '                maximum_favorable_excursion REAL,\n',
    '                maximum_adverse_excursion REAL,\n',
    '                tp_touched INTEGER,\n',
    '                sl_touched INTEGER,\n',
    '                selected_tp REAL,\n',
    '                selected_sl REAL,\n',
    '                main_reason TEXT,\n',
    '                strongest_blocker TEXT,\n',
    '                data_quality_status TEXT,\n',
    '                drift_status TEXT,\n',
    '                event_risk_status TEXT,\n',
    '                priority REAL,\n',
    '                knn_score REAL,\n',
    '                greedy_rank REAL,\n',
    '                model_agreement REAL,\n',
    "                record_status TEXT NOT NULL DEFAULT 'PENDING',\n",
    '                settlement_timestamp TEXT,\n',
    '                created_at TEXT NOT NULL,\n',
    '                source TEXT,\n',
    '                schema_version TEXT NOT NULL,\n',
    '                PRIMARY KEY(calculation_id, horizon)\n',
    '            )\n',
    '            """,\n',
    '            """\n',
    '            CREATE TABLE IF NOT EXISTS forecast_method_ledger_v3 (\n',
    '                calculation_id TEXT NOT NULL,\n',
    '                calculation_version TEXT NOT NULL,\n',
    '                forecast_origin_time TEXT NOT NULL,\n',
    '                target_time TEXT NOT NULL,\n',
    '                horizon INTEGER NOT NULL,\n',
    '                method TEXT NOT NULL,\n',
    '                predicted_close REAL,\n',
    '                predicted_direction TEXT,\n',
    '                actual_close REAL,\n',
    '                absolute_error REAL,\n',
    '                squared_error REAL,\n',
    '                directional_loss REAL,\n',
    '                quantile_loss REAL,\n',
    "                record_status TEXT NOT NULL DEFAULT 'PENDING',\n",
    '                settlement_timestamp TEXT,\n',
    '                created_at TEXT NOT NULL,\n',
    '                PRIMARY KEY(calculation_id, horizon, method)\n',
    '            )\n',
    '            """,\n',
    '            """\n',
    '            CREATE TABLE IF NOT EXISTS trust_validation_snapshots_v3 (\n',
    '                calculation_id TEXT PRIMARY KEY,\n',
    '                created_at TEXT NOT NULL,\n',
    '                calculation_version TEXT,\n',
    '                settled_sample_count INTEGER,\n',
    '                trust_classification TEXT,\n',
    '                summary_json TEXT NOT NULL,\n',
    '                schema_version TEXT NOT NULL\n',
    '            )\n',
    '            """,\n',
    '            "CREATE INDEX IF NOT EXISTS idx_trust_origin ON settled_forecast_ledger_v3(forecast_origin_time)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_trust_target ON settled_forecast_ledger_v3(target_time)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_trust_horizon ON settled_forecast_ledger_v3(horizon)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_trust_regime ON settled_forecast_ledger_v3(h1_regime,h4_regime,d1_regime)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_trust_session ON settled_forecast_ledger_v3(session)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_trust_calc ON settled_forecast_ledger_v3(calculation_id)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_trust_status_target ON settled_forecast_ledger_v3(record_status,target_time)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_method_status_target ON forecast_method_ledger_v3(record_status,target_time)",\n',
    '        ]\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            for statement in statements:\n',
    '                conn.execute(statement)\n',
    '        self._backfill_legacy_once()\n',
    '\n',
    '    def _backfill_legacy_once(self) -> None:\n',
    '        """Seed immutable history from the older ledger without changing it."""\n',
    '        try:\n',
    '            with _LOCK, self.connection() as conn:\n',
    '                legacy = conn.execute("SELECT name FROM sqlite_master WHERE type=\'table\' AND name=\'predictions\'").fetchone()\n',
    '                if not legacy:\n',
    '                    return\n',
    '                existing = conn.execute("SELECT COUNT(*) FROM settled_forecast_ledger_v3").fetchone()[0]\n',
    '                if existing:\n',
    '                    return\n',
    '                rows = conn.execute(\n',
    '                    """\n',
    '                    SELECT r.run_id,r.calculation_version,r.created_at,r.latest_completed_candle_time,r.source,\n',
    '                           p.horizon_hours,p.current_price,p.predicted_price,p.predicted_direction,\n',
    '                           p.buy_probability_raw,p.sell_probability_raw,p.wait_probability_raw,\n',
    '                           p.buy_probability_calibrated,p.sell_probability_calibrated,p.wait_probability_calibrated,\n',
    '                           p.decision_threshold,p.expected_value,p.expected_gain,p.expected_loss,p.estimated_cost,\n',
    '                           p.lower_bound,p.upper_bound,p.priority_score,p.knn_score,p.greedy_score,p.due_time,\n',
    '                           o.actual_price,o.absolute_error,o.direction_correct,o.target_hit,o.stop_hit,\n',
    '                           o.maximum_favourable_excursion,o.maximum_adverse_excursion,o.outcome_status,o.settled_at,\n',
    '                           rs.major_regime,rs.regime_age_hours,rs.transition_probability_3h\n',
    '                    FROM calculation_runs r\n',
    '                    JOIN predictions p ON p.run_id=r.run_id\n',
    '                    LEFT JOIN prediction_outcomes o ON o.run_id=p.run_id AND o.horizon_hours=p.horizon_hours\n',
    '                    LEFT JOIN regime_snapshots rs ON rs.run_id=r.run_id\n',
    '                    ORDER BY r.created_at ASC\n',
    '                    """\n',
    '                ).fetchall()\n',
    '                insert = """\n',
    '                    INSERT OR IGNORE INTO settled_forecast_ledger_v3(\n',
    '                        calculation_id,calculation_version,forecast_origin_time,forecast_origin_price,target_time,horizon,\n',
    '                        session,d1_regime,h4_regime,h1_regime,regime_age,regime_transition_risk,full_metric_direction,\n',
    '                        final_decision,tradeability_status,raw_confidence,calibrated_confidence,raw_buy_probability,\n',
    '                        raw_sell_probability,raw_wait_probability,calibrated_buy_probability,calibrated_sell_probability,\n',
    '                        calibrated_wait_probability,required_probability_threshold,expected_value_after_costs,\n',
    '                        expected_favorable_movement,expected_adverse_movement,estimated_cost_pips,predicted_close,\n',
    '                        p10,p25,p50,p75,p90,lower_band,upper_band,actual_close,absolute_error_pips,squared_error,\n',
    '                        direction_correct,interval_hit,maximum_favorable_excursion,maximum_adverse_excursion,tp_touched,\n',
    '                        sl_touched,selected_tp,selected_sl,main_reason,strongest_blocker,data_quality_status,drift_status,\n',
    '                        event_risk_status,priority,knn_score,greedy_rank,model_agreement,record_status,settlement_timestamp,\n',
    '                        created_at,source,schema_version\n',
    '                    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n',
    '                """\n',
    '                payloads = []\n',
    '                pip = float(TRUST_CONFIG["pip_size"])\n',
    '                for row in rows:\n',
    '                    d = dict(row)\n',
    '                    origin = _utc(d.get("latest_completed_candle_time") or d.get("created_at"))\n',
    '                    if origin is None:\n',
    '                        continue\n',
    '                    direction = _direction(d.get("predicted_direction"))\n',
    '                    raw = d.get(f"{direction.lower()}_probability_raw") if direction in {"BUY", "SELL", "WAIT"} else None\n',
    '                    cal = d.get(f"{direction.lower()}_probability_calibrated") if direction in {"BUY", "SELL", "WAIT"} else None\n',
    '                    abs_pips = (_finite(d.get("absolute_error"), 0.0) or 0.0) / pip if d.get("absolute_error") is not None else None\n',
    '                    status = str(d.get("outcome_status") or "PENDING").upper()\n',
    '                    payloads.append((\n',
    '                        d.get("run_id"), d.get("calculation_version") or "legacy", origin.isoformat(), d.get("current_price"),\n',
    '                        _iso(d.get("due_time")) or (origin + pd.Timedelta(hours=int(d.get("horizon_hours") or 1))).isoformat(),\n',
    '                        int(d.get("horizon_hours") or 1), _session(origin), None, None, d.get("major_regime"), d.get("regime_age_hours"),\n',
    '                        d.get("transition_probability_3h"), direction, d.get("decision"), d.get("decision"), raw, cal,\n',
    '                        d.get("buy_probability_raw"), d.get("sell_probability_raw"), d.get("wait_probability_raw"),\n',
    '                        d.get("buy_probability_calibrated"), d.get("sell_probability_calibrated"), d.get("wait_probability_calibrated"),\n',
    '                        d.get("decision_threshold"), d.get("expected_value"), d.get("expected_gain"), d.get("expected_loss"),\n',
    '                        (_finite(d.get("estimated_cost"), 0.0) or 0.0) / pip, d.get("predicted_price"), d.get("lower_bound"), None,\n',
    '                        d.get("predicted_price"), None, d.get("upper_bound"), d.get("lower_bound"), d.get("upper_bound"),\n',
    '                        d.get("actual_price"), abs_pips, (abs_pips ** 2 if abs_pips is not None else None), d.get("direction_correct"),\n',
    '                        int(bool(d.get("actual_price") is not None and d.get("lower_bound") is not None and d.get("upper_bound") is not None and d.get("lower_bound") <= d.get("actual_price") <= d.get("upper_bound"))),\n',
    '                        d.get("maximum_favourable_excursion"), d.get("maximum_adverse_excursion"), d.get("target_hit"), d.get("stop_hit"),\n',
    '                        None, None, "Migrated from prediction_ledger_20260617", "", "UNKNOWN", "UNKNOWN", "UNKNOWN", d.get("priority_score"),\n',
    '                        d.get("knn_score"), d.get("greedy_score"), None, status if status in {"PENDING", "SETTLED", "INVALID", "EXCLUDED"} else "PENDING",\n',
    '                        d.get("settled_at"), d.get("created_at") or _utc_now(), d.get("source"), SCHEMA_VERSION,\n',
    '                    ))\n',
    '                if payloads:\n',
    '                    conn.executemany(insert, payloads)\n',
    '        except Exception as exc:\n',
    '            self.last_error = f"legacy backfill: {exc}"\n',
    '\n',
    '    def settle_pending(self, ohlc: pd.DataFrame) -> Dict[str, Any]:\n',
    '        frame = normalize_completed_ohlc(ohlc)\n',
    '        if frame.empty:\n',
    '            return {"ok": False, "settled": 0, "pending": 0, "message": "No completed OHLC rows"}\n',
    '        latest = frame.index.max()\n',
    '        rows = self._execute(\n',
    '            "SELECT * FROM settled_forecast_ledger_v3 WHERE record_status=\'PENDING\' ORDER BY target_time ASC",\n',
    '            fetch=True,\n',
    '        )\n',
    '        settled = invalid = 0\n',
    '        pip = float(TRUST_CONFIG["pip_size"])\n',
    '        for row in rows:\n',
    '            target = _utc(row.get("target_time"))\n',
    '            origin_ts = _utc(row.get("forecast_origin_time"))\n',
    '            if target is None or origin_ts is None:\n',
    '                self._execute(\n',
    '                    "UPDATE settled_forecast_ledger_v3 SET record_status=\'INVALID\',settlement_timestamp=? WHERE calculation_id=? AND horizon=? AND record_status=\'PENDING\'",\n',
    '                    (_utc_now(), row.get("calculation_id"), int(row.get("horizon") or 1)),\n',
    '                )\n',
    '                invalid += 1\n',
    '                continue\n',
    '            if target > latest:\n',
    '                continue\n',
    '            eligible = frame.loc[frame.index >= target]\n',
    '            if eligible.empty:\n',
    '                continue\n',
    '            actual_time = eligible.index[0]\n',
    '            actual = float(eligible.iloc[0]["close"])\n',
    '            origin_price = _finite(row.get("forecast_origin_price"), None)\n',
    '            predicted = _finite(row.get("predicted_close"), None)\n',
    '            if origin_price is None or predicted is None:\n',
    '                self._execute(\n',
    '                    "UPDATE settled_forecast_ledger_v3 SET record_status=\'INVALID\',settlement_timestamp=? WHERE calculation_id=? AND horizon=? AND record_status=\'PENDING\'",\n',
    '                    (_utc_now(), row.get("calculation_id"), int(row.get("horizon") or 1)),\n',
    '                )\n',
    '                invalid += 1\n',
]
