"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    "        if not isinstance(st.session_state.get('lunch_metric_result_cache'), dict):\n",
    '            return\n',
    '        try:\n',
    "            df = st.session_state.get('dv_pp_df')\n",
    '            if not isinstance(df, pd.DataFrame) or df.empty:\n',
    "                clean_f = ns.get('_clean_lunch_visual_df')\n",
    "                df = clean_f(limit=1800) if callable(clean_f) else st.session_state.get('last_df', pd.DataFrame())\n",
    "            result = st.session_state.get('lunch_5layer_powerbi_result', {}) or st.session_state.get('dv_pp_base_result', {})\n",
    "            predicted = st.session_state.get('dv_pp_predicted', pd.DataFrame())\n",
    '            pack = _u11_compute(df, result, predicted, horizon=24)\n',
    "            st.session_state['technical_logic_upgrade_lunch_v20260611'] = pack\n",
    "            _u11_render_cards(pack, 'Lunch')\n",
    '        except Exception as exc:\n',
    "            st.warning(f'Lunch technical upgrade skipped safely: {exc}')\n",
    '\n',
    "    prev_copy = ns.get('_build_lunch_all_copy_text')\n",
    '    def _build_copy_u11():\n',
    "        base = prev_copy() if callable(prev_copy) else ''\n",
    "        extra = st.session_state.get('technical_logic_upgrade_lunch_v20260611') or st.session_state.get('technical_logic_upgrade_v20260611') or {}\n",
    '        safe = {}\n',
    '        try:\n',
    '            for k,v in extra.items():\n',
    "                if isinstance(v, pd.DataFrame): safe[k] = v.head(120).to_dict('records')\n",
    '                else: safe[k] = v\n',
    '        except Exception:\n',
    "            safe = {'summary': str(extra)[:1000]}\n",
    "        return str(base) + '\\n\\nTECHNICAL LOGIC UPGRADE 2026-06-11\\n' + '='*64 + '\\n' + json.dumps(safe, indent=2, ensure_ascii=False, default=str)\n",
    '\n',
    "    prev_finder = ns.get('_render_doo_finder')\n",
    '    def _render_finder_u11(results):\n',
    '        if callable(prev_finder):\n',
    '            prev_finder(results)\n',
    '        try:\n',
    "            st.markdown('### 🔎 Finder Sync — latest Lunch/Data logic')\n",
    "            st.caption('Finder now shows the same priority logic as Lunch for the selected day/hour context when available.')\n",
    "            pack = st.session_state.get('technical_logic_upgrade_lunch_v20260611') or st.session_state.get('technical_logic_upgrade_v20260611')\n",
    '            if isinstance(pack, dict):\n',
    "                _u11_render_cards(pack, 'Finder')\n",
    '            else:\n',
    "                st.info('Run Lunch or Data Visualization calculation first, then Finder mirrors the latest priority metrics.')\n",
    '        except Exception as exc:\n',
    "            st.caption(f'Finder sync skipped safely: {exc}')\n",
    '\n',
    "    ns['_u11_compute_technical_logic'] = _u11_compute\n",
    "    ns['_render_lunch_data_visualization_inner_tab'] = _render_dv_u11\n",
    "    ns['_render_metric_home_combined_inner_tab'] = _render_lunch_u11\n",
    "    ns['_build_lunch_all_copy_text'] = _build_copy_u11\n",
    "    ns['_render_doo_finder'] = _render_finder_u11\n",
]
