"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        st.caption("Lunch tab: Run Calculating first, then Metric table, 010 Reverse Decision, Prediction, NY/London overlap above Copy buttons, then Open/Close fields.")\n',
    '        ns["_render_metric_inner_tab"]()\n',
    '        with st.expander("🏠 Open / Close — Other Lunch fields", expanded=False):\n',
    '            ns["_render_home_dashboard"]()\n',
    '\n',
    '    def _build_last_candle_yellow_6h_projection_v5(d, horizon=6, mode="Balanced", risk_filter="Medium"):\n',
    '        x = _v4_prepare(d)\n',
    '        if x.empty or len(x) < 40:\n',
    '            return pd.DataFrame()\n',
    '        x = x.sort_values("time").copy()\n',
    '        close = pd.to_numeric(x["close"], errors="coerce").ffill()\n',
    '        high = pd.to_numeric(x["high"], errors="coerce").ffill()\n',
    '        low = pd.to_numeric(x["low"], errors="coerce").ffill()\n',
    '        ret = close.pct_change().fillna(0)\n',
    '        atr = (high - low).rolling(14, min_periods=4).mean().ffill().fillna((high - low).mean())\n',
    '        if mode == "Trend follow":\n',
    '            base_ret = float(ret.ewm(span=6, adjust=False).mean().iloc[-1])\n',
    '        elif mode == "Pullback safer":\n',
    '            base_ret = float(ret.ewm(span=12, adjust=False).mean().iloc[-1]) * 0.45\n',
    '        else:\n',
    '            base_ret = float(ret.ewm(span=9, adjust=False).mean().iloc[-1]) * 0.75\n',
    '        risk_mult = {"Low": 0.55, "Medium": 0.80, "High": 1.00}.get(str(risk_filter), 0.80)\n',
    '        base_ret *= risk_mult\n',
    '        last = x.iloc[-1]\n',
    '        last_time = pd.Timestamp(last["time"])\n',
    '        price = float(last["close"])\n',
    '        atr_last = float(atr.iloc[-1] or 0)\n',
    '        rows = []\n',
    '        for step in range(1, int(horizon) + 1):\n',
    '            damp = 1 / (1 + step * 0.10)\n',
    '            pred_close = price * (1 + base_ret * step * damp)\n',
    '            band = atr_last * (0.35 + step * 0.10) * risk_mult\n',
    '            rows.append({\n',
    '                "Future Hour": step,\n',
    '                "time": last_time + pd.Timedelta(hours=step),\n',
    '                "Yellow Predicted Close": round(float(pred_close), 5),\n',
    '                "Lower Risk Band": round(float(pred_close - band), 5),\n',
    '                "Upper Risk Band": round(float(pred_close + band), 5),\n',
    '                "Mode": mode,\n',
    '                "Risk Filter": risk_filter,\n',
    '            })\n',
    '        return pd.DataFrame(rows)\n',
    '\n',
    '    def _render_last_candle_yellow_6h_projection_v5():\n',
    '        d = st.session_state.get("dv_pp_df", pd.DataFrame())\n',
    '        if not isinstance(d, pd.DataFrame) or d.empty:\n',
    '            return\n',
    '        with st.expander("🟡 Open / Close — Last Candle Predict Next 6 Hours Yellow Line", expanded=True):\n',
    '            st.caption("Shows the latest candle’s forward yellow prediction line for the next hours, plus bands for less-risky planning.")\n',
    '            c = st.columns(3)\n',
    '            horizon = c[0].slider("Yellow future hours", 1, 12, int(st.session_state.get("yellow_horizon_v5", 6)), 1, key="yellow_horizon_v5")\n',
    '            mode = c[1].selectbox("Projection choice", ["Balanced", "Trend follow", "Pullback safer"], index=0, key="yellow_mode_v5")\n',
    '            risk_filter = c[2].selectbox("Risk filter", ["Low", "Medium", "High"], index=1, key="yellow_risk_v5")\n',
    '            future = _build_last_candle_yellow_6h_projection_v5(d, horizon=horizon, mode=mode, risk_filter=risk_filter)\n',
    '            if future.empty:\n',
    '                st.info("Need more candles to draw yellow 6-hour projection.")\n',
    '                return\n',
    '            try:\n',
    '                import plotly.graph_objects as go\n',
    '                x = _v4_prepare(d).sort_values("time").tail(80)\n',
    '                fig = go.Figure()\n',
    '                fig.add_trace(go.Candlestick(x=x["time"], open=x["open"], high=x["high"], low=x["low"], close=x["close"], name="Actual candles"))\n',
    '                last_time = pd.Timestamp(x["time"].iloc[-1])\n',
    '                last_close = float(x["close"].iloc[-1])\n',
    '                line_x = [last_time] + list(future["time"])\n',
    '                line_y = [last_close] + list(future["Yellow Predicted Close"])\n',
    '                fig.add_trace(go.Scatter(x=line_x, y=line_y, mode="markers+lines", name="YELLOW next-hours prediction", marker={"color": "yellow", "size": 9, "line": {"color": "#111827", "width": 1}}, line={"color": "#FACC15", "width": 3}))\n',
    '                fig.add_trace(go.Scatter(x=future["time"], y=future["Upper Risk Band"], mode="lines", name="Upper band", line={"color": "rgba(250,204,21,0.35)", "dash": "dot"}))\n',
    '                fig.add_trace(go.Scatter(x=future["time"], y=future["Lower Risk Band"], mode="lines", name="Lower band", line={"color": "rgba(250,204,21,0.35)", "dash": "dot"}))\n',
    '                fig.update_layout(height=560, margin=dict(l=8, r=8, t=42, b=8), title="PowerBI Candle — Last Candle Yellow Next-Hours Projection", xaxis_rangeslider_visible=False, legend=dict(orientation="h"))\n',
    '                st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False, "responsive": True})\n',
    '            except Exception as exc:\n',
    '                st.warning(f"Yellow 6-hour projection chart skipped safely: {exc}")\n',
    '            st.dataframe(future.sort_values("Future Hour"), use_container_width=True, hide_index=True, height=250)\n',
    '\n',
    '    prev_dv_v5 = ns.get("_render_lunch_data_visualization_inner_tab")\n',
    '    def _render_lunch_data_visualization_inner_tab_v5():\n',
    '        if callable(prev_dv_v5):\n',
    '            prev_dv_v5()\n',
    '        if st.session_state.get("lunch_bi_visual_ready", False):\n',
    '            _render_last_candle_yellow_6h_projection_v5()\n',
    '\n',
    '    prev_build_copy_v5 = ns.get("_build_lunch_all_copy_text")\n',
    '    def _build_lunch_all_copy_text_v5():\n',
    '        base = prev_build_copy_v5() if callable(prev_build_copy_v5) else ""\n',
    '        hist = st.session_state.get("ny_london_overlap_hourly_history_v5", pd.DataFrame())\n',
    '        summary = st.session_state.get("ny_london_overlap_hourly_summary_v5", {})\n',
    '        extra = {\n',
    '            "ny_london_overlap_v5_manual_run_summary": summary,\n',
    '            "ny_london_overlap_v5_history_today_to_last_25d_desc": hist.to_dict("records") if isinstance(hist, pd.DataFrame) else [],\n',
    '        }\n',
    '        return str(base) + "\\n\\nNY-LONDON OVERLAP V5 MANUAL-RUN EXPORT\\n" + "=" * 64 + "\\n" + json.dumps(extra, indent=2, ensure_ascii=False, default=str)\n',
    '\n',
    '    ns["_build_ny_london_overlap_hourly_history_v5"] = _build_ny_london_overlap_hourly_history_v5\n',
    '    ns["_render_ny_london_overlap_open_close_field_v5"] = _render_ny_london_overlap_open_close_field_v5\n',
    '    ns["_render_lunch_copy_refresh_bar"] = _render_lunch_copy_refresh_bar_v5\n',
    '    ns["_render_metric_home_combined_inner_tab"] = _render_metric_home_combined_inner_tab_v5\n',
    '    ns["_build_last_candle_yellow_6h_projection_v5"] = _build_last_candle_yellow_6h_projection_v5\n',
    '    ns["_render_lunch_data_visualization_inner_tab"] = _render_lunch_data_visualization_inner_tab_v5\n',
    '    ns["_build_lunch_all_copy_text"] = _build_lunch_all_copy_text_v5\n',
    '\n',
    '# =====================================================================\n',
    '# 2026-06-10 V6 FINAL USER RESTORE PATCH\n',
    '# - Data Visualization: merge the 4 projection displays into ONE PowerBI chart.\n',
    '# - Keep existing ML/result tables and copy export; do not delete old functions.\n',
    '# - NY/London: remove end threshold, use next 6 hours from start with midnight rollover.\n',
    '#   Example start 21 => 21,22,23,00,01,02.\n',
    '# =====================================================================\n',
    'try:\n',
    '    _PREV_APPLY_20260610_V5 = apply\n',
    'except Exception:\n',
    '    _PREV_APPLY_20260610_V5 = None\n',
    '\n',
    '\n',
    'def apply(ns: dict) -> None:  # type: ignore[no-redef]\n',
    '    if callable(_PREV_APPLY_20260610_V5):\n',
    '        _PREV_APPLY_20260610_V5(ns)\n',
    '\n',
    '    import json\n',
    '    import pandas as pd\n',
    '    import streamlit as st\n',
    '\n',
    '    def _v6_prepare(df):\n',
    "        prep = ns.get('_v4_prepare') or ns.get('_dv_prepare_ohlc_v20260609')\n",
    '        try:\n',
    '            if callable(prep):\n',
    '                return prep(df).copy()\n',
    '        except Exception:\n',
    '            pass\n',
    '        if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '            return pd.DataFrame()\n',
    '        cols = {str(c).lower().strip(): c for c in df.columns}\n',
    '        out = pd.DataFrame()\n',
    '        for std, alts in {\n',
    "            'time':['time','datetime','date','timestamp'], 'open':['open','o'], 'high':['high','h'], 'low':['low','l'], 'close':['close','c'], 'volume':['volume','vol','tick_volume']\n",
    '        }.items():\n',
    '            src = next((cols.get(a) for a in alts if cols.get(a) is not None), None)\n',
    '            if src is not None:\n',
    '                out[std] = df[src]\n',
    "        need = ['time','open','high','low','close']\n",
    '        if not all(c in out.columns for c in need):\n',
    '            return pd.DataFrame()\n',
    "        out['time'] = pd.to_datetime(out['time'], errors='coerce')\n",
    "        for c in ['open','high','low','close','volume']:\n",
    '            if c in out.columns:\n',
    "                out[c] = pd.to_numeric(out[c], errors='coerce')\n",
    "        return out.dropna(subset=need).sort_values('time').reset_index(drop=True)\n",
    '\n',
    '    def _v6_pressure(df):\n',
    "        f = ns.get('_pressure_scores_for_rows')\n",
    '        if callable(f):\n',
    '            try:\n',
    '                return f(df).copy()\n',
    '            except Exception:\n',
    '                pass\n',
    '        x = _v6_prepare(df)\n',
    '        if x.empty:\n',
    '            return x\n',
    "        rng = (x['high'] - x['low']).replace(0, pd.NA).ffill().fillna(0.0001)\n",
    "        body = (x['close'] - x['open']) / rng\n",
    '        vol = rng.rolling(14, min_periods=3).mean().replace(0, pd.NA).ffill().fillna(float(rng.mean() or 0.0001))\n',
    '        score = ((rng / vol).clip(0, 2) * 3.0 + body.abs().clip(0, 1) * 4.0 + 2.0).clip(0, 10)\n',
    '        buy = (5 + body.clip(-1, 1) * 4).clip(0, 10)\n',
    '        sell = (5 - body.clip(-1, 1) * 4).clip(0, 10)\n',
    "        x['Entry Pressure /10'] = score.round(2)\n",
    "        x['BUY Pressure /10'] = buy.round(2)\n",
    "        x['SELL Pressure /10'] = sell.round(2)\n",
    "        x['Score /10'] = ((score + buy.where(buy >= sell, sell)) / 2).round(2)\n",
    '        return x\n',
    '\n',
    '    def _nylo_decision_v6(score, entry, buy, sell):\n',
    '        score = float(score or 0); entry = float(entry or 0)\n',
    '        edge = abs(float(buy or 0) - float(sell or 0))\n',
    '        if score >= 7.2 and entry >= 6.8 and edge >= 0.55:\n',
    "            return 'ALLOWED'\n",
    '        if score >= 5.8 and entry >= 5.6:\n',
    "            return 'WAIT PULLBACK'\n",
    '        if score >= 4.4:\n',
    "            return 'HOLD'\n",
    "        return 'NO TRADE'\n",
    '\n',
    '    def _build_ny_london_overlap_hourly_history_v6(df=None, days=25, start_hour=21):\n',
    '        sh = int(start_hour or 21) % 24\n',
    '        hours = [int((sh + i) % 24) for i in range(6)]\n',
    "        raw = st.session_state.get('last_df') if df is None else df\n",
    '        d = _v6_pressure(raw)\n',
    '        if d.empty:\n',
    "            return pd.DataFrame(), {'ok': False, 'message': 'No clean EURUSD OHLC candles found.'}\n",
    "        d['HourNum'] = pd.to_datetime(d['time'], errors='coerce').dt.hour.astype('Int64')\n",
    "        last_time = pd.Timestamp(d['time'].max())\n",
    '        cutoff = last_time - pd.Timedelta(days=int(days) + 2)\n',
    "        x = d[d['time'].ge(cutoff) & d['HourNum'].isin(hours)].copy()\n",
    '        if x.empty:\n',
    "            label = ', '.join(f'{h:02d}:00' for h in hours)\n",
    "            return pd.DataFrame(), {'ok': False, 'message': f'No EURUSD candles inside next-6-hour window: {label}.'}\n",
    "        x['Day'] = pd.to_datetime(x['time']).dt.strftime('%Y-%m-%d %a')\n",
    "        x['Hour'] = pd.to_datetime(x['time']).dt.strftime('%H:00')\n",
    "        x['Window Order'] = x['HourNum'].map({h: i+1 for i, h in enumerate(hours)})\n",
    "        x['NY/London Alignment'] = x.apply(lambda r: 'BUY aligned' if r['BUY Pressure /10'] >= r['SELL Pressure /10'] + 0.55 else 'SELL aligned' if r['SELL Pressure /10'] >= r['BUY Pressure /10'] + 0.55 else 'Mixed / wait', axis=1)\n",
    "        x['Decision'] = x.apply(lambda r: _nylo_decision_v6(r['Score /10'], r['Entry Pressure /10'], r['BUY Pressure /10'], r['SELL Pressure /10']), axis=1)\n",
    "        x['Risk Note'] = x.apply(lambda r: 'Lower risk only after pullback confirmation' if r['Decision'] == 'WAIT PULLBACK' else 'Allowed by 6-hour pressure window' if r['Decision'] == 'ALLOWED' else 'Protect open position / avoid adding' if r['Decision'] == 'HOLD' else 'No trade: pressure weak', axis=1)\n",
    "        out = x.sort_values('time', ascending=False)[['Day','Hour','Window Order','Entry Pressure /10','BUY Pressure /10','SELL Pressure /10','Score /10','NY/London Alignment','Decision','Risk Note','open','high','low','close']].rename(columns={'open':'Open','high':'High','low':'Low','close':'Close'})\n",
    "        for col in ['Open','High','Low','Close']:\n",
    "            out[col] = pd.to_numeric(out[col], errors='coerce').round(5)\n",
    '        summary = {\n',
    "            'ok': True,\n",
    "            'rows': int(len(out)),\n",
    "            'start_threshold_hour': f'{sh:02d}:00',\n",
    "            'next_6_hours': ', '.join(f'{h:02d}:00' for h in hours),\n",
    "            'latest_score_10': float(out['Score /10'].iloc[0]),\n",
    "            'latest_decision': str(out['Decision'].iloc[0]),\n",
    "            'latest_alignment': str(out['NY/London Alignment'].iloc[0]),\n",
    "            'avg_entry_pressure_10': round(float(pd.to_numeric(out['Entry Pressure /10'], errors='coerce').mean()), 2),\n",
    "            'avg_buy_pressure_10': round(float(pd.to_numeric(out['BUY Pressure /10'], errors='coerce').mean()), 2),\n",
    "            'avg_sell_pressure_10': round(float(pd.to_numeric(out['SELL Pressure /10'], errors='coerce').mean()), 2),\n",
    '        }\n',
    '        return out.reset_index(drop=True), summary\n',
    '\n',
    '    def _render_ny_london_overlap_open_close_field_v6():\n',
    "        with st.expander('🌍 Open / Close — NY + London Next 6 Hours From Start Threshold', expanded=False):\n",
    "            st.caption('Manual-run only. End threshold was removed. Choose the start hour and the table continues for the next 6 hours across midnight, e.g. 21 → 21,22,23,00,01,02.')\n",
    '            c = st.columns([1.15, .75, .9])\n',
    '            with c[0]:\n',
    "                run = st.button('▶ Run NY/London Overlap Calculation', use_container_width=True, key='nylo_run_hourly_v6')\n",
    '            with c[1]:\n',
    "                days = st.slider('Days', 5, 25, int(st.session_state.get('nylo_days_v6', 25)), 1, key='nylo_days_v6')\n",
    '            with c[2]:\n',
    "                start_h = st.slider('Start threshold hour', 0, 23, int(st.session_state.get('nylo_start_h_v6', 21)), 1, key='nylo_start_h_v6')\n",
    "            st.caption('Selected next 6 hours: ' + ', '.join(f'{(int(start_h)+i)%24:02d}:00' for i in range(6)))\n",
    '            if run:\n',
    '                hist, summary = _build_ny_london_overlap_hourly_history_v6(days=days, start_hour=start_h)\n',
    "                st.session_state['ny_london_overlap_hourly_history_v6'] = hist\n",
    "                st.session_state['ny_london_overlap_hourly_summary_v6'] = summary\n",
    "                st.session_state['lunch_copy_payload_signature'] = None\n",
    "                if summary.get('ok'):\n",
    "                    st.success('NY/London next-6-hour calculation complete.')\n",
    "            hist = st.session_state.get('ny_london_overlap_hourly_history_v6', pd.DataFrame())\n",
    "            summary = st.session_state.get('ny_london_overlap_hourly_summary_v6', {})\n",
    '            if not isinstance(hist, pd.DataFrame) or hist.empty:\n',
    "                st.info('Press Run NY/London Overlap Calculation. This section does not calculate automatically when the tab opens.')\n",
    "                if isinstance(summary, dict) and summary.get('message'):\n",
    "                    st.warning(summary.get('message'))\n",
    '                return\n',
    '            m = st.columns(6)\n',
    "            m[0].metric('Start', summary.get('start_threshold_hour', '-'))\n",
    "            m[1].metric('Next 6H', summary.get('next_6_hours', '-'))\n",
    '            m[2].metric(\'Latest Score\', f"{summary.get(\'latest_score_10\',\'-\')}/10")\n',
    "            m[3].metric('Decision', summary.get('latest_decision', '-'))\n",
    '            m[4].metric(\'Avg BUY\', f"{summary.get(\'avg_buy_pressure_10\',\'-\')}/10")\n',
    '            m[5].metric(\'Avg SELL\', f"{summary.get(\'avg_sell_pressure_10\',\'-\')}/10")\n',
    '            st.dataframe(hist, use_container_width=True, hide_index=True, height=460)\n',
    '\n',
    "    def _v6_yellow_from_anchor(d, anchor_idx, horizon=6, mode='Balanced', risk_filter='Medium'):\n",
    "        build = ns.get('_build_last_candle_yellow_6h_projection_v5')\n",
    '        x = _v6_prepare(d)\n',
    '        if x.empty or anchor_idx < 20:\n',
    '            return pd.DataFrame()\n',
    '        sub = x.iloc[:anchor_idx+1].copy()\n',
    '        if callable(build):\n',
    '            try:\n',
    '                return build(sub, horizon=horizon, mode=mode, risk_filter=risk_filter)\n',
    '            except Exception:\n',
    '                pass\n',
    "        close = sub['close'].astype(float); high = sub['high'].astype(float); low = sub['low'].astype(float)\n",
    '        ret = close.pct_change().fillna(0)\n',
    '        base_ret = float(ret.ewm(span=9, adjust=False).mean().iloc[-1]) * 0.75\n',
    "        risk_mult = {'Low':0.55, 'Medium':0.80, 'High':1.00}.get(str(risk_filter), 0.80)\n",
    "        last_time = pd.Timestamp(sub['time'].iloc[-1]); price = float(close.iloc[-1])\n",
    '        atr = float((high-low).rolling(14, min_periods=4).mean().ffill().iloc[-1] or 0)\n',
    '        rows=[]\n',
    '        for step in range(1, int(horizon)+1):\n',
    '            pred = price * (1 + base_ret * step / (1 + step*.1) * risk_mult)\n',
    '            band = atr * (.35 + step*.10) * risk_mult\n',
    "            rows.append({'Future Hour':step, 'time':last_time+pd.Timedelta(hours=step), 'Yellow Predicted Close':round(pred,5), 'Lower Risk Band':round(pred-band,5), 'Upper Risk Band':round(pred+band,5)})\n",
    '        return pd.DataFrame(rows)\n',
    '\n',
    "    def _v6_today_finished_yellow_paths(d, horizon=6, mode='Balanced', risk_filter='Medium'):\n",
    '        x = _v6_prepare(d)\n',
    '        if x.empty:\n',
    '            return pd.DataFrame()\n',
    "        today = pd.Timestamp(x['time'].max()).date()\n",
    "        idxs = list(x.index[pd.to_datetime(x['time']).dt.date == today])\n",
    '        rows = []\n',
    '        for idx in idxs[:-1]:\n',
    '            fut = _v6_yellow_from_anchor(x, int(idx), horizon=horizon, mode=mode, risk_filter=risk_filter)\n',
    '            if isinstance(fut, pd.DataFrame) and not fut.empty:\n',
    "                fut = fut.copy(); fut['Anchor Time'] = pd.Timestamp(x.loc[idx, 'time']); rows.append(fut)\n",
    '        return pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()\n',
    '\n',
    "    def _render_unified_powerbi_projection_chart_v6(d, predicted, result=None, regime=None, horizon=24, yellow_horizon=6, mode='Balanced', risk_filter='Medium'):\n",
    '        """Render one calibrated PowerBI chart from existing source projections.\n',
    '\n',
    '        No model is added here.  Existing BLUE/model, YELLOW/current and\n',
    '        previous-candle paths are reliability-weighted using completed backtest\n',
    '        error, regime reliability and cross-path agreement.\n',
    '        """\n',
    '        try:\n',
    '            import plotly.graph_objects as go\n',
    '        except Exception as exc:\n',
    "            st.warning(f'Plotly unavailable for unified PowerBI chart: {exc}')\n",
    '            return\n',
    '        x = _v6_prepare(d)\n',
    '        if x.empty:\n',
    "            st.info('No clean OHLC data for unified projection chart.')\n",
    '            return\n',
    '        view = x.tail(130).copy()\n',
    '        latest_yellow = _v6_yellow_from_anchor(x, len(x)-1, horizon=min(int(yellow_horizon), int(horizon)), mode=mode, risk_filter=risk_filter)\n',
    '        previous_yellow = _v6_yellow_from_anchor(x, len(x)-2, horizon=min(int(yellow_horizon), int(horizon)), mode=mode, risk_filter=risk_filter) if len(x) > 2 else pd.DataFrame()\n',
    '\n',
    '        regime_reliability = None\n',
    '        if isinstance(regime, dict):\n',
    "            regime_reliability = regime.get('reliability') or regime.get('regime_reliability') or regime.get('Regime Reliability')\n",
    '        try:\n',
    '            from core.powerbi_path_calibration_20260617 import calibrate_projection_bundle\n',
    '            calibration = calibrate_projection_bundle(\n',
    '                x,\n',
    '                red=predicted if isinstance(predicted, pd.DataFrame) else pd.DataFrame(),\n',
    '                yellow=latest_yellow,\n',
    '                blue=previous_yellow,\n',
    '                horizon=min(int(horizon), 24),\n',
    "                bt_history=st.session_state.get('dv_pp_bt_hist', pd.DataFrame()),\n",
    "                bt_summary=st.session_state.get('dv_pp_bt_summary', {}),\n",
    '                regime_reliability=regime_reliability,\n',
    '            )\n',
    '        except Exception as exc:\n',
    "            calibration = {'ok': False, 'message': str(exc)}\n",
    "        st.session_state['powerbi_calibrated_bundle_20260617'] = calibration\n",
    "        main = calibration.get('main', pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n",
    "        red_path = calibration.get('red', pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n",
    "        yellow_path = calibration.get('yellow', pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n",
    "        blue_path = calibration.get('blue', pd.DataFrame()) if isinstance(calibration, dict) else pd.DataFrame()\n",
    "        summary = calibration.get('summary', {}) if isinstance(calibration, dict) else {}\n",
    '\n',
    '        if isinstance(summary, dict) and summary:\n',
    '            mc = st.columns(4)\n',
    '            mc[0].metric(\'Path Reliability\', f"{float(summary.get(\'reliability_pct\', 0) or 0):.1f}%")\n',
    '            mc[1].metric(\'Path Agreement\', f"{float(summary.get(\'path_agreement_pct\', 0) or 0):.1f}%")\n',
    '            mc[2].metric(\'Estimated Band Coverage\', f"{float(summary.get(\'estimated_band_coverage_pct\', 0) or 0):.1f}%")\n',
    '            mc[3].metric(\'Validated Error\', f"{float(summary.get(\'median_abs_error_pct\', 0) or 0):.5f}%", f"{int(summary.get(\'error_samples\', 0) or 0)} samples" + (\' • proxy\' if summary.get(\'error_is_proxy\') else \' • actual\'))\n',
    '\n',
    '        fig = go.Figure()\n',
    "        fig.add_trace(go.Candlestick(x=view['time'], open=view['open'], high=view['high'], low=view['low'], close=view['close'], name='Actual candles'))\n",
    "        last_time = pd.Timestamp(x['time'].iloc[-1])\n",
    "        last_close = float(x['close'].iloc[-1])\n",
    '\n',
    '        if isinstance(main, pd.DataFrame) and not main.empty:\n',
    "            fig.add_trace(go.Scatter(x=main['time'], y=main['upper_band'], mode='lines', name='Calibrated upper band', line={'color':'rgba(124,58,237,.46)','dash':'dash'}))\n",
    "            fig.add_trace(go.Scatter(x=main['time'], y=main['lower_band'], mode='lines', name='Calibrated lower band', line={'color':'rgba(124,58,237,.46)','dash':'dash'}, fill='tonexty', fillcolor='rgba(124,58,237,.10)'))\n",
    "            fig.add_trace(go.Scatter(x=[last_time]+list(main['time']), y=[last_close]+list(main['main_path']), mode='lines+markers', name='MAIN reliability-weighted path', line={'color':'#111827','width':5,'shape':'spline','smoothing':1.0}, marker={'size':7}))\n",
    '\n',
    '        if isinstance(red_path, pd.DataFrame) and not red_path.empty:\n',
    "            fig.add_trace(go.Scatter(x=[last_time]+list(red_path['time']), y=[last_close]+list(red_path['red_path']), mode='lines+markers', name='RED calibrated model path', line={'color':'#DC2626','width':3}, marker={'size':5}))\n",
    '        if isinstance(yellow_path, pd.DataFrame) and not yellow_path.empty:\n',
    "            fig.add_trace(go.Scatter(x=[last_time]+list(yellow_path['time']), y=[last_close]+list(yellow_path['yellow_path']), mode='lines+markers', name='YELLOW calibrated current path', line={'color':'#FACC15','width':4}, marker={'color':'#FACC15','size':8}))\n",
    '        if isinstance(blue_path, pd.DataFrame) and not blue_path.empty:\n',
    "            fig.add_trace(go.Scatter(x=[last_time]+list(blue_path['time']), y=[last_close]+list(blue_path['blue_path']), mode='lines+markers', name='BLUE calibrated previous path', line={'color':'#2563EB','width':3,'dash':'dot'}, marker={'color':'#2563EB','size':6}))\n",
    '\n',
    '        # Keep the useful completed intraday yellow history, but visually mute it\n',
    '        # so the current calibrated paths remain easy to read on phone screens.\n',
    '        today_paths = _v6_today_finished_yellow_paths(x, horizon=yellow_horizon, mode=mode, risk_filter=risk_filter)\n',
    '        if not today_paths.empty:\n',
    "            for anchor, grp in today_paths.groupby('Anchor Time'):\n",
    "                showleg = bool(anchor == today_paths['Anchor Time'].min())\n",
    "                fig.add_trace(go.Scatter(x=grp['time'], y=grp['Yellow Predicted Close'], mode='lines', name='YELLOW completed intraday paths' if showleg else 'completed path', showlegend=showleg, line={'color':'rgba(250,204,21,.24)','width':1.2}))\n",
    '\n',
    "        title_bits = ['PowerBI Price Prediction Projection: calibrated MAIN + bands + RED/YELLOW/BLUE']\n",
    '        if isinstance(result, dict):\n',
    '            title_bits.append(f"Master {result.get(\'master_score\',\'-\')}/10 Bull {result.get(\'bull_probability\',\'-\')}%")\n',
    '        if isinstance(regime, dict):\n',
    "            title_bits.append(str(regime.get('current_regime','')))\n",
    "        fig.update_layout(height=720, margin=dict(l=8,r=8,t=58,b=8), title=' | '.join([b for b in title_bits if b]), xaxis_rangeslider_visible=False, legend=dict(orientation='h'))\n",
    "        st.plotly_chart(fig, use_container_width=True, config={'displayModeBar': False, 'responsive': True})\n",
    '\n',
    '    def _safe_json_v6(obj):\n',
    '        try:\n',
    '            if isinstance(obj, pd.DataFrame):\n',
    "                return obj.tail(60).to_dict('records')\n",
    '            if isinstance(obj, pd.Series):\n',
    '                return obj.to_dict()\n',
    '            if isinstance(obj, pd.Timestamp):\n',
    '                return str(obj)\n',
    '            if isinstance(obj, dict):\n',
    '                return {str(k): _safe_json_v6(v) for k, v in obj.items()}\n',
    '            if isinstance(obj, (list, tuple)):\n',
    '                return [_safe_json_v6(x) for x in obj[:80]]\n',
    '            return obj\n',
    '        except Exception:\n',
    '            return str(obj)\n',
    '\n',
    '    def _render_data_visualization_v6():\n',
    "        apply_css = ns.get('_apply_v28_mobile_cpu_ram_css')\n",
    '        if callable(apply_css):\n',
    '            try: apply_css()\n',
    '            except Exception: pass\n',
    "        st.markdown('### 📊 Data Visualization — One Unified PowerBI Price Projection')\n",
    "        st.caption('Manual-run only. The four projection visuals are combined into one chart; ML tables/copy exports remain below.')\n",
    '        c = st.columns([1.1,.72,.72,.72,.72,.72])\n',
    '        with c[0]:\n',
    "            run = st.button('▶ Run Calculating', use_container_width=True, key='dv_run_calculating_v6')\n",
    '        with c[1]:\n',
    "            rows_limit = st.slider('Rows used', 800, 12000, int(st.session_state.get('dv_pp_rows_v6', 6000)), 400, key='dv_pp_rows_v6')\n",
    '        with c[2]:\n',
    "            horizon = st.slider('Future candles', 6, 60, int(st.session_state.get('dv_pp_horizon_v6', 24)), 6, key='dv_pp_horizon_v6')\n",
    '        with c[3]:\n',
    "            yellow_h = st.slider('Yellow prev hours', 1, 12, int(st.session_state.get('yellow_horizon_v6', 6)), 1, key='yellow_horizon_v6')\n",
    '        with c[4]:\n',
    "            mode = st.selectbox('Projection choice', ['Balanced','Trend follow','Pullback safer'], index=0, key='yellow_mode_v6')\n",
    '        with c[5]:\n',
    "            risk_filter = st.selectbox('Risk filter', ['Low','Medium','High'], index=1, key='yellow_risk_v6')\n",
    '        more = st.columns(3)\n',
    '        with more[0]:\n',
    "            min_days = st.slider('Regime min days', 3, 21, int(st.session_state.get('dv_pp_min_days_v6', 5)), 1, key='dv_pp_min_days_v6')\n",
    '        with more[1]:\n',
    "            bt_lookback = st.slider('Backtest summary bars', 60, 360, int(st.session_state.get('dv_pp_bt_v6', 180)), 20, key='dv_pp_bt_v6')\n",
    '        with more[2]:\n',
    "            chart_density = st.selectbox('Chart detail', ['Fast','Balanced','Full'], index=1, key='dv_chart_detail_v6')\n",
    '        if run:\n',
    "            st.session_state['lunch_bi_visual_ready'] = True\n",
    "            with st.spinner('Calculating unified PowerBI projection and ML tables…'):\n",
    "                clean_f = ns.get('_clean_lunch_visual_df')\n",
]
