"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    "                clean = clean_f(limit=rows_limit) if callable(clean_f) else st.session_state.get('last_df', pd.DataFrame())\n",
    "                prep_f = ns.get('_dv_prepare_ohlc_v20260609')\n",
    '                d = prep_f(clean, limit=rows_limit) if callable(prep_f) else _v6_prepare(clean).tail(rows_limit)\n',
    '                d = _v6_prepare(d)\n',
    '                if not isinstance(d, pd.DataFrame) or d.empty or len(d) < 120:\n',
    "                    st.warning('Need at least 120 clean OHLC candles. Refresh/connect data first.')\n",
    "                    ns['_render_lunch_copy_refresh_bar']()\n",
    '                    return\n',
    "                result = ns['_five_layer_powerbi_calculate'](d, horizon=horizon) if callable(ns.get('_five_layer_powerbi_calculate')) else {}\n",
    "                predicted = ns['_dv_predict_future_candles_v20260609'](d, horizon=horizon) if callable(ns.get('_dv_predict_future_candles_v20260609')) else pd.DataFrame()\n",
    "                bt_hist, bt_summary = ns['_dv_prediction_vs_actual_history_v20260609'](d, lookback=bt_lookback, horizon=1) if callable(ns.get('_dv_prediction_vs_actual_history_v20260609')) else (pd.DataFrame(), {})\n",
    "                regime, regime_hist = ns['_dv_major_regime_detector_v20260609'](d, min_days=float(min_days), lookback_days=240, horizon=horizon) if callable(ns.get('_dv_major_regime_detector_v20260609')) else ({}, pd.DataFrame())\n",
    "                light_path = ns['_dv_build_lightblue_path_v20260609'](ns['_dv_last_continuous_days_v20260609'](d, days=10), predicted) if callable(ns.get('_dv_build_lightblue_path_v20260609')) and callable(ns.get('_dv_last_continuous_days_v20260609')) else pd.DataFrame()\n",
    "                st.session_state.update({'dv_pp_df': d, 'dv_pp_base_result': result, 'dv_pp_predicted': predicted, 'dv_pp_bt_summary': bt_summary, 'dv_pp_bt_hist': bt_hist, 'dv_pp_regime_summary': regime, 'dv_pp_regime_hist': regime_hist, 'dv_pp_lightblue_path': light_path, 'lunch_5layer_powerbi_result': result, 'lunch_5layer_powerbi_df': d})\n",
    "            st.success('Unified Data Visualization result is ready.')\n",
    "        if not st.session_state.get('lunch_bi_visual_ready', False):\n",
    "            st.info('Press Run Calculating first. No heavy price projection runs when the tab opens.')\n",
    "            ns['_render_lunch_copy_refresh_bar']()\n",
    '            return\n',
    "        d = st.session_state.get('dv_pp_df', pd.DataFrame())\n",
    "        result = st.session_state.get('dv_pp_base_result', {})\n",
    "        predicted = st.session_state.get('dv_pp_predicted', pd.DataFrame())\n",
    "        regime = st.session_state.get('dv_pp_regime_summary', {})\n",
    "        bt_summary = st.session_state.get('dv_pp_bt_summary', {})\n",
    "        bt_hist = st.session_state.get('dv_pp_bt_hist', pd.DataFrame())\n",
    "        regime_hist = st.session_state.get('dv_pp_regime_hist', pd.DataFrame())\n",
    '        cards = st.columns(6)\n',
    '        cards[0].metric(\'Master\', f"{result.get(\'master_score\',\'-\')}/10" if isinstance(result, dict) else \'-\')\n',
    '        cards[1].metric(\'Bull\', f"{result.get(\'bull_probability\',\'-\')}%" if isinstance(result, dict) else \'-\')\n',
    "        cards[2].metric('Regime', regime.get('current_regime','-') if isinstance(regime, dict) else '-')\n",
    "        cards[3].metric('Days In', regime.get('days_since_last_change', regime.get('days_since_change','-')) if isinstance(regime, dict) else '-')\n",
    "        cards[4].metric('Days Left', regime.get('estimated_days_remaining', regime.get('estimated_days_left','-')) if isinstance(regime, dict) else '-')\n",
    '        cards[5].metric(\'BT Dir Acc\', f"{bt_summary.get(\'direction_accuracy_pct\',0)}%" if isinstance(bt_summary, dict) else \'-\')\n',
    '        _render_unified_powerbi_projection_chart_v6(d, predicted, result, regime, horizon=horizon, yellow_horizon=yellow_h, mode=mode, risk_filter=risk_filter)\n',
    "        with st.expander('🧠 ML Tables — kept from original 5-layer PowerBI', expanded=False):\n",
    '            if isinstance(result, dict):\n',
    "                for label, key in [('Prediction Ensemble Voting', 'vote_df'), ('Deep AI Table', 'deep_df'), ('Forecast Engine Table', 'forecast_df'), ('History / Layer Table', 'history')]:\n",
    '                    val = result.get(key)\n',
    '                    if isinstance(val, pd.DataFrame) and not val.empty:\n',
    "                        st.markdown('#### ' + label)\n",
    '                        st.dataframe(val, use_container_width=True, hide_index=True, height=260)\n',
    "                st.markdown('#### Summary JSON')\n",
    "                st.json(_safe_json_v6({k:v for k,v in result.items() if k not in {'vote_df','deep_df','forecast_df','history'}}))\n",
    "        with st.expander('Open / Close — Future Candle + Previous Prediction Tables', expanded=False):\n",
    '            if isinstance(predicted, pd.DataFrame) and not predicted.empty:\n',
    "                st.markdown('#### BLUE new future prediction candles')\n",
    '                st.dataframe(predicted, use_container_width=True, hide_index=True, height=260)\n',
    '            latest_yellow = _v6_yellow_from_anchor(d, len(_v6_prepare(d))-1, horizon=yellow_h, mode=mode, risk_filter=risk_filter)\n',
    '            if not latest_yellow.empty:\n',
    "                st.markdown('#### YELLOW latest candle predicted path')\n",
    '                st.dataframe(latest_yellow, use_container_width=True, hide_index=True, height=230)\n',
    '            today_paths = _v6_today_finished_yellow_paths(d, horizon=yellow_h, mode=mode, risk_filter=risk_filter)\n',
    '            if not today_paths.empty:\n',
    "                st.markdown('#### YELLOW all today finished predicted paths')\n",
    '                st.dataframe(today_paths.tail(120), use_container_width=True, hide_index=True, height=300)\n',
    '            if isinstance(bt_hist, pd.DataFrame) and not bt_hist.empty:\n',
    "                st.markdown('#### Prediction vs actual history')\n",
    '                st.dataframe(bt_hist, use_container_width=True, hide_index=True, height=300)\n',
    "        with st.expander('Open / Close — Smooth Regime History', expanded=False):\n",
    '            if isinstance(regime, dict):\n',
    '                st.json(_safe_json_v6(regime))\n',
    '            if isinstance(regime_hist, pd.DataFrame) and not regime_hist.empty:\n',
    '                st.dataframe(regime_hist, use_container_width=True, hide_index=True, height=320)\n',
    "        with st.expander('📋 Data Visualization Copy Export — unified projection', expanded=True):\n",
    '            latest_yellow = _v6_yellow_from_anchor(d, len(_v6_prepare(d))-1, horizon=yellow_h, mode=mode, risk_filter=risk_filter)\n',
    '            today_paths = _v6_today_finished_yellow_paths(d, horizon=yellow_h, mode=mode, risk_filter=risk_filter)\n',
    "            payload = {'export_type':'DATA_VISUALIZATION_UNIFIED_4_PROJECTIONS_NO_MISSING_ML_TABLES', 'built_at':str(pd.Timestamp.now()), 'powerbi_ml_summary':_safe_json_v6({k:v for k,v in (result or {}).items() if k not in {'vote_df','deep_df','forecast_df','history'}} if isinstance(result, dict) else {}), 'regime_summary':_safe_json_v6(regime), 'prediction_backtest_summary_only':_safe_json_v6(bt_summary), 'blue_new_future_prediction':_safe_json_v6(predicted if isinstance(predicted, pd.DataFrame) else pd.DataFrame()), 'yellow_latest_candle_next_path':_safe_json_v6(latest_yellow), 'yellow_all_today_finished_predicted_paths_tail':_safe_json_v6(today_paths.tail(120) if isinstance(today_paths, pd.DataFrame) else pd.DataFrame())}\n",
    '            text = json.dumps(payload, indent=2, ensure_ascii=False, default=str)\n',
    "            st.session_state['lunch_visualization_export'] = text\n",
    '            try:\n',
    '                from core.pro_terminal_uiux import render_mobile_copy_button\n',
    "                render_mobile_copy_button('Copy Unified Data Visualization', text, 'copy_data_visualization_unified_v6')\n",
    '            except Exception:\n',
    "                st.text_area('Unified Data Visualization Copy', text, height=260)\n",
    "        ns['_render_lunch_copy_refresh_bar']()\n",
    '\n',
    '    def _render_lunch_copy_refresh_bar_v6():\n',
    '        _render_ny_london_overlap_open_close_field_v6()\n',
    "        base = ns.get('_render_lunch_copy_refresh_bar_no_overlap_v4')\n",
    '        if callable(base):\n',
    '            base()\n',
    '        else:\n',
    "            prev = globals().get('_render_lunch_copy_refresh_bar_no_overlap_v4')\n",
    '            if callable(prev): prev()\n',
    '\n',
    "    prev_copy_v6 = ns.get('_build_lunch_all_copy_text')\n",
    '    def _build_lunch_all_copy_text_v6():\n',
    "        base = prev_copy_v6() if callable(prev_copy_v6) else ''\n",
    "        hist = st.session_state.get('ny_london_overlap_hourly_history_v6', pd.DataFrame())\n",
    "        summary = st.session_state.get('ny_london_overlap_hourly_summary_v6', {})\n",
    "        extra = {'ny_london_next_6h_from_start_threshold_summary': summary, 'ny_london_next_6h_history_today_to_last_25d_desc': hist.to_dict('records') if isinstance(hist, pd.DataFrame) else []}\n",
    "        return str(base) + '\\n\\nNY-LONDON NEXT-6H START-THRESHOLD EXPORT\\n' + '='*64 + '\\n' + json.dumps(extra, indent=2, ensure_ascii=False, default=str)\n",
    '\n',
    "    ns['_build_ny_london_overlap_hourly_history_v6'] = _build_ny_london_overlap_hourly_history_v6\n",
    "    ns['_render_ny_london_overlap_open_close_field_v6'] = _render_ny_london_overlap_open_close_field_v6\n",
    "    ns['_render_unified_powerbi_projection_chart_v6'] = _render_unified_powerbi_projection_chart_v6\n",
    "    ns['_render_lunch_data_visualization_inner_tab'] = _render_data_visualization_v6\n",
    "    ns['_render_lunch_copy_refresh_bar'] = _render_lunch_copy_refresh_bar_v6\n",
    "    ns['_build_lunch_all_copy_text'] = _build_lunch_all_copy_text_v6\n",
    '\n',
    '# 2026-06-10 V7 tiny copy-bar safety patch: keep only V6 NY block + original two copy buttons.\n',
    'try:\n',
    '    _PREV_APPLY_20260610_V6 = apply\n',
    'except Exception:\n',
    '    _PREV_APPLY_20260610_V6 = None\n',
    '\n',
    '\n',
    'def apply(ns: dict) -> None:  # type: ignore[no-redef]\n',
    '    if callable(_PREV_APPLY_20260610_V6):\n',
    '        _PREV_APPLY_20260610_V6(ns)\n',
    '    import streamlit as st\n',
    '    import pandas as pd\n',
    '    import json\n',
    '\n',
    '    def _render_lunch_copy_refresh_bar_v7():\n',
    "        render_ny = ns.get('_render_ny_london_overlap_open_close_field_v6')\n",
    '        if callable(render_ny):\n',
    '            render_ny()\n',
    '        try:\n',
    '            from core.pro_terminal_uiux import render_mobile_copy_button, apply_pro_terminal_css\n',
    '            apply_pro_terminal_css()\n',
    '        except Exception:\n',
    '            render_mobile_copy_button = None\n',
    '        try:\n',
    "            all_payload = ns.get('_get_cached_lunch_copy_payload', lambda: ns.get('_build_lunch_all_copy_text', lambda: '')())()\n",
    '        except Exception:\n',
    "            all_payload = ns.get('_build_lunch_all_copy_text', lambda: '')()\n",
    "        short_payload = ns.get('_build_short_necessary_copy_text', lambda: 'No short copy available.')()\n",
    "        st.markdown('### 📋 Copy Center')\n",
    '        a, b, c = st.columns([1, 1, .75])\n',
    '        with a:\n',
    '            if render_mobile_copy_button:\n',
    "                render_mobile_copy_button('Copy Short', short_payload, 'copy_short_v7_next6')\n",
    '            else:\n',
    "                st.text_area('Copy Short', short_payload, height=160)\n",
    '        with b:\n',
    '            if render_mobile_copy_button:\n',
    "                render_mobile_copy_button('Copy Full', all_payload, 'copy_full_v7_next6')\n",
    '            else:\n',
    "                st.text_area('Copy Full', all_payload, height=220)\n",
    '        with c:\n',
    "            if st.button('🔄 Refresh', use_container_width=True, key='refresh_copy_v7_next6'):\n",
    "                st.session_state['lunch_copy_payload_signature'] = None\n",
    '                st.rerun()\n',
    '\n',
    "    ns['_render_lunch_copy_refresh_bar'] = _render_lunch_copy_refresh_bar_v7\n",
    '\n',
    '# =====================================================================\n',
    '# 2026-06-11 ADDITIVE TECHNICAL LOGIC UPGRADE\n',
    '# Regime-vs-Prediction conflict, MTF regime, forecast agreement,\n',
    '# reliability history, probability cone, market quality, counter-trend\n',
    '# labels, regional expectation cards, Finder sync. Existing tables/charts,\n',
    '# copy buttons, ML tables and functions are not removed or renamed.\n',
    '# =====================================================================\n',
    'try:\n',
    '    _PREV_APPLY_20260611_TECH = apply\n',
    'except Exception:\n',
    '    _PREV_APPLY_20260611_TECH = None\n',
    '\n',
    '\n',
    'def apply(ns: dict) -> None:  # type: ignore[no-redef]\n',
    '    if callable(_PREV_APPLY_20260611_TECH):\n',
    '        _PREV_APPLY_20260611_TECH(ns)\n',
    '\n',
    '    import json\n',
    '    import math\n',
    '    import numpy as np\n',
    '    import pandas as pd\n',
    '    import streamlit as st\n',
    '\n',
    '    def _u11_num(v, default=0.0):\n',
    '        try:\n',
    '            x = float(v)\n',
    '            return x if math.isfinite(x) else float(default)\n',
    '        except Exception:\n',
    '            return float(default)\n',
    '\n',
    '    def _u11_prepare(df, limit=1800):\n',
    "        prep = ns.get('_dv_prepare_ohlc_v20260609') or ns.get('_v6_prepare')\n",
    '        try:\n',
    '            if callable(prep):\n',
    "                return prep(df, limit=limit) if prep.__name__.endswith('20260609') else prep(df).tail(limit)\n",
    '        except Exception:\n',
    '            pass\n',
    '        if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '            return pd.DataFrame()\n',
    '        x = df.copy().tail(int(limit)).reset_index(drop=True)\n',
    "        ren = {'datetime':'time','date':'time','timestamp':'time','o':'open','h':'high','l':'low','c':'close'}\n",
    '        low = {str(c).lower(): c for c in x.columns}\n',
    '        for a,b in ren.items():\n',
    '            if a in low and b not in x.columns:\n',
    '                x = x.rename(columns={low[a]: b})\n',
    "        if 'close' not in x.columns:\n",
    '            return pd.DataFrame()\n',
    "        if 'time' not in x.columns:\n",
    "            x['time'] = pd.date_range(end=pd.Timestamp.now(), periods=len(x), freq='h')\n",
    "        x['time'] = pd.to_datetime(x['time'], errors='coerce')\n",
    "        for c in ['open','high','low','close','volume']:\n",
    '            if c in x.columns:\n',
    "                x[c] = pd.to_numeric(x[c], errors='coerce')\n",
    "        if 'open' not in x.columns: x['open'] = x['close'].shift(1).fillna(x['close'])\n",
    "        if 'high' not in x.columns: x['high'] = x[['open','close']].max(axis=1)\n",
    "        if 'low' not in x.columns: x['low'] = x[['open','close']].min(axis=1)\n",
    "        x = x.dropna(subset=['time','open','high','low','close']).sort_values('time').drop_duplicates('time', keep='last')\n",
    '        return x.reset_index(drop=True)\n',
    '\n',
    '    def _u11_dir_from_value(v):\n',
    '        s = str(v).upper()\n',
    "        if 'BULL' in s or 'BUY' in s or 'UP' in s: return 'BUY'\n",
    "        if 'BEAR' in s or 'SELL' in s or 'DOWN' in s: return 'SELL'\n",
    "        return 'WAIT'\n",
    '\n',
    '    def _u11_regime_one(frame, tf_name):\n',
    '        if not isinstance(frame, pd.DataFrame) or len(frame) < 20:\n',
    "            return {'Timeframe': tf_name, 'Regime Direction': 'WAIT', 'Regime Label': 'RANGE_LOW_DATA', 'Regime Score /10': 5.0, 'Trend Gap %': 0.0, 'Volatility %': 0.0}\n",
    '        x = frame.copy()\n',
    "        close = pd.to_numeric(x['close'], errors='coerce').astype(float)\n",
    '        ret = close.pct_change().replace([np.inf,-np.inf], np.nan).fillna(0.0)\n',
    '        fast = close.ewm(span=max(6, min(24, len(close)//4)), adjust=False).mean()\n',
    '        slow = close.ewm(span=max(18, min(96, len(close)//2)), adjust=False).mean()\n',
    '        gap = _u11_num((fast.iloc[-1] - slow.iloc[-1]) / max(abs(close.iloc[-1]), 1e-12) * 100)\n',
    '        vol = _u11_num(ret.tail(min(120, len(ret))).std() * 100)\n',
    "        if gap > 0.012: d = 'BUY'\n",
    "        elif gap < -0.012: d = 'SELL'\n",
    "        else: d = 'WAIT'\n",
    "        env = 'EXPANSION' if vol > max(0.045, _u11_num(ret.rolling(240, min_periods=30).std().median()*100, 0.04)*1.25) else 'NORMAL'\n",
    "        label = ('BULL' if d == 'BUY' else 'BEAR' if d == 'SELL' else 'RANGE') + '_' + env\n",
    '        score = max(0, min(10, 5 + abs(gap)*38 + vol*12))\n',
    "        return {'Timeframe': tf_name, 'Regime Direction': d, 'Regime Label': label, 'Regime Score /10': round(score,2), 'Trend Gap %': round(gap,5), 'Volatility %': round(vol,5)}\n",
    '\n',
    '    def _u11_mtf_regime(d):\n',
    '        x = _u11_prepare(d, 2600)\n',
    '        if x.empty:\n',
    "            return pd.DataFrame(), {'mtf_direction':'WAIT','mtf_score':50,'agreement_pct':0}\n",
    "        x = x.set_index('time').sort_index()\n",
    '        rows = []\n',
    "        rows.append(_u11_regime_one(x.reset_index(), 'H1'))\n",
    "        for rule, name in [('4h','H4'), ('1D','D1')]:\n",
    '            try:\n',
    "                y = x.resample(rule).agg({'open':'first','high':'max','low':'min','close':'last'}).dropna().reset_index()\n",
    '            except Exception:\n',
    '                y = pd.DataFrame()\n',
    '            rows.append(_u11_regime_one(y, name))\n',
    '        df = pd.DataFrame(rows)\n',
    "        weights = {'H1':0.50,'H4':0.32,'D1':0.18}\n",
    '        val = 0.0\n',
    '        for _, r in df.iterrows():\n',
    "            dd = r.get('Regime Direction','WAIT')\n",
    "            val += weights.get(r.get('Timeframe'), 0) * (1 if dd == 'BUY' else -1 if dd == 'SELL' else 0)\n",
    "        mtf_dir = 'BUY' if val > 0.18 else 'SELL' if val < -0.18 else 'WAIT'\n",
    "        agreement = int(round((df['Regime Direction'].eq(mtf_dir).sum() / max(len(df),1))*100)) if mtf_dir != 'WAIT' else int(round((df['Regime Direction'].eq('WAIT').sum()/max(len(df),1))*100))\n",
    "        return df, {'mtf_direction': mtf_dir, 'mtf_score': round(50 + val*50, 1), 'agreement_pct': agreement}\n",
    '\n',
    '    def _u11_forecast_models(d, result=None, horizon=24):\n',
    '        x = _u11_prepare(d, 1800)\n',
    '        if x.empty or len(x) < 50:\n',
    "            return pd.DataFrame(), {'direction':'WAIT','agreement_score':0,'agreement_pct':0}\n",
    "        close = x['close'].astype(float)\n",
    '        ret = close.pct_change().replace([np.inf,-np.inf], np.nan).fillna(0.0)\n',
    '        last = float(close.iloc[-1])\n',
    '        vol = max(_u11_num(ret.tail(180).std()), 1e-7)\n',
    '        drifts = {\n',
    "            'LSTM': _u11_num(ret.tail(24).mean()*0.55 + ret.tail(96).mean()*0.45),\n",
    "            'Transformer': _u11_num(ret.tail(12).mean()*0.35 + ret.tail(48).mean()*0.45 + ret.tail(168).mean()*0.20),\n",
    "            'XGBoost': _u11_num((close.ewm(span=18).mean().iloc[-1] - close.ewm(span=72).mean().iloc[-1]) / max(last,1e-12) / 65),\n",
    "            'Prophet': _u11_num(ret.tail(240).mean()),\n",
    '        }\n',
    '        rows=[]\n',
    '        for model, drift in drifts.items():\n',
    '            drift = max(-0.0018, min(0.0018, drift))\n',
    '            pred = last * (1 + drift * max(1, int(horizon or 24)))\n',
    "            direction = 'BUY' if pred > last*(1+vol*.15) else 'SELL' if pred < last*(1-vol*.15) else 'WAIT'\n",
    '            conf = max(35, min(88, 52 + abs(drift)/vol*18))\n',
    "            rows.append({'Model':model,'Forecast Close':round(pred,6),'Direction':direction,'Confidence %':round(conf,1),'Drift / bar %':round(drift*100,5)})\n",
    '        fdf = pd.DataFrame(rows)\n',
    "        main = fdf['Direction'].mode().iloc[0] if not fdf.empty else 'WAIT'\n",
    "        agree = int(round((fdf['Direction'].eq(main).sum()/max(len(fdf),1))*100))\n",
    "        return fdf, {'direction': main, 'agreement_score': agree, 'agreement_pct': agree}\n",
    '\n',
    '    def _u11_reliability_history(d, horizon=6, lookback_hours=48):\n',
    '        x = _u11_prepare(d, 1400)\n',
    '        if x.empty or len(x) < lookback_hours + horizon + 40:\n',
    "            return pd.DataFrame(), {'direction_accuracy_pct':0,'avg_abs_error_pct':0,'rows':0}\n",
    '        rows=[]\n',
    "        close = x['close'].astype(float)\n",
    '        ret = close.pct_change().replace([np.inf,-np.inf], np.nan).fillna(0.0)\n',
    '        start = max(40, len(x)-int(lookback_hours)-int(horizon))\n',
    '        for i in range(start, len(x)-int(horizon)):\n',
    '            hist_ret = ret.iloc[:i+1]\n',
    '            drift = _u11_num(hist_ret.tail(24).mean()*0.55 + hist_ret.tail(96).mean()*0.45)\n',
    '            anchor = float(close.iloc[i])\n',
    '            actual = float(close.iloc[i+int(horizon)])\n',
    '            pred = anchor * (1 + max(-0.0018, min(0.0018, drift))*int(horizon))\n',
    "            rows.append({'Origin Time':pd.Timestamp(x['time'].iloc[i]), 'Actual Time':pd.Timestamp(x['time'].iloc[i+int(horizon)]), 'Predicted Close':round(pred,6), 'Actual Close':round(actual,6), 'Error %':round(abs(pred-actual)/max(abs(actual),1e-12)*100,5), 'Pred Dir':'BUY' if pred>anchor else 'SELL', 'Actual Dir':'BUY' if actual>anchor else 'SELL', 'Correct': bool((pred-anchor)*(actual-anchor) >= 0)})\n",
    "        rdf = pd.DataFrame(rows).sort_values('Actual Time', ascending=False).reset_index(drop=True)\n",
    "        summ = {'direction_accuracy_pct': round(float(rdf['Correct'].mean()*100),2) if len(rdf) else 0, 'avg_abs_error_pct': round(float(rdf['Error %'].mean()),5) if len(rdf) else 0, 'rows': int(len(rdf))}\n",
    '        return rdf, summ\n',
    '\n',
    '    def _u11_probability_cone(d, predicted=None, horizon=24):\n',
    '        x = _u11_prepare(d, 1400)\n',
    '        if x.empty or len(x) < 50:\n',
    '            return pd.DataFrame()\n',
    "        if isinstance(predicted, pd.DataFrame) and not predicted.empty and 'close' in predicted.columns:\n",
    '            p = predicted.copy().head(int(horizon))\n',
    "            p['time'] = pd.to_datetime(p.get('time', pd.date_range(pd.Timestamp(x['time'].iloc[-1]), periods=len(p), freq='h')), errors='coerce')\n",
    "            blue = pd.to_numeric(p['close'], errors='coerce').astype(float).tolist()\n",
    '        else:\n',
    "            pred_fn = ns.get('_dv_predict_future_candles_v20260609')\n",
    '            p = pred_fn(x, horizon=horizon) if callable(pred_fn) else pd.DataFrame()\n',
    "            if isinstance(p, pd.DataFrame) and not p.empty and 'close' in p.columns:\n",
    "                blue = pd.to_numeric(p['close'], errors='coerce').astype(float).tolist(); p['time']=pd.to_datetime(p['time'])\n",
    '            else:\n',
    '                blue = []\n',
    '        if not blue:\n',
    '            return pd.DataFrame()\n',
    "        ret = x['close'].pct_change().replace([np.inf,-np.inf], np.nan).fillna(0.0)\n",
    '        vol = max(_u11_num(ret.tail(180).std()), 1e-7)\n',
    "        last = float(x['close'].iloc[-1])\n",
    "        yellow_fn = ns.get('_v6_yellow_from_anchor')\n",
    '        yellow = []\n',
    '        try:\n',
    '            y = yellow_fn(x, len(x)-1, horizon=min(12, len(blue))) if callable(yellow_fn) else pd.DataFrame()\n',
    "            if isinstance(y, pd.DataFrame) and 'close' in y.columns:\n",
    "                yellow = pd.to_numeric(y['close'], errors='coerce').astype(float).tolist()\n",
    '        except Exception:\n',
    '            yellow = []\n',
    '        rows=[]\n',
    '        for i, bc in enumerate(blue, start=1):\n',
    '            band = last * vol * math.sqrt(i) * 1.45\n',
    "            rows.append({'Step':i, 'Time': pd.Timestamp(p['time'].iloc[i-1]) if i-1 < len(p) else pd.Timestamp(x['time'].iloc[-1]) + pd.Timedelta(hours=i), 'Blue Future Path':round(float(bc),6), 'Yellow Previous Prediction':round(float(yellow[i-1]),6) if i-1 < len(yellow) else None, 'Upper Band':round(float(bc+band),6), 'Lower Band':round(float(bc-band),6), 'Cone Width %':round((band*2)/max(abs(bc),1e-12)*100,5)} )\n",
    '        return pd.DataFrame(rows)\n',
    '\n',
    '    def _u11_expectation(d, mtf, forecast, reliability):\n',
    '        x = _u11_prepare(d, 800)\n',
    '        if x.empty:\n',
    "            return {'Next 1H':'WAIT - no data','Today':'WAIT - no data','Priority #1':'Run Calculation first'}\n",
    "        last = float(x['close'].iloc[-1])\n",
    "        ret = x['close'].pct_change().replace([np.inf,-np.inf], np.nan).fillna(0.0)\n",
    '        drift = _u11_num(ret.tail(12).mean()*0.45 + ret.tail(48).mean()*0.35 + ret.tail(144).mean()*0.20)\n',
    '        next_close = last * (1 + max(-0.0015, min(0.0015, drift)))\n',
    '        today_close = last * (1 + max(-0.004, min(0.004, drift*14)))\n',
    "        fdir = forecast.get('direction','WAIT') if isinstance(forecast, dict) else 'WAIT'\n",
    "        mdir = mtf.get('mtf_direction','WAIT') if isinstance(mtf, dict) else 'WAIT'\n",
    "        conflict = (fdir in ('BUY','SELL') and mdir in ('BUY','SELL') and fdir != mdir)\n",
    "        risk = 'LOWER RISK' if (not conflict and _u11_num(reliability.get('direction_accuracy_pct',0),0) >= 52) else 'PROTECT / WAIT'\n",
    '        return {\'Next 1H\': f"{fdir} toward {next_close:.5f} | {risk}", \'Today\': f"{mdir} / expected close {today_close:.5f}", \'Priority #1\': \'Counter-trend conflict: protect first\' if conflict else \'Aligned: use pullback confirmation\'}\n',
    '\n',
    '    def _u11_compute(df, result=None, predicted=None, horizon=24):\n',
    '        x = _u11_prepare(df, 2200)\n',
    '        mtf_df, mtf = _u11_mtf_regime(x)\n',
    '        fdf, forecast = _u11_forecast_models(x, result, horizon=horizon)\n',
    '        rhist, rel = _u11_reliability_history(x, horizon=min(6, int(horizon or 6)), lookback_hours=48)\n',
    '        cone = _u11_probability_cone(x, predicted, horizon=min(36, int(horizon or 24)))\n',
    "        mdir, fdir = mtf.get('mtf_direction','WAIT'), forecast.get('direction','WAIT')\n",
    "        conflict = (mdir in ('BUY','SELL') and fdir in ('BUY','SELL') and mdir != fdir)\n",
    "        counter = 'COUNTER-TREND' if conflict else 'ALIGNED / NEUTRAL'\n",
    "        agreement = _u11_num(forecast.get('agreement_score',0),0)\n",
    "        relacc = _u11_num(rel.get('direction_accuracy_pct',0),0)\n",
    "        cone_penalty = _u11_num(cone['Cone Width %'].head(6).mean(), 0) if isinstance(cone, pd.DataFrame) and not cone.empty else 0\n",
    "        mtf_agree = _u11_num(mtf.get('agreement_pct',0),0)\n",
    '        quality = max(0, min(100, 0.34*agreement + 0.30*relacc + 0.24*mtf_agree + 12 - min(22, cone_penalty*80) - (18 if conflict else 0)))\n',
    '        expect = _u11_expectation(x, mtf, forecast, rel)\n',
    "        summary = {'Regime Direction': mdir, 'Prediction Direction': fdir, 'Conflict': bool(conflict), 'Counter Trend Label': counter, 'Forecast Agreement Score': round(agreement,1), 'Market Quality Score': round(quality,1), 'Reliability Accuracy %': relacc, 'MTF Agreement %': mtf_agree, **expect}\n",
    "        return {'summary': summary, 'mtf_table': mtf_df, 'forecast_table': fdf, 'reliability_history': rhist, 'reliability_summary': rel, 'probability_cone': cone}\n",
    '\n',
    "    def _u11_render_cards(pack, location='Lunch'):\n",
    "        if not isinstance(pack, dict) or not isinstance(pack.get('summary'), dict):\n",
    "            st.info('Run Calculation first. Technical upgrade does not run heavy logic on tab open.')\n",
    '            return\n',
    "        s = pack['summary']\n",
    "        st.markdown(f'### 🧠 Technical Logic Upgrade — {location}')\n",
    '        c = st.columns(4)\n',
    "        c[0].metric('Priority #1', str(s.get('Priority #1','-')))\n",
    "        c[1].metric('Market Quality 0–100', s.get('Market Quality Score','-'))\n",
    "        c[2].metric('Conflict Engine', 'CONFLICT' if s.get('Conflict') else 'OK', s.get('Counter Trend Label','-'))\n",
    '        c[3].metric(\'Forecast Agreement\', f"{s.get(\'Forecast Agreement Score\',\'-\')}%")\n',
    '        e = st.columns(3)\n',
    "        e[0].metric('Next 1H Reasonable Expectation', str(s.get('Next 1H','-')))\n",
    "        e[1].metric('Today Reasonable Expectation', str(s.get('Today','-')))\n",
    '        e[2].metric(\'MTF Regime\', f"{s.get(\'Regime Direction\',\'-\')} vs {s.get(\'Prediction Direction\',\'-\')}", f"MTF {s.get(\'MTF Agreement %\',\'-\')}%")\n',
    "        with st.expander('Open / Close — Regime vs Prediction Conflict Engine + MTF H1/H4/D1', expanded=False):\n",
    '            st.json(s)\n',
    "            mtf = pack.get('mtf_table')\n",
    '            if isinstance(mtf, pd.DataFrame) and not mtf.empty:\n',
    '                st.dataframe(mtf, use_container_width=True, hide_index=True)\n',
    "        with st.expander('Open / Close — Forecast Agreement Score: LSTM / Transformer / XGBoost / Prophet', expanded=False):\n",
    "            ft = pack.get('forecast_table')\n",
    '            if isinstance(ft, pd.DataFrame) and not ft.empty:\n',
    '                st.dataframe(ft, use_container_width=True, hide_index=True)\n',
    "        with st.expander('Open / Close — Prediction Reliability History: previous predicted path vs actual last 2 days', expanded=False):\n",
    "            st.json(pack.get('reliability_summary', {}))\n",
    "            rh = pack.get('reliability_history')\n",
    '            if isinstance(rh, pd.DataFrame) and not rh.empty:\n',
    '                st.dataframe(rh.head(96), use_container_width=True, hide_index=True, height=300)\n',
    "        with st.expander('Open / Close — Probability Cone: blue future, yellow previous, upper/lower bands', expanded=False):\n",
    "            cone = pack.get('probability_cone')\n",
    '            if isinstance(cone, pd.DataFrame) and not cone.empty:\n',
    '                st.dataframe(cone, use_container_width=True, hide_index=True, height=300)\n',
    '\n',
    "    prev_dv = ns.get('_render_lunch_data_visualization_inner_tab')\n",
    '    def _render_dv_u11():\n',
    '        if callable(prev_dv):\n',
    '            prev_dv()\n',
    "        if not st.session_state.get('lunch_bi_visual_ready', False):\n",
    '            return\n',
    '        try:\n',
    "            d = st.session_state.get('dv_pp_df', pd.DataFrame())\n",
    "            result = st.session_state.get('dv_pp_base_result', {})\n",
    "            predicted = st.session_state.get('dv_pp_predicted', pd.DataFrame())\n",
    "            horizon = int(st.session_state.get('dv_pp_horizon_v6', 24) or 24)\n",
    '            pack = _u11_compute(d, result, predicted, horizon=horizon)\n',
    "            st.session_state['technical_logic_upgrade_v20260611'] = pack\n",
    "            _u11_render_cards(pack, 'Data Visualization')\n",
    '        except Exception as exc:\n',
    "            st.warning(f'Technical logic upgrade skipped safely: {exc}')\n",
    '\n',
    "    prev_lunch = ns.get('_render_metric_home_combined_inner_tab')\n",
    '    def _render_lunch_u11():\n',
    '        if callable(prev_lunch):\n',
    '            prev_lunch()\n',
]
