"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""2026-06-09 runtime-safe Lunch/Data Visualization patch.\n',
    '\n',
    'Adds compact copy exports, a second PowerBI-style candlestick projection chart,\n',
    'and lighter button states without touching connector/order logic.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    '\n',
    'def apply(ns: dict) -> None:\n',
    '    import json\n',
    '    import pandas as pd\n',
    '    import streamlit as st\n',
    '\n',
    '    def _safe_json(obj):\n',
    '        try:\n',
    '            if isinstance(obj, pd.DataFrame):\n',
    '                return obj.tail(30).to_dict("records")\n',
    '            if isinstance(obj, pd.Series):\n',
    '                return obj.to_dict()\n',
    '            if isinstance(obj, pd.Timestamp):\n',
    '                return str(obj)\n',
    '            if isinstance(obj, dict):\n',
    '                return {str(k): _safe_json(v) for k, v in obj.items()}\n',
    '            if isinstance(obj, (list, tuple)):\n',
    '                return [_safe_json(x) for x in obj[:60]]\n',
    '            return obj\n',
    '        except Exception:\n',
    '            return str(obj)\n',
    '\n',
    '    def _compact_latest_ohlc(df, rows=24):\n',
    '        if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '            return []\n',
    '        cols = [c for c in ["time", "open", "high", "low", "close", "volume"] if c in df.columns]\n',
    '        if not cols:\n',
    '            return []\n',
    '        out = df[cols].tail(int(rows)).copy()\n',
    '        for c in out.columns:\n',
    '            if "time" in str(c).lower():\n',
    '                out[c] = pd.to_datetime(out[c], errors="coerce").astype(str)\n',
    '        return out.to_dict("records")\n',
    '\n',
    '    def _build_lunch_all_copy_text_v2():\n',
    '        """Compact full Lunch export: current decision + new BI/projection data, no history tables."""\n',
    '        df = st.session_state.get("last_df")\n',
    '        metric = st.session_state.get("eurusd_h1_matrix_export", {}) or {}\n',
    '        pred = st.session_state.get("lunch_prediction_export", {}) or {}\n',
    '        dv_pred = st.session_state.get("dv_pp_predicted")\n',
    '        dv_path = st.session_state.get("dv_pp_lightblue_path")\n',
    '        dv_result = st.session_state.get("dv_pp_base_result", {}) or {}\n',
    '        dv_regime = st.session_state.get("dv_pp_regime_summary", {}) or {}\n',
    '        dv_bt_summary = st.session_state.get("dv_pp_bt_summary", {}) or {}\n',
    '\n',
    '        payload = {\n',
    '            "export_type": "LUNCH_COMPACT_FULL_NO_HISTORY",\n',
    '            "built_at": str(pd.Timestamp.now()),\n',
    '            "symbol": st.session_state.get("symbol", "EURUSD"),\n',
    '            "timeframe": st.session_state.get("timeframe", "H1"),\n',
    '            "source": st.session_state.get("source", "DISCONNECTED"),\n',
    '            "rows": len(df) if isinstance(df, pd.DataFrame) else 0,\n',
    '            "metric_and_reverse10_current": _safe_json(metric),\n',
    '            "lunch_prediction_current": _safe_json(pred),\n',
    '            "data_visualization_new_summary": {\n',
    '                "powerbi_ml": _safe_json({k: v for k, v in (dv_result or {}).items() if k not in {"vote_df", "deep_df", "forecast_df", "history"}}),\n',
    '                "smooth_regime": _safe_json(dv_regime),\n',
    '                "prediction_backtest_summary_only": _safe_json(dv_bt_summary),\n',
    '                "future_blue_candles": _safe_json(dv_pred if isinstance(dv_pred, pd.DataFrame) else pd.DataFrame()),\n',
    '                "light_blue_current_path": _safe_json(dv_path if isinstance(dv_path, pd.DataFrame) else pd.DataFrame()),\n',
    '            },\n',
    '            "latest_market_tail_24_only": _compact_latest_ohlc(df, rows=24),\n',
    '            "excluded_to_reduce_lines": [\n',
    '                "25D reversal scan/history tables",\n',
    '                "prediction-vs-actual full history rows",\n',
    '                "rolling projection history rows",\n',
    '                "raw account/order/deal history rows",\n',
    '            ],\n',
    '        }\n',
    '        return "LUNCH TAB COMPACT FULL COPY — NO HISTORY DATA\\n" + "=" * 64 + "\\n" + json.dumps(_safe_json(payload), indent=2, ensure_ascii=False, default=str)\n',
    '\n',
    '    def _render_second_powerbi_candle_chart(d, predicted, result=None, regime=None):\n',
    '        try:\n',
    '            import plotly.graph_objects as go\n',
    '            from plotly.subplots import make_subplots\n',
    '        except Exception as exc:\n',
    '            st.warning(f"Second PowerBI chart unavailable: {exc}")\n',
    '            return\n',
    '        prep = ns.get("_dv_prepare_ohlc_v20260609")\n',
    '        last_days = ns.get("_dv_last_continuous_days_v20260609")\n',
    '        if callable(last_days):\n',
    '            x = last_days(d, days=5, limit=3000)\n',
    '        elif callable(prep):\n',
    '            x = prep(d, limit=240).tail(120)\n',
    '        else:\n',
    '            x = d.tail(120) if isinstance(d, pd.DataFrame) else pd.DataFrame()\n',
    '        if not isinstance(x, pd.DataFrame) or x.empty:\n',
    '            st.info("Second chart needs clean OHLC data.")\n',
    '            return\n',
    '        fig = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=.045, row_heights=[.62, .20, .18], subplot_titles=("PowerBI Chart 2 — actual + future candles", "Trend / reliability ribbon", "Projected confidence"))\n',
    '        fig.add_trace(go.Candlestick(x=x["time"], open=x["open"], high=x["high"], low=x["low"], close=x["close"], name="Actual"), row=1, col=1)\n',
    '        if isinstance(predicted, pd.DataFrame) and not predicted.empty:\n',
    '            fig.add_trace(go.Candlestick(x=predicted["time"], open=predicted["open"], high=predicted["high"], low=predicted["low"], close=predicted["close"], name="Future BLUE candles", increasing={"line":{"color":"#0EA5E9","width":2},"fillcolor":"rgba(14,165,233,.32)"}, decreasing={"line":{"color":"#60A5FA","width":2},"fillcolor":"rgba(96,165,250,.24)"}), row=1, col=1)\n',
    '            conf_col = "confidence_pct" if "confidence_pct" in predicted.columns else None\n',
    '            if conf_col:\n',
    '                fig.add_trace(go.Bar(x=predicted["time"], y=predicted[conf_col], name="Forecast confidence %"), row=3, col=1)\n',
    '        close = pd.to_numeric(x["close"], errors="coerce")\n',
    '        ema_fast = close.ewm(span=12, adjust=False).mean()\n',
    '        ema_slow = close.ewm(span=48, adjust=False).mean()\n',
    '        ribbon = ((ema_fast - ema_slow) / close.replace(0, pd.NA) * 100).fillna(0)\n',
    '        fig.add_trace(go.Scatter(x=x["time"], y=ribbon, mode="lines", name="EMA trend ribbon %"), row=2, col=1)\n',
    '        fig.add_hline(y=0, row=2, col=1, line_width=1)\n',
    '        title_score = ""\n',
    '        if isinstance(result, dict):\n',
    '            title_score = f" • Master {result.get(\'master_score\',\'-\')}/10 • Bull {result.get(\'bull_probability\',\'-\')}%"\n',
    '        if isinstance(regime, dict) and regime.get("current_regime"):\n',
    '            title_score += f" • Regime {regime.get(\'current_regime\')}"\n',
    '        fig.update_layout(height=760, margin=dict(l=8, r=8, t=62, b=8), title="Second PowerBI-style Candlestick Projection" + title_score, xaxis_rangeslider_visible=False, legend=dict(orientation="h"))\n',
    '        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False, "responsive": True})\n',
    '\n',
    '\n',
    '    def _apply_v28_mobile_cpu_ram_css():\n',
    '        """Bigger phone-app mode + lighter GPU/CPU CSS.\n',
    '\n',
    '        Streamlit Cloud/mobile can feel slow when every card has heavy blur/shadow.\n',
    '        This keeps the real-app look but removes expensive effects on small screens.\n',
    '        """\n',
    '        st.markdown("""\n',
    '        <style>\n',
    '        :root{--v28-radius:22px;}\n',
    '        .v28-run-row div[data-testid="stButton"] > button{\n',
    '            min-height:58px!important;border-radius:22px!important;font-size:1.05rem!important;\n',
    '            font-weight:900!important;letter-spacing:.01em!important;\n',
    '        }\n',
    '        .v28-phone-note{padding:10px 12px;border-radius:18px;background:rgba(14,165,233,.10);border:1px solid rgba(14,165,233,.22);font-weight:800;}\n',
    '        @media (max-width: 820px){\n',
    '          .block-container{padding:.55rem .48rem 4.8rem .48rem!important;max-width:100%!important;}\n',
    '          h1,h2,h3{line-height:1.12!important;}\n',
    '          div[data-testid="stButton"] > button{min-height:52px!important;border-radius:20px!important;font-size:1.02rem!important;font-weight:850!important;}\n',
    '          div[data-testid="stMetric"]{border-radius:20px!important;padding:12px!important;box-shadow:none!important;backdrop-filter:none!important;}\n',
    '          section[data-testid="stSidebar"]{min-width:86vw!important;max-width:92vw!important;}\n',
    '          div[data-testid="stDataFrame"]{max-height:58vh!important;overflow:auto!important;border-radius:16px!important;}\n',
    '          .js-plotly-plot, .plot-container{max-height:78vh!important;}\n',
    '        }\n',
    '        </style>\n',
    '        """, unsafe_allow_html=True)\n',
    '\n',
    '    def _render_data_visualization_v2():\n',
    '        rows_limit = int(st.session_state.get("dv_pp_rows", 6000))\n',
    '        horizon = int(st.session_state.get("dv_pp_horizon", 24))\n',
    '        min_days = int(st.session_state.get("dv_pp_min_days", 5))\n',
    '        bt_lookback = int(st.session_state.get("dv_pp_bt", 180))\n',
    '        _apply_v28_mobile_cpu_ram_css()\n',
    '        st.markdown("### 📊 Data Visualization — Reliable PowerBI + ML Projection")\n',
    '        st.caption("Manual-run only for speed/RAM. Click Run Calculating first; no heavy 5-layer or chart work runs automatically.")\n',
    '        st.markdown(\'<div class="v28-run-row">\', unsafe_allow_html=True)\n',
    '        top = st.columns([1.25, .85, .85, .85, .85])\n',
    '        with top[0]:\n',
    '            run = st.button("▶ Run Calculating", use_container_width=True, key="dv_run_calculating_v28")\n',
    '            run_legacy = st.button("▶ Run Reliable PowerBI + Future Candles", use_container_width=True, key="dv_run_reliable_powerbi_v2")\n',
    '            run = bool(run or run_legacy)\n',
    '        with top[1]:\n',
    '            rows_limit = st.slider("Rows used", 800, 12000, min(rows_limit, 12000), 400, key="dv_pp_rows")\n',
    '        with top[2]:\n',
    '            horizon = st.slider("Future candles", 6, 60, min(horizon, 60), 6, key="dv_pp_horizon")\n',
    '        with top[3]:\n',
    '            min_days = st.slider("Regime min days", 3, 21, min_days, 1, key="dv_pp_min_days")\n',
    '        with top[4]:\n',
    '            bt_lookback = st.slider("Backtest summary bars", 60, 360, min(bt_lookback, 360), 20, key="dv_pp_bt")\n',
    '        st.markdown("</div>", unsafe_allow_html=True)\n',
    '\n',
    '        if run:\n',
    '            st.session_state["lunch_bi_visual_ready"] = True\n',
    '            with st.spinner("Calculating clean OHLC, ML projection, future candles, and reliability summary…"):\n',
    '                clean = ns["_clean_lunch_visual_df"](limit=rows_limit)\n',
    '                d = ns["_dv_prepare_ohlc_v20260609"](clean, limit=rows_limit)\n',
    '                if not isinstance(d, pd.DataFrame) or d.empty or len(d) < 120:\n',
    '                    st.warning("Need at least 120 clean OHLC candles. Refresh/connect data first.")\n',
    '                    ns["_render_lunch_copy_refresh_bar"]()\n',
    '                    return\n',
    '                result = ns["_five_layer_powerbi_calculate"](d, horizon=horizon)\n',
    '                predicted = ns["_dv_predict_future_candles_v20260609"](d, horizon=horizon)\n',
    '                _, bt_summary = ns["_dv_prediction_vs_actual_history_v20260609"](d, lookback=bt_lookback, horizon=1)\n',
    '                regime, _ = ns["_dv_major_regime_detector_v20260609"](d, min_days=float(min_days), lookback_days=240, horizon=horizon)\n',
    '                light_path = ns["_dv_build_lightblue_path_v20260609"](ns["_dv_last_continuous_days_v20260609"](d, days=10), predicted)\n',
    '                st.session_state.update({\n',
    '                    "dv_pp_df": d, "dv_pp_base_result": result, "dv_pp_predicted": predicted,\n',
    '                    "dv_pp_bt_summary": bt_summary, "dv_pp_regime_summary": regime,\n',
    '                    "dv_pp_lightblue_path": light_path,\n',
    '                    "lunch_5layer_powerbi_result": result,\n',
    '                    "lunch_5layer_powerbi_df": d,\n',
    '                })\n',
    '            st.success("Data Visualization upgraded result is ready.")\n',
    '\n',
    '        if not st.session_state.get("lunch_bi_visual_ready", False):\n',
    '            st.info("Press run first. No heavy chart calculation runs automatically.")\n',
    '            ns["_render_lunch_copy_refresh_bar"]()\n',
    '            return\n',
    '\n',
    '        d = st.session_state.get("dv_pp_df", pd.DataFrame())\n',
    '        result = st.session_state.get("dv_pp_base_result", {})\n',
    '        predicted = st.session_state.get("dv_pp_predicted", pd.DataFrame())\n',
    '        regime = st.session_state.get("dv_pp_regime_summary", {})\n',
    '        bt_summary = st.session_state.get("dv_pp_bt_summary", {})\n',
    '        light_path = st.session_state.get("dv_pp_lightblue_path", pd.DataFrame())\n',
    '\n',
    '        cards = st.columns(6)\n',
    '        if isinstance(result, dict):\n',
    '            cards[0].metric("Master", f"{result.get(\'master_score\',\'-\')}/10")\n',
    '            cards[1].metric("Bull", f"{result.get(\'bull_probability\',\'-\')}%")\n',
    '        if isinstance(regime, dict):\n',
    '            cards[2].metric("Regime", regime.get("current_regime", "-"))\n',
    '            cards[3].metric("Days In", regime.get("days_since_last_change", regime.get("days_since_change", "-")))\n',
    '            cards[4].metric("Days Left", regime.get("estimated_days_remaining", regime.get("estimated_days_left", "-")))\n',
    '        cards[5].metric("BT Dir Acc", f"{bt_summary.get(\'direction_accuracy_pct\', 0)}%" if isinstance(bt_summary, dict) else "-")\n',
    '\n',
    '        st.markdown("#### Main PowerBI Candlestick + ML Projection")\n',
    '        try:\n',
    '            ns["_dv_render_candle_powerbi_chart_v20260609"](d, predicted, None, None)\n',
    '        except TypeError:\n',
    '            ns["_dv_render_candle_powerbi_chart_v20260609"](d, predicted)\n',
    '        st.markdown("#### Second PowerBI-style Candlestick Chart with Future Candles")\n',
    '        _render_second_powerbi_candle_chart(d, predicted, result, regime)\n',
    '\n',
    '        # Feed the original PowerBI renderer so the expander shows results instead of only the old instruction.\n',
    '        if isinstance(result, dict) and result.get("ok"):\n',
    '            st.session_state["lunch_5layer_powerbi_result"] = result\n',
    '            st.session_state["lunch_5layer_powerbi_df"] = d\n',
    '        with st.expander("Open / Close — Original PowerBI + ML Projection", expanded=False):\n',
    '            try:\n',
    '                ns["_render_lunch_advanced_powerbi_ml_projection"](d, horizon=horizon)\n',
    '            except Exception as exc:\n',
    '                st.warning(f"Original PowerBI renderer could not display: {exc}")\n',
    '                st.json(_safe_json({k: v for k, v in (result or {}).items() if k not in {"vote_df", "deep_df", "forecast_df", "history"}}))\n',
    '\n',
    '        with st.expander("Open / Close — Future Candle Tables", expanded=False):\n',
    '            if isinstance(predicted, pd.DataFrame) and not predicted.empty:\n',
    '                sorter = ns.get("_dv_sort_newest_first_v20260609")\n',
    '                st.dataframe(sorter(predicted) if callable(sorter) else predicted.iloc[::-1], use_container_width=True, hide_index=True, height=260)\n',
    '            if isinstance(light_path, pd.DataFrame) and not light_path.empty:\n',
    '                st.markdown("Light-blue current path")\n',
    '                st.dataframe(light_path, use_container_width=True, hide_index=True, height=200)\n',
    '\n',
    '        with st.expander("📋 Data Visualization Copy Export — no history rows", expanded=True):\n',
    '            payload = {\n',
    '                "export_type": "DATA_VISUALIZATION_COMPACT_NO_HISTORY",\n',
    '                "built_at": str(pd.Timestamp.now()),\n',
    '                "powerbi_ml_summary": _safe_json({k: v for k, v in (result or {}).items() if k not in {"vote_df", "deep_df", "forecast_df", "history"}}),\n',
    '                "regime_summary": _safe_json(regime),\n',
    '                "prediction_backtest_summary_only": _safe_json(bt_summary),\n',
    '                "future_blue_candles": _safe_json(predicted if isinstance(predicted, pd.DataFrame) else pd.DataFrame()),\n',
    '                "light_blue_current_path": _safe_json(light_path if isinstance(light_path, pd.DataFrame) else pd.DataFrame()),\n',
    '            }\n',
    '            text = json.dumps(payload, indent=2, ensure_ascii=False, default=str)\n',
    '            st.session_state["lunch_visualization_export"] = text\n',
    '            try:\n',
    '                from core.pro_terminal_uiux import render_mobile_copy_button\n',
    '                render_mobile_copy_button("Copy Data Visualization", text, "copy_data_visualization_no_history_v2")\n',
    '            except Exception:\n',
    '                st.text_area("Data Visualization Copy", text, height=260)\n',
    '        ns["_render_lunch_copy_refresh_bar"]()\n',
    '\n',
    '    ns["_build_lunch_all_copy_text"] = _build_lunch_all_copy_text_v2\n',
    '    ns["_render_lunch_data_visualization_inner_tab"] = _render_data_visualization_v2\n',
    '\n',
    '# =====================================================================\n',
    '# 2026-06-10 ADDITIVE PATCH\n',
    '# Lunch NY-London overlap metrics + stronger Data Visualization KPI layer.\n',
    '# This section is intentionally additive/runtime-safe: if data is missing,\n',
    '# it shows a warning instead of breaking the app.\n',
    '# =====================================================================\n',
    'try:\n',
    '    _PREV_APPLY_20260609 = apply\n',
    'except Exception:\n',
    '    _PREV_APPLY_20260609 = None\n',
    '\n',
    '\n',
    'def apply(ns: dict) -> None:  # type: ignore[no-redef]\n',
    '    if callable(_PREV_APPLY_20260609):\n',
    '        _PREV_APPLY_20260609(ns)\n',
    '\n',
    '    import json\n',
    '    import pandas as pd\n',
    '    import streamlit as st\n',
    '\n',
    '    def _nylo_find_cols(df):\n',
    "        cols = {str(c).lower().strip(): c for c in getattr(df, 'columns', [])}\n",
    '        return {\n',
    "            'time': cols.get('time') or cols.get('datetime') or cols.get('date') or cols.get('timestamp'),\n",
    "            'open': cols.get('open') or cols.get('o'),\n",
    "            'high': cols.get('high') or cols.get('h'),\n",
    "            'low': cols.get('low') or cols.get('l'),\n",
    "            'close': cols.get('close') or cols.get('c'),\n",
    "            'volume': cols.get('volume') or cols.get('vol') or cols.get('tick_volume'),\n",
    '        }\n',
    '\n',
    '    def _nylo_prepare_df(df):\n',
    '        if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '            return pd.DataFrame()\n',
    '        m = _nylo_find_cols(df)\n',
    "        need = [m.get('open'), m.get('high'), m.get('low'), m.get('close')]\n",
    '        if not all(need):\n',
    '            return pd.DataFrame()\n',
    '        d = pd.DataFrame()\n',
    "        if m.get('time'):\n",
    "            d['time'] = pd.to_datetime(df[m['time']], errors='coerce', utc=False)\n",
    '        else:\n',
    "            d['time'] = pd.date_range(end=pd.Timestamp.utcnow().tz_localize(None), periods=len(df), freq='h')\n",
    "        for k in ['open', 'high', 'low', 'close']:\n",
    "            d[k] = pd.to_numeric(df[m[k]], errors='coerce')\n",
    "        if m.get('volume'):\n",
    "            d['volume'] = pd.to_numeric(df[m['volume']], errors='coerce').fillna(0)\n",
    '        else:\n',
    "            d['volume'] = 0.0\n",
    "        d = d.dropna(subset=['time', 'open', 'high', 'low', 'close']).sort_values('time')\n",
    '        return d.tail(12000).reset_index(drop=True)\n',
    '\n',
    '    def _score_0_10(value, lo, hi, reverse=False):\n',
    '        try:\n',
    '            v = float(value)\n',
    '            if hi == lo:\n',
    '                return 5.0\n',
    '            s = (v - lo) / (hi - lo) * 10.0\n',
    '            s = max(0.0, min(10.0, s))\n',
    '            return round(10.0 - s if reverse else s, 2)\n',
    '        except Exception:\n',
    '            return 0.0\n',
    '\n',
    '    def _build_ny_london_overlap_history(df=None, days=25):\n',
    "        raw = st.session_state.get('last_df') if df is None else df\n",
    '        d = _nylo_prepare_df(raw)\n',
    '        if d.empty:\n',
    '            return pd.DataFrame(), {}\n',
    "        # June/summer London-New York overlap is 12:00-16:00 UTC. This app's\n",
    '        # EURUSD feed is usually UTC-like; fixed hours keep the metric stable.\n',
    "        d['_date'] = d['time'].dt.date\n",
    "        d['_hour'] = d['time'].dt.hour\n",
    "        ov = d[(d['_hour'] >= 12) & (d['_hour'] <= 16)].copy()\n",
    '        if ov.empty:\n',
    "            ov = d[(d['_hour'] >= 13) & (d['_hour'] <= 17)].copy()\n",
    '        if ov.empty:\n',
    "            return pd.DataFrame(), {'message': 'No candles found inside NY-London overlap hours.'}\n",
    '        rows = []\n',
    "        all_range = (d['high'] - d['low']).rolling(24, min_periods=3).mean().dropna()\n",
    "        base_range = float(all_range.median()) if not all_range.empty else float((d['high'] - d['low']).median())\n",
    '        base_range = max(base_range, 1e-9)\n',
    "        for day, x in ov.groupby('_date'):\n",
    "            x = x.sort_values('time')\n",
    '            if x.empty:\n',
    '                continue\n',
    "            first_open = float(x['open'].iloc[0]); last_close = float(x['close'].iloc[-1])\n",
    "            hi = float(x['high'].max()); lo = float(x['low'].min())\n",
    '            rng = max(hi - lo, 1e-9)\n',
    '            body = abs(last_close - first_open)\n',
    "            direction = 'BUY' if last_close > first_open else 'SELL' if last_close < first_open else 'RANGE'\n",
    '            trend_eff = body / rng\n',
    '            range_power = rng / base_range\n',
    '            close_pos = (last_close - lo) / rng\n',
    '            momentum = (last_close - first_open) / max(abs(first_open), 1e-9) * 10000.0\n',
    '            vol_score = _score_0_10(range_power, 0.45, 2.2)\n',
    '            trend_score = _score_0_10(trend_eff, 0.15, 0.85)\n',
    "            buy_align = round((trend_score * 0.55 + _score_0_10(close_pos, 0.35, 0.9) * 0.45) if direction == 'BUY' else _score_0_10(close_pos, 0.35, 0.9) * 0.35, 2)\n",
    "            sell_align = round((trend_score * 0.55 + _score_0_10(1-close_pos, 0.35, 0.9) * 0.45) if direction == 'SELL' else _score_0_10(1-close_pos, 0.35, 0.9) * 0.35, 2)\n",
    '            risk_score = round(max(0.0, min(10.0, vol_score * 0.45 + (10.0 - trend_score) * 0.35 + abs(close_pos - 0.5) * 4.0)), 2)\n',
    '            overlap_score = round(max(buy_align, sell_align) * 0.45 + trend_score * 0.25 + vol_score * 0.20 + (10-risk_score) * 0.10, 2)\n',
    '            rows.append({\n',
    "                'Date': str(day),\n",
    "                'Weekday': pd.Timestamp(day).strftime('%A'),\n",
    "                'Overlap Hours': '12:00-16:00 UTC',\n",
    "                'Direction': direction,\n",
    "                'Open': round(first_open, 5), 'High': round(hi, 5), 'Low': round(lo, 5), 'Close': round(last_close, 5),\n",
    "                'Pips Move': round(momentum, 1),\n",
    "                'Range Power /10': vol_score,\n",
    "                'Trend Efficiency /10': trend_score,\n",
    "                'BUY Align /10': buy_align,\n",
    "                'SELL Align /10': sell_align,\n",
    "                'Risk /10': risk_score,\n",
    "                'Overlap Master /10': overlap_score,\n",
    "                'Read': 'TRADEABLE' if overlap_score >= 6.5 and risk_score <= 6.5 else 'PROTECT' if risk_score >= 7 else 'WAIT',\n",
    "                '_sort_time': pd.Timestamp(day),\n",
    '            })\n',
    "        hist = pd.DataFrame(rows).sort_values('_sort_time', ascending=False).head(int(days))\n",
    "        if '_sort_time' in hist.columns:\n",
    "            hist = hist.drop(columns=['_sort_time'])\n",
    '        summary = {}\n',
    '        if not hist.empty:\n',
    '            today = hist.iloc[0].to_dict()\n',
    '            summary = {\n',
    "                'ok': True,\n",
    "                'today_overlap_master_10': today.get('Overlap Master /10'),\n",
    "                'today_direction': today.get('Direction'),\n",
    "                'today_read': today.get('Read'),\n",
    "                'today_risk_10': today.get('Risk /10'),\n",
    "                'avg_25d_master_10': round(float(pd.to_numeric(hist['Overlap Master /10'], errors='coerce').mean()), 2),\n",
    "                'avg_25d_risk_10': round(float(pd.to_numeric(hist['Risk /10'], errors='coerce').mean()), 2),\n",
    "                'best_bias_25d': 'BUY' if pd.to_numeric(hist['BUY Align /10'], errors='coerce').mean() >= pd.to_numeric(hist['SELL Align /10'], errors='coerce').mean() else 'SELL',\n",
    "                'rows': int(len(hist)),\n",
    '            }\n',
    '        return hist, summary\n',
    '\n',
    '    def _render_ny_london_overlap_section():\n',
    "        st.markdown('### 🌍 NY–London Overlap Metric Duplicate')\n",
    "        st.caption('Separate Lunch metric duplicate using only EURUSD overlap-hour candles. Shows today → last 25 days descending, all scores out of 10.')\n",
    '        hist, summary = _build_ny_london_overlap_history(days=25)\n',
    "        st.session_state['ny_london_overlap_history'] = hist\n",
    "        st.session_state['ny_london_overlap_summary'] = summary\n",
    '        if not isinstance(hist, pd.DataFrame) or hist.empty:\n',
    "            st.warning((summary or {}).get('message', 'No overlap-hour history available yet. Refresh/connect EURUSD H1 data first.'))\n",
    '            return\n',
    '        c = st.columns(5)\n',
    '        c[0].metric(\'Today Overlap\', f"{summary.get(\'today_overlap_master_10\',\'-\')}/10")\n',
    "        c[1].metric('Today Bias', summary.get('today_direction', '-'))\n",
    '        c[2].metric(\'Today Risk\', f"{summary.get(\'today_risk_10\',\'-\')}/10")\n',
    '        c[3].metric(\'25D Avg\', f"{summary.get(\'avg_25d_master_10\',\'-\')}/10")\n',
    "        c[4].metric('25D Best Bias', summary.get('best_bias_25d', '-'))\n",
    '        st.dataframe(hist, use_container_width=True, hide_index=True, height=430)\n',
    '\n',
    '    def _build_dv_efficiency_summary(result=None, regime=None, bt_summary=None, predicted=None, d=None):\n',
    "        result = result or st.session_state.get('dv_pp_base_result', {}) or {}\n",
    "        regime = regime or st.session_state.get('dv_pp_regime_summary', {}) or {}\n",
    "        bt_summary = bt_summary or st.session_state.get('dv_pp_bt_summary', {}) or {}\n",
    "        predicted = predicted if predicted is not None else st.session_state.get('dv_pp_predicted')\n",
    "        d = d if d is not None else st.session_state.get('dv_pp_df')\n",
]
