"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Canonical runtime state, explicit adapters, and atomic publication.\n',
    '\n',
    'This module contains no calculation formulas.  It enforces one successful\n',
    'Settings calculation as the authoritative run and exposes one-way compatibility\n',
    'adapters for legacy renderers.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from copy import deepcopy\n',
    'from datetime import datetime, timezone\n',
    'from typing import Any, Dict, Iterable, Mapping, MutableMapping, Optional, Tuple\n',
    'import time\n',
    '\n',
    'try:\n',
    '    import pandas as pd\n',
    'except Exception:  # pragma: no cover\n',
    '    pd = None  # type: ignore\n',
    '\n',
    'CANONICAL_KEY = "canonical_decision_result_20260617"\n',
    'LAST_VALID_KEY = "last_valid_canonical_decision_result_20260617"\n',
    'STAGING_KEY = "canonical_decision_staging_20260617"\n',
    'RUNTIME_CONTEXT_KEY = "runtime_context_20260617"\n',
    'SHARED_KEY = "adx_shared_calc_result_20260615"\n',
    'LEGACY_SHARED_KEY = "shared_calc_result"\n',
    'GENERATION_KEY = "successful_calculation_generation_20260617"\n',
    '\n',
    'REQUIRED_CANONICAL_FIELDS = (\n',
    '    "run_id", "calculation_generation", "data_signature", "symbol", "timeframe",\n',
    '    "source", "latest_completed_candle_time", "created_at", "expires_at", "schema_version", "calculation_version",\n',
    '    "calculation_status",\n',
    ')\n',
    '\n',
    'ADAPTER_SPECS: Dict[str, Dict[str, Any]] = {\n',
    '    "market": {"accepted_legacy_source_keys": ("dv_pp_df", "lunch_5layer_powerbi_df", "last_df", "ohlc_df", "df")},\n',
    '    "metric": {"accepted_legacy_source_keys": ("lunch_metric_result_cache", "last_result", "current_result")},\n',
    '    "powerbi": {"accepted_legacy_source_keys": ("dv_pp_base_result", "lunch_5layer_powerbi_result", "lunch_prediction_export")},\n',
    '    "regime": {"accepted_legacy_source_keys": ("dv_pp_regime_summary", "regime_context_20260614", "canonical_regime_snapshot_20260617")},\n',
    '    "alpha_delta": {"accepted_legacy_source_keys": ("adx_regime_alpha_delta_20260615", "regime_alpha_delta")},\n',
    '    "priority": {"accepted_legacy_source_keys": ("canonical_priority_table_20260617", "adx_hourly_priority_calibrated_20260615")},\n',
    '    "knn_greedy": {"accepted_legacy_source_keys": ("canonical_priority_table_20260617", "three_center_priority_sorted_20260614")},\n',
    '    "reliability": {"accepted_legacy_source_keys": ("reliability_control_center_20260614", "adx_reliability_calibrated_20260615")},\n',
    '    "nlp": {"accepted_legacy_source_keys": ("nlp_market_intelligence_result", "regime_nlp_today_table", "nlp_ranked_news_df")},\n',
    '    "data_mining": {"accepted_legacy_source_keys": ("research_pack_20260612", "final_synced_research_merge_pack_20260612")},\n',
    '    "prediction_history": {"accepted_legacy_source_keys": ("dv_pp_bt_hist", "prediction_history_df", "prediction_vs_actual_history_df")},\n',
    '    "ai_grounding": {"accepted_legacy_source_keys": ("adx_ai_grounding_20260615",)},\n',
    '}\n',
    '\n',
    '\n',
    'def _utc_now_iso() -> str:\n',
    '    return datetime.now(timezone.utc).isoformat()\n',
    '\n',
    '\n',
    'def _is_df(value: Any) -> bool:\n',
    '    return pd is not None and isinstance(value, pd.DataFrame)\n',
    '\n',
    '\n',
    'def proposed_generation(state: Mapping[str, Any]) -> int:\n',
    '    """Return the next generation without mutating state."""\n',
    '    current = state.get(GENERATION_KEY, 0)\n',
    '    try:\n',
    '        current = int(current or 0)\n',
    '    except Exception:\n',
    '        current = 0\n',
    '    existing = state.get(CANONICAL_KEY) or state.get(LAST_VALID_KEY) or {}\n',
    '    if isinstance(existing, dict):\n',
    '        try:\n',
    '            current = max(current, int(existing.get("calculation_generation", 0) or 0))\n',
    '        except Exception:\n',
    '            pass\n',
    '    return current + 1\n',
    '\n',
    '\n',
    'def validate_canonical_result(payload: Any) -> Tuple[bool, list[str]]:\n',
    '    errors: list[str] = []\n',
    '    if not isinstance(payload, dict):\n',
    '        return False, ["canonical result is not a dictionary"]\n',
    '    for key in REQUIRED_CANONICAL_FIELDS:\n',
    '        if key not in payload or payload.get(key) in (None, ""):\n',
    '            errors.append(f"missing {key}")\n',
    '    try:\n',
    '        if int(payload.get("calculation_generation", 0) or 0) < 1:\n',
    '            errors.append("calculation_generation must be positive")\n',
    '    except Exception:\n',
    '        errors.append("calculation_generation is invalid")\n',
    '    status = str(payload.get("calculation_status", "")).upper()\n',
    '    if not status.startswith("COMPLETED"):\n',
    '        errors.append(f"calculation_status is not completed: {status or \'missing\'}")\n',
    '    market = payload.get("market") or {}\n',
    '    if not isinstance(market, dict) or not market.get("latest_completed_candle_time"):\n',
    '        errors.append("missing latest_completed_candle_time")\n',
    '    if not isinstance(payload.get("final_decision"), dict):\n',
    '        errors.append("missing final_decision object")\n',
    '    shared_schema = payload.get("shared_result_schema_version")\n',
    '    if shared_schema:\n',
    '        for key in (\n',
    '            "canonical_calculation_id", "multiscale_regime", "probabilistic_projection",\n',
    '            "dynamic_feature_weights", "forecast_decomposition", "validation_metrics",\n',
    '            "meta_labels", "layer_execution_metadata",\n',
    '        ):\n',
    '            if key not in payload:\n',
    '                errors.append(f"missing shared-result field {key}")\n',
    '        try:\n',
    '            from core.multiscale_probabilistic_upgrade_20260618 import invariant_report\n',
    '            invariants = invariant_report(payload)\n',
    '            for name, valid in invariants.items():\n',
    '                if not valid:\n',
    '                    errors.append(f"shared-result invariant failed: {name}")\n',
    '        except Exception as exc:\n',
    '            errors.append(f"shared-result validation error: {exc}")\n',
    '    research = payload.get("research_calibration")\n',
    '    if isinstance(research, Mapping) and research:\n',
    '        try:\n',
    '            from core.research_calibration_20260618 import validate_research_invariants\n',
    '            research_invariants = validate_research_invariants(research)\n',
    '            for name, valid in research_invariants.items():\n',
    '                if not valid:\n',
    '                    errors.append(f"research-calibration invariant failed: {name}")\n',
    '            if str(research.get("last_completed_h1_timestamp")) != str(payload.get("latest_completed_candle_time")):\n',
    '                errors.append("research-calibration latest completed H1 time mismatch")\n',
    '            if not bool(research.get("causal_completed_candle_only")):\n',
    '                errors.append("research-calibration is not marked completed-candle-only")\n',
    '            if int(research.get("future_rows_used", 1) or 0) != 0:\n',
    '                errors.append("research-calibration reports future rows")\n',
    '        except Exception as exc:\n',
    '            errors.append(f"research-calibration validation error: {exc}")\n',
    '    advanced = payload.get("advanced_reliability_shift")\n',
    '    if isinstance(advanced, Mapping) and advanced:\n',
    '        try:\n',
    '            advanced_identity = advanced.get("identity") if isinstance(advanced.get("identity"), Mapping) else {}\n',
    '            expected_id = str(payload.get("canonical_calculation_id") or payload.get("run_id") or "")\n',
    '            if str(advanced_identity.get("calculation_id") or "") != expected_id:\n',
    '                errors.append("advanced-reliability calculation id mismatch")\n',
    '            if int(advanced_identity.get("generation") or 0) != int(payload.get("calculation_generation") or 0):\n',
    '                errors.append("advanced-reliability calculation generation mismatch")\n',
    '            if str(advanced_identity.get("latest_completed_h1_time")) != str(payload.get("latest_completed_candle_time")):\n',
    '                errors.append("advanced-reliability latest completed H1 time mismatch")\n',
    '            contract = advanced.get("input_contract") if isinstance(advanced.get("input_contract"), Mapping) else {}\n',
    '            if not bool(contract.get("completed_utc_h1_only")):\n',
    '                errors.append("advanced-reliability is not marked completed-UTC-H1-only")\n',
    '            policy = advanced.get("decision_policy") if isinstance(advanced.get("decision_policy"), Mapping) else {}\n',
    '            if bool(policy.get("direction_reversal_allowed", True)):\n',
    '                errors.append("advanced-reliability direction reversal policy is unsafe")\n',
    '        except Exception as exc:\n',
    '            errors.append(f"advanced-reliability validation error: {exc}")\n',
    '    authority = str((payload.get("metadata") or {}).get("primary_calculation_authority") or "")\n',
    '    if authority == "Full Metric Detail + History":\n',
    '        if str(payload.get("symbol") or "").upper() != "EURUSD":\n',
    '            errors.append("operational symbol must be EURUSD")\n',
    '        if str(payload.get("timeframe") or "").upper() != "H1":\n',
    '            errors.append("operational timeframe must be H1")\n',
    '        required_full_metric = (\n',
    '            "full_metric_snapshot", "full_metric_direction", "tradeability_decision",\n',
    '            "full_metric_current_row", "full_metric_history", "reverse_10_current",\n',
    '            "reverse_10_history", "canonical_priority_table", "top_two_daily_candidates",\n',
    '        )\n',
    '        for key in required_full_metric:\n',
    '            if key not in payload:\n',
    '                errors.append(f"missing {key}")\n',
    '        snapshot = payload.get("full_metric_snapshot") or {}\n',
    '        expected_time = payload.get("latest_completed_candle_time")\n',
    '        if isinstance(snapshot, Mapping) and str(snapshot.get("latest_completed_h1_time")) != str(expected_time):\n',
    '            errors.append("full metric latest completed H1 time mismatch")\n',
    '    return not errors, errors\n',
    '\n',
    '\n',
    'def canonical_identity(payload: Mapping[str, Any] | None) -> Dict[str, Any]:\n',
    '    p = payload if isinstance(payload, Mapping) else {}\n',
    '    market = p.get("market") if isinstance(p.get("market"), Mapping) else {}\n',
    '    return {\n',
    '        "run_id": p.get("run_id"),\n',
    '        "calculation_generation": p.get("calculation_generation"),\n',
    '        "data_signature": p.get("data_signature"),\n',
    '        "symbol": p.get("symbol"),\n',
    '        "timeframe": p.get("timeframe"),\n',
    '        "source": p.get("source"),\n',
    '        "latest_completed_candle_time": p.get("latest_completed_candle_time") or market.get("latest_completed_candle_time"),\n',
    '        "created_at": p.get("created_at"),\n',
    '        "expires_at": p.get("expires_at"),\n',
    '        "schema_version": p.get("schema_version"),\n',
    '        "calculation_version": p.get("calculation_version"),\n',
    '        "calculation_status": p.get("calculation_status"),\n',
    '        "checksum": p.get("checksum"),\n',
    '        "snapshot_schema_version": p.get("snapshot_schema_version"),\n',
    '    }\n',
    '\n',
    '\n',
    'def component_matches_canonical(component: Any, canonical: Mapping[str, Any]) -> Tuple[bool, list[str]]:\n',
    '    """Validate identity fields for a synchronized component."""\n',
    '    if not isinstance(component, Mapping):\n',
    '        return False, ["component is not a mapping"]\n',
    '    expected = canonical_identity(canonical)\n',
    '    reasons: list[str] = []\n',
    '    aliases = {"generation": "calculation_generation", "candle time": "latest_completed_candle_time"}\n',
    '    for label, key in aliases.items():\n',
    '        got = component.get(key, component.get(label))\n',
    '        if got not in (None, "") and str(got) != str(expected.get(key)):\n',
    '            reasons.append(f"{key} mismatch")\n',
    '    for key in ("run_id", "symbol", "timeframe", "source", "data_signature"):\n',
    '        got = component.get(key)\n',
    '        if got not in (None, "") and str(got) != str(expected.get(key)):\n',
    '            reasons.append(f"{key} mismatch")\n',
    '    return not reasons, reasons\n',
    '\n',
    '\n',
    'def validate_operational_component(component: Any, canonical: Mapping[str, Any]) -> Tuple[bool, list[str]]:\n',
    '    """Require every operational identity field, not merely compare present ones."""\n',
    '    if not isinstance(component, Mapping):\n',
    '        return False, ["component is not a mapping"]\n',
    '    expected = canonical_identity(canonical)\n',
    '    reasons: list[str] = []\n',
    '    for key in (\n',
    '        "run_id", "calculation_generation", "data_signature", "symbol", "timeframe",\n',
    '        "latest_completed_candle_time",\n',
    '    ):\n',
    '        got = component.get(key)\n',
    '        if got in (None, ""):\n',
    '            reasons.append(f"missing {key}")\n',
    '        elif str(got) != str(expected.get(key)):\n',
    '            reasons.append(f"{key} mismatch")\n',
    '    return not reasons, reasons\n',
    '\n',
    '\n',
    'def component_freshness_guard(component: Any, canonical: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    """Validate one supporting component and return a safe operational action.\n',
    '\n',
    '    Stale or incomplete supporting evidence is never mixed silently with the\n',
    '    current Full Metric generation.  The canonical directional view is retained\n',
    '    for explanation, but entry permission becomes WAIT until identities match.\n',
    '    """\n',
    '    canonical_ok, canonical_errors = validate_canonical_result(dict(canonical or {}))\n',
    '    if not canonical_ok:\n',
    '        return {\n',
    '            "ok": False, "status": "CANONICAL NOT READY", "reasons": canonical_errors,\n',
    '            "safe_action": "WAIT", "directional_view": "WAIT",\n',
    '        }\n',
    '    ok, reasons = validate_operational_component(component, canonical)\n',
    '    final = canonical.get("final_decision") if isinstance(canonical.get("final_decision"), Mapping) else {}\n',
    '    direction = str(final.get("directional_market_view") or canonical.get("full_metric_direction") or "WAIT").upper()\n',
    '    tradeability = str(final.get("tradeability_decision") or canonical.get("tradeability_decision") or "WAIT").upper()\n',
    '    return {\n',
    '        "ok": bool(ok),\n',
    '        "status": "CURRENT" if ok else "STALE / MISMATCHED",\n',
    '        "reasons": list(reasons),\n',
    '        "safe_action": tradeability if ok and tradeability in {"BUY", "SELL"} else "WAIT",\n',
    '        "directional_view": direction if direction in {"BUY", "SELL"} else "WAIT",\n',
    '        **canonical_identity(canonical),\n',
    '    }\n',
    '\n',
    '\n',
    'def _source_meta(canonical: Mapping[str, Any], component: str) -> Dict[str, Any]:\n',
    '    meta = canonical_identity(canonical)\n',
    '    meta.update({\n',
    '        "adapter": component,\n',
    '        "accepted_legacy_source_keys": list(ADAPTER_SPECS.get(component, {}).get("accepted_legacy_source_keys", ())),\n',
    '        "source_timestamp": canonical.get("created_at"),\n',
    '        "validation_status": "VALID",\n',
    '    })\n',
    '    return meta\n',
    '\n',
    '\n',
    'def _canonical_priority_frame(priority_table: Any, canonical: Mapping[str, Any]):\n',
    '    if not _is_df(priority_table):\n',
    '        return pd.DataFrame() if pd is not None else priority_table\n',
    '    table = priority_table\n',
    '    identity = canonical_identity(canonical)\n',
    '    stamp = {\n',
    '        "run_id": identity["run_id"],\n',
    '        "generation": identity["calculation_generation"],\n',
    '        "calculation_generation": identity["calculation_generation"],\n',
    '        "data_signature": identity["data_signature"],\n',
    '        "symbol": identity["symbol"],\n',
    '        "timeframe": identity["timeframe"],\n',
    '        "source": identity["source"],\n',
    '        "latest_completed_candle_time": identity["latest_completed_candle_time"],\n',
    '        "data-quality status": (canonical.get("data_quality") or {}).get("status", "UNKNOWN"),\n',
    '    }\n',
    '    # One controlled copy prevents mutating the source table while avoiding many\n',
    '    # renderer-level copies later.\n',
    '    table = table.copy(deep=False)\n',
    '    for key, value in stamp.items():\n',
    '        table[key] = value\n',
    '\n',
    '    def first_existing(*names: str):\n',
    '        return next((table[name] for name in names if name in table.columns), None)\n',
    '\n',
    '    aliases = {\n',
    '        "candle time": first_existing("Time", "time", "latest_completed_candle_time"),\n',
    '        "hour": first_existing("Hour", "hour"),\n',
    '        "regime": first_existing("Major Regime", "Regime", "regime"),\n',
    '        "regime reliability": first_existing("Reliability %", "Reliability", "regime reliability"),\n',
    '        "prediction direction": first_existing("Direction", "Prediction Direction", "prediction direction", "Decision"),\n',
    '        "KNN score": first_existing("KNN Score /10", "KNN Score", "Priority Score"),\n',
    '        "Greedy score": first_existing("Greedy Score /10", "Greedy Score", "Priority Score"),\n',
    '        "combined score": first_existing("Priority Score", "Combined Score", "combined score"),\n',
    '        "priority rank": first_existing("Priority Rank", "priority rank", "Ascending Priority", "KNN Priority"),\n',
    '        "less-risky bias": first_existing("Less Risky Bias", "less-risky bias", "Decision"),\n',
    '        "qualification status": first_existing("Qualification Status", "qualification status"),\n',
    '        "blocking reason": first_existing("Blocking Reason", "blocking reason"),\n',
    '    }\n',
    '    for name, values in aliases.items():\n',
    '        if values is not None:\n',
    '            table[name] = values\n',
    '    if "priority label" not in table.columns:\n',
    '        rank_source = table["priority rank"] if "priority rank" in table.columns else pd.Series(14.0, index=table.index, dtype=float)\n',
    '        ranks = pd.to_numeric(rank_source, errors="coerce").fillna(14)\n',
    '        table["priority label"] = ranks.map(lambda rank: "A+" if rank <= 3 else "A" if rank <= 6 else "B" if rank <= 9 else "C" if rank <= 12 else "AVOID")\n',
    '    if "conflict status" not in table.columns:\n',
    '        canonical_direction = str((canonical.get("final_decision") or {}).get("directional_market_view") or "WAIT").upper()\n',
    '        row_direction = table.get("prediction direction", pd.Series("WAIT", index=table.index)).astype(str).str.upper()\n',
    '        table["conflict status"] = row_direction.map(lambda value: "ALIGNED" if value in {canonical_direction, "WAIT"} or canonical_direction == "WAIT" else "CONFLICT")\n',
    '    return table\n',
    '\n',
    '\n',
    'def build_shared_adapter(\n',
    '    state: Mapping[str, Any], canonical: Mapping[str, Any], legacy_shared: Optional[Mapping[str, Any]] = None,\n',
    '    priority_table: Any = None,\n',
    ') -> Dict[str, Any]:\n',
    '    """Create one-way legacy views derived from the authoritative canonical run."""\n',
    '    legacy = dict(legacy_shared or {})\n',
    '    final = dict(canonical.get("final_decision") or {})\n',
    '    market = dict(canonical.get("market") or {})\n',
    '    regime = dict(canonical.get("regime") or {})\n',
    '    reliability = dict(canonical.get("reliability") or {})\n',
    '    nlp = dict(canonical.get("nlp") or {})\n',
    '    priority = dict(canonical.get("priority") or {})\n',
    '    forecasts = dict(canonical.get("forecasts") or {})\n',
    '    horizons = dict(forecasts.get("horizons") or {})\n',
    '    multiscale = dict(canonical.get("multiscale_regime") or {})\n',
    '    probabilistic = dict(canonical.get("probabilistic_projection") or {})\n',
    '    validation_metrics = dict(canonical.get("validation_metrics") or {})\n',
    '    meta_labels = dict(canonical.get("meta_labels") or {})\n',
    '    layer_metadata = list(canonical.get("layer_execution_metadata") or [])\n',
    '    feature_weights = list(canonical.get("dynamic_feature_weights") or [])\n',
    '    decomposition = dict(canonical.get("forecast_decomposition") or {})\n',
    '    temporal_patches = dict(canonical.get("temporal_patches") or {})\n',
    '    research = dict(canonical.get("research_calibration") or {})\n',
    '    research_risk = dict(canonical.get("research_risk_stack") or {})\n',
    '    research_risk_summary = dict(research_risk.get("current_summary") or {})\n',
    '    advanced_reliability = dict(canonical.get("advanced_reliability_shift") or {})\n',
    '    ten_paper_research = dict(canonical.get("ten_paper_research_20260621") or {})\n',
    '    quant_research_v3 = dict(canonical.get("quant_research_v3") or {})\n',
    '    quant_v3_summary = dict(quant_research_v3.get("summary") or {})\n',
    '    quant_v3_identity = dict(quant_research_v3.get("identity") or {})\n',
    '    quant_research_v4 = dict(canonical.get("quant_research_v4") or {})\n',
    '    quant_v4_summary = dict(quant_research_v4.get("summary") or {})\n',
    '    quant_v4_identity = dict(quant_research_v4.get("identity") or {})\n',
    '    quant_research_v7 = dict(canonical.get("quant_research_v7") or {})\n',
    '    quant_v7_summary = dict(quant_research_v7.get("summary") or {})\n',
    '    quant_v7_identity = dict(quant_research_v7.get("identity") or {})\n',
    '    ten_paper_reject = dict(ten_paper_research.get("paper_3") or {})\n',
    '    ten_paper_explanations = dict(ten_paper_research.get("paper_5") or {})\n',
    '    advanced_identity = dict(advanced_reliability.get("identity") or {})\n',
    '    advanced_crc = dict(advanced_reliability.get("conformal_risk_control") or {})\n',
    '    advanced_mmd = dict(advanced_reliability.get("mmd") or {})\n',
    '    advanced_rrcf = dict(advanced_reliability.get("rrcf") or {})\n',
    '    advanced_multicalibration = dict(advanced_reliability.get("multicalibration") or {})\n',
    '    similar_day = dict(canonical.get("similar_day_intelligence") or {})\n',
    '    similar_day_summary = dict(similar_day.get("summary") or {})\n',
    '    regime_transition_trust = dict(canonical.get("regime_transition_trust_center") or {})\n',
    '    research_uncertainty = dict(research.get("uncertainty") or {})\n',
    '    research_change = dict(research.get("bayesian_changepoint") or {})\n',
    '    research_windows = dict(research.get("adaptive_windows") or {})\n',
    '    research_conformal = dict(research.get("conformal_prediction") or {})\n',
    '    research_coverage = dict(research.get("adaptive_coverage") or {})\n',
    '    research_dma = dict(research.get("dynamic_model_averaging") or {})\n',
    '    research_cset = dict(research.get("conditional_method_confidence_set") or {})\n',
    '    research_baselines = dict(research.get("baseline_forecasts") or {})\n',
    '    research_skill = dict(research.get("baseline_skill") or {})\n',
    '    research_reliability = dict(research.get("research_reliability") or {})\n',
    '    selected = int(final.get("selected_horizon") or forecasts.get("selected_horizon") or 3)\n',
    '    selected_forecast = dict(horizons.get(f"{selected}h") or {})\n',
    '    table = _canonical_priority_frame(priority_table, canonical)\n',
    '    if not _is_df(table):\n',
    '        existing = state.get("canonical_priority_table_20260617")\n',
    '        table = _canonical_priority_frame(existing, canonical) if _is_df(existing) else (pd.DataFrame() if pd is not None else None)\n',
    '\n',
    '    identity = canonical_identity(canonical)\n',
    '    full_metric = dict(canonical.get("full_metric_snapshot") or {})\n',
    '    top_two = list(canonical.get("top_two_daily_candidates") or full_metric.get("top_two_daily_candidates") or [])\n',
    '    current = {\n',
    '        "symbol": canonical.get("symbol"), "timeframe": canonical.get("timeframe"), "source": canonical.get("source"),\n',
    '        "latest_completed_h1_time": canonical.get("latest_completed_candle_time"),\n',
    '        "latest_completed_candle_time": canonical.get("latest_completed_candle_time"),\n',
    '        "last_close": canonical.get("last_close", market.get("current_price")),\n',
    '        "regime": canonical.get("current_major_regime", regime.get("major_regime", "UNKNOWN")),\n',
    '        "regime_direction": canonical.get("full_metric_direction", final.get("directional_market_view", "WAIT")),\n',
    '        "full_metric_direction": canonical.get("full_metric_direction", final.get("directional_market_view", "WAIT")),\n',
    '        "prediction_direction": selected_forecast.get("direction", "WAIT"),\n',
    '        "decision": final.get("final_decision", "DATA NOT READY"),\n',
    '        "tradeability_decision": final.get("tradeability_decision", "WAIT"),\n',
    '        "less_risky_decision": final.get("less_risky_decision", "WAIT"),\n',
    '        "master_score": canonical.get("master_score"), "entry_score": canonical.get("entry_score"),\n',
    '        "buy_score": canonical.get("buy_score"), "sell_score": canonical.get("sell_score"),\n',
    '        "hold_safety": canonical.get("hold_safety"), "tp_quality": canonical.get("tp_quality"),\n',
    '        "exit_risk": canonical.get("exit_risk"), "pullback_readiness": canonical.get("pullback_readiness"),\n',
    '        "trend_capacity_remaining": canonical.get("trend_capacity_remaining"),\n',
    '        "m1_confirmation": canonical.get("m1_confirmation"),\n',
    '        "forecast_close": selected_forecast.get("point_forecast"),\n',
    '        "forecast_confidence": final.get("calibrated_confidence"),\n',
    '        "reliability": reliability.get("score"), "uncertainty": final.get("uncertainty_pct"),\n',
    '        "error_estimate": final.get("error_estimate_pct"),\n',
    '        "blocking_reasons": list(final.get("blocking_reasons") or []),\n',
    '        "selected_horizon": selected,\n',
    '        "decision_policy": final.get("main_reason", ""),\n',
    '        "top_two_daily_candidates": top_two,\n',
    '        "run_id": canonical.get("run_id"), "calculation_generation": canonical.get("calculation_generation"),\n',
    '        "data_signature": canonical.get("data_signature"),\n',
    '        "canonical_calculation_id": canonical.get("canonical_calculation_id"),\n',
    '        "volatility_regime": multiscale.get("current_volatility_regime"),\n',
    '        "combined_regime": multiscale.get("combined_existing_and_volatility_regime"),\n',
    '        "regime_entropy": multiscale.get("mean_normalized_entropy"),\n',
    '        "regime_transition_risk_pct": multiscale.get("multi_scale_transition_risk_pct"),\n',
    '        "multi_scale_agreement_score": multiscale.get("multi_scale_agreement_score_0_10"),\n',
    '        "meta_labels": meta_labels,\n',
    '        "research_calculation_id": research.get("canonical_calculation_id"),\n',
    '        "research_reliability": research_reliability.get("calibrated_score_0_100"),\n',
    '        "aleatoric_uncertainty": research_uncertainty.get("aleatoric_uncertainty_0_100"),\n',
    '        "epistemic_uncertainty": research_uncertainty.get("epistemic_uncertainty_0_100"),\n',
    '        "combined_uncertainty": research_uncertainty.get("combined_uncertainty_0_100"),\n',
    '        "transition_risk": research_change.get("transition_risk_0_100"),\n',
]
