"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        "transition_window": research_change.get("estimated_transition_window"),\n',
    '        "research_validation_status": research.get("validation_status"),\n',
    '        "required_confidence_threshold": research_risk_summary.get("required_confidence_threshold"),\n',
    '        "selective_prediction_pass": research_risk_summary.get("selective_prediction_pass"),\n',
    '        "tp_first_probability": research_risk_summary.get("tp_first_probability"),\n',
    '        "sl_first_probability": research_risk_summary.get("sl_first_probability"),\n',
    '        "robust_expected_value": research_risk_summary.get("robust_expected_value"),\n',
    '        "extreme_risk_block": research_risk_summary.get("extreme_risk_block"),\n',
    '        "display_risk_multiplier": research_risk_summary.get("display_risk_multiplier"),\n',
    '        "similar_day_index": similar_day_summary.get("Best Similarity Index"),\n',
    '        "similar_day_result": similar_day_summary.get("Weighted historical result"),\n',
    '        "similar_day_reliability": similar_day_summary.get("Similar-day reliability"),\n',
    '        "similar_day_conflict": similar_day.get("conflict_warning"),\n',
    '        "advanced_research_status": advanced_reliability.get("research_confidence_status"),\n',
    '        "advanced_trust_cap_pct": advanced_reliability.get("trust_cap_pct"),\n',
    '        "advanced_crc_status": advanced_crc.get("status"),\n',
    '        "advanced_crc_risk_upper_bound": advanced_crc.get("risk_upper_bound"),\n',
    '        "advanced_crc_threshold": advanced_crc.get("threshold"),\n',
    '        "advanced_multicalibrated_probability": advanced_multicalibration.get("calibrated_probability"),\n',
    '        "advanced_mmd_severity": advanced_mmd.get("severity"),\n',
    '        "advanced_market_anomaly_score": advanced_rrcf.get("market_anomaly_score"),\n',
    '        "advanced_system_anomaly_score": advanced_rrcf.get("system_anomaly_score"),\n',
    '        "advanced_research_calculation_id": advanced_identity.get("calculation_id"),\n',
    '        "ten_paper_research_status": ten_paper_research.get("status"),\n',
    '        "ten_paper_research_mode": ten_paper_research.get("mode"),\n',
    '        "ten_paper_shadow_decision": ten_paper_reject.get("shadow_reject_option_decision"),\n',
    '        "ten_paper_transaction_id": ten_paper_research.get("transaction_id"),\n',
    '        "quant_v3_status": quant_v3_summary.get("overall_quant_v3_status"),\n',
    '        "quant_v3_mode": quant_research_v3.get("mode"),\n',
    '        "quant_v3_source_generation_id": quant_v3_identity.get("source_generation_id"),\n',
    '        "quant_v3_risk_multiplier": quant_v3_summary.get("cvar_risk_multiplier"),\n',
    '        "quant_v3_density_test": quant_v3_summary.get("density_test"),\n',
    '        "quant_v4_status": quant_v4_summary.get("overall_status"),\n',
    '        "quant_v4_mode": "SHADOW",\n',
    '        "quant_v4_source_generation_id": quant_v4_identity.get("source_generation_id"),\n',
    '        "quant_v4_direction_skill": quant_v4_summary.get("direction_skill"),\n',
    '        "quant_v4_interval_coverage": quant_v4_summary.get("interval_conditional_coverage"),\n',
    '        "quant_v4_transition_risk_6h": quant_v4_summary.get("transition_risk_6h"),\n',
    '        "quant_v4_tail_risk_backtest": quant_v4_summary.get("tail_risk_backtest"),\n',
    '        "quant_v4_sequential_monitor": quant_v4_summary.get("sequential_monitor"),\n',
    '    }\n',
    '    old_powerbi = legacy.get("powerbi") if isinstance(legacy.get("powerbi"), dict) else {}\n',
    '    old_nlp = legacy.get("nlp") if isinstance(legacy.get("nlp"), dict) else {}\n',
    '    old_data_mining = legacy.get("data_mining") if isinstance(legacy.get("data_mining"), dict) else {}\n',
    '    old_history = legacy.get("history") if isinstance(legacy.get("history"), dict) else {}\n',
    '    old_market = legacy.get("market") if isinstance(legacy.get("market"), dict) else {}\n',
    '    old_decision = legacy.get("decision") if isinstance(legacy.get("decision"), dict) else {}\n',
    '    old_regime = legacy.get("regime") if isinstance(legacy.get("regime"), dict) else {}\n',
    '    false_reversal_risk = old_decision.get("false_reversal_risk") or legacy.get("false_reversal_risk") or {}\n',
    '    window_analytics = old_regime.get("window_analytics") or legacy.get("regime_window_analytics") or {}\n',
    '\n',
    '    adapter = {\n',
    '        "version": "20260618_full_metric_canonical_adapter_v2",\n',
    '        "built_at": canonical.get("created_at"),\n',
    '        "signature": canonical.get("data_signature"),\n',
    '        # Keep one immutable reference; a shallow top-level duplicate made every\n',
    '        # adapter generation retain another large canonical container.\n',
    '        "canonical": canonical,\n',
    '        **canonical_identity(canonical),\n',
    '        "current": current,\n',
    '        "market": {**old_market, **current, "latest_completed_candle_time": market.get("latest_completed_candle_time"), "row_count": market.get("row_count"), "adapter_meta": _source_meta(canonical, "market")},\n',
    '        "decision": {**identity, "central_decision": final.get("final_decision"), "directional_market_view": final.get("directional_market_view"), "tradeability_decision": final.get("tradeability_decision"), "less_risky_decision": final.get("less_risky_decision"), "blocking_reasons": list(final.get("blocking_reasons") or []), "selected_horizon": selected, "false_reversal_risk": false_reversal_risk, "adapter_meta": _source_meta(canonical, "metric")},\n',
    '        "regime": {**identity, "current": regime.get("major_regime"), "direction": final.get("directional_market_view"), "alpha_delta": {"alpha": regime.get("alpha"), "delta": regime.get("delta"), "delta_acceleration": regime.get("delta_acceleration")}, "standards": {"lower": regime.get("lower_standard_regime"), "middle": regime.get("middle_standard_regime"), "higher": regime.get("higher_standard_regime")}, "window_analytics": window_analytics, "volatility_regime": multiscale.get("current_volatility_regime"), "combined_regime": multiscale.get("combined_existing_and_volatility_regime"), "scales": multiscale.get("scales", {}), "joint_27_state_probabilities": multiscale.get("joint_27_state_probabilities", []), "entropy": multiscale.get("mean_normalized_entropy"), "transition_risk_pct": multiscale.get("multi_scale_transition_risk_pct"), "agreement_score_0_10": multiscale.get("multi_scale_agreement_score_0_10"), "bayesian_changepoint": research_change, "adaptive_windows": research_windows, "research_transition_risk_0_100": research_change.get("transition_risk_0_100"), "estimated_transition_window": research_change.get("estimated_transition_window"), "adapter_meta": _source_meta(canonical, "regime")},\n',
    '        "priority": {**identity, "table": table, "best": table.iloc[0].to_dict() if _is_df(table) and not table.empty else priority, "top_two": top_two, "summary": priority, "research_refinements": canonical.get("research_score_refinements", {}), "knn_neighbor_quality": (canonical.get("research_score_refinements") or {}).get("knn_neighbor_quality", {}), "greedy_calibration_inputs": (canonical.get("research_score_refinements") or {}).get("greedy_inputs", {}), "adapter_meta": _source_meta(canonical, "priority")},\n',
    '        "hourly_priority_table": table,\n',
    '        "reliability": {**reliability, **identity, "selected_horizon": selected, "selected_horizon_validation": (reliability.get("validation_by_horizon") or {}).get(f"{selected}h", {}), "selected_horizon_calibration": (reliability.get("calibration_by_horizon") or {}).get(f"{selected}h", {}), "validation_metrics": validation_metrics, "regime_entropy": multiscale.get("mean_normalized_entropy"), "transition_risk_pct": multiscale.get("multi_scale_transition_risk_pct"), "agreement_score_0_10": multiscale.get("multi_scale_agreement_score_0_10"), "research_calibrated_score": research_reliability.get("calibrated_score_0_100"), "research_components": research_reliability.get("components", {}), "adaptive_coverage": research_coverage, "uncertainty_separation": research_uncertainty, "pbo": research.get("pbo", {}), "dsr": research.get("dsr", {}), "baseline_skill": research_skill, "research_risk_stack": research_risk, "advanced_reliability_shift": advanced_reliability, "adapter_meta": _source_meta(canonical, "reliability")},\n',
    '        "reliability_calibration": reliability,\n',
    '        "powerbi": {**old_powerbi, **identity, "forecast_close": selected_forecast.get("point_forecast"), "lower_bound": selected_forecast.get("lower_bound"), "upper_bound": selected_forecast.get("upper_bound"), "direction": selected_forecast.get("direction"), "canonical_direction": final.get("directional_market_view"), "tradeability_decision": final.get("tradeability_decision"), "selected_horizon": selected, "probabilistic_projection": probabilistic, "forecast_decomposition": decomposition, "dynamic_feature_weights": feature_weights, "volatility_regime": multiscale.get("current_volatility_regime"), "run_id": canonical.get("run_id"), "calculation_generation": canonical.get("calculation_generation"), "data_signature": canonical.get("data_signature"), "latest_completed_candle_time": canonical.get("latest_completed_candle_time"), "conformal_prediction": research_conformal, "adaptive_coverage": research_coverage, "dynamic_model_averaging": research_dma, "conditional_model_set": research_cset, "challenger_baselines": research_baselines, "baseline_skill": research_skill, "research_calculation_id": research.get("canonical_calculation_id"), "research_risk_stack": research_risk, "advanced_reliability_shift": advanced_reliability, "adapter_meta": _source_meta(canonical, "powerbi")},\n',
    '        "nlp": {**old_nlp, **identity, "summary": {**(old_nlp.get("summary") or {}), "nlp_direction": nlp.get("direction", "WAIT"), "reliability": nlp.get("reliability", 0), "conflict_level": nlp.get("conflict_level", "NONE"), "latest_rank_1_news": nlp.get("latest_headline", "No relevant news"), "news_time": nlp.get("latest_time"), "less_risky_decision": final.get("less_risky_decision", "WAIT")}, "adapter_meta": _source_meta(canonical, "nlp")},\n',
    '        "data_mining": {**old_data_mining, **identity, "temporal_patches": temporal_patches, "dynamic_feature_weights": feature_weights, "validation_metrics": validation_metrics, "layer_execution_metadata": layer_metadata, "ten_paper_research_calibration": research, "advanced_reliability_shift": advanced_reliability, "ten_paper_research_20260621": ten_paper_research, "adapter_meta": _source_meta(canonical, "data_mining")},\n',
    '        "history": {**old_history, **identity, "priority": table, "adapter_meta": _source_meta(canonical, "prediction_history")},\n',
    '        "prediction_feedback": legacy.get("prediction_feedback", {}),\n',
    '        "regime_alpha_delta": {"alpha": regime.get("alpha"), "delta": regime.get("delta"), "delta_acceleration": regime.get("delta_acceleration")},\n',
    '        "false_reversal_risk": false_reversal_risk,\n',
    '        "regime_window_analytics": window_analytics,\n',
    '        "full_metric_snapshot": full_metric,\n',
    '        "full_metric_history": canonical.get("full_metric_history", []),\n',
    '        "reverse_10_current": canonical.get("reverse_10_current", []),\n',
    '        "reverse_10_history": canonical.get("reverse_10_history", {}),\n',
    '        "top_two_daily_candidates": top_two,\n',
    '        "shared_result_schema_version": canonical.get("shared_result_schema_version"),\n',
    '        "canonical_calculation_id": canonical.get("canonical_calculation_id"),\n',
    '        "multiscale_regime": multiscale,\n',
    '        "probabilistic_projection": probabilistic,\n',
    '        "forecast_decomposition": decomposition,\n',
    '        "dynamic_feature_weights": feature_weights,\n',
    '        "temporal_patches": temporal_patches,\n',
    '        "validation_metrics": validation_metrics,\n',
    '        "meta_labels": meta_labels,\n',
    '        "layer_execution_metadata": layer_metadata,\n',
    '        "research_calibration": research,\n',
    '        "research_risk_stack": research_risk,\n',
    '        "advanced_reliability_shift": advanced_reliability,\n',
    '        "similar_day_intelligence": similar_day,\n',
    '        "regime_transition_trust_center": regime_transition_trust,\n',
    '        "ten_paper_research_20260621": ten_paper_research,\n',
    '        "quant_research_v4": quant_research_v4,\n',
    '        "quant_research_v7": quant_research_v7,\n',
    '        "research_calculation_id": research.get("canonical_calculation_id"),\n',
    '        "ai_grounding": {"first_decision": final.get("final_decision"), "decision": final.get("final_decision"), "directional_market_view": final.get("directional_market_view"), "tradeability_decision": final.get("tradeability_decision"), "less_risky_decision": final.get("less_risky_decision"), "blocking_reasons": list(final.get("blocking_reasons") or []), "regime": regime.get("major_regime"), "alpha": regime.get("alpha"), "delta": regime.get("delta"), "prediction_direction": selected_forecast.get("direction"), "prediction_range": {"point": selected_forecast.get("point_forecast"), "lower": selected_forecast.get("lower_bound"), "upper": selected_forecast.get("upper_bound")}, "selected_horizon": selected, "full_metric_scores": {"master": canonical.get("master_score"), "entry": canonical.get("entry_score"), "buy": canonical.get("buy_score"), "sell": canonical.get("sell_score"), "hold": canonical.get("hold_safety"), "tp": canonical.get("tp_quality"), "exit_risk": canonical.get("exit_risk")}, "top_two_daily_candidates": top_two, "reliability_score": reliability.get("score", 0), "uncertainty": final.get("uncertainty_pct"), "error_estimate": final.get("error_estimate_pct"), "nlp_impact": nlp, "research_confirmation": canonical.get("research_confirmation", {}), "research_risk_stack": research_risk, "advanced_reliability_shift": advanced_reliability, "advanced_trust_cap_pct": advanced_reliability.get("trust_cap_pct"), "advanced_crc_status": advanced_crc.get("status"), "advanced_mmd_severity": advanced_mmd.get("severity"), "volatility_regime": multiscale.get("current_volatility_regime"), "regime_entropy": multiscale.get("mean_normalized_entropy"), "transition_risk_pct": multiscale.get("multi_scale_transition_risk_pct"), "multi_scale_agreement_score": multiscale.get("multi_scale_agreement_score_0_10"), "meta_labels": meta_labels, "probabilistic_projection": probabilistic, "research_calibration_id": research.get("canonical_calculation_id"), "research_reliability": research_reliability.get("calibrated_score_0_100"), "uncertainty_separation": research_uncertainty, "bayesian_changepoint": research_change, "conformal_prediction": research_conformal, "baseline_skill": research_skill, "data_quality_score": (canonical.get("data_quality") or {}).get("score", 0), "similar_day_summary": similar_day_summary, "similar_day_reliability": similar_day.get("reliability"), "similar_day_conflict_warning": similar_day.get("conflict_warning"), "regime_transition_trust_center": regime_transition_trust, "ten_paper_research_status": ten_paper_research.get("status"), "ten_paper_shadow_decision": ten_paper_reject.get("shadow_reject_option_decision"), "ten_paper_explanations": ten_paper_explanations, "quant_research_v3_summary": quant_v3_summary, "quant_research_v3_identity": quant_v3_identity, "quant_research_v3_limitations": list(quant_research_v3.get("limitations") or []), "quant_research_v4_summary": quant_v4_summary, "quant_research_v4_identity": quant_v4_identity, "quant_research_v4_errors": list(quant_research_v4.get("errors") or []), "quant_research_v7_summary": quant_v7_summary, "quant_research_v7_identity": quant_v7_identity, "quant_research_v7_evidence": canonical.get("quant_research_v7_ai_evidence", {}), "latest_completed_h1_time": canonical.get("latest_completed_candle_time"), "latest_completed_candle_time": canonical.get("latest_completed_candle_time"), "run_id": canonical.get("run_id"), "calculation_generation": canonical.get("calculation_generation"), "data_signature": canonical.get("data_signature"), "symbol": canonical.get("symbol"), "timeframe": canonical.get("timeframe"), "adapter_meta": _source_meta(canonical, "ai_grounding")},\n',
    '        "adapter_specs": deepcopy(ADAPTER_SPECS),\n',
    '        "metadata": {"calculation_source": "canonical_decision_result_20260617", "one_way_legacy_adapter": True, **canonical_identity(canonical)},\n',
    '    }\n',
    '    return adapter\n',
    '\n',
    '\n',
    'def publish_canonical_atomically(\n',
    '    state: MutableMapping[str, Any], canonical: Dict[str, Any], *, legacy_shared: Optional[Mapping[str, Any]] = None,\n',
    '    priority_table: Any = None,\n',
    '    history_bundle: Optional[Mapping[str, Any]] = None,\n',
    ') -> Dict[str, Any]:\n',
    '    """Validate staging data and publish all synchronized keys as one generation.\n',
    '\n',
    '    The last valid canonical run remains untouched if validation fails.\n',
    '    """\n',
    '    ok, errors = validate_canonical_result(canonical)\n',
    '    if not ok:\n',
    '        state["canonical_publish_error_20260617"] = errors\n',
    '        state.pop(STAGING_KEY, None)\n',
    '        raise ValueError("Canonical validation failed: " + "; ".join(errors))\n',
    '    generation = int(canonical["calculation_generation"])\n',
    '    table = _canonical_priority_frame(priority_table, canonical)\n',
    '    canonical = dict(canonical)\n',
    '    if _is_df(table):\n',
    '        priority_records = table.to_dict("records")\n',
    '        canonical["priority_table"] = priority_records\n',
    '        canonical["canonical_priority_table"] = priority_records\n',
    '\n',
    '    # External architecture only: stamp, checksum, freeze, and atomically persist\n',
    '    # the completed generation before publishing any UI/session pointer. Protected\n',
    '    # calculation values are not recalculated or changed here.\n',
    '    from core.snapshot_schema_20260619 import (\n',
    '        SNAPSHOT_KEY, SCHEMA_VERSION as SNAPSHOT_SCHEMA_VERSION,\n',
    '        build_run_snapshot, canonical_checksum,\n',
    '    )\n',
    '    canonical.setdefault("calculation_completed_at", _utc_now_iso())\n',
    '    canonical["snapshot_schema_version"] = SNAPSHOT_SCHEMA_VERSION\n',
    '    canonical["checksum"] = canonical_checksum(canonical)\n',
    '    run_snapshot = build_run_snapshot(canonical)\n',
    '    snapshot_commit_started = time.perf_counter()\n',
    '    try:\n',
    '        from services.canonical_snapshot_store import commit_snapshot\n',
    '        commit_snapshot(run_snapshot, history_bundle=dict(history_bundle or {}))\n',
    '    except Exception as exc:\n',
    '        state["canonical_publish_error_20260617"] = [f"snapshot atomic commit failed: {exc}"]\n',
    '        state.pop(STAGING_KEY, None)\n',
    '        raise\n',
    '    try:\n',
    '        from services.tracing import record\n',
    '        record(\n',
    '            state, run_id=run_snapshot.run_id, generation=run_snapshot.generation,\n',
    '            stage="snapshot_commit", started_at=run_snapshot.calculation_completed_at,\n',
    '            ended_at=_utc_now_iso(), duration_ms=(time.perf_counter()-snapshot_commit_started)*1000,\n',
    '            success=True, rows_processed=int(len(table)) if hasattr(table, "__len__") else 0,\n',
    '            cache_status="MISS", detail="Atomic canonical snapshot committed",\n',
    '        )\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '    adapter = build_shared_adapter(state, canonical, legacy_shared=legacy_shared, priority_table=table)\n',
    '    adapter["run_snapshot"] = run_snapshot\n',
    '    adapter["risk_plan"] = canonical.get("risk_plan", {})\n',
    '    staging = {"canonical": canonical, "adapter": adapter, "priority_table": table, "published_at": _utc_now_iso()}\n',
    '    state[STAGING_KEY] = staging\n',
    '\n',
    '    # Compatibility values are references to the same validated objects; they are\n',
    '    # not separately recalculated copies.\n',
    '    state["canonical_priority_table_20260617"] = table\n',
    '    state["adx_hourly_priority_calibrated_20260615"] = table\n',
    '    state["three_center_priority_sorted_20260614"] = table\n',
    '    state["reliability_dynamic_priority_table_20260614"] = table\n',
    '    state[SHARED_KEY] = adapter\n',
    '    state[LEGACY_SHARED_KEY] = adapter\n',
    '    state[SNAPSHOT_KEY] = run_snapshot\n',
    '    state["canonical_decision_result"] = canonical\n',
    '    state[LAST_VALID_KEY] = canonical\n',
    '    state[GENERATION_KEY] = generation\n',
    '    # Authoritative pointer is written last.\n',
    '    state[CANONICAL_KEY] = canonical\n',
    '    # Build the small display/AI projection once, after atomic publication.\n',
    '    # Failure here is optional and may never invalidate the protected result.\n',
    '    try:\n',
    '        from core.compact_canonical_20260619 import publish_compact_runtime\n',
    '        evidence = table.head(40).to_dict("records") if _is_df(table) and not table.empty else []\n',
    '        summary, fact_pack = publish_compact_runtime(state, canonical, adapter, evidence_rows=evidence)\n',
    '        from core.performance_store_20260619 import persist_summary\n',
    '        persist_summary(str(summary.get("calculation_id")), summary, fact_pack)\n',
    '    except Exception as exc:\n',
    '        state["compact_runtime_optional_error_20260619"] = str(exc)\n',
    '    state["canonical_publish_error_20260617"] = []\n',
    '    state.pop(STAGING_KEY, None)\n',
    '    return adapter\n',
    '\n',
    '\n',
    'def get_canonical(state: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    current = state.get(CANONICAL_KEY)\n',
    '    if isinstance(current, dict) and validate_canonical_result(current)[0]:\n',
    '        return current\n',
    '    previous = state.get(LAST_VALID_KEY)\n',
    '    return previous if isinstance(previous, dict) and validate_canonical_result(previous)[0] else {}\n',
    '\n',
    '\n',
    'def begin_rerun(state: MutableMapping[str, Any]) -> int:\n',
    '    try:\n',
    '        value = int(state.get("app_rerun_identifier_20260617", 0) or 0) + 1\n',
    '    except Exception:\n',
    '        value = 1\n',
    '    state["app_rerun_identifier_20260617"] = value\n',
    '    state["shared_sync_calls_this_rerun_20260617"] = 0\n',
    '    state["navigation_authoritative_20260617"] = False\n',
    '    return value\n',
    '\n',
    '\n',
    'def build_runtime_context(state: MutableMapping[str, Any], *, active_page: str, active_subpage: str, phone_mode: bool) -> Dict[str, Any]:\n',
    '    canonical = get_canonical(state)\n',
    '    identity = canonical_identity(canonical)\n',
    '    context = {\n',
    '        "rerun_identifier": state.get("app_rerun_identifier_20260617", 0),\n',
    '        "active_page": active_page,\n',
    '        "active_subpage": active_subpage,\n',
    '        "phone_mode": bool(phone_mode),\n',
    '        "canonical_result": canonical,\n',
    '        "canonical_run_id": identity.get("run_id"),\n',
    '        "canonical_generation": identity.get("calculation_generation"),\n',
    '        "data_signature": identity.get("data_signature"),\n',
    '        "symbol": identity.get("symbol") or state.get("symbol"),\n',
    '        "timeframe": identity.get("timeframe") or state.get("timeframe"),\n',
    '        "source": identity.get("source") or state.get("source"),\n',
    '        "canonical_status": "READY" if canonical else "DATA NOT READY",\n',
    '    }\n',
    '    state[RUNTIME_CONTEXT_KEY] = context\n',
    '    state["navigation_authoritative_20260617"] = True\n',
    '    return context\n',
    '\n',
    '\n',
    'def shared_from_runtime(state: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    value = state.get(SHARED_KEY) or state.get(LEGACY_SHARED_KEY)\n',
    '    return value if isinstance(value, dict) else {}\n',
]
