"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Canonical regime, decision, error and 25-day table synchronization.\n',
    '\n',
    'The module only reconciles existing calculation outputs. It does not create a\n',
    'new market model. Lunch, PowerBI, Finder and Research read the same snapshot so\n',
    'regime/start/end/decision/error cannot drift between sections.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import math\n',
    'from typing import Any, Dict, Iterable, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    'import streamlit as st\n',
    '\n',
    'REGIME_KEYS = (\n',
    '    "major_regime_history_df", "full_metric_regime_history_df",\n',
    '    "full_metric_detail_history_df", "lunch_regime_history", "regime_history_df",\n',
    '    "dv_pp_regime_hist", "regime_history", "smooth_regime_history",\n',
    ')\n',
    'OHLC_KEYS = (\n',
    '    "calculation_staging_ohlc_df_20260617", "canonical_completed_ohlc_df_20260617", "dv_pp_df", "lunch_5layer_powerbi_df", "last_df", "full_metric_history_df",\n',
    '    "lunch_visual_df", "ohlc_df", "df",\n',
    ')\n',
    'PRIORITY_KEYS = (\n',
    '    "adx_hourly_priority_calibrated_20260615", "three_center_priority_sorted_20260614",\n',
    '    "reliability_dynamic_priority_table_20260614", "priority_table_df", "knn_greedy_priority_table",\n',
    ')\n',
    'NLP_KEYS = (\n',
    '    "regime_nlp_today_table", "nlp_ranked_news_df", "news_nlp_ranked_df",\n',
    '    "news_nlp_table", "nlp_news_df", "latest_news_df",\n',
    ')\n',
    '\n',
    '\n',
    'def _num(value: Any, default: float | None = None) -> float | None:\n',
    '    try:\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _dt_series(values: Any) -> pd.Series:\n',
    '    """Parse mixed API/history timestamps into timezone-naive UTC values."""\n',
    '    try:\n',
    '        index = values.index if isinstance(values, pd.Series) else None\n',
    '        raw = pd.Series(values, index=index)\n',
    '        return pd.to_datetime(raw, errors="coerce", utc=True).dt.tz_convert(None)\n',
    '    except Exception:\n',
    '        return pd.Series(pd.NaT, index=getattr(values, "index", None))\n',
    '\n',
    '\n',
    'def _dt_scalar(value: Any) -> pd.Timestamp:\n',
    '    try:\n',
    '        parsed = pd.to_datetime(value, errors="coerce", utc=True)\n',
    '        if pd.isna(parsed):\n',
    '            return pd.NaT\n',
    '        return pd.Timestamp(parsed).tz_convert(None)\n',
    '    except Exception:\n',
    '        return pd.NaT\n',
    '\n',
    '\n',
    'def _clip(value: Any, low: float = 0.0, high: float = 100.0, default: float = 50.0) -> float:\n',
    '    parsed = _num(value, default)\n',
    '    return max(low, min(high, float(default if parsed is None else parsed)))\n',
    '\n',
    '\n',
    'def _iter_state_dfs(keys: Iterable[str]):\n',
    '    for key in keys:\n',
    '        obj = st.session_state.get(key)\n',
    '        if isinstance(obj, pd.DataFrame) and not obj.empty:\n',
    '            yield key, obj\n',
    '        elif isinstance(obj, dict):\n',
    '            for subkey, value in obj.items():\n',
    '                if isinstance(value, pd.DataFrame) and not value.empty:\n',
    '                    yield f"{key}.{subkey}", value\n',
    '\n',
    '\n',
    'def _first_df(keys: Iterable[str]) -> pd.DataFrame:\n',
    '    for _key, df in _iter_state_dfs(keys):\n',
    '        return df\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _find_col(df: pd.DataFrame, aliases: Iterable[str]) -> str | None:\n',
    '    if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '        return None\n',
    '    norm = {str(c).strip().lower().replace("_", " "): c for c in df.columns}\n',
    '    normalized_aliases = [str(a).strip().lower().replace("_", " ") for a in aliases]\n',
    '    for alias in normalized_aliases:\n',
    '        if alias in norm:\n',
    '            return norm[alias]\n',
    '    for key, col in norm.items():\n',
    '        if any(alias and alias in key for alias in normalized_aliases):\n',
    '            return col\n',
    '    return None\n',
    '\n',
    '\n',
    'def _shared() -> Dict[str, Any]:\n',
    '    try:\n',
    '        from core.canonical_runtime_20260617 import shared_from_runtime\n',
    '        return shared_from_runtime(st.session_state)\n',
    '    except Exception:\n',
    '        value = st.session_state.get("adx_shared_calc_result_20260615") or st.session_state.get("shared_calc_result")\n',
    '        return value if isinstance(value, dict) else {}\n',
    '\n',
    '\n',
    'def _current_regime_from_state(shared: Dict[str, Any]) -> str:\n',
    '    candidates = []\n',
    '    for key in (\n',
    '        "dv_pp_regime_summary", "regime_context_20260614", "lunch_5layer_powerbi_result",\n',
    '        "final_merged_intelligence_pack_20260612", "lunch_metric_result_cache",\n',
    '    ):\n',
    '        obj = st.session_state.get(key)\n',
    '        if isinstance(obj, dict):\n',
    '            candidates.extend([\n',
    '                obj.get("current_regime"), obj.get("major_regime"), obj.get("master_regime"),\n',
    '                obj.get("regime"), (obj.get("scores") or {}).get("Regime") if isinstance(obj.get("scores"), dict) else None,\n',
    '            ])\n',
    '    current = shared.get("current", {}) if isinstance(shared.get("current"), dict) else {}\n',
    '    alpha = shared.get("regime_alpha_delta", {}) if isinstance(shared.get("regime_alpha_delta"), dict) else {}\n',
    '    candidates.extend([alpha.get("current_regime"), current.get("regime"), st.session_state.get("current_regime")])\n',
    '    for value in candidates:\n',
    '        text = str(value or "").strip()\n',
    '        if text and text not in {"-", "None", "nan", "WAIT", "NO TRADE"}:\n',
    '            return text\n',
    '    return "RANGE_NORMAL"\n',
    '\n',
    '\n',
    'def _normalize_ohlc() -> pd.DataFrame:\n',
    '    best = pd.DataFrame()\n',
    '    best_score = -1.0\n',
    '    for key, candidate in _iter_state_dfs(OHLC_KEYS):\n',
    '        try:\n',
    '            from core.runtime_cache_20260617 import cached_clean_ohlc\n',
    '            canonical = st.session_state.get("canonical_decision_result_20260617") or {}\n',
    '            df = cached_clean_ohlc(\n',
    '                candidate,\n',
    '                symbol=str(canonical.get("symbol") or st.session_state.get("symbol") or "EURUSD"),\n',
    '                timeframe=str(canonical.get("timeframe") or st.session_state.get("timeframe") or "H1"),\n',
    '                source=str(canonical.get("source") or st.session_state.get("source") or key),\n',
    '                data_signature=str(canonical.get("data_signature") or f"{key}:{len(candidate)}"),\n',
    '                calculation_version=str(canonical.get("calculation_version") or "decision-product-20260617-v1"),\n',
    '            )\n',
    '        except Exception:\n',
    '            df = pd.DataFrame()\n',
    '        if df.empty:\n',
    '            st.session_state["regime_data_not_ready_reason_20260617"] = f"{key} has no valid completed timestamped OHLC data"\n',
    '            continue\n',
    '        freshness = pd.Timestamp(df["time"].max())\n',
    '        age_hours = max(0.0, (pd.Timestamp.now(tz=freshness.tz) - freshness).total_seconds() / 3600.0) if freshness.tzinfo else max(0.0, (pd.Timestamp.now() - freshness).total_seconds() / 3600.0)\n',
    '        score = min(len(df), 5000) / 100.0 + max(0.0, 80.0 - age_hours / 3.0)\n',
    '        if key.startswith("dv_pp_df") or key.startswith("last_df"):\n',
    '            score += 8.0\n',
    '        if score > best_score:\n',
    '            best, best_score = df.reset_index(drop=True), score\n',
    '    return best\n',
    '\n',
    '\n',
    'def _momentum_direction(ohlc: pd.DataFrame, regime: str = "") -> str:\n',
    '    try:\n',
    '        from core.decision_policy_20260617 import infer_direction_from_regime\n',
    '        return infer_direction_from_regime(regime, ohlc)\n',
    '    except Exception:\n',
    '        return "WAIT"\n',
    '\n',
    '\n',
    'def _select_regime_source() -> Tuple[pd.DataFrame, str]:\n',
    '    """Choose the freshest structurally complete regime table, not first key."""\n',
    '    preference = {\n',
    '        "major_regime_history_df": 28.0,\n',
    '        "full_metric_regime_history_df": 27.5,\n',
    '        "full_metric_detail_history_df": 27.0,\n',
    '        "lunch_regime_history": 26.0,\n',
    '        "regime_history_df": 24.0,\n',
    '        "dv_pp_regime_hist": 22.0,\n',
    '        "regime_history": 18.0,\n',
    '        "smooth_regime_history": 16.0,\n',
    '    }\n',
    '    best_df, best_key, best_score = pd.DataFrame(), "", -1e9\n',
    '    now = pd.Timestamp.now()\n',
    '    fixed = list(_iter_state_dfs(REGIME_KEYS))\n',
    '    seen_names = set()\n',
    '    for key, df in fixed:\n',
    '        if key in seen_names:\n',
    '            continue\n',
    '        seen_names.add(key)\n',
    '        rcol = _find_col(df, ("major regime", "current regime", "master regime", "regime", "label", "state"))\n',
    '        if not rcol:\n',
    '            continue\n',
    '        scol = _find_col(df, ("regime start", "start time", "started", "start"))\n',
    '        tcol = _find_col(df, ("time", "datetime", "timestamp", "date", "bar time"))\n',
    '        ecol = _find_col(df, ("regime end", "end time", "ended", "end", "next change"))\n',
    '        times = pd.Series(dtype="datetime64[ns]")\n',
    '        open_current_segment = False\n',
    '        if ecol and scol:\n',
    '            parsed_end = _dt_series(df[ecol])\n',
    '            parsed_start = _dt_series(df[scol])\n',
    '            open_current_segment = bool(parsed_end.isna().any() and parsed_start.notna().any())\n',
    '        for col in (ecol, tcol, scol):\n',
    '            if col:\n',
    '                parsed = _dt_series(df[col]).dropna()\n',
    '                if not parsed.empty:\n',
    '                    times = parsed\n',
    '                    break\n',
    '        fresh_bonus = 55.0 if open_current_segment else 0.0\n',
    '        if not open_current_segment and not times.empty:\n',
    '            latest = pd.Timestamp(times.max())\n',
    '            try:\n',
    '                reference = pd.Timestamp.now(tz=latest.tz) if latest.tzinfo else now\n',
    '                age_days = max(0.0, (reference - latest).total_seconds() / 86400.0)\n',
    '                fresh_bonus = max(0.0, 55.0 - age_days * 4.0)\n',
    '            except Exception:\n',
    '                fresh_bonus = 5.0\n',
    '        explicit_bonus = 20.0 if scol else 0.0\n',
    '        explicit_bonus += 12.0 if ecol else 0.0\n',
    '        size_bonus = min(16.0, math.log2(max(2, len(df))) * 2.0)\n',
    '        root = key.split(".", 1)[0]\n',
    '        name_low = str(key).lower()\n',
    '        semantic_bonus = 0.0\n',
    '        if "full_metric" in name_low or "full metric" in name_low:\n',
    '            semantic_bonus += 38.0\n',
    '        if "major_regime" in name_low or "major regime" in name_low:\n',
    '            semantic_bonus += 28.0\n',
    '        if "history" in name_low:\n',
    '            semantic_bonus += 8.0\n',
    '        score = preference.get(root, 0.0) + semantic_bonus + fresh_bonus + explicit_bonus + size_bonus\n',
    '        if score > best_score:\n',
    '            best_df, best_key, best_score = df.copy(), key, score\n',
    '    return best_df, best_key\n',
    '\n',
    '\n',
    'def _regime_runs(shared: Dict[str, Any], days: int = 10, anchor: pd.Timestamp | None = None) -> Tuple[pd.DataFrame, str]:\n',
    '    raw, source_key = _select_regime_source()\n',
    '    fallback_regime = _current_regime_from_state(shared)\n',
    '    now = _dt_scalar(anchor).floor("s") if anchor is not None and not pd.isna(anchor) else pd.Timestamp.now(tz="UTC").tz_convert(None).floor("s")\n',
    '    if raw.empty:\n',
    '        return pd.DataFrame([{\n',
    '            "Regime": fallback_regime, "Regime Start": pd.NaT, "Regime End": pd.NaT,\n',
    '            "Status": "CURRENT", "Source": "current shared result",\n',
    '        }]), "current shared result"\n',
    '\n',
    '    rcol = _find_col(raw, ("major regime", "current regime", "master regime", "regime", "label", "state"))\n',
    '    scol = _find_col(raw, ("regime start", "start time", "started", "start"))\n',
    '    ecol = _find_col(raw, ("regime end", "end time", "ended", "end", "next change"))\n',
    '    tcol = _find_col(raw, ("time", "datetime", "timestamp", "date", "bar time"))\n',
    '    if not rcol:\n',
    '        return pd.DataFrame([{\n',
    '            "Regime": fallback_regime, "Regime Start": pd.NaT, "Regime End": pd.NaT,\n',
    '            "Status": "CURRENT", "Source": "shared fallback",\n',
    '        }]), "shared fallback"\n',
    '\n',
    '    work = pd.DataFrame({"Regime": raw[rcol].astype(str).str.strip()})\n',
    '    # Segment-level tables already contain regime start/end. Preserve them.\n',
    '    if scol:\n',
    '        work["Regime Start"] = _dt_series(raw[scol])\n',
    '        work["Regime End"] = _dt_series(raw[ecol]) if ecol else pd.NaT\n',
    '        work = work.dropna(subset=["Regime Start"]).sort_values("Regime Start").drop_duplicates(\n',
    '            subset=["Regime", "Regime Start"], keep="last"\n',
    '        ).reset_index(drop=True)\n',
    '        if not work.empty:\n',
    '            next_start = pd.Series(list(work["Regime Start"].iloc[1:]) + [pd.NaT], index=work.index, dtype="datetime64[ns]")\n',
    '            missing_closed = work["Regime End"].isna() & next_start.notna()\n',
    '            work.loc[missing_closed, "Regime End"] = next_start[missing_closed]\n',
    '            runs = work\n',
    '        else:\n',
    '            runs = pd.DataFrame()\n',
    '    else:\n',
    '        if tcol:\n',
    '            work["time"] = _dt_series(raw[tcol])\n',
    '        else:\n',
    '            st.session_state["regime_data_not_ready_reason_20260617"] = f"{source_key or \'regime source\'} has no valid timestamps"\n',
    '            return pd.DataFrame([{"Regime": "DATA NOT READY", "Regime Start": pd.NaT, "Regime End": pd.NaT, "Status": "DATA NOT READY", "Source": source_key or "missing timestamp"}]), source_key or "missing timestamp"\n',
    '        work = work.dropna(subset=["time"]).sort_values("time").reset_index(drop=True)\n',
    '        if work.empty:\n',
    '            runs = pd.DataFrame()\n',
    '        else:\n',
    '            group = work["Regime"].ne(work["Regime"].shift()).cumsum()\n',
    '            runs = work.groupby(group, as_index=False).agg(\n',
    '                Regime=("Regime", "last"),\n',
    '                **{"Regime Start": ("time", "min"), "Regime End": ("time", "max")},\n',
    '            )\n',
    '            if not runs.empty:\n',
    '                next_start = pd.Series(list(runs["Regime Start"].iloc[1:]) + [pd.NaT], index=runs.index, dtype="datetime64[ns]")\n',
    '                runs.loc[next_start.notna(), "Regime End"] = next_start[next_start.notna()]\n',
    '                runs.loc[runs.index[-1], "Regime End"] = pd.NaT\n',
    '\n',
    '    if runs.empty:\n',
    '        runs = pd.DataFrame([{"Regime": fallback_regime, "Regime Start": pd.NaT, "Regime End": pd.NaT}])\n',
    '    # If every recorded segment ended before the latest available market bar,\n',
    '    # append the shared current regime instead of silently re-labelling a stale\n',
    '    # historical segment as current.\n',
    '    starts_all = _dt_series(runs["Regime Start"])\n',
    '    ends_all = _dt_series(runs["Regime End"])\n',
    '    active_mask = starts_all.notna() & (starts_all <= now) & (ends_all.isna() | (ends_all >= now))\n',
    '    if not active_mask.any():\n',
    '        latest_regime = str(runs.iloc[-1].get("Regime", "")) if not runs.empty else ""\n',
    '        latest_end = ends_all.dropna().max() if ends_all.notna().any() else pd.NaT\n',
    '        latest_start = starts_all.dropna().max() if starts_all.notna().any() else pd.NaT\n',
    '        inferred_start = latest_end if not pd.isna(latest_end) else latest_start\n',
    '        if fallback_regime and (latest_regime != fallback_regime or pd.isna(latest_end) or latest_end < now):\n',
    '            runs = pd.concat([\n',
    '                runs,\n',
    '                pd.DataFrame([{\n',
    '                    "Regime": fallback_regime,\n',
    '                    "Regime Start": inferred_start,\n',
    '                    "Regime End": pd.NaT,\n',
    '                }]),\n',
    '            ], ignore_index=True)\n',
    '            starts_all = _dt_series(runs["Regime Start"])\n',
    '            ends_all = _dt_series(runs["Regime End"])\n',
    '\n',
    '    cutoff = now - pd.Timedelta(days=max(1, int(days)))\n',
    '    starts = _dt_series(runs["Regime Start"])\n',
    '    ends = _dt_series(runs["Regime End"])\n',
    '    # Keep a segment if it overlaps the window; this preserves a current regime\n',
    '    # that started before the requested 10-day window.\n',
    '    overlap = ends.isna() | (ends >= cutoff) | (starts >= cutoff)\n',
    '    filtered = runs.loc[overlap].copy()\n',
    '    if filtered.empty:\n',
    '        filtered = runs.tail(1).copy()\n',
    '    filtered["Status"] = "CLOSED"\n',
    '    fstart = _dt_series(filtered["Regime Start"])\n',
    '    fend = _dt_series(filtered["Regime End"])\n',
    '    current_mask = fstart.notna() & (fstart <= now) & (fend.isna() | (fend >= now))\n',
    '    if current_mask.any():\n',
    '        filtered.loc[current_mask, "Status"] = "CURRENT"\n',
    '    elif not filtered.empty:\n',
    '        filtered.loc[filtered.index[-1], "Status"] = "CURRENT"\n',
    '    filtered["Source"] = source_key or "regime history"\n',
    '    return filtered.tail(100).reset_index(drop=True), source_key or "regime history"\n',
    '\n',
    '\n',
    'def _error_snapshot(shared: Dict[str, Any], ohlc: pd.DataFrame) -> Dict[str, Any]:\n',
    '    """Use completed prediction-vs-actual data first; never present fake 0.00%."""\n',
    '    fb = shared.get("prediction_feedback", {}) if isinstance(shared.get("prediction_feedback"), dict) else {}\n',
    '    value = _num(fb.get("avg_abs_close_error_pct"), None)\n',
    '    samples = int(_num(fb.get("samples") or fb.get("tested_candles"), 0) or 0)\n',
    '    method = str(fb.get("method") or "")\n',
    '\n',
    '    # Read the exact PowerBI/backtest caches when shared feedback is stale or rounded to zero.\n',
    '    summaries = []\n',
    '    history_frames = []\n',
    '    for key, obj in list(st.session_state.items()):\n',
    '        key_low = str(key).lower()\n',
    '        if isinstance(obj, dict) and any(t in key_low for t in ("bt", "backtest", "prediction", "powerbi", "feedback")):\n',
    '            summaries.append((str(key), obj))\n',
    '        if isinstance(obj, pd.DataFrame) and not obj.empty and any(t in key_low for t in ("bt", "backtest", "prediction", "actual", "projection")):\n',
    '            history_frames.append((str(key), obj.copy()))\n',
    '    for key in ("dv_pp_bt_summary", "prediction_feedback", "prediction_backtest_summary"):\n',
    '        obj = st.session_state.get(key)\n',
    '        if isinstance(obj, dict):\n',
    '            summaries.insert(0, (key, obj))\n',
    '    for name, summary in summaries:\n',
    '        candidate = None\n',
    '        for field in ("avg_abs_close_error_pct", "average_error_pct", "avg_close_error_pct", "prediction_error_pct", "close_error_pct", "Prediction vs Actual Close Error"):\n',
    '            if field in summary:\n',
    '                candidate = _num(summary.get(field), None)\n',
    '                break\n',
    '        candidate_samples = int(_num(summary.get("samples") or summary.get("tested_candles") or summary.get("count"), 0) or 0)\n',
    '        if candidate is not None and candidate > 1e-9 and (candidate_samples > 0 or samples <= 0):\n',
    '            value, samples, method = float(candidate), max(samples, candidate_samples), f"{name} completed prediction-vs-actual summary"\n',
    '            break\n',
    '\n',
    '    if value is None or value <= 1e-9 or samples <= 0:\n',
    '        preferred = ["dv_pp_bt_hist", "prediction_vs_actual_history_df", "prediction_history_df", "dv_pp_projection_history"]\n',
    '        ordered = []\n',
    '        for key in preferred:\n',
    '            obj = st.session_state.get(key)\n',
    '            if isinstance(obj, pd.DataFrame) and not obj.empty:\n',
    '                ordered.append((key, obj.copy()))\n',
    '        ordered += history_frames\n',
    '        seen = set()\n',
    '        for name, frame in ordered:\n',
    '            if id(frame) in seen:\n',
    '                continue\n',
    '            seen.add(id(frame))\n',
    '            error_col = _find_col(frame, ("close error %", "absolute error %", "abs error", "prediction error %", "error %", "close_error_pct"))\n',
    '            if error_col:\n',
    '                values = pd.to_numeric(frame[error_col], errors="coerce").abs().replace([np.inf, -np.inf], np.nan).dropna()\n',
    '                values = values[values > 1e-12]\n',
    '                if not values.empty:\n',
    '                    value, samples, method = float(values.mean()), int(len(values)), f"{name} completed prediction-vs-actual rows"\n',
    '                    break\n',
    '            actual_col = _find_col(frame, ("actual close", "actual", "observed close"))\n',
    '            pred_col = _find_col(frame, ("pred close", "predicted close", "forecast close", "prediction"))\n',
    '            if actual_col and pred_col:\n',
    '                actual = pd.to_numeric(frame[actual_col], errors="coerce")\n',
    '                pred = pd.to_numeric(frame[pred_col], errors="coerce")\n',
    '                errors = ((pred - actual).abs() / actual.abs().replace(0, np.nan) * 100.0).dropna()\n',
    '                errors = errors[errors > 1e-12]\n',
    '                if not errors.empty:\n',
    '                    value, samples, method = float(errors.mean()), int(len(errors)), f"{name} calculated prediction-vs-actual rows"\n',
    '                    break\n',
    '\n',
    '    is_actual = bool(samples > 0 and value is not None and value > 1e-9 and "proxy" not in method.lower())\n',
    '    if is_actual:\n',
    '        return {"value": float(value), "samples": samples, "method": method or "prediction-vs-actual history", "is_proxy": False, "available": True}\n',
    '    if not ohlc.empty:\n',
    '        ret = pd.to_numeric(ohlc["close"], errors="coerce").pct_change().abs() * 100.0\n',
    '        proxy = _num(ret.tail(48).dropna().mean(), None)\n',
    '        if proxy is not None and proxy > 1e-9:\n',
    '            return {\n',
    '                "value": float(proxy), "samples": 0,\n',
    '                "method": "recent H1 volatility proxy; completed prediction-vs-actual rows unavailable",\n',
    '                "is_proxy": True, "available": True,\n',
    '            }\n',
    '    return {\n',
    '        "value": None, "samples": 0,\n',
    '        "method": "N/A; run PowerBI prediction-vs-actual backtest to create error samples",\n',
    '        "is_proxy": False, "available": False,\n',
    '    }\n',
    '\n',
    '\n',
    'def _decision_from_evidence(direction: str, existing: str, reliability: float, data_quality: float, exit_risk: float) -> str:\n',
    '    try:\n',
    '        from core.decision_policy_20260617 import reconcile_decision\n',
    '        return reconcile_decision(direction, existing, reliability, data_quality, exit_risk)\n',
    '    except Exception:\n',
    '        return "WAIT"\n',
]
