"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        "balanced_accuracy": float(np.mean(fold_balanced)),\n',
    '        "policy": "expanding chronological windows; no shuffle; purged labels",\n',
    '    }\n',
    '\n',
    '\n',
    'def _group_direction_metrics(data: pd.DataFrame, column: str, minimum: int = 20) -> Dict[str, Any]:\n',
    '    output: Dict[str, Any] = {}\n',
    '    if column not in data.columns:\n',
    '        return output\n',
    '    for name, group in data.groupby(column, dropna=False):\n',
    '        if len(group) < minimum:\n',
    '            continue\n',
    '        actual = group["actual_direction"].astype(str).str.upper()\n',
    '        predicted = group["predicted_direction"].astype(str).str.upper()\n',
    '        output[str(name)] = {\n',
    '            "samples": int(len(group)),\n',
    '            "direction_accuracy": float((actual == predicted).mean()),\n',
    '        }\n',
    '    return output\n',
    '\n',
    '\n',
    'def _walk_forward_summary(ledger: PredictionLedger, *, symbol: str, timeframe: str) -> ReliabilityResult:\n',
    '    all_rows = ledger.settled_predictions(symbol=symbol, timeframe=timeframe, limit=6000)\n',
    '    by_h: Dict[str, Dict[str, Any]] = {}\n',
    '    calibration: Dict[str, Dict[str, Any]] = {}\n',
    '    aggregate_brier: List[float] = []\n',
    '    aggregate_logloss: List[float] = []\n',
    '    aggregate_ece: List[float] = []\n',
    '    for h in HORIZONS:\n',
    '        d = all_rows[pd.to_numeric(all_rows.get("horizon_hours"), errors="coerce") == h] if not all_rows.empty else pd.DataFrame()\n',
    '        if len(d) < 20:\n',
    '            by_h[f"{h}h"] = {\n',
    '                "status": "INSUFFICIENT SAMPLE", "samples": len(d),\n',
    '                "purge_gap_rows": int(max(6, h)), "embargo_rows": 1,\n',
    '            }\n',
    '            continue\n',
    '        d = d.copy()\n',
    '        d["_created"] = pd.to_datetime(d.get("created_at"), utc=True, errors="coerce")\n',
    '        d = d.sort_values("_created")\n',
    '        y = pd.to_numeric(d.get("direction_correct"), errors="coerce").dropna()\n',
    '        actual = d.loc[y.index, "actual_direction"].astype(str).str.upper()\n',
    '        pred = d.loc[y.index, "predicted_direction"].astype(str).str.upper()\n',
    '        try:\n',
    '            from sklearn.metrics import balanced_accuracy_score, precision_recall_fscore_support\n',
    '            bal = float(balanced_accuracy_score(actual, pred))\n',
    '            precision, recall, f1, _ = precision_recall_fscore_support(\n',
    '                actual, pred, labels=["BUY", "SELL", "WAIT"], zero_division=0\n',
    '            )\n',
    '            cls = {\n',
    '                name: {"precision": float(precision[i]), "recall": float(recall[i]), "f1": float(f1[i])}\n',
    '                for i, name in enumerate(["BUY", "SELL", "WAIT"])\n',
    '            }\n',
    '        except Exception:\n',
    '            bal = float(y.mean()); cls = {}\n',
    '\n',
    '        abs_err = pd.to_numeric(d.get("absolute_error"), errors="coerce").dropna()\n',
    '        coverage = None\n',
    '        if {"actual_price", "lower_bound", "upper_bound"}.issubset(d.columns):\n',
    '            vals = d[["actual_price", "lower_bound", "upper_bound"]].apply(pd.to_numeric, errors="coerce").dropna()\n',
    '            if len(vals):\n',
    '                coverage = float(((vals.actual_price >= vals.lower_bound) & (vals.actual_price <= vals.upper_bound)).mean())\n',
    '\n',
    '        net = np.where(\n',
    '            pd.to_numeric(d.get("direction_correct"), errors="coerce").fillna(0) > 0,\n',
    '            pd.to_numeric(d.get("maximum_favourable_excursion"), errors="coerce").fillna(0),\n',
    '            -pd.to_numeric(d.get("maximum_adverse_excursion"), errors="coerce").fillna(0),\n',
    '        ) - pd.to_numeric(d.get("estimated_cost"), errors="coerce").fillna(0)\n',
    '        equity = np.cumsum(net)\n',
    '        dd = float(np.max(np.maximum.accumulate(equity) - equity)) if len(equity) else None\n',
    '        wins = float(np.sum(net[net > 0])); losses = abs(float(np.sum(net[net < 0])))\n',
    '        pf = wins / losses if losses > 0 else None\n',
    '\n',
    '        # Multiclass probability diagnostics use calibrated values only where all\n',
    '        # three probabilities and the settled class are available.\n',
    '        probability_columns = [\n',
    '            "buy_probability_calibrated", "sell_probability_calibrated", "wait_probability_calibrated"\n',
    '        ]\n',
    '        probability_metrics: Dict[str, Any] = {}\n',
    '        if set(probability_columns).issubset(d.columns):\n',
    '            probs = d[probability_columns].apply(pd.to_numeric, errors="coerce")\n',
    '            mask = probs.notna().all(axis=1) & d["actual_direction"].astype(str).str.upper().isin(["BUY", "SELL", "WAIT"])\n',
    '            if int(mask.sum()) >= 10:\n',
    '                p = probs.loc[mask].to_numpy(dtype=float)\n',
    '                p = np.clip(p, 1e-6, 1 - 1e-6)\n',
    '                p = p / p.sum(axis=1, keepdims=True)\n',
    '                labels = d.loc[mask, "actual_direction"].astype(str).str.upper().map({"BUY": 0, "SELL": 1, "WAIT": 2}).to_numpy()\n',
    '                one_hot = np.eye(3)[labels]\n',
    '                brier = float(np.mean(np.sum((p - one_hot) ** 2, axis=1)))\n',
    '                logloss = float(-np.mean(np.log(p[np.arange(len(p)), labels])))\n',
    '                confidence = p.max(axis=1); correct = (p.argmax(axis=1) == labels).astype(float)\n',
    '                cal_diag = _calibration_diagnostics(confidence, correct)\n',
    '                probability_metrics = {\n',
    '                    "brier_score": brier, "log_loss": logloss,\n',
    '                    "expected_calibration_error": cal_diag.get("expected_calibration_error"),\n',
    '                    "reliability_buckets": cal_diag.get("reliability_buckets", []),\n',
    '                }\n',
    '                aggregate_brier.append(brier); aggregate_logloss.append(logloss)\n',
    '                if probability_metrics["expected_calibration_error"] is not None:\n',
    '                    aggregate_ece.append(float(probability_metrics["expected_calibration_error"]))\n',
    '\n',
    '        if "created_at" in d.columns:\n',
    '            created_hour = pd.to_datetime(d["created_at"], utc=True, errors="coerce").dt.hour\n',
    '            d["session"] = np.select(\n',
    '                [created_hour.between(7, 11), created_hour.between(12, 16), created_hour.between(0, 6)],\n',
    '                ["LONDON", "NY_OVERLAP", "ASIA"], default="OTHER",\n',
    '            )\n',
    '        walk_forward = _purged_walk_forward_direction_metrics(d, h)\n',
    '        by_h[f"{h}h"] = {\n',
    '            "status": "VALID", "samples": len(d),\n',
    '            "trades": int((d.predicted_direction.astype(str).str.upper() != "WAIT").sum()),\n',
    '            "direction_accuracy": float(y.mean()), "balanced_accuracy": bal,\n',
    '            "class_metrics": cls,\n',
    '            "mean_absolute_price_error": float(abs_err.mean()) if len(abs_err) else None,\n',
    '            "median_absolute_price_error": float(abs_err.median()) if len(abs_err) else None,\n',
    '            "interval_coverage": coverage,\n',
    '            "average_interval_width": float((pd.to_numeric(d.get("upper_bound"), errors="coerce") - pd.to_numeric(d.get("lower_bound"), errors="coerce")).abs().mean()) if "upper_bound" in d and "lower_bound" in d else None,\n',
    '            "net_result_after_cost": float(np.sum(net)), "maximum_drawdown": dd, "profit_factor": pf,\n',
    '            "walk_forward": walk_forward,\n',
    '            "by_regime": _group_direction_metrics(d, "major_regime"),\n',
    '            "by_session": _group_direction_metrics(d, "session"),\n',
    '            **probability_metrics,\n',
    '        }\n',
    '    valid = [v for v in by_h.values() if v.get("status") == "VALID"]\n',
    '    if not valid:\n',
    '        return ReliabilityResult(\n',
    '            score=0, status="INSUFFICIENT SAMPLE", sample_count=len(all_rows),\n',
    '            validation_by_horizon=by_h, calibration_by_horizon=calibration,\n',
    '        )\n',
    '    accuracy = float(np.average([v["direction_accuracy"] for v in valid], weights=[v["samples"] for v in valid]))\n',
    '    errors = [v["mean_absolute_price_error"] for v in valid if v.get("mean_absolute_price_error") is not None]\n',
    '    coverages = [v["interval_coverage"] for v in valid if v.get("interval_coverage") is not None]\n',
    '    return ReliabilityResult(\n',
    '        score=accuracy * 100, status="VALIDATED", sample_count=len(all_rows), direction_accuracy=accuracy,\n',
    '        balanced_accuracy=float(np.mean([v["balanced_accuracy"] for v in valid])),\n',
    '        brier_score=float(np.mean(aggregate_brier)) if aggregate_brier else None,\n',
    '        log_loss=float(np.mean(aggregate_logloss)) if aggregate_logloss else None,\n',
    '        expected_calibration_error=float(np.mean(aggregate_ece)) if aggregate_ece else None,\n',
    '        mean_absolute_price_error=float(np.mean(errors)) if errors else None,\n',
    '        median_absolute_price_error=float(np.median(errors)) if errors else None,\n',
    '        interval_coverage=float(np.mean(coverages)) if coverages else None,\n',
    '        validation_by_horizon=by_h, calibration_by_horizon=calibration,\n',
    '    )\n',
    '\n',
    'def _reconcile(horizons: Dict[str,HorizonForecast]) -> Tuple[str,str,float]:\n',
    '    dirs={h:intf.direction for h,intf in horizons.items()}\n',
    '    active=[d for d in dirs.values() if d in {"BUY","SELL"}]\n',
    '    agreement=max(active.count("BUY"),active.count("SELL"))/len(active) if active else 0.0\n',
    '    if len(set(active))<=1 and active:\n',
    '        return "STRONG ALIGNMENT",f"All directional horizons agree on {active[0]}",agreement\n',
    '    d1=dirs.get("1h","WAIT"); d3=dirs.get("3h","WAIT"); d6=dirs.get("6h","WAIT")\n',
    '    if d1 in {"BUY","SELL"} and d3==d6 and d3 in {"BUY","SELL"} and d1!=d3:\n',
    '        return "SHORT PULLBACK",f"1h {d1} conflicts with 3h/6h {d3}",agreement\n',
    '    if d1=="WAIT" and d3==d6 and d3 in {"BUY","SELL"}:\n',
    '        return "DELAYED SETUP",f"1h waits while 3h/6h align {d3}",agreement\n',
    '    if dirs.get("1h")==dirs.get("2h")=="BUY" and d6=="SELL":\n',
    '        return "SHORT-LIVED BULLISH MOVE","Short horizons bullish inside bearish 6h structure",agreement\n',
    '    if dirs.get("1h")==dirs.get("2h")=="SELL" and d6=="BUY":\n',
    '        return "SHORT-LIVED BEARISH MOVE","Short horizons bearish inside bullish 6h structure",agreement\n',
    '    return "LARGE DISAGREEMENT","Horizon directions materially disagree; prefer WAIT",agreement\n',
    '\n',
    '\n',
    'def historical_similarity(frame: pd.DataFrame, horizon: int = 3, lookback: int = 24, top_n: int = 30) -> Dict[str,Any]:\n',
    '    if len(frame)<lookback+horizon+80:\n',
    '        return {"status":"INSUFFICIENT SAMPLE","match_count":0,"effective_weighted_sample_size":0}\n',
    '    close=frame.close.astype(float); returns=close.pct_change().fillna(0)\n',
    '    target=returns.tail(lookback).to_numpy(); candidates=[]\n',
    '    end_limit=len(frame)-lookback-horizon\n',
    '    for end in range(lookback,end_limit):\n',
    '        seq=returns.iloc[end-lookback:end].to_numpy()\n',
    '        denom=np.linalg.norm(target)*np.linalg.norm(seq)\n',
    '        sim=float(np.dot(target,seq)/denom) if denom>0 else 0.0\n',
    '        vol_match=1/(1+abs(float(np.std(seq)-np.std(target)))/(np.std(target)+1e-12))\n',
    '        recency=math.exp(-(len(frame)-end)/1500)\n',
    '        weight=max(0,sim)*vol_match*(0.55+0.45*recency)\n',
    '        if weight<=0: continue\n',
    '        start=float(close.iloc[end-1]); future=close.iloc[end:end+horizon]\n',
    '        move=float(future.iloc[-1]-start); mfe=float(future.max()-start); mae=float(start-future.min())\n',
    '        candidates.append((weight,sim,move,mfe,mae))\n',
    '    top=sorted(candidates,key=lambda x:x[0],reverse=True)[:top_n]\n',
    '    if len(top)<8: return {"status":"INSUFFICIENT SAMPLE","match_count":len(top),"effective_weighted_sample_size":0}\n',
    '    w=np.array([x[0] for x in top]); moves=np.array([x[2] for x in top]); w=w/(w.sum()+1e-12)\n',
    '    ess=float(1/np.sum(w*w)); bullish=float(np.sum(w[moves>0])); bearish=float(np.sum(w[moves<0]))\n',
    '    consistency=max(bullish,bearish)\n',
    '    reliability=max(0,min(1,consistency*min(1,ess/20)))\n',
    '    return {"status":"VALID","match_count":len(top),"effective_weighted_sample_size":ess,"bullish_outcome_percentage":bullish*100,"bearish_outcome_percentage":bearish*100,"median_movement":float(np.median(moves)),"p25_movement":float(np.percentile(moves,25)),"p75_movement":float(np.percentile(moves,75)),"outcome_consistency":consistency,"reliability_after_weighting":reliability,"note":"Similarity percentages are evidence, not probabilities."}\n',
    '\n',
    '\n',
    'def build_decision_result(\n',
    '    *, legacy_shared: Dict[str,Any], ohlc: pd.DataFrame, symbol: str="EURUSD", timeframe: str="H1",\n',
    '    source: str="UNKNOWN", ledger: Optional[PredictionLedger]=None, now: Any=None, calculation_generation: int=0,\n',
    '    full_metric_snapshot: Optional[Dict[str, Any]] = None,\n',
    ') -> DecisionResult:\n',
    '    ledger=ledger or get_prediction_ledger()\n',
    '    quality, frame=validate_data_quality(ohlc,symbol=symbol,timeframe=timeframe,source=source,now=now)\n',
    '    created=pd.Timestamp(now or datetime.now(timezone.utc)); created=created.tz_localize("UTC") if created.tzinfo is None else created.tz_convert("UTC")\n',
    '    run_id=f"{created.strftime(\'%Y%m%dT%H%M%SZ\')}-{uuid.uuid4().hex[:12]}"\n',
    '    signature=data_signature(frame,symbol=symbol,timeframe=timeframe,source=source)\n',
    '    parts=_extract_legacy(legacy_shared)\n',
    '    current_price=float(frame.close.iloc[-1]) if not frame.empty else _finite(parts["current"].get("last_close"),None)\n',
    '    latest_time=_utc_iso(frame.time.iloc[-1]) if not frame.empty else None\n',
    '    market=MarketState(latest_completed_candle_time=latest_time,current_price=current_price,row_count=len(frame),session=_session_label(frame.time.iloc[-1]) if not frame.empty else "UNKNOWN",spread=None,volatility=float(frame.close.pct_change().tail(24).std()) if len(frame)>=25 else None,source_available=bool(frame.size))\n',
    '    full_metric = dict(full_metric_snapshot or {})\n',
    '    regime=build_regime_result(parts,frame)\n',
    '    authority_regime = str(full_metric.get("current_major_regime") or "").strip()\n',
    '    if authority_regime and authority_regime.upper() != "UNKNOWN":\n',
    '        regime.major_regime = authority_regime\n',
    '    priority=_extract_priority(parts)\n',
    '    authority_candidates = list(full_metric.get("top_two_daily_candidates") or [])\n',
    '    authority_best = dict(authority_candidates[0]) if authority_candidates and isinstance(authority_candidates[0], dict) else {}\n',
    '    if authority_best:\n',
    '        authority_score = _finite(authority_best.get("Priority Score") or authority_best.get("combined score"), None)\n',
    '        if authority_score is not None:\n',
    '            priority.score = max(0.0, min(100.0, authority_score))\n',
    '            priority.label = "A+" if priority.score >= 88 else "A" if priority.score >= 76 else "B" if priority.score >= 62 else "C" if priority.score >= 45 else "AVOID"\n',
    '        priority.rank = int(_finite(authority_best.get("Priority Rank") or authority_best.get("priority rank"), 0) or 0) or None\n',
    '        priority.knn_score = _finite(authority_best.get("KNN Score"), priority.knn_score)\n',
    '        priority.greedy_score = _finite(authority_best.get("Greedy Score"), priority.greedy_score)\n',
    '    nlp=_extract_nlp(parts)\n',
    '    drift=compute_drift(ledger,frame,symbol=symbol,timeframe=timeframe)\n',
    '    reliability=_walk_forward_summary(ledger,symbol=symbol,timeframe=timeframe)\n',
    '    legacy_reliability = _finite(parts["reliability"].get("score"), None)\n',
    '    if legacy_reliability is not None:\n',
    '        legacy_reliability = legacy_reliability * 100.0 if legacy_reliability <= 1.0 else legacy_reliability\n',
    '        if reliability.status == "INSUFFICIENT SAMPLE" or reliability.sample_count < 30:\n',
    '            reliability.score = max(0.0, min(100.0, legacy_reliability))\n',
    '            reliability.status = "EXISTING VALIDATED RELIABILITY"\n',
    '    points=_point_forecasts(parts,frame)\n',
    '    atr=_atr(frame)\n',
    '    horizons: Dict[str,HorizonForecast]={}\n',
    '    soft_penalties_by_horizon: Dict[str, List[str]] = {}\n',
    '    preliminary_dirs=[]\n',
    '    for h in HORIZONS:\n',
    '        point=points[h]\n',
    '        direction="BUY" if point is not None and current_price is not None and point>current_price else "SELL" if point is not None and current_price is not None and point<current_price else _direction(parts["current"].get("prediction_direction") or parts["decision"].get("prediction_direction") or regime.major_regime)\n',
    '        preliminary_dirs.append(direction)\n',
    '    agreement=max(preliminary_dirs.count("BUY"),preliminary_dirs.count("SELL"))/len(HORIZONS)\n',
    '    priority.forecast_agreement=agreement\n',
    '    for h,direction in zip(HORIZONS,preliminary_dirs):\n',
    '        history=ledger.settled_predictions(symbol=symbol,timeframe=timeframe,horizon=h,limit=4000)\n',
    '        raw_buy,raw_sell,raw_wait,raw_source=_raw_probabilities(direction,parts,h)\n',
    '        (cal_buy,cal_sell,cal_wait),cal_source,cal_metrics=calibrate_probabilities(ledger,symbol=symbol,timeframe=timeframe,horizon=h,regime=regime.major_regime,raw=(raw_buy,raw_sell,raw_wait))\n',
    '        point=points[h]\n',
    '        lower,upper,res_n,coverage,target,cov_err=_interval(history,current_price or 0,point,h,atr,drift.interval_multiplier)\n',
    '        interval_width=(upper-lower) if upper is not None and lower is not None else None\n',
    '        interval_ratio=interval_width/abs(current_price) if interval_width is not None and current_price else None\n',
    '        direction_p={"BUY":cal_buy,"SELL":cal_sell,"WAIT":cal_wait}.get(direction)\n',
    '        ev=_expected_value(history,direction_p,current_price or 0,atr,h,symbol)\n',
    '        transition={1:regime.transition_probability_1h,2:regime.transition_probability_3h,3:regime.transition_probability_3h,6:regime.transition_probability_6h}[h]\n',
    '        action_prob,action_label,action_reason,action_blockers,action_source=_actionability(history,probability=direction_p,interval_ratio=interval_ratio,priority=priority.score,expected_value=ev["expected_value"],transition=transition,drift=drift,quality=quality,nlp=nlp)\n',
    '        threshold,threshold_ver,threshold_reasons=dynamic_threshold(horizon=h,regime=regime,drift=drift,quality=quality,expected_value=ev["expected_value"],interval_width_ratio=interval_ratio,agreement=agreement,priority=priority,actionability=action_prob,session=market.session,history=history)\n',
    '        hard_blockers=list(action_blockers)\n',
    '        soft_penalties: List[str] = []\n',
    '        if direction_p is None:\n',
    '            hard_blockers.append("calibrated directional probability unavailable")\n',
    '        elif direction_p < max(0.0, threshold - 0.10):\n',
    '            hard_blockers.append(f"calibrated probability {direction_p:.3f} materially below required {threshold:.3f}")\n',
    '        elif direction_p < threshold:\n',
    '            soft_penalties.append(f"calibrated probability {direction_p:.3f} slightly below target {threshold:.3f}")\n',
    '        if ev["expected_value"] is None:\n',
    '            hard_blockers.append("expected value after costs unavailable")\n',
    '        elif ev["expected_value"] <= 0:\n',
    '            hard_blockers.append("negative expected value after costs")\n',
    '        if interval_ratio is None or lower is None or upper is None or lower >= upper:\n',
    '            hard_blockers.append("broken prediction interval")\n',
    '        elif interval_ratio > 0.020:\n',
    '            hard_blockers.append("prediction interval critically wide")\n',
    '        elif interval_ratio > 0.008:\n',
    '            soft_penalties.append("prediction interval moderately wide")\n',
    '        if quality.status.startswith("FAIL"):\n',
    '            hard_blockers.append("critical market data quality failure")\n',
    '        if drift.status=="CRITICAL":\n',
    '            hard_blockers.append("critical forecast drift")\n',
    '        elif drift.status=="DEGRADED":\n',
    '            soft_penalties.append("forecast drift is degraded")\n',
    '        if nlp.conflict_level == "CRITICAL" and nlp.importance>=0.65:\n',
    '            hard_blockers.append("severe event conflict")\n',
    '        elif nlp.conflict_level in {"HIGH", "MODERATE"}:\n',
    '            soft_penalties.append("moderate event-risk disagreement")\n',
    '        if transition >= 0.85:\n',
    '            hard_blockers.append("critical regime transition risk")\n',
    '        elif transition >= 0.55:\n',
    '            soft_penalties.append("moderate regime transition risk")\n',
    '        if agreement < 0.50:\n',
    '            soft_penalties.append("moderate model disagreement")\n',
    '        if priority.score < 45:\n',
    '            soft_penalties.append("priority below preferred target")\n',
    '        if len(history) < 30:\n',
    '            soft_penalties.append("limited settled validation sample")\n',
    '        # Threshold reasons are explanatory modifiers, not automatic blockers.\n',
    '        soft_penalties.extend(str(x) for x in threshold_reasons if x)\n',
    '        soft_penalties_by_horizon[f"{h}h"] = sorted(set(soft_penalties))\n',
    '        controlled_gate = action_prob >= 0.45 and (direction_p is not None and direction_p >= max(0.0, threshold - 0.05))\n',
    '        decision=direction if direction in {"BUY","SELL"} and not hard_blockers and controlled_gate else "WAIT"\n',
    '        blockers = hard_blockers\n',
    '        due=_utc_iso(created+pd.Timedelta(hours=h))\n',
    '        horizons[f"{h}h"]=HorizonForecast(\n',
    '            horizon_hours=h,direction=direction,point_forecast=point,lower_bound=lower,upper_bound=upper,\n',
    '            target_coverage=target,actual_coverage=coverage,interval_width=interval_width,coverage_error=cov_err,\n',
    '            residual_sample_count=res_n,buy_probability_raw=raw_buy,sell_probability_raw=raw_sell,wait_probability_raw=raw_wait,\n',
    '            buy_probability_calibrated=cal_buy,sell_probability_calibrated=cal_sell,wait_probability_calibrated=cal_wait,\n',
    '            probability_source=cal_source if "OOS" in cal_source else raw_source,threshold=threshold,threshold_version=threshold_ver,\n',
    '            expected_gain=ev["expected_gain"],expected_loss=ev["expected_loss"],estimated_cost=ev["estimated_cost"],expected_value=ev["expected_value"],risk_reward=ev["risk_reward"],break_even_probability=ev["break_even_probability"],\n',
    '            reliability=(direction_p or 0),actionability_probability=action_prob,actionability_label="YES" if decision in {"BUY","SELL"} else action_label,actionability_reason=f"{action_reason} ({action_source}); soft evidence: {\', \'.join(soft_penalties[:5]) if soft_penalties else \'none\'}",blocking_reasons=sorted(set(blockers)),priority_score=max(0,priority.score-(100*(1-action_prob)*0.25)-min(15.0,2.0*len(soft_penalties))),knn_score=priority.knn_score,greedy_score=priority.greedy_score,drift_adjustment=drift.threshold_adjustment,decision=decision,due_time=due,\n',
    '        )\n',
    '        reliability.calibration_by_horizon[f"{h}h"]={**cal_metrics,"source":cal_source}\n',
    '    label,reason,agreement_score=_reconcile(horizons)\n',
    '    selected=3\n',
    '    primary=horizons["3h"] if horizons.get("3h") else horizons["2h"]\n',
    '    if primary.decision=="WAIT" and horizons["2h"].decision in {"BUY","SELL"}:\n',
    '        selected=2\n',
    '        primary=horizons["2h"]\n',
    '\n',
    '    # The protected Full Metric H1 direction is the market view authority.\n',
    '    # Forecasts, Research, NLP and M1 may confirm or block an entry, but they\n',
    '    # must never turn a blocked BUY into SELL (or a blocked SELL into BUY).\n',
    '    authority_direction = _direction(full_metric.get("full_metric_direction"))\n',
    '    market_view = authority_direction if full_metric else primary.direction\n',
    '    authority_tradeability = _direction(full_metric.get("tradeability_decision")) if full_metric else primary.decision\n',
    '    final_blockers = list(full_metric.get("blocking_reasons") or []) if full_metric else []\n',
    '    final_soft_warnings: List[str] = list(soft_penalties_by_horizon.get(f"{selected}h", []))\n',
    '    if label=="LARGE DISAGREEMENT":\n',
    '        final_soft_warnings.append("large multi-horizon disagreement lowers priority")\n',
    '    forecast_conflict = primary.direction in {"BUY", "SELL"} and market_view in {"BUY", "SELL"} and primary.direction != market_view\n',
    '    if forecast_conflict:\n',
    '        final_blockers.append(f"PowerBI/prediction {primary.direction} directly opposes Full Metric H1 {market_view}")\n',
    '    else:\n',
    '        final_blockers.extend(primary.blocking_reasons)\n',
    '\n',
    '    m1_status = str(full_metric.get("m1_timing_status") or "CONFIRM").upper() if full_metric else "CONFIRM"\n',
    '    if market_view in {"BUY", "SELL"} and m1_status == "WAIT FOR CONFIRMATION":\n',
    '        final_soft_warnings.append("M1 timing is neutral; reduce aggressiveness or wait for cleaner timing")\n',
    '\n',
    '    confidence_for_view={"BUY":primary.buy_probability_calibrated,"SELL":primary.sell_probability_calibrated,"WAIT":primary.wait_probability_calibrated}.get(market_view)\n',
    '    probability_floor = max(0.0, float(primary.threshold or 0.0) - 0.05)\n',
    '    break_even = float(primary.break_even_probability or 0.0)\n',
    '    calibrated_risk_ok = confidence_for_view is not None and confidence_for_view >= max(probability_floor, break_even)\n',
    '    positive_ev = primary.expected_value is not None and primary.expected_value > 0\n',
    '    interval_valid = primary.lower_bound is not None and primary.upper_bound is not None and primary.lower_bound < primary.upper_bound\n',
    '    can_trade_authority = market_view in {"BUY", "SELL"} and authority_tradeability == market_view\n',
    '    can_trade_forecast = primary.direction == market_view and not forecast_conflict and not primary.blocking_reasons and calibrated_risk_ok and positive_ev and interval_valid\n',
    '    if quality.status == "FAIL_ALL":\n',
    '        final_decision = "DATA NOT READY"\n',
    '    elif can_trade_authority and can_trade_forecast and not final_blockers:\n',
    '        final_decision = market_view\n',
    '    else:\n',
    '        final_decision = "WAIT"\n',
    '\n',
    '    confidence=confidence_for_view\n',
    '    uncertainty=100*(1-(confidence or 0)) if confidence is not None else 100.0\n',
    '    error_pct=None\n',
    '    if reliability.mean_absolute_price_error is not None and current_price:\n',
    '        error_pct=reliability.mean_absolute_price_error/abs(current_price)*100\n',
    '    risk_level="LOW" if final_decision in {"BUY","SELL"} and uncertainty<35 and drift.status=="STABLE" else "MEDIUM" if uncertainty<55 and drift.status in {"STABLE","WATCH"} else "HIGH"\n',
    '    supporting=[f"Full Metric H1 market view {market_view}",f"{selected}h forecast confirmation {primary.direction}",f"horizon agreement {agreement_score:.0%}",f"priority {priority.label} {priority.score:.1f}"] + [f"Soft warning: {x}" for x in sorted(set(final_soft_warnings))[:6]]\n',
    '    main_reason=("Full Metric H1 direction passed forecast, reliability, cost and timing confirmation gates" if final_decision in {"BUY","SELL"} else (final_blockers[0] if final_blockers else reason))\n',
    '    final=FinalDecision(\n',
    '        final_decision=final_decision,directional_market_view=market_view,tradeability_decision=final_decision if final_decision in {"BUY","SELL"} else "WAIT",less_risky_decision=final_decision if final_decision in {"BUY","SELL"} else "WAIT",main_reason=main_reason,supporting_reasons=supporting,blocking_reasons=sorted(set(final_blockers)),calibrated_confidence=confidence,actionability_probability=primary.actionability_probability if primary.direction == market_view else 0.0,expected_value=primary.expected_value if primary.direction == market_view else None,risk_level=risk_level,uncertainty_pct=uncertainty,error_estimate_pct=error_pct,selected_horizon=selected,decision_expiry_time=primary.due_time,regime_transition_warning=regime.transition_warning,drift_warning=drift.status,data_quality_warning=quality.status,\n',
    '    )\n',
    '    bundle=ForecastBundle(horizons=horizons,reconciliation_label=label,reconciliation_reason=reason,selected_horizon=selected,agreement_score=agreement_score)\n',
    '    interval_ok=primary.interval_width is not None and current_price is not None and primary.interval_width/abs(current_price)<=0.008\n',
    '    risk=RiskResult(risk_level=risk_level,uncertainty_pct=uncertainty,error_estimate_pct=error_pct,interval_acceptable=interval_ok,estimated_cost=primary.estimated_cost,cost_source="settled history or conservative symbol fallback")\n',
    '    similarity={f"{h}h":historical_similarity(frame,horizon=h) for h in HORIZONS}\n',
    '    expires=_utc_iso(created+pd.Timedelta(hours=1))\n',
    '    status="COMPLETED" if quality.status in {"PASS","PASS_WITH_WARNING"} else "COMPLETED_WITH_BLOCK"\n',
    '    return DecisionResult(\n',
    '        schema_version=SCHEMA_VERSION,run_id=run_id,calculation_generation=int(calculation_generation or 0),created_at=_utc_iso(created) or "",expires_at=expires,\n',
    '        symbol=symbol,timeframe=timeframe,source=source,latest_completed_candle_time=market.latest_completed_candle_time,data_signature=signature,model_version=MODEL_VERSION,\n',
    '        calculation_version=CALCULATION_VERSION,calculation_status=status,failure_reason=None,market=market,\n',
    '        data_quality=quality,regime=regime,forecasts=bundle,priority=priority,nlp=nlp,reliability=reliability,\n',
    '        drift=drift,risk=risk,final_decision=final,metadata={\n',
    '            "threshold_version":THRESHOLD_VERSION,"similarity":similarity,\n',
    '            "ledger_status":ledger.health(),"existing_logic_preserved":True,\n',
    '            "probability_note":"Calibrated only when settled out-of-sample samples are sufficient; otherwise marked proxy.",\n',
    '            "expected_value_note":"Estimate after conservative spread/slippage buffer; never guaranteed profit.",\n',
    '            "primary_calculation_authority":"Full Metric Detail + History" if full_metric else "legacy compatibility",\n',
    '            "full_metric_direction":market_view,\n',
    '            "confirmation_components_cannot_reverse_direction":bool(full_metric),\n',
    '            "m1_role":"entry timing and confirmation only",\n',
    '            "wait_policy_version":"hard-soft-selective-classification-20260619-v1",\n',
    '            "hard_blockers":sorted(set(final_blockers)),\n',
    '            "soft_penalties":sorted(set(final_soft_warnings)),\n',
    '            "soft_penalties_by_horizon":_json_safe(soft_penalties_by_horizon),\n',
    '            "coverage_gate":{"calibrated_probability_floor":probability_floor,"break_even_probability":break_even,"positive_expected_value_required":True,"m1_neutral_is_soft":True},\n',
    '            "reliability_components":{"ledger_walk_forward":_json_safe(asdict(reliability)),"legacy_existing_score":legacy_reliability},\n',
    '        },\n',
    '    )\n',
    '\n',
    '\n',
    'def serialize_result(result: DecisionResult) -> Dict[str,Any]:\n',
    '    return _json_safe(result.to_dict())\n',
]
