"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '\n',
    '\n',
    'def _atr(frame: pd.DataFrame, window: int = 14) -> Optional[float]:\n',
    '    if frame.empty or len(frame) < 2: return None\n',
    '    prev = frame["close"].shift(1)\n',
    '    tr = pd.concat([(frame["high"]-frame["low"]).abs(), (frame["high"]-prev).abs(), (frame["low"]-prev).abs()], axis=1).max(axis=1)\n',
    '    val = tr.tail(window).mean()\n',
    '    return _finite(val, None)\n',
    '\n',
    '\n',
    'def _raw_probabilities(direction: str, parts: Dict[str, Any], horizon: int) -> Tuple[Optional[float], Optional[float], Optional[float], str]:\n',
    '    confidence = _finite(parts["powerbi"].get("confidence") or parts["current"].get("forecast_confidence") or parts["reliability"].get("score"), None)\n',
    '    if confidence is None:\n',
    '        return None, None, None, "UNAVAILABLE"\n',
    '    if confidence > 1: confidence /= 100.0\n',
    '    confidence = _clip(confidence, 0.34, 0.95, 0.5)\n',
    '    # Longer horizons receive a conservative decay, not additional information.\n',
    '    confidence = 0.5 + (confidence - 0.5) * (1.0 - min(0.35, 0.05 * max(0, horizon - 1)))\n',
    '    wait = max(0.05, min(0.45, 1.0 - confidence))\n',
    '    remaining = 1.0 - wait\n',
    '    if direction == "BUY": buy, sell = remaining * 0.86, remaining * 0.14\n',
    '    elif direction == "SELL": sell, buy = remaining * 0.86, remaining * 0.14\n',
    '    else: buy = sell = (1.0 - max(wait, 0.5)) / 2; wait = max(wait, 0.5)\n',
    '    total = buy + sell + wait\n',
    '    return buy/total, sell/total, wait/total, "EXISTING_RELIABILITY_PROXY"\n',
    '\n',
    '\n',
    'def _calibration_diagnostics(probabilities: np.ndarray, outcomes: np.ndarray) -> Dict[str, Any]:\n',
    '    probabilities = np.clip(np.asarray(probabilities, dtype=float), 1e-6, 1 - 1e-6)\n',
    '    outcomes = np.asarray(outcomes, dtype=float)\n',
    '    if len(probabilities) == 0:\n',
    '        return {}\n',
    '    brier = float(np.mean((probabilities - outcomes) ** 2))\n',
    '    logloss = float(-np.mean(outcomes * np.log(probabilities) + (1 - outcomes) * np.log(1 - probabilities)))\n',
    '    buckets: List[Dict[str, Any]] = []\n',
    '    ece = 0.0\n',
    '    for lower in np.linspace(0.0, 0.9, 10):\n',
    '        upper = lower + 0.1\n',
    '        mask = (probabilities >= lower) & (probabilities < upper if upper < 1.0 else probabilities <= upper)\n',
    '        count = int(mask.sum())\n',
    '        if not count:\n',
    '            continue\n',
    '        confidence = float(probabilities[mask].mean())\n',
    '        observed = float(outcomes[mask].mean())\n',
    '        ece += (count / len(probabilities)) * abs(confidence - observed)\n',
    '        buckets.append({\n',
    '            "lower": round(float(lower), 2), "upper": round(float(upper), 2),\n',
    '            "count": count, "mean_probability": confidence, "observed_frequency": observed,\n',
    '        })\n',
    '    return {\n',
    '        "brier_score": brier, "log_loss": logloss,\n',
    '        "expected_calibration_error": float(ece), "reliability_buckets": buckets,\n',
    '    }\n',
    '\n',
    '\n',
    'def _fit_calibrator(history: pd.DataFrame, class_name: str, current_p: Optional[float]) -> Tuple[Optional[float], str, int, Dict[str, Any]]:\n',
    '    """Fit only on settled out-of-sample predictions, with chronological holdout diagnostics."""\n',
    '    if current_p is None or history.empty:\n',
    '        return current_p, "EXISTING_RELIABILITY_PROXY", 0, {}\n',
    '    pcol = f"{class_name.lower()}_probability_raw"\n',
    '    if pcol not in history.columns or "actual_direction" not in history.columns:\n',
    '        return current_p, "EXISTING_RELIABILITY_PROXY", len(history), {}\n',
    '    ordered = history.copy()\n',
    '    if "created_at" in ordered.columns:\n',
    '        ordered["_created"] = pd.to_datetime(ordered["created_at"], utc=True, errors="coerce")\n',
    '        ordered = ordered.sort_values("_created")\n',
    '    x = pd.to_numeric(ordered[pcol], errors="coerce")\n',
    '    y = (ordered["actual_direction"].astype(str).str.upper() == class_name.upper()).astype(int)\n',
    '    valid = x.notna() & y.notna()\n',
    '    x, y = x[valid].reset_index(drop=True), y[valid].reset_index(drop=True)\n',
    '    n = len(x)\n',
    '    if n < 30 or y.nunique() < 2:\n',
    '        return current_p, "EXISTING_RELIABILITY_PROXY", n, {}\n',
    '    try:\n',
    '        from sklearn.isotonic import IsotonicRegression\n',
    '        from sklearn.linear_model import LogisticRegression\n',
    '\n',
    '        method = "ISOTONIC_OOS" if n >= 200 else "SIGMOID_OOS"\n',
    '\n',
    '        def make_model(sample_count: int):\n',
    '            if sample_count >= 200:\n',
    '                return IsotonicRegression(out_of_bounds="clip")\n',
    '            return LogisticRegression(solver="lbfgs", class_weight="balanced", max_iter=500)\n',
    '\n',
    '        # Final 20% is never used for the reported calibration diagnostics.\n',
    '        split = min(n - 10, max(20, int(n * 0.8)))\n',
    '        x_train, y_train = x.iloc[:split], y.iloc[:split]\n',
    '        x_test, y_test = x.iloc[split:], y.iloc[split:]\n',
    '        test_metrics: Dict[str, Any] = {}\n',
    '        if len(x_test) >= 10 and y_train.nunique() >= 2:\n',
    '            eval_model = make_model(len(x_train))\n',
    '            if isinstance(eval_model, IsotonicRegression):\n',
    '                eval_model.fit(x_train.to_numpy(), y_train.to_numpy())\n',
    '                test_p = eval_model.predict(x_test.to_numpy())\n',
    '            else:\n',
    '                eval_model.fit(x_train.to_numpy().reshape(-1, 1), y_train.to_numpy())\n',
    '                test_p = eval_model.predict_proba(x_test.to_numpy().reshape(-1, 1))[:, 1]\n',
    '            test_metrics = _calibration_diagnostics(test_p, y_test.to_numpy())\n',
    '            test_metrics["validation_sample_count"] = int(len(x_test))\n',
    '            test_metrics["training_sample_count"] = int(len(x_train))\n',
    '            test_metrics["validation_policy"] = "chronological final 20% holdout"\n',
    '\n',
    '        final_model = make_model(n)\n',
    '        if isinstance(final_model, IsotonicRegression):\n',
    '            final_model.fit(x.to_numpy(), y.to_numpy())\n',
    '            calibrated = float(final_model.predict([current_p])[0])\n',
    '        else:\n',
    '            final_model.fit(x.to_numpy().reshape(-1, 1), y.to_numpy())\n',
    '            calibrated = float(final_model.predict_proba([[current_p]])[0, 1])\n',
    '        return _clip(calibrated), method, n, test_metrics\n',
    '    except Exception:\n',
    '        return current_p, "EXISTING_RELIABILITY_PROXY", n, {}\n',
    '\n',
    'def calibrate_probabilities(\n',
    '    ledger: PredictionLedger, *, symbol: str, timeframe: str, horizon: int,\n',
    '    regime: str, raw: Tuple[Optional[float], Optional[float], Optional[float]],\n',
    ') -> Tuple[Tuple[Optional[float], Optional[float], Optional[float]], str, Dict[str, Any]]:\n',
    '    history = ledger.settled_predictions(symbol=symbol, timeframe=timeframe, horizon=horizon, limit=4000)\n',
    '    hierarchy = [\n',
    '        (history[history.get("major_regime", pd.Series(index=history.index, dtype=str)).astype(str) == str(regime)] if not history.empty and "major_regime" in history else pd.DataFrame(), "SYMBOL_TF_HORIZON_REGIME"),\n',
    '        (history, "SYMBOL_TF_HORIZON"),\n',
    '        (ledger.settled_predictions(symbol=symbol, horizon=horizon, limit=4000), "SYMBOL_HORIZON"),\n',
    '        (ledger.settled_predictions(horizon=horizon, limit=6000), "GLOBAL_HORIZON"),\n',
    '    ]\n',
    '    selected = pd.DataFrame(); scope = "EXISTING_RELIABILITY_PROXY"\n',
    '    for candidate, label in hierarchy:\n',
    '        if isinstance(candidate, pd.DataFrame) and len(candidate) >= 30:\n',
    '            selected = candidate; scope = label; break\n',
    '    calibrated: List[Optional[float]] = []\n',
    '    methods: List[str] = []\n',
    '    metrics: Dict[str, Any] = {"sample_count": len(selected), "scope": scope}\n',
    '    for cls, p in zip(("BUY", "SELL", "WAIT"), raw):\n',
    '        cp, method, n, met = _fit_calibrator(selected, cls, p)\n',
    '        calibrated.append(cp); methods.append(method); metrics[f"{cls.lower()}_sample_count"] = n\n',
    '        metrics.update({f"{cls.lower()}_{k}": v for k,v in met.items()})\n',
    '    if all(p is not None for p in calibrated):\n',
    '        arr = np.clip(np.asarray(calibrated, dtype=float), 0, 1)\n',
    '        total = float(arr.sum())\n',
    '        arr = arr / total if total > 0 else np.array([1/3,1/3,1/3])\n',
    '        calibrated = [float(x) for x in arr]\n',
    '    source = "+".join(sorted(set(methods))) + ":" + scope\n',
    '    return (calibrated[0], calibrated[1], calibrated[2]), source, metrics\n',
    '\n',
    '\n',
    'def _interval(history: pd.DataFrame, current: float, point: Optional[float], horizon: int, atr: Optional[float], drift_multiplier: float) -> Tuple[Optional[float], Optional[float], int, Optional[float], float, Optional[float]]:\n',
    '    target = 0.90\n',
    '    residuals = pd.to_numeric(history.get("absolute_error", pd.Series(dtype=float)), errors="coerce").dropna() if not history.empty else pd.Series(dtype=float)\n',
    '    coverage = None\n',
    '    if not history.empty and {"actual_price","lower_bound","upper_bound"}.issubset(history.columns):\n',
    '        valid = history[["actual_price","lower_bound","upper_bound"]].apply(pd.to_numeric, errors="coerce").dropna()\n',
    '        if len(valid): coverage = float(((valid.actual_price >= valid.lower_bound) & (valid.actual_price <= valid.upper_bound)).mean())\n',
    '    if len(residuals) >= 20:\n',
    '        radius = float(np.quantile(residuals, target))\n',
    '        if coverage is not None and coverage < target:\n',
    '            radius *= 1 + min(0.75, (target-coverage)*2.5)\n',
    '    else:\n',
    '        radius = (atr or abs(current)*0.0008) * math.sqrt(max(1,horizon)) * 1.35\n',
    '    radius *= max(1.0, drift_multiplier)\n',
    '    if point is None: return None, None, len(residuals), coverage, target, None\n',
    '    lower, upper = point-radius, point+radius\n',
    '    return lower, upper, len(residuals), coverage, target, (coverage-target if coverage is not None else None)\n',
    '\n',
    '\n',
    'def _optimize_threshold(history: pd.DataFrame, fallback: float) -> Tuple[float, str]:\n',
    '    if history.empty or len(history) < 40:\n',
    '        return fallback, "fallback-v1"\n',
    '    data = history.sort_values("created_at") if "created_at" in history else history.copy()\n',
    '    train = data.iloc[:max(1,int(len(data)*0.8))]\n',
    '    if len(train) < 32: return fallback, "fallback-v1"\n',
    '    probs = []\n',
    '    for _, row in train.iterrows():\n',
    '        d = str(row.get("predicted_direction") or "WAIT").upper()\n',
    '        p = _finite(row.get(f"{d.lower()}_probability_calibrated"), None) or _finite(row.get(f"{d.lower()}_probability_raw"), None)\n',
    '        probs.append(p)\n',
    '    train = train.assign(_p=probs)\n',
    '    train = train[train._p.notna()]\n',
    '    if len(train) < 30: return fallback, "fallback-v1"\n',
    '    best_t, best_u = fallback, -1e18\n',
    '    for t in np.arange(0.52,0.761,0.02):\n',
    '        take = train[train._p >= t]\n',
    '        if len(take) < 8: continue\n',
    '        correct = pd.to_numeric(take.get("direction_correct"), errors="coerce").fillna(0)\n',
    '        mfe = pd.to_numeric(take.get("maximum_favourable_excursion"), errors="coerce").fillna(0)\n',
    '        mae = pd.to_numeric(take.get("maximum_adverse_excursion"), errors="coerce").fillna(0)\n',
    '        cost = pd.to_numeric(take.get("estimated_cost"), errors="coerce").fillna(0)\n',
    '        net = np.where(correct>0, mfe, -mae) - cost\n',
    '        equity = np.cumsum(net)\n',
    '        drawdown = float(np.max(np.maximum.accumulate(equity)-equity)) if len(equity) else 0\n',
    '        false_penalty = float((correct==0).mean())\n',
    '        trade_penalty = max(0.0, len(take)/len(train)-0.65)\n',
    '        utility = float(np.sum(net) - 0.35*drawdown - 0.15*false_penalty - 0.1*trade_penalty)\n',
    '        if utility > best_u: best_t,best_u=float(t),utility\n',
    '    return max(0.52,min(0.76,best_t)), "walk-forward-utility-v1"\n',
    '\n',
    '\n',
    'def dynamic_threshold(\n',
    '    *, horizon: int, regime: RegimeResult, drift: DriftResult, quality: DataQualityResult,\n',
    '    expected_value: Optional[float], interval_width_ratio: Optional[float], agreement: float,\n',
    '    priority: PriorityResult, actionability: float, session: str, history: pd.DataFrame,\n',
    ') -> Tuple[float, str, List[str]]:\n',
    '    fallback = {1:0.58,2:0.59,3:0.60,6:0.62}.get(horizon,0.60)\n',
    '    base, version = _optimize_threshold(history, fallback)\n',
    '    reasons: List[str] = []\n',
    '    reg_dir = _direction(regime.major_regime)\n',
    '    if reg_dir in {"BUY","SELL"} and regime.confidence >= 0.65 and regime.transition_probability_3h < 0.35:\n',
    '        base -= 0.025; reasons.append("strong aligned regime")\n',
    '    if reg_dir == "WAIT" or "RANGE" in regime.major_regime.upper():\n',
    '        base += 0.04; reasons.append("range regime")\n',
    '    transition = {1:regime.transition_probability_1h,2:regime.transition_probability_3h,3:regime.transition_probability_3h,6:regime.transition_probability_6h}[horizon]\n',
    '    if transition >= 0.5: base += 0.045; reasons.append("transition risk")\n',
    '    if drift.status == "WATCH": base += 0.015\n',
    '    elif drift.status == "DEGRADED": base += 0.045; reasons.append("degraded drift")\n',
    '    elif drift.status == "CRITICAL": base += 0.09; reasons.append("critical drift")\n',
    '    if quality.status == "PASS_WITH_WARNING": base += 0.02\n',
    '    elif quality.status.startswith("FAIL"): base = 0.99; reasons.append("data quality block")\n',
    '    if expected_value is not None and expected_value <= 0: base = max(base,0.99); reasons.append("negative expected value")\n',
    '    if interval_width_ratio is not None and interval_width_ratio > 0.004: base += 0.03; reasons.append("wide interval")\n',
    '    if agreement < 0.45: base += 0.06; reasons.append("forecast disagreement")\n',
    '    if priority.score < 45: base += 0.04\n',
    '    if actionability < 0.5: base += 0.05\n',
    '    if session in {"LATE"}: base += 0.01\n',
    '    return max(0.52,min(0.99,base)), version or THRESHOLD_VERSION, reasons\n',
    '\n',
    '\n',
    'def _expected_value(history: pd.DataFrame, direction_p: Optional[float], current: float, atr: Optional[float], horizon: int, symbol: str) -> Dict[str, Any]:\n',
    '    pip_size = 0.01 if "JPY" in symbol.upper() else 0.0001\n',
    '    spread = pip_size * (1.2 if "EURUSD" in symbol.upper() else 2.0)\n',
    '    slippage = spread * 0.35\n',
    '    buffer = spread * 0.25\n',
    '    estimated_cost = spread + slippage + buffer\n',
    '    correct = history[pd.to_numeric(history.get("direction_correct"), errors="coerce")==1] if not history.empty and "direction_correct" in history else pd.DataFrame()\n',
    '    wrong = history[pd.to_numeric(history.get("direction_correct"), errors="coerce")==0] if not history.empty and "direction_correct" in history else pd.DataFrame()\n',
    '    if len(correct) >= 10:\n',
    '        avg_gain = float(pd.to_numeric(correct.get("maximum_favourable_excursion"), errors="coerce").dropna().median())\n',
    '        gain_source = "settled MFE"\n',
    '    else:\n',
    '        avg_gain = (atr or abs(current)*0.0007) * math.sqrt(horizon)\n',
    '        gain_source = "ATR fallback"\n',
    '    if len(wrong) >= 10:\n',
    '        avg_loss = float(pd.to_numeric(wrong.get("maximum_adverse_excursion"), errors="coerce").dropna().median())\n',
    '        loss_source = "settled MAE"\n',
    '    else:\n',
    '        avg_loss = (atr or abs(current)*0.0007) * math.sqrt(horizon) * 0.9\n',
    '        loss_source = "ATR fallback"\n',
    '    if direction_p is None:\n',
    '        return {"expected_gain":None,"expected_loss":None,"estimated_cost":estimated_cost,"expected_value":None,"risk_reward":None,"break_even_probability":None,"source":f"{gain_source}/{loss_source}"}\n',
    '    expected_gain = direction_p * avg_gain\n',
    '    expected_loss = (1-direction_p) * avg_loss\n',
    '    ev = expected_gain - expected_loss - estimated_cost\n',
    '    rr = avg_gain/avg_loss if avg_loss>0 else None\n',
    '    bep = (avg_loss+estimated_cost)/(avg_gain+avg_loss) if avg_gain+avg_loss>0 else None\n',
    '    return {"expected_gain":expected_gain,"expected_loss":expected_loss,"estimated_cost":estimated_cost,"expected_value":ev,"risk_reward":rr,"break_even_probability":bep,"source":f"{gain_source}/{loss_source}"}\n',
    '\n',
    '\n',
    'def _actionability(history: pd.DataFrame, *, probability: Optional[float], interval_ratio: Optional[float], priority: float, expected_value: Optional[float], transition: float, drift: DriftResult, quality: DataQualityResult, nlp: NLPResult) -> Tuple[float,str,str,List[str],str]:\n',
    '    """Estimate coverage while keeping hard blockers separate from soft evidence.\n',
    '\n',
    '    Moderate disagreement, slightly low priority, neutral timing and limited\n',
    '    samples reduce the score but do not automatically force WAIT.  Only safety\n',
    '    failures are returned in ``blockers``.\n',
    '    """\n',
    '    blockers: List[str] = []\n',
    '    p = probability or 0.0\n',
    '    if len(history) >= 60 and "direction_correct" in history:\n',
    '        try:\n',
    '            from sklearn.linear_model import LogisticRegression\n',
    '            data = history.sort_values("created_at") if "created_at" in history else history.copy()\n',
    '            data = data.iloc[:max(1,int(len(data)*0.8))]\n',
    '            feats = pd.DataFrame({\n',
    '                "p": pd.to_numeric(data.get("buy_probability_calibrated"), errors="coerce").fillna(pd.to_numeric(data.get("sell_probability_calibrated"), errors="coerce")).fillna(0.5),\n',
    '                "priority": pd.to_numeric(data.get("priority_score"), errors="coerce").fillna(50)/100,\n',
    '                "ev": pd.to_numeric(data.get("expected_value"), errors="coerce").fillna(0),\n',
    '                "width": (pd.to_numeric(data.get("upper_bound"), errors="coerce")-pd.to_numeric(data.get("lower_bound"), errors="coerce")).abs().fillna(0),\n',
    '            })\n',
    '            y = pd.to_numeric(data["direction_correct"], errors="coerce").fillna(0).astype(int)\n',
    '            if y.nunique() >= 2:\n',
    '                model = LogisticRegression(class_weight="balanced", max_iter=300)\n',
    '                model.fit(feats, y)\n',
    '                cur = [[p, priority/100, expected_value or 0, interval_ratio or 0]]\n',
    '                prob = float(model.predict_proba(cur)[0,1]); source="CHRONOLOGICAL_LOGISTIC_META"\n',
    '            else:\n',
    '                raise ValueError("one class")\n',
    '        except Exception:\n',
    '            prob = 0.42*p + 0.25*(priority/100) + 0.18*(1-transition) + 0.15*quality.score/100; source="DETERMINISTIC_FALLBACK"\n',
    '    else:\n',
    '        prob = 0.42*p + 0.25*(priority/100) + 0.18*(1-transition) + 0.15*quality.score/100; source="DETERMINISTIC_FALLBACK"\n',
    '    if interval_ratio is not None:\n',
    '        prob -= min(0.16, interval_ratio*14)\n',
    '    if expected_value is None:\n',
    '        prob -= 0.16\n',
    '        blockers.append("expected value after costs is unavailable")\n',
    '    elif expected_value <= 0:\n',
    '        prob -= 0.30\n',
    '        blockers.append("negative expected value after costs")\n',
    '    if drift.status == "DEGRADED":\n',
    '        prob -= 0.10\n',
    '    if drift.status == "CRITICAL":\n',
    '        prob -= 0.28\n',
    '        blockers.append("critical forecast drift")\n',
    '    if quality.status.startswith("FAIL"):\n',
    '        prob = 0\n',
    '        blockers.append("critical market data quality failure")\n',
    '    if transition >= 0.85:\n',
    '        prob -= 0.25\n',
    '        blockers.append("critical regime transition risk")\n',
    '    elif transition >= 0.55:\n',
    '        prob -= 0.08\n',
    '    if nlp.conflict_level == "CRITICAL" and nlp.importance >= 0.65:\n',
    '        prob -= 0.20\n',
    '        blockers.append("severe event conflict")\n',
    '    elif nlp.conflict_level == "HIGH" and nlp.importance >= 0.65:\n',
    '        prob -= 0.08\n',
    '    prob = _clip(prob)\n',
    '    label = "YES" if prob >= 0.50 and not blockers else "NO"\n',
    '    reason = "Signal passes hard safety gates" if label=="YES" else (blockers[0] if blockers else "Evidence remains below the controlled coverage gate")\n',
    '    return prob,label,reason,blockers,source\n',
    '\n',
    '\n',
    'def compute_drift(ledger: PredictionLedger, frame: pd.DataFrame, *, symbol: str, timeframe: str) -> DriftResult:\n',
    '    settled = ledger.settled_predictions(symbol=symbol,timeframe=timeframe,limit=800)\n',
    '    reasons: List[str] = []\n',
    '    prediction_score=0.0\n',
    '    if len(settled) >= 40:\n',
    '        data=settled.sort_values("created_at") if "created_at" in settled else settled\n',
    '        recent=data.tail(max(15,int(len(data)*0.2))); base=data.iloc[:-len(recent)]\n',
    '        rec_err=pd.to_numeric(recent.get("absolute_error"),errors="coerce").dropna()\n',
    '        base_err=pd.to_numeric(base.get("absolute_error"),errors="coerce").dropna()\n',
    '        if len(rec_err)>=5 and len(base_err)>=15 and base_err.median()>0:\n',
    '            ratio=float(rec_err.median()/base_err.median())\n',
    '            if ratio>1.8: prediction_score+=55; reasons.append("forecast error sharply increased")\n',
    '            elif ratio>1.3: prediction_score+=28; reasons.append("forecast error increased")\n',
    '        rec_acc=pd.to_numeric(recent.get("direction_correct"),errors="coerce").mean()\n',
    '        base_acc=pd.to_numeric(base.get("direction_correct"),errors="coerce").mean()\n',
    '        if pd.notna(rec_acc) and pd.notna(base_acc) and base_acc-rec_acc>0.18: prediction_score+=30; reasons.append("direction accuracy deteriorated")\n',
    '    feature_score=0.0\n',
    '    if len(frame)>=120:\n',
    '        returns=frame.close.pct_change().dropna()\n',
    '        recent=returns.tail(24); base=returns.iloc[-240:-24] if len(returns)>=264 else returns.iloc[:-24]\n',
    '        if len(base)>=40 and base.std()>0:\n',
    '            z=abs(float(recent.std()-base.std()))/float(base.std())\n',
    '            if z>1.0: feature_score+=45; reasons.append("volatility feature drift")\n',
    '            elif z>0.5: feature_score+=22\n',
    '        ranges=(frame.high-frame.low).abs()\n',
    '        if len(ranges)>=120:\n',
    '            r_ratio=float(ranges.tail(24).median()/max(ranges.iloc[:-24].median(),1e-12))\n',
    '            if r_ratio>2.0 or r_ratio<0.45: feature_score+=35; reasons.append("range/ATR distribution shifted")\n',
    '    runs=ledger.recent_runs(symbol=symbol,timeframe=timeframe,limit=160)\n',
    '    decision_score=0.0\n',
    '    if len(runs)>=30 and "result_json" in runs:\n',
    '        decisions=[]\n',
    '        for val in runs.result_json:\n',
    '            try: decisions.append(json.loads(val).get("final_decision",{}).get("final_decision","WAIT"))\n',
    '            except Exception: decisions.append("WAIT")\n',
    '        ser=pd.Series(decisions)\n',
    '        recent=ser.head(20); older=ser.iloc[20:]\n',
    '        if len(older)>=10:\n',
    '            drift=sum(abs(float((recent==x).mean()-(older==x).mean())) for x in ("BUY","SELL","WAIT"))\n',
    '            if drift>0.8: decision_score+=45; reasons.append("decision frequency shifted")\n',
    '    score=max(prediction_score,feature_score,decision_score)\n',
    '    status="CRITICAL" if score>=75 else "DEGRADED" if score>=50 else "WATCH" if score>=25 else "STABLE"\n',
    '    return DriftResult(\n',
    '        status=status,score=min(100,score),\n',
    '        prediction_status="CRITICAL" if prediction_score>=75 else "DEGRADED" if prediction_score>=50 else "WATCH" if prediction_score>=25 else "STABLE",\n',
    '        feature_status="CRITICAL" if feature_score>=75 else "DEGRADED" if feature_score>=50 else "WATCH" if feature_score>=25 else "STABLE",\n',
    '        decision_status="CRITICAL" if decision_score>=75 else "DEGRADED" if decision_score>=50 else "WATCH" if decision_score>=25 else "STABLE",\n',
    '        reasons=reasons, threshold_adjustment={"STABLE":0,"WATCH":0.015,"DEGRADED":0.045,"CRITICAL":0.09}[status],\n',
    '        interval_multiplier={"STABLE":1,"WATCH":1.08,"DEGRADED":1.25,"CRITICAL":1.55}[status],\n',
    '        retraining_recommended=status in {"DEGRADED","CRITICAL"},\n',
    '    )\n',
    '\n',
    '\n',
    'def _purged_walk_forward_direction_metrics(data: pd.DataFrame, horizon: int) -> Dict[str, Any]:\n',
    '    """Evaluate existing OOS ledger predictions in chronological purged windows.\n',
    '\n',
    '    The ledger rows are predictions produced before their outcomes were known.  This\n',
    '    evaluator still removes at least ``horizon`` rows between each expanding history\n',
    '    window and test window, plus one embargo row, so overlapping labels are not mixed.\n',
    '    """\n',
    '    if len(data) < 60:\n',
    '        return {\n',
    '            "status": "INSUFFICIENT SAMPLE", "fold_count": 0,\n',
    '            "purge_gap_rows": int(max(6, horizon)), "embargo_rows": 1,\n',
    '        }\n',
    '    ordered = data.copy()\n',
    '    ordered["_created"] = pd.to_datetime(ordered.get("created_at"), utc=True, errors="coerce")\n',
    '    ordered = ordered.sort_values("_created").reset_index(drop=True)\n',
    '    purge = int(max(6, horizon))\n',
    '    embargo = 1\n',
    '    min_history = max(40, int(len(ordered) * 0.45))\n',
    '    test_size = max(10, int(len(ordered) * 0.15))\n',
    '    fold_scores: List[float] = []\n',
    '    fold_balanced: List[float] = []\n',
    '    test_samples = 0\n',
    '    train_end = min_history\n',
    '    while train_end + purge + embargo + 5 <= len(ordered):\n',
    '        test_start = train_end + purge\n',
    '        test_end = min(len(ordered), test_start + test_size)\n',
    '        test = ordered.iloc[test_start:test_end]\n',
    '        if len(test) < 5:\n',
    '            break\n',
    '        actual = test["actual_direction"].astype(str).str.upper()\n',
    '        predicted = test["predicted_direction"].astype(str).str.upper()\n',
    '        fold_scores.append(float((actual == predicted).mean()))\n',
    '        try:\n',
    '            from sklearn.metrics import balanced_accuracy_score\n',
    '            fold_balanced.append(float(balanced_accuracy_score(actual, predicted)))\n',
    '        except Exception:\n',
    '            fold_balanced.append(fold_scores[-1])\n',
    '        test_samples += len(test)\n',
    '        train_end = test_end + embargo\n',
    '    if not fold_scores:\n',
    '        return {\n',
    '            "status": "INSUFFICIENT SAMPLE", "fold_count": 0,\n',
    '            "purge_gap_rows": purge, "embargo_rows": embargo,\n',
    '        }\n',
    '    return {\n',
    '        "status": "VALID", "fold_count": len(fold_scores),\n',
    '        "purge_gap_rows": purge, "embargo_rows": embargo,\n',
    '        "test_samples": int(test_samples),\n',
    '        "direction_accuracy": float(np.mean(fold_scores)),\n',
]
