"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""End-to-end reliability layer for the existing ADX Quant Pro engines.\n',
    '\n',
    'This module adds no standalone price-prediction model.  It adapts existing\n',
    'PowerBI/regime/priority/NLP outputs, validates their input data, records every\n',
    'run, calibrates only from settled out-of-sample ledger rows, reconciles 1/2/3/6\n',
    'hour horizons, and applies one auditable tradeability policy.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import hashlib\n',
    'import json\n',
    'import math\n',
    'import uuid\n',
    'from dataclasses import asdict\n',
    'from datetime import datetime, timedelta, timezone\n',
    'from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'from core.decision_contract_20260617 import (\n',
    '    CALCULATION_VERSION, MODEL_VERSION, SCHEMA_VERSION, DataQualityResult,\n',
    '    DecisionResult, DriftResult, FinalDecision, ForecastBundle, HorizonForecast,\n',
    '    MarketState, NLPResult, PriorityResult, RegimeResult, ReliabilityResult,\n',
    '    RiskResult,\n',
    ')\n',
    'from core.prediction_ledger_20260617 import PredictionLedger, get_prediction_ledger\n',
    '\n',
    'HORIZONS = (1, 2, 3, 6)\n',
    'THRESHOLD_VERSION = "dynamic-threshold-v1"\n',
    '\n',
    '\n',
    'def _finite(value: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    try:\n',
    '        out = float(value)\n',
    '        return out if math.isfinite(out) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(value: Any, lo: float = 0.0, hi: float = 1.0, default: float = 0.0) -> float:\n',
    '    val = _finite(value, default)\n',
    '    return float(max(lo, min(hi, val if val is not None else default)))\n',
    '\n',
    '\n',
    'def _utc_iso(value: Any = None) -> Optional[str]:\n',
    '    try:\n',
    '        ts = pd.Timestamp(value if value is not None else datetime.now(timezone.utc))\n',
    '        if pd.isna(ts):\n',
    '            return None\n',
    '        if ts.tzinfo is None:\n',
    '            ts = ts.tz_localize("UTC")\n',
    '        else:\n',
    '            ts = ts.tz_convert("UTC")\n',
    '        return ts.isoformat()\n',
    '    except Exception:\n',
    '        return None\n',
    '\n',
    '\n',
    'def _json_safe(value: Any) -> Any:\n',
    '    if isinstance(value, dict):\n',
    '        return {str(k): _json_safe(v) for k, v in value.items()}\n',
    '    if isinstance(value, (list, tuple)):\n',
    '        return [_json_safe(v) for v in value]\n',
    '    if isinstance(value, pd.DataFrame):\n',
    '        return value.to_dict("records")\n',
    '    if isinstance(value, pd.Series):\n',
    '        return value.to_list()\n',
    '    if isinstance(value, (np.integer,)): return int(value)\n',
    '    if isinstance(value, (np.floating,)): return _finite(value)\n',
    '    if isinstance(value, (pd.Timestamp, datetime)): return _utc_iso(value)\n',
    '    return value\n',
    '\n',
    '\n',
    'def normalize_ohlc(df: Any) -> pd.DataFrame:\n',
    '    if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close", "volume"])\n',
    '    raw = df.copy()\n',
    '    cmap = {str(c).strip().lower(): c for c in raw.columns}\n',
    '    tcol = next((cmap.get(x) for x in ("time", "timestamp", "datetime", "date") if cmap.get(x) is not None), None)\n',
    '    columns: Dict[str, Any] = {}\n',
    '    for name, aliases in {\n',
    '        "open": ("open", "o"), "high": ("high", "h"), "low": ("low", "l"), "close": ("close", "c")\n',
    '    }.items():\n',
    '        col = next((cmap.get(a) for a in aliases if cmap.get(a) is not None), None)\n',
    '        if col is not None:\n',
    '            columns[name] = pd.to_numeric(raw[col], errors="coerce")\n',
    '    if tcol is not None:\n',
    '        times = pd.to_datetime(raw[tcol], utc=True, errors="coerce")\n',
    '    else:\n',
    '        times = pd.to_datetime(raw.index, utc=True, errors="coerce")\n',
    '    out = pd.DataFrame(columns)\n',
    '    out.insert(0, "time", times)\n',
    '    vcol = next((cmap.get(x) for x in ("volume", "tick_volume", "vol") if cmap.get(x) is not None), None)\n',
    '    out["volume"] = pd.to_numeric(raw[vcol], errors="coerce") if vcol is not None else np.nan\n',
    '    return out.reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _timeframe_hours(timeframe: str) -> Optional[float]:\n',
    '    text = str(timeframe or "").strip().upper()\n',
    '    if text.startswith("H"):\n',
    '        return _finite(text[1:], None)\n',
    '    if text.startswith("M"):\n',
    '        mins = _finite(text[1:], None)\n',
    '        return mins / 60.0 if mins else None\n',
    '    if text.startswith("D"):\n',
    '        days = _finite(text[1:], None)\n',
    '        return days * 24.0 if days else None\n',
    '    return None\n',
    '\n',
    '\n',
    'def validate_data_quality(\n',
    '    df: Any, *, symbol: str, timeframe: str, source: str, now: Any = None,\n',
    '    minimum_rows: int = 120,\n',
    ') -> Tuple[DataQualityResult, pd.DataFrame]:\n',
    '    raw = normalize_ohlc(df)\n',
    '    blocking: List[str] = []\n',
    '    warnings: List[str] = []\n',
    '    disabled: List[str] = []\n',
    '    required = {"time", "open", "high", "low", "close"}\n',
    '    if not required.issubset(raw.columns):\n',
    '        missing = sorted(required.difference(raw.columns))\n',
    '        blocking.append("Missing required columns: " + ", ".join(missing))\n',
    '        return DataQualityResult(status="FAIL_ALL", score=0, blocking_reasons=blocking), raw\n',
    '\n',
    '    invalid_time = int(raw["time"].isna().sum())\n',
    '    if invalid_time:\n',
    '        warnings.append(f"{invalid_time} rows have invalid timestamps and were excluded")\n',
    '    frame = raw.dropna(subset=["time"]).copy()\n',
    '    duplicates = int(frame["time"].duplicated(keep=False).sum())\n',
    '    if duplicates:\n',
    '        blocking.append(f"Duplicate candle timestamps: {duplicates}")\n',
    '        disabled.append("time-series models")\n',
    '    unordered = not frame["time"].is_monotonic_increasing\n',
    '    if unordered:\n',
    '        warnings.append("Timestamps were not ordered; calculations use chronological order")\n',
    '    frame = frame.sort_values("time").drop_duplicates("time", keep="last").reset_index(drop=True)\n',
    '\n',
    '    numeric_missing = frame[["open", "high", "low", "close"]].isna().any(axis=1)\n',
    '    missing_pct = float(numeric_missing.mean() * 100) if len(frame) else 100.0\n',
    '    if missing_pct > 5:\n',
    '        blocking.append(f"Missing OHLC rows {missing_pct:.2f}% exceeds 5%")\n',
    '        disabled.append("price models")\n',
    '    elif missing_pct > 0:\n',
    '        warnings.append(f"Missing OHLC rows: {missing_pct:.2f}%")\n',
    '    frame = frame.loc[~numeric_missing].copy()\n',
    '\n',
    '    if len(frame) < minimum_rows:\n',
    '        blocking.append(f"Only {len(frame)} clean rows; at least {minimum_rows} required")\n',
    '    price_positive = (frame[["open", "high", "low", "close"]] > 0).all(axis=1) if not frame.empty else pd.Series(dtype=bool)\n',
    '    invalid_positive = int((~price_positive).sum()) if len(price_positive) else 0\n',
    '    invalid_high = int((frame["high"] < frame[["open", "close", "low"]].max(axis=1)).sum()) if not frame.empty else 0\n',
    '    invalid_low = int((frame["low"] > frame[["open", "close", "high"]].min(axis=1)).sum()) if not frame.empty else 0\n',
    '    if invalid_positive: blocking.append(f"Non-positive prices: {invalid_positive}")\n',
    '    if invalid_high: blocking.append(f"High below OHLC relationship: {invalid_high}")\n',
    '    if invalid_low: blocking.append(f"Low above OHLC relationship: {invalid_low}")\n',
    '\n',
    '    tf_hours = _timeframe_hours(timeframe)\n',
    '    if tf_hours is None:\n',
    '        blocking.append(f"Unsupported timeframe: {timeframe or \'empty\'}")\n',
    '    elif len(frame) >= 3:\n',
    '        spacing = frame["time"].diff().dropna().dt.total_seconds() / 3600.0\n',
    '        median_spacing = float(spacing.median()) if not spacing.empty else tf_hours\n',
    '        unreasonable = float((abs(spacing - tf_hours) > max(tf_hours * 0.35, 0.15)).mean() * 100) if not spacing.empty else 0.0\n',
    '        if unreasonable > 35:\n',
    '            warnings.append(f"Irregular {timeframe} spacing: {unreasonable:.1f}% of gaps")\n',
    '            disabled.append("spacing-sensitive models")\n',
    '        if median_spacing <= 0:\n',
    '            blocking.append("Timestamp spacing is non-positive")\n',
    '\n',
    '    now_ts = pd.Timestamp(now or datetime.now(timezone.utc))\n',
    '    if now_ts.tzinfo is None: now_ts = now_ts.tz_localize("UTC")\n',
    '    else: now_ts = now_ts.tz_convert("UTC")\n',
    '    future_mask = frame["time"] > now_ts + pd.Timedelta(minutes=5) if not frame.empty else pd.Series(False, index=frame.index)\n',
    '    future_rows = int(future_mask.sum()) if not frame.empty else 0\n',
    '    if future_rows:\n',
    '        # Broker/API feeds may include forming candles or rows whose timestamp is\n',
    '        # ahead because of source timezone handling.  These rows are never used\n',
    '        # by the completed-H1 calculation.  Excluding them is a successful safety\n',
    '        # action, not a model failure, provided valid completed rows remain.\n',
    '        warnings.append(\n',
    '            f"Future timestamps detected and safely excluded from completed-H1 calculations: {future_rows}"\n',
    '        )\n',
    '        frame = frame.loc[~future_mask].copy()\n',
    '    latest_completed = False\n',
    '    if not frame.empty and tf_hours:\n',
    '        latest = frame["time"].iloc[-1]\n',
    '        completion = latest + pd.Timedelta(hours=tf_hours)\n',
    '        latest_completed = bool(completion <= now_ts + pd.Timedelta(minutes=3))\n',
    '        if not latest_completed:\n',
    '            warnings.append("Latest candle appears incomplete and was excluded from historical calculations")\n',
    '            frame = frame.iloc[:-1].copy()\n',
    '        if not frame.empty:\n',
    '            age_hours = (now_ts - frame["time"].iloc[-1]).total_seconds() / 3600.0\n',
    '            if age_hours > max(tf_hours * 4, 6):\n',
    '                warnings.append(f"Latest completed candle is stale by {age_hours:.1f} hours")\n',
    '    if frame.empty:\n',
    '        blocking.append("No completed clean candles remain")\n',
    '\n',
    '    source_ok = bool(str(source or "").strip())\n',
    '    symbol_ok = bool(str(symbol or "").strip())\n',
    '    timeframe_ok = bool(tf_hours)\n',
    '    if not source_ok: warnings.append("Source identity is missing")\n',
    '    if not symbol_ok: blocking.append("Symbol identity is missing")\n',
    '\n',
    '    severe = any(x for x in blocking if any(k in x.lower() for k in ("missing required", "no completed", "symbol identity")))\n',
    '    if severe:\n',
    '        status = "FAIL_ALL"\n',
    '    elif blocking:\n',
    '        status = "FAIL_MODEL"\n',
    '    elif warnings:\n',
    '        status = "PASS_WITH_WARNING"\n',
    '    else:\n',
    '        status = "PASS"\n',
    '    penalty = len(warnings) * 5 + len(blocking) * 18 + min(25.0, missing_pct * 3)\n',
    '    score = max(0.0, min(100.0, 100.0 - penalty))\n',
    '    return DataQualityResult(\n',
    '        status=status, score=score, blocking_reasons=blocking, warnings=warnings,\n',
    '        model_disabled=sorted(set(disabled)), latest_candle_completed=latest_completed,\n',
    '        normalized_timezone="UTC", missing_row_pct=round(missing_pct, 4),\n',
    '        source_identity_ok=source_ok, symbol_identity_ok=symbol_ok,\n',
    '        timeframe_identity_ok=timeframe_ok,\n',
    '    ), frame.reset_index(drop=True)\n',
    '\n',
    '\n',
    'def data_signature(frame: pd.DataFrame, *, symbol: str, timeframe: str, source: str) -> str:\n',
    '    latest = _utc_iso(frame["time"].iloc[-1]) if isinstance(frame, pd.DataFrame) and not frame.empty and "time" in frame else "empty"\n',
    '    rows = len(frame) if isinstance(frame, pd.DataFrame) else 0\n',
    '    payload = f"{symbol}|{timeframe}|{source}|{latest}|{rows}"\n',
    '    if isinstance(frame, pd.DataFrame) and not frame.empty:\n',
    '        try:\n',
    '            payload += "|" + frame.tail(5)[["open", "high", "low", "close"]].round(10).to_json()\n',
    '        except Exception:\n',
    '            pass\n',
    '    return hashlib.sha256(payload.encode("utf-8", errors="ignore")).hexdigest()[:24]\n',
    '\n',
    '\n',
    'def _session_label(ts: pd.Timestamp) -> str:\n',
    '    hour = int(ts.hour)\n',
    '    if 0 <= hour < 7: return "ASIA"\n',
    '    if 7 <= hour < 12: return "LONDON"\n',
    '    if 12 <= hour < 16: return "LONDON_NY_OVERLAP"\n',
    '    if 16 <= hour < 21: return "NEW_YORK"\n',
    '    return "LATE"\n',
    '\n',
    '\n',
    'def _extract_legacy(legacy: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    shared = dict(legacy or {})\n',
    '    current = dict(shared.get("current") or {})\n',
    '    market = dict(shared.get("market") or {})\n',
    '    decision = dict(shared.get("decision") or {})\n',
    '    regime = dict(shared.get("regime") or {})\n',
    '    reliability = dict(shared.get("reliability") or shared.get("reliability_calibration") or {})\n',
    '    powerbi = dict(shared.get("powerbi") or {})\n',
    '    priority = dict(shared.get("priority") or {})\n',
    '    nlp = dict(shared.get("nlp") or {})\n',
    '    alpha_delta = dict(shared.get("regime_alpha_delta") or regime.get("alpha_delta") or {})\n',
    '    return {\n',
    '        "current": current, "market": market, "decision": decision, "regime": regime,\n',
    '        "reliability": reliability, "powerbi": powerbi, "priority": priority,\n',
    '        "nlp": nlp, "alpha_delta": alpha_delta,\n',
    '    }\n',
    '\n',
    '\n',
    'def _direction(text: Any) -> str:\n',
    '    s = str(text or "").upper()\n',
    '    if "BUY" in s or "BULL" in s or "UP" in s: return "BUY"\n',
    '    if "SELL" in s or "BEAR" in s or "DOWN" in s: return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _extract_priority(parts: Dict[str, Any]) -> PriorityResult:\n',
    '    priority = parts["priority"]\n',
    '    best = dict(priority.get("best") or {}) if isinstance(priority, dict) else {}\n',
    '    current = parts["current"]\n',
    '    knn = _finite(best.get("KNN Score") or best.get("knn_score") or current.get("knn_score"), None)\n',
    '    greedy = _finite(best.get("Greedy Score") or best.get("greedy_score") or current.get("greedy_score"), None)\n',
    '    score = _finite(best.get("Priority Score") or best.get("score") or current.get("priority_score"), None)\n',
    '    if score is None:\n',
    '        values = [v for v in (knn, greedy, _finite(parts["reliability"].get("score"), None)) if v is not None]\n',
    '        score = float(np.mean(values)) if values else 0.0\n',
    '    score = max(0.0, min(100.0, score))\n',
    '    label = "A+" if score >= 88 else "A" if score >= 76 else "B" if score >= 62 else "C" if score >= 45 else "AVOID"\n',
    '    rank = int(best.get("Priority Rank") or best.get("rank") or 0) or None\n',
    '    return PriorityResult(score=score, label=label, rank=rank, knn_score=knn, greedy_score=greedy)\n',
    '\n',
    '\n',
    'def _extract_nlp(parts: Dict[str, Any]) -> NLPResult:\n',
    '    nlp = parts["nlp"]\n',
    '    summary = dict(nlp.get("summary") or {}) if isinstance(nlp, dict) else {}\n',
    '    available = bool(summary or nlp.get("articles")) if isinstance(nlp, dict) else False\n',
    '    try:\n',
    '        from core.finnhub_connector import connection_status\n',
    '        fh = connection_status()\n',
    '        finnhub_available = bool(fh.get("connected"))\n',
    '    except Exception:\n',
    '        finnhub_available = False\n',
    '    direction = _direction(summary.get("nlp_direction") or summary.get("direction"))\n',
    '    conflict = str(summary.get("conflict_level") or summary.get("nlp_conflict_level") or "NONE").upper()\n',
    '    reliability = _finite(summary.get("reliability") or summary.get("nlp_reliability_score"), 0.0) or 0.0\n',
    '    if reliability > 1: reliability /= 100.0\n',
    '    importance = _finite(summary.get("importance") or summary.get("importance_score"), 0.0) or 0.0\n',
    '    if importance > 1: importance /= 100.0\n',
    '    return NLPResult(\n',
    '        available=available, finnhub_available=finnhub_available, direction=direction,\n',
    '        conflict_level=conflict, importance=_clip(importance), reliability=_clip(reliability),\n',
    '        latest_headline=str(summary.get("latest_rank_1_news") or summary.get("headline") or "No relevant news")[:300],\n',
    '        latest_time=_utc_iso(summary.get("news_time") or summary.get("timestamp")),\n',
    '        event_response_sample_count=int(_finite(summary.get("event_response_sample_count"), 0) or 0),\n',
    '        modifier=0.0,\n',
    '    )\n',
    '\n',
    '\n',
    'def _regime_runs(regime_history: Any, major: str, frame: pd.DataFrame) -> Tuple[List[float], float]:\n',
    '    durations: List[float] = []\n',
    '    age = 0.0\n',
    '    if isinstance(regime_history, pd.DataFrame) and not regime_history.empty:\n',
    '        hist = regime_history.copy()\n',
    '        cmap = {str(c).lower().strip(): c for c in hist.columns}\n',
    '        rcol = next((c for k, c in cmap.items() if "regime" in k), None)\n',
    '        scol = next((c for k, c in cmap.items() if "start" in k or "change time" in k), None)\n',
    '        ecol = next((c for k, c in cmap.items() if "end" in k), None)\n',
    '        if rcol and scol:\n',
    '            hist[scol] = pd.to_datetime(hist[scol], utc=True, errors="coerce")\n',
    '            if ecol: hist[ecol] = pd.to_datetime(hist[ecol], utc=True, errors="coerce")\n',
    '            hist = hist.dropna(subset=[scol]).sort_values(scol)\n',
    '            now = frame["time"].iloc[-1] if not frame.empty else pd.Timestamp.now(tz="UTC")\n',
    '            for idx, row in hist.iterrows():\n',
    '                start = row[scol]\n',
    '                end = row[ecol] if ecol and not pd.isna(row.get(ecol)) else now\n',
    '                hours = max(0.0, (end - start).total_seconds() / 3600.0)\n',
    '                if hours > 0: durations.append(hours)\n',
    '            current_rows = hist[hist[rcol].astype(str).str.upper() == str(major).upper()]\n',
    '            if not current_rows.empty:\n',
    '                start = current_rows.iloc[-1][scol]\n',
    '                age = max(0.0, (now - start).total_seconds() / 3600.0)\n',
    '    if age == 0 and not frame.empty:\n',
    '        age = min(24.0, float(len(frame)))\n',
    '    return durations, age\n',
    '\n',
    '\n',
    'def build_regime_result(parts: Dict[str, Any], frame: pd.DataFrame) -> RegimeResult:\n',
    '    reg = parts["regime"]\n',
    '    current = parts["current"]\n',
    '    ad = parts["alpha_delta"]\n',
    '    major = str(reg.get("current") or current.get("regime") or current.get("current_regime") or "UNKNOWN")\n',
    '    history = reg.get("history")\n',
    '    durations, age = _regime_runs(history, major, frame)\n',
    '    expected = float(np.median(durations)) if durations else None\n',
    '    p25 = float(np.percentile(durations, 25)) if len(durations) >= 4 else None\n',
    '    p75 = float(np.percentile(durations, 75)) if len(durations) >= 4 else None\n',
    '    remaining = max(0.0, expected - age) if expected is not None else None\n',
    '    score = _finite(current.get("regime_score") or reg.get("score"), 0.0) or 0.0\n',
    '    if score <= 10: score *= 10\n',
    '    confidence = _finite(parts["reliability"].get("score") or current.get("regime_confidence"), 0.0) or 0.0\n',
    '    if confidence > 1: confidence /= 100.0\n',
    '    alpha = _finite(ad.get("regime_alpha") or ad.get("alpha") or current.get("alpha"), None)\n',
    '    delta = _finite(ad.get("regime_delta") or ad.get("delta") or current.get("delta"), None)\n',
    '    previous_delta = _finite(ad.get("previous_delta") or ad.get("delta_previous"), None)\n',
    '    acceleration = (delta - previous_delta) if delta is not None and previous_delta is not None else _finite(ad.get("delta_acceleration"), None)\n',
    '    direction = _direction(major)\n',
    '    persistence = 0.5\n',
    '    if durations and expected:\n',
    '        persistence = _clip(age / max(expected, 1.0), 0, 1, 0.5)\n',
    '    base_transition = 0.12\n',
    '    if p75 and age > p75: base_transition += 0.28\n',
    '    elif expected and age > expected: base_transition += 0.18\n',
    '    if delta is not None and alpha is not None and alpha * delta < 0: base_transition += 0.16\n',
    '    if confidence < 0.45: base_transition += 0.10\n',
    '    t1 = _clip(base_transition, 0.02, 0.85, 0.15)\n',
    '    t3 = _clip(1 - (1 - t1) ** 3, 0.03, 0.94, 0.3)\n',
    '    t6 = _clip(1 - (1 - t1) ** 6, 0.05, 0.98, 0.5)\n',
    '    next_probs = {"RANGE/TRANSITION": round(t3, 4)}\n',
    '    if direction == "BUY": next_probs["BEARISH"] = round(t3 * 0.55, 4); next_probs["BULLISH"] = round(1 - t3, 4)\n',
    '    elif direction == "SELL": next_probs["BULLISH"] = round(t3 * 0.55, 4); next_probs["BEARISH"] = round(1 - t3, 4)\n',
    '    else: next_probs.update({"BULLISH": round((1-t3)/2,4), "BEARISH": round((1-t3)/2,4)})\n',
    '    warning = "HIGH" if t3 >= 0.65 else "WATCH" if t3 >= 0.4 else "NONE"\n',
    '    # Preserve existing major regime across lower/middle/higher when no explicit standards are present.\n',
    '    lower = str(reg.get("lower_standard_regime") or current.get("lower_standard_regime") or major)\n',
    '    middle = str(reg.get("middle_standard_regime") or current.get("middle_standard_regime") or major)\n',
    '    higher = str(reg.get("higher_standard_regime") or current.get("higher_standard_regime") or major)\n',
    '    disagreement = len({_direction(lower), _direction(middle), _direction(higher)} - {"WAIT"}) > 1\n',
    '    if disagreement:\n',
    '        confidence *= 0.8\n',
    '    return RegimeResult(\n',
    '        major_regime=major, lower_standard_regime=lower, middle_standard_regime=middle,\n',
    '        higher_standard_regime=higher, regime_score=max(0,min(100,score)), confidence=_clip(confidence),\n',
    '        reliability=_clip(confidence), age_hours=round(age,3), expected_duration_hours=expected,\n',
    '        duration_p25_hours=p25, duration_p75_hours=p75, remaining_duration_hours=remaining,\n',
    '        alpha=alpha, delta=delta, delta_acceleration=acceleration, persistence_score=persistence,\n',
    '        transition_probability_1h=t1, transition_probability_3h=t3, transition_probability_6h=t6,\n',
    '        possible_next_regimes=next_probs, transition_warning=warning,\n',
    '        conflict_warning="MULTI_STANDARD_DISAGREEMENT" if disagreement else "NONE",\n',
    '    )\n',
    '\n',
    '\n',
    'def _prediction_frame(parts: Dict[str, Any]) -> pd.DataFrame:\n',
    '    candidate = parts["powerbi"].get("projected_path") if isinstance(parts["powerbi"], dict) else None\n',
    '    if isinstance(candidate, pd.DataFrame): return candidate.copy()\n',
    '    if isinstance(candidate, list): return pd.DataFrame(candidate)\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _point_forecasts(parts: Dict[str, Any], frame: pd.DataFrame) -> Dict[int, Optional[float]]:\n',
    '    current = float(frame["close"].iloc[-1]) if not frame.empty else _finite(parts["current"].get("last_close"), None)\n',
    '    pred = _prediction_frame(parts)\n',
    '    points: Dict[int, Optional[float]] = {h: None for h in HORIZONS}\n',
    '    if not pred.empty:\n',
    '        cmap = {str(c).lower(): c for c in pred.columns}\n',
    '        ccol = next((c for k,c in cmap.items() if "close" in k or "forecast" in k or "predicted price" in k), None)\n',
    '        if ccol:\n',
    '            values = pd.to_numeric(pred[ccol], errors="coerce").dropna().tolist()\n',
    '            for h in HORIZONS:\n',
    '                if len(values) >= h: points[h] = float(values[h-1])\n',
    '    final = _finite(parts["powerbi"].get("forecast_close") or parts["current"].get("forecast_close"), None)\n',
    '    if current is not None and final is not None:\n',
    '        for h in HORIZONS:\n',
    '            if points[h] is None:\n',
    '                points[h] = current + (final - current) * (h / max(HORIZONS))\n',
    '    return points\n',
]
