"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = ['"""One-click Settings calculation orchestrator.\n',
 '\n',
 "This module does not add a prediction model. It calls the project's existing\n",
 'Lunch, PowerBI, regime, NLP and shared-sync functions once, stores their normal\n',
 'caches, and then lets the Lunch page render those caches without another Run or\n',
 'Load button.\n',
 '"""\n',
 'from __future__ import annotations\n',
 '\n',
 'import time\n',
 'from typing import Any, Dict, Mapping\n',
 '\n',
 'import pandas as pd\n',
 'import streamlit as st\n',
 '\n',
 '\n',
 'REGIME_NLP_HISTORY_DAYS = 25\n',
 '\n',
 '\n',
 'def _call(ns: Dict[str, Any], name: str, *args: Any, **kwargs: Any) -> Any:\n',
 '    fn = ns.get(name)\n',
 '    if not callable(fn):\n',
 '        raise RuntimeError(f"Existing function {name} is unavailable")\n',
 '    return fn(*args, **kwargs)\n',
 '\n',
 '\n',
 'def _build_lunch_metric(ns: Dict[str, Any]) -> Dict[str, Any]:\n',
 '    result = _call(ns, "_get_cached_lunch_metric_result", True)\n',
 '    if not isinstance(result, dict):\n',
 '        return {"ok": False, "message": "Lunch metric returned an unsupported result."}\n',
 '    if result.get("ok"):\n',
 '        st.session_state["lunch_show_full_metric_details"] = True\n',
 '        try:\n',
 '            _call(ns, "_get_cached_lunch_copy_payload", True)\n',
 '        except Exception:\n',
 '            pass\n',
 '        try:\n',
 '            scan = _call(ns, "_load_reversal_scan")\n',
 '            if isinstance(scan, pd.DataFrame) and not scan.empty:\n',
 '                st.session_state["home_reversal_25d_scan"] = scan\n',
 '        except Exception:\n',
 '            pass\n',
 '    return result\n',
 '\n',
 '\n',
 'def _build_powerbi(ns: Dict[str, Any], validated_df: pd.DataFrame | None = None) -> Dict[str, Any]:\n',
 '    rows_limit = int(st.session_state.get("dv_pp_rows", 10000) or 10000)\n',
 '    horizon = int(st.session_state.get("dv_pp_horizon", 36) or 36)\n',
 '    min_days = int(st.session_state.get("dv_pp_min_days", 5) or 5)\n',
 '    bt_lookback = int(st.session_state.get("dv_pp_bt", 180) or 180)\n',
 '\n',
 '    raw = validated_df if isinstance(validated_df, pd.DataFrame) and not validated_df.empty else _call(ns, '
 '"_clean_lunch_visual_df", limit=rows_limit)\n',
 '    data = _call(ns, "_dv_prepare_ohlc_v20260609", raw, limit=rows_limit)\n',
 '    if not isinstance(data, pd.DataFrame) or data.empty or len(data) < 120:\n',
 '        return {\n',
 '            "ok": False,\n',
 '            "message": "PowerBI needs at least 120 clean OHLC rows.",\n',
 '            "rows": int(len(data)) if isinstance(data, pd.DataFrame) else 0,\n',
 '        }\n',
 '\n',
 '    base_result = _call(ns, "_five_layer_powerbi_calculate", data, horizon=horizon)\n',
 '    predicted = _call(ns, "_dv_predict_future_candles_v20260609", data, horizon=horizon)\n',
 '    bt_hist, bt_summary = _call(ns, "_dv_prediction_vs_actual_history_v20260609", data, lookback=bt_lookback, '
 'horizon=1)\n',
 '\n',
 '    # Deterministic accuracy/reliability post-calibration. The original model\n',
 '    # outputs are preserved; this adds a shared main path and empirical bands\n',
 '    # based on completed prediction-vs-actual error and path agreement.\n',
 '    yellow_current = pd.DataFrame()\n',
 '    blue_previous = pd.DataFrame()\n',
 '    yellow_builder = ns.get("_build_last_candle_yellow_6h_projection_v5")\n',
 '    if callable(yellow_builder):\n',
 '        try:\n',
 '            yellow_current = yellow_builder(data, horizon=min(24, horizon), mode="Balanced", risk_filter="Medium")\n',
 '        except Exception:\n',
 '            yellow_current = pd.DataFrame()\n',
 '        try:\n',
 '            blue_previous = yellow_builder(data.iloc[:-1], horizon=min(24, horizon), mode="Balanced", '
 'risk_filter="Medium")\n',
 '        except Exception:\n',
 '            blue_previous = pd.DataFrame()\n',
 '    try:\n',
 '        from core.powerbi_path_calibration_20260617 import calibrate_projection_bundle, calibrated_candles\n',
 '        regime_reliability = None\n',
 '        regime_ctx = st.session_state.get("regime_context_20260614")\n',
 '        if isinstance(regime_ctx, dict):\n',
 '            metrics = regime_ctx.get("metrics", {}) if isinstance(regime_ctx.get("metrics"), dict) else {}\n',
 '            regime_reliability = metrics.get("Regime Reliable Score") or metrics.get("Regime Reliability")\n',
 '        regime_name = None\n',
 '        conflict_state = None\n',
 '        if isinstance(regime_ctx, dict):\n',
 '            summary_ctx = regime_ctx.get("summary") if isinstance(regime_ctx.get("summary"), dict) else {}\n',
 '            regime_name = regime_ctx.get("current_regime") or regime_ctx.get("Current Regime") or '
 'summary_ctx.get("Current Regime")\n',
 '            conflict_state = regime_ctx.get("conflict") or regime_ctx.get("transition_risk")\n',
 '        calibrated_bundle = calibrate_projection_bundle(\n',
 '            data,\n',
 '            red=predicted,\n',
 '            yellow=yellow_current,\n',
 '            blue=blue_previous,\n',
 '            horizon=horizon,\n',
 '            bt_history=bt_hist,\n',
 '            bt_summary=bt_summary,\n',
 '            regime_reliability=regime_reliability,\n',
 '            current_regime=regime_name,\n',
 '            transition_or_conflict=conflict_state,\n',
 '            source_data_timestamp=data["time"].iloc[-1] if "time" in data.columns else None,\n',
 '        )\n',
 '        # Additive combination upgrade only: existing red/yellow/blue paths and\n',
 '        # their raw outputs are preserved in the audit. Settled residual MSE,\n',
 '        # Wiener gain and lagged residual correlation determine adaptive weights\n',
 '        # before any visual step limiting is applied.\n',
 '        try:\n',
 '            from core.powerbi_mmse_weighting_20260618 import upgrade_projection_bundle\n',
 '            support_cache = st.session_state.get("causal_quant_support_20260618")\n',
 '            support_cache = support_cache if isinstance(support_cache, dict) else {}\n',
 '            calibrated_bundle = upgrade_projection_bundle(\n',
 '                calibrated_bundle,\n',
 '                market_data=data,\n',
 '                regime_conditioned_distributions=support_cache.get("regime_conditioned_distributions"),\n',
 '                transition_state=(support_cache.get("transition_risk") or {}).get("status", conflict_state),\n',
 '            )\n',
 '        except Exception as exc:\n',
 '            calibrated_bundle.setdefault("audit", {})["mmse_weighting_error"] = str(exc)[:240]\n',
 '        calibrated_prediction = calibrated_candles(\n',
 '            calibrated_bundle,\n',
 '            anchor_price=float(data["close"].iloc[-1]),\n',
 '        )\n',
 '    except Exception as exc:\n',
 '        calibrated_bundle = {"ok": False, "message": str(exc)}\n',
 '        calibrated_prediction = pd.DataFrame()\n',
 '\n',
 '    projection_history = _call(\n',
 '        ns,\n',
 '        "_dv_dynamic_projection_history_v20260609",\n',
 '        data,\n',
 '        lookback_days=10,\n',
 '        horizon=min(6, horizon),\n',
 '    )\n',
 '    regime_summary, regime_hist = _call(\n',
 '        ns,\n',
 '        "_dv_major_regime_detector_v20260609",\n',
 '        data,\n',
 '        min_days=float(min_days),\n',
 '        lookback_days=240,\n',
 '        horizon=horizon,\n',
 '    )\n',
 '    recent = _call(ns, "_dv_last_continuous_days_v20260609", data, days=10)\n',
 '    lightblue = _call(ns, "_dv_build_lightblue_path_v20260609", recent, predicted)\n',
 '    sorter = ns.get("_dv_sort_newest_first_v20260609")\n',
 '    if callable(sorter):\n',
 '        bt_hist = sorter(bt_hist)\n',
 '        regime_hist = sorter(regime_hist)\n',
 '\n',
 '    signature_fn = ns.get("_lunch_df_signature")\n',
 '    data_signature = signature_fn() if callable(signature_fn) else (len(data), str(data.iloc[-1].get("time", "")))\n',
 '    signature = (data_signature, rows_limit, horizon, min_days, bt_lookback, "settings_auto_powerbi_20260617")\n',
 '\n',
 '    st.session_state.update({\n',
 '        "lunch_bi_visual_ready": True,\n',
 '        "dv_pp_df": data,\n',
 '        "dv_pp_base_result": base_result,\n',
 '        "dv_pp_predicted": predicted,\n',
 '        "dv_pp_predicted_calibrated_20260617": calibrated_prediction,\n',
 '        "powerbi_calibrated_bundle_20260617": calibrated_bundle,\n',
 '        "powerbi_path_audit_20260618": calibrated_bundle.get("audit", {}) if isinstance(calibrated_bundle, dict) '
 'else {},\n',
 '        "dv_pp_lightblue_path": lightblue,\n',
 '        "dv_pp_projection_history": projection_history,\n',
 '        "dv_pp_bt_hist": bt_hist,\n',
 '        "dv_pp_bt_summary": bt_summary,\n',
 '        "dv_pp_regime_summary": regime_summary,\n',
 '        "dv_pp_regime_hist": regime_hist,\n',
 '        "dv_pp_sig": signature,\n',
 '        "show_restored_powerbi_20260617": True,\n',
 '        "load_original_powerbi_from_antd_lunch_20260615": True,\n',
 '    })\n',
 '    return {\n',
 '        "ok": True,\n',
 '        "rows": int(len(data)),\n',
 '        "predicted_rows": int(len(predicted)) if isinstance(predicted, pd.DataFrame) else 0,\n',
 '        "calibrated_rows": int(len(calibrated_prediction)) if isinstance(calibrated_prediction, pd.DataFrame) else '
 '0,\n',
 '        "path_reliability_pct": ((calibrated_bundle.get("summary") or {}).get("reliability_pct") if '
 'isinstance(calibrated_bundle, dict) else None),\n',
 '        "backtest_rows": int(len(bt_hist)) if isinstance(bt_hist, pd.DataFrame) else 0,\n',
 '    }\n',
 '\n',
 '\n',
 'def _source_identity() -> tuple[str, str, str]:\n',
 '    # Operational decisions keep completed-H1 authority while the selected\n',
 '    # instrument is read from the single global symbol state.\n',
 '    from core.symbol_universe_20260629 import normalize_instrument\n',
 '    symbol = normalize_instrument(st.session_state.get("symbol") or "EURUSD")\n',
 '    source = str(st.session_state.get("data_source") or st.session_state.get("selected_source") or '
 'st.session_state.get("source") or "SESSION")\n',
 '    return symbol, "H1", source\n',
 '\n',
 '\n',
 'def _preflight_dataframe(ns: Dict[str, Any]) -> pd.DataFrame:\n',
 '    """Select the newest valid timestamped OHLC source for the Settings run.\n',
 '\n',
 '    A newly refreshed connector dataframe must outrank an older derived display\n',
 '    cache.  Schema quality and identity still matter, but a candidate that is\n',
 '    materially behind the freshest valid source receives a hard stale penalty.\n',
 '    """\n',
 '    candidates: list[tuple[str, pd.DataFrame]] = []\n',
 '    for name, args in (("_clean_lunch_visual_df", (10000,)), ("_prepare_lunch_df", ()), ("_get_lunch_df", ())):\n',
 '        fn = ns.get(name)\n',
 '        if callable(fn):\n',
 '            try:\n',
 '                value = fn(*args) if args else fn()\n',
 '            except TypeError:\n',
 '                try:\n',
 '                    value = fn(limit=10000)\n',
 '                except Exception:\n',
 '                    value = None\n',
 '            except Exception:\n',
 '                value = None\n',
 '            if isinstance(value, pd.DataFrame) and not value.empty:\n',
 '                candidates.append((name, value))\n',
 '    for key in ("last_df", "dv_pp_df", "lunch_5layer_powerbi_df", "ohlc_df", "df"):\n',
 '        value = st.session_state.get(key)\n',
 '        if isinstance(value, pd.DataFrame) and not value.empty:\n',
 '            candidates.append((key, value))\n',
 '\n',
 '    preference = {\n',
 '        "last_df": 55, "_clean_lunch_visual_df": 42, "dv_pp_df": 36,\n',
 '        "lunch_5layer_powerbi_df": 34, "_prepare_lunch_df": 28,\n',
 '        "ohlc_df": 22, "df": 18, "_get_lunch_df": 16,\n',
 '    }\n',
 '    prepared: list[tuple[str, pd.DataFrame, pd.Series, pd.Timestamp, dict[str, Any], int, int]] = []\n',
 '    for name, raw in candidates:\n',
 '        lower = {str(c).strip().lower(): c for c in raw.columns}\n',
 '        time_col = next((lower[k] for k in ("time", "datetime", "timestamp", "date_time", "date") if k in lower), '
 'None)\n',
 '        close_col = next((lower[k] for k in ("close", "c") if k in lower), None)\n',
 '        if time_col is None or close_col is None:\n',
 '            continue\n',
 '        parsed = pd.to_datetime(raw[time_col], errors="coerce", utc=True)\n',
 '        valid_count = int(parsed.notna().sum())\n',
 '        latest = parsed.max()\n',
 '        if valid_count < 30 or pd.isna(latest):\n',
 '            continue\n',
 '        ohlc_count = sum(1 for key in ("open", "high", "low", "close") if key in lower)\n',
 '        prepared.append((name, raw, parsed, pd.Timestamp(latest), lower, valid_count, ohlc_count))\n',
 '\n',
 '    if not prepared:\n',
 '        st.session_state["selected_ohlc_source_key_20260617"] = "NONE"\n',
 '        return pd.DataFrame()\n',
 '\n',
 '    freshest_latest = max(item[3] for item in prepared)\n',
 '    tf = str(st.session_state.get("timeframe") or "H1").upper()\n',
 '    interval_seconds = {\n',
 '        "M1": 60, "M2": 120, "M3": 180, "M4": 240, "M5": 300,\n',
 '        "M10": 600, "M15": 900, "M30": 1800, "H1": 3600,\n',
 '        "H4": 14400, "D1": 86400, "CUSTOM": 3600,\n',
 '    }.get(tf, 3600)\n',
 '    fresh_fetch = time.time() - float(st.session_state.get("last_fetch", 0.0) or 0.0) <= 180.0\n',
 '    active_identity = dict(zip(("symbol", "timeframe", "source"), _source_identity()))\n',
 '    previous = st.session_state.get("canonical_decision_result_20260617") or {}\n',
 '    best = pd.DataFrame()\n',
 '    best_score = float("-inf")\n',
 '    diagnostics: list[dict[str, Any]] = []\n',
 '\n',
 '    for name, frame, parsed, latest, lower, valid_count, ohlc_count in prepared:\n',
 '        lag_seconds = max(0.0, float((freshest_latest - latest).total_seconds()))\n',
 '        lag_intervals = lag_seconds / max(1, interval_seconds)\n',
 '        duplicate_penalty = float(parsed.duplicated().mean() * 40.0)\n',
 '        score = float(preference.get(name, 0)) + min(valid_count, 10000) / 250.0 + ohlc_count * 4.0 - '
 'duplicate_penalty\n',
 '        # Freshness dominates display-cache preference. Equal-time derived data\n',
 '        # can still win on schema, while a stale cache cannot beat last_df.\n',
 '        score += max(0.0, 70.0 - lag_intervals * 35.0)\n',
 '        if lag_intervals > 1.5:\n',
 '            score -= 220.0 + min(180.0, lag_intervals * 12.0)\n',
 '        if name == "last_df" and fresh_fetch:\n',
 '            score += 85.0\n',
 '\n',
 '        attrs = getattr(frame, "attrs", {}) or {}\n',
 '        identity_mismatch = False\n',
 '        for field in ("symbol", "timeframe", "source"):\n',
 '            declared = attrs.get(field)\n',
 '            active = active_identity.get(field)\n',
 '            if declared and active:\n',
 '                if str(declared).upper() != str(active).upper():\n',
 '                    identity_mismatch = True\n',
 '                    break\n',
 '                score += 8.0\n',
 '        if identity_mismatch:\n',
 '            diagnostics.append({"source": name, "latest": latest.isoformat(), "score": None, "rejected": "identity '
 'mismatch"})\n',
 '            continue\n',
 '        declared_run = attrs.get("run_id")\n',
 '        declared_signature = attrs.get("data_signature")\n',
 '        if declared_run and previous.get("run_id"):\n',
 '            score += 6.0 if str(declared_run) == str(previous.get("run_id")) else -18.0\n',
 '        if declared_signature and previous.get("data_signature"):\n',
 '            score += 6.0 if str(declared_signature) == str(previous.get("data_signature")) else -12.0\n',
 '        diagnostics.append({\n',
 '            "source": name, "latest": latest.isoformat(), "lag_intervals": round(lag_intervals, 3),\n',
 '            "score": round(score, 3), "rows": int(len(frame)),\n',
 '        })\n',
 '        if score > best_score:\n',
 '            best = frame\n',
 '            best_score = score\n',
 '            st.session_state["selected_ohlc_source_key_20260617"] = name\n',
 '            st.session_state["selected_ohlc_latest_time_20260617"] = latest.isoformat()\n',
 '\n',
 '    st.session_state["ohlc_source_selection_diagnostics_20260622"] = diagnostics\n',
 '    st.session_state["freshest_available_ohlc_time_20260622"] = freshest_latest.isoformat()\n',
 '    return best\n',
 '\n',
 '\n',
 'def run_settings_calculation(ns: Dict[str, Any]) -> Dict[str, Any]:\n',
 '    """Build all existing caches once, then atomically publish one canonical result."""\n',
 '    started = time.time()\n',
 '    run_started_at = pd.Timestamp.now(tz="UTC").isoformat()\n',
 '    perf_started = time.perf_counter()\n',
 '    try:\n',
 '        import psutil\n',
 '        _process = psutil.Process()\n',
 '        rss_before = int(_process.memory_info().rss)\n',
 '    except Exception:\n',
 '        _process = None\n',
 '        rss_before = 0\n',
 '    lock_key = "settings_calculation_lock_20260617"\n',
 '    lock_time_key = "settings_calculation_lock_time_20260617"\n',
 '    now = time.time()\n',
 '    if st.session_state.get(lock_key) and now - float(st.session_state.get(lock_time_key, 0) or 0) < 300:\n',
 '        return {\n',
 '            "ok": False, "duplicate_blocked": True,\n',
 '            "errors": ["A calculation is already running; duplicate execution was blocked."],\n',
 '            "built_at": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"),\n',
 '        }\n',
 '    st.session_state[lock_key] = True\n',
 '    st.session_state[lock_time_key] = now\n',
 '\n',
 '    symbol, timeframe, source = _source_identity()\n',
 '    status: Dict[str, Any] = {\n',
 '        "ok": True, "metric": {}, "powerbi": {}, "data_quality": {}, "ledger": {},\n',
 '        "canonical": {}, "calibration": {}, "drift": {}, "errors": [],\n',
 '    }\n',
 '    requested_scope = str(st.session_state.get("settings_calculation_scope_20260625") or "FULL").upper()\n',
 '    # Only the dedicated Super Quick button is limited to protected Lunch\n',
 '    # Fields 1-3. QUICK still runs protected Fields 1-9 + AI and skips only\n',
 '    # the additive thesis/shadow publishers in the outer wrapper.\n',
 '    quick_scope = requested_scope == "LUNCH_CORE"\n',
 '    status["calculation_scope"] = "QUICK_FIELDS_1_2_3" if quick_scope else ("QUICK_FIELDS_1_TO_9_PLUS_AI" if requested_scope == "QUICK" else "FULL_FIELDS_1_TO_9_PLUS_AI")\n',
 '    status["quick_scope_contract"] = {\n',
 '        "fields": [1, 2, 3] if quick_scope else list(range(1, 10)),\n',
 '        "protected_core_logic_unchanged": True,\n',
 '        "optional_field4_9_research_skipped": bool(quick_scope),\n',
 '    }\n',
 '    nlp_result: Dict[str, Any] = {}\n',
 '    research_pack: Dict[str, Any] = {}\n',
 '    detail_tables: Dict[str, Any] = {}\n',
 '    standards = pd.DataFrame()\n',
 '    trust_store = None\n',
 '    regime_trust_history_bundle: Dict[str, Any] = {}\n',
 '    try:\n',
 '        from core.operational_sync_20260618 import clear_operational_errors\n',
 '        clear_operational_errors(st.session_state)\n',
 '    except Exception:\n',
 '        pass\n',
 '    try:\n',
 '        from core.decision_product_engine_20260617 import validate_data_quality\n',
 '        from core.prediction_ledger_20260617 import get_prediction_ledger\n',
 '        ledger = get_prediction_ledger()\n',
 '        preflight = _preflight_dataframe(ns)\n',
 '        quality, clean_preflight = validate_data_quality(\n',
 '            preflight, symbol=symbol, timeframe=timeframe, source=source,\n',
 '        )\n',
 '        status["data_quality"] = {\n',
 '            "status": quality.status, "score": quality.score,\n',
 '            "warnings": quality.warnings, "blocking_reasons": quality.blocking_reasons,\n',
 '        }\n',
 '        # Additive declarative gate. It never repairs prices. A rejected source\n',
 '        # generation is recorded while the prior completed canonical pointer stays\n',
 '        # untouched.\n',
 '        from core.canonical_data_validation_20260621 import validate_source_frame\n',
 '        research_validation_preflight = validate_source_frame(\n',
 '            clean_preflight,\n',
 '            symbol=symbol,\n',
 '            timeframe=timeframe,\n',
 '            source=source,\n',
 '            source_row_count=len(preflight) if isinstance(preflight, pd.DataFrame) else None,\n',
 '        )\n',
 '        status["research_data_validation"] = {\n',
 '            "status": research_validation_preflight.status,\n',
 '            "generation_id": research_validation_preflight.generation_id,\n',
 '            "critical_failure_count": research_validation_preflight.critical_failure_count,\n',
 '            "warning_count": research_validation_preflight.warning_count,\n',
 '            "failed_constraints": research_validation_preflight.failed_constraints,\n',
 '        }\n',
 '        if not research_validation_preflight.publication_allowed:\n',
 '            from core.research_validation_store_20260621 import record_rejected_generation\n',
 '            previous_valid = st.session_state.get("canonical_decision_result")\n',
 '            previous_valid = previous_valid if isinstance(previous_valid, Mapping) else {}\n',
 '            status["research_validation_rejection"] = record_rejected_generation(\n',
 '                research_validation_preflight,\n',
 '                reason="Pre-calculation declarative data validation rejected the generation.",\n',
 '                previous_valid=previous_valid,\n',
 '            )\n',
 '            status["ok"] = False\n',
 '            status["errors"].append("Research validation gate rejected source data; previous canonical generation '
 'was preserved.")\n',
 '            st.session_state["research_validation_diagnostic_20260621"] = research_validation_preflight.as_dict()\n',
 '            return status\n',
 '        # Settlements use only completed candles and run before a new prediction is written.\n',
 '        status["outcome_settlement"] = ledger.settle_pending_outcomes(clean_preflight)\n',
 '        status["ledger"] = ledger.health()\n',
 '        try:\n',
 '            from core.trust_history_20260619 import get_trust_history_store\n',
 '            trust_store = get_trust_history_store()\n',
 '            status["trust_history_settlement"] = trust_store.settle_pending(clean_preflight)\n',
 '        except Exception as exc:\n',
 '            trust_store = None\n',
 '            status["trust_history_settlement"] = {"ok": False, "error": str(exc)}\n',
 '            status["errors"].append(f"Settled trust history: {exc}")\n',
 '\n',
 '        if quality.status == "FAIL_ALL":\n',
 '            failed_run_id = '
 'f"FAILED-{pd.Timestamp.utcnow().strftime(\'%Y%m%dT%H%M%S\')}-{int(time.time()*1000)%1000000:06d}"\n',
 '            ledger.record_failed_run({\n',
 '                "run_id": failed_run_id,\n',
 '                "created_at": pd.Timestamp.utcnow().isoformat(),\n']
