"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = ['                "symbol": symbol, "timeframe": timeframe, "source": source,\n',
 '                "data_signature": "preflight-failed", "model_version": "existing-models-v1",\n',
 '                "calculation_version": "decision-product-20260617-v1", "schema_version": "2.0.0",\n',
 '                "data_quality": {"status": quality.status}, "calculation_status": "FAILED",\n',
 '                "failure_reason": "; ".join(quality.blocking_reasons),\n',
 '                "market": {"latest_completed_candle_time": None},\n',
 '            })\n',
 '            status["ok"] = False\n',
 '            status["errors"].append("Data quality FAIL_ALL: " + "; ".join(quality.blocking_reasons))\n',
 '            st.session_state["canonical_decision_attempt_20260617"] = {\n',
 '                "run_id": failed_run_id, "calculation_status": "FAILED",\n',
 '                "failure_reason": "; ".join(quality.blocking_reasons),\n',
 '                "data_quality": status["data_quality"],\n',
 '            }\n',
 '            return status\n',
 '\n',
 '        # One private staging frame is the only OHLC input for this calculation.\n',
 '        # It is not published to legacy keys until the complete canonical run succeeds.\n',
 '        clean_preflight = clean_preflight.copy(deep=False)\n',
 '        clean_preflight.attrs.update({"symbol": symbol, "timeframe": timeframe, "source": source, '
 '"validation_status": quality.status})\n',
 '        periodicity_precomputed = {}\n',
 '        periodicity_frame_precomputed = pd.DataFrame()\n',
 '        try:\n',
 '            from core.research_risk_stack_20260619 import build_periodicity_normalization\n',
 '            settled_for_periodicity = trust_store.frame(status="SETTLED", limit=20000) if trust_store is not None '
 'else pd.DataFrame()\n',
 '            periodicity_precomputed, periodicity_frame_precomputed = build_periodicity_normalization(\n',
 '                clean_preflight, settled=settled_for_periodicity\n',
 '            )\n',
 '            if isinstance(periodicity_frame_precomputed, pd.DataFrame) and not '
 'periodicity_frame_precomputed.empty:\n',
 '                time_col = next((c for c in clean_preflight.columns if str(c).strip().lower() in {"time", '
 '"timestamp", "datetime", "date"}), None)\n',
 '                source_time = pd.to_datetime(clean_preflight[time_col] if time_col else clean_preflight.index, '
 'errors="coerce", utc=True)\n',
 '                normalised = periodicity_frame_precomputed.reindex(pd.DatetimeIndex(source_time))\n',
 '                for column in (\n',
 '                    "hour_of_week", "expected_hourly_volatility", "periodicity_normalized_return",\n',
 '                    "periodicity_normalized_range", "periodicity_normalized_atr",\n',
 '                    "periodicity_normalized_volume", "periodicity_normalized_residual",\n',
 '                    "periodicity_sample_count", "periodicity_reliability",\n',
 '                ):\n',
 '                    if column in normalised.columns:\n',
 '                        clean_preflight[column] = normalised[column].to_numpy()\n',
 '            status["periodicity_normalization"] = {\n',
 '                "ok": True,\n',
 '                "status": periodicity_precomputed.get("status"),\n',
 '                "causal_shift_applied": periodicity_precomputed.get("causal_shift_applied", False),\n',
 '                "sample_count": periodicity_precomputed.get("periodicity_sample_count", 0),\n',
 '            }\n',
 '        except Exception as exc:\n',
 '            periodicity_precomputed = {}\n',
 '            periodicity_frame_precomputed = pd.DataFrame()\n',
 '            status["periodicity_normalization"] = {"ok": False, "optional": True, "message": str(exc)}\n',
 '        st.session_state["calculation_staging_ohlc_df_20260617"] = clean_preflight\n',
 '\n',
 '        if quality.status == "FAIL_MODEL":\n',
 '            st.session_state["data_quality_disabled_models_20260617"] = list(quality.model_disabled)\n',
 '            status["errors"].append(\n',
 '                "Data quality FAIL_MODEL: affected models are blocked in the final policy ("\n',
 '                + ", ".join(quality.model_disabled or ["unspecified model group"]) + ")"\n',
 '            )\n',
 '        else:\n',
 '            st.session_state["data_quality_disabled_models_20260617"] = []\n',
 '\n',
 '        try:\n',
 '            from ui.home_master_control_bar_20260615 import run_home_calculation_gate\n',
 '            run_home_calculation_gate()\n',
 '        except Exception:\n',
 '            for key in ("metric_run_calculate", "research_run_calculate", "other_run_calculate"):\n',
 '                st.session_state[key] = True\n',
 '\n',
 '        st.session_state.update({\n',
 '            "metric_run_calculate": True,\n',
 '            "research_run_calculate": True,\n',
 '            "other_run_calculate": True,\n',
 '            "lunch_force_reversal_scan": True,\n',
 '            "lunch_run_visualization": True,\n',
 '            "lunch_bi_visual_ready": True,\n',
 '            "show_restored_original_lunch_20260617": True,\n',
 '            "show_restored_metric_detail_20260617": True,\n',
 '            "show_restored_metric_history_20260617": True,\n',
 '            "show_restored_powerbi_20260617": True,\n',
 '            "settings_auto_open_lunch_20260617": True,\n',
 '            "dinner_load_original_advanced_details_20260614": True,\n',
 '            "dinner_auto_sync_from_main_run_20260617": True,\n',
 '            "regime_auto_sync_from_main_run_20260617": True,\n',
 '        })\n',
 '\n',
 '        try:\n',
 '            status["metric"] = _build_lunch_metric(ns)\n',
 '            if not status["metric"].get("ok"):\n',
 '                status["ok"] = False\n',
 '                status["errors"].append(status["metric"].get("message", "Lunch metric was not ready."))\n',
 '        except Exception as exc:\n',
 '            status["ok"] = False\n',
 '            status["metric"] = {"ok": False, "message": str(exc)}\n',
 '            status["errors"].append(f"Lunch metric: {exc}")\n',
 '\n',
 '        try:\n',
 '            status["powerbi"] = _build_powerbi(ns, validated_df=clean_preflight)\n',
 '            if not status["powerbi"].get("ok"):\n',
 '                status["ok"] = False\n',
 '                status["errors"].append(status["powerbi"].get("message", "PowerBI was not ready."))\n',
 '        except Exception as exc:\n',
 '            status["ok"] = False\n',
 '            status["powerbi"] = {"ok": False, "message": str(exc)}\n',
 '            status["errors"].append(f"PowerBI: {exc}")\n',
 '\n',
 '        if quick_scope:\n',
 '            nlp_result = {}\n',
 '            research_pack = {}\n',
 '            status["nlp"] = {"ok": False, "status": "SKIPPED_FOR_QUICK_FIELDS_1_2_3"}\n',
 '            status["research"] = {"ok": False, "status": "SKIPPED_FOR_QUICK_FIELDS_1_2_3"}\n',
 '        else:\n',
 '            # NLP, Data Analysis and Data Mining are built in this same Settings\n',
 '            # transaction. Finnhub remains optional; cached/persisted 10-day real\n',
 '            # news is used honestly when the live source returns fewer rows.\n',
 '            try:\n',
 '                from ui.nlp_research_panel import run_nlp_analysis\n',
 '                nlp_result = run_nlp_analysis(force_news=False, use_finbert=False)\n',
 '                articles = nlp_result.get("articles") if isinstance(nlp_result, dict) else None\n',
 '                status["nlp"] = {\n',
 '                    "ok": bool(nlp_result),\n',
 '                    "source": "cached/local or optional Finnhub",\n',
 '                    "article_rows": int(len(articles)) if isinstance(articles, pd.DataFrame) else 0,\n',
 '                    "window_days": 10,\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                nlp_result = {}\n',
 '                status["nlp"] = {"ok": False, "message": str(exc)}\n',
 '                status["errors"].append(f"NLP: {exc}")\n',
 '            try:\n',
 '                from tabs.research import build_all_research_pack_for_settings\n',
 '                research_pack = build_all_research_pack_for_settings(clean_preflight, nlp_result=nlp_result)\n',
 '                status["research"] = {\n',
 '                    "ok": bool(research_pack.get("all_inner_tabs_ready")),\n',
 '                    "data_analysis": bool((research_pack.get("data_analysis") or {}).get("ok")),\n',
 '                    "data_mining": bool((research_pack.get("data_mining") or {}).get("ok")),\n',
 '                    "nlp": bool(research_pack.get("nlp")),\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                research_pack = {}\n',
 '                status["research"] = {"ok": False, "message": str(exc)}\n',
 '                status["errors"].append(f"Research/Data Mining: {exc}")\n',
 '\n',
 '        # Prime the deepest existing regime/reliability caches once inside the\n',
 '        # main Settings workflow. Dinner/Regime renderers only read these caches\n',
 '        # and never expose another Run or Load control.\n',
 '        status["inner_sections"] = {}\n',
 '        for builder_name, label in (\n',
 '            ("build_reliability_control_center_20260614", "reliability"),\n',
 '            ("build_regime_context_20260614", "regime"),\n',
 '        ):\n',
 '            builder = ns.get(builder_name)\n',
 '            if callable(builder):\n',
 '                try:\n',
 '                    built = builder(force=True)\n',
 '                    status["inner_sections"][label] = {"ok": bool(built), "source": builder_name}\n',
 '                except TypeError:\n',
 '                    try:\n',
 '                        built = builder(True)\n',
 '                        status["inner_sections"][label] = {"ok": bool(built), "source": builder_name}\n',
 '                    except Exception as exc:\n',
 '                        status["inner_sections"][label] = {"ok": False, "message": str(exc)}\n',
 '                        status["errors"].append(f"{label.title()} inner cache: {exc}")\n',
 '                except Exception as exc:\n',
 '                    status["inner_sections"][label] = {"ok": False, "message": str(exc)}\n',
 '                    status["errors"].append(f"{label.title()} inner cache: {exc}")\n',
 '            else:\n',
 '                status["inner_sections"][label] = {"ok": False, "message": "Existing builder unavailable"}\n',
 '\n',
 '        try:\n',
 '            from core.adx_shared_sync_20260615 import ensure_shared_calculation_result\n',
 '            legacy_shared = ensure_shared_calculation_result(force=True)\n',
 '        except Exception as exc:\n',
 '            legacy_shared = {}\n',
 '            status["errors"].append(f"Shared sync: {exc}")\n',
 '\n',
 '        try:\n',
 '            from core.regime_sync_20260617 import canonical_regime_snapshot, regime_standard_table, '
 'regime_standard_detail_tables\n',
 '            canonical_regime_snapshot(days=25)\n',
 '            standards = regime_standard_table(force=True)\n',
 '            detail_tables = regime_standard_detail_tables(force=False)\n',
 '            status["regime_detail_tables"] = {k: int(len(v)) for k, v in detail_tables.items() if isinstance(v, '
 'pd.DataFrame)}\n',
 '            st.session_state["regime_standard_table_staging_20260622"] = standards\n',
 '            st.session_state["regime_standard_detail_tables_staging_20260622"] = detail_tables\n',
 '            # Carry the existing 1-day, 5-day and 25-day standards into the same\n',
 '            # immutable result instead of letting the Regime page calculate a\n',
 '            # second, newer copy after Lunch/PowerBI have already finished.\n',
 '            if isinstance(legacy_shared, dict) and isinstance(standards, pd.DataFrame) and not standards.empty:\n',
 '                regime_payload = legacy_shared.setdefault("regime", {})\n',
 '                for _, row in standards.iterrows():\n',
 '                    label = str(row.get("Standard", "")).lower()\n',
 '                    value = str(row.get("Major Regime", "UNKNOWN") or "UNKNOWN")\n',
 '                    if "lower" in label:\n',
 '                        regime_payload["lower_standard_regime"] = value\n',
 '                    elif "middle" in label:\n',
 '                        regime_payload["middle_standard_regime"] = value\n',
 '                    elif "higher" in label:\n',
 '                        regime_payload["higher_standard_regime"] = value\n',
 '                regime_payload["standards"] = standards.to_dict("records")\n',
 '        except Exception as exc:\n',
 '            status["errors"].append(f"Regime sync: {exc}")\n',
 '\n',
 '        canonical_priority_table = pd.DataFrame()\n',
 '        try:\n',
 '            from core.regime_sync_20260617 import merged_hourly_regime_nlp_priority\n',
 '            canonical_priority_table = merged_hourly_regime_nlp_priority(days=REGIME_NLP_HISTORY_DAYS)\n',
 '            status["canonical_priority_rows"] = int(len(canonical_priority_table)) if '
 'isinstance(canonical_priority_table, pd.DataFrame) else 0\n',
 '        except Exception as exc:\n',
 '            status["errors"].append(f"Canonical 25-day priority table: {exc}")\n',
 '\n',
 '        # One causal 600-row Alpha/Delta history feeds all three regime standards.\n',
 '        try:\n',
 '            from core.regime_window_analytics_20260618 import build_regime_window_analytics\n',
 '            legacy_regime = legacy_shared.get("regime", {}) if isinstance(legacy_shared, dict) and '
 'isinstance(legacy_shared.get("regime"), dict) else {}\n',
 '            existing_regime = legacy_regime.get("current") or legacy_regime.get("current_regime") or ""\n',
 '            existing_rel = ((legacy_shared.get("reliability") or {}).get("score", 50) if isinstance(legacy_shared, '
 'dict) else 50)\n',
 '            window_analytics = build_regime_window_analytics(clean_preflight, existing_regime=str(existing_regime), '
 'existing_reliability=float(existing_rel or 50))\n',
 '            st.session_state["regime_window_analytics_20260618"] = window_analytics\n',
 '            if isinstance(legacy_shared, dict):\n',
 '                legacy_shared.setdefault("regime", {})["window_analytics"] = window_analytics\n',
 '                legacy_shared["regime_window_analytics"] = window_analytics\n',
 '                bundle = st.session_state.get("powerbi_calibrated_bundle_20260617")\n',
 '                if isinstance(bundle, dict):\n',
 '                    legacy_shared.setdefault("powerbi", {})["calibrated_bundle"] = bundle\n',
 '            status["regime_window_analytics"] = {"ok": bool(window_analytics.get("ok")), "rows": '
 'int(window_analytics.get("actual_history_rows", 0))}\n',
 '        except Exception as exc:\n',
 '            status["errors"].append(f"Regime window analytics: {exc}")\n',
 '\n',
 '        try:\n',
 '            from core.decision_product_engine_20260617 import build_decision_result, serialize_result\n',
 '            from core.canonical_runtime_20260617 import proposed_generation, publish_canonical_atomically\n',
 '            from core.full_metric_canonical_adapter_20260618 import (\n',
 '                apply_canonical_confirmations,\n',
 '                build_full_metric_authority,\n',
 '                enrich_canonical_payload,\n',
 '            )\n',
 '            final_df = clean_preflight\n',
 '            generation = proposed_generation(st.session_state)\n',
 '\n',
 '            # The 25-day regime/NLP table remains a confirmation source. The\n',
 '            # canonical priority table itself is ranked from the protected Full\n',
 '            # Metric history, so no downstream tab can calculate another bias.\n',
 '            confirmation_priority_table = canonical_priority_table\n',
 '            full_metric_authority = build_full_metric_authority(\n',
 '                status.get("metric") or {},\n',
 '                final_df,\n',
 '                symbol=symbol,\n',
 '                timeframe=timeframe,\n',
 '                legacy_shared=legacy_shared,\n',
 '                confirmation_table=confirmation_priority_table,\n',
 '                data_quality_status=quality.status,\n',
 '            )\n',
 '            # Causal Research support is computed once from completed H1 rows and\n',
 '            # protected Full Metric history. It cannot create or reverse a\n',
 '            # direction; it only enriches candidates and may force WAIT.\n',
 '            try:\n',
 '                from core.causal_quant_support_20260618 import (\n',
 '                    apply_support_to_authority,\n',
 '                    build_causal_support_bundle,\n',
 '                    public_support_view,\n',
 '                )\n',
 '                previous_support = st.session_state.get("causal_quant_support_20260618")\n',
 '                previous_support = previous_support if isinstance(previous_support, dict) else {}\n',
 '                causal_support = build_causal_support_bundle(\n',
 '                    final_df,\n',
 '                    full_metric_authority.get("priority_table"),\n',
 '                    context=legacy_shared,\n',
 '                    previous_cache=previous_support,\n',
 '                )\n',
 '                full_metric_authority = apply_support_to_authority(full_metric_authority, causal_support)\n',
 '                st.session_state["causal_quant_support_20260618"] = causal_support\n',
 '                public_causal_support = public_support_view(causal_support)\n',
 '                if isinstance(legacy_shared, dict):\n',
 '                    legacy_shared["research_support"] = public_causal_support\n',
 '                    legacy_shared.setdefault("data_mining", {})["causal_quant_support"] = public_causal_support\n',
 '                research_pack = st.session_state.get("research_pack_20260612")\n',
 '                if isinstance(research_pack, dict):\n',
 '                    research_pack["causal_quant_support"] = public_causal_support\n',
 '                    st.session_state["research_pack_20260612"] = research_pack\n',
 '                status["causal_support"] = {\n',
 '                    "ok": True,\n',
 '                    "cache_status": causal_support.get("cache_status"),\n',
 '                    "rows": causal_support.get("retained_rows"),\n',
 '                    "pattern": (causal_support.get("pattern_memory") or {}).get("pattern_confirmation"),\n',
 '                    "transition": (causal_support.get("transition_risk") or {}).get("status"),\n',
 '                    "actionability": (causal_support.get("actionability") or {}).get("current_label"),\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                causal_support = {\n',
 '                    "version": "causal-quant-support-20260618-v1",\n',
 '                    "cache_status": "SAFE_FALLBACK",\n',
 '                    "pattern_memory": {"pattern_confirmation": "NEUTRAL", "pattern_confidence": 0.0},\n',
 '                    "transition_risk": {"status": "WATCH", "value": 0.5},\n',
 '                    "actionability": {"current_label": "WATCH", "status": "FAILED SAFELY"},\n',
 '                    "failure": str(exc)[:300],\n',
 '                }\n',
 '                st.session_state["causal_quant_support_20260618"] = causal_support\n',
 '                status["errors"].append(f"Causal Research support: {exc}")\n',
 '            canonical_priority_table = full_metric_authority["priority_table"]\n',
 '            canonical_obj = build_decision_result(\n',
 '                legacy_shared=legacy_shared, ohlc=final_df, symbol=symbol,\n',
 '                timeframe=timeframe, source=source, ledger=ledger,\n',
 '                calculation_generation=generation,\n',
 '                full_metric_snapshot=full_metric_authority["snapshot"],\n',
 '            )\n',
 '            canonical_base = serialize_result(canonical_obj)\n',
 '            try:\n',
 '                from core.causal_quant_support_20260618 import apply_support_to_canonical\n',
 '                canonical_base = apply_support_to_canonical(canonical_base, causal_support)\n',
 '            except Exception as exc:\n',
 '                canonical_base.setdefault("metadata", {})["causal_support_apply_error"] = str(exc)[:240]\n',
 '                canonical_base.setdefault("final_decision", {}).setdefault("blocking_reasons", []).append(\n',
 '                    "Causal support failed safely; entry remains conservatively gated"\n',
 '                )\n',
 '                canonical_base["final_decision"]["final_decision"] = "WAIT"\n',
 '                canonical_base["final_decision"]["tradeability_decision"] = "WAIT"\n',
 '                canonical_base["final_decision"]["less_risky_decision"] = "WAIT"\n',
 '\n',
 '            # Additive multi-scale volatility/risk calibration.  This layer never\n',
 '            # changes the protected Full Metric formulas or the central red/yellow/\n',
 '            # blue path.  It is calculated once inside this Settings transaction\n',
 '            # and is then reused by every existing tab through the canonical adapter.\n',
 '            from core.multiscale_probabilistic_upgrade_20260618 import (\n',
 '                build_and_apply_upgrade,\n',
 '                enrich_existing_regime_tables,\n',
 '                invariant_report,\n',
 '            )\n',
 '            previous_upgrade = st.session_state.get("multiscale_probabilistic_upgrade_20260618")\n',
 '            previous_upgrade = previous_upgrade if isinstance(previous_upgrade, dict) else {}\n',
 '            canonical_base, upgrade_cache, upgraded_bundle = build_and_apply_upgrade(\n',
 '                canonical_base,\n',
 '                ohlc=final_df,\n',
 '                calibrated_bundle=st.session_state.get("powerbi_calibrated_bundle_20260617"),\n',
 '                prediction_history=st.session_state.get("dv_pp_bt_hist"),\n',
 '                previous_cache=previous_upgrade,\n',
 '            )\n',
 '            st.session_state["multiscale_probabilistic_upgrade_20260618"] = upgrade_cache\n',
 '\n',
 '            # Ten-paper causal calibration runs once inside the same Settings\n',
 '            # transaction. It is optional and fail-safe: Full Metric History and\n',
 '            # the previously valid canonical result remain publishable if this\n',
 '            # enrichment fails. The red/yellow/blue central paths are preserved;\n',
 '            # only empirical bands, uncertainty and validation metadata are added.\n',
 '            research_result = {}\n',
 '            # One bounded settled-evidence frame is reused by the second-generation\n',
 '            # reliability/shift transaction. It is populated by the existing\n',
 '            # research settlement block and never stored as another session-state\n',
 '            # DataFrame.\n',
 '            settled_research_predictions = pd.DataFrame()\n',
 '            try:\n',
 '                from core.research_calibration_20260618 import (\n',
 '                    ResearchStore,\n',
 '                    build_research_layer_fail_safe,\n',
 '                )\n',
 '                research_store = ResearchStore()\n',
 '                experiment_matrix, _, _ = research_store.performance_matrix()\n',
 '                conformal_settlement = research_store.settle_conformal_predictions(final_df)\n',
 '                research_outcomes = research_store.completed_conformal_outcomes(limit=5000)\n',
 '                ledger_outcomes = ledger.settled_predictions(symbol=symbol, timeframe=timeframe, limit=6000)\n',
 '                completed_sources = [frame for frame in (ledger_outcomes, research_outcomes) if isinstance(frame, '
 'pd.DataFrame) and not frame.empty]\n',
 '                settled_research_predictions = pd.concat(completed_sources, ignore_index=True, sort=False) if '
 'completed_sources else pd.DataFrame()\n',
 '                status["research_conformal_settlement"] = conformal_settlement\n',
 '                previous_research = st.session_state.get("research_calibration_20260618")\n',
 '                previous_research = previous_research if isinstance(previous_research, dict) else {}\n',
 '                canonical_base, research_result, upgraded_bundle, research_layer_status = '
 'build_research_layer_fail_safe(\n',
 '                    canonical_base,\n',
 '                    ohlc=final_df,\n',
 '                    calibrated_bundle=upgraded_bundle,\n',
 '                    prediction_history=st.session_state.get("dv_pp_bt_hist"),\n',
 '                    settled_predictions=settled_research_predictions,\n',
 '                    previous_cache=previous_research,\n',
 '                    experiment_performance_matrix=experiment_matrix,\n',
 '                    # PBO/DSR remain honestly UNAVAILABLE until the registry has\n',
 '                    # enough tested configurations and aligned realised returns.\n',
 '                    strategy_returns=None,\n',
 '                    number_of_trials=None,\n',
 '                    sharpe_trials=None,\n',
 '                )\n',
 '                if research_layer_status.get("ok"):\n',
 '                    st.session_state["research_calibration_20260618"] = research_result\n',
 '                    status["research_calibration"] = {\n',
 '                        "ok": True,\n',
 '                        "calculation_id": research_result.get("canonical_calculation_id"),\n',
 '                        "validation_status": research_result.get("validation_status"),\n',
 '                        "residual_vectors": (research_result.get("conformal_prediction") or '
 '{}).get("residual_vector_count"),\n',
 '                        "pbo_status": (research_result.get("pbo") or {}).get("status"),\n',
 '                        "dsr_status": (research_result.get("dsr") or {}).get("validation_label"),\n',
 '                        "invariants": research_result.get("invariants"),\n',
 '                    }\n',
 '                else:\n',
 '                    status["research_calibration"] = {"ok": False, "optional": True, **research_layer_status}\n',
 '            except Exception as exc:\n',
 '                canonical_base.setdefault("metadata", {})["research_calibration_error"] = str(exc)[:500]\n',
 '                canonical_base.setdefault("metadata", {})["research_calibration_status"] = "FAILED SAFELY"\n',
 '                status["research_calibration"] = {"ok": False, "optional": True, "message": str(exc)}\n',
 '\n',
 '            # Lightweight ten-concept risk stack. It consumes only completed H1\n',
 '            # candles, settled forecasts and the protected Full Metric authority.\n',
 '            # It cannot create/reverse direction; it may only confirm, downgrade,\n',
 '            # or force WAIT. All outputs are computed once in this transaction.\n',
 '            research_risk_result = {}\n',
 '            try:\n',
 '                from core.research_risk_stack_20260619 import (\n',
 '                    build_and_apply_research_risk_stack,\n',
 '                    enrich_metric_history,\n',
 '                )\n',
 '                previous_risk = st.session_state.get("research_risk_stack_20260619")\n',
 '                previous_risk = previous_risk if isinstance(previous_risk, dict) else {}\n',
 '                canonical_base, research_risk_result, risk_priority_table, upgraded_bundle = '
 'build_and_apply_research_risk_stack(\n',
 '                    canonical_base,\n']
