"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = ['                    ohlc=final_df,\n',
 '                    trust_store=trust_store,\n',
 '                    priority_table=full_metric_authority.get("priority_table"),\n',
 '                    calibrated_bundle=upgraded_bundle,\n',
 '                    previous_cache=previous_risk,\n',
 '                    precomputed_periodicity=periodicity_precomputed,\n',
 '                    precomputed_periodicity_frame=periodicity_frame_precomputed,\n',
 '                )\n',
 '                st.session_state["research_risk_stack_20260619"] = research_risk_result\n',
 '                if isinstance(risk_priority_table, pd.DataFrame) and not risk_priority_table.empty:\n',
 '                    full_metric_authority["priority_table"] = risk_priority_table\n',
 '                    status["metric"] = enrich_metric_history(status.get("metric") or {}, risk_priority_table)\n',
 '                status["research_risk_stack"] = {\n',
 '                    "ok": True,\n',
 '                    "version": research_risk_result.get("version"),\n',
 '                    "periodicity_status": (research_risk_result.get("periodicity") or {}).get("status"),\n',
 '                    "proper_scoring_status": (research_risk_result.get("proper_scoring") or {}).get("status"),\n',
 '                    "competing_risk_status": (research_risk_result.get("competing_risk") or {}).get("status"),\n',
 '                    "trust_status": (research_risk_result.get("confidence_sequence") or {}).get("trust_status"),\n',
 '                    "selective_pass": (research_risk_result.get("selective_prediction") or '
 '{}).get("selective_prediction_pass"),\n',
 '                    "evt_sufficient": (research_risk_result.get("evt_tail") or {}).get("evt_sample_sufficient"),\n',
 '                    "event_cluster_level": (research_risk_result.get("event_intensity") or '
 '{}).get("event_cluster_level"),\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                canonical_base.setdefault("metadata", {})["research_risk_stack_status"] = "FAILED SAFELY"\n',
 '                canonical_base["metadata"]["research_risk_stack_error"] = str(exc)[:500]\n',
 '                status["research_risk_stack"] = {"ok": False, "optional": True, "message": str(exc)}\n',
 '                status["errors"].append(f"Research risk stack: {exc}")\n',
 '\n',
 '            if isinstance(upgraded_bundle, dict):\n',
 '                st.session_state["powerbi_calibrated_bundle_20260617"] = upgraded_bundle\n',
 '                try:\n',
 '                    from core.powerbi_path_calibration_20260617 import calibrated_candles\n',
 '                    anchor = float(pd.to_numeric(final_df["close"], errors="coerce").dropna().iloc[-1])\n',
 '                    st.session_state["dv_pp_predicted_calibrated_20260617"] = calibrated_candles(\n',
 '                        upgraded_bundle, anchor_price=anchor\n',
 '                    )\n',
 '                except Exception as exc:\n',
 '                    canonical_base.setdefault("metadata", {})["probabilistic_candle_refresh_error"] = '
 'str(exc)[:240]\n',
 '            detail_tables, standards = enrich_existing_regime_tables(\n',
 '                detail_tables, standards if isinstance(standards, pd.DataFrame) else pd.DataFrame(),\n',
 '                canonical_base.get("multiscale_regime") or {},\n',
 '                str(canonical_base.get("canonical_calculation_id") or ""),\n',
 '            )\n',
 '            st.session_state["regime_standard_detail_tables_staging_20260622"] = detail_tables\n',
 '            st.session_state["regime_standard_table_staging_20260622"] = standards\n',
 '            status["multiscale_probabilistic_upgrade"] = {\n',
 '                "ok": True,\n',
 '                "calculation_id": canonical_base.get("canonical_calculation_id"),\n',
 '                "volatility_regime": (canonical_base.get("multiscale_regime") or '
 '{}).get("current_volatility_regime"),\n',
 '                "invariants": invariant_report(canonical_base),\n',
 '            }\n',
 '            full_metric_authority = apply_canonical_confirmations(\n',
 '                full_metric_authority, canonical_base\n',
 '            )\n',
 '            # Refresh only the candidate display/status aliases after the existing\n',
 '            # canonical gates settle. Protected Full Metric formulas and direction\n',
 '            # remain untouched; this keeps Lunch, Dinner, Finder and AI identical.\n',
 '            try:\n',
 '                from core.causal_quant_support_20260618 import apply_support_to_authority\n',
 '                full_metric_authority = apply_support_to_authority(full_metric_authority, causal_support)\n',
 '            except Exception as exc:\n',
 '                canonical_base.setdefault("metadata", {})["candidate_support_refresh_error"] = str(exc)[:240]\n',
 '            canonical_priority_table = full_metric_authority["priority_table"]\n',
 '            canonical = enrich_canonical_payload(canonical_base, full_metric_authority)\n',
 '            canonical["calculation_started_at"] = run_started_at\n',
 '            try:\n',
 '                from core.trust_history_20260619 import enrich_canonical_with_trust, get_trust_history_store\n',
 '                trust_store = trust_store or get_trust_history_store()\n',
 '                canonical = enrich_canonical_with_trust(canonical, trust_store)\n',
 '                # Include the forecasts about to be recorded as pending, never as settled.\n',
 '                trust_summary = canonical.get("trust_validation") if isinstance(canonical.get("trust_validation"), '
 'dict) else {}\n',
 '                trust_summary["pending_sample_count"] = int(trust_summary.get("pending_sample_count") or 0) + len(\n',
 '                    ((canonical.get("forecasts") or {}).get("horizons") or {})\n',
 '                )\n',
 '                canonical["trust_validation"] = trust_summary\n',
 '                status["trust_validation"] = {\n',
 '                    "ok": True,\n',
 '                    "settled_samples": trust_summary.get("settled_sample_count", 0),\n',
 '                    "pending_samples": trust_summary.get("pending_sample_count", 0),\n',
 '                    "classification": trust_summary.get("trust_classification", "INSUFFICIENT"),\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                canonical.setdefault("metadata", {})["trust_validation_error"] = str(exc)[:300]\n',
 '                status["trust_validation"] = {"ok": False, "error": str(exc)}\n',
 '                status["errors"].append(f"Trust validation: {exc}")\n',
 '            # Build the display-only aggregate position-sizing guardrail from\n',
 '            # current account/risk settings. It never changes protected trading\n',
 '            # formulas or the BUY/SELL/WAIT decision.\n',
 '            try:\n',
 '                from services.position_sizing import build_risk_plan\n',
 '                canonical["risk_plan"] = build_risk_plan(st.session_state, canonical)\n',
 '                status["risk_plan"] = {\n',
 '                    "ok": True,\n',
 '                    "status": canonical["risk_plan"].get("status"),\n',
 '                    "recommended_lots": canonical["risk_plan"].get("recommended_lots"),\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                canonical["risk_plan"] = {"status": "BLOCK", "reason": f"Position sizing unavailable: {exc}", '
 '"recommended_lots": 0.0}\n',
 '                status["errors"].append(f"Position sizing guardrail: {exc}")\n',
 '\n',
 '            # Decision 11 is a read-only interpretation of the already completed\n',
 '            # canonical outputs. It appends one published support decision and never\n',
 '            # changes or reweights the protected original ten decisions.\n',
 '            try:\n',
 '                from core.medium_standard_regime_bias_20260619 import build_medium_standard_regime_bias\n',
 '                canonical["medium_standard_regime_bias"] = build_medium_standard_regime_bias(canonical)\n',
 '                status["medium_standard_regime_bias"] = {\n',
 '                    "ok": True,\n',
 '                    "decision": canonical["medium_standard_regime_bias"].get("decision"),\n',
 '                    "score": canonical["medium_standard_regime_bias"].get("score"),\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                canonical["medium_standard_regime_bias"] = {\n',
 '                    "decision_number": 11, "name": "Medium-Standard Regime Bias",\n',
 '                    "decision": "WAIT", "score": 5.0, "confidence_class": "Weak",\n',
 '                    "primary_reason": "Published canonical inputs were incomplete.",\n',
 '                    "conflict_warning": str(exc)[:240], "read_only_support": True,\n',
 '                    "protected_ten_decisions_changed": False,\n',
 '                }\n',
 '                status["medium_standard_regime_bias"] = {"ok": False, "message": str(exc)}\n',
 '\n',
 '            similar_day_feature_rows = []\n',
 '            if quick_scope:\n',
 '                status["similar_day_intelligence"] = {"ok": False, "status": "SKIPPED_FOR_QUICK_FIELDS_1_2_3"}\n',
 '            else:\n',
 "                # Similar-Day Intelligence is calculated once from this transaction's\n",
 '                # completed H1 authority, then embedded in the same canonical payload.\n',
 '                # Lunch Field 4 is display-only and never calls this builder.\n',
 '                similar_day_feature_rows = []\n',
 '                try:\n',
 '                    from core.similar_day_intelligence_20260619 import build_similar_day_intelligence\n',
 '                    similar_day_result = build_similar_day_intelligence(\n',
 '                        final_df, canonical, history_table=canonical_priority_table,\n',
 '                        forecast_history=st.session_state.get("dv_pp_bt_hist"),\n',
 '                        state=st.session_state,\n',
 '                    )\n',
 '                    similar_day_result = dict(similar_day_result) if isinstance(similar_day_result, dict) else {}\n',
 '                    similar_day_feature_rows = list(similar_day_result.pop("_feature_store_rows", []) or [])\n',
 '                    canonical["similar_day_intelligence"] = similar_day_result\n',
 '                    status["similar_day_intelligence"] = {\n',
 '                        "ok": bool(similar_day_result.get("ok")),\n',
 '                        "status": similar_day_result.get("status"),\n',
 '                        "candidate_rows": len(similar_day_result.get("history_25") or []),\n',
 '                        "top_five_rows": len(similar_day_result.get("top_five") or []),\n',
 '                        "reliability": similar_day_result.get("reliability"),\n',
 '                        "cache_status": similar_day_result.get("cache_status"),\n',
 '                        "duration_seconds": similar_day_result.get("calculation_duration_seconds"),\n',
 '                    }\n',
 '                    st.session_state["similar_day_intelligence_20260619"] = similar_day_result\n',
 '                except Exception as exc:\n',
 '                    similar_day_result = {\n',
 '                        "ok": False, "status": "Unavailable",\n',
 '                        "message": "The completed generation did not contain enough valid, aligned EURUSD H1 history '
 'for Similar-Day Intelligence. Existing Lunch data remains available.",\n',
 '                        "engine_version": "similar-day-engine-20260619-v1",\n',
 '                        "feature_version": "similar-day-features-20260619-v1",\n',
 '                        "calculated_at": pd.Timestamp.now(tz="UTC").isoformat(),\n',
 '                        "latest_completed_h1_timestamp": canonical.get("latest_completed_candle_time"),\n',
 '                        "calculation_generation": canonical.get("calculation_generation"),\n',
 '                    }\n',
 '                    canonical["similar_day_intelligence"] = similar_day_result\n',
 '                    st.session_state["similar_day_intelligence_20260619"] = similar_day_result\n',
 '                    st.session_state["similar_day_technical_error_20260619"] = repr(exc)\n',
 '                    status["similar_day_intelligence"] = {"ok": False, "status": "Unavailable", "message": '
 'str(exc)}\n',
 '                    status["errors"].append(f"Similar-Day Intelligence: {exc}")\n',
 '\n',
 '            # Second-generation Advanced Reliability and Distribution-Shift Layer.\n',
 '            # This is the single hidden versioned research transaction: it runs\n',
 '            # after settled forecast evidence and the complete canonical object are\n',
 '            # available, but before atomic canonical publication. It reuses this\n',
 "            # transaction's completed H1 frame and one bounded settled frame.\n",
 '            advanced_reliability_result = {}\n',
 '            advanced_reliability_store = None\n',
 '            try:\n',
 '                from core.advanced_reliability_shift_20260620 import (\n',
 '                    AdvancedReliabilityStore,\n',
 '                    build_advanced_reliability_transaction,\n',
 '                )\n',
 '                advanced_reliability_store = AdvancedReliabilityStore()\n',
 '                if not isinstance(settled_research_predictions, pd.DataFrame) or '
 'settled_research_predictions.empty:\n',
 '                    settled_research_predictions = (\n',
 '                        trust_store.frame(status="SETTLED", limit=6000)\n',
 '                        if trust_store is not None else pd.DataFrame()\n',
 '                    )\n',
 '                canonical, advanced_reliability_result, advanced_stage = build_advanced_reliability_transaction(\n',
 '                    canonical,\n',
 '                    completed_h1=final_df,\n',
 '                    settled_predictions=settled_research_predictions,\n',
 '                    store=advanced_reliability_store,\n',
 '                    previous=st.session_state.get("advanced_reliability_shift_20260620"),\n',
 '                    persist_stage=True,\n',
 '                )\n',
 '                st.session_state["advanced_reliability_shift_20260620"] = advanced_reliability_result\n',
 '                status["advanced_reliability_shift"] = {\n',
 '                    "ok": True,\n',
 '                    "version": advanced_reliability_result.get("version"),\n',
 '                    "calculation_id": (advanced_reliability_result.get("identity") or {}).get("calculation_id"),\n',
 '                    "settled_rows": (advanced_reliability_result.get("input_contract") or '
 '{}).get("settled_prediction_rows"),\n',
 '                    "crc_status": (advanced_reliability_result.get("conformal_risk_control") or {}).get("status"),\n',
 '                    "mmd_severity": (advanced_reliability_result.get("mmd") or {}).get("severity"),\n',
 '                    "bbse_status": (advanced_reliability_result.get("bbse") or {}).get("status"),\n',
 '                    "trust_cap_pct": advanced_reliability_result.get("trust_cap_pct"),\n',
 '                    "stage": advanced_stage,\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                canonical.setdefault("metadata", {})["advanced_reliability_shift_status"] = "FAILED SAFELY"\n',
 '                canonical["metadata"]["advanced_reliability_shift_error"] = str(exc)[:500]\n',
 '                status["advanced_reliability_shift"] = {"ok": False, "optional": True, "message": str(exc)}\n',
 '                status["errors"].append(f"Advanced reliability/shift layer: {exc}")\n',
 '\n',
 '            history_bundle = {}\n',
 '            if quick_scope:\n',
 '                status["history_research_evidence"] = {"ok": False, "status": "SKIPPED_FOR_QUICK_FIELDS_1_2_3"}\n',
 '            else:\n',
 '                # Build the history-first research evidence exactly once inside the\n',
 '                # Settings transaction. It consumes only the completed H1 frame and\n',
 '                # already-computed canonical outputs; protected formulas, decisions,\n',
 '                # thresholds, weights and original paths are never changed.\n',
 '                history_bundle = {}\n',
 '                try:\n',
 '                    from core.history_research_pipeline_20260620 import build_history_research_transaction\n',
 '                    previous_published = st.session_state.get("canonical_decision_result")\n',
 '                    previous_published = previous_published if isinstance(previous_published, Mapping) else {}\n',
 '                    canonical, history_bundle, history_summary = build_history_research_transaction(\n',
 '                        canonical,\n',
 '                        completed_h1=final_df,\n',
 '                        priority_table=canonical_priority_table,\n',
 '                        settled_predictions=settled_research_predictions,\n',
 '                        calibrated_bundle=upgraded_bundle if isinstance(upgraded_bundle, Mapping) else {},\n',
 '                        previous=previous_published,\n',
 '                    )\n',
 '                    status["history_research_evidence"] = {\n',
 '                        "ok": True,\n',
 '                        "version": history_summary.get("version"),\n',
 '                        "total_rows": history_summary.get("total_rows"),\n',
 '                        "tables_affected": history_summary.get("tables_affected"),\n',
 '                        "protected_outputs_changed": history_summary.get("protected_outputs_changed"),\n',
 '                        "duration_ms": history_summary.get("duration_ms"),\n',
 '                    }\n',
 '                except Exception as exc:\n',
 '                    # Fail safely: the protected canonical object remains publishable,\n',
 '                    # while no partial evidence table is committed.\n',
 '                    history_bundle = {}\n',
 '                    canonical.setdefault("metadata", {})["history_research_evidence_status"] = "FAILED SAFELY"\n',
 '                    canonical["metadata"]["history_research_evidence_error"] = str(exc)[:500]\n',
 '                    status["history_research_evidence"] = {"ok": False, "optional": True, "message": str(exc)}\n',
 '                    status["errors"].append(f"History research evidence: {exc}")\n',
 '\n',
 '            # Regime transition, drift and trust evidence is computed once here.\n',
 '            # It wraps the protected regime as a warning/calibration layer and\n',
 '            # never overwrites the canonical regime or decision.\n',
 '            try:\n',
 '                from core.regime_transition_trust_20260621 import build_regime_transition_trust\n',
 '                previous_published = st.session_state.get("canonical_decision_result")\n',
 '                previous_published = previous_published if isinstance(previous_published, Mapping) else {}\n',
 '                canonical, regime_trust_result, regime_trust_history_bundle = build_regime_transition_trust(\n',
 '                    canonical, completed_h1=final_df, priority_table=canonical_priority_table,\n',
 '                    settled_predictions=settled_research_predictions,\n',
 '                    calibrated_bundle=upgraded_bundle if isinstance(upgraded_bundle, Mapping) else {},\n',
 '                    previous=previous_published,\n',
 '                )\n',
 '                st.session_state["regime_transition_trust_center_20260621"] = regime_trust_result\n',
 '                status["regime_transition_trust_center"] = {\n',
 '                    "ok": True,\n',
 '                    "drift_type": (regime_trust_result.get("transition_summary") or {}).get("drift_type"),\n',
 '                    "transition_status": (regime_trust_result.get("transition_summary") or '
 '{}).get("transition_status"),\n',
 '                    "protected_regime_unchanged": regime_trust_result.get("protected_regime_unchanged"),\n',
 '                }\n',
 '            except Exception as exc:\n',
 '                regime_trust_history_bundle = {}\n',
 '                canonical.setdefault("metadata", {})["regime_transition_trust_status"] = "FAILED SAFELY"\n',
 '                canonical["metadata"]["regime_transition_trust_error"] = str(exc)[:500]\n',
 '                status["regime_transition_trust_center"] = {"ok": False, "optional": True, "message": str(exc)}\n',
 '                status["errors"].append(f"Regime transition trust center: {exc}")\n',
 '\n',
 '            if quick_scope:\n',
 '                status["research_validation_20260621"] = {"ok": False, "status": "SKIPPED_FOR_QUICK_FIELDS_1_2_3"}\n',
 '                status["ten_paper_research_20260621"] = {"ok": False, "status": "SKIPPED_FOR_QUICK_FIELDS_1_2_3"}\n',
 '                for _quick_key in (\n',
 '                    "quant_research_v3_20260622", "quant_research_v4_20260622",\n',
 '                    "quant_research_v6_20260622", "quant_research_v7_20260622",\n',
 '                    "quant_research_v8_20260622",\n',
 '                ):\n',
 '                    status[_quick_key] = {"ok": False, "status": "SKIPPED_FOR_QUICK_FIELDS_1_2_3", "shadow_only": '
 'True}\n',
 '            else:\n',
 '                # Ten-paper research-validation layer. This executes once on the\n',
 '                # Settings Run Calculation path, uses bounded settled evidence, and\n',
 '                # publishes shadow/trust outputs only. It never creates or reverses a\n',
 '                # BUY/SELL direction.\n',
 '                try:\n',
 '                    from core.research_validation_common_20260621 import profile_int\n',
 '                    from core.research_validation_layer_20260621 import build_research_validation_transaction\n',
 '                    settled_method_predictions = (\n',
 '                        trust_store.method_frame(status="SETTLED", limit=profile_int(12000, 2000))\n',
 '                        if trust_store is not None else pd.DataFrame()\n',
 '                    )\n',
 '                    previous_published = st.session_state.get("canonical_decision_result")\n',
 '                    previous_published = previous_published if isinstance(previous_published, Mapping) else {}\n',
 '                    canonical, research_validation_bundle, research_validation_summary = '
 'build_research_validation_transaction(\n',
 '                        canonical,\n',
 '                        completed_h1=final_df,\n',
 '                        settled_predictions=settled_research_predictions,\n',
 '                        settled_method_predictions=settled_method_predictions,\n',
 '                        preflight_validation=research_validation_preflight,\n',
 '                        previous=previous_published,\n',
 '                        runtime_metrics={\n',
 '                            "calculation_latency_ms": (time.perf_counter() - perf_started) * 1000.0,\n',
 '                            "rss_mb": (int(_process.memory_info().rss) / (1024.0 * 1024.0)) if _process is not None '
 'else None,\n',
 '                        },\n',
 '                    )\n',
 '                    history_bundle.update(research_validation_bundle)\n',
 '                    status["research_validation_20260621"] = {"ok": True, **research_validation_summary}\n',
 '                except Exception as exc:\n',
 '                    # Optional statistical evidence fails closed: no promotion and no\n',
 '                    # direction change. The protected canonical payload remains valid.\n',
 '                    canonical.setdefault("metadata", {})["research_validation_20260621_status"] = "FAILED SAFELY"\n',
 '                    canonical["metadata"]["research_validation_20260621_error"] = str(exc)[:500]\n',
 '                    status["research_validation_20260621"] = {"ok": False, "optional": True, "message": str(exc)}\n',
 '                    status["errors"].append(f"Research validation layer: {exc}")\n',
 '\n',
 '                # Ten requested paper concepts are built exactly once here, after all\n',
 '                # required settled evidence is available and immediately before the\n',
 '                # canonical publication gate. Builders are intentionally absent from\n',
 '                # tabs/pages/renderers. Outputs start in SHADOW mode and can only keep\n',
 '                # a protected direction or conservatively recommend WAIT.\n',
 '                try:\n',
 '                    from core.ten_paper_research_layers_20260621 import build_ten_paper_research_transaction\n',
 '                    from core.research_validation_store_20260621 import BUNDLE_KEY\n',
 '                    previous_published = st.session_state.get("canonical_decision_result")\n',
 '                    previous_published = previous_published if isinstance(previous_published, Mapping) else {}\n',
 '                    methods_for_ten_papers = (\n',
 '                        settled_method_predictions\n',
 '                        if "settled_method_predictions" in locals() and isinstance(settled_method_predictions, '
 'pd.DataFrame)\n',
 '                        else pd.DataFrame()\n',
 '                    )\n',
 '                    canonical, ten_paper_bundle, ten_paper_summary = build_ten_paper_research_transaction(\n',
 '                        canonical,\n',
 '                        completed_h1=final_df,\n',
 '                        settled_predictions=settled_research_predictions,\n',
 '                        settled_method_predictions=methods_for_ten_papers,\n',
 '                        previous=previous_published,\n',
 '                    )\n',
 '                    # Both research generations share the same custom bundle key. Merge\n',
 '                    # table rows instead of replacing the already-staged transaction.\n',
 '                    staged = history_bundle.setdefault(BUNDLE_KEY, {})\n',
 '                    for table_name, rows in (ten_paper_bundle.get(BUNDLE_KEY, {}) or {}).items():\n',
 '                        staged.setdefault(table_name, []).extend(list(rows or []))\n',
 '                    status["ten_paper_research_20260621"] = {"ok": True, **ten_paper_summary}\n',
 '                except Exception as exc:\n',
 '                    canonical.setdefault("metadata", {})["ten_paper_research_status"] = "INSUFFICIENT_EVIDENCE"\n',
 '                    canonical["metadata"]["ten_paper_research_error"] = str(exc)[:500]\n',
 '                    status["ten_paper_research_20260621"] = {\n',
 '                        "ok": False, "optional": True, "mode": "SHADOW",\n',
 '                        "status": "INSUFFICIENT_EVIDENCE", "message": str(exc),\n',
 '                    }\n',
 '                    status["errors"].append(f"Ten-paper shadow research layer: {exc}")\n',
 '\n',
 '                # Advanced Quant Research V3 runs exactly once here: after canonical\n',
 '                # broker-time normalization, completed-H1 validation, data-quality\n',
 '                # preflight, protected calculations and due-outcome settlement, and\n',
 '                # before final atomic publication. Renderers, copy controls and AI\n',
 '                # questions only read the published compact generation.\n',
 '                try:\n',
 '                    from core.quant_research_v3_store_20260622 import (\n',
 '                        BUNDLE_KEY as QUANT_V3_BUNDLE_KEY,\n',
 '                        build_quant_research_v3_transaction,\n',
 '                    )\n',
 '                    previous_published = st.session_state.get("canonical_decision_result")\n',
 '                    previous_published = previous_published if isinstance(previous_published, Mapping) else {}\n',
 '                    canonical, quant_v3_bundle, quant_v3_summary = build_quant_research_v3_transaction(\n',
 '                        canonical,\n',
 '                        completed_h1=final_df,\n',
 '                        previous=previous_published,\n',
 '                    )\n',
 '                    staged_v3 = quant_v3_bundle.get(QUANT_V3_BUNDLE_KEY) if isinstance(quant_v3_bundle, Mapping) '
 'else None\n',
 '                    if staged_v3:\n',
 '                        history_bundle[QUANT_V3_BUNDLE_KEY] = staged_v3\n',
 '                    status["quant_research_v3_20260622"] = {"ok": quant_v3_summary.get("status") != "FAILED_SAFELY", '
 '**quant_v3_summary}\n',
 '                except Exception as exc:\n',
 '                    canonical.setdefault("metadata", {})["quant_research_v3_status"] = "FAILED_SAFELY"\n',
 '                    canonical["metadata"]["quant_research_v3_error"] = str(exc)[:500]\n',
 '                    status["quant_research_v3_20260622"] = {\n',
 '                        "ok": False, "optional": True, "mode": "SHADOW",\n',
 '                        "status": "FAILED_SAFELY", "message": str(exc),\n',
 '                        "production_influence_enabled": False,\n',
 '                    }\n',
 '                    status["errors"].append(f"Advanced Quant Research V3: {exc}")\n',
 '\n',
 '                # Advanced Quant Research V4 runs exactly once at the same protected\n',
 '                # Settings boundary, after completed-H1 normalization, protected\n',
 '                # calculations, settled outcomes, and Quant V3 evidence, but before\n',
 '                # final canonical publication. Renderers, copy, AI, refresh and page\n',
 '                # navigation only read this published generation and never refit it.\n',
 '                try:\n',
 '                    from core.quant_research_v4_store_20260622 import (\n',
 '                        BUNDLE_KEY as QUANT_V4_BUNDLE_KEY,\n',
 '                        build_quant_research_v4_transaction,\n',
 '                    )\n',
 '                    previous_published = st.session_state.get("canonical_decision_result")\n',
 '                    previous_published = previous_published if isinstance(previous_published, Mapping) else {}\n',
 '                    canonical, quant_v4_bundle, quant_v4_summary = build_quant_research_v4_transaction(\n',
 '                        canonical,\n',
 '                        completed_h1=final_df,\n',
 '                        settled_outcomes=settled_research_predictions,\n',
 '                        previous=previous_published,\n',
 '                    )\n',
 '                    staged_v4 = quant_v4_bundle.get(QUANT_V4_BUNDLE_KEY) if isinstance(quant_v4_bundle, Mapping) '
 'else None\n',
 '                    if staged_v4:\n',
 '                        history_bundle[QUANT_V4_BUNDLE_KEY] = staged_v4\n']
