"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = ['"""Canonical event-time and MT5 broker-chart clock contract.\n',
 '\n',
 'UTC remains the identity/storage clock.  Broker and Myanmar clocks are display\n',
 'projections only.  Broker time is never silently replaced with UTC when the\n',
 'broker clock is not configured.\n',
 '"""\n',
 'from __future__ import annotations\n',
 '\n',
 'from datetime import timedelta, timezone\n',
 'import re\n',
 'from typing import Any, Mapping, MutableMapping, Sequence\n',
 'from zoneinfo import ZoneInfo, ZoneInfoNotFoundError\n',
 '\n',
 'import pandas as pd\n',
 '\n',
 'CONTRACT_VERSION = "broker-time-contract-20260630-v4"\n',
 'BROKER_TIME_UNAVAILABLE = "BROKER TIME UNAVAILABLE — CONFIGURE SETTINGS"\n',
 '\n',
 '# Date and Hour are deliberately excluded: neither is an authoritative candle\n',
 '# timestamp.  A DatetimeIndex is accepted after the explicit columns.\n',
 '_TIME_COLUMNS: tuple[str, ...] = (\n',
 '    "event_time_utc", "latest_completed_h1_utc", "record_time", "target_time",\n',
 '    "broker_candle_time", "Broker Candle Time", "Completed Broker Candle",\n',
 '    "completed_broker_candle", "Broker Candle", "Completed Candle",\n',
 '    "time", "Time", "Datetime", "DateTime", "Timestamp", "timestamp",\n',
 '    "candle time", "Candle Time", "candle_time", "latest_completed_h1",\n',
 '    "latest_completed_candle_time", "anchor_time", "future_time", "Future Time",\n',
 '    "projection_time", "Projection Time", "target time", "Target Time",\n',
 ')\n',
 '_DISPLAY_CLOCK_ALIASES: frozenset[str] = frozenset({\n',
 '    "broker candle time", "completed broker candle", "completed candle",\n',
 '    "broker candle", "broker time", "candle time", "time", "datetime", "timestamp",\n',
 '})\n',
 '_MANUAL_OFFSET_KEYS: tuple[str, ...] = (\n',
 '    "manual_broker_offset_minutes_20260622",\n',
 '    "manual_broker_utc_offset_hours_20260622",\n',
 '    "mt5_broker_utc_offset_hours_20260622",\n',
 '    "broker_utc_offset_hours",\n',
 '    "mt5_server_utc_offset_hours",\n',
 ')\n',
 '_IANA_KEYS: tuple[str, ...] = (\n',
 '    "broker_timezone_iana_20260622", "broker_iana_timezone", "broker_timezone",\n',
 '    "mt5_broker_timezone", "mt5_broker_timezone_iana",\n',
 ')\n',
 '\n',
 '_BRIDGE_TIME_KEYS: tuple[str, ...] = (\n',
 '    "validated_doo_bridge_broker_timestamp_20260622", "doo_bridge_broker_timestamp",\n',
 '    "bridge_broker_server_time", "broker_server_timestamp",\n',
 ')\n',
 '_BRIDGE_RECEIPT_KEYS: tuple[str, ...] = (\n',
 '    "validated_doo_bridge_receipt_utc_20260622", "doo_bridge_receipt_utc",\n',
 '    "bridge_receipt_time_utc", "broker_timestamp_received_at_utc",\n',
 ')\n',
 '_PERSISTED_OFFSET_KEYS: tuple[str, ...] = (\n',
 '    "persisted_broker_offset_minutes_20260622", "last_valid_broker_offset_minutes_20260622",\n',
 '    "persisted_broker_utc_offset_hours", "last_valid_broker_utc_offset_hours",\n',
 ')\n',
 '\n',
 '\n',
 'def _as_utc(value: Any) -> pd.Timestamp | None:\n',
 '    if value in (None, ""):\n',
 '        return None\n',
 '    try:\n',
 '        parsed = pd.to_datetime(value, errors="coerce", utc=True)\n',
 '        if isinstance(parsed, pd.Series):\n',
 '            parsed = parsed.dropna().max() if parsed.notna().any() else pd.NaT\n',
 '        elif isinstance(parsed, pd.DatetimeIndex):\n',
 '            parsed = parsed.dropna().max() if len(parsed.dropna()) else pd.NaT\n',
 '        return None if pd.isna(parsed) else pd.Timestamp(parsed).tz_convert("UTC")\n',
 '    except Exception:\n',
 '        return None\n',
 '\n',
 '\n',
 'def _canonical_from_state(state: Mapping[str, Any]) -> Mapping[str, Any]:\n',
 '    try:\n',
 '        from core.canonical_runtime_20260617 import get_canonical\n',
 '        current = get_canonical(state)\n',
 '        if isinstance(current, Mapping):\n',
 '            return current\n',
 '    except Exception:\n',
 '        pass\n',
 '    for key in (\n',
 '        "canonical_result_20260617", "canonical_decision_result_20260617",\n',
 '        "canonical_decision_result", "last_valid_canonical_decision_result_20260617",\n',
 '        "canonical_result",\n',
 '    ):\n',
 '        value = state.get(key)\n',
 '        if isinstance(value, Mapping):\n',
 '            return value\n',
 '    return {}\n',
 '\n',
 '\n',
 'def _state_with_saved_broker_clock(\n',
 '    state: Mapping[str, Any],\n',
 '    canonical: Mapping[str, Any] | None = None,\n',
 ') -> Mapping[str, Any]:\n',
 '    """Recover display-clock evidence from the immutable saved snapshot.\n',
 '\n',
 '    This is presentation-only. It never changes candle identity, calculations,\n',
 '    predictions, decisions, strategy rules, or model weights. Explicit Settings\n',
 '    values remain first priority; saved snapshot evidence is used only when those\n',
 '    values are absent after a Streamlit rerun/navigation.\n',
 '    """\n',
 '    if any(state.get(key) not in (None, "") for key in (*_IANA_KEYS, *_MANUAL_OFFSET_KEYS, '
 '*_PERSISTED_OFFSET_KEYS)):\n',
 '        return state\n',
 '    merged = dict(state)\n',
 '    candidates: list[Mapping[str, Any]] = []\n',
 '    if isinstance(canonical, Mapping):\n',
 '        candidates.append(canonical)\n',
 '    for key in ("canonical_run_snapshot_v9", "canonical_run_contract_v10"):\n',
 '        value = state.get(key)\n',
 '        if isinstance(value, Mapping):\n',
 '            candidates.append(value)\n',
 '    for candidate in candidates:\n',
 '        timezone_name = candidate.get("broker_timezone_iana") or candidate.get("broker_timezone")\n',
 '        if timezone_name not in (None, "", "UNAVAILABLE") and "/" in str(timezone_name):\n',
 '            merged["broker_timezone_iana_20260622"] = str(timezone_name)\n',
 '            return merged\n',
 '        display = str(\n',
 '            candidate.get("shared_broker_time_display")\n',
 '            or candidate.get("broker_time_display")\n',
 '            or candidate.get("broker_candle_time")\n',
 '            or candidate.get("broker_time")\n',
 '            or ""\n',
 '        )\n',
 '        resolution = str(candidate.get("broker_clock_resolution") or candidate.get("resolution_precedence") or '
 '"").lower()\n',
 '        available = candidate.get("broker_clock_available") is True or resolution not in {"", "unavailable", '
 '"none"}\n',
 '        explicit_label = "BROKER UTC" in display.upper() or bool(re.search(r"UTC\\s*[+-]\\s*\\d", str(timezone_name '
 'or ""), re.I))\n',
 '        raw_minutes = candidate.get("broker_offset_minutes")\n',
 '        minutes = _valid_offset_minutes(raw_minutes, value_is_hours=False) if raw_minutes not in (None, "") else '
 'None\n',
 '        if minutes is not None and (available or explicit_label or minutes != 0):\n',
 '            merged["persisted_broker_offset_minutes_20260622"] = minutes\n',
 '            return merged\n',
 '        match = re.search(r"UTC\\s*([+-])\\s*(\\d{1,2})(?::(\\d{2}))?", display, re.I)\n',
 '        if match:\n',
 '            parsed = (int(match.group(2)) * 60 + int(match.group(3) or 0)) * (1 if match.group(1) == "+" else -1)\n',
 '            parsed = _valid_offset_minutes(parsed, value_is_hours=False)\n',
 '            if parsed is not None:\n',
 '                merged["persisted_broker_offset_minutes_20260622"] = parsed\n',
 '                return merged\n',
 '    return merged\n',
 '\n',
 '\n',
 'def _authoritative_time_column(frame: pd.DataFrame) -> str | None:\n',
 '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
 '        return None\n',
 '    for name in _TIME_COLUMNS:\n',
 '        if name in frame.columns:\n',
 '            return name\n',
 '    normalized = {str(c).strip().lower().replace("_", " "): c for c in frame.columns}\n',
 '    for name in _TIME_COLUMNS:\n',
 '        hit = normalized.get(str(name).strip().lower().replace("_", " "))\n',
 '        if hit is not None:\n',
 '            return str(hit)\n',
 '    return None\n',
 '\n',
 '\n',
 'def _frame_time_series(frame: Any) -> pd.Series:\n',
 '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
 '        return pd.Series(dtype="datetime64[ns, UTC]")\n',
 '    col = _authoritative_time_column(frame)\n',
 '    if col is not None:\n',
 '        parsed = pd.to_datetime(frame[col], errors="coerce", utc=True)\n',
 '        return pd.Series(parsed, index=frame.index)\n',
 '    if isinstance(frame.index, pd.DatetimeIndex):\n',
 '        return pd.Series(pd.to_datetime(frame.index, errors="coerce", utc=True), index=frame.index)\n',
 '    if not isinstance(frame.index, pd.RangeIndex):\n',
 '        parsed = pd.to_datetime(frame.index, errors="coerce", utc=True)\n',
 '        if isinstance(parsed, pd.DatetimeIndex) and parsed.notna().any():\n',
 '            return pd.Series(parsed, index=frame.index)\n',
 '    return pd.Series(pd.NaT, index=frame.index, dtype="datetime64[ns, UTC]")\n',
 '\n',
 '\n',
 'def _frame_latest_utc(frame: Any) -> pd.Timestamp | None:\n',
 '    parsed = _frame_time_series(frame).dropna()\n',
 '    return pd.Timestamp(parsed.max()).tz_convert("UTC") if not parsed.empty else None\n',
 '\n',
 '\n',
 'def _valid_offset_minutes(value: Any, *, value_is_hours: bool) -> int | None:\n',
 '    try:\n',
 '        number = float(value)\n',
 '    except Exception:\n',
 '        return None\n',
 '    minutes = int(round(number * 60.0)) if value_is_hours else int(round(number))\n',
 '    return minutes if -12 * 60 <= minutes <= 14 * 60 else None\n',
 '\n',
 '\n',
 'def _first_present(state: Mapping[str, Any], keys: Sequence[str]) -> tuple[str | None, Any]:\n',
 '    for key in keys:\n',
 '        if key in state and state.get(key) not in (None, ""):\n',
 '            return key, state.get(key)\n',
 '    return None, None\n',
 '\n',
 '\n',
 'def _offset_label_minutes(minutes: int | None) -> str:\n',
 '    if minutes is None:\n',
 '        return "UNAVAILABLE"\n',
 '    sign = "+" if minutes >= 0 else "-"\n',
 '    hours, remainder = divmod(abs(int(minutes)), 60)\n',
 '    return f"{sign}{hours}" if remainder == 0 else f"{sign}{hours}:{remainder:02d}"\n',
 '\n',
 '\n',
 'def _fixed_timezone(minutes: int):\n',
 '    return timezone(timedelta(minutes=int(minutes)))\n',
 '\n',
 '\n',
 'def _utc_now_iso() -> str:\n',
 '    """Observation metadata only; never used as a candle identity fallback."""\n',
 '    return pd.Timestamp.now(tz="UTC").isoformat()\n',
 '\n',
 '\n',
 'def _validated_bridge_offset(state: Mapping[str, Any]) -> dict[str, Any]:\n',
 '    """Validate a bridge server timestamp against its UTC receipt observation."""\n',
 '    time_key, server_raw = _first_present(state, _BRIDGE_TIME_KEYS)\n',
 '    receipt_key, receipt_raw = _first_present(state, _BRIDGE_RECEIPT_KEYS)\n',
 '    if time_key is None or receipt_key is None:\n',
 '        return {"available": False, "error": None}\n',
 '    receipt = _as_utc(receipt_raw)\n',
 '    if receipt is None:\n',
 '        return {"available": False, "error": "Bridge receipt UTC is invalid."}\n',
 '    try:\n',
 '        raw = pd.Timestamp(server_raw)\n',
 '    except Exception:\n',
 '        return {"available": False, "error": "Bridge broker-server timestamp is invalid."}\n',
 '    now = pd.Timestamp.now(tz="UTC")\n',
 '    if abs((now - receipt).total_seconds()) > 86400:\n',
 '        return {"available": False, "error": "Bridge broker-clock observation is stale."}\n',
 '    if raw.tzinfo is not None:\n',
 '        offset = raw.utcoffset()\n',
 '        minutes = int(round(offset.total_seconds() / 60.0)) if offset is not None else None\n',
 '        server_utc = raw.tz_convert("UTC")\n',
 '        # Server clock and receipt should describe the same observation within a safe network window.\n',
 '        if abs((server_utc - receipt).total_seconds()) > 900:\n',
 '            return {"available": False, "error": "Bridge broker timestamp differs from UTC receipt by more than 15 '
 'minutes."}\n',
 '    else:\n',
 '        # Naive server timestamps are interpreted only for offset discovery. Round to\n',
 '        # 15 minutes to tolerate network delay while rejecting impossible offsets.\n',
 '        naive_utc_wall = receipt.tz_localize(None)\n',
 '        minutes = int(round((raw - naive_utc_wall).total_seconds() / 900.0) * 15)\n',
 '    minutes = _valid_offset_minutes(minutes, value_is_hours=False)\n',
 '    if minutes is None:\n',
 '        return {"available": False, "error": "Bridge supplied an impossible broker UTC offset."}\n',
 '    return {"available": True, "minutes": minutes, "source_key": time_key, "receipt_key": receipt_key, '
 '"observed_at_utc": receipt.isoformat()}\n',
 '\n',
 '\n',
 'def resolve_broker_clock(\n',
 '    state: Mapping[str, Any],\n',
 '    *,\n',
 '    event_time_utc: Any | None = None,\n',
 '    consolidate_aliases: bool = True,\n',
 ') -> dict[str, Any]:\n',
 '    """Resolve validated bridge > manual offset > IANA timezone > persisted offset.\n',
 '\n',
 '    The returned ``available`` flag must be checked by every display caller.\n',
 '    No zero-offset fallback is provided and impossible bridge offsets are rejected.\n',
 '    """\n',
 '    event = _as_utc(event_time_utc)\n',
 '    if event is None:\n',
 '        return {\n',
 '            "available": False, "status": BROKER_TIME_UNAVAILABLE, "display": BROKER_TIME_UNAVAILABLE,\n',
 '            "broker_offset_minutes": None, "broker_offset_hours": None,\n',
 '            "broker_offset_label": "UNAVAILABLE", "broker_timezone_iana": None,\n',
 '            "broker_tzinfo": None, "resolution_precedence": "unavailable",\n',
 '            "resolution_error": "No canonical completed candle timestamp was supplied.",\n',
 '            "observation_time_utc": None,\n',
 '        }\n',
 '    minutes: int | None = None\n',
 '    timezone_name: str | None = None\n',
 '    precedence = "unavailable"\n',
 '    error: str | None = None\n',
 '    observation_time: str | None = None\n',
 '\n',
 '    bridge = _validated_bridge_offset(state)\n',
 '    if bridge.get("available"):\n',
 '        minutes = int(bridge["minutes"]); precedence = "validated_doo_bridge"; observation_time = '
 'bridge.get("observed_at_utc")\n',
 '    elif bridge.get("error"):\n',
 '        error = str(bridge.get("error"))\n',
 '\n',
 '    if minutes is None:\n',
 '        key, raw = _first_present(state, _MANUAL_OFFSET_KEYS)\n',
 '        if key is not None:\n',
 '            minutes = _valid_offset_minutes(raw, value_is_hours=not key.endswith("minutes_20260622"))\n',
 '            if minutes is not None: precedence = "manual_offset"\n',
 '            else: error = f"Invalid manual broker offset in {key}."\n',
 '\n',
 '    if minutes is None:\n',
 '        tz_key, tz_raw = _first_present(state, _IANA_KEYS)\n',
 '        if tz_key is not None:\n',
 '            timezone_name = str(tz_raw).strip()\n',
 '            try:\n',
 '                zone = ZoneInfo(timezone_name)\n',
 '                offset = event.astimezone(zone).utcoffset()\n',
 '                minutes = int(offset.total_seconds() // 60) if offset is not None else None\n',
 '                if minutes is not None: precedence = "iana_timezone"\n',
 '                else: error = f"Timezone {timezone_name} returned no UTC offset."\n',
 '            except (ZoneInfoNotFoundError, ValueError) as exc:\n',
 '                error = f"Invalid broker timezone {timezone_name}: {exc}"; timezone_name = None\n',
 '\n',
 '    if minutes is None:\n',
 '        persisted_key, persisted_raw = _first_present(state, _PERSISTED_OFFSET_KEYS)\n',
 '        if persisted_key is not None:\n',
 '            minutes = _valid_offset_minutes(persisted_raw, value_is_hours="hours" in persisted_key)\n',
 '            if minutes is not None: precedence = "persisted_offset"\n',
 '            elif error is None: error = f"Invalid persisted broker offset in {persisted_key}."\n',
 '\n',
 '    available = minutes is not None\n',
 '    tzinfo = None\n',
 '    if available:\n',
 '        tzinfo = ZoneInfo(timezone_name) if precedence == "iana_timezone" and timezone_name else '
 '_fixed_timezone(int(minutes))\n',
 '        if consolidate_aliases and isinstance(state, MutableMapping):\n',
 '            state["persisted_broker_offset_minutes_20260622"] = int(minutes)\n',
 '            state["last_valid_broker_offset_minutes_20260622"] = int(minutes)\n',
 '            state["broker_clock_resolution_source_20260622"] = precedence\n',
 '            state["broker_clock_observation_time_utc_20260622"] = observation_time or _utc_now_iso()\n',
 '            # Backward aliases remain synchronized, but never outrank IANA or validated bridge evidence.\n',
 '            hours = float(minutes) / 60.0\n',
 '            state["broker_utc_offset_hours"] = hours\n',
 '            if precedence == "iana_timezone" and timezone_name: state["broker_timezone_iana_20260622"] = '
 'timezone_name\n',
 '    return {\n',
 '        "available": available, "broker_offset_minutes": int(minutes) if minutes is not None else None,\n',
 '        "broker_offset_hours": float(minutes) / 60.0 if minutes is not None else None,\n',
 '        "broker_offset_label": _offset_label_minutes(minutes), "broker_timezone_iana": timezone_name,\n',
 '        "broker_tzinfo": tzinfo, "resolution_precedence": precedence, "resolution_error": error,\n',
 '        "observation_time_utc": observation_time,\n',
 '    }\n',
 '\n',
 '\n',
 'def _canonical_completed_utc(canonical: Mapping[str, Any]) -> pd.Timestamp | None:\n',
 '    market = canonical.get("market") if isinstance(canonical.get("market"), Mapping) else {}\n',
 '    for value in (\n',
 '        canonical.get("event_time_utc"), canonical.get("latest_completed_h1_utc"),\n',
 '        canonical.get("latest_completed_candle_time"), canonical.get("latest_completed_h1"),\n',
 '        canonical.get("anchor_time"), market.get("latest_completed_candle_time"),\n',
 '        market.get("latest_completed_h1"),\n',
 '    ):\n',
 '        parsed = _as_utc(value)\n',
 '        if parsed is not None:\n',
 '            return parsed\n',
 '    return None\n',
 '\n',
 '\n',
 'def _generation(canonical: Mapping[str, Any], state: Mapping[str, Any]) -> Any:\n',
 '    return canonical.get("calculation_generation", state.get("canonical_calculation_generation_20260617", '
 'state.get("calculation_generation")))\n',
 '\n',
 '\n',
 'def _calculation_id(canonical: Mapping[str, Any], state: Mapping[str, Any]) -> Any:\n',
 '    return (\n',
 '        canonical.get("calculation_id") or canonical.get("canonical_calculation_id")\n',
 '        or canonical.get("run_id") or state.get("canonical_calculation_id_20260617")\n',
 '        or state.get("active_calculation_id_20260619")\n',
 '    )\n',
 '\n',
 '\n',
 'def shared_broker_time_provider(\n',
 '    state: Mapping[str, Any],\n',
 '    *,\n',
 '    frame: Any | None = None,\n',
 '    canonical: Mapping[str, Any] | None = None,\n',
 ') -> dict[str, Any]:\n',
 '    """Return the complete canonical market-time contract."""\n',
 '    canonical = canonical if isinstance(canonical, Mapping) else _canonical_from_state(state)\n',
 '    canonical_utc = _canonical_completed_utc(canonical)\n',
 '    # A restored session can contain an old canonical generation while MT5/API\n',
 '    # data has already advanced.  Select the freshest authoritative candle\n',
 '    # timestamp across the canonical object and loaded market frames.  This is\n',
 '    # a clock/watermark repair only; it never recalculates trading scores.\n',
 '    frame_candidates = []\n',
 '    if isinstance(frame, pd.DataFrame):\n',
 '        frame_candidates.append(("explicit_frame", frame))\n',
 '    for key in (\n',
 '        "canonical_completed_ohlc_df_20260617", "last_df", "dv_pp_df", "custom_h1_df",\n',
 '        "home_df", "prepared_lunch_df", "lunch_visual_df", "live_df", "shared_df",\n',
 '        "market_df", "eurusd_h1_df", "lunch_df", "full_metric_history_df_20260618",\n',
 '    ):\n',
 '        value = state.get(key)\n',
 '        if isinstance(value, pd.DataFrame) and not value.empty:\n',
 '            frame_candidates.append((key, value))\n',
 '    loaded = [(name, _frame_latest_utc(value)) for name, value in frame_candidates]\n',
 '    loaded = [(name, stamp) for name, stamp in loaded if stamp is not None]\n',
 '    newest_loaded = max(loaded, key=lambda item: item[1]) if loaded else (None, None)\n',
 '    completed_utc = canonical_utc\n',
 '    timestamp_source = "canonical_completed_h1" if canonical_utc is not None else "unavailable"\n',
 '    if newest_loaded[1] is not None and (completed_utc is None or newest_loaded[1] > completed_utc):\n',
 '        completed_utc = newest_loaded[1]\n',
 '        timestamp_source = f"freshest_loaded_candle:{newest_loaded[0]}"\n',
 '\n',
 '    resolution_state = _state_with_saved_broker_clock(state, canonical)\n',
 '    clock = resolve_broker_clock(resolution_state, event_time_utc=completed_utc)\n',
 '    if clock.get("available") and isinstance(state, MutableMapping):\n',
 '        minutes = clock.get("broker_offset_minutes")\n',
 '        if minutes is not None:\n',
 '            state.setdefault("persisted_broker_offset_minutes_20260622", int(minutes))\n',
 '            state.setdefault("last_valid_broker_offset_minutes_20260622", int(minutes))\n',
 '    tzinfo = clock.get("broker_tzinfo")\n',
 '    broker_time = completed_utc.tz_convert(tzinfo) if completed_utc is not None and tzinfo is not None else None\n',
 '    myanmar_time = completed_utc.tz_convert(_fixed_timezone(390)) if completed_utc is not None else None\n',
 '    label = clock.get("broker_offset_label")\n',
 '    market = canonical.get("market") if isinstance(canonical.get("market"), Mapping) else {}\n',
 '    quality = canonical.get("data_quality") if isinstance(canonical.get("data_quality"), Mapping) else {}\n',
 '    processing = pd.Timestamp.now(tz="UTC")\n',
 '    lag = max(0.0, (processing - completed_utc).total_seconds() / 60.0) if completed_utc is not None else None\n',
 '    broker_display = (\n',
 '        broker_time.strftime("%Y-%m-%d %H:%M:%S") + f" (Broker UTC{label})"\n',
 '        if broker_time is not None else BROKER_TIME_UNAVAILABLE\n',
 '    )\n',
 '    source = canonical.get("source") or market.get("source") or timestamp_source\n',
 '    watermark_status = "AVAILABLE" if completed_utc is not None else "UNAVAILABLE"\n',
 '    if completed_utc is not None and lag is not None and lag > 180:\n',
 '        watermark_status = "STALE"\n',
 '    return {\n',
 '        "event_time_utc": completed_utc.isoformat() if completed_utc is not None else None,\n',
 '        "latest_completed_h1_utc": completed_utc.isoformat() if completed_utc is not None else None,\n',
 '        "latest_broker_candle_utc": completed_utc,\n',
 '        "latest_broker_candle_utc_iso": completed_utc.isoformat() if completed_utc is not None else None,\n',
 '        "shared_broker_time": broker_time,\n',
 '        "shared_broker_time_iso": broker_time.isoformat() if broker_time is not None else None,\n',
 '        "shared_broker_time_display": broker_display,\n',
 '        "latest_broker_candle_timestamp": broker_time,\n',
 '        "broker_time": broker_time,\n',
 '        "broker_time_display": broker_display,\n',
 '        "broker_hour": broker_time.strftime("%H:00") if broker_time is not None else BROKER_TIME_UNAVAILABLE,\n',
 '        "broker_date": broker_time.strftime("%Y-%m-%d") if broker_time is not None else BROKER_TIME_UNAVAILABLE,\n',
 '        "broker_weekday": broker_time.strftime("%A") if broker_time is not None else BROKER_TIME_UNAVAILABLE,\n',
 '        "myanmar_time": myanmar_time,\n',
 '        "myanmar_time_display": myanmar_time.strftime("%Y-%m-%d %H:%M:%S (Myanmar UTC+6:30)") if myanmar_time is not '
 'None else "UNAVAILABLE",\n',
 '        "broker_offset_minutes": clock.get("broker_offset_minutes"),\n',
 '        "broker_offset_hours": clock.get("broker_offset_hours"),\n',
 '        "broker_offset_label": label,\n',
 '        "broker_timezone_iana": clock.get("broker_timezone_iana"),\n',
 '        "broker_clock_available": bool(clock.get("available")),\n',
 '        "broker_clock_resolution": clock.get("resolution_precedence"),\n',
 '        "broker_clock_error": clock.get("resolution_error"),\n',
 '        "broker_clock_observation_time_utc": clock.get("observation_time_utc"),\n',
 '        "contract_version": CONTRACT_VERSION,\n',
 '        "calculation_id": _calculation_id(canonical, state),\n',
 '        "calculation_generation": _generation(canonical, state),\n',
 '        "source": source,\n',
 '        "symbol": canonical.get("symbol") or state.get("symbol") or "EURUSD",\n',
 '        "timeframe": canonical.get("timeframe") or state.get("timeframe") or "H1",\n',
 '        "ingested_at_utc": canonical.get("ingested_at_utc") or canonical.get("created_at"),\n',
 '        "processing_time_utc": processing.isoformat(),\n',
 '        "watermark_status": watermark_status,\n',
 '        "freshness_lag_minutes": round(lag, 2) if lag is not None else None,\n',
 '        "timestamp_source": timestamp_source,\n',
 '        "contract_version": CONTRACT_VERSION,\n',
 '        "is_completed_candle": completed_utc is not None,\n',
 '        "data_quality_status": quality.get("quality_status") or quality.get("status") or '
 'canonical.get("data_quality_status") or "UNAVAILABLE",\n',
 '    }\n',
 '\n',
 '\n',
 'def frame_to_shared_broker_clock(\n',
 '    frame: pd.DataFrame,\n',
 '    state: Mapping[str, Any],\n',
 '    *,\n',
 '    canonical: Mapping[str, Any] | None = None,\n',
 '    include_myanmar: bool = True,\n',
 '    reject_future_incomplete: bool = True,\n',
 '    hide_raw_utc: bool = True,\n',
 ') -> pd.DataFrame:\n',
 '    """Create a newest-first display projection from canonical UTC event times."""\n',
 '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
 '        return frame\n',
 '    work = frame.copy(deep=False)\n',
 '    time_col = _authoritative_time_column(work)\n',
 '    if time_col is None and isinstance(work.index, pd.DatetimeIndex):\n',
 '        index_name = work.index.name or "event_time_utc"\n',
 '        work = work.reset_index().rename(columns={index_name: "event_time_utc", "index": "event_time_utc"})\n',
 '        time_col = "event_time_utc"\n',
 '    if time_col is None:\n',
 '        return work\n',
 '    parsed = pd.to_datetime(work[time_col], errors="coerce", utc=True)\n',
 '    work = work.loc[parsed.notna()].copy()\n',
 '    parsed = parsed.loc[work.index]\n',
 '    if work.empty:\n',
 '        return work.reset_index(drop=True)\n',
 '\n',
 '    # The frame itself is authoritative evidence. Passing it into the provider\n',
 '    # prevents an old restored canonical object from filtering out newer completed\n',
 '    # rows that are already present in the table being rendered.\n',
 '    contract = shared_broker_time_provider(state, frame=work, canonical=canonical)\n',
 '    watermark = _as_utc(contract.get("latest_completed_h1_utc"))\n',
 '    if reject_future_incomplete and watermark is not None:\n',
 '        keep = parsed.le(watermark)\n',
 '        work = work.loc[keep].copy()\n',
 '        parsed = parsed.loc[keep]\n',
 '    if work.empty:\n',
 '        return work.reset_index(drop=True)\n',
 '\n',
 '    work["__event_time_utc"] = parsed\n',
 '    # Preserve caller order; history query layers own newest-first ordering.\n',
 '    parsed = work["__event_time_utc"]\n',
 '    position = list(work.columns).index(time_col) if time_col in work.columns else 0\n',
 '    if hide_raw_utc and time_col in work.columns:\n',
 '        work = work.drop(columns=[time_col])\n',
 '\n',
 '    if not contract.get("broker_clock_available"):\n',
 '        broker_col = "Broker Time"\n',
 '        work.insert(min(position, len(work.columns)), broker_col, BROKER_TIME_UNAVAILABLE)\n',
 '        if include_myanmar:\n',
 '            myanmar = parsed.dt.tz_convert(_fixed_timezone(390)).dt.strftime("%Y-%m-%d %H:%M:%S")\n',
 '            work.insert(min(position + 1, len(work.columns)), "Myanmar Time (UTC+6:30)", myanmar)\n',
 '        # Never corrupt usable history dates with a configuration warning. When\n',
 '        # broker offset evidence is temporarily unavailable after navigation,\n',
 '        # preserve canonical candle identity and rebuild visible calendar fields\n',
 '        # from the authoritative UTC event timestamp. The Broker Time column stays\n',
 '        # explicit about the missing offset; no broker time is guessed.\n',
 '        canonical_utc = parsed.dt.tz_convert("UTC")\n',
 '        work["Date"] = canonical_utc.dt.strftime("%Y-%m-%d")\n',
 '        work["Weekday"] = canonical_utc.dt.strftime("%A")\n',
 '        work["Hour"] = canonical_utc.dt.strftime("%H:00")\n',
 '        # Repeated display projections must not leave a second stale time alias.\n',
 '        for column in list(work.columns):\n',
 '            normalized = str(column).strip().lower().replace("_", " ")\n',
 '            if normalized in _DISPLAY_CLOCK_ALIASES and column != broker_col:\n',
 '                work[column] = canonical_utc.dt.tz_localize(None)\n',
 '    else:\n',
 '        resolution_state = _state_with_saved_broker_clock(state, canonical if isinstance(canonical, Mapping) else '
 '_canonical_from_state(state))\n',
 '        tzinfo = resolve_broker_clock(resolution_state, event_time_utc=watermark).get("broker_tzinfo")\n',
 '        broker = parsed.dt.tz_convert(tzinfo)\n',
 '        label = str(contract.get("broker_offset_label"))\n',
 '        broker_col = f"Broker Time (UTC{label})"\n',
 '        work.insert(min(position, len(work.columns)), broker_col, broker.dt.tz_localize(None))\n',
 '        if include_myanmar:\n',
 '            myanmar = parsed.dt.tz_convert(_fixed_timezone(390)).dt.tz_localize(None)\n',
 '            work.insert(min(position + 1, len(work.columns)), "Myanmar Time (UTC+6:30)", myanmar)\n',
 '        # Always rebuild these visible fields from broker time, even when they\n',
 '        # already existed with stale UTC-derived values.\n',
 '        work["Date"] = broker.dt.strftime("%Y-%m-%d")\n',
 '        work["Weekday"] = broker.dt.strftime("%A")\n',
 '        work["Hour"] = broker.dt.strftime("%H:00")\n',
 '        # Every visible candle-time alias is rebuilt from the same broker-aware\n',
 '        # timestamp. This prevents Date/Hour/Completed Candle disagreements.\n',
 '        for column in list(work.columns):\n',
 '            normalized = str(column).strip().lower().replace("_", " ")\n',
 '            if normalized in _DISPLAY_CLOCK_ALIASES and column != broker_col:\n',
 '                work[column] = broker.dt.tz_localize(None)\n',
 '    work = work.drop(columns=["__event_time_utc"], errors="ignore")\n',
 '    return work.reset_index(drop=True)\n',
 '\n',
 '\n',
 'def latest_history_utc(frame: Any) -> pd.Timestamp | None:\n',
 '    return _frame_latest_utc(frame)\n',
 '\n',
 '\n',
 'def _single_column_identity(frame: Any, names: Sequence[str]) -> set[str]:\n',
 '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
 '        return set()\n',
 '    normalized = {str(c).strip().lower(): c for c in frame.columns}\n',
 '    for name in names:\n',
 '        col = normalized.get(name.lower())\n',
 '        if col is not None:\n',
 '            return {str(v) for v in frame[col].dropna().astype(str).unique()}\n',
 '    return set()\n',
 '\n',
 '\n']
