"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = ['def history_sync_status(\n',
 '    state: Mapping[str, Any],\n',
 '    *,\n',
 '    history_frame: Any | None = None,\n',
 '    canonical: Mapping[str, Any] | None = None,\n',
 ') -> dict[str, Any]:\n',
 '    """Validate timestamp, calculation, generation, offset, source and contract."""\n',
 '    clock = shared_broker_time_provider(state, frame=history_frame, canonical=canonical)\n',
 '    expected = _as_utc(clock.get("latest_completed_h1_utc"))\n',
 '    actual = latest_history_utc(history_frame)\n',
 '    difference = abs((actual - expected).total_seconds()) / 60.0 if actual is not None and expected is not None else '
 'None\n',
 '    expected_calc = str(clock.get("calculation_id"))\n',
 '    expected_gen = str(clock.get("calculation_generation"))\n',
 '    expected_offset = str(clock.get("broker_offset_minutes"))\n',
 '    expected_source = str(clock.get("source"))\n',
 '    calc_values = _single_column_identity(history_frame, ("calculation_id", "canonical_calculation_id", "run_id"))\n',
 '    gen_values = _single_column_identity(history_frame, ("generation", "calculation_generation"))\n',
 '    offset_values = _single_column_identity(history_frame, ("broker_offset_minutes",))\n',
 '    source_values = _single_column_identity(history_frame, ("source",))\n',
 '    contract_values = _single_column_identity(history_frame, ("contract_version", "timestamp_contract_version"))\n',
 '    calc_match = not calc_values or calc_values == {expected_calc}\n',
 '    gen_match = not gen_values or gen_values == {expected_gen}\n',
 '    offset_match = not offset_values or offset_values == {expected_offset}\n',
 '    source_match = not source_values or source_values == {expected_source}\n',
 '    contract_match = not contract_values or contract_values == {CONTRACT_VERSION}\n',
 '    timestamp_match = difference is not None and difference < 1.0\n',
 '    if expected is None:\n',
 '        status, reason = "UNAVAILABLE", "No canonical completed-H1 watermark is published."\n',
 '    elif not clock.get("broker_clock_available"):\n',
 '        status, reason = "UNAVAILABLE", BROKER_TIME_UNAVAILABLE\n',
 '    elif actual is None:\n',
 '        status, reason = "STALE", "No authoritative history timestamp is available."\n',
 '    elif timestamp_match and calc_match and gen_match and offset_match and source_match and contract_match:\n',
 '        status, reason = "SYNCED", "Timestamp, calculation ID, generation, broker clock, source and contract '
 'match."\n',
 '    elif difference is not None and difference > 0 and calc_match and gen_match and offset_match and source_match:\n',
 '        status, reason = "STALE", "History watermark differs from the active completed-H1 watermark."\n',
 '    else:\n',
 '        status, reason = "OUT OF SYNC", "One or more generation/identity/broker-contract checks failed."\n',
 '    resolution_state = _state_with_saved_broker_clock(state, canonical if isinstance(canonical, Mapping) else '
 '_canonical_from_state(state))\n',
 '    tzinfo = resolve_broker_clock(resolution_state, event_time_utc=actual).get("broker_tzinfo")\n',
 '    actual_broker = actual.tz_convert(tzinfo) if actual is not None and tzinfo is not None else None\n',
 '    return {\n',
 '        **clock,\n',
 '        "status": status,\n',
 '        "status_code": status.replace(" ", "_"),\n',
 '        "synced": status == "SYNCED",\n',
 '        "latest_history_record_utc": actual,\n',
 '        "latest_history_record_utc_iso": actual.isoformat() if actual is not None else None,\n',
 '        "latest_history_record": actual_broker,\n',
 '        "latest_history_record_display": (\n',
 '            actual_broker.strftime("%Y-%m-%d %H:%M:%S") + f" (Broker UTC{clock.get(\'broker_offset_label\')})"\n',
 '            if actual_broker is not None else (BROKER_TIME_UNAVAILABLE if actual is not None else "Not available")\n',
 '        ),\n',
 '        "difference_minutes": round(difference, 2) if difference is not None else None,\n',
 '        "difference_in_minutes": round(difference, 2) if difference is not None else None,\n',
 '        "canonical_latest_completed_h1_utc": clock.get("latest_completed_h1_utc"),\n',
 '        "displayed_broker_candle_time": clock.get("broker_time_display"),\n',
 '        "displayed_myanmar_candle_time": clock.get("myanmar_time_display"),\n',
 '        "latest_field1_history_utc": actual.isoformat() if actual is not None else None,\n',
 '        "latest_field6_history_utc": None,\n',
 '        "calculation_id_match": calc_match,\n',
 '        "generation_match": gen_match,\n',
 '        "broker_offset_match": offset_match,\n',
 '        "source_match": source_match,\n',
 '        "contract_version_match": contract_match,\n',
 '        "timestamp_match": timestamp_match,\n',
 '        "reason": reason,\n',
 '    }\n',
 '\n',
 '\n',
 '__all__ = [\n',
 '    "CONTRACT_VERSION", "BROKER_TIME_UNAVAILABLE", "resolve_broker_clock",\n',
 '    "shared_broker_time_provider", "frame_to_shared_broker_clock",\n',
 '    "history_sync_status", "latest_history_utc",\n',
 ']\n']
