"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Lightweight advanced analytics add-ons for ADX Quant Pro (2026-06-15).\n',
    '\n',
    'Non-destructive display helpers only.  They read existing session dataframe,\n',
    'regime context, prediction/error caches, and AI context.  No new tab, no new ML\n',
    'engine, no external API, and no heavy model is created here.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import math\n',
    'from statistics import NormalDist\n',
    'from typing import Any, Dict, Iterable, List, Optional, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    'import streamlit as st\n',
    '\n',
    'UNIQUE = "20260615_adv_analytics"\n',
    '\n',
    '\n',
    'def _num(v: Any, default: float = 0.0) -> float:\n',
    '    try:\n',
    '        if v is None or v == "":\n',
    '            return float(default)\n',
    '        x = float(v)\n',
    '        return x if math.isfinite(x) else float(default)\n',
    '    except Exception:\n',
    '        return float(default)\n',
    '\n',
    '\n',
    'def _clip(v: Any, lo: float = 0.0, hi: float = 100.0) -> float:\n',
    '    return float(max(lo, min(hi, _num(v, lo))))\n',
    '\n',
    '\n',
    'def _norm_col(v: Any) -> str:\n',
    '    return "".join(ch for ch in str(v).lower() if ch.isalnum())\n',
    '\n',
    '\n',
    'def _find_col(df: pd.DataFrame, aliases: Iterable[str]) -> Optional[str]:\n',
    '    if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '        return None\n',
    '    nmap = {_norm_col(c): c for c in df.columns}\n',
    '    for a in aliases:\n',
    '        na = _norm_col(a)\n',
    '        if na in nmap:\n',
    '            return nmap[na]\n',
    '    for nk, col in nmap.items():\n',
    '        for a in aliases:\n',
    '            na = _norm_col(a)\n',
    '            if na and na in nk:\n',
    '                return col\n',
    '    return None\n',
    '\n',
    '\n',
    'def get_market_df(limit: int = 5000) -> pd.DataFrame:\n',
    '    """Return a normalized OHLC dataframe from existing session_state caches."""\n',
    '    for key in [\n',
    '        "dv_pp_df", "last_df", "live_df", "shared_df", "cached_df",\n',
    '        "market_df", "eurusd_h1_df", "lunch_df",\n',
    '    ]:\n',
    '        raw = st.session_state.get(key)\n',
    '        if isinstance(raw, pd.DataFrame) and not raw.empty:\n',
    '            d = raw.copy().tail(int(limit)).reset_index(drop=True)\n',
    '            break\n',
    '    else:\n',
    '        return pd.DataFrame()\n',
    '\n',
    '    low = {str(c).lower().strip(): c for c in d.columns}\n',
    '    rename_map = {\n',
    '        "datetime": "time", "date": "time", "timestamp": "time", "timeopen": "time",\n',
    '        "o": "open", "h": "high", "l": "low", "c": "close",\n',
    '    }\n',
    '    for src, dst in rename_map.items():\n',
    '        if src in low and dst not in d.columns:\n',
    '            d = d.rename(columns={low[src]: dst})\n',
    '    if "time" not in d.columns:\n',
    '        d["time"] = pd.date_range(end=pd.Timestamp.now().floor("h"), periods=len(d), freq="h")\n',
    '    for col in ["open", "high", "low", "close"]:\n',
    '        if col not in d.columns:\n',
    '            d[col] = d.get("close", np.nan)\n',
    '        d[col] = pd.to_numeric(d[col], errors="coerce")\n',
    '    d["time"] = pd.to_datetime(d["time"], errors="coerce")\n',
    '    d = d.dropna(subset=["time", "close"]).sort_values("time").drop_duplicates("time", keep="last")\n',
    '    return d.reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _feature_frame(d: pd.DataFrame) -> pd.DataFrame:\n',
    '    if not isinstance(d, pd.DataFrame) or d.empty:\n',
    '        return pd.DataFrame()\n',
    '    x = d.copy().reset_index(drop=True)\n',
    '    close = pd.to_numeric(x["close"], errors="coerce").astype(float)\n',
    '    x["ret1"] = close.pct_change().fillna(0.0)\n',
    '    x["move_pips"] = close.diff().fillna(0.0) * 10000.0\n',
    '    x["abs_move_pips"] = x["move_pips"].abs()\n',
    '    x["range_pips"] = (pd.to_numeric(x["high"], errors="coerce") - pd.to_numeric(x["low"], errors="coerce")).abs().fillna(0.0) * 10000.0\n',
    '    x["ma12"] = close.rolling(12, min_periods=3).mean()\n',
    '    x["ma48"] = close.rolling(48, min_periods=10).mean()\n',
    '    x["trend_gap_pips"] = (x["ma12"] - x["ma48"]).fillna(0.0) * 10000.0\n',
    '    x["vol24_pips"] = x["move_pips"].rolling(24, min_periods=6).std().fillna(x["move_pips"].abs().expanding().mean())\n',
    '    x["hour"] = pd.to_datetime(x["time"]).dt.hour\n',
    '    x["day_name"] = pd.to_datetime(x["time"]).dt.day_name().str[:3]\n',
    '    x["direction"] = np.where(x["move_pips"] > 0, "BUY", np.where(x["move_pips"] < 0, "SELL", "WAIT"))\n',
    '    x["regime_direction"] = np.where(x["ma12"] > x["ma48"], "BULL", np.where(x["ma12"] < x["ma48"], "BEAR", "RANGE"))\n',
    '    try:\n',
    '        vol_q = pd.qcut(x["vol24_pips"].rank(method="first"), 3, labels=["Low Vol", "Mid Vol", "High Vol"])\n',
    '        x["vol_bucket"] = vol_q.astype(str)\n',
    '    except Exception:\n',
    '        x["vol_bucket"] = "Mid Vol"\n',
    '    try:\n',
    '        trend_abs = x["trend_gap_pips"].abs()\n',
    '        x["trend_bucket"] = pd.qcut(trend_abs.rank(method="first"), 3, labels=["Flat", "Normal", "Strong"]).astype(str)\n',
    '    except Exception:\n',
    '        x["trend_bucket"] = "Normal"\n',
    '    return x.dropna(subset=["time", "close"]).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _regime_score(value: Any) -> float:\n',
    '    s = str(value or "").upper()\n',
    '    if "BULL" in s or s == "BUY":\n',
    '        return 1.0\n',
    '    if "BEAR" in s or s == "SELL":\n',
    '        return -1.0\n',
    '    if "RANGE" in s or "WAIT" in s:\n',
    '        return 0.0\n',
    '    return _num(value, 0.0)\n',
    '\n',
    '\n',
    'def _safe_ratio(now: float, prev: float) -> float:\n',
    '    if abs(prev) < 1e-12:\n',
    '        return 0.0\n',
    '    return float(now / prev)\n',
    '\n',
    '\n',
    'def _fmt_pct(v: Any) -> str:\n',
    '    return f"{_num(v):.1f}%"\n',
    '\n',
    '\n',
    'def build_diagnostic_analysis_table(df: Optional[pd.DataFrame] = None) -> pd.DataFrame:\n',
    '    d = get_market_df(3000) if df is None else df.copy()\n',
    '    x = _feature_frame(d)\n',
    '    if x.empty:\n',
    '        return pd.DataFrame([{\n',
    '            "Diagnostic Area": "Data availability",\n',
    '            "Cause Found": "No usable OHLC data in session_state",\n',
    '            "Evidence": "Rows = 0",\n',
    '            "Impact": "Cannot diagnose regime, volatility, error, or priority.",\n',
    '            "Action / Fix": "Load/connect data, then press Run Calculation.",\n',
    '            "Severity": "HIGH",\n',
    '        }])\n',
    '    last = x.iloc[-1]\n',
    '    ret24 = float(x["move_pips"].tail(24).sum()) if len(x) else 0.0\n',
    '    vol_now = float(x["vol24_pips"].tail(1).iloc[0]) if len(x) else 0.0\n',
    '    vol_med = float(x["vol24_pips"].tail(240).median()) if len(x) else 0.0\n',
    '    range_now = float(x["range_pips"].tail(24).mean()) if len(x) else 0.0\n',
    '    trend_gap = float(last.get("trend_gap_pips", 0.0))\n',
    '\n',
    '    bt = st.session_state.get("dv_pp_bt_summary", {})\n',
    '    err_pct = _num(bt.get("avg_abs_close_error_pct", 0) if isinstance(bt, dict) else 0, 0)\n',
    '    acc_pct = _num(bt.get("direction_accuracy_pct", 0) if isinstance(bt, dict) else 0, 0)\n',
    '    q = st.session_state.get("last_data_quality", {})\n',
    '    data_score = _num(q.get("score", q.get("Data Quality Score", 0)) if isinstance(q, dict) else 0, 0)\n',
    '    regime = st.session_state.get("current_regime") or st.session_state.get("master_regime") or str(last.get("regime_direction", "RANGE"))\n',
    '    rctx = st.session_state.get("regime_context_20260614", {})\n',
    '    shift = 0.0\n',
    '    rel = 0.0\n',
    '    if isinstance(rctx, dict):\n',
    '        metrics = rctx.get("metrics", {}) if isinstance(rctx.get("metrics", {}), dict) else rctx\n',
    '        shift = _num(metrics.get("Transition Risk %", metrics.get("Shift Risk", 0)), 0)\n',
    '        rel = _num(metrics.get("Regime Reliable Score", metrics.get("Regime Reliability", 0)), 0)\n',
    '\n',
    '    rows = [\n',
    '        {\n',
    '            "Diagnostic Area": "Trend driver",\n',
    '            "Cause Found": "MA12 above MA48" if trend_gap > 0 else "MA12 below MA48" if trend_gap < 0 else "MA12/MA48 flat",\n',
    '            "Evidence": f"Trend gap {trend_gap:.2f} pips; 24H net {ret24:.2f} pips",\n',
    '            "Impact": "Directional bias can dominate entries." if abs(trend_gap) >= 2 else "Trend is weak; prediction can flip faster.",\n',
    '            "Action / Fix": "Require regime + priority sync before entry.",\n',
    '            "Severity": "MEDIUM" if abs(trend_gap) >= 2 else "LOW",\n',
    '        },\n',
    '        {\n',
    '            "Diagnostic Area": "Volatility / heat",\n',
    '            "Cause Found": "Volatility above recent median" if vol_now > vol_med * 1.15 else "Volatility normal/compressed",\n',
    '            "Evidence": f"Vol24 {vol_now:.2f} pips vs median {vol_med:.2f}; avg range {range_now:.2f} pips",\n',
    '            "Impact": "TP/SL error risk increases." if vol_now > vol_med * 1.15 else "Lower movement but less phone/system stress.",\n',
    '            "Action / Fix": "Use run-gated views; avoid auto-refreshing heavy charts.",\n',
    '            "Severity": "HIGH" if vol_now > vol_med * 1.6 else "MEDIUM" if vol_now > vol_med * 1.15 else "LOW",\n',
    '        },\n',
    '        {\n',
    '            "Diagnostic Area": "Regime conflict / transition",\n',
    '            "Cause Found": f"Current regime {regime}",\n',
    '            "Evidence": f"Reliability {rel:.1f}%; shift risk {shift:.1f}%",\n',
    '            "Impact": "Regime may change; priority should wait." if shift >= 55 or rel < 55 else "Regime state is usable for confirmation.",\n',
    '            "Action / Fix": "Use alpha/delta regime metrics and resolver before trusting one label.",\n',
    '            "Severity": "HIGH" if shift >= 60 or rel < 45 else "MEDIUM" if shift >= 45 or rel < 60 else "LOW",\n',
    '        },\n',
    '        {\n',
    '            "Diagnostic Area": "Prediction error",\n',
    '            "Cause Found": "Backtest/error cache found" if err_pct or acc_pct else "Prediction error cache not ready",\n',
    '            "Evidence": f"Avg abs close error {err_pct:.4f}%; direction accuracy {acc_pct:.2f}%",\n',
    '            "Impact": "Projection should be treated as low confidence." if err_pct > 0.08 or (acc_pct and acc_pct < 50) else "Projection quality acceptable if regime agrees.",\n',
    '            "Action / Fix": "Show confidence, error, freshness, alpha point, and delta point together.",\n',
    '            "Severity": "HIGH" if err_pct > 0.12 else "MEDIUM" if err_pct > 0.06 else "LOW",\n',
    '        },\n',
    '        {\n',
    '            "Diagnostic Area": "Data quality",\n',
    '            "Cause Found": "Session dataframe available",\n',
    '            "Evidence": f"Rows {len(x):,}; data quality score {data_score:.1f}",\n',
    '            "Impact": "Missing/low quality rows can make analysis unreliable." if data_score and data_score < 60 else "Enough data for lightweight diagnostics.",\n',
    '            "Action / Fix": "Keep calculations manually run-gated and cache results.",\n',
    '            "Severity": "MEDIUM" if data_score and data_score < 60 else "LOW",\n',
    '        },\n',
    '    ]\n',
    '    return pd.DataFrame(rows)\n',
    '\n',
    '\n',
    'def build_sampling_estimating_hypothesis_tables(df: Optional[pd.DataFrame] = None) -> Dict[str, pd.DataFrame]:\n',
    '    d = get_market_df(4000) if df is None else df.copy()\n',
    '    x = _feature_frame(d)\n',
    '    if x.empty or len(x) < 20:\n',
    '        return {"sampling": pd.DataFrame(), "estimating": pd.DataFrame(), "hypothesis": pd.DataFrame()}\n',
    '    x = x.tail(1500).copy()\n',
    '    # Sampling: deterministic stratified sample by session/hour buckets; no random CPU-heavy work.\n',
    '    bins = pd.cut(x["hour"], bins=[-1, 5, 11, 17, 23], labels=["Asia 00-05", "EU 06-11", "NY 12-17", "Late 18-23"])\n',
    '    x["session_bucket"] = bins.astype(str)\n',
    '    sampling = x.groupby("session_bucket", dropna=False).agg(\n',
    '        Sample_Size=("move_pips", "size"),\n',
    '        Avg_Move_Pips=("move_pips", "mean"),\n',
    '        Avg_Abs_Move_Pips=("abs_move_pips", "mean"),\n',
    '        Up_Rate_Pct=("move_pips", lambda s: float((s > 0).mean() * 100)),\n',
    '        Avg_Range_Pips=("range_pips", "mean"),\n',
    '    ).reset_index().rename(columns={"session_bucket": "Sampling Stratum"})\n',
    '    for col in ["Avg_Move_Pips", "Avg_Abs_Move_Pips", "Up_Rate_Pct", "Avg_Range_Pips"]:\n',
    '        sampling[col] = pd.to_numeric(sampling[col], errors="coerce").round(3)\n',
    '\n',
    '    ret = x["move_pips"].dropna().astype(float)\n',
    '    n = int(len(ret))\n',
    '    mean = float(ret.mean()) if n else 0.0\n',
    '    std = float(ret.std(ddof=1)) if n > 1 else 0.0\n',
    '    se = std / math.sqrt(max(n, 1))\n',
    '    ci = 1.96 * se\n',
    '    estimating = pd.DataFrame([\n',
    '        {"Estimate": "Mean H1 move", "Value": round(mean, 4), "Lower 95%": round(mean - ci, 4), "Upper 95%": round(mean + ci, 4), "Sample Size": n},\n',
    '        {"Estimate": "Mean absolute H1 move", "Value": round(float(ret.abs().mean()), 4), "Lower 95%": "-", "Upper 95%": "-", "Sample Size": n},\n',
    '        {"Estimate": "Expected range pips", "Value": round(float(x["range_pips"].mean()), 4), "Lower 95%": "-", "Upper 95%": "-", "Sample Size": n},\n',
    '    ])\n',
    '    z = mean / se if se > 1e-12 else 0.0\n',
    '    try:\n',
    '        p = 2 * (1 - NormalDist().cdf(abs(z)))\n',
    '    except Exception:\n',
    '        p = 1.0\n',
    '    hypothesis = pd.DataFrame([\n',
    '        {\n',
    '            "Hypothesis Test": "H0: average H1 move = 0 pips",\n',
    '            "Statistic": round(z, 4),\n',
    '            "p_value_approx": round(float(p), 5),\n',
    '            "Decision": "Reject H0: directional drift exists" if p < 0.05 else "Do not reject H0: drift not strong",\n',
    '            "Trading Meaning": "Use trend/regime confirmation" if p < 0.05 else "Avoid forcing direction from mean alone",\n',
    '        },\n',
    '        {\n',
    '            "Hypothesis Test": "H0: high-volatility hours are not larger than normal hours",\n',
    '            "Statistic": round(float(x.loc[x["vol_bucket"] == "High Vol", "abs_move_pips"].mean() - x["abs_move_pips"].mean()), 4),\n',
    '            "p_value_approx": "effect-size only",\n',
    '            "Decision": "High-vol hours move more" if float(x.loc[x["vol_bucket"] == "High Vol", "abs_move_pips"].mean()) > float(x["abs_move_pips"].mean()) else "No high-vol advantage",\n',
    '            "Trading Meaning": "More TP opportunity but more exit risk" if float(x.loc[x["vol_bucket"] == "High Vol", "abs_move_pips"].mean()) > float(x["abs_move_pips"].mean()) else "Use normal priority rules",\n',
    '        },\n',
    '    ])\n',
    '    return {"sampling": sampling, "estimating": estimating, "hypothesis": hypothesis}\n',
    '\n',
    '\n',
    'def build_data_mining_extension_tables(df: Optional[pd.DataFrame] = None) -> Dict[str, pd.DataFrame]:\n',
    '    d = get_market_df(4000) if df is None else df.copy()\n',
    '    x = _feature_frame(d)\n',
    '    if x.empty or len(x) < 40:\n',
    '        empty = pd.DataFrame()\n',
    '        return {"pattern": empty, "cluster": empty, "association": empty, "anomaly": empty, "cube": empty}\n',
    '    x = x.tail(1800).copy()\n',
    '\n',
    '    # Pattern evaluation.\n',
    '    x["prev_direction"] = x["direction"].shift(1).fillna("WAIT")\n',
    '    x["momentum_hit"] = x["direction"] == x["prev_direction"]\n',
    '    x["reversal_hit"] = (x["direction"] != x["prev_direction"]) & (x["direction"] != "WAIT") & (x["prev_direction"] != "WAIT")\n',
    '    pattern = pd.DataFrame([\n',
    '        {"Pattern Evaluation": "Momentum continuation", "Hit Rate %": round(float(x["momentum_hit"].mean() * 100), 2), "Evidence": "Current candle direction equals previous candle direction", "Use": "Good for hold/follow only when regime agrees"},\n',
    '        {"Pattern Evaluation": "Reversal pressure", "Hit Rate %": round(float(x["reversal_hit"].mean() * 100), 2), "Evidence": "Direction flips after previous candle", "Use": "Use with exit-risk/protect logic"},\n',
    '        {"Pattern Evaluation": "Regime-aligned move", "Hit Rate %": round(float(((x["regime_direction"].eq("BULL") & x["direction"].eq("BUY")) | (x["regime_direction"].eq("BEAR") & x["direction"].eq("SELL"))).mean() * 100), 2), "Evidence": "Move direction matches derived regime", "Use": "Confirm priority and reliability"},\n',
    '    ])\n',
    '\n',
    '    # Lightweight clustering by volatility/trend buckets.\n',
    '    cluster = x.groupby(["vol_bucket", "trend_bucket", "regime_direction"], dropna=False).agg(\n',
    '        Rows=("move_pips", "size"),\n',
    '        Avg_Move_Pips=("move_pips", "mean"),\n',
    '        Avg_Abs_Move_Pips=("abs_move_pips", "mean"),\n',
    '        Up_Rate_Pct=("move_pips", lambda s: float((s > 0).mean() * 100)),\n',
    '        Avg_Range_Pips=("range_pips", "mean"),\n',
    '    ).reset_index().sort_values(["Rows", "Avg_Abs_Move_Pips"], ascending=[False, False]).head(60)\n',
    '    for col in ["Avg_Move_Pips", "Avg_Abs_Move_Pips", "Up_Rate_Pct", "Avg_Range_Pips"]:\n',
    '        cluster[col] = pd.to_numeric(cluster[col], errors="coerce").round(3)\n',
    '\n',
    '    # Association rules for simple market baskets.\n',
    '    total = max(len(x), 1)\n',
    '    high_vol = x["vol_bucket"].eq("High Vol")\n',
    '    strong_trend = x["trend_bucket"].eq("Strong")\n',
    '    bull_regime = x["regime_direction"].eq("BULL")\n',
    '    bear_regime = x["regime_direction"].eq("BEAR")\n',
    '    big_move = x["abs_move_pips"] >= float(x["abs_move_pips"].quantile(0.70))\n',
    '    up_move = x["move_pips"] > 0\n',
    '    down_move = x["move_pips"] < 0\n',
    '\n',
    '    def assoc_row(name: str, antecedent: pd.Series, consequent: pd.Series, use: str) -> Dict[str, Any]:\n',
    '        a = antecedent.fillna(False)\n',
    '        c = consequent.fillna(False)\n',
    '        support = float((a & c).mean() * 100)\n',
    '        conf = float(((a & c).sum() / max(int(a.sum()), 1)) * 100)\n',
    '        base = float(c.mean())\n',
    '        lift = float((conf / 100) / max(base, 1e-9))\n',
    '        return {"Association Rule": name, "Support %": round(support, 2), "Confidence %": round(conf, 2), "Lift": round(lift, 3), "Use": use}\n',
    '\n',
    '    association = pd.DataFrame([\n',
    '        assoc_row("High Vol → Big Move", high_vol, big_move, "TP possible but risk wider"),\n',
    '        assoc_row("Strong Trend → Big Move", strong_trend, big_move, "Follow only with priority sync"),\n',
    '        assoc_row("Bull Regime → Up Move", bull_regime, up_move, "BUY confirmation proxy"),\n',
    '        assoc_row("Bear Regime → Down Move", bear_regime, down_move, "SELL confirmation proxy"),\n',
    '    ]).sort_values(["Lift", "Confidence %"], ascending=[False, False])\n',
    '\n',
    '    # Anomaly detection: z-score on move and range.\n',
    '    mv = x["move_pips"].astype(float)\n',
    '    rg = x["range_pips"].astype(float)\n',
    '    z_move = (mv - mv.rolling(96, min_periods=20).mean()) / mv.rolling(96, min_periods=20).std().replace(0, np.nan)\n',
    '    z_range = (rg - rg.rolling(96, min_periods=20).mean()) / rg.rolling(96, min_periods=20).std().replace(0, np.nan)\n',
    '    work = x.copy()\n',
    '    work["Move_Z"] = z_move.replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    work["Range_Z"] = z_range.replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '    work["Anomaly Score"] = (work["Move_Z"].abs() * 0.55 + work["Range_Z"].abs() * 0.45).round(3)\n',
    '    anomaly = work.sort_values(["Anomaly Score", "time"], ascending=[False, False]).head(30)[["time", "hour", "direction", "regime_direction", "move_pips", "range_pips", "Move_Z", "Range_Z", "Anomaly Score"]].copy()\n',
    '    for col in ["move_pips", "range_pips", "Move_Z", "Range_Z", "Anomaly Score"]:\n',
    '        anomaly[col] = pd.to_numeric(anomaly[col], errors="coerce").round(3)\n',
    '\n',
    '    # 3D data cube: Hour × Regime × Volatility bucket.\n',
    '    cube = x.groupby(["hour", "regime_direction", "vol_bucket"], dropna=False).agg(\n',
    '        Candle_Count=("move_pips", "size"),\n',
    '        Avg_Move_Pips=("move_pips", "mean"),\n',
    '        Avg_Abs_Move_Pips=("abs_move_pips", "mean"),\n',
    '        Up_Rate_Pct=("move_pips", lambda s: float((s > 0).mean() * 100)),\n',
    '        Avg_Range_Pips=("range_pips", "mean"),\n',
    '    ).reset_index().sort_values(["Candle_Count", "Avg_Abs_Move_Pips"], ascending=[False, False]).head(120)\n',
    '    for col in ["Avg_Move_Pips", "Avg_Abs_Move_Pips", "Up_Rate_Pct", "Avg_Range_Pips"]:\n',
    '        cube[col] = pd.to_numeric(cube[col], errors="coerce").round(3)\n',
    '    cube = cube.rename(columns={"hour": "Hour Dimension", "regime_direction": "Regime Dimension", "vol_bucket": "Volatility Dimension"})\n',
    '\n',
    '    return {"pattern": pattern, "cluster": cluster, "association": association, "anomaly": anomaly, "cube": cube}\n',
    '\n',
    '\n',
    'def build_regime_alpha_delta_table(ns: Optional[dict] = None) -> pd.DataFrame:\n',
    '    """Calculate regime alpha/delta from previous vs current regime path.\n',
    '\n',
    '    Alpha = current-vs-previous regime difference + ratio drift + divergence\n',
    '    mean.  Delta = now-alpha vs previous-alpha difference/ratio/divergence. It\n',
    '    is display-only and does not modify regime formulas.\n',
    '    """\n',
    '    hist = pd.DataFrame()\n',
    '    if ns:\n',
    '        try:\n',
    '            builder = ns.get("build_regime_context_20260614")\n',
    '            rctx = builder(force=False) if callable(builder) and bool(st.session_state.get("metric_run_calculate", False)) else st.session_state.get("regime_context_20260614", {})\n',
    '            if isinstance(rctx, dict):\n',
    '                raw = rctx.get("history", pd.DataFrame())\n',
    '                if isinstance(raw, pd.DataFrame) and not raw.empty:\n',
    '                    hist = raw.copy()\n',
    '        except Exception:\n',
    '            hist = pd.DataFrame()\n',
    '    if hist.empty:\n',
    '        d = get_market_df(900)\n',
    '        x = _feature_frame(d)\n',
    '        if not x.empty:\n',
    '            hist = x[["time", "regime_direction", "trend_gap_pips", "vol24_pips"]].copy().rename(columns={"regime_direction": "regime"})\n',
    '    if hist.empty:\n',
    '        return pd.DataFrame()\n',
    '\n',
    '    tcol = _find_col(hist, ["time", "datetime", "date", "end", "end time", "timestamp"])\n',
    '    rcol = _find_col(hist, ["regime", "major regime", "current regime", "h1 regime", "regime_direction"])\n',
    '    score_col = _find_col(hist, ["path", "score", "regime score", "Regime Score", "confidence score"])\n',
    '    out = pd.DataFrame()\n',
    '    if rcol is not None:\n',
    '        out["Now Regime"] = hist[rcol].astype(str)\n',
    '        out["Now Regime Score"] = out["Now Regime"].map(_regime_score).astype(float)\n',
    '    elif score_col is not None:\n',
    '        out["Now Regime Score"] = pd.to_numeric(hist[score_col], errors="coerce").fillna(0.0).astype(float)\n',
    '        out["Now Regime"] = np.where(out["Now Regime Score"] > 0.25, "BULL", np.where(out["Now Regime Score"] < -0.25, "BEAR", "RANGE"))\n',
    '    else:\n',
    '        return pd.DataFrame()\n',
    '    out["time"] = pd.to_datetime(hist[tcol], errors="coerce") if tcol else pd.date_range(end=pd.Timestamp.now().floor("h"), periods=len(out), freq="h")\n',
    '    out = out.dropna(subset=["time"]).tail(120).reset_index(drop=True)\n',
    '    out["Prev Regime"] = out["Now Regime"].shift(1).fillna(out["Now Regime"].iloc[0])\n',
    '    out["Prev Regime Score"] = out["Now Regime Score"].shift(1).fillna(out["Now Regime Score"].iloc[0])\n',
    '    out["Regime Difference"] = out["Now Regime Score"] - out["Prev Regime Score"]\n',
    '    out["Regime Ratio Now/Prev"] = [_safe_ratio(n, p) for n, p in zip(out["Now Regime Score"], out["Prev Regime Score"])]\n',
    '    out["Regime Ratio Drift"] = out["Regime Ratio Now/Prev"].replace([np.inf, -np.inf], np.nan).fillna(0.0) - 1.0\n',
    '    out["Regime Divergence Mean"] = out["Regime Difference"].abs().expanding().mean()\n',
    '    out["Regime Alpha"] = (out["Regime Difference"] + out["Regime Ratio Drift"] + out["Regime Divergence Mean"]) / 3.0\n',
    '    out["Prev Alpha"] = out["Regime Alpha"].shift(1).fillna(0.0)\n',
    '    out["Alpha Difference"] = out["Regime Alpha"] - out["Prev Alpha"]\n',
    '    out["Alpha Ratio Now/Prev"] = [_safe_ratio(n, p) for n, p in zip(out["Regime Alpha"], out["Prev Alpha"])]\n',
    '    out["Alpha Ratio Drift"] = out["Alpha Ratio Now/Prev"].replace([np.inf, -np.inf], np.nan).fillna(0.0) - 1.0\n',
    '    out["Alpha Divergence Mean"] = out["Alpha Difference"].abs().expanding().mean()\n',
    '    out["Regime Delta"] = (out["Alpha Difference"] + out["Alpha Ratio Drift"] + out["Alpha Divergence Mean"]) / 3.0\n',
    '    out["Delta Meaning"] = np.where(out["Regime Delta"].abs() >= 0.65, "Strong regime change pressure", np.where(out["Regime Delta"].abs() >= 0.25, "Moderate regime movement", "Stable / low change"))\n',
    '    for c in ["Now Regime Score", "Prev Regime Score", "Regime Difference", "Regime Ratio Now/Prev", "Regime Ratio Drift", "Regime Divergence Mean", "Regime Alpha", "Prev Alpha", "Alpha Difference", "Alpha Ratio Now/Prev", "Alpha Ratio Drift", "Alpha Divergence Mean", "Regime Delta"]:\n',
    '        out[c] = pd.to_numeric(out[c], errors="coerce").replace([np.inf, -np.inf], np.nan).fillna(0.0).round(4)\n',
    '    return out\n',
    '\n',
    '\n',
    'def render_regime_alpha_delta_metrics(ns: Optional[dict] = None, *, key: str = "regime_alpha_delta") -> pd.DataFrame:\n',
    '    table = build_regime_alpha_delta_table(ns)\n',
    '    st.session_state[f"{key}_table_{UNIQUE}"] = table\n',
    '    if not isinstance(table, pd.DataFrame) or table.empty:\n',
    '        st.info("Regime Alpha/Delta needs regime history or OHLC data. Run Regime Sync/Data Visualization first.")\n',
    '        return table\n',
    '    last = table.iloc[-1]\n',
    '    c = st.columns(4)\n',
    '    c[0].metric("Regime Alpha", f"{_num(last.get(\'Regime Alpha\')):.4f}")\n',
    '    c[1].metric("Regime Delta", f"{_num(last.get(\'Regime Delta\')):.4f}")\n',
]
