"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    c[2].metric("Regime Diff", f"{_num(last.get(\'Regime Difference\')):.4f}")\n',
    '    c[3].metric("Div Mean", f"{_num(last.get(\'Regime Divergence Mean\')):.4f}")\n',
    '    st.caption(f"Alpha uses previous-vs-now regime difference + ratio drift + divergence mean. Delta uses previous-alpha vs now-alpha difference + ratio drift + divergence mean. Latest: {last.get(\'Delta Meaning\', \'-\')}")\n',
    '    with st.expander("Open / Close — Regime Alpha / Delta calculation table", expanded=False):\n',
    '        try:\n',
    '            from ui.stable_ui_libs_20260615 import modern_table\n',
    '            modern_table(table.tail(80), f"{key}_modern_table_{UNIQUE}", height=320)\n',
    '        except Exception:\n',
    '            st.dataframe(table.tail(80), use_container_width=True, hide_index=True, height=320)\n',
    '    return table\n',
    '\n',
    '\n',
    'def _render_table(df: pd.DataFrame, key: str, height: int = 260) -> None:\n',
    '    if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '        st.info("No rows yet. Load data and press Run Calculation.")\n',
    '        return\n',
    '    try:\n',
    '        from ui.stable_ui_libs_20260615 import modern_table\n',
    '        modern_table(df, key, height=height)\n',
    '    except Exception:\n',
    '        st.dataframe(df, use_container_width=True, hide_index=True, height=height)\n',
    '\n',
    '\n',
    'def render_diagnostic_analysis_table(*, key: str = "diagnostic_analysis", expanded: bool = False) -> pd.DataFrame:\n',
    '    table = build_diagnostic_analysis_table()\n',
    '    st.session_state[f"{key}_table_{UNIQUE}"] = table\n',
    '    with st.expander("Open / Close — Diagnostic Analysis Table", expanded=expanded):\n',
    '        st.caption("Shows WHY the current market/system result may be happening. Lightweight and cached; no new model.")\n',
    '        _render_table(table, f"{key}_{UNIQUE}", height=260)\n',
    '    return table\n',
    '\n',
    '\n',
    'def render_sampling_estimation_hypothesis_panel(*, key: str = "sampling_hypothesis", expanded: bool = False) -> Dict[str, pd.DataFrame]:\n',
    '    tabs = build_sampling_estimating_hypothesis_tables()\n',
    '    with st.expander("Open / Close — Sampling + Estimating + Hypothesis Testing", expanded=expanded):\n',
    '        st.caption("Deterministic lightweight statistics using existing candles only. No SciPy/sklearn required.")\n',
    '        sub = st.tabs(["Sampling", "Estimating", "Hypothesis"])\n',
    '        with sub[0]:\n',
    '            _render_table(tabs.get("sampling", pd.DataFrame()), f"{key}_sampling_{UNIQUE}", 240)\n',
    '        with sub[1]:\n',
    '            _render_table(tabs.get("estimating", pd.DataFrame()), f"{key}_estimating_{UNIQUE}", 220)\n',
    '        with sub[2]:\n',
    '            _render_table(tabs.get("hypothesis", pd.DataFrame()), f"{key}_hypothesis_{UNIQUE}", 240)\n',
    '    return tabs\n',
    '\n',
    '\n',
    'def render_data_mining_advanced_panel(*, key: str = "data_mining_advanced", expanded: bool = False) -> Dict[str, pd.DataFrame]:\n',
    '    tables = build_data_mining_extension_tables()\n',
    '    with st.expander("Open / Close — Pattern Evaluation + Cluster + Association + Anomaly + 3D Data Cube", expanded=expanded):\n',
    '        st.caption("Adds requested data-mining views inside one open/close field. CPU/RAM safe: quantile buckets and groupby only; no new ML model.")\n',
    '        sub = st.tabs(["Pattern", "Cluster", "Association", "Anomaly", "3D Cube"])\n',
    '        with sub[0]:\n',
    '            _render_table(tables.get("pattern", pd.DataFrame()), f"{key}_pattern_{UNIQUE}", 230)\n',
    '        with sub[1]:\n',
    '            _render_table(tables.get("cluster", pd.DataFrame()), f"{key}_cluster_{UNIQUE}", 310)\n',
    '        with sub[2]:\n',
    '            _render_table(tables.get("association", pd.DataFrame()), f"{key}_association_{UNIQUE}", 240)\n',
    '        with sub[3]:\n',
    '            _render_table(tables.get("anomaly", pd.DataFrame()), f"{key}_anomaly_{UNIQUE}", 320)\n',
    '        with sub[4]:\n',
    '            _render_table(tables.get("cube", pd.DataFrame()), f"{key}_cube_{UNIQUE}", 340)\n',
    '    st.session_state[f"{key}_tables_{UNIQUE}"] = {k: (v.head(120).to_dict("records") if isinstance(v, pd.DataFrame) else []) for k, v in tables.items()}\n',
    '    return tables\n',
    '\n',
    '\n',
    'def render_data_mining_advanced_inline(*, key: str = "data_mining_advanced_inline") -> Dict[str, pd.DataFrame]:\n',
    '    """Inline version for existing open/close fields, avoiding nested expanders."""\n',
    '    tables = build_data_mining_extension_tables()\n',
    '    st.caption("Pattern evaluation, sampling-aware clustering, association rules, anomaly analysis, and 3D cube use existing candles only.")\n',
    '    sub = st.tabs(["Pattern", "Cluster", "Association", "Anomaly", "3D Cube"])\n',
    '    with sub[0]:\n',
    '        _render_table(tables.get("pattern", pd.DataFrame()), f"{key}_pattern_{UNIQUE}", 230)\n',
    '    with sub[1]:\n',
    '        _render_table(tables.get("cluster", pd.DataFrame()), f"{key}_cluster_{UNIQUE}", 310)\n',
    '    with sub[2]:\n',
    '        _render_table(tables.get("association", pd.DataFrame()), f"{key}_association_{UNIQUE}", 240)\n',
    '    with sub[3]:\n',
    '        _render_table(tables.get("anomaly", pd.DataFrame()), f"{key}_anomaly_{UNIQUE}", 320)\n',
    '    with sub[4]:\n',
    '        _render_table(tables.get("cube", pd.DataFrame()), f"{key}_cube_{UNIQUE}", 340)\n',
    '    return tables\n',
]
