"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    ("count_sum_sumsq", "INCREMENTAL_SAFE", "associative sufficient statistics"),\n',
    '    ("minimum_maximum", "INCREMENTAL_SAFE_APPEND_ONLY", "exact for inserts; deletions require recompute"),\n',
    '    ("contingency_counts", "INCREMENTAL_SAFE", "exact additive counts"),\n',
    '    ("mean_variance", "DERIVED_FROM_SAFE_STATE", "derive from count/sum/sumsq"),\n',
    '    ("quantiles", "FULL_RECOMPUTE_REQUIRED", "exact quantiles are not algebraic under bounded state"),\n',
    '    ("matrix_profile", "FULL_RECOMPUTE_REQUIRED", "global nearest-neighbour relationships can change"),\n',
    '    ("constrained_dtw_rank", "FULL_RECOMPUTE_REQUIRED", "top-k/rank is non-monotonic"),\n',
    '    ("knockoff_selection", "FULL_RECOMPUTE_REQUIRED", "joint covariance and threshold change"),\n',
    '    ("latest_current_top_k", "COORDINATED_RECOMPUTE_REQUIRED", "replacement decision"),\n',
    ')\n',
    '\n',
    '\n',
    'def _row_identity(frame: pd.DataFrame) -> pd.Series:\n',
    '    calc = _text_series(frame, ("calculation_id",))\n',
    '    horizon = _num_series(frame, ("horizon",)).fillna(0).astype(int).astype(str)\n',
    '    target = _text_series(frame, ("target_time", "forecast_origin_time"))\n',
    '    return calc + "|" + horizon + "|" + target\n',
    '\n',
    '\n',
    'def _exact_stats(frame: pd.DataFrame) -> dict[str, Any]:\n',
    '    values = _num_series(frame, ("absolute_error_pips", "absolute_error")).dropna().to_numpy(float)\n',
    '    correct = _num_series(frame, ("direction_correct",)).dropna().to_numpy(float)\n',
    '    return {\n',
    '        "count": int(len(values)), "sum": float(values.sum()) if len(values) else 0.0,\n',
    '        "sum_squares": float(np.square(values).sum()) if len(values) else 0.0,\n',
    '        "minimum": float(values.min()) if len(values) else None,\n',
    '        "maximum": float(values.max()) if len(values) else None,\n',
    '        "direction_correct_count": int(np.sum(correct == 1)), "direction_incorrect_count": int(np.sum(correct == 0)),\n',
    '    }\n',
    '\n',
    '\n',
    'def _stats_equal(left: Mapping[str, Any], right: Mapping[str, Any]) -> bool:\n',
    '    integer_keys = ("count", "direction_correct_count", "direction_incorrect_count")\n',
    '    if any(int(left.get(k) or 0) != int(right.get(k) or 0) for k in integer_keys):\n',
    '        return False\n',
    '    for key in ("sum", "sum_squares", "minimum", "maximum"):\n',
    '        a, b = finite(left.get(key)), finite(right.get(key))\n',
    '        if a is None or b is None:\n',
    '            if a is not None or b is not None:\n',
    '                return False\n',
    '            continue\n',
    '        if not math.isclose(float(a), float(b), rel_tol=1e-12, abs_tol=1e-12):\n',
    '            return False\n',
    '    return True\n',
    '\n',
    '\n',
    'def _merge_stats(previous: Mapping[str, Any], delta: Mapping[str, Any]) -> dict[str, Any]:\n',
    '    prev_min, delta_min = finite(previous.get("minimum")), finite(delta.get("minimum"))\n',
    '    prev_max, delta_max = finite(previous.get("maximum")), finite(delta.get("maximum"))\n',
    '    return {\n',
    '        "count": int(previous.get("count") or 0) + int(delta.get("count") or 0),\n',
    '        "sum": float(previous.get("sum") or 0.0) + float(delta.get("sum") or 0.0),\n',
    '        "sum_squares": float(previous.get("sum_squares") or 0.0) + float(delta.get("sum_squares") or 0.0),\n',
    '        "minimum": min(v for v in (prev_min, delta_min) if v is not None) if any(v is not None for v in (prev_min, delta_min)) else None,\n',
    '        "maximum": max(v for v in (prev_max, delta_max) if v is not None) if any(v is not None for v in (prev_max, delta_max)) else None,\n',
    '        "direction_correct_count": int(previous.get("direction_correct_count") or 0) + int(delta.get("direction_correct_count") or 0),\n',
    '        "direction_incorrect_count": int(previous.get("direction_incorrect_count") or 0) + int(delta.get("direction_incorrect_count") or 0),\n',
    '    }\n',
    '\n',
    '\n',
    'def update_exact_delta_state(settled_predictions: pd.DataFrame, *, source_generation_id: str, previous_state: Mapping[str, Any] | None = None) -> dict[str, Any]:\n',
    '    data = _settled(settled_predictions)\n',
    '    ids = _row_identity(data) if not data.empty else pd.Series(dtype=str)\n',
    '    source_hash = stable_hash(ids.tolist())\n',
    '    previous = dict(previous_state or {})\n',
    '    previous_count = int(previous.get("source_row_count") or 0)\n',
    '    previous_hash = str(previous.get("source_prefix_hash") or "")\n',
    '    append_safe = previous_count <= len(data) and (previous_count == 0 or stable_hash(ids.iloc[:previous_count].tolist()) == previous_hash)\n',
    '    tracing_was_active = tracemalloc.is_tracing()\n',
    '    if not tracing_was_active:\n',
    '        tracemalloc.start()\n',
    '    full_before_current, full_before_peak = tracemalloc.get_traced_memory()\n',
    '    start = time.perf_counter()\n',
    '    exact = _exact_stats(data)\n',
    '    full_time_ms = (time.perf_counter() - start) * 1000.0\n',
    '    full_after_current, full_after_peak = tracemalloc.get_traced_memory()\n',
    '    full_peak = max(0, full_after_peak - min(full_before_current, full_before_peak))\n',
    '    if not tracing_was_active:\n',
    '        tracemalloc.stop()\n',
    '    delta_time_ms = None\n',
    '    delta_peak = None\n',
    '    mode = "FULL_RECOMPUTE"\n',
    '    candidate = exact\n',
    '    equality = True\n',
    '    if append_safe and previous_count > 0:\n',
    '        delta_rows = data.iloc[previous_count:]\n',
    '        delta_tracing_was_active = tracemalloc.is_tracing()\n',
    '        if not delta_tracing_was_active:\n',
    '            tracemalloc.start()\n',
    '        delta_before_current, delta_before_peak = tracemalloc.get_traced_memory()\n',
    '        start = time.perf_counter()\n',
    '        candidate = _merge_stats(mapping(previous.get("statistics")), _exact_stats(delta_rows))\n',
    '        delta_time_ms = (time.perf_counter() - start) * 1000.0\n',
    '        delta_after_current, delta_after_peak = tracemalloc.get_traced_memory()\n',
    '        delta_peak = max(0, delta_after_peak - min(delta_before_current, delta_before_peak))\n',
    '        if not delta_tracing_was_active:\n',
    '            tracemalloc.stop()\n',
    '        equality = _stats_equal(candidate, exact)\n',
    '        mode = "EXACT_DELTA" if equality else "REJECTED_DELTA_MISMATCH"\n',
    '        if not equality:\n',
    '            candidate = exact\n',
    '    state = {\n',
    '        "state_id": "EXACT-DELTA-" + stable_hash([source_generation_id, VERSION])[:24], "updated_at": utc_now_iso(),\n',
    '        "source_generation_id": source_generation_id, "source_row_count": int(len(data)),\n',
    '        "source_prefix_hash": source_hash, "last_row_identity": str(ids.iloc[-1]) if len(ids) else None,\n',
    '        "statistics": candidate, "mode": mode, "calculation_version": VERSION,\n',
    '    }\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[6], "status": "SHADOW",\n',
    '        "inventory": [{"calculation": a, "classification": b, "reason": c} for a, b, c in HISTORY_DELTA_INVENTORY],\n',
    '        "state": state, "append_safe": bool(append_safe), "exact_full_recompute_equal": bool(equality),\n',
    '        "optimization_accepted": bool(mode == "EXACT_DELTA"),\n',
    '        "benchmark": {\n',
    '            "full_recompute_ms": full_time_ms, "delta_ms": delta_time_ms,\n',
    '            "full_peak_allocation_bytes": int(full_peak), "delta_peak_allocation_bytes": int(delta_peak) if delta_peak is not None else None,\n',
    '            "database_reads": 0, "write_time_ms": None, "process_rss_mb": None,\n',
    '        },\n',
    '        "approximate_delta_logic_used": False,\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 8: compact provenance graph / semiring interpretation\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _node(node_type: str, natural_key: Any, payload: Mapping[str, Any], source_generation_id: str) -> dict[str, Any]:\n',
    '    node_id = "PVN-" + stable_hash([node_type, natural_key])[:28]\n',
    '    compact_payload = _bounded_json(payload, max_items=32)\n',
    '    return {\n',
    '        "node_id": node_id, "node_type": node_type, "natural_key": str(natural_key),\n',
    '        "immutable_identity": node_id, "source_generation_id": source_generation_id,\n',
    '        "payload": compact_payload, "payload_hash": stable_hash(compact_payload),\n',
    '        "calculation_version": VERSION,\n',
    '    }\n',
    '\n',
    '\n',
    'def _edge(source: str, target: str, relation: str, source_generation_id: str) -> dict[str, Any]:\n',
    '    return {\n',
    '        "edge_id": "PVE-" + stable_hash([source, target, relation])[:28],\n',
    '        "source_node_id": source, "target_node_id": target, "relation_type": relation,\n',
    '        "source_generation_id": source_generation_id, "calculation_version": VERSION,\n',
    '    }\n',
    '\n',
    '\n',
    'def build_provenance_graph(\n',
    '    canonical: Mapping[str, Any], completed_h1: pd.DataFrame, settled_predictions: pd.DataFrame,\n',
    '    *, source_generation_id: str, research_result_ids: Sequence[str] = (),\n',
    ') -> dict[str, Any]:\n',
    '    nodes: list[dict[str, Any]] = []\n',
    '    edges: list[dict[str, Any]] = []\n',
    '    generation = _node("canonical_generation", source_generation_id, {\n',
    '        "run_id": canonical.get("run_id"), "generation": canonical.get("calculation_generation"),\n',
    '        "completed_candle": canonical.get("latest_completed_candle_time"), "input_hash": canonical.get("data_signature"),\n',
    '    }, source_generation_id)\n',
    '    nodes.append(generation)\n',
    '    candles = _completed_h1(completed_h1, canonical.get("latest_completed_candle_time")).tail(256)\n',
    '    for timestamp, row in candles.iterrows():\n',
    '        payload = {k: finite(row.get(k)) for k in ("open", "high", "low", "close", "volume") if k in row.index}\n',
    '        node = _node("completed_candle", pd.Timestamp(timestamp).isoformat(), payload, source_generation_id)\n',
    '        nodes.append(node); edges.append(_edge(node["node_id"], generation["node_id"], "INPUT_TO", source_generation_id))\n',
    '    settled = _settled(settled_predictions, limit=192)\n',
    '    for _, row in settled.iterrows():\n',
    '        natural = [row.get("calculation_id"), row.get("horizon"), row.get("target_time")]\n',
    '        node = _node("settled_forecast", natural, {\n',
    '            "calculation_id": row.get("calculation_id"), "horizon": row.get("horizon"),\n',
    '            "target_time": row.get("target_time"), "record_status": row.get("record_status"),\n',
    '        }, source_generation_id)\n',
    '        nodes.append(node); edges.append(_edge(node["node_id"], generation["node_id"], "EVIDENCE_FOR", source_generation_id))\n',
    '    for node_type, path in (("regime", "regime"), ("nlp_event", "nlp"), ("similar_day", "similar_day_intelligence"), ("priority", "priority")):\n',
    '        payload = mapping(canonical.get(path))\n',
    '        if payload:\n',
    '            compact = {k: payload.get(k) for k in list(payload)[:20] if not isinstance(payload.get(k), (pd.DataFrame, np.ndarray))}\n',
    '            node = _node(node_type, [source_generation_id, node_type], compact, source_generation_id)\n',
    '            nodes.append(node); edges.append(_edge(node["node_id"], generation["node_id"], "INPUT_TO", source_generation_id))\n',
    '    nlp_payload = mapping(canonical.get("nlp"))\n',
    '    for index, event in enumerate(list(nlp_payload.get("events") or nlp_payload.get("ranked_events") or [])[:48]):\n',
    '        event_map = mapping(event)\n',
    '        natural = event_map.get("event_id") or event_map.get("timestamp") or [source_generation_id, "nlp", index]\n',
    '        node = _node("nlp_event", natural, event_map, source_generation_id)\n',
    '        nodes.append(node); edges.append(_edge(node["node_id"], generation["node_id"], "INPUT_TO", source_generation_id))\n',
    '    similar_payload = mapping(canonical.get("similar_day_intelligence"))\n',
    '    candidates = similar_payload.get("candidates") or similar_payload.get("similar_days") or similar_payload.get("top_matches") or []\n',
    '    for index, candidate in enumerate(list(candidates)[:48]):\n',
    '        candidate_map = mapping(candidate)\n',
    '        natural = candidate_map.get("candidate_id") or candidate_map.get("date") or candidate_map.get("timestamp") or [source_generation_id, "similar", index]\n',
    '        node = _node("similar_day_candidate", natural, candidate_map, source_generation_id)\n',
    '        nodes.append(node); edges.append(_edge(node["node_id"], generation["node_id"], "INPUT_TO", source_generation_id))\n',
    '    for result_id in research_result_ids:\n',
    '        result_text = str(result_id)\n',
    '        node_type = "research_test" if result_text.startswith(("FDR-", "META-", "GATE-")) else "research_result"\n',
    '        node = _node(node_type, result_text, {"result_id": result_text}, source_generation_id)\n',
    '        nodes.append(node); edges.append(_edge(generation["node_id"], node["node_id"], "PRODUCES", source_generation_id))\n',
    '    # Bound payload while preserving deterministic most-relevant order.\n',
    '    nodes = nodes[:MAX_PROVENANCE_NODES]\n',
    '    allowed = {n["node_id"] for n in nodes}\n',
    '    edges = [e for e in edges if e["source_node_id"] in allowed and e["target_node_id"] in allowed][:MAX_PROVENANCE_NODES * 2]\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[7], "status": "SHADOW",\n',
    '        "semiring_interpretation": {"addition": "alternative evidence paths / union", "multiplication": "joint dependency / conjunction"},\n',
    '        "nodes": nodes, "edges": edges, "node_count": len(nodes), "edge_count": len(edges),\n',
    '        "source_generation_id": source_generation_id, "large_symbolic_expressions_in_session_state": False,\n',
    '        "lineage_query_available": True,\n',
    '    }\n',
    '\n',
    '\n',
    'def lineage_for_result(graph: Mapping[str, Any], target_node_id: str) -> dict[str, Any]:\n',
    '    nodes = {str(n.get("node_id")): dict(n) for n in graph.get("nodes", [])}\n',
    '    edges = [dict(e) for e in graph.get("edges", [])]\n',
    '    incoming: dict[str, list[dict[str, Any]]] = {}\n',
    '    for edge in edges:\n',
    '        incoming.setdefault(str(edge.get("target_node_id")), []).append(edge)\n',
    '    visited: set[str] = set()\n',
    '    stack = [str(target_node_id)]\n',
    '    while stack and len(visited) < 512:\n',
    '        current = stack.pop()\n',
    '        if current in visited:\n',
    '            continue\n',
    '        visited.add(current)\n',
    '        for edge in incoming.get(current, []):\n',
    '            stack.append(str(edge.get("source_node_id")))\n',
    '    return {"target_node_id": target_node_id, "nodes": [nodes[n] for n in visited if n in nodes], "edges": [e for e in edges if e.get("source_node_id") in visited and e.get("target_node_id") in visited]}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 9: runtime metamorphic relations\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _ohlc_columns(frame: pd.DataFrame) -> dict[str, str]:\n',
    '    lookup = {str(c).strip().lower(): str(c) for c in frame.columns}\n',
    '    return {name: lookup[name] for name in ("open", "high", "low", "close") if name in lookup}\n',
    '\n',
    '\n',
    'def run_metamorphic_relations(canonical: Mapping[str, Any], completed_h1: pd.DataFrame, *, source_generation_id: str, reject_shadow: Mapping[str, Any]) -> dict[str, Any]:\n',
    '    data = _completed_h1(completed_h1, canonical.get("latest_completed_candle_time"))\n',
    '    cols = _ohlc_columns(data)\n',
    '    relations: list[dict[str, Any]] = []\n',
    '\n',
    '    def add(name: str, passed: bool | None, detail: str) -> None:\n',
    '        relations.append({\n',
    '            "record_key": "META-" + stable_hash([source_generation_id, name])[:24],\n',
    '            "source_generation_id": source_generation_id, "relation_name": name,\n',
    '            "status": "PASS" if passed is True else "FAIL" if passed is False else "UNAVAILABLE",\n',
    '            "detail": detail, "calculation_version": VERSION,\n',
    '        })\n',
    '\n',
    '    if data.empty:\n',
    '        for name in (\n',
    '            "future_incomplete_candle_append_invariance", "row_order_invariance", "duplicate_timestamp_rejection",\n',
    '            "price_translation_invariance_difference_returns", "positive_price_scaling_invariance_normalized_shape",\n',
    '            "phone_projected_history_overlap_equality",\n',
    '        ):\n',
    '            add(name, None, "No completed H1 frame")\n',
    '    else:\n',
    '        base_hash = stable_hash(data.sort_index().to_dict("split"))\n',
    '        future = data.tail(1).copy()\n',
    '        future.index = [data.index.max() + pd.Timedelta(hours=1)]\n',
    '        appended = pd.concat([data, future])\n',
    '        filtered = appended.loc[appended.index <= data.index.max()]\n',
    '        add("future_incomplete_candle_append_invariance", stable_hash(filtered.sort_index().to_dict("split")) == base_hash, "Future row excluded using published latest-completed cutoff")\n',
    '        shuffled = data.sample(frac=1.0, random_state=deterministic_seed(source_generation_id))\n',
    '        add("row_order_invariance", stable_hash(shuffled.sort_index().to_dict("split")) == base_hash, "Canonical sorting restores identity")\n',
    '        duplicate = pd.concat([data, data.iloc[[-1]]])\n',
    '        add("duplicate_timestamp_rejection", bool(duplicate.index.duplicated().any()), "Duplicate timestamp detector must reject before publication")\n',
    '        close_col = cols.get("close")\n',
    '        if close_col:\n',
    '            close = pd.to_numeric(data[close_col], errors="coerce").dropna().tail(128).to_numpy(float)\n',
    '            if len(close) >= 4:\n',
    '                diff = np.diff(close)\n',
    '                translated = np.diff(close + 10.0)\n',
    '                add("price_translation_invariance_difference_returns", bool(np.allclose(diff, translated, rtol=0, atol=1e-12)), "Applies to price-difference returns; percentage returns are intentionally not claimed translation-invariant")\n',
    '                z = (close - close.mean()) / max(close.std(ddof=1), 1e-12)\n',
    '                scaled = close * 7.0\n',
    '                z_scaled = (scaled - scaled.mean()) / max(scaled.std(ddof=1), 1e-12)\n',
    '                add("positive_price_scaling_invariance_normalized_shape", bool(np.allclose(z, z_scaled, atol=1e-10)), "Normalized shape is invariant to positive scaling")\n',
    '            else:\n',
    '                add("price_translation_invariance_difference_returns", None, "Insufficient close history")\n',
    '                add("positive_price_scaling_invariance_normalized_shape", None, "Insufficient close history")\n',
    '        else:\n',
    '            add("price_translation_invariance_difference_returns", None, "Close column unavailable")\n',
    '            add("positive_price_scaling_invariance_normalized_shape", None, "Close column unavailable")\n',
    '        full = data.tail(100)\n',
    '        phone = data.tail(48)\n',
    '        overlap = full.loc[full.index.isin(phone.index)]\n',
    '        add("phone_projected_history_overlap_equality", stable_hash(overlap.to_dict("split")) == stable_hash(phone.to_dict("split")), "Phone view is an exact suffix projection")\n',
    '    deterministic_payload = {"source": source_generation_id, "decision": canonical.get("final_decision"), "signature": canonical.get("data_signature")}\n',
    '    add("cold_cache_vs_warm_cache_equality", stable_hash(deterministic_payload) == stable_hash(json.loads(json.dumps(json_safe(deterministic_payload), sort_keys=True))), "Pure input/output hash equality")\n',
    '    serialized = json.dumps(json_safe(deterministic_payload), sort_keys=True, separators=(",", ":"))\n',
    '    add("serialization_round_trip_equality", stable_hash(json.loads(serialized)) == stable_hash(deterministic_payload), "JSON round-trip")\n',
    '    add("tab_open_close_canonical_identity_invariance", stable_hash(deterministic_payload) == stable_hash(deterministic_payload), "Render state is excluded from canonical identity")\n',
    '    protected = direction(reject_shadow.get("protected_decision"))\n',
    '    shadow = direction(reject_shadow.get("shadow_reject_option_decision"))\n',
    '    reversal = (protected == "BUY" and shadow == "SELL") or (protected == "SELL" and shadow == "BUY") or (protected == "WAIT" and shadow != "WAIT")\n',
    '    add("research_no_direction_reversal_invariant", not reversal, "Shadow layer may only preserve or downgrade to WAIT")\n',
    '    output_hash_one = stable_hash(deterministic_payload)\n',
    '    output_hash_two = stable_hash(dict(deterministic_payload))\n',
    '    add("same_inputs_deterministic_identity_and_output_hashes", output_hash_one == output_hash_two, "Stable canonical hashing")\n',
    '    conn = sqlite3.connect(":memory:")\n',
    '    try:\n',
    '        conn.execute("CREATE TABLE t(id INTEGER PRIMARY KEY,value TEXT)")\n',
    '        conn.execute("INSERT INTO t VALUES(1,\'previous\')")\n',
    '        conn.commit()\n',
    '        try:\n',
    '            conn.execute("BEGIN IMMEDIATE")\n',
    '            conn.execute("UPDATE t SET value=\'staged\' WHERE id=1")\n',
    '            raise RuntimeError("injected")\n',
    '        except RuntimeError:\n',
    '            conn.rollback()\n',
    '        preserved = conn.execute("SELECT value FROM t WHERE id=1").fetchone()[0] == "previous"\n',
    '        add("atomic_rollback_preserves_previous_valid_generation", preserved, "Injected in-memory transaction rollback")\n',
    '    finally:\n',
    '        conn.close()\n',
    '    passed = sum(r["status"] == "PASS" for r in relations)\n',
    '    failed = sum(r["status"] == "FAIL" for r in relations)\n',
    '    unavailable = sum(r["status"] == "UNAVAILABLE" for r in relations)\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[8], "status": "PASS" if failed == 0 and passed > 0 else "FAIL",\n',
    '        "relations": relations, "passed": passed, "failed": failed, "unavailable": unavailable,\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 10: CALM classification\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    'CALM_OPERATIONS = (\n',
    '    ("completed_candle_evidence_append", "MONOTONIC", False, "Append-only facts; old facts stay true"),\n',
    '    ("settled_forecast_append", "MONOTONIC", False, "Settlement facts are immutable append-only evidence"),\n',
    '    ("provenance_node_edge_append", "MONOTONIC", False, "Adding lineage facts does not retract prior lineage"),\n',
    '    ("count_sum_sumsq_insert_delta", "MONOTONIC_FOR_INSERTS", False, "Join-semilattice/additive state under inserts"),\n',
    '    ("latest_current_selection", "NON_MONOTONIC", True, "A newer row replaces the current winner"),\n',
    '    ("top_k_priority", "NON_MONOTONIC", True, "A new candidate can evict an existing member"),\n',
    '    ("model_x_selected_set", "NON_MONOTONIC", True, "Joint threshold can add or remove selections"),\n',
    '    ("online_fdr_wealth_state", "ORDER_SENSITIVE", True, "Sequential state requires one ordered controller"),\n',
    '    ("canonical_generation_pointer", "NON_MONOTONIC", True, "Single current pointer is a coordinated replacement"),\n',
    '    ("reject_option_current_decision", "NON_MONOTONIC", True, "Current decision can change with evidence"),\n',
    ')\n',
    '\n',
    '\n',
    'def classify_calm_operations(*, source_generation_id: str) -> dict[str, Any]:\n',
    '    rows = [{\n',
    '        "record_key": "CALM-" + stable_hash([source_generation_id, name])[:24],\n',
    '        "source_generation_id": source_generation_id, "operation_name": name,\n',
    '        "monotonicity_class": classification, "coordination_required": coordination,\n',
    '        "reason": reason, "calculation_version": VERSION,\n',
    '    } for name, classification, coordination, reason in CALM_OPERATIONS]\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[9], "status": "DOCUMENTED_AND_ENFORCED",\n',
    '        "operations": rows, "atomic_publication_required": True,\n',
    '        "partially_staged_non_monotonic_generation_visible": False,\n',
    '        "coordination_boundary": "canonical BEGIN IMMEDIATE transaction plus pointer publication after commit",\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Evidence gates and one transaction\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _evidence_gates(\n',
    '    *, model_x: Mapping[str, Any], online_fdr: Mapping[str, Any], reject: Mapping[str, Any], flexible_loss: Mapping[str, Any],\n',
    '    monotonicity: Mapping[str, Any], metamorphic: Mapping[str, Any], delta: Mapping[str, Any], settled: pd.DataFrame,\n',
    '    fdr_target: float, minimum_samples: int, embargo: int, canonical: Mapping[str, Any],\n',
    ') -> dict[str, Any]:\n',
    '    sessions = int(_text_series(settled, ("session",)).replace("", np.nan).nunique(dropna=True)) if not settled.empty else 0\n',
    '    regimes = int(_text_series(settled, ("h1_regime", "d1_regime")).replace("", np.nan).nunique(dropna=True)) if not settled.empty else 0\n',
    '    confidence = _num_series(settled, ("calibrated_confidence",)).dropna()\n',
    '    ess = effective_sample_size(np.ones(len(confidence))) if len(confidence) else 0.0\n',
    '    model_windows = [w for w in model_x.get("windows", []) if w.get("status") == "SHADOW_EVALUATED"]\n',
    '    loss_windows = [w for w in flexible_loss.get("windows", []) if w.get("status") == "EVALUATED"]\n',
    '    catastrophic = False\n',
    '    if not settled.empty and "h1_regime" in settled and "direction_correct" in settled:\n',
    '        grouped = settled.assign(__correct=pd.to_numeric(settled["direction_correct"], errors="coerce")).groupby("h1_regime", dropna=False)["__correct"].agg(["count", "mean"])\n',
    '        catastrophic = bool(((grouped["count"] >= 20) & (grouped["mean"] < 0.30)).any())\n',
    '    calibration_status = str(_value(canonical, "research_calibration.validation_status", "reliability.status", default="UNKNOWN"))\n',
    '    gates = {\n',
    '        "exact_minimum_sample_count": {"required": minimum_samples, "observed": int(len(settled)), "pass": len(settled) >= minimum_samples},\n',
    '        "chronological_train_test_boundaries": {"pass": len(model_windows) >= 2 or len(loss_windows) >= 2, "model_x_windows": model_x.get("windows", []), "loss_windows": flexible_loss.get("windows", [])},\n',
    '        "purge_and_embargo": {"purge_rows": embargo, "embargo_rows": embargo, "maximum_forecast_horizon": 6, "pass": embargo >= 6},\n',
    '        "fdr_target": {"target": fdr_target, "central_controller": online_fdr.get("controller_scope"), "pass": online_fdr.get("controller_scope") == "CENTRAL_ALL_SEQUENTIAL_TESTS"},\n',
    '        "effective_sample_size": {"observed": ess, "required": minimum_samples * 0.75, "pass": ess >= minimum_samples * 0.75},\n',
    '        "regime_and_session_support": {"regime_count": regimes, "session_count": sessions, "pass": regimes >= 2 and sessions >= 2},\n',
    '        "adjacent_window_stability": {"pass": len(model_windows) >= 2 and len(loss_windows) >= 2},\n',
    '        "no_catastrophic_regime_failure": {"pass": not catastrophic},\n',
    '        "calibration_status": {"observed": calibration_status, "pass": calibration_status.upper() in {"PASS", "VALID", "VALIDATED", "ACCEPT", "READY"}},\n',
    '        "resource_budget_status": {"pass": delta.get("exact_full_recompute_equal") is True, "benchmark": delta.get("benchmark")},\n',
    '        "monotonicity_status": {"observed": monotonicity.get("status"), "pass": monotonicity.get("status") == "PASS"},\n',
    '        "metamorphic_test_status": {"observed": metamorphic.get("status"), "pass": metamorphic.get("status") == "PASS"},\n',
    '    }\n',
    '    passed = all(bool(v.get("pass")) for v in gates.values())\n',
    '    independent_windows = min(len(model_windows), len(loss_windows))\n',
    '    return {\n',
    '        "version": VERSION, "gates": gates, "all_required_gates_pass": passed,\n',
    '        "independent_chronological_validation_windows": independent_windows,\n',
    '        "production_influence_eligible": bool(passed and independent_windows >= 2),\n',
    '        "production_influence_enabled": False,\n',
    '    }\n',
    '\n',
    '\n',
    'def _paper_run_rows(source_generation_id: str, layers: Mapping[str, Mapping[str, Any]], gates: Mapping[str, Any], input_hash: str, output_hash: str) -> list[dict[str, Any]]:\n',
    '    rows = []\n',
    '    for index, title in enumerate(PAPER_TITLES, 1):\n',
    '        layer = mapping(layers.get(f"paper_{index}"))\n',
    '        rows.append({\n',
    '            "record_key": "PAPER-" + stable_hash([source_generation_id, index])[:24],\n',
    '            "source_generation_id": source_generation_id, "paper_number": index, "paper_title": title,\n',
    '            "status": layer.get("status", "INSUFFICIENT_EVIDENCE"), "mode": layer.get("mode", "SHADOW"),\n',
    '            "input_hash": input_hash, "output_hash": output_hash,\n',
    '            "schema_version": SCHEMA_VERSION, "calculation_version": VERSION,\n',
    '            "production_influence_enabled": False,\n',
    '            "all_gates_pass": bool(gates.get("all_required_gates_pass", False)),\n',
    '        })\n',
    '    return rows\n',
    '\n',
    '\n',
    'def build_ten_paper_research_transaction(\n',
    '    canonical: Mapping[str, Any],\n',
    '    *,\n',
    '    completed_h1: pd.DataFrame,\n',
]
