"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '            "diagnostics": diagnostics, **support,\n',
    '        })\n',
    '    stable_selected = sorted(feature for feature, flags in selections.items() if len(flags) >= 2 and all(flags[:2]))\n',
    '    review_only = sorted(\n',
    '        feature for feature, flags in selections.items()\n',
    '        if len(flags) >= 2 and not any(flags[:2])\n',
    '        and len(validation_effects.get(feature, [])) >= 2\n',
    '        and all(effect is not None and abs(float(effect)) <= 0.05 for effect in validation_effects[feature][:2])\n',
    '    )\n',
    '    adequate_windows = sum(row.get("status") == "SHADOW_EVALUATED" for row in window_results) >= 2\n',
    '    status = "SHADOW" if adequate_windows else "INSUFFICIENT_EVIDENCE"\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[0], "status": status,\n',
    '        "mode": "SHADOW", "minimum_sample_count": minimum_samples, "observed_sample_count": int(len(data)),\n',
    '        "purge_rows": embargo, "embargo_rows": embargo, "fdr_target": float(fdr_target),\n',
    '        "windows": window_results, "feature_statistics": feature_rows,\n',
    '        "stable_selected_features": stable_selected,\n',
    '        "removal_review_candidates": review_only if adequate_windows and regime_support >= 2 else [],\n',
    '        "removal_review_rule": "unselected in both walk-forward windows, absolute test effect <= 0.05 in both, and at least two regimes",\n',
    '        "automatic_feature_removal": False, "production_feature_set_changed": False,\n',
    '        "regime_support": regime_support,\n',
    '        "fdr_control_claimed": False,\n',
    '        "assumption_status": "UNVERIFIED_ESTIMATED_COVARIATE_DISTRIBUTION",\n',
    '        "reason": "Second-order knockoffs are implemented, but exact Model-X exchangeability is not proven for the supplied time-series covariates.",\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 2: central online FDR controller\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _gamma(index: int) -> float:\n',
    '    i = max(1, int(index))\n',
    '    return float(6.0 / (math.pi * math.pi * i * i))\n',
    '\n',
    '\n',
    'def collect_sequential_tests(canonical: Mapping[str, Any], model_x: Mapping[str, Any]) -> list[dict[str, Any]]:\n',
    '    tests: list[dict[str, Any]] = []\n',
    '    existing = mapping(canonical.get("research_validation_20260621"))\n',
    '    cpa = mapping(existing.get("conditional_predictive_ability"))\n',
    '    for row in list(cpa.get("rows") or [])[:120]:\n',
    '        p_value = finite(row.get("p_value"))\n',
    '        if p_value is not None:\n',
    '            tests.append({"test_family": "forecast_superiority", "raw_p_value": p_value, "source": "conditional_predictive_ability", "test_key": row.get("evaluation_id") or stable_hash(row)})\n',
    '    for item in list(existing.get("superior_predictive_ability") or [])[:24]:\n',
    '        row = mapping(mapping(item).get("row"))\n',
    '        p_value = finite(row.get("spa_p_value"))\n',
    '        if p_value is not None:\n',
    '            tests.append({"test_family": "promotion_tests", "raw_p_value": p_value, "source": "superior_predictive_ability", "test_key": row.get("evaluation_id") or stable_hash(row)})\n',
    '    advanced = mapping(canonical.get("advanced_reliability_shift"))\n',
    '    for family, section_name in (("drift", "mmd"), ("calibration", "multicalibration"), ("regime_conditional", "conformal_risk_control")):\n',
    '        section = mapping(advanced.get(section_name))\n',
    '        p_value = finite(section.get("p_value"), finite(section.get("test_p_value")))\n',
    '        if p_value is not None:\n',
    '            tests.append({"test_family": family, "raw_p_value": p_value, "source": section_name, "test_key": section.get("evaluation_id") or stable_hash([section_name, section])})\n',
    '    # Knockoff selection is controlled by its own threshold; register a family\n',
    '    # audit row without inventing a p-value.\n',
    '    if model_x:\n',
    '        tests.append({"test_family": "feature_selection", "raw_p_value": None, "source": "model_x_knockoffs", "test_key": stable_hash(["model_x", model_x.get("source_generation_id"), model_x.get("fdr_target")]), "status": "NON_PVALUE_FDR_PROCEDURE"})\n',
    '    unique: dict[str, dict[str, Any]] = {}\n',
    '    for row in tests:\n',
    '        unique[str(row["test_key"])] = row\n',
    '    return list(unique.values())[:MAX_FDR_TESTS_PER_RUN]\n',
    '\n',
    '\n',
    'def apply_online_fdr(\n',
    '    tests: Sequence[Mapping[str, Any]],\n',
    '    *,\n',
    '    source_generation_id: str,\n',
    '    previous_state: Mapping[str, Any] | None = None,\n',
    '    fdr_target: float = DEFAULT_FDR_TARGET,\n',
    ') -> dict[str, Any]:\n',
    '    previous = dict(previous_state or {})\n',
    '    state_version = "online-fdr-alpha-investing-shadow-v1"\n',
    '    migration = "CONTINUED"\n',
    '    if previous.get("state_version") not in (None, state_version):\n',
    '        previous = {}\n',
    '        migration = "DETERMINISTIC_RESET_VERSION_CHANGE"\n',
    '    wealth = finite(previous.get("wealth"), float(fdr_target) / 2.0) or float(fdr_target) / 2.0\n',
    '    test_index = int(previous.get("test_index") or 0)\n',
    '    recent = [str(x) for x in (previous.get("recent_test_keys") or [])][-300:]\n',
    '    seen = set(recent)\n',
    '    records: list[dict[str, Any]] = []\n',
    '    for raw in tests:\n',
    '        key = str(raw.get("test_key") or stable_hash(raw))\n',
    '        p_value = finite(raw.get("raw_p_value"))\n',
    '        if key in seen:\n',
    '            continue\n',
    '        if p_value is None:\n',
    '            records.append({\n',
    '                "record_key": "FDR-" + stable_hash([source_generation_id, key])[:24],\n',
    '                "source_generation_id": source_generation_id, "test_key": key,\n',
    '                "test_family": raw.get("test_family"), "source_module": raw.get("source"),\n',
    '                "raw_p_value": None, "allocated_alpha": 0.0, "adjusted_result": "NOT_A_PVALUE_TEST",\n',
    '                "wealth_before": wealth, "wealth_after": wealth, "test_index": test_index,\n',
    '                "dependence_assumption": "not applicable", "calculation_version": VERSION,\n',
    '            })\n',
    '            recent.append(key); seen.add(key)\n',
    '            continue\n',
    '        p_value = float(max(0.0, min(1.0, p_value)))\n',
    '        test_index += 1\n',
    '        wealth_before = wealth\n',
    '        allocated = min(float(fdr_target), max(1e-8, wealth_before * _gamma(test_index)))\n',
    '        rejected = bool(p_value <= allocated)\n',
    '        if rejected:\n',
    '            wealth = min(float(fdr_target), wealth_before + float(fdr_target) * 0.25)\n',
    '        else:\n',
    '            wealth = max(1e-8, wealth_before - allocated / max(1.0 - allocated, 1e-8))\n',
    '        records.append({\n',
    '            "record_key": "FDR-" + stable_hash([source_generation_id, key, test_index])[:24],\n',
    '            "source_generation_id": source_generation_id, "test_key": key,\n',
    '            "test_family": raw.get("test_family"), "source_module": raw.get("source"),\n',
    '            "raw_p_value": p_value, "allocated_alpha": allocated,\n',
    '            "adjusted_result": "REJECT" if rejected else "DO_NOT_REJECT",\n',
    '            "wealth_before": wealth_before, "wealth_after": wealth, "test_index": test_index,\n',
    '            "dependence_assumption": "FDR theorem requires valid null p-values and independence/qualified dependence conditions",\n',
    '            "calculation_version": VERSION,\n',
    '        })\n',
    '        recent.append(key); seen.add(key)\n',
    '    state = {\n',
    '        "state_id": "ONLINE_FDR-" + stable_hash([source_generation_id, state_version])[:24], "state_version": state_version,\n',
    '        "updated_at": utc_now_iso(), "source_generation_id": source_generation_id,\n',
    '        "fdr_target": float(fdr_target), "wealth": float(wealth), "test_index": int(test_index),\n',
    '        "recent_test_keys": recent[-300:], "migration_action": migration,\n',
    '        "dependence_assumptions_documented": True, "fdr_control_claimed_for_production": False,\n',
    '        "calculation_version": VERSION,\n',
    '    }\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[1], "status": "SHADOW",\n',
    '        "controller_scope": "CENTRAL_ALL_SEQUENTIAL_TESTS", "records": records, "state": state,\n',
    '        "new_pvalue_test_count": int(sum(r["raw_p_value"] is not None for r in records)),\n',
    '        "rejection_count": int(sum(r["adjusted_result"] == "REJECT" for r in records)),\n',
    '        "unlimited_module_thresholds_allowed": False,\n',
    '        "dependence_assumptions": state["dependence_assumptions_documented"],\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 3: reject option\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def build_reject_option_shadow(\n',
    '    canonical: Mapping[str, Any], settled_predictions: pd.DataFrame,\n',
    '    *, source_generation_id: str, rejection_cost: float = DEFAULT_REJECTION_COST,\n',
    ') -> dict[str, Any]:\n',
    '    final = mapping(canonical.get("final_decision"))\n',
    '    protected = direction(final.get("tradeability_decision") or final.get("final_decision") or canonical.get("tradeability_decision"))\n',
    '    confidence = probability(final.get("calibrated_confidence"), probability(_value(canonical, "reliability.score"), 0.5)) or 0.5\n',
    '    uncertainty = probability(final.get("uncertainty_pct"), 1.0 - confidence) or (1.0 - confidence)\n',
    '    exit_risk_raw = finite(canonical.get("exit_risk"), 5.0) or 5.0\n',
    '    exit_risk = float(max(0.0, min(1.0, exit_risk_raw if exit_risk_raw <= 1.0 else exit_risk_raw / (10.0 if exit_risk_raw <= 10.0 else 100.0))))\n',
    '    conflict = probability(_value(canonical, "priority.conflict_score", "reliability.conflict_score"), 0.0) or 0.0\n',
    '    accepted_risk_estimate = float(max(0.0, min(1.0, 0.55 * (1.0 - confidence) + 0.20 * uncertainty + 0.15 * exit_risk + 0.10 * conflict)))\n',
    '    shadow = protected\n',
    '    if protected in {"BUY", "SELL"} and accepted_risk_estimate > float(rejection_cost):\n',
    '        shadow = "WAIT"\n',
    '    if protected == "WAIT":\n',
    '        shadow = "WAIT"\n',
    '    data = _settled(settled_predictions)\n',
    '    metrics = {"accepted_decision_risk": None, "coverage": None, "wait_rate": None, "missed_opportunity_rate": None, "sample_count": int(len(data))}\n',
    '    if not data.empty:\n',
    '        decisions = _text_series(data, ("final_decision", "tradeability_status")).map(direction)\n',
    '        confidences = _num_series(data, ("calibrated_confidence", "raw_confidence"))\n',
    '        confidences = confidences.where(confidences <= 1.0, confidences / 100.0).clip(0, 1)\n',
    '        correct = _num_series(data, ("direction_correct",)).clip(0, 1)\n',
    '        tradeable = decisions.isin(["BUY", "SELL"])\n',
    '        accepted = tradeable & (confidences >= 1.0 - float(rejection_cost))\n',
    '        rejected = tradeable & ~accepted\n',
    '        if tradeable.any():\n',
    '            metrics["coverage"] = float(accepted.sum() / tradeable.sum())\n',
    '            metrics["wait_rate"] = float(rejected.sum() / tradeable.sum())\n',
    '            metrics["missed_opportunity_rate"] = float(((rejected) & correct.eq(1)).sum() / tradeable.sum())\n',
    '        if accepted.any() and correct.notna().any():\n',
    '            metrics["accepted_decision_risk"] = float((1.0 - correct.loc[accepted]).mean())\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[2], "status": "SHADOW",\n',
    '        "source_generation_id": source_generation_id, "protected_decision": protected,\n',
    '        "shadow_reject_option_decision": shadow, "rejection_cost": float(rejection_cost),\n',
    '        "accepted_risk_estimate": accepted_risk_estimate, "metrics": metrics,\n',
    '        "protected_decision_visible_and_unchanged": True,\n',
    '        "existing_wait_promoted": False, "direction_reversal_allowed": False,\n',
    '        "production_influence_allowed": False,\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 4: flexible asymmetric loss\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    'FLEXIBLE_LOSS_DEFINITION = {\n',
    '    "version": "trading-flexible-loss-v1-fixed-before-evaluation",\n',
    '    "wrong_direction": 4.0,\n',
    '    "tp_late_proxy": 1.0,\n',
    '    "sl_first_proxy": 3.0,\n',
    '    "maximum_adverse_excursion": 1.5,\n',
    '    "interval_miss": 1.5,\n',
    '    "high_exit_risk_proxy": 1.0,\n',
    '}\n',
    '\n',
    '\n',
    'def _loss_rows(data: pd.DataFrame) -> pd.DataFrame:\n',
    '    if data.empty:\n',
    '        return pd.DataFrame()\n',
    '    result = pd.DataFrame(index=data.index)\n',
    '    correct = _num_series(data, ("direction_correct",)).clip(0, 1)\n',
    '    result["wrong_direction"] = 1.0 - correct\n',
    '    tp = _num_series(data, ("tp_touched",)).clip(0, 1)\n',
    '    sl = _num_series(data, ("sl_touched",)).clip(0, 1)\n',
    '    result["tp_late_proxy"] = ((correct.eq(1)) & tp.eq(0)).astype(float).where(correct.notna() & tp.notna())\n',
    '    result["sl_first_proxy"] = sl  # ledger has touch state, not exact first-touch ordering\n',
    '    mae = _num_series(data, ("maximum_adverse_excursion",)).abs()\n',
    '    scale = _num_series(data, ("expected_favorable_movement",)).abs().replace(0, np.nan)\n',
    '    if scale.notna().sum() < 8:\n',
    '        scale = mae.median() if mae.notna().any() else 1.0\n',
    '    result["maximum_adverse_excursion"] = (mae / scale).clip(0, 5) if isinstance(scale, pd.Series) else (mae / max(float(scale), 1e-9)).clip(0, 5)\n',
    '    interval_hit = _num_series(data, ("interval_hit",)).clip(0, 1)\n',
    '    result["interval_miss"] = 1.0 - interval_hit\n',
    '    adverse = _num_series(data, ("expected_adverse_movement",)).abs()\n',
    '    favorable = _num_series(data, ("expected_favorable_movement",)).abs().replace(0, np.nan)\n',
    '    result["high_exit_risk_proxy"] = (adverse / favorable).clip(0, 5)\n',
    '    weighted = pd.Series(0.0, index=result.index)\n',
    '    weight_support = pd.Series(0.0, index=result.index)\n',
    '    for component, weight in FLEXIBLE_LOSS_DEFINITION.items():\n',
    '        if component == "version":\n',
    '            continue\n',
    '        values = pd.to_numeric(result[component], errors="coerce")\n',
    '        weighted = weighted.add(values.fillna(0.0) * float(weight), fill_value=0.0)\n',
    '        weight_support = weight_support.add(values.notna().astype(float) * float(weight), fill_value=0.0)\n',
    '    result["flexible_loss"] = weighted / weight_support.replace(0, np.nan)\n',
    '    return result\n',
    '\n',
    '\n',
    'def evaluate_flexible_asymmetric_loss(\n',
    '    settled_predictions: pd.DataFrame, *, source_generation_id: str, minimum_samples: int = DEFAULT_MINIMUM_SAMPLES, embargo: int = 6,\n',
    ') -> dict[str, Any]:\n',
    '    data = _settled(settled_predictions)\n',
    '    windows = _chronological_windows(data, minimum_samples=minimum_samples, embargo=embargo)\n',
    '    rows: list[dict[str, Any]] = []\n',
    '    for name, train_window, test_window, boundaries in windows[:2]:\n',
    '        losses = _loss_rows(test_window)\n',
    '        component_means = {c: finite(losses[c].mean()) for c in losses.columns if c != "flexible_loss"}\n',
    '        value = finite(losses["flexible_loss"].mean()) if "flexible_loss" in losses else None\n',
    '        rows.append({\n',
    '            "evaluation_id": "LOSS-" + stable_hash([source_generation_id, name, FLEXIBLE_LOSS_DEFINITION])[:24],\n',
    '            "source_generation_id": source_generation_id, "window_id": name,\n',
    '            "window_start": boundaries["test_start"], "window_end": boundaries["test_end"],\n',
    '            "train_start": boundaries["train_start"], "train_end": boundaries["train_end"],\n',
    '            "test_start": boundaries["test_start"], "test_end": boundaries["test_end"],\n',
    '            "train_row_count": boundaries["train_row_count"], "test_row_count": boundaries["test_row_count"],\n',
    '            "purge_rows": embargo, "embargo_rows": embargo, "sample_count": int(losses["flexible_loss"].notna().sum()) if not losses.empty else 0,\n',
    '            "loss_definition_version": FLEXIBLE_LOSS_DEFINITION["version"],\n',
    '            "loss_weights": FLEXIBLE_LOSS_DEFINITION, "mean_flexible_loss": value,\n',
    '            "component_means": component_means, "status": "EVALUATED" if value is not None else "INSUFFICIENT_EVIDENCE",\n',
    '            "calculation_version": VERSION,\n',
    '        })\n',
    '    status = "SHADOW" if len(rows) >= 2 and all(r["status"] == "EVALUATED" for r in rows) else "INSUFFICIENT_EVIDENCE"\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[3], "status": status,\n',
    '        "loss_definition": FLEXIBLE_LOSS_DEFINITION, "windows": rows,\n',
    '        "weights_tuned_on_complete_history": False,\n',
    '        "existing_mae_rmse_brier_crps_interval_score_unchanged": True,\n',
    '        "limitations": ["TP-late and SL-first are conservative proxies because the current settled ledger stores touches, not ordered intrahour paths."],\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 5: explanations / SHAP routing\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _rule_contributions(canonical: Mapping[str, Any], protected: str) -> list[dict[str, Any]]:\n',
    '    raw = {\n',
    '        "Master score": finite(canonical.get("master_score"), 5.0),\n',
    '        "Entry score": finite(canonical.get("entry_score"), 5.0),\n',
    '        "Hold safety": finite(canonical.get("hold_safety"), 5.0),\n',
    '        "TP quality": finite(canonical.get("tp_quality"), 5.0),\n',
    '        "Exit risk": finite(canonical.get("exit_risk"), 5.0),\n',
    '        "Trend capacity": finite(canonical.get("trend_capacity_remaining"), 5.0),\n',
    '        "Reliability": finite(_value(canonical, "reliability.score"), 50.0),\n',
    '        "Forecast agreement": finite(_value(canonical, "forecasts.agreement_score", "priority.forecast_agreement"), 50.0),\n',
    '        "Conflict": finite(_value(canonical, "priority.conflict_score", "reliability.conflict_score"), 0.0),\n',
    '        "Data quality": finite(_value(canonical, "data_quality.score"), 50.0),\n',
    '    }\n',
    '    rows: list[dict[str, Any]] = []\n',
    '    for name, value in raw.items():\n',
    '        if value is None:\n',
    '            continue\n',
    '        if name in {"Reliability", "Forecast agreement", "Conflict", "Data quality"}:\n',
    '            centered = (float(value) - 50.0) / 50.0\n',
    '        else:\n',
    '            centered = (float(value) - 5.0) / 5.0\n',
    '        if name in {"Exit risk", "Conflict"}:\n',
    '            centered *= -1.0\n',
    '        rows.append({"factor": name, "contribution": float(centered), "method": "protected-rule-grouped-contribution"})\n',
    '    return sorted(rows, key=lambda r: abs(r["contribution"]), reverse=True)[:MAX_CACHE_FACTORS]\n',
    '\n',
    '\n',
    'def build_lightweight_explanations(canonical: Mapping[str, Any], *, source_generation_id: str) -> dict[str, Any]:\n',
    '    final = mapping(canonical.get("final_decision"))\n',
    '    protected = direction(final.get("tradeability_decision") or final.get("final_decision"))\n',
    '    grouped = _rule_contributions(canonical, protected)\n',
    '    supporting = [row for row in grouped if row["contribution"] > 0][:5]\n',
    '    opposing = [row for row in grouped if row["contribution"] < 0][:5]\n',
    '    wait_causing = [row for row in opposing if row["factor"] in {"Exit risk", "Conflict", "Reliability", "Data quality"}][:5]\n',
    '    raw_tree = mapping(canonical.get("tree_shap_explanations"))\n',
    '    raw_linear = mapping(canonical.get("linear_model_explanations"))\n',
    '    tree_descriptor = str(raw_tree.get("model_type") or raw_tree.get("estimator_type") or raw_tree.get("method") or "").lower()\n',
    '    tree_compatible = bool(raw_tree) and any(token in tree_descriptor for token in (\n',
    '        "treeshap", "tree_shap", "xgboost", "lightgbm", "catboost", "randomforest",\n',
    '        "random_forest", "decisiontree", "decision_tree", "gradientboost", "gradient_boost",\n',
    '    ))\n',
    '    linear_descriptor = str(raw_linear.get("model_type") or raw_linear.get("estimator_type") or raw_linear.get("method") or "").lower()\n',
    '    linear_compatible = bool(raw_linear) and (\n',
    '        any(token in linear_descriptor for token in ("linear", "logistic", "ridge", "lasso", "elastic"))\n',
    '        or any(key in raw_linear for key in ("coefficients", "contributions", "feature_contributions"))\n',
    '    )\n',
    '    precomputed_tree = _bounded_json(raw_tree, max_items=32) if tree_compatible else {}\n',
    '    linear = _bounded_json(raw_linear, max_items=32) if linear_compatible else {}\n',
    '    tree_status = "TREE_SHAP_CACHE_USED" if tree_compatible else "NO_COMPATIBLE_PRECOMPUTED_TREE_SHAP"\n',
    '    linear_status = "EXACT_LINEAR_CONTRIBUTIONS_USED" if linear_compatible else "NO_LINEAR_COEFFICIENT_PAYLOAD"\n',
    '    payload = {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[4], "status": "SHADOW",\n',
    '        "source_generation_id": source_generation_id, "canonical_calculation_id": source_generation_id,\n',
    '        "protected_decision": protected, "tree_shap_status": tree_status, "linear_status": linear_status,\n',
    '        "grouped_rule_contributions": grouped, "top_supporting_factors": supporting,\n',
    '        "top_opposing_factors": opposing, "wait_causing_factors": wait_causing,\n',
    '        "tree_shap": precomputed_tree if precomputed_tree else {}, "linear_contributions": linear if linear else {},\n',
    '        "attribution_is_causal_evidence": False,\n',
    '        "causality_notice": "Feature attribution explains model/rule output allocation; it is not causal evidence.",\n',
    '    }\n',
    '    payload["explanation_id"] = "EXP-" + stable_hash([source_generation_id, grouped, precomputed_tree, linear])[:24]\n',
    '    return payload\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 6: monotonicity contract validator\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    'MONOTONICITY_CONTRACT = (\n',
    '    ("exit_risk_vs_tradeability", "exit_risk", "tradeability", "NONINCREASING"),\n',
    '    ("uncertainty_vs_reliability", "uncertainty", "reliability", "NONINCREASING"),\n',
    '    ("data_quality_vs_reliability", "data_quality", "reliability", "NONDECREASING"),\n',
    '    ("conflict_vs_priority_quality", "conflict", "priority_quality", "NONINCREASING"),\n',
    '    ("forecast_support_vs_confidence", "model_agreement", "calibrated_confidence", "NONDECREASING"),\n',
    '    ("sample_support_vs_evidence_confidence", "sample_support", "evidence_confidence", "NONDECREASING"),\n',
    ')\n',
    '\n',
    '\n',
    'def _monotonic_violation_rate(x: pd.Series, y: pd.Series, expected: str, *, bins: int = 8) -> tuple[float | None, int, list[float]]:\n',
    '    frame = pd.DataFrame({"x": pd.to_numeric(x, errors="coerce"), "y": pd.to_numeric(y, errors="coerce")}).dropna()\n',
    '    if len(frame) < 24 or frame["x"].nunique() < 3:\n',
    '        return None, int(len(frame)), []\n',
    '    ranks = frame["x"].rank(method="first")\n',
    '    q = min(int(bins), max(3, int(math.sqrt(len(frame)))))\n',
    '    frame["bin"] = pd.qcut(ranks, q=q, duplicates="drop")\n',
    '    means = frame.groupby("bin", observed=True)["y"].mean().to_numpy(float)\n',
    '    diffs = np.diff(means)\n',
    '    tolerance = 1e-9\n',
    '    violations = diffs < -tolerance if expected == "NONDECREASING" else diffs > tolerance\n',
    '    return float(np.mean(violations)) if len(violations) else 0.0, int(len(frame)), means.tolist()\n',
    '\n',
    '\n',
    'def validate_monotonicity_contract(settled_predictions: pd.DataFrame, *, source_generation_id: str) -> dict[str, Any]:\n',
    '    data = _settled(settled_predictions)\n',
    '    tradeability = _text_series(data, ("final_decision", "tradeability_status")).map(lambda v: 1.0 if direction(v) in {"BUY", "SELL"} else 0.0)\n',
    '    confidence = _num_series(data, ("calibrated_confidence", "raw_confidence"))\n',
    '    confidence = confidence.where(confidence <= 1.0, confidence / 100.0).clip(0, 1)\n',
    '    reliability = _num_series(data, ("reliability_score", "reliability"))\n',
    '    reliability = reliability.where(reliability <= 1.0, reliability / 100.0).clip(0, 1)\n',
    '    if reliability.notna().sum() < 24:\n',
    '        reliability = _num_series(data, ("direction_correct",)).expanding(min_periods=12).mean()\n',
    '    exit_risk = _num_series(data, ("exit_risk", "expected_adverse_movement", "maximum_adverse_excursion")).abs()\n',
    '    exit_risk = exit_risk.where(exit_risk <= 1.0, exit_risk / 10.0).clip(0, 1)\n',
    '    conflict = _num_series(data, ("conflict_score",))\n',
    '    if conflict.notna().sum() < 24:\n',
    '        agreement = _num_series(data, ("model_agreement",))\n',
    '        agreement = agreement.where(agreement <= 1.0, agreement / 100.0).clip(0, 1)\n',
    '        conflict = 1.0 - agreement\n',
    '    else:\n',
    '        conflict = conflict.where(conflict <= 1.0, conflict / 100.0).clip(0, 1)\n',
    '    inputs = {\n',
    '        "exit_risk": exit_risk,\n',
    '        "tradeability": tradeability,\n',
    '        "uncertainty": 1.0 - confidence,\n',
    '        "reliability": reliability,\n',
    '        "data_quality": _text_series(data, ("data_quality_status",)).map({"FAIL": 0.0, "BLOCKED": 0.0, "WARNING": 0.5, "PASS": 1.0, "OK": 1.0}).astype(float),\n',
    '        "conflict": conflict,\n',
    '        "priority_quality": 1.0 / (1.0 + _num_series(data, ("priority", "greedy_rank")).clip(lower=0)),\n',
    '        "model_agreement": _num_series(data, ("model_agreement",)),\n',
    '        "calibrated_confidence": confidence,\n',
    '        "sample_support": pd.Series(np.arange(1, len(data) + 1), index=data.index, dtype=float),\n',
    '        "evidence_confidence": confidence.expanding(min_periods=1).mean(),\n',
    '    }\n',
    '    rows: list[dict[str, Any]] = []\n',
    '    for name, x_name, y_name, expected in MONOTONICITY_CONTRACT:\n',
    '        rate, support, bin_means = _monotonic_violation_rate(inputs[x_name], inputs[y_name], expected)\n',
    '        status = "INSUFFICIENT_EVIDENCE" if rate is None else "PASS" if rate <= 0.10 else "VIOLATION"\n',
    '        rows.append({\n',
    '            "record_key": "MONO-" + stable_hash([source_generation_id, name])[:24],\n',
    '            "source_generation_id": source_generation_id, "contract_name": name,\n',
    '            "input_name": x_name, "output_name": y_name, "expected_direction": expected,\n',
    '            "sample_support": support, "violation_rate": rate, "status": status,\n',
    '            "bin_means": bin_means, "calculation_version": VERSION,\n',
    '        })\n',
    '    evaluated = [r for r in rows if r["status"] != "INSUFFICIENT_EVIDENCE"]\n',
    '    overall = "PASS" if evaluated and all(r["status"] == "PASS" for r in evaluated) else "VIOLATION" if any(r["status"] == "VIOLATION" for r in evaluated) else "INSUFFICIENT_EVIDENCE"\n',
    '    return {\n',
    '        "version": VERSION, "paper": PAPER_TITLES[5], "status": overall,\n',
    '        "mode": "VALIDATOR_ONLY", "contract": [list(x) for x in MONOTONICITY_CONTRACT],\n',
    '        "results": rows, "protected_scores_altered": False, "constrained_model_promoted": False,\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Paper 7: exact incremental/delta maintenance\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    'HISTORY_DELTA_INVENTORY = (\n',
]
