"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '                st.info("No priority table found yet.")\n',
    '\n',
    '\n',
    'def _regime_best_action(m: Dict[str, Any]) -> str:\n',
    '    reliability = _num(m.get("Regime Reliable Score"), 0)\n',
    '    shift = _num(m.get("Transition Risk %"), 0)\n',
    '    conflict = str(m.get("Regime Conflict", "NO")).upper().startswith("Y")\n',
    '    direction = _direction_from_regime(m)\n',
    '    if conflict:\n',
    '        return "WAIT — forecast/regime conflict"\n',
    '    if reliability >= 75 and shift < 45 and direction in {"BUY", "SELL"}:\n',
    '        return f"FOLLOW {direction} bias with confirmation"\n',
    '    if reliability >= 60:\n',
    '        return "SMALL SIZE / WAIT for confirmation"\n',
    '    return "AVOID — regime not reliable"\n',
    '\n',
    '\n',
    'def _major_regime_history(ctx: Dict[str, Any]) -> pd.DataFrame:\n',
    '    hist = ctx.get("history", pd.DataFrame()) if isinstance(ctx, dict) else pd.DataFrame()\n',
    '    metrics = ctx.get("metrics", {}) if isinstance(ctx, dict) else {}\n',
    '    if not isinstance(hist, pd.DataFrame) or hist.empty:\n',
    '        return pd.DataFrame(columns=["Start Time", "End Time", "Duration Hours", "Duration Days", "Major Regime", "Avg Confidence", "Avg Reliability", "Shift Risk", "Best Trade Bias", "Result After Regime"])\n',
    '    out = hist.copy()\n',
    '    # Normalize names from the existing regime segment table. It is already aggregated by consecutive same-regime hours.\n',
    '    if "Start" in out.columns and "Start Time" not in out.columns:\n',
    '        out["Start Time"] = out["Start"]\n',
    '    if "End" in out.columns and "End Time" not in out.columns:\n',
    '        out["End Time"] = out["End"]\n',
    '    if "Regime" in out.columns and "Major Regime" not in out.columns:\n',
    '        out["Major Regime"] = out["Regime"]\n',
    '    if "Duration Hours" not in out.columns:\n',
    '        out["Duration Hours"] = 1\n',
    '    try:\n',
    '        out["End Time"] = pd.to_datetime(out["End Time"], errors="coerce")\n',
    '        max_end = out["End Time"].max()\n',
    '        if pd.notna(max_end):\n',
    '            out = out[out["End Time"] >= max_end - pd.Timedelta(days=25)]\n',
    '    except Exception:\n',
    '        pass\n',
    '    out["Duration Days"] = pd.to_numeric(out.get("Duration Hours", 0), errors="coerce").fillna(0) / 24.0\n',
    '    out["Avg Confidence"] = out.get("Avg Confidence", round(_num(metrics.get("Regime Confidence %"), 55), 1))\n',
    '    out["Avg Reliability"] = out.get("Avg Reliability", round(_num(metrics.get("Regime Reliable Score"), 55), 1))\n',
    '    out["Shift Risk"] = out.get("Shift Risk", round(_num(metrics.get("Transition Risk %"), 50), 1))\n',
    '    if "Regime Direction" in out.columns:\n',
    '        out["Best Trade Bias"] = out["Regime Direction"]\n',
    '    else:\n',
    '        out["Best Trade Bias"] = out["Major Regime"].astype(str).map(lambda x: "BUY" if "BULL" in x.upper() else "SELL" if "BEAR" in x.upper() else "WAIT")\n',
    '    if "Outcome pips" in out.columns:\n',
    '        def _result(row: pd.Series) -> str:\n',
    '            pips = _num(row.get("Outcome pips"), 0)\n',
    '            bias = str(row.get("Best Trade Bias", "WAIT")).upper()\n',
    '            if bias == "BUY" and pips > 0:\n',
    '                return f"Worked +{pips:.1f} pips"\n',
    '            if bias == "SELL" and pips < 0:\n',
    '                return f"Worked +{abs(pips):.1f} pips"\n',
    '            if abs(pips) < 1:\n',
    '                return "Flat / no edge"\n',
    '            return f"Failed {pips:.1f} pips"\n',
    '        out["Result After Regime"] = out.apply(_result, axis=1)\n',
    '    elif "Result After Regime" not in out.columns:\n',
    '        out["Result After Regime"] = "Need outcome history"\n',
    '    cols = ["Start Time", "End Time", "Duration Hours", "Duration Days", "Major Regime", "Avg Confidence", "Avg Reliability", "Shift Risk", "Best Trade Bias", "Result After Regime"]\n',
    '    out = out[[c for c in cols if c in out.columns]].sort_values("End Time", ascending=False).reset_index(drop=True)\n',
    '    if "Duration Days" in out.columns:\n',
    '        out["Duration Days"] = pd.to_numeric(out["Duration Days"], errors="coerce").round(2)\n',
    '    return out\n',
    '\n',
    '\n',
    'def _render_regime_intelligence_center(ns: dict) -> None:\n',
    '    st.markdown("### 🧭 Regime Intelligence Center")\n',
    '    st.caption("Regime tab is synced to the same Lunch/Data Visualization regime context, with only the important values shown first.")\n',
    '    a, b, c = st.columns([1.2, .8, 1.8])\n',
    '    if a.button("▶ Run Regime Sync", key=f"run_regime_clean_{UNIQUE}", use_container_width=True):\n',
    '        st.session_state[f"ready_{UNIQUE}"] = True\n',
    '        try:\n',
    '            _regime_context(ns, force=True)\n',
    '            _state_context(ns, force=False)\n',
    '        except Exception:\n',
    '            pass\n',
    '        try:\n',
    '            from core.styles import request_close_sidebar\n',
    '            request_close_sidebar()\n',
    '        except Exception:\n',
    '            pass\n',
    '    if b.button("Clear", key=f"clear_regime_clean_{UNIQUE}", use_container_width=True):\n',
    '        st.session_state[f"ready_{UNIQUE}"] = False\n',
    '    c.caption("No hourly regime spam by default. The table below aggregates consecutive same-regime periods over the last 25 days.")\n',
    '    if not st.session_state.get(f"ready_{UNIQUE}") and not isinstance(st.session_state.get("regime_context_20260614"), dict):\n',
    '        st.info("Click Run Regime Sync to load the compact regime summary and 25-day major regime history.")\n',
    '        return\n',
    '    ctx = _regime_context(ns, force=False)\n',
    '    m = ctx.get("metrics", {}) if isinstance(ctx, dict) else {}\n',
    '    trust = "Trusted" if _num(m.get("Regime Reliable Score"), 0) >= 70 and _num(m.get("Transition Risk %"), 100) < 55 else "Caution / Not trusted"\n',
    '    top = {\n',
    '        "Current Regime": m.get("Current Regime", "-"),\n',
    '        "Regime Confidence": _fmt(m.get("Regime Confidence %", 0), "%"),\n',
    '        "Regime Reliability": _fmt(m.get("Regime Reliable Score", 0), "%"),\n',
    '        "Regime Age": f"{int(_num(m.get(\'Regime Age Hours\'), 0))}h",\n',
    '        "Shift Risk": _fmt(m.get("Transition Risk %", 0), "%"),\n',
    '        "Regime Best Action": _regime_best_action(m),\n',
    '        "Regime Trust Reason": f"{trust}; source: {m.get(\'Regime Sync Source\', \'existing sync context\')}",\n',
    '    }\n',
    '    c1, c2, c3 = st.columns(3)\n',
    '    c1.metric("Current Regime", top["Current Regime"])\n',
    '    c2.metric("Confidence", top["Regime Confidence"])\n',
    '    c3.metric("Reliability", top["Regime Reliability"])\n',
    '    c4, c5, c6 = st.columns(3)\n',
    '    c4.metric("Age", top["Regime Age"])\n',
    '    c5.metric("Shift Risk", top["Shift Risk"])\n',
    '    c6.metric("Best Action", top["Regime Best Action"])\n',
    '    st.info(top["Regime Trust Reason"])\n',
    '\n',
    '    table = _major_regime_history(ctx)\n',
    '    st.markdown("#### 25-Day Major Regime History Table")\n',
    '    st.caption("Consecutive same-regime hours are merged into one period. This replaces the annoying every-hour regime table by default.")\n',
    '    if isinstance(table, pd.DataFrame) and not table.empty:\n',
    '        st.dataframe(table, use_container_width=True, hide_index=True, height=420)\n',
    '    else:\n',
    '        st.info("Need more regime/H1 history to build the 25-day major regime table.")\n',
    '\n',
    '    with st.expander("Advanced Details — full regime metrics and KNN/Greedy regime similarity", expanded=False):\n',
    '        if m:\n',
    '            st.dataframe(pd.DataFrame([{"Metric": k, "Value": v} for k, v in m.items()]), use_container_width=True, hide_index=True, height=360)\n',
    '        knn = ctx.get("knn", pd.DataFrame()) if isinstance(ctx, dict) else pd.DataFrame()\n',
    '        if isinstance(knn, pd.DataFrame) and not knn.empty:\n',
    '            st.markdown("##### Similar Historical Regimes")\n',
    '            st.dataframe(knn, use_container_width=True, hide_index=True, height=300)\n',
    '        text = _safe_json({"top_summary": top, "metrics": m, "major_regime_history": table.to_dict("records") if isinstance(table, pd.DataFrame) else []})\n',
    '        _copy_button("📋 Copy Regime Intelligence Summary", text, f"copy_regime_intelligence_{UNIQUE}")\n',
    '        st.download_button("⬇️ Download Regime Intelligence JSON", text, file_name="regime_intelligence_center.json", mime="application/json", use_container_width=True, key=f"download_regime_intelligence_{UNIQUE}")\n',
    '\n',
    '\n',
    'def _compact_no_history_text(ns: dict) -> str:\n',
    '    build = ns.get("_build_lunch_all_copy_text")\n',
    '    try:\n',
    '        full = build() if callable(build) else "Run Calculation first; copy builder is not ready."\n',
    '    except Exception as exc:\n',
    '        full = f"Run Calculation first; copy builder failed safely: {exc}"\n',
    '    lines = str(full).splitlines()\n',
    '    keep: List[str] = []\n',
    '    skip_markers = ["history", "25d", "25-day", "backtest rows", "regime_history", "full_metric_history", "candles", "rows"]\n',
    '    for line in lines:\n',
    '        low = line.lower()\n',
    '        if any(m in low for m in skip_markers) and len(keep) > 18:\n',
    '            continue\n',
    '        keep.append(line)\n',
    '        if len(keep) >= 260:\n',
    '            break\n',
    '    return "LUNCH COMPACT FULL COPY — NO HISTORY\\n" + "=" * 64 + "\\n" + "\\n".join(keep).strip()\n',
    '\n',
    '\n',
    'def _render_no_history_copy(ns: dict) -> None:\n',
    '    with st.expander("📋 Open / Close — Lunch Compact Full Copy — No History", expanded=False):\n',
    '        text = _compact_no_history_text(ns)\n',
    '        c1, c2 = st.columns([1, .75])\n',
    '        with c1:\n',
    '            _copy_button("📋 Copy Compact Full — No History", text, f"copy_compact_no_history_clean_{UNIQUE}")\n',
    '        with c2:\n',
    '            st.download_button("⬇️ Download No-History TXT", text, file_name="lunch_compact_full_no_history.txt", mime="text/plain", use_container_width=True, key=f"download_compact_no_history_clean_{UNIQUE}")\n',
    '\n',
    '\n',
    'def _render_data_visualization(prev_data) -> None:\n',
    '    with st.expander("📊 Open / Close — Data Visualization inside Lunch", expanded=False):\n',
    '        st.caption("Preserved from the previous working ZIP. It stays collapsed so Home/Lunch is cleaner.")\n',
    '        if callable(prev_data):\n',
    '            prev_data()\n',
    '        else:\n',
    '            st.warning("Data Visualization renderer is not available in this ZIP.")\n',
    '\n',
    '\n',
    'def _render_research_with_ai(prev_research) -> None:\n',
    '    st.markdown("### 🎓 Research Inner Tab")\n',
    '    research_tab, ai_tab = st.tabs(["Research Pack", "AI Assistant Lite"])\n',
    '    with research_tab:\n',
    '        if callable(prev_research):\n',
    '            prev_research()\n',
    '        else:\n',
    '            try:\n',
    '                import tabs.research as research\n',
    '                research.show()\n',
    '            except Exception as exc:\n',
    '                st.error("Research tab could not load safely.")\n',
    '                st.exception(exc)\n',
    '    with ai_tab:\n',
    '        try:\n',
    '            from .ai_assistant_lite import render_ai_assistant_lite_tab\n',
    '        except Exception:\n',
    '            from tabs.ai_assistant_lite import render_ai_assistant_lite_tab\n',
    '        render_ai_assistant_lite_tab()\n',
    '\n',
    '\n',
    'def _selector() -> str:\n',
    '    choices = [("Lunch", "🍱"), ("Regime", "🧭"), ("Research", "🎓"), ("Doo Prime", "🏦")]\n',
    '    current = st.session_state.get("home_inner_tab", "Lunch")\n',
    '    if current in {"AI Assistant Lite", "Data Visualization"}:\n',
    '        current = "Research" if current == "AI Assistant Lite" else "Lunch"\n',
    '        st.session_state["home_inner_tab"] = current\n',
    '    names = [x[0] for x in choices]\n',
    '    if current not in names:\n',
    '        current = "Lunch"\n',
    '        st.session_state["home_inner_tab"] = current\n',
    '    cols = st.columns(len(choices))\n',
    '    for idx, (name, icon) in enumerate(choices):\n',
    '        active = st.session_state.get("home_inner_tab", current) == name\n',
    '        if cols[idx].button(("✅ " if active else "") + f"{icon} {name}", use_container_width=True, key=f"home_clean_inner_{idx}_{UNIQUE}"):\n',
    '            st.session_state["home_inner_tab"] = name\n',
    '            st.session_state["ui_navigation_click_ts"] = time.time()\n',
    '            try:\n',
    '                from core.styles import request_close_sidebar\n',
    '                request_close_sidebar()\n',
    '            except Exception:\n',
    '                pass\n',
    '            try:\n',
    '                st.rerun()\n',
    '            except Exception:\n',
    '                pass\n',
    '    return st.session_state.get("home_inner_tab", current)\n',
    '\n',
    '\n',
    'def _summary_copy(ns: dict, compact: bool = False) -> str:\n',
    '    if not _run_ready():\n',
    '        return "\\n\\nCLEAN DECISION UI SUMMARY\\nPress Run Calculating first."\n',
    '    ctx = _state_context(ns, force=False)\n',
    '    rctx = _regime_context(ns, force=False)\n',
    '    decision = _decision_summary(ns, ctx, rctx)\n',
    '    priority = _priority_summary(ns, ctx)\n',
    '    regime_table = _major_regime_history(rctx)\n',
    '    payload = {\n',
    '        "Decision Control Panel": decision,\n',
    '        "System Trust Center": {\n',
    '            "Robustness Score": ctx.get("summary", {}).get("Forecast Robustness Score") if isinstance(ctx, dict) else None,\n',
    '            "Data Quality Score": ctx.get("data_quality_market_feed_health", {}).get("Data Quality Score") if isinstance(ctx, dict) else None,\n',
    '            "Leakage Risk": ctx.get("feature_leakage_guard", {}).get("Leakage Risk %") if isinstance(ctx, dict) else None,\n',
    '            "Drift Risk": ctx.get("distribution_shift_wasserstein_style_drift", {}).get("Drift Warning") if isinstance(ctx, dict) else None,\n',
    '            "Forecast Freshness": ctx.get("model_decay_forecast_freshness", {}).get("Prediction Freshness") if isinstance(ctx, dict) else None,\n',
    '            "Main Weakness": ctx.get("summary", {}).get("Main Weakness") if isinstance(ctx, dict) else None,\n',
    '            "Best Action": ctx.get("summary", {}).get("Best Action Now") if isinstance(ctx, dict) else None,\n',
    '        },\n',
    '        "Dynamic Entry Priority Center": priority,\n',
    '        "Regime Intelligence Center": rctx.get("metrics", {}) if isinstance(rctx, dict) else {},\n',
    '    }\n',
    '    if not compact:\n',
    '        payload["25-Day Major Regime History Table"] = regime_table.to_dict("records") if isinstance(regime_table, pd.DataFrame) else []\n',
    '    return "\\n\\nCLEAN DECISION / SYSTEM TRUST / REGIME UI SUMMARY\\n" + _safe_json(payload)\n',
    '\n',
    '\n',
    'def install(ns: dict) -> None:\n',
    '    if ns.get("_clean_decision_regime_ui_installed_20260614"):\n',
    '        return\n',
    '\n',
    '    # Ensure the older builder functions are available, but do not show the old detailed renderer by default.\n',
    '    try:\n',
    '        from .reliability_control_center_20260614 import install as _install_rcc\n',
    '    except Exception:\n',
    '        from tabs.reliability_control_center_20260614 import install as _install_rcc\n',
    '    try:\n',
    '        _install_rcc(ns)\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '    prev_full = ns.get("_build_lunch_all_copy_text")\n',
    '    prev_short = ns.get("_build_short_necessary_copy_text")\n',
    '\n',
    '    def _full_with_clean_summary() -> str:\n',
    '        base = prev_full() if callable(prev_full) else ""\n',
    '        return str(base) + _summary_copy(ns, compact=False)\n',
    '\n',
    '    def _short_with_clean_summary() -> str:\n',
    '        base = prev_short() if callable(prev_short) else ""\n',
    '        return str(base) + _summary_copy(ns, compact=True)\n',
    '\n',
    '    if callable(prev_full):\n',
    '        ns["_build_lunch_all_copy_text"] = _full_with_clean_summary\n',
    '    if callable(prev_short):\n',
    '        ns["_build_short_necessary_copy_text"] = _short_with_clean_summary\n',
    '\n',
    '    prev_lunch = ns.get("_render_metric_home_combined_inner_tab")\n',
    '    prev_data = ns.get("_render_lunch_data_visualization_inner_tab")\n',
    '    prev_research = ns.get("_render_home_research_inner_20260612")\n',
    '    prev_doo = ns.get("_render_doo_prime_inner_tab")\n',
    '    footer = ns.get("render_tab_footer")\n',
    '\n',
    '    def _show_clean() -> None:\n',
    '        try:\n',
    '            from core.streamlit_safe_dataframe import install_safe_dataframe_patch\n',
    '            install_safe_dataframe_patch()\n',
    '        except Exception:\n',
    '            pass\n',
    '        selected = _selector()\n',
    '        if selected == "Lunch":\n',
    '            _render_decision_control_panel(ns)\n',
    '            if callable(prev_lunch):\n',
    '                prev_lunch()\n',
    '            else:\n',
    '                st.warning("Lunch renderer is not available.")\n',
    '            _render_system_trust_center(ns)\n',
    '            _render_dynamic_entry_priority_center(ns)\n',
    '            _render_no_history_copy(ns)\n',
    '            _render_data_visualization(prev_data)\n',
    '        elif selected == "Regime":\n',
    '            _render_regime_intelligence_center(ns)\n',
    '        elif selected == "Research":\n',
    '            _render_research_with_ai(prev_research)\n',
    '        else:\n',
    '            if callable(prev_doo):\n',
    '                prev_doo()\n',
    '            else:\n',
    '                st.info("Doo Prime inner tab is not available in this ZIP.")\n',
    '        if callable(footer):\n',
    '            try:\n',
    '                footer("Lunch")\n',
    '            except Exception:\n',
    '                pass\n',
    '\n',
    '    ns["show"] = _show_clean\n',
    '    ns["render_regime_inner_tab_20260614"] = lambda: _render_regime_intelligence_center(ns)\n',
    '    ns["build_clean_decision_summary_20260614"] = lambda compact=False: _summary_copy(ns, compact=compact)\n',
    '    ns["_clean_decision_regime_ui_installed_20260614"] = True\n',
]
