"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Clean Decision / System Trust / Regime Intelligence UI patch (2026-06-14).\n',
    '\n',
    'Display-only reorganizer. It does not remove calculations, models, ML tables,\n',
    'exports, or source metric logic. Older detail outputs remain available through\n',
    'advanced expanders; the visible Home/Lunch and Regime views become smaller and\n',
    'more mobile-friendly.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import json\n',
    'import math\n',
    'import re\n',
    'import time\n',
    'from typing import Any, Dict, Iterable, List, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    'import streamlit as st\n',
    '\n',
    'UNIQUE = "20260614_clean_decision_regime_ui"\n',
    '\n',
    '\n',
    'def _num(v: Any, default: float = 0.0) -> float:\n',
    '    try:\n',
    '        if v is None or v == "":\n',
    '            return float(default)\n',
    '        if isinstance(v, str):\n',
    '            v = v.replace("%", "").replace("/10", "").replace(",", "").strip()\n',
    '            if "→" in v or "above" in v.lower():\n',
    '                m = re.search(r"-?\\d+(?:\\.\\d+)?", v)\n',
    '                v = m.group(0) if m else default\n',
    '        x = float(v)\n',
    '        return x if math.isfinite(x) else float(default)\n',
    '    except Exception:\n',
    '        return float(default)\n',
    '\n',
    '\n',
    'def _clip(v: Any, lo: float = 0.0, hi: float = 100.0) -> float:\n',
    '    return float(max(lo, min(hi, _num(v, lo))))\n',
    '\n',
    '\n',
    'def _norm(v: Any) -> str:\n',
    '    return re.sub(r"[^a-z0-9]+", "", str(v).lower())\n',
    '\n',
    '\n',
    'def _fmt(v: Any, suffix: str = "") -> str:\n',
    '    if isinstance(v, (int, float, np.number)) and math.isfinite(float(v)):\n',
    '        x = float(v)\n',
    '        if suffix == "%":\n',
    '            return f"{x:.1f}%"\n',
    '        if abs(x) >= 100:\n',
    '            return f"{x:.0f}{suffix}"\n',
    '        return f"{x:.2f}{suffix}"\n',
    '    return str(v)\n',
    '\n',
    '\n',
    'def _copy_button(label: str, text: str, key: str) -> None:\n',
    '    try:\n',
    '        from streamlit_copy_button import copy_button\n',
    '        copy_button(text, label, key=key)\n',
    '    except Exception:\n',
    '        try:\n',
    '            from core.pro_terminal_uiux import render_mobile_copy_button\n',
    '            render_mobile_copy_button(label, text, key)\n',
    '        except Exception:\n',
    '            st.text_area(label, text, height=160, key=key + "_fallback")\n',
    '\n',
    '\n',
    'def _safe_json(obj: Any) -> str:\n',
    '    return json.dumps(obj, indent=2, default=str, ensure_ascii=False)\n',
    '\n',
    '\n',
    'def _run_ready() -> bool:\n',
    '    return bool(st.session_state.get("metric_run_calculate", False) or st.session_state.get(f"ready_{UNIQUE}", False))\n',
    '\n',
    '\n',
    'def _state_context(ns: dict, force: bool = False) -> Dict[str, Any]:\n',
    '    builder = ns.get("build_reliability_control_center_20260614")\n',
    '    if callable(builder):\n',
    '        try:\n',
    '            return builder(force=force) or {}\n',
    '        except TypeError:\n',
    '            try:\n',
    '                return builder(force) or {}\n',
    '            except Exception:\n',
    '                return {}\n',
    '        except Exception:\n',
    '            return {}\n',
    '    return st.session_state.get("reliability_control_center_20260614", {}) if isinstance(st.session_state.get("reliability_control_center_20260614"), dict) else {}\n',
    '\n',
    '\n',
    'def _regime_context(ns: dict, force: bool = False) -> Dict[str, Any]:\n',
    '    builder = ns.get("build_regime_context_20260614")\n',
    '    if callable(builder):\n',
    '        try:\n',
    '            return builder(force=force) or {}\n',
    '        except TypeError:\n',
    '            try:\n',
    '                return builder(force) or {}\n',
    '            except Exception:\n',
    '                return {}\n',
    '        except Exception:\n',
    '            return {}\n',
    '    ctx = st.session_state.get("regime_context_20260614")\n',
    '    return ctx if isinstance(ctx, dict) else {}\n',
    '\n',
    '\n',
    'def _priority_table(ns: dict, ctx: Dict[str, Any]) -> pd.DataFrame:\n',
    '    obj = st.session_state.get("reliability_dynamic_priority_table_20260614")\n',
    '    if isinstance(obj, pd.DataFrame) and not obj.empty:\n',
    '        return obj.copy()\n',
    '    records = ctx.get("priority_table_preview", []) if isinstance(ctx, dict) else []\n',
    '    if records:\n',
    '        try:\n',
    '            return pd.DataFrame(records)\n',
    '        except Exception:\n',
    '            pass\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _find_col(df: pd.DataFrame, aliases: Iterable[str]) -> str | None:\n',
    '    if not isinstance(df, pd.DataFrame) or df.empty:\n',
    '        return None\n',
    '    nmap = {_norm(c): c for c in df.columns}\n',
    '    for alias in aliases:\n',
    '        na = _norm(alias)\n',
    '        if na in nmap:\n',
    '            return nmap[na]\n',
    '    for nk, col in nmap.items():\n',
    '        for alias in aliases:\n',
    '            na = _norm(alias)\n',
    '            if na and na in nk:\n',
    '                return col\n',
    '    return None\n',
    '\n',
    '\n',
    'def _series(df: pd.DataFrame, aliases: Iterable[str], default: float = 0.0) -> pd.Series:\n',
    '    col = _find_col(df, aliases)\n',
    '    if col is None:\n',
    '        return pd.Series(default, index=df.index, dtype=float)\n',
    '    return pd.to_numeric(df[col], errors="coerce").fillna(default).astype(float)\n',
    '\n',
    '\n',
    'def _hour_text_from_row(row: pd.Series) -> str:\n',
    '    for key in ["Time", "Datetime", "Date", "Timestamp", "Start Time", "End Time"]:\n',
    '        if key in row.index:\n',
    '            try:\n',
    '                t = pd.to_datetime(row[key], errors="coerce")\n',
    '                if pd.notna(t):\n',
    '                    return t.strftime("%m-%d %H:00")\n',
    '            except Exception:\n',
    '                pass\n',
    '    for key in ["Hour", "hour"]:\n',
    '        if key in row.index:\n',
    '            return f"H{int(_num(row[key], 0)) % 24:02d}"\n',
    '    return "hour n/a"\n',
    '\n',
    '\n',
    'def _priority_label(score: float) -> str:\n',
    '    x = _clip(score)\n',
    '    if x >= 90:\n',
    '        return "A+ Elite"\n',
    '    if x >= 80:\n',
    '        return "A Strong"\n',
    '    if x >= 70:\n',
    '        return "B+ Good"\n',
    '    if x >= 60:\n',
    '        return "B Watch"\n',
    '    if x >= 45:\n',
    '        return "C Weak"\n',
    '    return "Avoid"\n',
    '\n',
    '\n',
    'def _priority_rank_1_14(score: float) -> int:\n',
    '    # 1 is best, 14 is avoid. This only translates an existing priority score.\n',
    '    return int(max(1, min(14, round(15 - _clip(score) / 100 * 14))))\n',
    '\n',
    '\n',
    'def _priority_summary(ns: dict, ctx: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    p = ctx.get("priority_anti_constant_engine", {}) if isinstance(ctx, dict) else {}\n',
    '    tab = _priority_table(ns, ctx)\n',
    '    score = 60.0\n',
    '    best_2 = "Need Run Calculation"\n',
    '    label = "Watch"\n',
    '    if isinstance(tab, pd.DataFrame) and not tab.empty:\n',
    '        score_s = _series(tab, ["Greedy Score", "KNN Priority Score", "Priority Score", "Reliability Score"], 60)\n',
    '        score = float(score_s.tail(min(len(score_s), 24)).max()) if len(score_s) else 60.0\n',
    '        label_col = _find_col(tab, ["Priority Label", "Label", "Decision"])\n',
    '        try:\n',
    '            work = tab.copy()\n',
    '            work["_score"] = score_s\n',
    '            top = work.sort_values("_score", ascending=False).head(2)\n',
    '            chunks = []\n',
    '            for _, row in top.iterrows():\n',
    '                lab = str(row.get(label_col, _priority_label(row.get("_score", 60)))) if label_col else _priority_label(row.get("_score", 60))\n',
    '                chunks.append(f"{_hour_text_from_row(row)} ({_fmt(row.get(\'_score\', 0))}, {lab})")\n',
    '            if chunks:\n',
    '                best_2 = "; ".join(chunks)\n',
    '            if label_col and len(top):\n',
    '                label = str(top.iloc[0].get(label_col, _priority_label(score)))\n',
    '            else:\n',
    '                label = _priority_label(score)\n',
    '        except Exception:\n',
    '            label = _priority_label(score)\n',
    '    constant = p.get("Constant Score Warning", "Need priority table")\n',
    '    movement = _num(p.get("Priority Movement Score"), 0)\n',
    '    reason = "Score moves by hour using existing metrics, hour/session shape, risk, quality, and regime/forecast conflict."\n',
    '    if "constant" in str(constant).lower():\n',
    '        reason = "Constant-score warning active; display reliability downgraded until hourly scores move."\n',
    '    return {\n',
    '        "Priority Rank 1-14": _priority_rank_1_14(score),\n',
    '        "Priority Label": label,\n',
    '        "Best 2 Hours": best_2,\n',
    '        "Priority Movement Score": round(movement, 1),\n',
    '        "Constant Score Warning": constant,\n',
    '        "Why priority changed": reason,\n',
    '        "Dynamic Priority Reliability": p.get("Dynamic Priority Reliability", 0),\n',
    '        "_score": score,\n',
    '    }\n',
    '\n',
    '\n',
    'def _direction_from_regime(metrics: Dict[str, Any]) -> str:\n',
    '    direct = str(metrics.get("Regime Direction", "")).upper()\n',
    '    if direct in {"BUY", "SELL", "WAIT"}:\n',
    '        return direct\n',
    '    reg = str(metrics.get("Current Regime", "")).upper()\n',
    '    if "BULL" in reg:\n',
    '        return "BUY"\n',
    '    if "BEAR" in reg:\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _decision_summary(ns: dict, ctx: Dict[str, Any], rctx: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    s = ctx.get("summary", {}) if isinstance(ctx, dict) else {}\n',
    '    q = ctx.get("data_quality_market_feed_health", {}) if isinstance(ctx, dict) else {}\n',
    '    leak = ctx.get("feature_leakage_guard", {}) if isinstance(ctx, dict) else {}\n',
    '    drift = ctx.get("distribution_shift_wasserstein_style_drift", {}) if isinstance(ctx, dict) else {}\n',
    '    anomaly = ctx.get("anomaly_and_shock_detector", {}) if isinstance(ctx, dict) else {}\n',
    '    fresh = ctx.get("model_decay_forecast_freshness", {}) if isinstance(ctx, dict) else {}\n',
    '    mfe = ctx.get("mfe_mae_exit_control", {}) if isinstance(ctx, dict) else {}\n',
    '    rm = rctx.get("metrics", {}) if isinstance(rctx, dict) else {}\n',
    '    ps = _priority_summary(ns, ctx)\n',
    '\n',
    '    robustness = _num(s.get("Forecast Robustness Score"), 0)\n',
    '    regime_rel = _num(rm.get("Regime Reliable Score", ctx.get("regime_state_reliability", {}).get("Regime Reliability Score", 0) if isinstance(ctx, dict) else 0), 0)\n',
    '    priority_rel = _num(ps.get("Dynamic Priority Reliability"), 0)\n',
    '    data_quality = _num(q.get("Data Quality Score"), 0)\n',
    '    leakage_risk = _num(leak.get("Leakage Risk %"), 0)\n',
    '    anomaly_score = _num(anomaly.get("Anomaly Score"), 0)\n',
    '    freshness = _num(fresh.get("Prediction Freshness", fresh.get("Decayed Confidence Score", 0)), 0)\n',
    '    confidence = _clip(robustness * .36 + regime_rel * .22 + priority_rel * .18 + data_quality * .14 + freshness * .10 - leakage_risk * .16 - max(0, anomaly_score - 50) * .18)\n',
    '    risk = _clip(100 - confidence + leakage_risk * .25 + max(0, anomaly_score - 55) * .30)\n',
    '    direction = _direction_from_regime(rm) if rm else str(ctx.get("regime_state_reliability", {}).get("Current Regime", "WAIT"))\n',
    '    if direction not in {"BUY", "SELL", "WAIT"}:\n',
    '        direction = "BUY" if "BULL" in direction.upper() else "SELL" if "BEAR" in direction.upper() else "WAIT"\n',
    '    do_not_trade = []\n',
    '    if leakage_risk >= 65:\n',
    '        do_not_trade.append("leakage risk high")\n',
    '    if str(drift.get("Drift Warning", "")).lower().startswith("danger"):\n',
    '        do_not_trade.append("distribution drift dangerous")\n',
    '    if anomaly_score >= 65:\n',
    '        do_not_trade.append("shock/anomaly high")\n',
    '    if risk >= 70:\n',
    '        do_not_trade.append("risk too high")\n',
    '    if "constant" in str(ps.get("Constant Score Warning", "")).lower():\n',
    '        do_not_trade.append("priority constant")\n',
    '\n',
    '    if do_not_trade:\n',
    '        status = "Avoid"\n',
    '    elif confidence >= 78 and risk < 45 and direction in {"BUY", "SELL"}:\n',
    '        status = "Enter"\n',
    '    elif confidence >= 62 and risk < 62:\n',
    '        status = "Wait"\n',
    '    else:\n',
    '        status = "Protect / Wait"\n',
    '    reason = s.get("Main Weakness", "System trust")\n',
    '    if status == "Enter":\n',
    '        reason = f"Robustness {robustness:.1f}, regime reliability {regime_rel:.1f}, and dynamic priority support {direction}."\n',
    '    elif do_not_trade:\n',
    '        reason = "Blocked by " + ", ".join(do_not_trade[:3])\n',
    '    else:\n',
    '        reason = f"Main weakness: {reason}; wait for better confirmation."\n',
    '    return {\n',
    '        "Trade Status": status,\n',
    '        "Direction": direction,\n',
    '        "Confidence %": round(confidence, 1),\n',
    '        "Risk %": round(risk, 1),\n',
    '        "Best TP Zone": mfe.get("Safer TP Zone", "Need history"),\n',
    '        "Danger SL Zone": mfe.get("Danger SL Zone", "Need history"),\n',
    '        "Main Reason": reason,\n',
    '        "Do-not-trade warning": "YES — " + ", ".join(do_not_trade) if do_not_trade else "NO hard block detected",\n',
    '        "Priority Rank": ps.get("Priority Rank 1-14"),\n',
    '        "Regime Trust Reason": s.get("Why regime is trusted or not trusted", "Need regime sync"),\n',
    '    }\n',
    '\n',
    '\n',
    'def _detail_rows(ctx: Dict[str, Any], include: Iterable[str]) -> pd.DataFrame:\n',
    '    rows: List[Dict[str, Any]] = []\n',
    '    for key in include:\n',
    '        block = ctx.get(key, {}) if isinstance(ctx, dict) else {}\n',
    '        title = key.replace("_", " ").title()\n',
    '        if isinstance(block, dict):\n',
    '            for k, v in block.items():\n',
    '                if str(k).startswith("_"):\n',
    '                    continue\n',
    '                rows.append({"Group": title, "Check": k, "Value": v})\n',
    '    return pd.DataFrame(rows)\n',
    '\n',
    '\n',
    'def _render_decision_control_panel(ns: dict) -> None:\n',
    '    if not _run_ready():\n',
    '        with st.expander("🎛️ Decision Control Panel", expanded=True):\n',
    '            st.info("Press **Run Calculating** first. The decision panel stays idle to keep iPhone 11 Pro performance stable.")\n',
    '        return\n',
    '    ctx = _state_context(ns, force=False)\n',
    '    rctx = _regime_context(ns, force=False)\n',
    '    d = _decision_summary(ns, ctx, rctx)\n',
    '    with st.container():\n',
    '        st.markdown("### 🎛️ Decision Control Panel")\n',
    '        c1, c2, c3, c4 = st.columns(4)\n',
    '        c1.metric("Trade Status", d.get("Trade Status", "-"))\n',
    '        c2.metric("Direction", d.get("Direction", "-"))\n',
    '        c3.metric("Confidence", _fmt(d.get("Confidence %", 0), "%"))\n',
    '        c4.metric("Risk", _fmt(d.get("Risk %", 0), "%"))\n',
    '        c5, c6 = st.columns(2)\n',
    '        c5.metric("Best TP Zone", d.get("Best TP Zone", "-"))\n',
    '        c6.metric("Danger SL Zone", d.get("Danger SL Zone", "-"))\n',
    '        st.info(str(d.get("Main Reason", "-")))\n',
    '        st.caption(f"Do-not-trade warning: {d.get(\'Do-not-trade warning\', \'-\')}")\n',
    '\n',
    '\n',
    'def _render_system_trust_center(ns: dict) -> None:\n',
    '    with st.expander("🛡️ Open / Close — System Trust Center", expanded=False):\n',
    '        st.caption("Merged Reliability Control Center, Forecast Robustness, Data Quality, Leakage, Drift, Anomaly, and Forecast Freshness into one compact view.")\n',
    '        if not _run_ready():\n',
    '            st.info("Press **Run Calculating** first. System Trust Center will not run heavy checks on open.")\n',
    '            return\n',
    '        if st.button("▶ Refresh System Trust Center", key=f"refresh_system_trust_{UNIQUE}", use_container_width=True):\n',
    '            st.session_state.pop("reliability_control_center_20260614", None)\n',
    '        ctx = _state_context(ns, force=False)\n',
    '        summary = ctx.get("summary", {}) if isinstance(ctx, dict) else {}\n',
    '        quality = ctx.get("data_quality_market_feed_health", {}) if isinstance(ctx, dict) else {}\n',
    '        leak = ctx.get("feature_leakage_guard", {}) if isinstance(ctx, dict) else {}\n',
    '        drift = ctx.get("distribution_shift_wasserstein_style_drift", {}) if isinstance(ctx, dict) else {}\n',
    '        fresh = ctx.get("model_decay_forecast_freshness", {}) if isinstance(ctx, dict) else {}\n',
    '        c = st.columns(4)\n',
    '        c[0].metric("Robustness", _fmt(summary.get("Forecast Robustness Score", 0), "%"))\n',
    '        c[1].metric("Data Quality", _fmt(quality.get("Data Quality Score", 0), "%"))\n',
    '        c[2].metric("Leakage Risk", _fmt(leak.get("Leakage Risk %", 0), "%"))\n',
    '        c[3].metric("Drift Risk", drift.get("Drift Warning", "-"))\n',
    '        c2 = st.columns(3)\n',
    '        c2[0].metric("Forecast Freshness", _fmt(fresh.get("Prediction Freshness", fresh.get("Decayed Confidence Score", 0)), "%"))\n',
    '        c2[1].metric("Main Weakness", summary.get("Main Weakness", "-"))\n',
    '        c2[2].metric("Best Action", summary.get("Best Action Now", "-"))\n',
    '        try:\n',
    '            from core.canonical_runtime_20260617 import get_canonical\n',
    '            canonical = get_canonical(st.session_state)\n',
    '        except Exception:\n',
    '            canonical = st.session_state.get("canonical_result_20260617") or {}\n',
    '        research = canonical.get("research_risk_stack", {}) if isinstance(canonical, dict) else {}\n',
    '        confidence = research.get("confidence_sequence", {}) if isinstance(research, dict) else {}\n',
    '        selective = research.get("selective_prediction", {}) if isinstance(research, dict) else {}\n',
    '        proper = research.get("proper_scoring", {}) if isinstance(research, dict) else {}\n',
    '        evt = research.get("evt_tail", {}) if isinstance(research, dict) else {}\n',
    '        invariance = research.get("invariance", {}) if isinstance(research, dict) else {}\n',
    '        metrics = confidence.get("metrics", {}) if isinstance(confidence, dict) else {}\n',
    '        sample_counts = [int((item or {}).get("effective_sample_count") or 0) for item in metrics.values() if isinstance(item, dict)]\n',
    '        c3 = st.columns(4)\n',
    '        c3[0].metric("Anytime-valid trust", confidence.get("trust_status", "INSUFFICIENT_DATA"))\n',
    '        c3[1].metric("Risk–coverage", "PASS" if selective.get("selective_prediction_pass") else "WAIT", f"threshold {selective.get(\'required_confidence_threshold\', \'—\')}%")\n',
    '        c3[2].metric("CRPS skill", _fmt(proper.get("skill_vs_naive", 0), "%"), f"Energy {_fmt(proper.get(\'joint_energy_score\', 0))}")\n',
    '        c3[3].metric("Effective samples", max(sample_counts or [0]), f"CRPS n={proper.get(\'sample_count\', 0)}")\n',
    '        c4 = st.columns(2)\n',
    '        c4[0].metric("EVT status", "BLOCK" if evt.get("extreme_risk_block") else ("READY" if evt.get("evt_sample_sufficient") else "DEVELOPING"), f"exceedances {evt.get(\'evt_exceedance_count\', 0)}")\n',
    '        c4[1].metric("Invariance status", invariance.get("feature_stability_warning", "INSUFFICIENT_DATA"), f"score {_fmt(invariance.get(\'invariance_score\', 0), \'%\')}")\n',
    '        st.caption("Only the summary shows first. All previous detail blocks are still available below.")\n',
    '        with st.expander("Advanced Details — all merged reliability checks", expanded=False):\n',
    '            details = _detail_rows(ctx, [\n',
    '                "feature_leakage_guard",\n',
    '                "data_quality_market_feed_health",\n',
    '                "distribution_shift_wasserstein_style_drift",\n',
    '                "anomaly_and_shock_detector",\n',
    '                "model_decay_forecast_freshness",\n',
    '                "market_maker_pressure_proxy",\n',
    '                "pca_factor_structure_dashboard",\n',
    '                "mfe_mae_exit_control",\n',
    '            ])\n',
    '            if not details.empty:\n',
    '                st.dataframe(details, use_container_width=True, hide_index=True, height=420)\n',
    '            else:\n',
    '                st.info("No advanced details available yet.")\n',
    '            if research:\n',
    '                st.markdown("**Research risk validation details**")\n',
    '                st.json(research)\n',
    '\n',
    '\n',
    'def _render_dynamic_entry_priority_center(ns: dict) -> None:\n',
    '    with st.expander("🎯 Open / Close — Dynamic Entry Priority Center", expanded=False):\n',
    '        st.caption("Merged KNN Priority, Greedy Priority, Anti-Constant, Best Hour, and Best 2 Entries into one compact view.")\n',
    '        if not _run_ready():\n',
    '            st.info("Press **Run Calculating** first. Priority stays idle until run.")\n',
    '            return\n',
    '        ctx = _state_context(ns, force=False)\n',
    '        ps = _priority_summary(ns, ctx)\n',
    '        c = st.columns(3)\n',
    '        c[0].metric("Priority Rank 1–14", ps.get("Priority Rank 1-14", "-"))\n',
    '        c[1].metric("Priority Label", ps.get("Priority Label", "-"))\n',
    '        c[2].metric("Movement Score", _fmt(ps.get("Priority Movement Score", 0), "%"))\n',
    '        st.info(f"Best 2 Hours: {ps.get(\'Best 2 Hours\', \'-\')}")\n',
    '        st.warning(str(ps.get("Constant Score Warning", "-"))) if "constant" in str(ps.get("Constant Score Warning", "")).lower() else st.success(str(ps.get("Constant Score Warning", "-")))\n',
    '        st.caption(str(ps.get("Why priority changed", "-")))\n',
    '        with st.expander("Advanced Details — priority table and anti-constant checks", expanded=False):\n',
    '            priority = ctx.get("priority_anti_constant_engine", {}) if isinstance(ctx, dict) else {}\n',
    '            if isinstance(priority, dict) and priority:\n',
    '                st.dataframe(pd.DataFrame([{"Check": k, "Value": v} for k, v in priority.items()]), use_container_width=True, hide_index=True)\n',
    '            tab = _priority_table(ns, ctx)\n',
    '            if isinstance(tab, pd.DataFrame) and not tab.empty:\n',
    '                st.dataframe(tab.tail(48), use_container_width=True, hide_index=True, height=360)\n',
    '            else:\n',
]
