"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Read-only regime-transition, drift, calibration and system-trust evidence.\n',
    '\n',
    'This module wraps the existing canonical regime and forecast outputs.  It does\n',
    'not create a second prediction engine and never overwrites the protected regime,\n',
    'priority, reliability, conflict or BUY/SELL/WAIT decisions.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'from collections import Counter, defaultdict\n',
    'from copy import deepcopy\n',
    'from hashlib import sha256\n',
    'from math import exp, isfinite, lgamma, log, pi, sqrt\n',
    'from typing import Any, Iterable, Mapping, MutableMapping, Sequence\n',
    'import json\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'VERSION = "regime-transition-trust-20260621-v1"\n',
    'SCHEMA_VERSION = "regime-transition-trust-schema-1.0.0"\n',
    'DRIFT_LABELS = {\n',
    '    "NONE", "SUDDEN", "GRADUAL", "INCREMENTAL", "RECURRING",\n',
    '    "VOLATILITY_ONLY", "FEATURE_DRIFT", "PREDICTION_ERROR_DRIFT",\n',
    '}\n',
    '\n',
    '\n',
    'def _mapping(value: Any) -> Mapping[str, Any]:\n',
    '    return value if isinstance(value, Mapping) else {}\n',
    '\n',
    '\n',
    'def _num(value: Any, default: float = 0.0) -> float:\n',
    '    try:\n',
    '        number = float(value)\n',
    '        return number if isfinite(number) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(value: Any, low: float = 0.0, high: float = 100.0) -> float:\n',
    '    return max(low, min(high, _num(value)))\n',
    '\n',
    '\n',
    'def _norm(value: Any) -> str:\n',
    '    return "".join(ch for ch in str(value or "").lower() if ch.isalnum())\n',
    '\n',
    '\n',
    'def _find_col(frame: pd.DataFrame, aliases: Sequence[str]) -> str | None:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return None\n',
    '    normalized = {_norm(column): str(column) for column in frame.columns}\n',
    '    for alias in aliases:\n',
    '        key = _norm(alias)\n',
    '        if key in normalized:\n',
    '            return normalized[key]\n',
    '    for key, column in normalized.items():\n',
    '        if any(_norm(alias) in key for alias in aliases if _norm(alias)):\n',
    '            return column\n',
    '    return None\n',
    '\n',
    '\n',
    'def _completed_frame(frame: pd.DataFrame) -> pd.DataFrame:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame()\n',
    '    work = frame.copy(deep=False)\n',
    '    time_col = _find_col(work, ("time", "timestamp", "datetime", "date"))\n',
    '    close_col = _find_col(work, ("close", "actual_close", "price"))\n',
    '    if not time_col or not close_col:\n',
    '        return pd.DataFrame()\n',
    '    work = work.copy()\n',
    '    work[time_col] = pd.to_datetime(work[time_col], errors="coerce", utc=True)\n',
    '    work[close_col] = pd.to_numeric(work[close_col], errors="coerce")\n',
    '    work = work.dropna(subset=[time_col, close_col]).sort_values(time_col).drop_duplicates(time_col, keep="last")\n',
    '    work = work.rename(columns={time_col: "__time", close_col: "__close"})\n',
    '    return work.reset_index(drop=True)\n',
    '\n',
    '\n',
    'def _frame_fingerprint(frame: pd.DataFrame) -> str:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return "EMPTY"\n',
    '    sample = frame.tail(512).copy(deep=False)\n',
    '    payload = {\n',
    '        "rows": len(frame),\n',
    '        "columns": [str(c) for c in frame.columns],\n',
    '        "tail": sample.to_json(date_format="iso", orient="split", default_handler=str),\n',
    '    }\n',
    '    return sha256(json.dumps(payload, sort_keys=True, default=str).encode("utf-8", errors="ignore")).hexdigest()\n',
    '\n',
    '\n',
    'def _student_t_logpdf(x: float, mu: float, kappa: float, alpha: float, beta: float) -> float:\n',
    '    df = max(2.0 * alpha, 1e-6)\n',
    '    scale2 = max(beta * (kappa + 1.0) / max(alpha * kappa, 1e-9), 1e-9)\n',
    '    z2 = (x - mu) ** 2 / scale2\n',
    '    return (\n',
    '        lgamma((df + 1.0) / 2.0) - lgamma(df / 2.0)\n',
    '        - 0.5 * (log(df * pi) + log(scale2))\n',
    '        - ((df + 1.0) / 2.0) * log(1.0 + z2 / df)\n',
    '    )\n',
    '\n',
    '\n',
    'def bayesian_online_changepoint(\n',
    '    values: Iterable[float], *, hazard_lambda: float = 72.0, max_run_length: int = 240,\n',
    ') -> dict[str, Any]:\n',
    '    """Adams-MacKay style run-length recursion with Normal-Gamma predictions."""\n',
    '    array = np.asarray(list(values), dtype=float)\n',
    '    array = array[np.isfinite(array)]\n',
    '    if len(array) < 8:\n',
    '        return {"probability": 0.0, "most_likely_run_length": int(len(array)), "run_length_uncertainty": 1.0, "samples": int(len(array))}\n',
    '    array = array[-max(16, int(max_run_length)) :]\n',
    '    scale = float(np.nanstd(array))\n',
    '    if not isfinite(scale) or scale <= 1e-12:\n',
    '        scale = 1.0\n',
    '    center = float(np.nanmedian(array))\n',
    '    if not isfinite(center):\n',
    '        center = 0.0\n',
    '    centered = (array - center) / scale\n',
    '\n',
    '    hazard = min(max(1.0 / max(float(hazard_lambda), 2.0), 1e-4), 0.5)\n',
    '    probs = np.array([1.0], dtype=float)\n',
    '    mu = np.array([0.0], dtype=float)\n',
    '    kappa = np.array([1.0], dtype=float)\n',
    '    alpha = np.array([1.0], dtype=float)\n',
    '    beta = np.array([1.0], dtype=float)\n',
    '    cp_series: list[float] = []\n',
    '\n',
    '    for x in centered:\n',
    '        logs = np.array([_student_t_logpdf(float(x), float(mu[i]), float(kappa[i]), float(alpha[i]), float(beta[i])) for i in range(len(probs))])\n',
    '        logs -= np.nanmax(logs)\n',
    '        predictive = np.exp(logs)\n',
    '        growth = probs * (1.0 - hazard) * predictive\n',
    '        cp = float(np.sum(probs * hazard * predictive))\n',
    '        new_probs = np.concatenate(([cp], growth))\n',
    '        total = float(np.sum(new_probs))\n',
    '        new_probs = new_probs / total if total > 0 else np.array([1.0])\n',
    '        if len(new_probs) > max_run_length + 1:\n',
    '            new_probs = new_probs[: max_run_length + 1]\n',
    '            new_probs /= max(float(new_probs.sum()), 1e-12)\n',
    '\n',
    '        old_mu, old_kappa, old_alpha, old_beta = mu, kappa, alpha, beta\n',
    '        growth_len = min(len(old_mu), max_run_length)\n',
    '        new_mu = np.empty(len(new_probs), dtype=float)\n',
    '        new_kappa = np.empty(len(new_probs), dtype=float)\n',
    '        new_alpha = np.empty(len(new_probs), dtype=float)\n',
    '        new_beta = np.empty(len(new_probs), dtype=float)\n',
    '\n',
    '        def update(m: float, k: float, a: float, b: float) -> tuple[float, float, float, float]:\n',
    '            next_k = k + 1.0\n',
    '            next_m = (k * m + x) / next_k\n',
    '            next_a = a + 0.5\n',
    '            next_b = b + k * (x - m) ** 2 / (2.0 * next_k)\n',
    '            return next_m, next_k, next_a, next_b\n',
    '\n',
    '        new_mu[0], new_kappa[0], new_alpha[0], new_beta[0] = update(0.0, 1.0, 1.0, 1.0)\n',
    '        for i in range(1, len(new_probs)):\n',
    '            source = min(i - 1, growth_len - 1)\n',
    '            new_mu[i], new_kappa[i], new_alpha[i], new_beta[i] = update(\n',
    '                float(old_mu[source]), float(old_kappa[source]), float(old_alpha[source]), float(old_beta[source])\n',
    '            )\n',
    '        probs, mu, kappa, alpha, beta = new_probs, new_mu, new_kappa, new_alpha, new_beta\n',
    '        cp_series.append(float(probs[0]))\n',
    '\n',
    '    entropy = -float(np.sum(probs * np.log(np.maximum(probs, 1e-12))))\n',
    '    max_entropy = log(max(len(probs), 2))\n',
    '    recent_cp = max(cp_series[-3:] or [0.0])\n',
    '    return {\n',
    '        "probability": round(_clip(recent_cp * 100.0), 4),\n',
    '        "most_likely_run_length": int(np.argmax(probs)),\n',
    '        "run_length_uncertainty": round(_clip((entropy / max(max_entropy, 1e-9)) * 100.0), 4),\n',
    '        "samples": int(len(array)),\n',
    '        "posterior_tail": [round(float(x), 8) for x in probs[: min(30, len(probs))]],\n',
    '    }\n',
    '\n',
    '\n',
    'def adaptive_window_detection(values: Iterable[float], *, delta: float = 0.002, max_window: int = 512) -> dict[str, Any]:\n',
    '    """Lightweight ADWIN-style adaptive-window split test."""\n',
    '    array = np.asarray(list(values), dtype=float)\n',
    '    array = array[np.isfinite(array)][-max_window:]\n',
    '    n = len(array)\n',
    '    if n < 24:\n',
    '        return {"changed": False, "status": "STABLE", "window_size": n, "score": 0.0, "cut": None}\n',
    '    variance = float(np.var(array, ddof=1)) if n > 2 else 0.0\n',
    '    log_term = log(2.0 / max(delta, 1e-9))\n',
    '    best = {"ratio": 0.0, "cut": None, "difference": 0.0, "epsilon": float("inf")}\n',
    '    min_part = max(8, min(24, n // 4))\n',
    '    step = max(1, n // 64)\n',
    '    for cut in range(min_part, n - min_part + 1, step):\n',
    '        left, right = array[:cut], array[cut:]\n',
    '        n0, n1 = len(left), len(right)\n',
    '        harmonic = (1.0 / n0) + (1.0 / n1)\n',
    '        epsilon = sqrt(max(2.0 * variance * harmonic * log_term, 0.0)) + (2.0 / 3.0) * log_term * harmonic\n',
    '        difference = abs(float(np.mean(left)) - float(np.mean(right)))\n',
    '        ratio = difference / max(epsilon, 1e-12)\n',
    '        if ratio > best["ratio"]:\n',
    '            best = {"ratio": ratio, "cut": cut, "difference": difference, "epsilon": epsilon}\n',
    '    changed = bool(best["ratio"] > 1.0)\n',
    '    window_size = int(n - int(best["cut"])) if changed and best["cut"] is not None else n\n',
    '    return {\n',
    '        "changed": changed,\n',
    '        "status": "CHANGE" if changed else "STABLE",\n',
    '        "window_size": window_size,\n',
    '        "score": round(_clip(float(best["ratio"]) * 50.0), 4),\n',
    '        "cut": best["cut"],\n',
    '        "mean_difference": round(float(best["difference"]), 8),\n',
    '        "epsilon": round(float(best["epsilon"]), 8) if isfinite(float(best["epsilon"])) else None,\n',
    '    }\n',
    '\n',
    '\n',
    'def _forecast_models(canonical: Mapping[str, Any]) -> list[tuple[str, float, float]]:\n',
    '    forecasts = _mapping(canonical.get("forecasts"))\n',
    '    selected = _mapping(forecasts.get("selected"))\n',
    '    items: list[tuple[str, float, float]] = []\n',
    '    containers = [\n',
    '        forecasts.get("models"), forecasts.get("model_forecasts"),\n',
    '        canonical.get("model_forecasts"), canonical.get("forecast_decomposition"),\n',
    '        _mapping(canonical.get("powerbi")).get("models"),\n',
    '    ]\n',
    '    for container in containers:\n',
    '        if not isinstance(container, Mapping):\n',
    '            continue\n',
    '        for name, value in container.items():\n',
    '            if isinstance(value, Mapping):\n',
    '                point = _num(value.get("point_forecast", value.get("forecast", value.get("price"))), np.nan)\n',
    '                confidence = _num(value.get("confidence", value.get("confidence_pct", 50.0)), 50.0)\n',
    '            else:\n',
    '                point, confidence = _num(value, np.nan), 50.0\n',
    '            if isfinite(point):\n',
    '                items.append((str(name), point, confidence))\n',
    '    if not items:\n',
    '        point = _num(selected.get("point_forecast"), np.nan)\n',
    '        if isfinite(point):\n',
    '            items.append(("Selected Forecast", point, _num(selected.get("confidence_pct", selected.get("confidence", 50.0)), 50.0)))\n',
    '    dedup: dict[str, tuple[str, float, float]] = {}\n',
    '    for row in items:\n',
    '        dedup[_norm(row[0])] = row\n',
    '    return list(dedup.values())\n',
    '\n',
    '\n',
    'def _settled_calibration(frame: pd.DataFrame, raw_confidence: float) -> dict[str, Any]:\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return {\n',
    '            "samples": 0, "calibrated_confidence": raw_confidence,\n',
    '            "expected_calibration_error": None, "brier_score": None,\n',
    '            "rolling_coverage": None, "absolute_close_error": None,\n',
    '            "actual_direction": "UNSETTLED", "actual_inside_interval": None,\n',
    '            "coverage_history": [], "error_history": [],\n',
    '        }\n',
    '    work = frame.copy(deep=False)\n',
    '    conf_col = _find_col(work, ("confidence", "probability", "raw_confidence", "confidence_pct"))\n',
    '    pred_col = _find_col(work, ("predicted_direction", "prediction_direction", "direction"))\n',
    '    actual_col = _find_col(work, ("actual_direction", "realized_direction", "outcome_direction"))\n',
    '    inside_col = _find_col(work, ("actual_inside_interval", "inside_interval", "covered"))\n',
    '    error_col = _find_col(work, ("absolute_close_error", "abs_error", "absolute_error", "error"))\n',
    '    if pred_col and actual_col:\n',
    '        correctness = work[pred_col].astype(str).str.upper().eq(work[actual_col].astype(str).str.upper()).astype(float)\n',
    '    else:\n',
    '        correct_col = _find_col(work, ("direction_correct", "correct", "is_correct"))\n',
    '        correctness = pd.to_numeric(work[correct_col], errors="coerce") if correct_col else pd.Series(dtype=float)\n',
    '    probabilities = pd.to_numeric(work[conf_col], errors="coerce") if conf_col else pd.Series(raw_confidence / 100.0, index=work.index, dtype=float)\n',
    '    if not probabilities.empty and float(probabilities.dropna().median() if probabilities.notna().any() else 0) > 1.0:\n',
    '        probabilities = probabilities / 100.0\n',
    '    valid = probabilities.notna() & correctness.notna() if not correctness.empty else pd.Series(False, index=work.index)\n',
    '    probs, actual = probabilities[valid].clip(0, 1), correctness[valid].clip(0, 1)\n',
    '    ece = None\n',
    '    brier = None\n',
    '    calibrated = raw_confidence\n',
    '    if len(probs):\n',
    '        bins = np.linspace(0.0, 1.0, 11)\n',
    '        ece_value = 0.0\n',
    '        raw_p = raw_confidence / 100.0\n',
    '        local_accuracy = float(actual.mean())\n',
    '        for lower, upper in zip(bins[:-1], bins[1:]):\n',
    '            mask = (probs >= lower) & (probs < upper if upper < 1.0 else probs <= upper)\n',
    '            if mask.any():\n',
    '                ece_value += float(mask.mean()) * abs(float(actual[mask].mean()) - float(probs[mask].mean()))\n',
    '                if lower <= raw_p <= upper:\n',
    '                    local_accuracy = float(actual[mask].mean())\n',
    '        weight = len(probs) / (len(probs) + 20.0)\n',
    '        calibrated = 100.0 * ((1.0 - weight) * raw_p + weight * local_accuracy)\n',
    '        ece = ece_value * 100.0\n',
    '        brier = float(np.mean((probs.to_numpy() - actual.to_numpy()) ** 2))\n',
    '    inside = pd.to_numeric(work[inside_col], errors="coerce") if inside_col else pd.Series(dtype=float)\n',
    '    coverage = float(inside.dropna().tail(100).mean() * 100.0) if inside.notna().any() else None\n',
    '    errors = pd.to_numeric(work[error_col], errors="coerce").dropna() if error_col else pd.Series(dtype=float)\n',
    '    last_actual = str(work[actual_col].dropna().iloc[-1]) if actual_col and work[actual_col].notna().any() else "UNSETTLED"\n',
    '    return {\n',
    '        "samples": int(len(probs)),\n',
    '        "calibrated_confidence": round(_clip(calibrated), 4),\n',
    '        "expected_calibration_error": round(ece, 6) if ece is not None else None,\n',
    '        "brier_score": round(brier, 8) if brier is not None else None,\n',
    '        "rolling_coverage": round(coverage, 4) if coverage is not None else None,\n',
    '        "absolute_close_error": round(float(errors.iloc[-1]), 8) if len(errors) else None,\n',
    '        "actual_direction": last_actual,\n',
    '        "actual_inside_interval": bool(inside.dropna().iloc[-1]) if inside.notna().any() else None,\n',
    '        "coverage_history": inside.dropna().tail(40).astype(float).tolist(),\n',
    '        "error_history": errors.tail(200).astype(float).tolist(),\n',
    '    }\n',
    '\n',
    '\n',
    'def _regime_history(priority_table: pd.DataFrame, completed: pd.DataFrame) -> pd.DataFrame:\n',
    '    candidates = [priority_table, completed]\n',
    '    for source in candidates:\n',
    '        if not isinstance(source, pd.DataFrame) or source.empty:\n',
    '            continue\n',
    '        time_col = _find_col(source, ("time", "timestamp", "datetime", "date", "hour"))\n',
    '        regime_col = _find_col(source, ("major_regime", "regime", "current_regime", "market_regime"))\n',
    '        if not time_col or not regime_col:\n',
    '            continue\n',
    '        frame = source[[time_col, regime_col]].copy()\n',
    '        frame[time_col] = pd.to_datetime(frame[time_col], errors="coerce", utc=True)\n',
    '        frame[regime_col] = frame[regime_col].astype(str).str.upper().str.strip()\n',
    '        frame = frame.dropna(subset=[time_col]).loc[lambda x: x[regime_col].ne("")]\n',
    '        frame = frame.sort_values(time_col).drop_duplicates(time_col, keep="last")\n',
    '        return frame.rename(columns={time_col: "time", regime_col: "regime"}).reset_index(drop=True)\n',
    '    return pd.DataFrame(columns=["time", "regime"])\n',
    '\n',
    '\n',
    'def _transition_rows(regimes: pd.DataFrame, completed: pd.DataFrame) -> list[dict[str, Any]]:\n',
    '    if regimes.empty or completed.empty:\n',
    '        return []\n',
    '    price = completed[["__time", "__close"]].copy()\n',
    '    merged = pd.merge_asof(regimes.sort_values("time"), price.sort_values("__time"), left_on="time", right_on="__time", direction="nearest", tolerance=pd.Timedelta("90min"))\n',
    '    rows: list[dict[str, Any]] = []\n',
    '    previous = None\n',
    '    for idx, row in merged.iterrows():\n',
    '        current = str(row.get("regime") or "UNKNOWN")\n',
    '        if previous is not None and current != previous:\n',
    '            start = int(idx)\n',
    '            entry = _num(row.get("__close"), np.nan)\n',
    '            future = merged.iloc[start : start + 7]\n',
    '            prices = pd.to_numeric(future.get("__close"), errors="coerce").dropna().tolist()\n',
    '            def at(hours: int) -> float | None:\n',
    '                position = min(hours, len(prices) - 1)\n',
    '                return float(prices[position]) if prices and position >= 0 else None\n',
    '            direction = "BUY" if "BULL" in current else "SELL" if "BEAR" in current else "WAIT"\n',
    '            after = prices[1:7] if len(prices) > 1 else []\n',
    '            deltas = [value - entry for value in after] if isfinite(entry) else []\n',
    '            signed = deltas if direction == "BUY" else [-x for x in deltas] if direction == "SELL" else deltas\n',
    '            rows.append({\n',
    '                "transition_time": row.get("time"), "previous_regime": previous,\n',
    '                "new_regime": current, "entry_reference_price": entry if isfinite(entry) else None,\n',
    '                "actual_close_1h": at(1), "actual_close_2h": at(2), "actual_close_3h": at(3), "actual_close_6h": at(6),\n',
    '                "direction_correct_1h": (at(1) > entry if direction == "BUY" else at(1) < entry if direction == "SELL" else None) if at(1) is not None and isfinite(entry) else None,\n',
    '                "direction_correct_3h": (at(3) > entry if direction == "BUY" else at(3) < entry if direction == "SELL" else None) if at(3) is not None and isfinite(entry) else None,\n',
    '                "direction_correct_6h": (at(6) > entry if direction == "BUY" else at(6) < entry if direction == "SELL" else None) if at(6) is not None and isfinite(entry) else None,\n',
    '                "maximum_favorable_excursion": max(signed) if signed else None,\n',
    '                "maximum_adverse_excursion": min(signed) if signed else None,\n',
    '                "regime_still_active_6h": bool(len(future) > 6 and str(future.iloc[6].get("regime")) == current),\n',
    '            })\n',
    '        previous = current\n',
    '    return rows\n',
    '\n',
    '\n',
    'def _candidate_next(regimes: pd.DataFrame, current: str, canonical: Mapping[str, Any]) -> tuple[str, int]:\n',
    '    counts: Counter[str] = Counter()\n',
    '    if not regimes.empty:\n',
    '        sequence = regimes["regime"].astype(str).tolist()\n',
    '        compact = [value for i, value in enumerate(sequence) if i == 0 or value != sequence[i - 1]]\n',
    '        for left, right in zip(compact[:-1], compact[1:]):\n',
    '            if left == current:\n',
    '                counts[right] += 1\n',
    '    if counts:\n',
    '        candidate, count = counts.most_common(1)[0]\n',
    '        return candidate, int(count)\n',
    '    regime = _mapping(canonical.get("regime"))\n',
    '    explicit = regime.get("candidate_next_regime") or regime.get("next_regime")\n',
    '    if explicit:\n',
    '        return str(explicit).upper(), 0\n',
    '    final = _mapping(canonical.get("final_decision"))\n',
    '    direction = str(final.get("directional_market_view") or final.get("less_risky_decision") or "WAIT").upper()\n',
    '    environment = "NORMAL"\n',
    '    if "COMPRESSION" in current:\n',
    '        environment = "EXPANSION"\n',
    '    elif "EXPANSION" in current:\n',
    '        environment = "NORMAL"\n',
    '    if direction == "BUY":\n',
    '        return f"BULL_{environment}", 0\n',
    '    if direction == "SELL":\n',
    '        return f"BEAR_{environment}", 0\n',
    '    return "RANGE_NORMAL", 0\n',
    '\n',
    '\n',
    'def _plain_reason(status: str, drift_type: str, conflict: str, trust: float) -> str:\n',
    '    parts = [f"Transition evidence is {status.lower()}."]\n',
    '    if drift_type != "NONE":\n',
    '        parts.append(f"The strongest warning is {drift_type.replace(\'_\', \' \').lower()}.")\n',
    '    if conflict not in {"NONE", "NO CONFLICT", "ALIGNED", ""}:\n',
    '        parts.append("The existing regime and prediction are not fully aligned.")\n',
    '    parts.append(f"Calibrated regime trust is {trust:.1f}/100; the original regime remains authoritative.")\n',
    '    return " ".join(parts)\n',
    '\n',
    '\n',
    'def build_regime_transition_trust(\n',
    '    canonical: Mapping[str, Any], *, completed_h1: pd.DataFrame,\n',
    '    priority_table: pd.DataFrame | None = None, settled_predictions: pd.DataFrame | None = None,\n',
    '    calibrated_bundle: Mapping[str, Any] | None = None, previous: Mapping[str, Any] | None = None,\n',
    ') -> tuple[dict[str, Any], dict[str, Any], dict[str, list[dict[str, Any]]]]:\n',
    '    """Build additive evidence and normalized history rows for one canonical run."""\n',
    '    output = deepcopy(dict(canonical))\n',
    '    completed = _completed_frame(completed_h1)\n',
    '    priority = priority_table if isinstance(priority_table, pd.DataFrame) else pd.DataFrame()\n',
    '    settled = settled_predictions if isinstance(settled_predictions, pd.DataFrame) else pd.DataFrame()\n',
    '    previous = _mapping(previous)\n',
    '    regime = _mapping(output.get("regime"))\n',
    '    final = _mapping(output.get("final_decision"))\n',
    '    reliability = _mapping(output.get("reliability"))\n',
    '    forecasts = _mapping(output.get("forecasts"))\n',
    '    selected = _mapping(forecasts.get("selected"))\n',
    '    market = _mapping(output.get("market"))\n',
    '\n',
    '    returns = completed["__close"].pct_change().replace([np.inf, -np.inf], np.nan).dropna() if not completed.empty else pd.Series(dtype=float)\n',
    '    volatility = returns.rolling(24, min_periods=8).std().dropna()\n',
    '    return_scale = float(returns.tail(240).std()) if len(returns) else 0.0\n',
    '    if not isfinite(return_scale) or return_scale <= 1e-12:\n',
    '        return_scale = 1e-9\n',
    '    normalized_returns = (returns / return_scale).clip(-8, 8)\n',
    '    bocpd = bayesian_online_changepoint(normalized_returns.tail(240).tolist())\n',
    '    adwin = adaptive_window_detection(normalized_returns.tail(512).tolist())\n',
    '\n',
    '    current_regime = str(regime.get("major_regime") or regime.get("current") or regime.get("current_regime") or "UNKNOWN").upper()\n',
    '    history = _regime_history(priority, completed)\n',
    '    transitions = _transition_rows(history, completed)\n',
]
