"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    previous_regime = str(regime.get("previous_regime") or "").upper()\n',
    '    transition_time = regime.get("last_change_time") or regime.get("transition_time") or output.get("latest_completed_candle_time")\n',
    '    if transitions:\n',
    '        latest_transition = transitions[-1]\n',
    '        if not previous_regime:\n',
    '            previous_regime = str(latest_transition.get("previous_regime") or "UNKNOWN")\n',
    '        if current_regime == "UNKNOWN":\n',
    '            current_regime = str(latest_transition.get("new_regime") or "UNKNOWN")\n',
    '        transition_time = latest_transition.get("transition_time") or transition_time\n',
    '    if not previous_regime:\n',
    '        previous_regime = str(_mapping(previous.get("regime")).get("major_regime") or current_regime)\n',
    '    candidate_next, recurring_count = _candidate_next(history, current_regime, output)\n',
    '\n',
    '    model_rows = _forecast_models(output)\n',
    '    model_points = np.asarray([row[1] for row in model_rows], dtype=float)\n',
    '    last_close = float(completed["__close"].iloc[-1]) if not completed.empty else _num(market.get("last_close"), 0.0)\n',
    '    forecast_spread = float(np.std(model_points) / max(abs(last_close), 1e-9) * 100.0) if len(model_points) > 1 else 0.0\n',
    '    forecast_disagreement = _clip(forecast_spread * 400.0)\n',
    '\n',
    '    vol_recent = float(volatility.tail(24).mean()) if len(volatility) else 0.0\n',
    '    vol_prior = float(volatility.iloc[-72:-24].mean()) if len(volatility) >= 72 else float(volatility.head(max(len(volatility) - 24, 1)).mean() if len(volatility) > 24 else vol_recent)\n',
    '    volatility_shift = abs(vol_recent - vol_prior) / max(abs(vol_prior), 1e-9) * 100.0 if vol_prior else 0.0\n',
    '    volatility_drift_score = _clip(volatility_shift)\n',
    '\n',
    '    raw_confidence = _clip(\n',
    '        selected.get("confidence_pct", selected.get("confidence", reliability.get("score", 50.0)))\n',
    '    )\n',
    '    calibration = _settled_calibration(settled, raw_confidence)\n',
    '    error_values = calibration.get("error_history") or []\n',
    '    error_adwin = adaptive_window_detection(error_values, max_window=300) if error_values else {"changed": False, "score": 0.0, "window_size": 0}\n',
    '    error_drift_score = _clip(error_adwin.get("score", 0.0))\n',
    '    ece = calibration.get("expected_calibration_error")\n',
    '    calibration_deterioration = _clip((ece or 0.0) * 2.0)\n',
    '\n',
    '    conflict = str(\n',
    '        output.get("conflict_status") or regime.get("prediction_conflict") or\n',
    '        _mapping(output.get("conflict")).get("status") or "NONE"\n',
    '    ).upper()\n',
    '    conflict_score = 100.0 if conflict not in {"NONE", "NO CONFLICT", "ALIGNED", "OK", ""} else 0.0\n',
    '    change_probability = _clip(\n',
    '        0.45 * _num(bocpd.get("probability"))\n',
    '        + 0.20 * (100.0 if adwin.get("changed") else _num(adwin.get("score")))\n',
    '        + 0.15 * volatility_drift_score\n',
    '        + 0.10 * forecast_disagreement\n',
    '        + 0.10 * error_drift_score\n',
    '    )\n',
    '    observed_change = previous_regime != current_regime and current_regime != "UNKNOWN"\n',
    '    if observed_change and change_probability >= 55:\n',
    '        transition_status = "CONFIRMED"\n',
    '    elif change_probability >= 45 or adwin.get("changed"):\n',
    '        transition_status = "WATCH"\n',
    '    else:\n',
    '        transition_status = "STABLE"\n',
    '\n',
    '    recent = normalized_returns.tail(72)\n',
    '    gradual_score = 0.0\n',
    '    incremental_score = 0.0\n',
    '    if len(recent) >= 24:\n',
    '        thirds = np.array_split(recent.to_numpy(), 3)\n',
    '        means = [float(np.mean(x)) for x in thirds if len(x)]\n',
    '        if len(means) == 3:\n',
    '            gradual_score = _clip((max(means) - min(means)) / max(float(np.std(recent)), 1e-9) * 35.0)\n',
    '            monotonic = (means[0] <= means[1] <= means[2]) or (means[0] >= means[1] >= means[2])\n',
    '            incremental_score = gradual_score if monotonic else 0.0\n',
    '    feature_drift_score = _clip(max(_num(adwin.get("score")), forecast_disagreement * 0.7))\n',
    '\n',
    '    if error_drift_score >= 65:\n',
    '        drift_type = "PREDICTION_ERROR_DRIFT"\n',
    '    elif volatility_drift_score >= 65 and feature_drift_score < 45 and error_drift_score < 45:\n',
    '        drift_type = "VOLATILITY_ONLY"\n',
    '    elif observed_change and change_probability >= 75 and _num(bocpd.get("probability")) >= 55:\n',
    '        drift_type = "SUDDEN"\n',
    '    elif recurring_count >= 2 and observed_change:\n',
    '        drift_type = "RECURRING"\n',
    '    elif incremental_score >= 50:\n',
    '        drift_type = "INCREMENTAL"\n',
    '    elif gradual_score >= 45 or (adwin.get("changed") and _num(bocpd.get("probability")) < 50):\n',
    '        drift_type = "GRADUAL"\n',
    '    elif feature_drift_score >= 55:\n',
    '        drift_type = "FEATURE_DRIFT"\n',
    '    else:\n',
    '        drift_type = "NONE"\n',
    '    if drift_type not in DRIFT_LABELS:\n',
    '        drift_type = "NONE"\n',
    '\n',
    '    existing_trust = _clip(regime.get("reliability", regime.get("regime_reliability", reliability.get("score", 50.0))))\n',
    '    calibrated_trust = _clip(\n',
    '        existing_trust\n',
    '        - 0.18 * change_probability\n',
    '        - 0.12 * forecast_disagreement\n',
    '        - 0.12 * error_drift_score\n',
    '        - 0.08 * calibration_deterioration\n',
    '        - 0.05 * conflict_score\n',
    '        + 8.0\n',
    '    )\n',
    '    safer_decision = str(final.get("less_risky_decision") or final.get("final_decision") or "WAIT").upper()\n',
    '    if calibrated_trust < 45 or conflict_score or change_probability >= 70:\n',
    '        safer_decision = "WAIT"\n',
    '\n',
    '    target_coverage = _num(_mapping(calibrated_bundle).get("target_coverage"), 90.0)\n',
    '    if target_coverage <= 1.0:\n',
    '        target_coverage *= 100.0\n',
    '    rolling_coverage = calibration.get("rolling_coverage")\n',
    '    coverage_error = target_coverage - _num(rolling_coverage, target_coverage)\n',
    '    coverage_history = list(calibration.get("coverage_history") or [])\n',
    '    historical_errors = [target_coverage / 100.0 - float(x) for x in coverage_history]\n',
    '    proportional = coverage_error / 100.0\n',
    '    integral = float(np.sum(historical_errors[-20:]))\n',
    '    derivative = historical_errors[-1] - historical_errors[-2] if len(historical_errors) >= 2 else 0.0\n',
    '\n',
    '    point = _num(selected.get("point_forecast", selected.get("forecast", last_close)), last_close)\n',
    '    lower = _num(selected.get("lower_bound", selected.get("lower", point)), point)\n',
    '    upper = _num(selected.get("upper_bound", selected.get("upper", point)), point)\n',
    '    residuals = np.asarray(calibration.get("error_history") or [], dtype=float)\n',
    '    residuals = residuals[np.isfinite(residuals)]\n',
    '    conformal_radius = float(np.quantile(residuals, min(max(target_coverage / 100.0, 0.5), 0.995))) if len(residuals) >= 10 else max(abs(upper - lower) / 2.0, abs(point) * 0.0007)\n',
    '    base_half_width = max(abs(point - lower), abs(upper - point), conformal_radius, abs(point) * 0.0001)\n',
    '    pid_signal = 0.35 * proportional + 0.05 * integral + 0.10 * derivative\n',
    '    width_adjustment = max(-0.35, min(0.75, pid_signal))\n',
    '    next_half_width = base_half_width * (1.0 + width_adjustment)\n',
    '    adaptive_lower, adaptive_upper = point - next_half_width, point + next_half_width\n',
    '\n',
    '    latest_time = completed["__time"].iloc[-1] if not completed.empty else pd.Timestamp.now(tz="UTC")\n',
    '    transition_ts = pd.to_datetime(transition_time, errors="coerce", utc=True)\n',
    '    if pd.isna(transition_ts):\n',
    '        transition_ts = latest_time\n',
    '    elapsed_hours = max((pd.Timestamp(latest_time) - pd.Timestamp(transition_ts)).total_seconds() / 3600.0, 0.0)\n',
    '    now_utc = pd.Timestamp.now(tz="UTC")\n',
    '    latest_utc = pd.Timestamp(latest_time)\n',
    '    if latest_utc.tzinfo is None:\n',
    '        latest_utc = latest_utc.tz_localize("UTC")\n',
    '    freshness_hours = max((now_utc - latest_utc).total_seconds() / 3600.0, 0.0)\n',
    '    fallback_use = bool(output.get("fallback_use") or _mapping(output.get("metadata")).get("fallback_use"))\n',
    '    missing_sources: list[str] = []\n',
    '    if completed.empty:\n',
    '        missing_sources.append("completed_h1")\n',
    '    if not model_rows:\n',
    '        missing_sources.append("model_forecasts")\n',
    '    if settled.empty:\n',
    '        missing_sources.append("settled_predictions")\n',
    '\n',
    '    matching = [row for row in transitions if str(row.get("previous_regime")) == previous_regime and str(row.get("new_regime")) == current_regime]\n',
    '    # Reuse published Similar-Day scores when a transition date is present there.\n',
    '    # This is a ranking aid only and does not alter the existing Similar-Day engine.\n',
    '    similar_payload = _mapping(output.get("similar_day_intelligence"))\n',
    '    similar_rows = list(similar_payload.get("history_25") or []) + list(similar_payload.get("top_five") or [])\n',
    '    similar_by_date: dict[str, float] = {}\n',
    '    for item in similar_rows:\n',
    '        if not isinstance(item, Mapping):\n',
    '            continue\n',
    '        date_value = item.get("Historical Date") or item.get("date") or item.get("timestamp")\n',
    '        parsed_date = pd.to_datetime(date_value, errors="coerce", utc=True)\n',
    '        if pd.isna(parsed_date):\n',
    '            continue\n',
    '        score = _num(item.get("Similarity Index", item.get("similarity_score")), 0.0)\n',
    '        similar_by_date[pd.Timestamp(parsed_date).date().isoformat()] = max(score, similar_by_date.get(pd.Timestamp(parsed_date).date().isoformat(), 0.0))\n',
    '    top_matches: list[dict[str, Any]] = []\n',
    '    for row in matching[-50:]:\n',
    '        entry = _num(row.get("entry_reference_price"), 0.0)\n',
    '        movements = {}\n',
    '        for horizon in (1, 2, 3, 6):\n',
    '            close = row.get(f"actual_close_{horizon}h")\n',
    '            movements[f"movement_{horizon}h"] = ((_num(close) - entry) / max(abs(entry), 1e-9) * 100.0) if close is not None and entry else None\n',
    '        transition_date = pd.to_datetime(row.get("transition_time"), errors="coerce", utc=True)\n',
    '        date_key = pd.Timestamp(transition_date).date().isoformat() if pd.notna(transition_date) else ""\n',
    '        similarity = similar_by_date.get(date_key)\n',
    '        if similarity is None:\n',
    '            # Recency is a transparent fallback when no Similar-Day score exists.\n',
    '            age_days = max((pd.Timestamp(latest_time) - pd.Timestamp(transition_date)).total_seconds() / 86400.0, 0.0) if pd.notna(transition_date) else 999.0\n',
    '            similarity = max(0.0, 55.0 - min(age_days, 55.0))\n',
    '        top_matches.append({\n',
    '            "transition_time": row.get("transition_time"),\n',
    '            "previous_regime": row.get("previous_regime"),\n',
    '            "new_regime": row.get("new_regime"),\n',
    '            "similarity_score": round(similarity, 3),\n',
    '            **movements,\n',
    '            "maximum_favorable_excursion": row.get("maximum_favorable_excursion"),\n',
    '            "maximum_adverse_excursion": row.get("maximum_adverse_excursion"),\n',
    '        })\n',
    '    top_matches = sorted(top_matches, key=lambda row: (_num(row.get("similarity_score")), str(row.get("transition_time"))), reverse=True)[:5]\n',
    '\n',
    '    reason = _plain_reason(transition_status, drift_type, conflict, calibrated_trust)\n',
    '    run_id = str(output.get("run_id") or output.get("canonical_calculation_id") or "")\n',
    '    generation = int(_num(output.get("calculation_generation"), 0))\n',
    '    timestamp = pd.Timestamp.now(tz="UTC")\n',
    '    identity = {\n',
    '        "canonical_run_id": run_id,\n',
    '        "calculation_generation": generation,\n',
    '        "source_data_timestamp": str(latest_time),\n',
    '        "data_freshness": "CURRENT" if freshness_hours <= 2 else "STALE" if freshness_hours > 6 else "AGING",\n',
    '        "data_freshness_hours": round(freshness_hours, 3),\n',
    '        "data_fingerprint": _frame_fingerprint(completed_h1),\n',
    '        "result_schema_version": str(output.get("shared_result_schema_version") or output.get("schema_version") or SCHEMA_VERSION),\n',
    '        "missing_source_warnings": missing_sources,\n',
    '        "fallback_use": fallback_use,\n',
    '        "last_successful_calculation": str(output.get("calculation_completed_at") or output.get("created_at") or timestamp),\n',
    '        "all_visible_components_same_canonical_result": True,\n',
    '    }\n',
    '    result = {\n',
    '        "version": VERSION,\n',
    '        "schema_version": SCHEMA_VERSION,\n',
    '        "mode": "EVIDENCE_ONLY",\n',
    '        "protected_regime_unchanged": True,\n',
    '        "protected_decision_unchanged": True,\n',
    '        "transition_summary": {\n',
    '            "previous_regime": previous_regime,\n',
    '            "current_regime": current_regime,\n',
    '            "candidate_next_regime": candidate_next,\n',
    '            "regime_change_probability": round(change_probability, 4),\n',
    '            "transition_status": transition_status,\n',
    '            "drift_type": drift_type,\n',
    '            "hours_since_last_confirmed_transition": round(elapsed_hours, 3),\n',
    '            "days_since_last_confirmed_transition": round(elapsed_hours / 24.0, 3),\n',
    '            "calibrated_regime_trust": round(calibrated_trust, 4),\n',
    '            "safer_decision": safer_decision,\n',
    '            "reason": reason,\n',
    '        },\n',
    '        "change_evidence": {\n',
    '            "bayesian_online_changepoint_probability": bocpd.get("probability"),\n',
    '            "most_likely_run_length": bocpd.get("most_likely_run_length"),\n',
    '            "run_length_uncertainty": bocpd.get("run_length_uncertainty"),\n',
    '            "adwin_change_status": adwin.get("status"),\n',
    '            "effective_adaptive_window_size": adwin.get("window_size"),\n',
    '            "volatility_shift": round(volatility_shift, 4),\n',
    '            "forecast_disagreement": round(forecast_disagreement, 4),\n',
    '            "prediction_error_drift": round(error_drift_score, 4),\n',
    '            "calibration_deterioration": round(calibration_deterioration, 4),\n',
    '            "regime_prediction_conflict": conflict,\n',
    '            "feature_drift_score": round(feature_drift_score, 4),\n',
    '        },\n',
    '        "historical_transition_matches": {\n',
    '            "sample_size": len(matching),\n',
    '            "warning": "Historical transition sample is small; treat the match statistics as descriptive only." if len(matching) < 5 else "",\n',
    '            "top_five": top_matches,\n',
    '        },\n',
    '        "prediction_calibration": {\n',
    '            "raw_confidence": round(raw_confidence, 4),\n',
    '            "calibrated_confidence": calibration.get("calibrated_confidence"),\n',
    '            "expected_calibration_error": calibration.get("expected_calibration_error"),\n',
    '            "brier_score": calibration.get("brier_score"),\n',
    '            "rolling_interval_coverage": rolling_coverage,\n',
    '            "target_coverage": round(target_coverage, 4),\n',
    '            "coverage_error": round(coverage_error, 4),\n',
    '            "adaptive_lower_prediction_band": round(adaptive_lower, 8),\n',
    '            "adaptive_upper_prediction_band": round(adaptive_upper, 8),\n',
    '            "pid_proportional_error": round(proportional, 8),\n',
    '            "pid_integral_error": round(integral, 8),\n',
    '            "pid_derivative_error": round(derivative, 8),\n',
    '            "next_interval_width_adjustment": round(width_adjustment * 100.0, 4),\n',
    '            "settled_sample_count": calibration.get("samples"),\n',
    '        },\n',
    '        "system_trust_audit": identity,\n',
    '    }\n',
    '    output["regime_transition_trust_center"] = result\n',
    '    output.setdefault("metadata", {})["regime_transition_trust_version"] = VERSION\n',
    '    output["metadata"]["regime_transition_trust_mode"] = "EVIDENCE_ONLY"\n',
    '\n',
    '    base = {"timestamp": timestamp, "run_id": run_id, "calculation_generation": generation}\n',
    '    transition_history = [{\n',
    '        **base, "transition_time": transition_ts, "previous_regime": previous_regime,\n',
    '        "new_regime": current_regime, "change_probability": change_probability,\n',
    '        "drift_type": drift_type, "run_length_before": bocpd.get("most_likely_run_length"),\n',
    '        "confirmation_delay_bars": max(0, int(round(elapsed_hours))),\n',
    '        "volatility_before": vol_prior, "volatility_after": vol_recent,\n',
    '        "forecast_disagreement": forecast_disagreement,\n',
    '        "calibrated_regime_trust": calibrated_trust, "trigger_summary": reason,\n',
    '    }]\n',
    '    outcome_history = []\n',
    '    for row in transitions[-100:]:\n',
    '        outcome_history.append({\n',
    '            **base, "transition_time": row.get("transition_time"), "new_regime": row.get("new_regime"),\n',
    '            "entry_reference_price": row.get("entry_reference_price"),\n',
    '            "actual_close_1h": row.get("actual_close_1h"), "actual_close_2h": row.get("actual_close_2h"),\n',
    '            "actual_close_3h": row.get("actual_close_3h"), "actual_close_6h": row.get("actual_close_6h"),\n',
    '            "direction_correct_1h": row.get("direction_correct_1h"),\n',
    '            "direction_correct_3h": row.get("direction_correct_3h"),\n',
    '            "direction_correct_6h": row.get("direction_correct_6h"),\n',
    '            "maximum_favorable_excursion": row.get("maximum_favorable_excursion"),\n',
    '            "maximum_adverse_excursion": row.get("maximum_adverse_excursion"),\n',
    '            "regime_still_active_6h": row.get("regime_still_active_6h"),\n',
    '        })\n',
    '    calibration_history = [{\n',
    '        **base, "raw_confidence": raw_confidence,\n',
    '        "calibrated_confidence": calibration.get("calibrated_confidence"),\n',
    '        "predicted_direction": str(selected.get("direction") or final.get("directional_market_view") or safer_decision),\n',
    '        "actual_direction": calibration.get("actual_direction"),\n',
    '        "absolute_close_error": calibration.get("absolute_close_error"),\n',
    '        "interval_lower": adaptive_lower, "interval_upper": adaptive_upper,\n',
    '        "actual_inside_interval": calibration.get("actual_inside_interval"),\n',
    '        "rolling_coverage": rolling_coverage,\n',
    '        "expected_calibration_error": calibration.get("expected_calibration_error"),\n',
    '        "brier_score": calibration.get("brier_score"),\n',
    '    }]\n',
    '    drift_history = [{\n',
    '        **base, "bocpd_probability": bocpd.get("probability"),\n',
    '        "adwin_detection_status": adwin.get("status"),\n',
    '        "adaptive_window_size": adwin.get("window_size"), "drift_type": drift_type,\n',
    '        "forecast_spread": forecast_spread, "error_drift_score": error_drift_score,\n',
    '        "volatility_drift_score": volatility_drift_score,\n',
    '        "action_taken": "Evidence recorded; protected regime unchanged" if safer_decision != "WAIT" else "Evidence recorded; safer decision constrained to WAIT",\n',
    '    }]\n',
    '    audit_history = [{\n',
    '        **base, "master_decision": str(final.get("final_decision") or "WAIT"),\n',
    '        "less_risky_decision": safer_decision,\n',
    '        "priority_rank": str(output.get("priority_rank") or _mapping(output.get("priority")).get("rank") or "-"),\n',
    '        "regime": current_regime, "regime_trust": calibrated_trust,\n',
    '        "forecast_reliability": _clip(reliability.get("score", raw_confidence)),\n',
    '        "conflict_status": conflict, "data_freshness": identity["data_freshness"],\n',
    '        "fallback_use": fallback_use, "reason_summary": reason,\n',
    '    }]\n',
    '    bundle = {\n',
    '        "regime_transition_history": transition_history,\n',
    '        "post_transition_outcome_history": outcome_history,\n',
    '        "prediction_calibration_history": calibration_history,\n',
    '        "drift_detector_history": drift_history,\n',
    '        "decision_audit_history": audit_history,\n',
    '    }\n',
    '    return output, result, bundle\n',
    '\n',
    '\n',
    '__all__ = [\n',
    '    "VERSION", "SCHEMA_VERSION", "DRIFT_LABELS", "bayesian_online_changepoint",\n',
    '    "adaptive_window_detection", "build_regime_transition_trust",\n',
    ']\n',
]
