"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '                published_at TEXT\n',
    '            )\n',
    '            """,\n',
    '            """\n',
    '            CREATE TABLE IF NOT EXISTS advanced_reliability_shift_vectors_v2 (\n',
    '                calculation_id TEXT NOT NULL,\n',
    '                calculation_generation INTEGER NOT NULL,\n',
    '                stream_type TEXT NOT NULL,\n',
    '                vector_time TEXT,\n',
    '                score REAL,\n',
    '                vector_json TEXT NOT NULL,\n',
    '                created_at TEXT NOT NULL,\n',
    '                PRIMARY KEY(calculation_id, stream_type)\n',
    '            )\n',
    '            """,\n',
    '            "CREATE INDEX IF NOT EXISTS idx_advanced_shift_generation_v2 ON advanced_reliability_shift_snapshots_v2(calculation_generation)",\n',
    '            "CREATE INDEX IF NOT EXISTS idx_advanced_shift_vector_time_v2 ON advanced_reliability_shift_vectors_v2(stream_type, vector_time)",\n',
    '        )\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            for statement in statements:\n',
    '                conn.execute(statement)\n',
    '\n',
    '    def stage(self, result: Mapping[str, Any], vectors: Optional[Mapping[str, Sequence[float]]] = None) -> Dict[str, Any]:\n',
    '        identity = _mapping(result.get("identity"))\n',
    '        calculation_id = str(identity.get("calculation_id") or "")\n',
    '        generation = int(identity.get("generation") or 0)\n',
    '        if not calculation_id:\n',
    '            return {"ok": False, "status": "SKIPPED", "reason": "Missing calculation id"}\n',
    '        compact = _json_safe(result)\n',
    '        now = _utc_now()\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            current = conn.execute("SELECT MAX(calculation_generation) AS generation FROM advanced_reliability_shift_snapshots_v2 WHERE publication_status=\'PUBLISHED\'").fetchone()\n',
    '            latest_generation = int(current["generation"] or 0) if current else 0\n',
    '            if generation < latest_generation:\n',
    '                return {"ok": False, "status": "STALE_REJECTED", "latest_generation": latest_generation}\n',
    '            conn.execute(\n',
    '                """\n',
    '                INSERT OR REPLACE INTO advanced_reliability_shift_snapshots_v2(\n',
    '                    calculation_id,calculation_generation,latest_completed_h1_time,data_hash,version,\n',
    '                    publication_status,payload_json,created_at,published_at\n',
    "                ) VALUES (?,?,?,?,?,'STAGED',?,?,NULL)\n",
    '                """,\n',
    '                (calculation_id, generation, str(identity.get("latest_completed_h1_time") or ""), str(identity.get("data_hash") or ""), VERSION, json.dumps(compact, ensure_ascii=False, default=str), now),\n',
    '            )\n',
    '            for stream_type, vector in (vectors or {}).items():\n',
    '                vector_list = [float(value) for value in list(vector)[:260] if _finite(value, None) is not None]\n',
    '                score = _finite(_mapping(result.get("rrcf")).get(f"{stream_type}_anomaly_score"), None)\n',
    '                conn.execute(\n',
    '                    """\n',
    '                    INSERT OR REPLACE INTO advanced_reliability_shift_vectors_v2(\n',
    '                        calculation_id,calculation_generation,stream_type,vector_time,score,vector_json,created_at\n',
    '                    ) VALUES (?,?,?,?,?,?,?)\n',
    '                    """,\n',
    '                    (calculation_id, generation, str(stream_type), str(identity.get("latest_completed_h1_time") or ""), score, json.dumps(vector_list), now),\n',
    '                )\n',
    '            # Bound persisted vectors without scanning application history.\n',
    '            conn.execute(\n',
    '                """\n',
    '                DELETE FROM advanced_reliability_shift_vectors_v2\n',
    '                WHERE rowid NOT IN (\n',
    '                    SELECT rowid FROM advanced_reliability_shift_vectors_v2\n',
    '                    ORDER BY calculation_generation DESC LIMIT 1024\n',
    '                )\n',
    '                """\n',
    '            )\n',
    '        return {"ok": True, "status": "STAGED", "calculation_id": calculation_id, "generation": generation}\n',
    '\n',
    '    def mark_published(self, calculation_id: str) -> Dict[str, Any]:\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            cursor = conn.execute("UPDATE advanced_reliability_shift_snapshots_v2 SET publication_status=\'PUBLISHED\',published_at=? WHERE calculation_id=? AND publication_status=\'STAGED\'", (_utc_now(), str(calculation_id)))\n',
    '        return {"ok": cursor.rowcount >= 0, "status": "PUBLISHED" if cursor.rowcount else "NOT_FOUND", "calculation_id": str(calculation_id)}\n',
    '\n',
    '    def latest(self) -> Dict[str, Any]:\n',
    '        with _LOCK, self.connection() as conn:\n',
    '            row = conn.execute("SELECT payload_json FROM advanced_reliability_shift_snapshots_v2 WHERE publication_status=\'PUBLISHED\' ORDER BY calculation_generation DESC LIMIT 1").fetchone()\n',
    '        if not row:\n',
    '            return {}\n',
    '        try:\n',
    '            return json.loads(row["payload_json"])\n',
    '        except Exception:\n',
    '            return {}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Integration and policy\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _renormalize_probabilities(probabilities: Mapping[str, float], direction: str, new_value: float) -> Dict[str, float]:\n',
    '    result = {label: float(probabilities.get(label, 0.0)) for label in ("BUY", "SELL", "WAIT")}\n',
    '    new_value = float(np.clip(new_value, 0, 1))\n',
    '    others = [label for label in result if label != direction]\n',
    '    other_total = sum(result[label] for label in others)\n',
    '    result[direction] = new_value\n',
    '    remaining = 1.0 - new_value\n',
    '    if other_total <= 1e-12:\n',
    '        for label in others:\n',
    '            result[label] = remaining / len(others)\n',
    '    else:\n',
    '        for label in others:\n',
    '            result[label] = remaining * result[label] / other_total\n',
    '    return result\n',
    '\n',
    '\n',
    'def _apply_probability_updates(canonical: MutableMapping[str, Any], probabilities: Mapping[str, float], source: str) -> None:\n',
    '    """Copy-on-write update of only the selected forecast row.\n',
    '\n',
    '    The canonical input can contain large record lists, so a full deepcopy would\n',
    '    be wasteful.  Copying the three nested mapping levels prevents mutation of\n',
    '    the protected pre-research canonical object without duplicating large data.\n',
    '    """\n',
    '    horizon = _selected_horizon(canonical)\n',
    '    forecasts = dict(_mapping(canonical.get("forecasts")))\n',
    '    horizons = dict(_mapping(forecasts.get("horizons")))\n',
    '    key = f"{horizon}h"\n',
    '    row = dict(_mapping(horizons.get(key)))\n',
    '    if not row:\n',
    '        return\n',
    '    row["buy_probability_calibrated"] = float(probabilities["BUY"])\n',
    '    row["sell_probability_calibrated"] = float(probabilities["SELL"])\n',
    '    row["wait_probability_calibrated"] = float(probabilities["WAIT"])\n',
    '    row["advanced_calibration_source"] = source\n',
    '    horizons[key] = row\n',
    '    forecasts["horizons"] = horizons\n',
    '    canonical["forecasts"] = forecasts\n',
    '\n',
    '\n',
    'def apply_advanced_reliability_policy(canonical: Mapping[str, Any], result: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    # Shallow top-level copy plus targeted copy-on-write mappings avoids both\n',
    '    # input mutation and a duplicate of large canonical histories/data frames.\n',
    '    payload = dict(canonical)\n',
    '    payload["metadata"] = dict(_mapping(canonical.get("metadata")))\n',
    '    final = dict(_mapping(canonical.get("final_decision")))\n',
    '    priority = dict(_mapping(canonical.get("priority")))\n',
    '    direction = _direction(final.get("directional_market_view") or payload.get("full_metric_direction"))\n',
    '    existing_decision = _direction(final.get("final_decision"))\n',
    '    probabilities = dict(_mapping(result.get("adjusted_probabilities")))\n',
    '    if probabilities and abs(sum(float(value) for value in probabilities.values()) - 1.0) <= 1e-6:\n',
    '        _apply_probability_updates(payload, probabilities, str(result.get("probability_adjustment_source") or "advanced_reliability_shift"))\n',
    '    trust_cap = _clip(result.get("trust_cap_pct"), 0, 100, 100)\n',
    '    existing_priority = _finite(priority.get("score"), None)\n',
    '    if existing_priority is not None:\n',
    '        priority["protected_score"] = existing_priority\n',
    '        priority["research_adjusted_score"] = min(existing_priority, trust_cap)\n',
    '        priority["research_adjustment_does_not_change_scale"] = True\n',
    '        payload["priority"] = priority\n',
    '    final["research_trust_cap_pct"] = trust_cap\n',
    '    final["research_adjusted_confidence"] = min(_prob(final.get("calibrated_confidence"), 1.0) or 1.0, trust_cap / 100.0)\n',
    '    warnings = list(final.get("supporting_reasons") or [])\n',
    '    blockers = list(final.get("blocking_reasons") or [])\n',
    '    mmd = _mapping(result.get("mmd"))\n',
    '    rrcf = _mapping(result.get("rrcf"))\n',
    '    if mmd.get("severity") in {"MEDIUM", "HIGH"}:\n',
    '        warnings.append(f"Advanced drift warning: MMD severity {mmd.get(\'severity\')}")\n',
    '    if max(_finite(rrcf.get("market_anomaly_score"), 0.0) or 0.0, _finite(rrcf.get("system_anomaly_score"), 0.0) or 0.0) >= 0.72:\n',
    '        warnings.append("Advanced anomaly warning: bounded random-cut forest score exceeded the conservative watch threshold")\n',
    '    crc = _mapping(result.get("conformal_risk_control"))\n',
    '    current_probability = _prob(probabilities.get(direction), None) if probabilities else _prob(final.get("calibrated_confidence"), None)\n',
    '    downgrade_reasons = []\n',
    '    if existing_decision in {"BUY", "SELL"} and crc.get("validity_status") in {"VALID", "CONSERVATIVE_BLOCK"}:\n',
    '        threshold = _prob(crc.get("threshold"), None)\n',
    '        upper = _prob(crc.get("risk_upper_bound"), None)\n',
    '        target = _prob(crc.get("target_risk"), None)\n',
    '        if crc.get("status") == "RISK_NOT_CONTROLLED":\n',
    '            downgrade_reasons.append(f"CRC risk upper bound {upper!s} did not meet target {target!s}")\n',
    '        if threshold is not None and current_probability is not None and current_probability + 1e-12 < threshold:\n',
    '            downgrade_reasons.append(f"Adjusted {direction} probability {current_probability:.3f} is below CRC threshold {threshold:.3f}")\n',
    '    if downgrade_reasons:\n',
    '        final["final_decision"] = "WAIT"\n',
    '        final["tradeability_decision"] = "WAIT"\n',
    '        final["less_risky_decision"] = "WAIT"\n',
    '        final["research_downgraded_from"] = existing_decision\n',
    '        blockers.extend(downgrade_reasons)\n',
    '        final["main_reason"] = downgrade_reasons[0]\n',
    '    final["supporting_reasons"] = list(dict.fromkeys(map(str, warnings)))\n',
    '    final["blocking_reasons"] = list(dict.fromkeys(map(str, blockers)))\n',
    '    final["advanced_reliability_policy"] = {\n',
    '        "direction_reversal_allowed": False,\n',
    '        "direction_before": direction,\n',
    '        "direction_after": _direction(final.get("directional_market_view") or direction),\n',
    '        "decision_before": existing_decision,\n',
    '        "decision_after": _direction(final.get("final_decision")),\n',
    '        "downgrade_reasons": downgrade_reasons,\n',
    '    }\n',
    '    payload["final_decision"] = final\n',
    '    payload["advanced_reliability_shift"] = _json_safe(result)\n',
    '    payload.setdefault("metadata", {})["advanced_reliability_shift_version"] = VERSION\n',
    '    payload["metadata"]["advanced_reliability_direction_policy"] = "confirm/reduce/warn/WAIT-only; never reverse BUY/SELL"\n',
    '    return payload\n',
    '\n',
    '\n',
    'def build_advanced_reliability_transaction(\n',
    '    canonical: Mapping[str, Any],\n',
    '    *,\n',
    '    completed_h1: pd.DataFrame,\n',
    '    settled_predictions: pd.DataFrame,\n',
    '    store: Optional[AdvancedReliabilityStore] = None,\n',
    '    previous: Optional[Mapping[str, Any]] = None,\n',
    '    persist_stage: bool = True,\n',
    ') -> Tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any]]:\n',
    '    """Compute, apply, and stage one hidden versioned research transaction."""\n',
    '    started = time.perf_counter()\n',
    '    latest = canonical.get("latest_completed_candle_time")\n',
    '    h1 = normalize_completed_h1(completed_h1, latest)\n',
    '    settled = normalize_settled_predictions(settled_predictions, latest)\n',
    '    identity = _current_identity(canonical, h1)\n',
    '    base_probabilities = _current_probabilities(canonical)\n',
    '\n',
    '    mmd = build_mmd_drift(h1, settled, identity)\n',
    '    bbse = bbse_label_shift(settled, mmd)\n',
    '    direction = str(identity.get("direction") or "WAIT")\n',
    '    probabilities = dict(base_probabilities)\n',
    '    probability_sources = []\n',
    '    if bbse.get("valid"):\n',
    '        weights = _mapping(_mapping(bbse.get("direction")).get("correction_weights"))\n',
    '        adjusted = {label: probabilities[label] * _clip(weights.get(label), 0.25, 4.0, 1.0) for label in probabilities}\n',
    '        total = sum(adjusted.values()) or 1.0\n',
    '        probabilities = {label: value / total for label, value in adjusted.items()}\n',
    '        probability_sources.append("BBSE")\n',
    '    multicalibration = multicalibrate_probability(settled, identity, probabilities.get(direction, 0.0))\n',
    '    if multicalibration.get("status") in {"VALID", "VALID_GLOBAL_FALLBACK"}:\n',
    '        probabilities = _renormalize_probabilities(probabilities, direction, float(multicalibration["calibrated_probability"]))\n',
    '        probability_sources.append("MULTICALIBRATION")\n',
    '    crc = conformal_risk_control(settled, identity)\n',
    '    revin = build_revin_evidence(h1, settled, canonical)\n',
    '    irm = irm_diagnostics(settled)\n',
    '    group_dro = group_dro_validation(settled)\n',
    '    rrcf = build_rrcf_anomaly(h1, settled, canonical, identity)\n',
    '    signatures = build_path_signature_features(h1)\n',
    '    dml = {"status": "DEFERRED_OFFLINE", "ran_during_navigation": False, "effects": {}, "reason": "No explicit maintenance request in normal Run Calculation."}\n',
    '\n',
    '    caps = [100.0, _finite(rrcf.get("combined_trust_cap_pct"), 100.0) or 100.0]\n',
    '    if mmd.get("severity") == "MEDIUM":\n',
    '        caps.append(80.0)\n',
    '    elif mmd.get("severity") == "HIGH":\n',
    '        caps.append(60.0)\n',
    '    invariance_score = _prob(irm.get("invariance_score"), None)\n',
    '    if invariance_score is not None:\n',
    '        caps.append(55.0 + 45.0 * invariance_score)\n',
    '    if group_dro.get("status") == "VALID":\n',
    '        selected_name = group_dro.get("selected_candidate")\n',
    '        robust = _prob(_mapping(_mapping(group_dro.get("candidates")).get(selected_name)).get("robust_selection_score"), None)\n',
    '        if robust is not None:\n',
    '            caps.append(50.0 + 50.0 * robust)\n',
    '    if crc.get("status") == "INSUFFICIENT_EVIDENCE":\n',
    '        caps.append(70.0)\n',
    '    trust_cap = float(min(caps))\n',
    '    result: Dict[str, Any] = {\n',
    '        "version": VERSION, "schema_version": SCHEMA_VERSION, "created_at": _utc_now(),\n',
    '        "identity": identity,\n',
    '        "input_contract": {"completed_h1_rows": int(len(h1)), "settled_prediction_rows": int(len(settled)), "completed_utc_h1_only": True, "bounded_windows": True, "renderers_calculate": False},\n',
    '        "conformal_risk_control": crc,\n',
    '        "multicalibration": multicalibration,\n',
    '        "revin": revin,\n',
    '        "mmd": mmd,\n',
    '        "bbse": bbse,\n',
    '        "dml": dml,\n',
    '        "irm": irm,\n',
    '        "group_dro": group_dro,\n',
    '        "rrcf": rrcf,\n',
    '        "path_signatures": signatures,\n',
    '        "base_probabilities": base_probabilities,\n',
    '        "adjusted_probabilities": probabilities,\n',
    '        "probability_adjustment_source": "+".join(probability_sources) if probability_sources else "UNCHANGED_INSUFFICIENT_OR_INVALID",\n',
    '        "trust_cap_pct": trust_cap,\n',
    '        "research_confidence_status": "VALIDATED" if crc.get("status") == "VALID" and trust_cap >= 70 else "CONSERVATIVE" if len(settled) >= 25 else "INSUFFICIENT_EVIDENCE",\n',
    '        "decision_policy": {"new_direction_engine": False, "direction_reversal_allowed": False, "allowed_actions": ["CONFIRM", "LOWER_CONFIDENCE", "LOWER_PRIORITY", "WARN", "DOWNGRADE_TO_WAIT"]},\n',
    '        "performance": {"duration_seconds": None, "bounded_ohlc_rows": _MAX_OHLC_ROWS, "bounded_settled_rows": _MAX_SETTLED_ROWS, "maximum_mmd_sample_per_side": _MAX_MMD_SAMPLE},\n',
    '        "limitations": [\n',
    '            "EURUSD H1 is serially dependent, so paper-level iid/exchangeability guarantees are not claimed.",\n',
    '            "RevIN influence remains disabled unless compatible contributor outputs and settled purged superiority evidence exist.",\n',
    '            "TP-first/SL-first BBSE is unavailable without a pre-outcome touch-class predictor.",\n',
    '            "The live anomaly implementation is a bounded random-cut-tree approximation, not an exact dynamic RRCF codisp implementation.",\n',
    '            "DML effects are not computed during normal UI navigation and require explicit historical event indicators.",\n',
    '        ],\n',
    '    }\n',
    '    result["performance"]["duration_seconds"] = round(time.perf_counter() - started, 6)\n',
    '    applied = apply_advanced_reliability_policy(canonical, result)\n',
    '    persistence = {"ok": False, "status": "NOT_REQUESTED"}\n',
    '    if persist_stage:\n',
    '        store = store or AdvancedReliabilityStore()\n',
    '        vector_payload = {"signature": _mapping(signatures).get("features", [])}\n',
    '        persistence = store.stage(result, vector_payload)\n',
    '    result["persistence"] = persistence\n',
    '    # Keep canonical and returned result synchronized after the staging status is known.\n',
    '    applied["advanced_reliability_shift"] = _json_safe(result)\n',
    '    return applied, result, persistence\n',
    '\n',
    '\n',
    'def mark_advanced_reliability_published(calculation_id: str, store: Optional[AdvancedReliabilityStore] = None) -> Dict[str, Any]:\n',
    '    return (store or AdvancedReliabilityStore()).mark_published(calculation_id)\n',
    '\n',
    '\n',
    '__all__ = [\n',
    '    "VERSION", "SCHEMA_VERSION", "AdvancedReliabilityStore",\n',
    '    "normalize_completed_h1", "normalize_settled_predictions", "completed_h1_hash",\n',
    '    "conformal_risk_control", "multicalibrate_probability",\n',
    '    "revin_normalize", "revin_inverse", "build_revin_evidence",\n',
    '    "rbf_mmd2", "mmd_block_test", "build_mmd_drift",\n',
    '    "bbse_label_shift", "chronological_purged_splits", "double_ml_partial_linear", "build_dml_event_effects",\n',
    '    "irm_diagnostics", "group_dro_validation", "random_cut_forest_score", "build_rrcf_anomaly",\n',
    '    "lead_lag_path", "truncated_signature", "build_path_signature_features",\n',
    '    "apply_advanced_reliability_policy", "build_advanced_reliability_transaction",\n',
    '    "mark_advanced_reliability_published",\n',
    ']\n',
]
