"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '    unsafe = losses["unsafe_non_wait"].to_numpy(dtype=float)\n',
    '    confidence = losses["confidence"].to_numpy(dtype=float)\n',
    '    for threshold in thresholds:\n',
    '        # Monotone bounded loss: a stricter threshold can only turn an action\n',
    '        # into abstention, so every per-row loss is non-increasing in threshold.\n',
    '        gated_loss = unsafe * (confidence >= threshold).astype(float)\n',
    '        observed = float(np.mean(gated_loss))\n',
    '        upper = min(1.0, observed + correction)\n',
    '        curve.append({\n',
    '            "threshold": float(threshold), "observed_risk": observed,\n',
    '            "risk_upper_bound": upper, "action_rate": float(np.mean(confidence >= threshold)),\n',
    '        })\n',
    '    feasible = [row for row in curve if row["risk_upper_bound"] <= target]\n',
    '    selected = feasible[0] if feasible else curve[-1]\n',
    '    loss_summary = {name: float(losses[name].mean()) for name in ("false_entry", "sl_before_tp", "incorrect_high_confidence", "unsafe_non_wait")}\n',
    '    valid = bool(feasible) and n >= minimum\n',
    '    return {\n',
    '        "status": "VALID" if valid else "RISK_NOT_CONTROLLED",\n',
    '        "validity_status": "VALID" if valid else "CONSERVATIVE_BLOCK",\n',
    '        "target_risk": target,\n',
    '        "observed_risk": selected["observed_risk"],\n',
    '        "risk_upper_bound": selected["risk_upper_bound"],\n',
    '        "threshold": selected["threshold"],\n',
    '        "condition": level,\n',
    '        "sample_count": n,\n',
    '        "minimum_sample_rule": minimum,\n',
    '        "action_rate": selected["action_rate"],\n',
    '        "losses": loss_summary,\n',
    '        "monotone_loss_verified": all(curve[index]["observed_risk"] + 1e-12 >= curve[index + 1]["observed_risk"] for index in range(len(curve) - 1)),\n',
    '        "curve": curve[::5] + ([curve[-1]] if curve[-1] not in curve[::5] else []),\n',
    '        "assumption_note": "Chronological settled operational approximation; no iid/exchangeability guarantee is claimed for EURUSD H1.",\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# B. Multicalibration with overlapping groups and shrinkage\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _settled_group_columns(frame: pd.DataFrame) -> pd.DataFrame:\n',
    '    origin = pd.to_datetime(frame.get("__origin", pd.Series(pd.NaT, index=frame.index)), utc=True, errors="coerce")\n',
    '    result = pd.DataFrame(index=frame.index)\n',
    '    result["session"] = origin.map(_session)\n',
    '    result["hour"] = origin.dt.hour.fillna(-1).astype(int)\n',
    '    result["h1_regime"] = _column_text(frame, ("h1_regime", "major_regime", "regime"))\n',
    '    result["h4_regime"] = _column_text(frame, ("h4_regime",))\n',
    '    result["d1_regime"] = _column_text(frame, ("d1_regime",))\n',
    '    result["volatility_state"] = _column_text(frame, ("volatility_state", "drift_status"))\n',
    '    result["direction"] = _predicted_direction_series(frame)\n',
    '    result["horizon"] = _column_numeric(frame, ("horizon", "horizon_hours")).fillna(-1).astype(int)\n',
    '    result["event_risk"] = _column_text(frame, ("event_risk_status", "event_importance"))\n',
    '    result["conflict"] = _column_text(frame, ("conflict_status", "strongest_blocker"), "NONE").str.upper().ne("NONE")\n',
    '    result["counter_trend"] = _column_text(frame, ("counter_trend", "strongest_blocker"), "").str.lower().str.contains("counter")\n',
    '    transition = _column_numeric(frame, ("regime_transition_risk", "transition_risk"))\n',
    '    result["transition_risk"] = pd.cut(transition, [-np.inf, 0.33, 0.66, np.inf], labels=["LOW", "MEDIUM", "HIGH"]).astype(str)\n',
    '    return result\n',
    '\n',
    '\n',
    'def multicalibrate_probability(\n',
    '    settled: pd.DataFrame,\n',
    '    identity: Mapping[str, Any],\n',
    '    raw_probability: float,\n',
    '    *,\n',
    '    min_support: int = 30,\n',
    '    shrinkage: float = 60.0,\n',
    '    max_total_adjustment: float = 0.15,\n',
    ') -> Dict[str, Any]:\n',
    '    direction = str(identity.get("direction") or "WAIT")\n',
    '    if settled.empty or direction not in {"BUY", "SELL", "WAIT"}:\n',
    '        return {"status": "INSUFFICIENT_EVIDENCE", "raw_probability": raw_probability, "calibrated_probability": raw_probability, "calibration_gap": 0.0, "subgroup_support": 0, "fallback_level": "NONE", "groups": []}\n',
    '    groups = _settled_group_columns(settled)\n',
    '    probability = _probability_for_direction(settled, direction, calibrated=False)\n',
    '    actual = (_actual_direction_series(settled) == direction).astype(float)\n',
    '    valid = probability.notna() & actual.notna()\n',
    '    probability = probability.loc[valid]\n',
    '    actual = actual.loc[valid]\n',
    '    groups = groups.loc[valid]\n',
    '    if len(probability) < min_support:\n',
    '        return {"status": "INSUFFICIENT_EVIDENCE", "raw_probability": raw_probability, "calibrated_probability": raw_probability, "calibration_gap": 0.0, "subgroup_support": int(len(probability)), "fallback_level": "GLOBAL_INSUFFICIENT", "groups": []}\n',
    '\n',
    '    transition_value = _finite(identity.get("transition_risk"), None)\n',
    '    transition_label = "UNKNOWN" if transition_value is None else "LOW" if transition_value <= 33 else "MEDIUM" if transition_value <= 66 else "HIGH"\n',
    '    current = {\n',
    '        "session": identity.get("session"), "hour": identity.get("hour"),\n',
    '        "h1_regime": identity.get("h1_regime"), "h4_regime": identity.get("h4_regime"),\n',
    '        "d1_regime": identity.get("d1_regime"), "volatility_state": identity.get("volatility_state"),\n',
    '        "direction": direction, "horizon": identity.get("horizon"), "event_risk": identity.get("event_risk"),\n',
    '        "conflict": bool(identity.get("conflict")), "counter_trend": bool(identity.get("counter_trend")),\n',
    '        "transition_risk": transition_label,\n',
    '    }\n',
    '    candidate_groups = []\n',
    '    for name, value in current.items():\n',
    '        if value in (None, "", "UNKNOWN", -1):\n',
    '            continue\n',
    '        mask = groups[name].astype(str) == str(value)\n',
    '        support = int(mask.sum())\n',
    '        if support < min_support:\n',
    '            continue\n',
    '        residual = float((actual.loc[mask] - probability.loc[mask]).mean())\n',
    '        weight = support / (support + shrinkage)\n',
    '        candidate_groups.append({"group": f"{name}={value}", "support": support, "raw_gap": residual, "shrinkage_weight": weight, "adjustment": residual * weight})\n',
    '    # Add a few high-value intersections only when they are genuinely supported.\n',
    '    intersections = (("session", "direction"), ("h1_regime", "direction"), ("horizon", "direction"), ("event_risk", "direction"), ("conflict", "direction"))\n',
    '    for fields in intersections:\n',
    '        if any(current.get(field) in (None, "", "UNKNOWN", -1) for field in fields):\n',
    '            continue\n',
    '        mask = pd.Series(True, index=groups.index)\n',
    '        for field in fields:\n',
    '            mask &= groups[field].astype(str) == str(current[field])\n',
    '        support = int(mask.sum())\n',
    '        if support < max(min_support, 40):\n',
    '            continue\n',
    '        residual = float((actual.loc[mask] - probability.loc[mask]).mean())\n',
    '        weight = support / (support + 1.5 * shrinkage)\n',
    '        candidate_groups.append({"group": "&".join(f"{field}={current[field]}" for field in fields), "support": support, "raw_gap": residual, "shrinkage_weight": weight, "adjustment": residual * weight})\n',
    '    if not candidate_groups:\n',
    '        global_gap = float((actual - probability).mean())\n',
    '        weight = len(probability) / (len(probability) + 2.0 * shrinkage)\n',
    '        adjustment = float(np.clip(global_gap * weight, -max_total_adjustment, max_total_adjustment))\n',
    '        calibrated = float(np.clip(raw_probability + adjustment, 0, 1))\n',
    '        return {"status": "VALID_GLOBAL_FALLBACK", "raw_probability": raw_probability, "calibrated_probability": calibrated, "calibration_gap": calibrated - raw_probability, "subgroup_support": int(len(probability)), "fallback_level": "GLOBAL", "groups": []}\n',
    '    candidate_groups = sorted(candidate_groups, key=lambda row: (-row["support"], abs(row["adjustment"])))[:8]\n',
    '    weights = np.array([math.sqrt(row["support"]) for row in candidate_groups], dtype=float)\n',
    '    adjustments = np.array([row["adjustment"] for row in candidate_groups], dtype=float)\n',
    '    aggregate = float(np.sum(weights * adjustments) / max(1e-12, np.sum(weights)))\n',
    '    aggregate = float(np.clip(aggregate, -max_total_adjustment, max_total_adjustment))\n',
    '    calibrated = float(np.clip(raw_probability + aggregate, 0, 1))\n',
    '    return {\n',
    '        "status": "VALID", "raw_probability": float(raw_probability),\n',
    '        "calibrated_probability": calibrated, "calibration_gap": calibrated - float(raw_probability),\n',
    '        "subgroup_support": int(max(row["support"] for row in candidate_groups)),\n',
    '        "fallback_level": "OVERLAPPING_GROUP_SHRINKAGE", "groups": candidate_groups,\n',
    '        "tiny_group_protection": {"minimum_support": min_support, "shrinkage": shrinkage, "maximum_total_adjustment": max_total_adjustment},\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# C. Reversible Instance Normalization wrapper / evidence gate\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def revin_normalize(values: Sequence[float], epsilon: float = 1e-8) -> Tuple[np.ndarray, float, float]:\n',
    '    array = np.asarray(values, dtype=float)\n',
    '    if array.size == 0:\n',
    '        return array.copy(), 0.0, 1.0\n',
    '    mean = float(np.nanmean(array))\n',
    '    std = float(np.nanstd(array))\n',
    '    if not math.isfinite(std) or std < epsilon:\n',
    '        std = 1.0\n',
    '    return (array - mean) / std, mean, std\n',
    '\n',
    '\n',
    'def revin_inverse(values: Sequence[float], mean: float, std: float) -> np.ndarray:\n',
    '    return np.asarray(values, dtype=float) * float(std) + float(mean)\n',
    '\n',
    '\n',
    'def build_revin_evidence(h1: pd.DataFrame, settled: pd.DataFrame, canonical: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    if h1.empty:\n',
    '        return {"status": "UNAVAILABLE", "influence_enabled": False, "reason": "No completed H1 input window.", "predictions": []}\n',
    '    close = h1["close"].tail(96).to_numpy(dtype=float)\n',
    '    normalized, mean, std = revin_normalize(close)\n',
    '    forecasts = _mapping(_mapping(canonical.get("forecasts")).get("horizons"))\n',
    '    predictions = []\n',
    '    for horizon in HORIZONS:\n',
    '        row = _mapping(forecasts.get(f"{horizon}h"))\n',
    '        original = _finite(row.get("point_forecast"), None)\n',
    '        if original is None:\n',
    '            continue\n',
    '        normalized_point = (original - mean) / std\n',
    '        reversed_point = float(revin_inverse([normalized_point], mean, std)[0])\n',
    '        predictions.append({"horizon": horizon, "original_prediction": original, "revin_prediction": reversed_point, "absolute_roundtrip_error": abs(reversed_point - original)})\n',
    '    original_col = _find_column(settled, ("original_prediction", "original_predicted_close")) if not settled.empty else None\n',
    '    revin_col = _find_column(settled, ("revin_prediction", "revin_predicted_close")) if not settled.empty else None\n',
    '    actual_col = _find_column(settled, ("actual_close",)) if not settled.empty else None\n',
    '    influence = False\n',
    '    evidence: Dict[str, Any] = {"status": "DIAGNOSTIC_ONLY", "sample_count": 0, "mae_original": None, "mae_revin": None, "relative_improvement": None}\n',
    '    if original_col and revin_col and actual_col:\n',
    '        validation = settled[[original_col, revin_col, actual_col]].apply(pd.to_numeric, errors="coerce").dropna().tail(1200)\n',
    '        if len(validation) >= 60:\n',
    '            split = int(len(validation) * 0.70)\n',
    '            test = validation.iloc[split:]\n',
    '            mae_original = float(np.mean(np.abs(test[original_col] - test[actual_col])))\n',
    '            mae_revin = float(np.mean(np.abs(test[revin_col] - test[actual_col])))\n',
    '            relative = (mae_original - mae_revin) / max(mae_original, 1e-12)\n',
    '            influence = bool(relative >= 0.02 and len(test) >= 20)\n',
    '            evidence = {"status": "VALID" if influence else "NO_SUPERIORITY", "sample_count": int(len(test)), "mae_original": mae_original, "mae_revin": mae_revin, "relative_improvement": relative, "purged_walk_forward_required": True}\n',
    '    return {\n',
    '        "status": evidence["status"], "input_window_rows": int(len(close)), "window_mean": mean,\n',
    '        "window_std": std, "latest_normalized_value": float(normalized[-1]) if normalized.size else None,\n',
    '        "predictions": predictions, "influence_enabled": influence, "settled_evidence": evidence,\n',
    '        "reason": "Existing contributor interface exposes price-space points only; RevIN is kept as a reversible wrapper and cannot influence weights without settled walk-forward superiority." if not influence else "Settled purged evidence met the conservative RevIN superiority gate.",\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# D. MMD drift detection with bounded block permutation\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _standardize_pair(x: np.ndarray, y: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:\n',
    '    pooled = np.vstack([x, y])\n',
    '    median = np.nanmedian(pooled, axis=0)\n',
    '    q75 = np.nanpercentile(pooled, 75, axis=0)\n',
    '    q25 = np.nanpercentile(pooled, 25, axis=0)\n',
    '    scale = q75 - q25\n',
    '    std = np.nanstd(pooled, axis=0)\n',
    '    scale = np.where((~np.isfinite(scale)) | (scale < 1e-9), std, scale)\n',
    '    scale = np.where((~np.isfinite(scale)) | (scale < 1e-9), 1.0, scale)\n',
    '    return np.nan_to_num((x - median) / scale), np.nan_to_num((y - median) / scale)\n',
    '\n',
    '\n',
    'def _pairwise_sqdist(x: np.ndarray, y: np.ndarray) -> np.ndarray:\n',
    '    return np.maximum(0.0, np.sum(x * x, axis=1)[:, None] + np.sum(y * y, axis=1)[None, :] - 2.0 * x @ y.T)\n',
    '\n',
    '\n',
    'def rbf_mmd2(x: np.ndarray, y: np.ndarray, gamma: Optional[float] = None) -> Tuple[float, float]:\n',
    '    x = np.asarray(x, dtype=float)\n',
    '    y = np.asarray(y, dtype=float)\n',
    '    if len(x) < 2 or len(y) < 2:\n',
    '        return 0.0, 1.0\n',
    '    x, y = _standardize_pair(x, y)\n',
    '    pooled = np.vstack([x, y])\n',
    '    if gamma is None:\n',
    '        sample = pooled[: min(96, len(pooled))]\n',
    '        distances = _pairwise_sqdist(sample, sample)\n',
    '        positive = distances[np.triu_indices_from(distances, k=1)]\n',
    '        positive = positive[positive > 1e-12]\n',
    '        median = float(np.median(positive)) if positive.size else 1.0\n',
    '        gamma = 1.0 / max(1e-9, 2.0 * median)\n',
    '    kxx = np.exp(-gamma * _pairwise_sqdist(x, x))\n',
    '    kyy = np.exp(-gamma * _pairwise_sqdist(y, y))\n',
    '    kxy = np.exp(-gamma * _pairwise_sqdist(x, y))\n',
    '    # Biased statistic is non-negative and stable in small bounded samples.\n',
    '    statistic = float(max(0.0, kxx.mean() + kyy.mean() - 2.0 * kxy.mean()))\n',
    '    return statistic, float(gamma)\n',
    '\n',
    '\n',
    'def mmd_block_test(\n',
    '    reference: np.ndarray,\n',
    '    recent: np.ndarray,\n',
    '    *,\n',
    '    seed: int = 0,\n',
    '    block_size: int = 6,\n',
    '    permutations: int = 64,\n',
    '    feature_names: Optional[Sequence[str]] = None,\n',
    ') -> Dict[str, Any]:\n',
    '    x = np.asarray(reference, dtype=float)[-_MAX_MMD_SAMPLE:]\n',
    '    y = np.asarray(recent, dtype=float)[-_MAX_MMD_SAMPLE:]\n',
    '    if x.ndim != 2 or y.ndim != 2 or len(x) < 12 or len(y) < 12 or x.shape[1] != y.shape[1]:\n',
    '        return {"status": "INSUFFICIENT_EVIDENCE", "statistic": None, "threshold": None, "significance": None, "severity": "UNKNOWN", "sample_count_reference": int(len(x) if x.ndim else 0), "sample_count_recent": int(len(y) if y.ndim else 0), "shifted_features": []}\n',
    '    observed, gamma = rbf_mmd2(x, y)\n',
    '    pooled = np.vstack([x, y])\n',
    '    n = len(x)\n',
    '    rng = np.random.default_rng(int(seed) % (2**32 - 1))\n',
    '    blocks = [np.arange(start, min(start + max(2, block_size), len(pooled))) for start in range(0, len(pooled), max(2, block_size))]\n',
    '    null = []\n',
    '    for _ in range(max(16, int(permutations))):\n',
    '        order = rng.permutation(len(blocks))\n',
    '        indices = np.concatenate([blocks[index] for index in order])\n',
    '        permuted = pooled[indices]\n',
    '        stat, _ = rbf_mmd2(permuted[:n], permuted[n:], gamma=gamma)\n',
    '        null.append(stat)\n',
    '    threshold = float(np.quantile(null, 0.95))\n',
    '    pvalue = float((1 + sum(value >= observed for value in null)) / (len(null) + 1))\n',
    '    ref_mean = np.nanmean(x, axis=0)\n',
    '    rec_mean = np.nanmean(y, axis=0)\n',
    '    pooled_std = np.nanstd(pooled, axis=0)\n',
    '    effects = np.abs(rec_mean - ref_mean) / np.where(pooled_std < 1e-9, 1.0, pooled_std)\n',
    '    names = list(feature_names or [f"feature_{index}" for index in range(x.shape[1])])\n',
    '    shifted = sorted(({"feature": names[index], "standardized_mean_shift": float(effects[index])} for index in range(len(names))), key=lambda row: row["standardized_mean_shift"], reverse=True)[:6]\n',
    '    significant = observed > threshold and pvalue <= 0.05\n',
    '    severity = "HIGH" if significant and observed > 2.0 * max(threshold, 1e-12) else "MEDIUM" if significant else "LOW"\n',
    '    return {"status": "VALID", "statistic": observed, "threshold": threshold, "significance": pvalue, "significant": significant, "severity": severity, "kernel": "RBF", "gamma": gamma, "block_size": block_size, "permutations": len(null), "sample_count_reference": int(len(x)), "sample_count_recent": int(len(y)), "shifted_features": shifted}\n',
    '\n',
    '\n',
    'def build_market_feature_frame(h1: pd.DataFrame) -> pd.DataFrame:\n',
    '    if h1.empty:\n',
    '        return pd.DataFrame()\n',
    '    result = pd.DataFrame({"time": h1["time"]})\n',
    '    close = pd.to_numeric(h1["close"], errors="coerce")\n',
    '    high = pd.to_numeric(h1["high"], errors="coerce")\n',
    '    low = pd.to_numeric(h1["low"], errors="coerce")\n',
    '    open_ = pd.to_numeric(h1["open"], errors="coerce")\n',
    '    volume = pd.to_numeric(h1.get("volume", 0.0), errors="coerce").fillna(0.0)\n',
    '    result["return"] = close.pct_change().fillna(0.0)\n',
    '    result["range"] = ((high - low) / close.replace(0, np.nan)).fillna(0.0)\n',
    '    result["pressure"] = ((close - open_) / (high - low).replace(0, np.nan)).fillna(0.0).clip(-2, 2)\n',
    '    result["volume_change"] = volume.pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0).clip(-10, 10)\n',
    '    result["volatility"] = result["return"].rolling(24, min_periods=6).std().fillna(0.0)\n',
    '    result["atr_proxy"] = (high - low).rolling(14, min_periods=4).mean().fillna(high - low)\n',
    '    for column in ("adx", "plus_di", "minus_di", "periodicity_normalized_residual"):\n',
    '        if column in h1:\n',
    '            result[column] = pd.to_numeric(h1[column], errors="coerce").fillna(0.0)\n',
    '    return result.replace([np.inf, -np.inf], np.nan).fillna(0.0)\n',
    '\n',
    '\n',
    'def build_mmd_drift(h1: pd.DataFrame, settled: pd.DataFrame, identity: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    features = build_market_feature_frame(h1)\n',
    '    columns = [column for column in ("return", "range", "pressure", "volume_change", "volatility", "atr_proxy", "adx", "plus_di", "minus_di") if column in features]\n',
    '    seed = int(_stable_hash(identity)[:8], 16)\n',
    '    comparisons: Dict[str, Any] = {}\n',
    '    if len(features) >= 96:\n',
    '        recent = features[columns].tail(48).to_numpy(dtype=float)\n',
    '        reference = features[columns].iloc[:-48].tail(600).to_numpy(dtype=float)\n',
    '        comparisons["recent_vs_25_day"] = mmd_block_test(reference, recent, seed=seed, feature_names=columns)\n',
    '        current_session = str(identity.get("session") or "UNKNOWN")\n',
    '        sessions = features["time"].map(_session)\n',
    '        session_rows = features.loc[sessions == current_session, columns]\n',
    '        if len(session_rows) >= 36:\n',
    '            comparisons["current_session_vs_historical_session"] = mmd_block_test(session_rows.iloc[:-12].to_numpy(dtype=float), session_rows.tail(12).to_numpy(dtype=float), seed=seed + 1, feature_names=columns)\n',
    '    if not settled.empty:\n',
    '        residual_columns = [column for column in ("absolute_error_pips", "squared_error", "maximum_favorable_excursion", "maximum_adverse_excursion") if column in settled]\n',
    '        if residual_columns:\n',
    '            residuals = settled[residual_columns].apply(pd.to_numeric, errors="coerce").dropna()\n',
    '            if len(residuals) >= 48:\n',
    '                split = max(24, int(len(residuals) * 0.75))\n',
    '                comparisons["recent_residual_vs_reference_residual"] = mmd_block_test(residuals.iloc[:split].to_numpy(dtype=float), residuals.iloc[split:].to_numpy(dtype=float), seed=seed + 2, feature_names=residual_columns)\n',
    '    valid = [value for value in comparisons.values() if value.get("status") == "VALID"]\n',
    '    severity_order = {"UNKNOWN": 0, "LOW": 1, "MEDIUM": 2, "HIGH": 3}\n',
    '    severity = max((value.get("severity", "UNKNOWN") for value in valid), key=lambda label: severity_order.get(label, 0), default="UNKNOWN")\n',
    '    significant = any(bool(value.get("significant")) for value in valid)\n',
    '    return {"status": "VALID" if valid else "INSUFFICIENT_EVIDENCE", "severity": severity, "strong_feature_drift": significant and severity in {"MEDIUM", "HIGH"}, "comparisons": comparisons, "bounded_samples": True, "maximum_sample_per_side": _MAX_MMD_SAMPLE}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# E. BBSE label-shift correction\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _confusion_pred_given_true(predicted: Sequence[str], actual: Sequence[str], labels: Sequence[str]) -> np.ndarray:\n',
    '    matrix = np.zeros((len(labels), len(labels)), dtype=float)\n',
    '    lookup = {label: index for index, label in enumerate(labels)}\n',
    '    for pred, truth in zip(predicted, actual):\n',
    '        if pred in lookup and truth in lookup:\n',
    '            matrix[lookup[pred], lookup[truth]] += 1.0\n',
    '    for column in range(matrix.shape[1]):\n',
    '        total = matrix[:, column].sum()\n',
    '        if total > 0:\n',
    '            matrix[:, column] /= total\n',
    '    return matrix\n',
    '\n',
    '\n',
    'def _prior(labels_values: Sequence[str], labels: Sequence[str]) -> np.ndarray:\n',
    '    values = pd.Series(labels_values).value_counts(normalize=True)\n',
    '    return np.array([float(values.get(label, 0.0)) for label in labels], dtype=float)\n',
    '\n',
    '\n',
    'def bbse_label_shift(settled: pd.DataFrame, mmd: Mapping[str, Any]) -> Dict[str, Any]:\n',
    '    labels = ("BUY", "SELL", "WAIT")\n',
    '    if settled.empty or len(settled) < 90:\n',
    '        return {"status": "INSUFFICIENT_EVIDENCE", "valid": False, "reason": "At least 90 chronological settled rows are required.", "direction": {}, "tp_sl": {"status": "UNAVAILABLE", "reason": "Insufficient predictor/outcome labels."}}\n',
    '    if bool(mmd.get("strong_feature_drift")):\n',
    '        return {"status": "REJECTED", "valid": False, "reason": "Strong feature drift contradicts the label-shift-only assumption.", "direction": {}, "tp_sl": {"status": "UNAVAILABLE", "reason": "Correction disabled while feature drift is strong."}}\n',
    '    predicted = _predicted_direction_series(settled)\n',
    '    actual = _actual_direction_series(settled)\n',
    '    split = int(len(settled) * 0.70)\n',
    '    reference_pred, reference_actual = predicted.iloc[:split], actual.iloc[:split]\n',
    '    current_pred = predicted.iloc[split:]\n',
    '    support = reference_actual.value_counts()\n',
    '    if any(int(support.get(label, 0)) < 10 for label in labels):\n',
    '        return {"status": "REJECTED", "valid": False, "reason": "Reference confusion matrix has fewer than 10 samples in at least one direction class.", "direction": {"class_support": support.to_dict()}, "tp_sl": {"status": "UNAVAILABLE", "reason": "Direction support failed."}}\n',
    '    confusion = _confusion_pred_given_true(reference_pred, reference_actual, labels)\n',
    '    condition = float(np.linalg.cond(confusion))\n',
    '    rank = int(np.linalg.matrix_rank(confusion))\n',
    '    if rank < len(labels) or not math.isfinite(condition) or condition > 50.0:\n',
    '        return {"status": "REJECTED", "valid": False, "reason": "Confusion matrix is singular or ill-conditioned.", "direction": {"confusion_matrix": confusion.tolist(), "condition_number": condition, "rank": rank}, "tp_sl": {"status": "UNAVAILABLE", "reason": "Direction correction rejected."}}\n',
    '    q_pred = _prior(current_pred, labels)\n',
    '    estimated = np.linalg.solve(confusion, q_pred)\n',
    '    estimated = np.clip(estimated, 0.0, None)\n',
    '    estimated = estimated / max(estimated.sum(), 1e-12)\n',
    '    original = _prior(reference_actual, labels)\n',
    '    weights = estimated / np.maximum(original, 1e-9)\n',
    '    direction = {\n',
    '        "status": "VALID", "labels": list(labels), "confusion_matrix": confusion.tolist(),\n',
    '        "condition_number": condition, "rank": rank,\n',
    '        "original_priors": {label: float(original[index]) for index, label in enumerate(labels)},\n',
    '        "current_predicted_priors": {label: float(q_pred[index]) for index, label in enumerate(labels)},\n',
    '        "estimated_current_priors": {label: float(estimated[index]) for index, label in enumerate(labels)},\n',
    '        "correction_weights": {label: float(weights[index]) for index, label in enumerate(labels)},\n',
    '        "reference_sample_count": int(split), "current_sample_count": int(len(settled) - split),\n',
    '    }\n',
    '    touch_pred_col = _find_column(settled, ("predicted_touch_label", "predicted_tp_sl_label"))\n',
    '    if touch_pred_col and {"tp_touched", "sl_touched"}.issubset(settled.columns):\n',
    '        touch_actual = np.where(pd.to_numeric(settled["tp_touched"], errors="coerce").fillna(0) > 0, "TP_FIRST", np.where(pd.to_numeric(settled["sl_touched"], errors="coerce").fillna(0) > 0, "SL_FIRST", "NEITHER"))\n',
    '        touch = {"status": "AVAILABLE_FOR_OFFLINE_EXTENSION", "observed_base_rates": pd.Series(touch_actual).value_counts(normalize=True).to_dict(), "note": "A full BBSE correction requires a validated pre-outcome touch-class predictor."}\n',
    '    else:\n',
    '        tp = _column_numeric(settled, ("tp_touched",)).fillna(0)\n',
    '        sl = _column_numeric(settled, ("sl_touched",)).fillna(0)\n',
    '        touch = {"status": "UNAVAILABLE", "reason": "No pre-outcome TP-first/SL-first predictor label exists in the settled schema.", "observed_base_rates": {"TP_FIRST": float(((tp > 0) & (sl <= 0)).mean()), "SL_FIRST": float(((sl > 0) & (tp <= 0)).mean()), "OTHER_OR_ORDER_UNKNOWN": float(((tp > 0) == (sl > 0)).mean())}}\n',
    '    return {"status": "VALID", "valid": True, "reason": "Chronological BBSE direction correction passed support and conditioning checks.", "direction": direction, "tp_sl": touch, "assumption": "p(x|y) stable; correction is rejected under strong feature drift."}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# F. Double / Debiased Machine Learning (offline bounded maintenance only)\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def chronological_purged_splits(n_rows: int, *, n_splits: int = 3, purge: int = 6, embargo: int = 6, min_train: int = 40) -> Sequence[Tuple[np.ndarray, np.ndarray]]:\n',
    '    if n_rows < min_train + 20:\n',
    '        return []\n',
    '    boundaries = np.linspace(min_train, n_rows, n_splits + 1, dtype=int)\n',
    '    splits = []\n',
    '    for index in range(n_splits):\n',
    '        test_start = int(boundaries[index])\n',
    '        test_end = int(boundaries[index + 1])\n',
    '        train_end = max(0, test_start - max(purge, embargo))\n',
    '        train = np.arange(0, train_end, dtype=int)\n',
    '        test = np.arange(test_start, test_end, dtype=int)\n',
    '        if len(train) >= min_train and len(test) >= 8:\n',
    '            splits.append((train, test))\n',
    '    return splits\n',
    '\n',
    '\n',
    'def _ridge_fit(x: np.ndarray, y: np.ndarray, penalty: float = 1.0) -> np.ndarray:\n',
    '    x = np.asarray(x, dtype=float)\n',
    '    y = np.asarray(y, dtype=float)\n',
    '    design = np.column_stack([np.ones(len(x)), x])\n',
    '    identity = np.eye(design.shape[1])\n',
    '    identity[0, 0] = 0.0\n',
    '    return np.linalg.pinv(design.T @ design + penalty * identity) @ design.T @ y\n',
]
