"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""Second-generation reliability and distribution-shift transaction.\n',
    '\n',
    'This module is intentionally additive and display-independent.  It consumes one\n',
    'already-cleaned completed-UTC-H1 frame, one chronological settled-prediction\n',
    'frame, and one canonical payload.  It never creates an independent BUY/SELL\n',
    'signal and never reverses the protected Full Metric direction.  Its only policy\n',
    'powers are to:\n',
    '\n',
    '* calibrate probabilities when evidence and assumptions are valid;\n',
    '* cap research trust / effective priority;\n',
    '* append warnings; and\n',
    '* conservatively downgrade an existing BUY/SELL tradeability decision to WAIT\n',
    '  through the final Conformal Risk Control gate.\n',
    '\n',
    'The implementation is lightweight (NumPy/Pandas/SQLite only), bounded, and safe\n',
    'for Streamlit Cloud / Python 3.12.  Offline-only DML maintenance is exposed as a\n',
    'pure function and is never executed by normal tab navigation.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import hashlib\n',
    'import json\n',
    'import math\n',
    'import os\n',
    'import sqlite3\n',
    'import threading\n',
    'import time\n',
    'from contextlib import contextmanager\n',
    'from dataclasses import dataclass\n',
    'from datetime import datetime, timezone\n',
    'from pathlib import Path\n',
    'from typing import Any, Dict, Iterable, Mapping, MutableMapping, Optional, Sequence, Tuple\n',
    '\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    '\n',
    'VERSION = "advanced-reliability-shift-20260620-v2"\n',
    'SCHEMA_VERSION = "adx-advanced-reliability-shift-2.0.0"\n',
    'PROJECT_ROOT = Path(__file__).resolve().parents[1]\n',
    'DEFAULT_DB_PATH = PROJECT_ROOT / "data" / "quant_app.sqlite3"\n',
    'HORIZONS = (1, 2, 3, 6)\n',
    '_MAX_OHLC_ROWS = 720\n',
    '_MAX_SETTLED_ROWS = 6000\n',
    '_MAX_MMD_SAMPLE = 128\n',
    '_LOCK = threading.RLock()\n',
    '\n',
    '\n',
    'def _utc_now() -> str:\n',
    '    return datetime.now(timezone.utc).isoformat()\n',
    '\n',
    '\n',
    'def _mapping(value: Any) -> Mapping[str, Any]:\n',
    '    return value if isinstance(value, Mapping) else {}\n',
    '\n',
    '\n',
    'def _finite(value: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    try:\n',
    '        result = float(value)\n',
    '        return result if math.isfinite(result) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(value: Any, lo: float, hi: float, default: float = 0.0) -> float:\n',
    '    number = _finite(value, default)\n',
    '    return float(max(lo, min(hi, number if number is not None else default)))\n',
    '\n',
    '\n',
    'def _prob(value: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    number = _finite(value, default)\n',
    '    if number is None:\n',
    '        return None\n',
    '    if number > 1.0:\n',
    '        number /= 100.0\n',
    '    return float(max(0.0, min(1.0, number)))\n',
    '\n',
    '\n',
    'def _direction(value: Any) -> str:\n',
    '    text = str(value or "").upper()\n',
    '    if "BUY" in text or "BULL" in text or text == "UP":\n',
    '        return "BUY"\n',
    '    if "SELL" in text or "BEAR" in text or text == "DOWN":\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    'def _utc(value: Any) -> Optional[pd.Timestamp]:\n',
    '    try:\n',
    '        ts = pd.Timestamp(value)\n',
    '        if pd.isna(ts):\n',
    '            return None\n',
    '        return ts.tz_localize("UTC") if ts.tzinfo is None else ts.tz_convert("UTC")\n',
    '    except Exception:\n',
    '        return None\n',
    '\n',
    '\n',
    'def _session(value: Any) -> str:\n',
    '    ts = _utc(value)\n',
    '    if ts is None:\n',
    '        return "UNKNOWN"\n',
    '    hour = int(ts.hour)\n',
    '    if 0 <= hour < 7:\n',
    '        return "ASIA"\n',
    '    if 7 <= hour < 12:\n',
    '        return "LONDON"\n',
    '    if 12 <= hour < 16:\n',
    '        return "LONDON_NY_OVERLAP"\n',
    '    if 16 <= hour < 21:\n',
    '        return "NEW_YORK"\n',
    '    return "LATE_NY"\n',
    '\n',
    '\n',
    'def _json_safe(value: Any) -> Any:\n',
    '    if isinstance(value, Mapping):\n',
    '        return {str(k): _json_safe(v) for k, v in value.items()}\n',
    '    if isinstance(value, (list, tuple)):\n',
    '        return [_json_safe(v) for v in value]\n',
    '    if isinstance(value, np.ndarray):\n',
    '        return [_json_safe(v) for v in value.tolist()]\n',
    '    if isinstance(value, pd.DataFrame):\n',
    '        return [_json_safe(v) for v in value.to_dict("records")]\n',
    '    if isinstance(value, pd.Series):\n',
    '        return [_json_safe(v) for v in value.tolist()]\n',
    '    if isinstance(value, (pd.Timestamp, datetime)):\n',
    '        ts = _utc(value)\n',
    '        return ts.isoformat() if ts is not None else str(value)\n',
    '    if isinstance(value, (np.floating, float)):\n',
    '        return float(value) if math.isfinite(float(value)) else None\n',
    '    if isinstance(value, (np.integer, int)):\n',
    '        return int(value)\n',
    '    if isinstance(value, (np.bool_, bool)):\n',
    '        return bool(value)\n',
    '    if value is pd.NA:\n',
    '        return None\n',
    '    return value\n',
    '\n',
    '\n',
    'def _stable_hash(value: Any) -> str:\n',
    '    payload = json.dumps(_json_safe(value), sort_keys=True, separators=(",", ":"), default=str)\n',
    '    return hashlib.sha256(payload.encode("utf-8")).hexdigest()\n',
    '\n',
    '\n',
    'def _find_column(frame: pd.DataFrame, aliases: Sequence[str]) -> Optional[str]:\n',
    '    lookup = {str(column).strip().lower(): column for column in frame.columns}\n',
    '    return next((lookup[name.lower()] for name in aliases if name.lower() in lookup), None)\n',
    '\n',
    '\n',
    'def normalize_completed_h1(frame: Any, latest_completed: Any = None, *, limit: int = _MAX_OHLC_ROWS) -> pd.DataFrame:\n',
    '    """Return one sorted, unique, bounded completed-H1 frame.\n',
    '\n',
    '    The upstream data-quality layer already removes an open candle.  This helper\n',
    '    applies an additional explicit canonical cutoff and never infers or appends\n',
    '    future rows.  Rolling features elsewhere use trailing windows only.\n',
    '    """\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close", "volume"])\n',
    '    data = frame.copy(deep=False)\n',
    '    tcol = _find_column(data, ("time", "timestamp", "datetime", "date"))\n',
    '    columns: Dict[str, Optional[str]] = {\n',
    '        name: _find_column(data, (name, name[0])) for name in ("open", "high", "low", "close")\n',
    '    }\n',
    '    if any(value is None for value in columns.values()):\n',
    '        return pd.DataFrame(columns=["time", "open", "high", "low", "close", "volume"])\n',
    '    times = pd.to_datetime(data[tcol] if tcol is not None else data.index, errors="coerce", utc=True)\n',
    '    out = pd.DataFrame({"time": times})\n',
    '    for name, column in columns.items():\n',
    '        out[name] = pd.to_numeric(data[column], errors="coerce").to_numpy()\n',
    '    volume_col = _find_column(data, ("volume", "tick_volume", "real_volume"))\n',
    '    out["volume"] = pd.to_numeric(data[volume_col], errors="coerce").to_numpy() if volume_col else 0.0\n',
    '    # Carry existing bounded indicators without recalculating them.\n',
    '    for name in ("atr", "adx", "plus_di", "minus_di", "pressure", "periodicity_normalized_residual"):\n',
    '        column = _find_column(data, (name,))\n',
    '        if column is not None:\n',
    '            out[name] = pd.to_numeric(data[column], errors="coerce").to_numpy()\n',
    '    out = out.dropna(subset=["time", "open", "high", "low", "close"]).sort_values("time")\n',
    '    out = out.drop_duplicates("time", keep="last")\n',
    '    cutoff = _utc(latest_completed)\n',
    '    if cutoff is not None:\n',
    '        out = out.loc[out["time"] <= cutoff]\n',
    '    return out.tail(max(1, int(limit))).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def normalize_settled_predictions(frame: Any, latest_completed: Any = None, *, limit: int = _MAX_SETTLED_ROWS) -> pd.DataFrame:\n',
    '    """Return one chronological bounded settled-evidence frame."""\n',
    '    if not isinstance(frame, pd.DataFrame) or frame.empty:\n',
    '        return pd.DataFrame()\n',
    '    data = frame.copy(deep=False)\n',
    '    status_col = _find_column(data, ("record_status", "outcome_status", "status"))\n',
    '    if status_col is not None:\n',
    '        statuses = data[status_col].astype(str).str.upper()\n',
    '        if statuses.str.contains("SETTLED").any():\n',
    '            data = data.loc[statuses.str.contains("SETTLED")]\n',
    '    origin_col = _find_column(data, ("forecast_origin_time", "origin_time", "created_at", "time"))\n',
    '    target_col = _find_column(data, ("target_time", "settled_target_time"))\n',
    '    settled_col = _find_column(data, ("settlement_timestamp", "settled_at"))\n',
    '    data = data.assign(\n',
    '        __origin=pd.to_datetime(data[origin_col], errors="coerce", utc=True) if origin_col else pd.NaT,\n',
    '        __target=pd.to_datetime(data[target_col], errors="coerce", utc=True) if target_col else pd.NaT,\n',
    '        __settled=pd.to_datetime(data[settled_col], errors="coerce", utc=True) if settled_col else pd.NaT,\n',
    '    )\n',
    '    data["__order"] = data["__settled"].fillna(data["__target"]).fillna(data["__origin"])\n',
    '    cutoff = _utc(latest_completed)\n',
    '    if cutoff is not None:\n',
    '        data = data.loc[data["__target"].isna() | (data["__target"] <= cutoff)]\n',
    '    data = data.loc[data["__order"].notna()].sort_values("__order")\n',
    '    calc_col = _find_column(data, ("calculation_id", "canonical_calculation_id", "run_id"))\n',
    '    horizon_col = _find_column(data, ("horizon", "horizon_hours"))\n',
    '    if calc_col and horizon_col:\n',
    '        data = data.drop_duplicates([calc_col, horizon_col], keep="last")\n',
    '    return data.tail(max(1, int(limit))).reset_index(drop=True)\n',
    '\n',
    '\n',
    'def completed_h1_hash(frame: pd.DataFrame) -> str:\n',
    '    if frame.empty:\n',
    '        return hashlib.sha256(b"empty-h1").hexdigest()\n',
    '    columns = [column for column in ("time", "open", "high", "low", "close", "volume") if column in frame]\n',
    '    records = frame[columns].tail(_MAX_OHLC_ROWS).copy(deep=False)\n',
    '    if "time" in records:\n',
    '        records = records.assign(time=pd.to_datetime(records["time"], utc=True, errors="coerce").astype(str))\n',
    '    return _stable_hash(records.to_dict("records"))\n',
    '\n',
    '\n',
    'def _selected_horizon(canonical: Mapping[str, Any]) -> int:\n',
    '    final = _mapping(canonical.get("final_decision"))\n',
    '    forecasts = _mapping(canonical.get("forecasts"))\n',
    '    value = _finite(final.get("selected_horizon") or forecasts.get("selected_horizon"), 3)\n',
    '    horizon = int(value or 3)\n',
    '    return horizon if horizon in HORIZONS else 3\n',
    '\n',
    '\n',
    'def _selected_forecast(canonical: Mapping[str, Any]) -> Mapping[str, Any]:\n',
    '    horizon = _selected_horizon(canonical)\n',
    '    return _mapping(_mapping(_mapping(canonical.get("forecasts")).get("horizons")).get(f"{horizon}h"))\n',
    '\n',
    '\n',
    'def _current_identity(canonical: Mapping[str, Any], h1: pd.DataFrame) -> Dict[str, Any]:\n',
    '    final = _mapping(canonical.get("final_decision"))\n',
    '    regime = _mapping(canonical.get("regime"))\n',
    '    multiscale = _mapping(canonical.get("multiscale_regime"))\n',
    '    latest = canonical.get("latest_completed_candle_time")\n',
    '    if latest is None and not h1.empty:\n',
    '        latest = h1["time"].iloc[-1]\n',
    '    direction = _direction(final.get("directional_market_view") or canonical.get("full_metric_direction"))\n',
    '    return {\n',
    '        "calculation_id": str(canonical.get("canonical_calculation_id") or canonical.get("run_id") or ""),\n',
    '        "generation": int(_finite(canonical.get("calculation_generation"), 0) or 0),\n',
    '        "latest_completed_h1_time": _json_safe(latest),\n',
    '        "data_hash": completed_h1_hash(h1),\n',
    '        "direction": direction,\n',
    '        "decision": _direction(final.get("final_decision")),\n',
    '        "horizon": _selected_horizon(canonical),\n',
    '        "session": _session(latest),\n',
    '        "hour": int(_utc(latest).hour) if _utc(latest) is not None else None,\n',
    '        "h1_regime": str(regime.get("h1_regime") or regime.get("major_regime") or canonical.get("current_major_regime") or "UNKNOWN"),\n',
    '        "h4_regime": str(regime.get("h4_regime") or "UNKNOWN"),\n',
    '        "d1_regime": str(regime.get("d1_regime") or "UNKNOWN"),\n',
    '        "volatility_state": str(multiscale.get("current_volatility_regime") or "UNKNOWN"),\n',
    '        "event_risk": str(_mapping(canonical.get("nlp")).get("event_risk_status") or _mapping(canonical.get("nlp")).get("importance") or "UNKNOWN"),\n',
    '        "conflict": bool(final.get("blocking_reasons")),\n',
    '        "counter_trend": bool("counter" in " ".join(map(str, final.get("blocking_reasons") or [])).lower()),\n',
    '        "transition_risk": _finite(multiscale.get("multi_scale_transition_risk_pct") or regime.get("transition_risk"), None),\n',
    '    }\n',
    '\n',
    '\n',
    'def _column_numeric(frame: pd.DataFrame, aliases: Sequence[str], default: Any = np.nan) -> pd.Series:\n',
    '    column = _find_column(frame, aliases)\n',
    '    if column is None:\n',
    '        return pd.Series(default, index=frame.index, dtype=float)\n',
    '    return pd.to_numeric(frame[column], errors="coerce")\n',
    '\n',
    '\n',
    'def _column_text(frame: pd.DataFrame, aliases: Sequence[str], default: str = "UNKNOWN") -> pd.Series:\n',
    '    column = _find_column(frame, aliases)\n',
    '    if column is None:\n',
    '        return pd.Series(default, index=frame.index, dtype=object)\n',
    '    return frame[column].fillna(default).astype(str)\n',
    '\n',
    '\n',
    'def _predicted_direction_series(frame: pd.DataFrame) -> pd.Series:\n',
    '    column = _find_column(frame, ("full_metric_direction", "final_decision", "predicted_direction", "direction"))\n',
    '    if column is not None:\n',
    '        return frame[column].map(_direction)\n',
    '    buy = _column_numeric(frame, ("calibrated_buy_probability", "raw_buy_probability"))\n',
    '    sell = _column_numeric(frame, ("calibrated_sell_probability", "raw_sell_probability"))\n',
    '    wait = _column_numeric(frame, ("calibrated_wait_probability", "raw_wait_probability"))\n',
    '    matrix = np.column_stack([buy.fillna(0), sell.fillna(0), wait.fillna(0)])\n',
    '    labels = np.array(["BUY", "SELL", "WAIT"])\n',
    '    return pd.Series(labels[np.argmax(matrix, axis=1)], index=frame.index)\n',
    '\n',
    '\n',
    'def _actual_direction_series(frame: pd.DataFrame) -> pd.Series:\n',
    '    actual = _column_numeric(frame, ("actual_close",))\n',
    '    origin = _column_numeric(frame, ("forecast_origin_price", "origin_price", "last_close"))\n',
    '    delta = actual - origin\n',
    '    deadband = 0.00002\n',
    '    labels = np.where(delta > deadband, "BUY", np.where(delta < -deadband, "SELL", "WAIT"))\n',
    '    missing = actual.isna() | origin.isna()\n',
    '    predicted = _predicted_direction_series(frame)\n',
    '    correct = _column_numeric(frame, ("direction_correct",))\n',
    '    fallback = np.where(correct.fillna(-1).to_numpy() == 1, predicted.to_numpy(), np.where(predicted == "BUY", "SELL", np.where(predicted == "SELL", "BUY", "WAIT")))\n',
    '    labels = np.where(missing.to_numpy(), fallback, labels)\n',
    '    return pd.Series(labels, index=frame.index)\n',
    '\n',
    '\n',
    'def _probability_for_direction(frame: pd.DataFrame, direction: str, *, calibrated: bool = True) -> pd.Series:\n',
    '    prefix = "calibrated" if calibrated else "raw"\n',
    '    aliases = (f"{prefix}_{direction.lower()}_probability", f"{direction.lower()}_probability_{prefix}")\n',
    '    series = _column_numeric(frame, aliases)\n',
    '    if series.notna().sum() == 0 and calibrated:\n',
    '        series = _probability_for_direction(frame, direction, calibrated=False)\n',
    '    return series.map(lambda value: _prob(value, np.nan))\n',
    '\n',
    '\n',
    'def _current_probabilities(canonical: Mapping[str, Any]) -> Dict[str, float]:\n',
    '    forecast = _selected_forecast(canonical)\n',
    '    values = {\n',
    '        "BUY": _prob(forecast.get("buy_probability_calibrated") or forecast.get("buy_probability_raw"), None),\n',
    '        "SELL": _prob(forecast.get("sell_probability_calibrated") or forecast.get("sell_probability_raw"), None),\n',
    '        "WAIT": _prob(forecast.get("wait_probability_calibrated") or forecast.get("wait_probability_raw"), None),\n',
    '    }\n',
    '    missing = [key for key, value in values.items() if value is None]\n',
    '    if missing:\n',
    '        direction = _direction(_mapping(canonical.get("final_decision")).get("directional_market_view"))\n',
    '        default = {"BUY": 0.25, "SELL": 0.25, "WAIT": 0.50}\n',
    '        if direction == "BUY":\n',
    '            default = {"BUY": 0.55, "SELL": 0.20, "WAIT": 0.25}\n',
    '        elif direction == "SELL":\n',
    '            default = {"BUY": 0.20, "SELL": 0.55, "WAIT": 0.25}\n',
    '        for key in missing:\n',
    '            values[key] = default[key]\n',
    '    total = sum(float(value or 0) for value in values.values()) or 1.0\n',
    '    return {key: float(value or 0) / total for key, value in values.items()}\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# A. Conformal Risk Control (operational chronological approximation)\n',
    '# ---------------------------------------------------------------------------\n',
    '\n',
    '\n',
    'def _risk_losses(frame: pd.DataFrame, direction: str) -> pd.DataFrame:\n',
    '    predicted = _predicted_direction_series(frame)\n',
    '    correct = _column_numeric(frame, ("direction_correct",))\n',
    '    tp = _column_numeric(frame, ("tp_touched",))\n',
    '    sl = _column_numeric(frame, ("sl_touched",))\n',
    '    confidence = _probability_for_direction(frame, direction, calibrated=True)\n',
    '    non_wait = predicted.isin(["BUY", "SELL"]).astype(float)\n',
    '    false_entry = ((non_wait == 1) & (correct.fillna(0) <= 0)).astype(float)\n',
    '    sl_before_tp = ((sl.fillna(0) > 0) & (tp.fillna(0) <= 0)).astype(float)\n',
    '    incorrect_high = ((confidence.fillna(0) >= 0.70) & (correct.fillna(0) <= 0)).astype(float)\n',
    '    unsafe_non_wait = np.maximum.reduce([\n',
    '        false_entry.to_numpy(dtype=float),\n',
    '        sl_before_tp.to_numpy(dtype=float),\n',
    '        incorrect_high.to_numpy(dtype=float),\n',
    '    ])\n',
    '    return pd.DataFrame({\n',
    '        "confidence": confidence.fillna(0.0).clip(0, 1),\n',
    '        "false_entry": false_entry,\n',
    '        "sl_before_tp": sl_before_tp,\n',
    '        "incorrect_high_confidence": incorrect_high,\n',
    '        "unsafe_non_wait": unsafe_non_wait,\n',
    '    }, index=frame.index)\n',
    '\n',
    '\n',
    'def _condition_masks(frame: pd.DataFrame, identity: Mapping[str, Any]) -> Sequence[Tuple[str, pd.Series, int]]:\n',
    '    predicted = _predicted_direction_series(frame)\n',
    '    horizon = _column_numeric(frame, ("horizon", "horizon_hours"))\n',
    '    origin = pd.to_datetime(frame.get("__origin", pd.Series(pd.NaT, index=frame.index)), utc=True, errors="coerce")\n',
    '    sessions = origin.map(_session)\n',
    '    regime = _column_text(frame, ("h1_regime", "regime", "major_regime"))\n',
    '    event = _column_text(frame, ("event_risk_status", "event_importance"))\n',
    '    direction = str(identity.get("direction") or "WAIT")\n',
    '    selected = int(identity.get("horizon") or 3)\n',
    '    session = str(identity.get("session") or "UNKNOWN")\n',
    '    h1_regime = str(identity.get("h1_regime") or "UNKNOWN")\n',
    '    event_risk = str(identity.get("event_risk") or "UNKNOWN")\n',
    '    all_mask = pd.Series(True, index=frame.index)\n',
    '    return (\n',
    '        ("direction+horizon+session+regime+event", (predicted == direction) & (horizon == selected) & (sessions == session) & (regime == h1_regime) & (event == event_risk), 40),\n',
    '        ("direction+horizon+session+regime", (predicted == direction) & (horizon == selected) & (sessions == session) & (regime == h1_regime), 35),\n',
    '        ("direction+horizon+session", (predicted == direction) & (horizon == selected) & (sessions == session), 30),\n',
    '        ("direction+horizon", (predicted == direction) & (horizon == selected), 25),\n',
    '        ("horizon", horizon == selected, 25),\n',
    '        ("global", all_mask, 25),\n',
    '    )\n',
    '\n',
    '\n',
    'def conformal_risk_control(\n',
    '    settled: pd.DataFrame,\n',
    '    identity: Mapping[str, Any],\n',
    '    *,\n',
    '    target_risk: Optional[float] = None,\n',
    '    alpha: float = 0.05,\n',
    ') -> Dict[str, Any]:\n',
    '    target = float(target_risk if target_risk is not None else (0.15 if str(identity.get("event_risk", "")).upper() in {"HIGH", "CRITICAL"} or bool(identity.get("conflict")) else 0.20))\n',
    '    if settled.empty or identity.get("direction") not in {"BUY", "SELL"}:\n',
    '        return {\n',
    '            "status": "INSUFFICIENT_EVIDENCE", "validity_status": "INVALID",\n',
    '            "target_risk": target, "observed_risk": None, "risk_upper_bound": None,\n',
    '            "threshold": None, "condition": None, "sample_count": 0,\n',
    '            "losses": {}, "reason": "No settled non-WAIT directional evidence.",\n',
    '        }\n',
    '    chosen = None\n',
    '    for level, mask, minimum in _condition_masks(settled, identity):\n',
    '        subset = settled.loc[mask]\n',
    '        if len(subset) >= minimum:\n',
    '            chosen = (level, subset.tail(1200), minimum)\n',
    '            break\n',
    '    if chosen is None:\n',
    '        return {\n',
    '            "status": "INSUFFICIENT_EVIDENCE", "validity_status": "INVALID",\n',
    '            "target_risk": target, "observed_risk": None, "risk_upper_bound": None,\n',
    '            "threshold": None, "condition": "no_fallback_met", "sample_count": int(len(settled)),\n',
    '            "losses": {}, "reason": "Hierarchical calibration groups did not meet minimum settled support.",\n',
    '        }\n',
    '    level, subset, minimum = chosen\n',
    '    losses = _risk_losses(subset, str(identity["direction"]))\n',
    '    n = int(len(losses))\n',
    '    correction = math.sqrt(math.log(1.0 / max(1e-9, alpha)) / (2.0 * max(1, n)))\n',
    '    thresholds = np.round(np.linspace(0.50, 1.00, 51), 2)\n',
    '    curve = []\n',
]
