"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""2026-06-12 final cleanup patch.\n',
    '\n',
    'Goals:\n',
    '- Move Research into Lunch/Home inner tabs.\n',
    '- Replace duplicated Data Visualization add-on fields with one merged run-gated field.\n',
    '- Add a synced PowerBI projection overlay using accuracy-adjusted KNN/Greedy/NLP/Structure outputs.\n',
    '- Keep original functions available and copy exports updated.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    '\n',
    'def install(ns: dict) -> None:\n',
    '    import json\n',
    '    import math\n',
    '    import time\n',
    '    from typing import Any, Dict, List\n',
    '\n',
    '    import numpy as np\n',
    '    import pandas as pd\n',
    '    import plotly.graph_objects as go\n',
    '    import streamlit as st\n',
    '\n',
    '    from core.research_causality_20260618 import causal_binary_target, causal_news_asof, purged_time_order_split\n',
    '\n',
    '    UNIQUE = "20260612_final_sync2"\n',
    '\n',
    '    def _num(v: Any, default: float = 0.0) -> float:\n',
    '        try:\n',
    '            x = float(v)\n',
    '            return x if math.isfinite(x) else float(default)\n',
    '        except Exception:\n',
    '            return float(default)\n',
    '\n',
    '    def _safe(obj: Any, rows: int = 120) -> Any:\n',
    '        try:\n',
    '            if isinstance(obj, pd.DataFrame):\n',
    '                return obj.head(rows).to_dict("records")\n',
    '            if isinstance(obj, pd.Series):\n',
    '                return obj.to_dict()\n',
    '            if isinstance(obj, pd.Timestamp):\n',
    '                return str(obj)\n',
    '            if isinstance(obj, dict):\n',
    '                return {str(k): _safe(v, rows) for k, v in obj.items()}\n',
    '            if isinstance(obj, (list, tuple)):\n',
    '                return [_safe(x, rows) for x in list(obj)[:rows]]\n',
    '            return obj\n',
    '        except Exception:\n',
    '            return str(obj)\n',
    '\n',
    '    def _json(obj: Any, rows: int = 120) -> str:\n',
    '        return json.dumps(_safe(obj, rows), indent=2, ensure_ascii=False, default=str)\n',
    '\n',
    '    def _copy_button(label: str, text: str, key: str) -> None:\n',
    '        try:\n',
    '            from streamlit_copy_button import copy_button\n',
    '            copy_button(text, label, key=key)\n',
    '        except Exception:\n',
    '            try:\n',
    '                from core.pro_terminal_uiux import render_mobile_copy_button\n',
    '                render_mobile_copy_button(label, text, key)\n',
    '            except Exception:\n',
    '                st.text_area(label, text, height=220, key=key + "_fallback")\n',
    '\n',
    '    def _mobile_css() -> None:\n',
    '        big = bool(st.session_state.get("phone_mode", False))\n',
    '        mult = 1.12 if big else 1.0\n',
    '        st.markdown(f"""\n',
    '        <style>\n',
    '        :root{{--new7-scale:{mult};}}\n',
    '        .block-container{{max-width:1200px;padding-top:.55rem!important}}\n',
    '        div[data-testid="stMetric"]{{border-radius:{22*mult:.0f}px!important;padding:{12*mult:.0f}px {14*mult:.0f}px!important;border:1px solid rgba(14,165,233,.22)!important;box-shadow:0 14px 36px rgba(15,23,42,.09)!important;background:linear-gradient(145deg,rgba(255,255,255,.88),rgba(224,242,254,.58))!important}}\n',
    '        .stButton>button{{border-radius:999px!important;min-height:{48*mult:.0f}px!important;font-size:{15*mult:.0f}px!important;font-weight:900!important;box-shadow:0 12px 24px rgba(14,165,233,.17)!important}}\n',
    '        .stTabs [data-baseweb="tab"]{{font-size:{14*mult:.0f}px!important;font-weight:900!important;padding:{10*mult:.0f}px {14*mult:.0f}px!important;border-radius:999px!important}}\n',
    '        textarea,input,.stSelectbox,.stSlider{{font-size:{15*mult:.0f}px!important}}\n',
    '        div[data-testid="stExpander"]{{border-radius:22px!important;border:1px solid rgba(14,165,233,.22)!important;box-shadow:0 14px 34px rgba(15,23,42,.07)!important;overflow:hidden!important}}\n',
    '        [data-baseweb="select"], [data-testid="stSlider"]{{background:rgba(255,255,255,.72)!important;border-radius:18px!important;padding:.2rem!important}}\n',
    '        .new7-pop-card{{animation:new7pop .28s ease-out both}}@keyframes new7pop{{from{{transform:translateY(7px);opacity:.72}}to{{transform:none;opacity:1}}}}\n',
    '        @media(max-width:780px){{\n',
    '          .block-container{{padding-left:.45rem!important;padding-right:.45rem!important}}\n',
    '          div[data-testid="column"]{{min-width:0!important}}\n',
    '          div[data-testid="stMetric"]{{margin:.20rem 0!important}}\n',
    '          [data-testid="stHorizontalBlock"]{{gap:.35rem!important}}\n',
    '          h1{{font-size:{26*mult:.0f}px!important}} h2{{font-size:{22*mult:.0f}px!important}} h3{{font-size:{18*mult:.0f}px!important}}\n',
    '          .stDataFrame{{font-size:{12*mult:.0f}px!important}}\n',
    '        }}\n',
    '        </style>\n',
    '        """, unsafe_allow_html=True)\n',
    '\n',
    '    def _dir(regime: Any) -> str:\n',
    '        s = str(regime).upper()\n',
    '        if "BEAR" in s:\n',
    '            return "SELL"\n',
    '        if "BULL" in s:\n',
    '            return "BUY"\n',
    '        return "WAIT"\n',
    '\n',
    '    def _master_direction() -> str:\n',
    '        canonical = st.session_state.get("canonical_decision_result_20260617", {})\n',
    '        if isinstance(canonical, dict):\n',
    '            value = canonical.get("full_metric_direction") or (canonical.get("final_decision") or {}).get("directional_market_view")\n',
    '            if value:\n',
    '                return _dir(value)\n',
    '        return _dir(_master_regime())\n',
    '\n',
    '    def _prep_ohlc(limit: int = 6000) -> pd.DataFrame:\n',
    '        raw = st.session_state.get("dv_pp_df")\n',
    '        if not isinstance(raw, pd.DataFrame) or raw.empty:\n',
    '            raw = st.session_state.get("last_df")\n',
    '        prep = ns.get("_dv_prepare_ohlc_v20260609")\n',
    '        if callable(prep):\n',
    '            try:\n',
    '                out = prep(raw, limit=int(limit))\n',
    '                if isinstance(out, pd.DataFrame) and not out.empty:\n',
    '                    return out.tail(int(limit)).reset_index(drop=True)\n',
    '            except Exception:\n',
    '                pass\n',
    '        if not isinstance(raw, pd.DataFrame) or raw.empty:\n',
    '            return pd.DataFrame()\n',
    '        d = raw.copy().tail(int(limit)).reset_index(drop=True)\n',
    '        low = {str(c).lower(): c for c in d.columns}\n',
    '        for src, dst in {"datetime": "time", "date": "time", "timestamp": "time", "o": "open", "h": "high", "l": "low", "c": "close"}.items():\n',
    '            if src in low and dst not in d.columns:\n',
    '                d = d.rename(columns={low[src]: dst})\n',
    '        if "time" not in d.columns:\n',
    '            return pd.DataFrame()\n',
    '        if "close" not in d.columns:\n',
    '            return pd.DataFrame()\n',
    '        for col in ["open", "high", "low", "close"]:\n',
    '            if col not in d.columns:\n',
    '                d[col] = d["close"]\n',
    '            d[col] = pd.to_numeric(d[col], errors="coerce")\n',
    '        d["time"] = pd.to_datetime(d["time"], errors="coerce")\n',
    '        return d.dropna(subset=["time", "close"]).sort_values("time").drop_duplicates("time", keep="last").reset_index(drop=True)\n',
    '\n',
    '    def _master_regime() -> str:\n',
    '        for key in ("dv_pp_regime_summary", "lunch_5layer_powerbi_result", "final_merged_intelligence_pack_20260612", "nylo_unified_home_sync_20260612"):\n',
    '            obj = st.session_state.get(key, {})\n',
    '            if isinstance(obj, dict):\n',
    '                cur = obj.get("current_regime") or obj.get("master_regime")\n',
    '                if not cur and isinstance(obj.get("summary"), dict):\n',
    '                    cur = obj["summary"].get("current_powerbi_regime")\n',
    '                if cur:\n',
    '                    return str(cur)\n',
    '        return "RANGE_NORMAL"\n',
    '\n',
    '    def _base_powerbi_run(rows: int, horizon: int, bt_lookback: int, min_days: int) -> Dict[str, Any]:\n',
    '        clean_f = ns.get("_clean_lunch_visual_df")\n',
    '        prep = ns.get("_dv_prepare_ohlc_v20260609")\n',
    '        clean = clean_f(limit=int(rows)) if callable(clean_f) else st.session_state.get("last_df", pd.DataFrame())\n',
    '        d = prep(clean, limit=int(rows)) if callable(prep) else _prep_ohlc(int(rows))\n',
    '        if not isinstance(d, pd.DataFrame) or len(d) < 120:\n',
    '            return {"ok": False, "message": "Need at least 120 clean OHLC candles."}\n',
    '        calc = ns.get("_five_layer_powerbi_calculate")\n',
    '        pred_f = ns.get("_dv_predict_future_candles_v20260609")\n',
    '        bt_f = ns.get("_dv_prediction_vs_actual_history_v20260609")\n',
    '        reg_f = ns.get("_dv_major_regime_detector_v20260609")\n',
    '        result = calc(d, horizon=int(horizon)) if callable(calc) else {}\n',
    '        pred = pred_f(d, horizon=int(horizon)) if callable(pred_f) else pd.DataFrame()\n',
    '        if callable(bt_f):\n',
    '            bt_hist, bt_sum = bt_f(d, lookback=int(bt_lookback), horizon=1)\n',
    '        else:\n',
    '            bt_hist, bt_sum = pd.DataFrame(), {}\n',
    '        if callable(reg_f):\n',
    '            reg, reg_hist = reg_f(d, min_days=float(min_days), lookback_days=240, horizon=int(horizon))\n',
    '        else:\n',
    '            reg, reg_hist = {}, pd.DataFrame()\n',
    '        st.session_state.update({\n',
    '            "lunch_bi_visual_ready": True,\n',
    '            "dv_pp_df": d,\n',
    '            "dv_pp_base_result": result,\n',
    '            "dv_pp_predicted": pred,\n',
    '            "dv_pp_bt_summary": bt_sum,\n',
    '            "dv_pp_bt_hist": bt_hist,\n',
    '            "dv_pp_regime_summary": reg,\n',
    '            "dv_pp_regime_hist": reg_hist,\n',
    '            "lunch_5layer_powerbi_result": result,\n',
    '            "lunch_5layer_powerbi_df": d,\n',
    '        })\n',
    '        return {"ok": True, "df": d, "result": result, "predicted": pred, "bt_hist": bt_hist, "bt_summary": bt_sum, "regime_summary": reg, "regime_history": reg_hist}\n',
    '\n',
    '    def _light_quant_structure(d: pd.DataFrame, regime: str) -> Dict[str, Any]:\n',
    '        if not isinstance(d, pd.DataFrame) or len(d) < 80:\n',
    '            return {"ok": False, "message": "Need more H1 candles."}\n',
    '        c = pd.to_numeric(d["close"], errors="coerce").dropna()\n',
    '        h = pd.to_numeric(d["high"], errors="coerce").reindex(c.index).fillna(c)\n',
    '        l = pd.to_numeric(d["low"], errors="coerce").reindex(c.index).fillna(c)\n',
    '        o = pd.to_numeric(d["open"], errors="coerce").reindex(c.index).fillna(c)\n',
    '        ret = c.pct_change().fillna(0)\n',
    '        rng = (h - l).abs().replace(0, np.nan).ffill().fillna(c.abs() * 0.00045)\n',
    '        atr12 = rng.rolling(12, min_periods=4).mean()\n',
    '        atr72 = rng.rolling(72, min_periods=20).median().replace(0, np.nan)\n',
    '        ratio = (atr12 / atr72).replace([np.inf, -np.inf], np.nan).fillna(1.0)\n',
    '        compression = max(0.0, min(100.0, (1.22 - float(ratio.iloc[-1])) / 0.72 * 100.0))\n',
    '        z = (ret.abs() / ret.rolling(72, min_periods=20).std().replace(0, np.nan)).replace([np.inf, -np.inf], np.nan).fillna(0)\n',
    '        shock = max(0.0, min(100.0, float(z.tail(8).max()) * 24.0))\n',
    '        noise = max(0.0, min(100.0, float(((rng - (c - o).abs()).clip(lower=0) / rng).tail(48).mean()) * 100.0))\n',
    '        denom = max(float(c.diff().abs().tail(24).sum()), 1e-9)\n',
    '        trend_quality = max(0.0, min(100.0, abs(float(c.iloc[-1] - c.iloc[-24])) / denom * 100.0))\n',
    '        md = _dir(regime)\n',
    '        score = max(0.0, min(100.0, (100 - noise) * .28 + trend_quality * .28 + (100 - shock) * .22 + (100 - abs(compression - 50)) * .22))\n',
    '        band = max(float(atr12.iloc[-1]), float(c.iloc[-1]) * .00035) * (1.0 + shock / 220.0)\n',
    '        sign = 1 if md == "BUY" else -1 if md == "SELL" else 0\n',
    '        next_price = float(c.iloc[-1]) + sign * band * (0.42 + score / 180.0)\n',
    '        return {\n',
    '            "ok": True,\n',
    '            "quant_structure_score": round(score, 1),\n',
    '            "master_regime": regime,\n',
    '            "master_direction": md,\n',
    '            "compression_expansion": {"Compression Score": round(compression, 1), "Expansion Probability": round(min(100.0, compression * .55 + shock * .35), 1), "Time In Compression": int((ratio.tail(72) < .82).sum()), "Expansion Risk": "HIGH" if compression > 72 else "MEDIUM" if compression > 45 else "LOW"},\n',
    '            "regime_vortex": {"Regime Stability": round(max(0.0, 100 - shock * .45 - noise * .22), 1), "Regime Rotation Speed": round(float(abs(ret.tail(24).mean() - ret.tail(96).mean())) * 100000, 2), "Regime Conflict": "LOW", "Regime Strength": round(trend_quality, 1)},\n',
    '            "cycle_drift": {"Dominant Cycle Length": "H1 lightweight rhythm", "Cycle Drift Score": round(float(abs(ret.tail(24).mean() - ret.tail(96).mean())) * 100000, 2), "Cycle Stability": round(max(0.0, 100.0 - shock * .5), 1), "Cycle Change Warning": "WATCH" if shock > 55 else "NORMAL"},\n',
    '            "volatility_waterfall": {"H1 Volatility Energy": round(float(ret.tail(24).std()) * 10000, 3), "H4 Volatility Energy": round(float(ret.rolling(4).sum().tail(42).std()) * 10000, 3), "D1 Volatility Energy": round(float(ret.rolling(24).sum().tail(30).std()) * 10000, 3), "Volatility Drift": round(float((ratio.tail(6).mean() - ratio.tail(72).median()) * 100), 2)},\n',
    '            "broadband_shock_signature": {"Shock Probability": round(shock, 1), "Shock Magnitude": round(abs(float(ret.iloc[-1])) * 10000, 3), "Shock Persistence": int((z.tail(12) > 2).sum()), "Shock Recovery": round(max(0.0, 100.0 - shock * .75), 1)},\n',
    '            "aftershock_engine": {"Recent Shock": "YES" if bool((z.tail(12) > 2.4).any()) else "NO", "Aftershock Risk": round(shock, 1), "Stabilization Score": round(max(0.0, 100.0 - shock * .75), 1)},\n',
    '            "microstructure_reality": {"Noise Level": round(noise, 1), "Trend Quality": round(trend_quality, 1), "Directional Efficiency": round(trend_quality, 1)},\n',
    '            "sync_outputs": {"Next 1H Reasonable Direction": md if score >= 42 else "WAIT", "Next 1H Reasonable Price": round(next_price, 5), "Next 1H Lower Band": round(next_price - band, 5), "Next 1H Upper Band": round(next_price + band, 5), "Next Regime Update": "Continuation likely" if score >= 62 and shock < 55 else "Rotation watch"},\n',
    '        }\n',
    '\n',
    '    def _news_summary_from_existing(master_dir: str) -> Dict[str, Any]:\n',
    '        # Prefer existing News/NLP pack so no API/RSS call is made here.\n',
    '        for key in ("final_merged_intelligence_pack_20260612", "dv_news_nlp_pack_20260612", "research_pack_20260612"):\n',
    '            obj = st.session_state.get(key, {})\n',
    '            if not isinstance(obj, dict):\n',
    '                continue\n',
    '            nlp = obj.get("news_nlp") or obj.get("nlp") or {}\n',
    '            summ = nlp.get("summary", {}) if isinstance(nlp, dict) else {}\n',
    '            if summ:\n',
    '                return {"summary": summ, "table": nlp.get("table", pd.DataFrame()) if isinstance(nlp, dict) else pd.DataFrame(), "source": obj.get("source", "cached")}\n',
    '        return {"summary": {"news_direction": "WAIT", "news_sync": "NEUTRAL", "articles_used": 0, "Master Direction": master_dir, "message": "Run News/NLP if you want external confirmation."}, "table": pd.DataFrame(), "source": "cached-none"}\n',
    '\n',
    '    def _accuracy_adjusted_projection(d: pd.DataFrame, q: Dict[str, Any], news: Dict[str, Any], horizon: int = 24) -> pd.DataFrame:\n',
    '        if not isinstance(d, pd.DataFrame) or d.empty:\n',
    '            return pd.DataFrame()\n',
    '        c = pd.to_numeric(d["close"], errors="coerce").dropna()\n',
    '        h = pd.to_numeric(d["high"], errors="coerce").reindex(c.index).fillna(c)\n',
    '        l = pd.to_numeric(d["low"], errors="coerce").reindex(c.index).fillna(c)\n',
    '        last = float(c.iloc[-1])\n',
    '        last_time = pd.Timestamp(d["time"].iloc[-1]) if "time" in d.columns else pd.Timestamp.now().floor("h")\n',
    '        atr = max(float((h - l).abs().tail(14).mean()), last * 0.00035)\n',
    '        md = q.get("master_direction", _dir(_master_regime())) if isinstance(q, dict) else _dir(_master_regime())\n',
    '        sign = 1 if md == "BUY" else -1 if md == "SELL" else 0\n',
    '        score = _num(q.get("quant_structure_score", 55) if isinstance(q, dict) else 55, 55) / 100.0\n',
    '        after = _num(q.get("aftershock_engine", {}).get("Aftershock Risk", 0) if isinstance(q, dict) else 0, 0) / 100.0\n',
    '        nsumm = news.get("summary", {}) if isinstance(news, dict) else {}\n',
    '        sync = str(nsumm.get("news_sync") or nsumm.get("News Sync") or "NEUTRAL").upper()\n',
    '        nudge = 0.10 if sync == "CONFIRM" else -0.08 if sync == "CONFLICT" else 0.0\n',
    '        bt = st.session_state.get("dv_pp_bt_summary", {})\n',
    '        err_pct = _num(bt.get("avg_abs_close_error_pct", 0) if isinstance(bt, dict) else 0, 0)\n',
    '        acc = _num(bt.get("direction_accuracy_pct", 50) if isinstance(bt, dict) else 50, 50) / 100.0\n',
    '        rows: List[Dict[str, Any]] = []\n',
    '        for step in range(1, int(horizon) + 1):\n',
    '            drift = sign * atr * math.sqrt(step) * (0.30 + score * 0.58 + max(0, acc - .50) * .35 + nudge)\n',
    '            price = last + drift\n',
    '            band = atr * math.sqrt(step) * (1.0 + after * .75 + min(.8, err_pct / 10.0))\n',
    '            rows.append({\n',
    '                "Priority Rank": step,\n',
    '                "time": last_time + pd.Timedelta(hours=step),\n',
    '                "Step": step,\n',
    '                "Master Direction": md,\n',
    '                "Reasonable Direction": md if sign else "WAIT",\n',
    '                "Accuracy Adjusted Price": round(price, 5),\n',
    '                "Upper Band": round(price + band, 5),\n',
    '                "Lower Band": round(price - band, 5),\n',
    '                "Confidence %": round(max(5, min(95, 52 + score * 32 + acc * 10 - after * 18 - min(err_pct, 2) * 4)), 1),\n',
    '                "News Sync": sync,\n',
    '                "BT Error %": round(err_pct, 5),\n',
    '            })\n',
    '        return pd.DataFrame(rows)\n',
    '\n',
    '    def _research_rf_summary(d: pd.DataFrame) -> Dict[str, Any]:\n',
    '        try:\n',
    '            # Reuse already-run research first, avoiding a second calculation.\n',
    '            pack = st.session_state.get("research_pack_20260612", {})\n',
    '            if isinstance(pack, dict) and isinstance(pack.get("data_mining"), dict):\n',
    '                rf = pack["data_mining"].get("random_forest", {})\n',
    '                if isinstance(rf, dict) and rf:\n',
    '                    return rf\n',
    '            if not isinstance(d, pd.DataFrame) or len(d) < 160:\n',
    '                return {"status": "WAIT", "message": "Need 160+ candles"}\n',
    '            from sklearn.ensemble import RandomForestClassifier\n',
    '            from sklearn.metrics import accuracy_score\n',
    '            c = d["close"].astype(float)\n',
    '            f = pd.DataFrame({\n',
    '                "ret1": c.pct_change(),\n',
    '                "ret3": c.pct_change(3),\n',
    '                "ret6": c.pct_change(6),\n',
    '                "ma12_gap": c / c.rolling(12).mean() - 1,\n',
    '                "ma48_gap": c / c.rolling(48).mean() - 1,\n',
    '                "range_pct": (d["high"] - d["low"]).abs() / c.replace(0, np.nan),\n',
    '                "vol24": c.pct_change().rolling(24).std(),\n',
    '                "hour": pd.to_datetime(d["time"]).dt.hour,\n',
    '                "target_up": causal_binary_target(c),\n',
    '            })\n',
    '            cols = ["ret1", "ret3", "ret6", "ma12_gap", "ma48_gap", "range_pct", "vol24", "hour"]\n',
    '            f = f.dropna(subset=cols).tail(3500).reset_index(drop=True)\n',
    '            train, test = purged_time_order_split(\n',
    '                f, target_col="target_up", train_fraction=0.78, purge_rows=1, minimum_train=80\n',
    '            )\n',
    '            if train.empty or train["target_up"].nunique() < 2:\n',
    '                raise ValueError("Insufficient causal labeled rows for Random Forest")\n',
    '            model = RandomForestClassifier(n_estimators=80, max_depth=5, min_samples_leaf=8, random_state=42, n_jobs=1)\n',
    '            model.fit(train[cols], train["target_up"].astype(int))\n',
    '            pred = model.predict(test[cols]) if len(test) else []\n',
    '            acc = float(accuracy_score(test["target_up"].astype(int), pred)) if len(test) else 0.0\n',
    '            up = float(model.predict_proba(f[cols].tail(1))[0][1])\n',
    '            rf_dir = "BUY" if up >= .55 else "SELL" if up <= .45 else "WAIT"\n',
    '            master = _master_direction()\n',
    '            return {"status": "READY", "Random Forest Accuracy %": round(acc * 100, 2), "RF Next 1H Up Probability %": round(up * 100, 2), "RF Direction": rf_dir, "Master Direction": master, "RF Sync": "CONFIRM" if rf_dir == master and rf_dir != "WAIT" else "CONFLICT" if rf_dir in ("BUY", "SELL") and master in ("BUY", "SELL") and rf_dir != master else "NEUTRAL"}\n',
    '        except Exception as exc:\n',
    '            return {"status": "OPTIONAL", "message": str(exc)[:160]}\n',
    '\n',
    '    def _regime_nlp_history(d: pd.DataFrame, news_sync: str, master_dir: str) -> pd.DataFrame:\n',
    '        if not isinstance(d, pd.DataFrame) or d.empty:\n',
    '            return pd.DataFrame()\n',
    '        x = d.tail(25 * 24).copy()\n',
    '        x["hour"] = pd.to_datetime(x["time"]).dt.hour\n',
    '        x = x[(x["hour"] >= 1) & (x["hour"] <= 14)].copy().reset_index(drop=True)\n',
    '        if x.empty:\n',
    '            return pd.DataFrame()\n',
    '        c = x["close"].astype(float)\n',
    '        ma12 = c.rolling(12, min_periods=3).mean()\n',
    '        ma48 = c.rolling(48, min_periods=10).mean()\n',
    '        x["Regime Direction"] = np.where(ma12 > ma48, "BUY", np.where(ma12 < ma48, "SELL", "WAIT"))\n',
    '        news_table = st.session_state.get("nlp_ranked_news_df")\n',
    '        joined = causal_news_asof(x[["time"]], news_table if isinstance(news_table, pd.DataFrame) else pd.DataFrame())\n',
    '        sync_col = next((c for c in ("news_sync", "News Sync", "NLP Sync", "nlp_sync") if c in joined.columns), None)\n',
    '        x["NLP Sync"] = joined[sync_col].reindex(x.index).fillna("UNAVAILABLE").astype(str).str.upper() if sync_col else "UNAVAILABLE"\n',
    '        nlp_adjustment = np.select([x["NLP Sync"].eq("CONFIRM"), x["NLP Sync"].eq("CONFLICT")], [10, -12], default=0)\n',
    '        x["Greedy Score"] = np.where(x["Regime Direction"] == master_dir, 70, 42) + nlp_adjustment\n',
    '        x["Entry Opportunity"] = np.where((x["Regime Direction"] == master_dir) & (x["Greedy Score"] >= 64), "YES", "WATCH")\n',
    '        out = x.tail(160).sort_values(["Greedy Score", "time"], ascending=[False, False]).head(14).copy().reset_index(drop=True)\n',
    '        out["Priority Rank"] = out.index + 1\n',
    '        return out[["Priority Rank", "time", "hour", "Regime Direction", "NLP Sync", "Greedy Score", "Entry Opportunity"]]\n',
    '\n',
    '    def _priority_table(q: Dict[str, Any], news: Dict[str, Any], rf: Dict[str, Any], proj: pd.DataFrame, hist: pd.DataFrame) -> pd.DataFrame:\n',
    '        md = q.get("master_direction", _dir(_master_regime())) if isinstance(q, dict) else _dir(_master_regime())\n',
    '        nsumm = news.get("summary", {}) if isinstance(news, dict) else {}\n',
    '        nsync = str(nsumm.get("news_sync") or nsumm.get("News Sync") or "NEUTRAL").upper()\n',
    '        qscore = _num(q.get("quant_structure_score", 50) if isinstance(q, dict) else 50, 50)\n',
    '        conf = _num(proj.iloc[0].get("Confidence %"), 50) if isinstance(proj, pd.DataFrame) and not proj.empty else 50\n',
    '        rows = [\n',
    '            {"Priority Rank": 1, "Source": "Unified PowerBI master regime", "Greedy Score": 95 if md in ("BUY", "SELL") else 50, "Direction": md, "Decision": f"{md} master" if md in ("BUY", "SELL") else "WAIT", "Reason": _master_regime()},\n',
    '            {"Priority Rank": 2, "Source": "Accuracy-adjusted projection", "Greedy Score": round(conf, 1), "Direction": md, "Decision": "USE" if conf >= 58 else "WATCH", "Reason": "Projection uses regime + error + structure + news confirmation"},\n',
    '            {"Priority Rank": 3, "Source": "News/NLP conflict filter", "Greedy Score": 88 if nsync == "CONFIRM" else 55 if nsync in ("NEUTRAL", "LOW PRIORITY") else 25, "Direction": nsumm.get("news_direction") or nsumm.get("News Direction") or "WAIT", "Decision": nsync, "Reason": "News never overrides PowerBI"},\n',
    '            {"Priority Rank": 4, "Source": "Quant Structure", "Greedy Score": round(qscore, 1), "Direction": md, "Decision": "CONFIRM" if qscore >= 62 else "WATCH", "Reason": "Compression/expansion + shock + microstructure"},\n',
    '            {"Priority Rank": 5, "Source": "Random Forest research", "Greedy Score": _num(rf.get("Random Forest Accuracy %", 0), 0), "Direction": rf.get("RF Direction", "WAIT"), "Decision": rf.get("RF Sync", "NEUTRAL"), "Reason": "Research only; not master direction"},\n',
    '        ]\n',
    '        if isinstance(hist, pd.DataFrame) and not hist.empty:\n',
    '            for _, r in hist.head(9).iterrows():\n',
    '                rows.append({"Priority Rank": len(rows) + 1, "Source": f"Regime/NLP History H{int(r.get(\'hour\', 0)):02d}", "Greedy Score": round(_num(r.get("Greedy Score")), 1), "Direction": r.get("Regime Direction", "WAIT"), "Decision": r.get("Entry Opportunity", "WATCH"), "Reason": f"NLP {r.get(\'NLP Sync\',\'NEUTRAL\')} | {r.get(\'time\',\'\')}"})\n',
    '        return pd.DataFrame(rows).sort_values("Priority Rank", ascending=True).head(14).reset_index(drop=True)\n',
    '\n',
    '    def _build_combined_pack(horizon: int = 24) -> Dict[str, Any]:\n',
    '        d = _prep_ohlc(6000)\n',
    '        regime = _master_regime()\n',
    '        master_dir = _master_direction()\n',
    '        q = _light_quant_structure(d, regime)\n',
    '        news = _news_summary_from_existing(master_dir)\n',
    '        proj = _accuracy_adjusted_projection(d, q if isinstance(q, dict) else {}, news, horizon=int(horizon))\n',
    '        rf = _research_rf_summary(d)\n',
    '        nsync = str((news.get("summary", {}) if isinstance(news, dict) else {}).get("news_sync") or "NEUTRAL").upper()\n',
    '        hist = _regime_nlp_history(d, nsync, master_dir)\n',
    '        pr = _priority_table(q if isinstance(q, dict) else {}, news, rf, proj, hist)\n',
    '        bt_sum = st.session_state.get("dv_pp_bt_summary", {})\n',
    '        pack = {\n',
    '            "export_type": "FINAL_SYNCED_POWERBI_RESEARCH_MERGE_20260612",\n',
    '            "built_at": str(pd.Timestamp.now()),\n',
    '            "symbol": "EURUSD",\n',
    '            "timeframe": "H1",\n',
    '            "master_regime": regime,\n',
    '            "master_direction": master_dir,\n',
    '            "data_mining_random_forest": rf,\n',
    '            "news_nlp": news,\n',
    '            "quant_structure": q,\n',
    '            "actual_vs_error_summary": bt_sum,\n',
    '            "accuracy_adjusted_projection": proj,\n',
    '            "regime_prediction_history_with_nlp": hist,\n',
    '            "priority_1_to_14": pr,\n',
    '            "market_story": f"PowerBI master regime is {regime}; master direction is {master_dir}. NLP is {nsync}; Quant Structure score is {q.get(\'quant_structure_score\',\'-\') if isinstance(q,dict) else \'-\'}; RF is {rf.get(\'RF Sync\',\'NEUTRAL\')}. Priority table is sorted ascending 1→14.",\n',
    '        }\n',
    '        st.session_state["final_synced_research_merge_pack_20260612"] = pack\n',
    '        st.session_state["final_synced_research_merge_export_20260612"] = _json(pack, 180)\n',
    '        st.session_state["final_merged_intelligence_pack_20260612"] = pack\n',
    '        st.session_state["final_merged_intelligence_export_20260612"] = st.session_state["final_synced_research_merge_export_20260612"]\n',
    '        st.session_state["lunch_visualization_export"] = str(st.session_state.get("lunch_visualization_export", "")) + "\\n\\n" + st.session_state["final_synced_research_merge_export_20260612"]\n',
    '        return pack\n',
    '\n',
    '    def _visual_spline_projection_20260614(proj: pd.DataFrame) -> pd.DataFrame:\n',
    '        """Display-only smoothing for the red synced path.\n',
    '\n',
    '        Does not change prediction tables or model outputs. It interpolates\n',
    '        between existing projected points so the visual red line is less\n',
    '        straight and easier to read against the older yellow path.\n',
    '        """\n',
    '        try:\n',
    '            if not isinstance(proj, pd.DataFrame) or proj.empty or "time" not in proj.columns or "Accuracy Adjusted Price" not in proj.columns:\n',
    '                return pd.DataFrame()\n',
    '            p = proj[["time", "Accuracy Adjusted Price"]].copy().dropna()\n',
    '            p["time"] = pd.to_datetime(p["time"], errors="coerce")\n',
    '            p["Accuracy Adjusted Price"] = pd.to_numeric(p["Accuracy Adjusted Price"], errors="coerce")\n',
    '            p = p.dropna().sort_values("time")\n',
    '            if len(p) < 2:\n',
    '                return p\n',
    '            dense_rows = []\n',
    '            for i in range(len(p) - 1):\n',
    '                t0, t1 = p["time"].iloc[i], p["time"].iloc[i + 1]\n',
    '                y0, y1 = float(p["Accuracy Adjusted Price"].iloc[i]), float(p["Accuracy Adjusted Price"].iloc[i + 1])\n',
    '                for j in range(4):\n',
    '                    u = j / 4.0\n',
    '                    smooth = u * u * (3 - 2 * u)\n',
    '                    dense_rows.append({"time": t0 + (t1 - t0) * u, "Accuracy Adjusted Price": y0 + (y1 - y0) * smooth})\n',
    '            dense_rows.append({"time": p["time"].iloc[-1], "Accuracy Adjusted Price": float(p["Accuracy Adjusted Price"].iloc[-1])})\n',
    '            return pd.DataFrame(dense_rows)\n',
    '        except Exception:\n',
    '            return proj\n',
    '\n',
    '    def _chart_powerbi_synced(d: pd.DataFrame, base_pred: pd.DataFrame, synced_proj: pd.DataFrame, title: str) -> None:\n',
    '        if not isinstance(d, pd.DataFrame) or d.empty:\n',
    '            st.info("No clean EURUSD H1 data for chart.")\n',
    '            return\n',
]
