"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        pred_dir = _direction_from_prices(last_close, forecast_close)\n',
    '    regime_dir = _direction_from_regime(regime)\n',
    '    decision = _find_value(flat, ["final_decision", "master_decision", "decision", "best_current_opportunity"], "-")\n',
    '    entry = _safe_num(_find_value(flat, ["entry_score", "entry strength", "entry /10", "entry pressure"], None))\n',
    '    hold = _safe_num(_find_value(flat, ["hold_score", "hold safety", "hold /10"], None))\n',
    '    tp = _safe_num(_find_value(flat, ["tp_score", "tp quality", "tp /10"], None))\n',
    '    exit_risk = _safe_num(_find_value(flat, ["exit_risk", "exit risk /10", "risk_score"], None))\n',
    '    forecast_conf = _safe_num(_find_value(flat, ["forecast_confidence", "forecast confidence %", "confidence_pct"], None))\n',
    '    market_quality = _safe_num(_find_value(flat, ["market_quality", "market_quality_score", "quality_score"], None))\n',
    '    return {\n',
    '        "symbol": _find_value(flat, ["symbol", "ticker"], "EURUSD"),\n',
    '        "timeframe": _find_value(flat, ["timeframe", "tf"], "H1"),\n',
    '        "last_close": last_close,\n',
    '        "forecast_close": forecast_close,\n',
    '        "prediction_direction": pred_dir,\n',
    '        "regime": str(regime or "-"),\n',
    '        "regime_direction": regime_dir,\n',
    '        "decision": str(decision or "-"),\n',
    '        "entry_score": entry,\n',
    '        "hold_score": hold,\n',
    '        "tp_score": tp,\n',
    '        "exit_risk": exit_risk,\n',
    '        "forecast_confidence": forecast_conf,\n',
    '        "market_quality": market_quality,\n',
    '    }\n',
    '\n',
    '\n',
    'def _regime_alpha_delta(flat: Dict[str, Any], data: Dict[str, Any], feedback: Dict[str, Any], quality: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    ohlc = data.get("ohlc")\n',
    '    hist = data.get("regime_hist")\n',
    '    current_regime = str(_find_value(flat, ["current_regime", "regime", "major_regime"], "-") or "-")\n',
    '    previous_regime = "-"\n',
    '    try:\n',
    '        if _is_df(hist):\n',
    '            rcol = _find_col(hist, ["regime", "current_regime", "major_regime", "label"])\n',
    '            if rcol:\n',
    '                vals = [str(x) for x in hist[rcol].dropna().astype(str).tolist() if str(x).strip()]\n',
    '                if vals:\n',
    '                    current_regime = vals[-1]\n',
    '                    # Find last different regime as previous.\n',
    '                    for val in reversed(vals[:-1]):\n',
    '                        if val != current_regime:\n',
    '                            previous_regime = val\n',
    '                            break\n',
    '    except Exception:\n',
    '        pass\n',
    '    alpha_now = 50.0\n',
    '    alpha_prev = 50.0\n',
    '    divergence = 0.0\n',
    '    ratio = 1.0\n',
    '    try:\n',
    '        c = _series_num(ohlc, ["close", "c"]).dropna()\n',
    '        h = _series_num(ohlc, ["high", "h"]).reindex(c.index).fillna(c)\n',
    '        l = _series_num(ohlc, ["low", "l"]).reindex(c.index).fillna(c)\n',
    '        if len(c) >= 12:\n',
    '            ret_now = float((c.iloc[-1] - c.iloc[-6]) / max(abs(c.iloc[-6]), 1e-12) * 100.0)\n',
    '            ret_prev = float((c.iloc[-7] - c.iloc[-12]) / max(abs(c.iloc[-12]), 1e-12) * 100.0) if len(c) >= 18 else 0.0\n',
    '            rng = ((h - l).abs() / c.replace(0, np.nan).abs() * 100.0).tail(24).mean()\n',
    '            vol_adj = max(float(rng or 0.01), 0.01)\n',
    '            alpha_now = _clip(50 + (ret_now / vol_adj) * 12.0 + (_clip(feedback.get("direction_accuracy_pct"), 0, 100, 50) - 50) * 0.28 + (quality.get("score", 50) - 50) * 0.18, 0, 100, 50)\n',
    '            alpha_prev = _clip(50 + (ret_prev / vol_adj) * 12.0, 0, 100, 50)\n',
    '            divergence = alpha_now - alpha_prev\n',
    '            ratio = alpha_now / max(alpha_prev, 1.0)\n',
    '    except Exception:\n',
    '        pass\n',
    '    delta = alpha_now - alpha_prev\n',
    '    valid = bool(quality.get("ok") and abs(delta) >= 3.0 and _clip(feedback.get("reliability_cap_from_feedback"), 0, 100, 50) >= 45)\n',
    '    return {\n',
    '        "current_regime": current_regime,\n',
    '        "previous_regime": previous_regime,\n',
    '        "regime_alpha_now": round(alpha_now, 2),\n',
    '        "regime_alpha_previous": round(alpha_prev, 2),\n',
    '        "regime_delta": round(delta, 2),\n',
    '        "regime_alpha_ratio": round(ratio, 4),\n',
    '        "regime_divergence_mean": round(divergence, 2),\n',
    '        "validation_status": "VALID" if valid else "WATCH / NEED MORE CONFIRMATION",\n',
    '        "rule": "Alpha = current regime strength after feedback + data-quality calibration; Delta = current alpha - previous alpha.",\n',
    '    }\n',
    '\n',
    '\n',
    '\n',
    'def _false_reversal_risk(flat: Dict[str, Any], current: Dict[str, Any], reliability: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    """Score false-reversal exposure from existing causal decision evidence only."""\n',
    '    strength = _safe_num(_find_value(flat, ["reversal_strength", "reversal strength", "reverse strength"], 0.0), 0.0) or 0.0\n',
    '    active = _safe_num(_find_value(flat, ["active_10_count", "active 10 count", "active reversal count"], 0.0), 0.0) or 0.0\n',
    '    probability = _safe_num(_find_value(flat, ["probability_%", "probability %", "reversal probability", "probability_pct"], 0.0), 0.0) or 0.0\n',
    '    move_ratio = _safe_num(_find_value(flat, ["move_ratio_now_prev", "move ratio now prev", "move ratio"], 1.0), 1.0) or 1.0\n',
    '    derivative = _safe_num(_find_value(flat, ["direction_derivative", "direction derivative"], 0.0), 0.0) or 0.0\n',
    '    strength_pct = _clip(strength * 10.0 if abs(strength) <= 10 else strength, 0, 100, 0)\n',
    '    active_pct = _clip(active * 10.0, 0, 100, 0)\n',
    '    probability_pct = _clip(probability, 0, 100, 0)\n',
    '    momentum = _clip(max(0.0, abs(move_ratio) - 1.0) * 24.0 + abs(derivative) * 240.0, 0, 100, 0)\n',
    '    reversal_confirmation = strength_pct * 0.45 + active_pct * 0.35 + probability_pct * 0.20\n',
    '    weak_confirmation = 100.0 - reversal_confirmation\n',
    '    apparent_reversal = probability_pct * 0.60 + strength_pct * 0.40\n',
    '    regime = str(current.get("regime") or "").upper()\n',
    '    continuation_regime = 8.0 if any(x in regime for x in ("TREND", "EXPANSION", "BULL", "BEAR")) and "TRANSITION" not in regime else 0.0\n',
    '    reliability_score = _clip(reliability.get("score"), 0, 100, 50)\n',
    '    low_evidence_penalty = max(0.0, 55.0 - reliability_score) * 0.22\n',
    '    raw = momentum * 0.45 + weak_confirmation * 0.32 + apparent_reversal * 0.23 + continuation_regime + low_evidence_penalty\n',
    '    score = round(_clip(raw / 10.0, 0, 10, 0), 2)\n',
    '    label = "LOW" if score < 3 else "WATCH" if score < 5 else "CAUTION" if score < 7 else "HIGH"\n',
    '    reasons = []\n',
    '    reasons.append("Strong momentum continuation" if momentum >= 55 else "Continuation momentum is limited")\n',
    '    reasons.append("Weak reversal confirmation" if reversal_confirmation < 50 else "Reversal confirmation is present")\n',
    '    return {\n',
    '        "score": score, "label": label, "reason": " • ".join(reasons),\n',
    '        "inputs": {"reversal_strength": strength, "active_10_count": active, "probability_pct": probability_pct, "move_ratio_now_prev": move_ratio, "direction_derivative": derivative},\n',
    '        "calculation_source": "central shared existing reversal/regime evidence",\n',
    '    }\n',
    '\n',
    'def _calibrated_reliability(current: Dict[str, Any], feedback: Dict[str, Any], quality: Dict[str, Any], alpha_delta: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    entry = _clip((current.get("entry_score") or 0) * 10 if (current.get("entry_score") or 0) <= 10 else current.get("entry_score"), 0, 100, 50)\n',
    '    hold = _clip((current.get("hold_score") or 0) * 10 if (current.get("hold_score") or 0) <= 10 else current.get("hold_score"), 0, 100, 50)\n',
    '    tp = _clip((current.get("tp_score") or 0) * 10 if (current.get("tp_score") or 0) <= 10 else current.get("tp_score"), 0, 100, 50)\n',
    '    exit_risk = _clip((current.get("exit_risk") or 5) * 10 if (current.get("exit_risk") or 0) <= 10 else current.get("exit_risk"), 0, 100, 50)\n',
    '    forecast_conf = _clip(current.get("forecast_confidence"), 0, 100, 50)\n',
    '    market_quality = _clip(current.get("market_quality"), 0, 100, quality.get("score", 50))\n',
    '    dir_acc = _clip(feedback.get("direction_accuracy_pct"), 0, 100, 50)\n',
    '    fb_cap = _clip(feedback.get("reliability_cap_from_feedback"), 25, 100, 70)\n',
    '    data_q = _clip(quality.get("score"), 0, 100, 50)\n',
    '    alpha_valid = 72.0 if alpha_delta.get("validation_status") == "VALID" else 48.0\n',
    '    conflict_penalty = 0.0\n',
    '    if current.get("prediction_direction") in {"BUY", "SELL"} and current.get("regime_direction") in {"BUY", "SELL"} and current.get("prediction_direction") != current.get("regime_direction"):\n',
    '        conflict_penalty = 12.0\n',
    '    raw = (\n',
    '        data_q * 0.20\n',
    '        + dir_acc * 0.22\n',
    '        + fb_cap * 0.18\n',
    '        + forecast_conf * 0.12\n',
    '        + market_quality * 0.10\n',
    '        + (100.0 - exit_risk) * 0.08\n',
    '        + ((entry + hold + tp) / 3.0) * 0.06\n',
    '        + alpha_valid * 0.04\n',
    '        - conflict_penalty\n',
    '    )\n',
    '    score = _clip(raw, 0, 100, 50)\n',
    '    # A reliability score should never be higher than the feedback cap + a small buffer.\n',
    '    score = min(score, fb_cap + 8.0)\n',
    '    if not quality.get("ok"):\n',
    '        score = min(score, 55.0)\n',
    '    grade = "A" if score >= 82 else "B" if score >= 68 else "C" if score >= 52 else "D / Protect"\n',
    '    return {\n',
    '        "score": round(score, 2),\n',
    '        "grade": grade,\n',
    '        "data_quality_component": round(data_q, 2),\n',
    '        "direction_accuracy_component": round(dir_acc, 2),\n',
    '        "feedback_cap": round(fb_cap, 2),\n',
    '        "conflict_penalty": round(conflict_penalty, 2),\n',
    '        "calibration_rule": "Score is capped by prediction-vs-actual feedback and lowered by data quality or regime/prediction conflict.",\n',
    '    }\n',
    '\n',
    '\n',
    'def _priority_label(score: float) -> str:\n',
    '    if score >= 90:\n',
    '        return "A+ Best"\n',
    '    if score >= 80:\n',
    '        return "A Strong"\n',
    '    if score >= 70:\n',
    '        return "B+ Good"\n',
    '    if score >= 60:\n',
    '        return "B Watch"\n',
    '    if score >= 45:\n',
    '        return "C Weak"\n',
    '    return "Avoid"\n',
    '\n',
    '\n',
    'def _priority_rank(score: float) -> int:\n',
    '    return int(max(1, min(14, round(15 - _clip(score, 0, 100, 50) / 100.0 * 14))))\n',
    '\n',
    '\n',
    'def _build_hourly_priority(data: Dict[str, Any], current: Dict[str, Any], reliability: Dict[str, Any], feedback: Dict[str, Any]):\n',
    '    if pd is None:\n',
    '        return None\n',
    '    old = data.get("priority")\n',
    '    rows: List[Dict[str, Any]] = []\n',
    '    base_rel = _clip(reliability.get("score"), 0, 100, 55)\n',
    '    fb_penalty = _clip(feedback.get("error_penalty"), 0, 60, 10)\n',
    '    if _is_df(old):\n',
    '        work = old.copy().tail(48).reset_index(drop=True)\n',
    '        score_col = _find_col(work, ["Greedy Score", "KNN Priority Score", "Priority Score", "Reliability Score", "Score"])\n',
    '        hour_col = _find_col(work, ["hour", "Hour", "Time", "Datetime", "Timestamp", "Date"])\n',
    '        base_scores = _series_num(work, [score_col] if score_col else ["__none__"], base_rel)\n',
    '        for i, (_, row) in enumerate(work.iterrows()):\n',
    '            hour = "-"\n',
    '            if hour_col:\n',
    '                try:\n',
    '                    t = pd.to_datetime(row.get(hour_col), errors="coerce")\n',
    '                    hour = int(t.hour) if pd.notna(t) else str(row.get(hour_col))\n',
    '                except Exception:\n',
    '                    try:\n',
    '                        hour = int(float(row.get(hour_col))) % 24\n',
    '                    except Exception:\n',
    '                        hour = str(row.get(hour_col))\n',
    '            dynamic = math.sin((i + 1) * 1.618) * 3.0\n',
    '            score = _clip(float(base_scores.iloc[i]) * 0.55 + base_rel * 0.35 + (100 - fb_penalty) * 0.10 + dynamic, 0, 100, base_rel)\n',
    '            new_row = {str(k): row[k] for k in work.columns}\n',
    '            new_row.update({\n',
    '                "Shared Sync Score": round(score, 2),\n',
    '                "Priority Rank 1-14": _priority_rank(score),\n',
    '                "Priority Label": _priority_label(score),\n',
    '                "Calibration Reason": "Existing priority + reliability + prediction feedback + anti-constant hourly movement",\n',
    '                "Hour": hour,\n',
    '            })\n',
    '            rows.append(new_row)\n',
    '    else:\n',
    '        ohlc = data.get("ohlc")\n',
    '        if _is_df(ohlc):\n',
    '            c = _series_num(ohlc, ["close", "c"]).replace(0, np.nan)\n',
    '            h = _series_num(ohlc, ["high", "h"]).reindex(c.index).fillna(c)\n',
    '            l = _series_num(ohlc, ["low", "l"]).reindex(c.index).fillna(c)\n',
    '            tcol = _find_col(ohlc, ["time", "datetime", "timestamp", "date"])\n',
    '            ret = c.pct_change().fillna(0) * 100.0\n',
    '            rng = ((h - l).abs() / c.abs().replace(0, np.nan) * 100.0).fillna(0)\n',
    '            tail_idx = list(ohlc.tail(24).index)\n',
    '            for j, idx in enumerate(tail_idx):\n',
    '                try:\n',
    '                    hour: Any = j\n',
    '                    if tcol:\n',
    '                        ts = pd.to_datetime(ohlc.loc[idx, tcol], errors="coerce")\n',
    '                        if pd.notna(ts):\n',
    '                            hour = int(ts.hour)\n',
    '                    momentum = float(ret.loc[idx]) if idx in ret.index else 0.0\n',
    '                    vol = float(rng.loc[idx]) if idx in rng.index else 0.0\n',
    '                    directional_bonus = 5.0 if (momentum > 0 and current.get("prediction_direction") == "BUY") or (momentum < 0 and current.get("prediction_direction") == "SELL") else -2.0\n',
    '                    time_variation = math.sin((float(hour) + 1.0) / 24.0 * math.tau) * 4.5 if isinstance(hour, int) else math.sin(j + 1) * 3.0\n',
    '                    score = _clip(base_rel * 0.62 + (100 - min(vol * 80, 35)) * 0.18 + (100 - fb_penalty) * 0.12 + 50 * 0.08 + directional_bonus + time_variation, 0, 100, base_rel)\n',
    '                    rows.append({\n',
    '                        "Hour": hour,\n',
    '                        "Shared Sync Score": round(score, 2),\n',
    '                        "Priority Rank 1-14": _priority_rank(score),\n',
    '                        "Priority Label": _priority_label(score),\n',
    '                        "Momentum %": round(momentum, 5),\n',
    '                        "Range %": round(vol, 5),\n',
    '                        "Calibration Reason": "OHLC-derived hourly priority proxy using existing data only; no new prediction model",\n',
    '                    })\n',
    '                except Exception:\n',
    '                    continue\n',
    '    if not rows:\n',
    '        return pd.DataFrame()\n',
    '    df = pd.DataFrame(rows)\n',
    '    try:\n',
    '        df = df.sort_values(["Priority Rank 1-14", "Shared Sync Score"], ascending=[True, False]).reset_index(drop=True)\n',
    '    except Exception:\n',
    '        pass\n',
    '    return df\n',
    '\n',
    '\n',
    'def _ai_grounding(current: Dict[str, Any], reliability: Dict[str, Any], quality: Dict[str, Any], priority_df: Any) -> Dict[str, Any]:\n',
    '    best_priority = "-"\n',
    '    try:\n',
    '        if _is_df(priority_df):\n',
    '            top = priority_df.iloc[0]\n',
    '            best_priority = f"Rank {top.get(\'Priority Rank 1-14\', \'-\')}: {top.get(\'Priority Label\', \'-\')}"\n',
    '    except Exception:\n',
    '        pass\n',
    '    conflict = current.get("prediction_direction") in {"BUY", "SELL"} and current.get("regime_direction") in {"BUY", "SELL"} and current.get("prediction_direction") != current.get("regime_direction")\n',
    '    must_say = []\n',
    '    if not quality.get("ok"):\n',
    '        must_say.append("data quality is weak")\n',
    '    if conflict:\n',
    '        must_say.append("regime and PowerBI/prediction conflict")\n',
    '    rel_score = _clip(reliability.get("score"), 0, 100, 50)\n',
    '    if rel_score < 35:\n',
    '        must_say.append("reliability is critically low; NO TRADE/PROTECT is required")\n',
    '    elif rel_score < 45:\n',
    '        must_say.append("reliability is weak; require extra confirmation and reduced risk")\n',
    '    return {\n',
    '        "ai_must_not_override": ["Regime", "Priority", "Power BI / prediction", "Reliability", "Data Quality"],\n',
    '        "decision": current.get("decision", "-"),\n',
    '        "regime": current.get("regime", "-"),\n',
    '        "regime_direction": current.get("regime_direction", "WAIT"),\n',
    '        "prediction_direction": current.get("prediction_direction", "WAIT"),\n',
    '        "reliability_score": reliability.get("score", 0),\n',
    '        "data_quality_score": quality.get("score", 0),\n',
    '        "best_priority": best_priority,\n',
    '        "conflict": bool(conflict),\n',
    '        "must_say": must_say,\n',
    '    }\n',
    '\n',
    '\n',
    'def _signature_with_state(st: Any, data: Dict[str, Any]) -> str:\n',
    '    try:\n',
    '        parts = [data.get("source_signature", "")]\n',
    '        for key in ["symbol", "timeframe", "metric_run_calculate", "run_data_visualization_antd_20260615"]:\n',
    '            parts.append(str(st.session_state.get(key, "")))\n',
    '        return hashlib.md5("|".join(parts).encode("utf-8", errors="ignore")).hexdigest()[:16]\n',
    '    except Exception:\n',
    '        return str(time.time())\n',
    '\n',
    '\n',
    'def build_shared_calculation_result(st: Any = None, force: bool = False) -> Dict[str, Any]:\n',
    '    """Build/update one shared object. Normal reruns adapt the canonical run only."""\n',
    '    if st is None:\n',
    '        import streamlit as st  # type: ignore\n',
    '    if not force:\n',
    '        try:\n',
    '            from core.canonical_runtime_20260617 import get_canonical, build_shared_adapter\n',
    '            canonical = get_canonical(st.session_state)\n',
    '            if canonical:\n',
    '                old = st.session_state.get(SHARED_KEY)\n',
    '                if isinstance(old, dict) and old.get("run_id") == canonical.get("run_id") and old.get("calculation_generation") == canonical.get("calculation_generation"):\n',
    '                    return old\n',
    '                priority = st.session_state.get("canonical_priority_table_20260617")\n',
    '                adapter = build_shared_adapter(st.session_state, canonical, legacy_shared=old if isinstance(old, dict) else None, priority_table=priority)\n',
    '                st.session_state[SHARED_KEY] = adapter\n',
    '                st.session_state[LEGACY_SHARED_KEY] = adapter\n',
    '                return adapter\n',
    '        except Exception:\n',
    '            pass\n',
    '    phone_mode = bool(st.session_state.get("phone_mode", False))\n',
    '    data = _collect_core_data(st, phone_mode)\n',
    '    signature = _signature_with_state(st, data)\n',
    '    old = st.session_state.get(SHARED_KEY)\n',
    '    if isinstance(old, dict) and old.get("signature") == signature and not force:\n',
    '        return old\n',
    '\n',
    '    flat = _collect_flat_state(st)\n',
    '    quality = _data_quality(data.get("ohlc"))\n',
    '    feedback = _prediction_feedback(flat, data)\n',
    '    current = _extract_current_summary(flat, data)\n',
    '    alpha_delta = _regime_alpha_delta(flat, data, feedback, quality)\n',
    '    reliability = _calibrated_reliability(current, feedback, quality, alpha_delta)\n',
    '    # One system-wide policy prevents Lunch, PowerBI, Finder and AI from\n',
    '    # producing conflicting WAIT/NO TRADE results for the same shared data.\n',
    '    try:\n',
    '        from core.decision_policy_20260617 import (\n',
    '            DECISION_POLICY_TEXT, infer_direction_from_regime, reconcile_decision,\n',
    '        )\n',
    '        rel_score = _clip(reliability.get("score"), 0, 100, 50)\n',
    '        risk = _safe_num(current.get("exit_risk"), 5.0) or 5.0\n',
    '        risk_pct = risk * 10.0 if risk <= 10 else risk\n',
    '        data_quality_score = _clip(quality.get("score"), 0, 100, 50)\n',
    '        direction = current.get("regime_direction")\n',
    '        if direction not in {"BUY", "SELL"}:\n',
    '            direction = infer_direction_from_regime(current.get("regime"), data.get("ohlc"))\n',
    '        if direction not in {"BUY", "SELL"}:\n',
    '            direction = current.get("prediction_direction")\n',
    '        current["regime_direction"] = direction if direction in {"BUY", "SELL"} else "WAIT"\n',
    '        current["decision"] = reconcile_decision(\n',
    '            direction, current.get("decision"), rel_score, data_quality_score, risk_pct\n',
    '        )\n',
    '        current["decision_policy"] = DECISION_POLICY_TEXT\n',
    '    except Exception:\n',
    '        pass\n',
    '    false_reversal_risk = _false_reversal_risk(flat, current, reliability)\n',
    '    priority_df = _build_hourly_priority(data, current, reliability, feedback)\n',
    '    grounding = _ai_grounding(current, reliability, quality, priority_df)\n',
    '\n',
    '    # Map the original calculation/cache objects into one additive data contract.\n',
    '    # Existing keys remain untouched and renderers still call their original code.\n',
    '    powerbi_source: Dict[str, Any] = {}\n',
    '    for key in ("dv_pp_base_result", "lunch_5layer_powerbi_result", "lunch_prediction_export", "dv_pp_regime_summary"):\n',
    '        candidate = st.session_state.get(key)\n',
    '        if isinstance(candidate, dict) and candidate:\n',
    '            powerbi_source = dict(candidate)\n',
    '            break\n',
    '    powerbi_source.setdefault("available", bool(powerbi_source) or _is_df(data.get("predicted")))\n',
    '    powerbi_source.setdefault("last_close", current.get("last_close"))\n',
    '    powerbi_source.setdefault("forecast_close", current.get("forecast_close"))\n',
    '    powerbi_source.setdefault("direction", current.get("prediction_direction", "WAIT"))\n',
    '    powerbi_source.setdefault("confidence", current.get("forecast_confidence"))\n',
    '    powerbi_source.setdefault("direction_accuracy", feedback.get("direction_accuracy_pct"))\n',
    '    powerbi_source.setdefault("avg_abs_close_error_pct", feedback.get("avg_abs_close_error_pct"))\n',
    '    powerbi_source.setdefault("projected_path", data.get("predicted"))\n',
    '    powerbi_source.setdefault("prediction_vs_actual_history", data.get("bt_hist"))\n',
    '\n',
    '    nlp_source = st.session_state.get("nlp_market_intelligence_result", {})\n',
    '    nlp_contract = dict(nlp_source) if isinstance(nlp_source, dict) else {}\n',
    '    nlp_contract.setdefault("summary", {})\n',
    '    research_pack = st.session_state.get("research_pack_20260612", {})\n',
    '    data_mining_contract = research_pack.get("data_mining", {}) if isinstance(research_pack, dict) else {}\n',
    '    if not isinstance(data_mining_contract, dict):\n',
    '        data_mining_contract = {}\n',
    '\n',
    '    market_contract = {\n',
    '        "symbol": current.get("symbol", "EURUSD"), "timeframe": current.get("timeframe", "H1"),\n',
    '        "last_close": current.get("last_close"), "forecast_close": current.get("forecast_close"),\n',
    '        "data_quality": quality, "ohlc": data.get("ohlc"),\n',
    '    }\n',
    '    regime_contract = {\n',
    '        "current": current.get("regime", "-"), "direction": current.get("regime_direction", "WAIT"),\n',
    '        "alpha_delta": alpha_delta, "history": data.get("regime_hist"),\n',
    '    }\n',
    '    decision_contract = {\n',
    '        "central_decision": current.get("decision", "WAIT"), "entry_score": current.get("entry_score"),\n',
    '        "hold_score": current.get("hold_score"), "tp_score": current.get("tp_score"),\n',
    '        "exit_risk": current.get("exit_risk"), "prediction_direction": current.get("prediction_direction", "WAIT"),\n',
    '        "policy": current.get("decision_policy", ""),\n',
    '        "false_reversal_risk": false_reversal_risk,\n',
    '    }\n',
    '    priority_contract = {\n',
    '        "table": priority_df if _is_df(priority_df) else (pd.DataFrame() if pd is not None else None),\n',
    '        "best": (priority_df.iloc[0].to_dict() if _is_df(priority_df) else {}),\n',
    '    }\n',
    '    history_contract = {\n',
    '        "prediction_vs_actual": data.get("bt_hist"), "regime": data.get("regime_hist"),\n',
    '        "priority": data.get("priority"), "ohlc": data.get("ohlc"),\n',
    '    }\n',
    '\n',
    '    result: Dict[str, Any] = {\n',
    '        "version": UNIQUE,\n',
    '        "built_at": _now_text(),\n',
    '        "signature": signature,\n',
    '        "market": market_contract,\n',
    '        "regime": regime_contract,\n',
    '        "decision": decision_contract,\n',
    '        "priority": priority_contract,\n',
    '        "reliability": reliability,\n',
    '        "powerbi": powerbi_source,\n',
    '        "nlp": nlp_contract,\n',
    '        "data_mining": data_mining_contract,\n',
    '        "history": history_contract,\n',
    '        "metadata": {"built_at": _now_text(), "signature": signature, "shared_contract_version": "1.0", "calculation_source": "existing session caches"},\n',
    '        "current": current,\n',
    '        "data_quality": quality,\n',
    '        "prediction_feedback": feedback,\n',
    '        "reliability_calibration": reliability,\n',
    '        "regime_alpha_delta": alpha_delta,\n',
    '        "hourly_priority_table": priority_df if _is_df(priority_df) else (pd.DataFrame() if pd is not None else None),\n',
]
