"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '        "ai_grounding": grounding,\n',
    '        "false_reversal_risk": false_reversal_risk,\n',
    '        # Immutable canonical object is created only by the main Settings run.\n',
    '        # Re-renders may rebuild this lightweight adapter but never create a new run.\n',
    '        "canonical": st.session_state.get("canonical_decision_result_20260617") or st.session_state.get("last_valid_canonical_decision_result_20260617") or {},\n',
    '        "run_id": (st.session_state.get("canonical_decision_result_20260617") or {}).get("run_id") if isinstance(st.session_state.get("canonical_decision_result_20260617"), dict) else None,\n',
    '        "source_keys": {\n',
    '            "ohlc": "dv_pp_df/lunch_5layer_powerbi_df/last_df",\n',
    '            "prediction": "dv_pp_predicted/dv_pp_lightblue_path",\n',
    '            "feedback": "dv_pp_bt_hist/dv_pp_bt_summary",\n',
    '            "regime": "dv_pp_regime_summary/dv_pp_regime_hist",\n',
    '            "priority": "three_center_priority_sorted_20260614/reliability_dynamic_priority_table_20260614",\n',
    '        },\n',
    '    }\n',
    '    st.session_state[SHARED_KEY] = result\n',
    '    st.session_state[LEGACY_SHARED_KEY] = result\n',
    '    st.session_state["adx_shared_calc_signature_20260615"] = signature\n',
    '    st.session_state["adx_reliability_calibrated_20260615"] = reliability\n',
    '    st.session_state["adx_prediction_feedback_20260615"] = feedback\n',
    '    st.session_state["adx_regime_alpha_delta_20260615"] = alpha_delta\n',
    '    st.session_state["adx_ai_grounding_20260615"] = grounding\n',
    '    if _is_df(priority_df):\n',
    '        st.session_state["adx_hourly_priority_calibrated_20260615"] = priority_df\n',
    '        # Backward-compatible fill only when old tables are missing/empty. This\n',
    '        # makes existing Research KNN/Greedy display work without replacing a\n',
    '        # non-empty original priority table.\n',
    '        for key in ["three_center_priority_sorted_20260614", "reliability_dynamic_priority_table_20260614"]:\n',
    '            try:\n',
    '                if not _is_df(st.session_state.get(key)):\n',
    '                    st.session_state[key] = priority_df\n',
    '            except Exception:\n',
    '                pass\n',
    '    return result\n',
    '\n',
    '\n',
    'def ensure_shared_calculation_result(force: bool = False) -> Dict[str, Any]:\n',
    '    try:\n',
    '        import streamlit as st  # type: ignore\n',
    '        rerun_id = st.session_state.get("app_rerun_identifier_20260617")\n',
    '        if not force and rerun_id is not None:\n',
    '            last_id = st.session_state.get("shared_sync_last_rerun_identifier_20260617")\n',
    '            cached = st.session_state.get(SHARED_KEY)\n',
    '            if last_id == rerun_id and isinstance(cached, dict):\n',
    '                return cached\n',
    '            st.session_state["shared_sync_last_rerun_identifier_20260617"] = rerun_id\n',
    '            st.session_state["shared_sync_calls_this_rerun_20260617"] = int(st.session_state.get("shared_sync_calls_this_rerun_20260617", 0) or 0) + 1\n',
    '        return build_shared_calculation_result(st, force=force)\n',
    '    except Exception as exc:\n',
    '        try:\n',
    '            import streamlit as st  # type: ignore\n',
    '            st.session_state["adx_shared_calc_error_20260615"] = str(exc)\n',
    '        except Exception:\n',
    '            pass\n',
    '        return {"version": UNIQUE, "error": str(exc), "built_at": _now_text()}\n',
    '\n',
    '\n',
    'def install_phone_safety_defaults() -> None:\n',
    '    """Light app-wide defaults for phone performance; no layout change."""\n',
    '    try:\n',
    '        import streamlit as st  # type: ignore\n',
    '        st.session_state.setdefault("safe_default_rows_20260615", MAX_MOBILE_ROWS)\n',
    '        st.session_state.setdefault("shared_sync_lazy_load_20260615", True)\n',
    '        st.session_state.setdefault("max_default_table_rows_phone_20260615", MAX_MOBILE_ROWS)\n',
    '        st.session_state.setdefault("max_default_table_rows_desktop_20260615", MAX_DESKTOP_ROWS)\n',
    '    except Exception:\n',
    '        pass\n',
    '\n',
    '\n',
    'def render_shared_sync_compact_panel(location: str = "") -> None:\n',
    '    """Optional renderer. Use only inside existing tabs/expanders."""\n',
    '    try:\n',
    '        import streamlit as st  # type: ignore\n',
    '        from core.canonical_runtime_20260617 import shared_from_runtime\n',
    '        result = shared_from_runtime(st.session_state)\n',
    '        rel = result.get("reliability_calibration", {}) if isinstance(result, dict) else {}\n',
    '        fb = result.get("prediction_feedback", {}) if isinstance(result, dict) else {}\n',
    '        ad = result.get("regime_alpha_delta", {}) if isinstance(result, dict) else {}\n',
    '        q = result.get("data_quality", {}) if isinstance(result, dict) else {}\n',
    '        c1, c2, c3, c4 = st.columns(4)\n',
    '        c1.metric("Shared Sync", "READY" if result and not result.get("error") else "WATCH")\n',
    '        c2.metric("Reliability", f"{_safe_num(rel.get(\'score\'), 0):.1f}", str(rel.get("grade", "-")))\n',
    '        c3.metric("Pred Error", f"{_safe_num(fb.get(\'avg_abs_close_error_pct\'), 0):.4f}%", str(fb.get("feedback_loop_status", "-"))[:24])\n',
    '        c4.metric("Regime Δ", f"{_safe_num(ad.get(\'regime_delta\'), 0):.2f}", str(ad.get("validation_status", "-"))[:24])\n',
    '        st.caption(f"Central shared result: {result.get(\'built_at\',\'-\')} • Data quality {q.get(\'score\',\'-\')} • {location}")\n',
    '    except Exception as exc:\n',
    '        try:\n',
    '            import streamlit as st  # type: ignore\n',
    '            st.caption(f"Shared sync compact panel skipped safely: {exc}")\n',
    '        except Exception:\n',
    '            pass\n',
    '\n',
    '\n',
    'def ground_ai_answer_text(answer: str, question: str = "") -> str:\n',
    '    """Ground an answer without forcing a trade bias onto unrelated questions."""\n',
    '    try:\n',
    '        import streamlit as st  # type: ignore\n',
    '        from core.canonical_runtime_20260617 import shared_from_runtime\n',
    '        result = shared_from_runtime(st.session_state)\n',
    '    except Exception:\n',
    '        result = {}\n',
    '    g = result.get("ai_grounding", {}) if isinstance(result, dict) else {}\n',
    '    if not isinstance(g, dict):\n',
    '        return str(answer or "")\n',
    '    rel = _safe_num(g.get("reliability_score"), 0) or 0\n',
    '    dq = _safe_num(g.get("data_quality_score"), 0) or 0\n',
    '    must = g.get("must_say") if isinstance(g.get("must_say"), list) else []\n',
    '    base = str(answer or "")\n',
    '    if "AI Grounding Guard" in base or "Data Grounding" in base:\n',
    '        return base\n',
    '    q = str(question or "").lower()\n',
    '    directional_terms = (\n',
    '        "buy", "sell", "long", "short", "entry", "trade", "position", "tp", "take profit",\n',
    '        "stop loss", "hold", "exit", "direction", "bias", "safer", "less risky", "price prediction",\n',
    '    )\n',
    '    is_directional = any(term in q for term in directional_terms)\n',
    '    system_control_terms = (\n',
    '        "sidebar", "menu", "settings", "setting page", "phone ui", "api connection",\n',
    '        "nlp api", "llm", "copy short", "copy full", "finder", "research tab",\n',
    '        "other tab", "engine", "train data", "pre original", "backtest", "profile",\n',
    '        "question pattern", "startup page", "opens first",\n',
    '    )\n',
    '    if not is_directional and any(term in q for term in system_control_terms):\n',
    '        return base\n',
    '    if not is_directional:\n',
    '        # Factual market/NLP/error/reliability questions get a data-quality note,\n',
    '        # never an unrelated BUY/SELL recommendation. Pure app-control questions\n',
    '        # return the direct answer above without trading-data boilerplate.\n',
    '        if rel >= 45 and dq >= 55 and not g.get("conflict"):\n',
    '            return base\n',
    '        return base + f"\\n\\n**Data Grounding:** Reliability={rel:.1f}, Data Quality={dq:.1f}. Missing or weak data limits certainty."\n',
    '    guard_needed = bool(must or g.get("conflict") or rel < 45 or dq < 55)\n',
    '    if not guard_needed:\n',
    '        return base\n',
    '    guard = (\n',
    '        "\\n\\n**AI Grounding Guard:** This directional answer cannot override the synchronized system. "\n',
    '        f"Decision={g.get(\'decision\',\'-\')}, Regime={g.get(\'regime\',\'-\')} ({g.get(\'regime_direction\',\'WAIT\')}), "\n',
    '        f"PowerBI/Prediction={g.get(\'prediction_direction\',\'WAIT\')}, Reliability={rel:.1f}, Data Quality={dq:.1f}, "\n',
    '        f"Priority={g.get(\'best_priority\',\'-\')}."\n',
    '    )\n',
    '    if must:\n',
    '        guard += " Must mention: " + ", ".join(map(str, must)) + "."\n',
    '    return base + guard\n',
    '\n',
    '\n',
    'def shared_result_copy_payload() -> str:\n',
    '    try:\n',
    '        import streamlit as st  # type: ignore\n',
    '        from core.canonical_runtime_20260617 import shared_from_runtime\n',
    '        result = shared_from_runtime(st.session_state)\n',
    '    except Exception:\n',
    '        result = {}\n',
    '    safe = _json_safe(result)\n',
    '    try:\n',
    '        return json.dumps(safe, indent=2, ensure_ascii=False, default=str)\n',
    '    except Exception:\n',
    '        return str(safe)\n',
]
