"""Source lines for a backward-compatible V9 implementation segment."""
SOURCE_LINES = [
    '"""ADX shared calculation sync and safety calibration patch (2026-06-15).\n',
    '\n',
    'Additive, non-destructive module.\n',
    '\n',
    'Purpose\n',
    '-------\n',
    'Create one shared calculation result that every existing page can read without\n',
    'moving, deleting, or replacing old tab logic.  The module only reads existing\n',
    'session_state outputs and OHLC data, derives calibration/validation summaries,\n',
    'and writes new shared keys back to session_state.  It never trains a new model,\n',
    'never changes the original PowerBI/ML/regime formulas, and never removes any\n',
    'old table/chart/copy/export key.\n',
    '"""\n',
    'from __future__ import annotations\n',
    '\n',
    'import hashlib\n',
    'import json\n',
    'import math\n',
    'import re\n',
    'import time\n',
    'from dataclasses import dataclass\n',
    'from typing import Any, Dict, Iterable, List, Optional, Tuple\n',
    '\n',
    'try:  # pandas/numpy are project requirements, but import defensively.\n',
    '    import numpy as np\n',
    '    import pandas as pd\n',
    'except Exception:  # pragma: no cover\n',
    '    np = None  # type: ignore\n',
    '    pd = None  # type: ignore\n',
    '\n',
    'UNIQUE = "20260615_shared_sync"\n',
    'SHARED_KEY = "adx_shared_calc_result_20260615"\n',
    'LEGACY_SHARED_KEY = "shared_calc_result"\n',
    'MAX_MOBILE_ROWS = 120\n',
    'MAX_DESKTOP_ROWS = 360\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Safe primitives\n',
    '# ---------------------------------------------------------------------------\n',
    'def _now_text() -> str:\n',
    '    try:\n',
    '        if pd is not None:\n',
    '            return str(pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))\n',
    '    except Exception:\n',
    '        pass\n',
    '    return str(int(time.time()))\n',
    '\n',
    '\n',
    'def _safe_num(v: Any, default: Optional[float] = None) -> Optional[float]:\n',
    '    try:\n',
    '        if v is None or v == "":\n',
    '            return default\n',
    '        if isinstance(v, str):\n',
    '            m = re.search(r"-?\\d+(?:\\.\\d+)?", v.replace(",", ""))\n',
    '            if not m:\n',
    '                return default\n',
    '            v = m.group(0)\n',
    '        x = float(v)\n',
    '        return x if math.isfinite(x) else default\n',
    '    except Exception:\n',
    '        return default\n',
    '\n',
    '\n',
    'def _clip(v: Any, lo: float = 0.0, hi: float = 100.0, default: float = 0.0) -> float:\n',
    '    x = _safe_num(v, default)\n',
    '    if x is None:\n',
    '        x = default\n',
    '    return float(max(lo, min(hi, x)))\n',
    '\n',
    '\n',
    'def _norm_key(v: Any) -> str:\n',
    '    return re.sub(r"[^a-z0-9]+", "", str(v or "").lower())\n',
    '\n',
    '\n',
    'def _is_df(obj: Any) -> bool:\n',
    '    try:\n',
    '        return pd is not None and isinstance(obj, pd.DataFrame) and not obj.empty\n',
    '    except Exception:\n',
    '        return False\n',
    '\n',
    '\n',
    'def _find_col(df: Any, aliases: Iterable[str]) -> Optional[str]:\n',
    '    if not _is_df(df):\n',
    '        return None\n',
    '    try:\n',
    '        nmap = {_norm_key(c): c for c in df.columns}\n',
    '        for a in aliases:\n',
    '            na = _norm_key(a)\n',
    '            if na in nmap:\n',
    '                return nmap[na]\n',
    '        for nk, col in nmap.items():\n',
    '            for a in aliases:\n',
    '                na = _norm_key(a)\n',
    '                if na and na in nk:\n',
    '                    return col\n',
    '    except Exception:\n',
    '        pass\n',
    '    return None\n',
    '\n',
    '\n',
    'def _series_num(df: Any, aliases: Iterable[str], default: float = 0.0):\n',
    '    if pd is None or not _is_df(df):\n',
    '        return pd.Series(dtype=float) if pd is not None else []\n',
    '    col = _find_col(df, aliases)\n',
    '    try:\n',
    '        if col is None:\n',
    '            return pd.Series(default, index=df.index, dtype=float)\n',
    '        return pd.to_numeric(df[col], errors="coerce").fillna(default).astype(float)\n',
    '    except Exception:\n',
    '        return pd.Series(default, index=df.index, dtype=float)\n',
    '\n',
    '\n',
    'def _safe_tail_df(df: Any, rows: int):\n',
    '    if not _is_df(df):\n',
    '        return pd.DataFrame() if pd is not None else None\n',
    '    try:\n',
    '        return df.tail(int(max(1, rows))).copy()\n',
    '    except Exception:\n',
    '        try:\n',
    '            return df.copy()\n',
    '        except Exception:\n',
    '            return pd.DataFrame() if pd is not None else None\n',
    '\n',
    '\n',
    'def _json_safe(obj: Any, rows: int = 80) -> Any:\n',
    '    try:\n',
    '        if pd is not None and isinstance(obj, pd.DataFrame):\n',
    '            return obj.head(rows).to_dict("records")\n',
    '        if pd is not None and isinstance(obj, pd.Series):\n',
    '            return obj.head(rows).to_dict()\n',
    '        if np is not None and isinstance(obj, (np.integer,)):\n',
    '            return int(obj)\n',
    '        if np is not None and isinstance(obj, (np.floating,)):\n',
    '            x = float(obj)\n',
    '            return x if math.isfinite(x) else None\n',
    '        if pd is not None and isinstance(obj, (pd.Timestamp,)):\n',
    '            return str(obj)\n',
    '        if isinstance(obj, dict):\n',
    '            return {str(k): _json_safe(v, rows) for k, v in obj.items() if k not in {"data", "flat"}}\n',
    '        if isinstance(obj, (list, tuple)):\n',
    '            return [_json_safe(x, rows) for x in list(obj)[:rows]]\n',
    '        return obj\n',
    '    except Exception:\n',
    '        return str(obj)\n',
    '\n',
    '\n',
    'def _flatten_dict(obj: Any, prefix: str = "", depth: int = 0, limit: int = 1800) -> Dict[str, Any]:\n',
    '    out: Dict[str, Any] = {}\n',
    '    if depth > 5 or len(out) >= limit:\n',
    '        return out\n',
    '    if isinstance(obj, dict):\n',
    '        for k, v in obj.items():\n',
    '            if len(out) >= limit:\n',
    '                break\n',
    '            key = f"{prefix}.{k}" if prefix else str(k)\n',
    '            if isinstance(v, dict):\n',
    '                out.update(_flatten_dict(v, key, depth + 1, limit))\n',
    '            elif not _is_df(v):\n',
    '                out[key] = v\n',
    '    return out\n',
    '\n',
    '\n',
    'def _find_value(flat: Dict[str, Any], aliases: Iterable[str], default: Any = None) -> Any:\n',
    '    try:\n',
    '        nmap = {_norm_key(k): v for k, v in flat.items()}\n',
    '        for a in aliases:\n',
    '            na = _norm_key(a)\n',
    '            if na in nmap:\n',
    '                return nmap[na]\n',
    '        for nk, v in nmap.items():\n',
    '            for a in aliases:\n',
    '                na = _norm_key(a)\n',
    '                if na and na in nk:\n',
    '                    return v\n',
    '    except Exception:\n',
    '        pass\n',
    '    return default\n',
    '\n',
    '\n',
    'def _first_df_from_state(st: Any, keys: Iterable[str]):\n',
    '    if pd is None:\n',
    '        return None\n',
    '    for key in keys:\n',
    '        try:\n',
    '            obj = st.session_state.get(key)\n',
    '            if _is_df(obj):\n',
    '                return obj\n',
    '        except Exception:\n',
    '            pass\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _df_signature(df: Any) -> str:\n',
    '    if not _is_df(df):\n',
    '        return "empty"\n',
    '    try:\n',
    '        cols = list(map(str, df.columns[:20]))\n',
    '        rows = len(df)\n',
    '        tail = df.tail(3).to_json(default_handler=str)\n',
    '        return hashlib.md5((str(rows) + "|" + ",".join(cols) + "|" + tail).encode("utf-8", errors="ignore")).hexdigest()[:14]\n',
    '    except Exception:\n',
    '        return f"rows_{len(df)}"\n',
    '\n',
    '\n',
    'def _direction_from_regime(regime: Any) -> str:\n',
    '    try:\n',
    '        from core.decision_policy_20260617 import infer_direction_from_regime\n',
    '        return infer_direction_from_regime(regime)\n',
    '    except Exception:\n',
    '        s = str(regime or "").upper()\n',
    '        if any(token in s for token in ("BEAR", "DOWNTREND", "EXPANSION_DOWN", "DOWN_EXPANSION")):\n',
    '            return "SELL"\n',
    '        if any(token in s for token in ("BULL", "UPTREND", "EXPANSION_UP", "UP_EXPANSION")):\n',
    '            return "BUY"\n',
    '        return "WAIT"\n',
    '\n',
    '\n',
    'def _direction_from_prices(last_close: Any, forecast_close: Any) -> str:\n',
    '    a = _safe_num(last_close)\n',
    '    b = _safe_num(forecast_close)\n',
    '    if a is None or b is None:\n',
    '        return "WAIT"\n',
    '    if b > a:\n',
    '        return "BUY"\n',
    '    if b < a:\n',
    '        return "SELL"\n',
    '    return "WAIT"\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# State collection\n',
    '# ---------------------------------------------------------------------------\n',
    'def _collect_flat_state(st: Any) -> Dict[str, Any]:\n',
    '    flat: Dict[str, Any] = {}\n',
    '    preferred = [\n',
    '        "dv_pp_base_result", "lunch_5layer_powerbi_result", "dv_pp_regime_summary", "dv_pp_bt_summary",\n',
    '        "final_merged_intelligence_pack_20260612", "final_synced_research_merge_pack_20260612",\n',
    '        "reliability_control_center_20260614", "regime_context_20260614", "nylo_unified_home_sync_20260612",\n',
    '        "news_nlp_knn_greedy_pack_20260612", "quant_structure_pack_20260612", "research_pack_20260612",\n',
    '        "lunch_prediction_export", "lunch_metric_result_cache", "last_result", "current_result", SHARED_KEY,\n',
    '    ]\n',
    '    try:\n',
    '        sensitive = ("api_key", "apikey", "token", "secret", "password", "finnhub")\n',
    '        for key in preferred:\n',
    '            if any(marker in str(key).lower() for marker in sensitive):\n',
    '                continue\n',
    '            v = st.session_state.get(key)\n',
    '            if isinstance(v, dict):\n',
    '                flat.update(_flatten_dict(v, key))\n',
    '        for k, v in list(st.session_state.items()):\n',
    '            if len(flat) > 2400:\n',
    '                break\n',
    '            key_text = str(k)\n',
    '            if any(marker in key_text.lower() for marker in sensitive):\n',
    '                continue\n',
    '            if isinstance(v, dict):\n',
    '                flat.update(_flatten_dict(v, key_text, limit=2400))\n',
    '            elif isinstance(v, (str, int, float, bool)) and len(str(v)) < 180:\n',
    '                flat[key_text] = v\n',
    '    except Exception:\n',
    '        pass\n',
    '    return flat\n',
    '\n',
    '\n',
    'def _collect_core_data(st: Any, phone_mode: bool) -> Dict[str, Any]:\n',
    '    rows = MAX_MOBILE_ROWS if phone_mode else MAX_DESKTOP_ROWS\n',
    '    ohlc = _first_df_from_state(st, ["calculation_staging_ohlc_df_20260617", "canonical_completed_ohlc_df_20260617", "dv_pp_df", "lunch_5layer_powerbi_df", "last_df", "ohlc_df", "df", "ws_ticks"])\n',
    '    predicted = _first_df_from_state(st, ["dv_pp_predicted", "dv_pp_lightblue_path", "prediction_path_df", "predicted_df", "forecast_df"])\n',
    '    bt_hist = _first_df_from_state(st, ["dv_pp_bt_hist", "prediction_history_df", "prediction_vs_actual_history_df", "dv_pp_projection_history"])\n',
    '    regime_hist = _first_df_from_state(st, ["dv_pp_regime_hist", "regime_history_df", "major_regime_history_df", "lunch_regime_history"])\n',
    '    original_priority = _first_df_from_state(st, [\n',
    '        "three_center_priority_sorted_20260614",\n',
    '        "reliability_dynamic_priority_table_20260614",\n',
    '        "priority_table_df", "knn_greedy_priority_table",\n',
    '    ])\n',
    '    priority = original_priority if _is_df(original_priority) else _first_df_from_state(st, ["adx_hourly_priority_calibrated_20260615"])\n',
    '    return {\n',
    '        "ohlc": _safe_tail_df(ohlc, rows),\n',
    '        "predicted": _safe_tail_df(predicted, min(rows, 80)),\n',
    '        "bt_hist": _safe_tail_df(bt_hist, rows),\n',
    '        "regime_hist": _safe_tail_df(regime_hist, rows),\n',
    '        "priority": _safe_tail_df(priority, rows),\n',
    '        "source_signature": "|".join([\n',
    '            _df_signature(ohlc), _df_signature(predicted), _df_signature(bt_hist), _df_signature(regime_hist),\n',
    '            str(st.session_state.get("metric_run_calculate", False)),\n',
    '            str(st.session_state.get("run_data_visualization_antd_20260615", False)),\n',
    '        ]),\n',
    '    }\n',
    '\n',
    '\n',
    '# ---------------------------------------------------------------------------\n',
    '# Derived engines: data quality, feedback, reliability, regime alpha/delta,\n',
    '# priority table, AI grounding.\n',
    '# ---------------------------------------------------------------------------\n',
    'def _data_quality(df: Any) -> Dict[str, Any]:\n',
    '    if not _is_df(df):\n',
    '        return {"ok": False, "score": 15.0, "rows": 0, "message": "No OHLC dataframe available yet."}\n',
    '    rows = int(len(df))\n',
    '    close_col = _find_col(df, ["close", "c"])\n',
    '    time_col = _find_col(df, ["time", "datetime", "timestamp", "date"])\n',
    '    null_pct = 0.0\n',
    '    dup_pct = 0.0\n',
    '    monotonic_ok = True\n',
    '    try:\n',
    '        use = [c for c in [time_col, close_col, _find_col(df, ["open"]), _find_col(df, ["high"]), _find_col(df, ["low"])] if c]\n',
    '        if use:\n',
    '            null_pct = float(df[use].isna().mean().mean() * 100.0)\n',
    '        if time_col:\n',
    '            t = pd.to_datetime(df[time_col], errors="coerce")\n',
    '            dup_pct = float(t.duplicated().mean() * 100.0)\n',
    '            monotonic_ok = bool(t.dropna().is_monotonic_increasing)\n',
    '    except Exception:\n',
    '        pass\n',
    '    score = 100.0\n',
    '    if rows < 30:\n',
    '        score -= 35.0\n',
    '    elif rows < 80:\n',
    '        score -= 15.0\n',
    '    if close_col is None:\n',
    '        score -= 40.0\n',
    '    score -= min(35.0, null_pct * 2.0)\n',
    '    score -= min(25.0, dup_pct * 3.0)\n',
    '    if not monotonic_ok:\n',
    '        score -= 8.0\n',
    '    score = _clip(score, 0, 100, 50)\n',
    '    return {\n',
    '        "ok": bool(score >= 55 and close_col is not None),\n',
    '        "score": round(score, 2),\n',
    '        "rows": rows,\n',
    '        "close_col": close_col or "",\n',
    '        "time_col": time_col or "",\n',
    '        "null_pct": round(null_pct, 3),\n',
    '        "duplicate_time_pct": round(dup_pct, 3),\n',
    '        "monotonic_time": bool(monotonic_ok),\n',
    '        "default_display_rows": MAX_MOBILE_ROWS,\n',
    '        "message": "OK" if score >= 55 else "Low data quality / limited rows. Reliability is capped.",\n',
    '    }\n',
    '\n',
    '\n',
    'def _prediction_feedback(flat: Dict[str, Any], data: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    hist = data.get("bt_hist")\n',
    '    pred_df = data.get("predicted")\n',
    '    ohlc = data.get("ohlc")\n',
    '    avg_error = _safe_num(_find_value(flat, ["avg_abs_close_error_pct", "prediction_error_pct", "close_error_pct", "prediction_vs_actual_error"], None))\n',
    '    direction_acc = _safe_num(_find_value(flat, ["direction_accuracy_pct", "direction_accuracy", "Direction Accuracy %"], None))\n',
    '    samples = 0\n',
    '    method = "session-summary"\n',
    '    try:\n',
    '        if _is_df(hist):\n',
    '            pred_col = _find_col(hist, ["predicted", "prediction", "forecast", "previous_predicted_path", "predicted_close", "forecast_close"])\n',
    '            actual_col = _find_col(hist, ["actual", "actual_close", "close"])\n',
    '            if pred_col and actual_col:\n',
    '                p = pd.to_numeric(hist[pred_col], errors="coerce")\n',
    '                a = pd.to_numeric(hist[actual_col], errors="coerce")\n',
    '                mask = p.notna() & a.notna() & (a.abs() > 1e-12)\n',
    '                if mask.any():\n',
    '                    err = ((p[mask] - a[mask]).abs() / a[mask].abs() * 100.0)\n',
    '                    avg_error = float(err.tail(80).mean())\n',
    '                    samples = int(mask.sum())\n',
    '                    method = "prediction-vs-actual-history"\n',
    '                    try:\n',
    '                        da = (p.diff()[mask].apply(lambda x: 1 if x > 0 else -1 if x < 0 else 0) == a.diff()[mask].apply(lambda x: 1 if x > 0 else -1 if x < 0 else 0)).mean() * 100.0\n',
    '                        if math.isfinite(float(da)):\n',
    '                            direction_acc = float(da)\n',
    '                    except Exception:\n',
    '                        pass\n',
    '    except Exception:\n',
    '        pass\n',
    '    if avg_error is None or float(avg_error) <= 1e-9:\n',
    '        # Use recent volatility as an honest proxy until enough old prediction\n',
    '        # vs actual rows exist. This is not a new prediction engine.\n',
    '        try:\n',
    '            c = _series_num(ohlc, ["close", "c"]).replace(0, np.nan)\n',
    '            ret = c.pct_change().abs() * 100.0\n',
    '            avg_error = float(ret.tail(48).mean()) if len(ret.dropna()) else 0.15\n',
    '            method = "volatility-proxy-until-feedback-history-exists"\n',
    '        except Exception:\n',
    '            avg_error = 0.15\n',
    '    if direction_acc is None:\n',
    '        direction_acc = 50.0\n',
    '    error_penalty = _clip((avg_error or 0.0) * 450.0, 0, 60, 0)\n',
    '    reliability_cap = _clip(100.0 - error_penalty, 35, 100, 70)\n',
    '    return {\n',
    '        "method": method,\n',
    '        "samples": int(samples),\n',
    '        "avg_abs_close_error_pct": round(float(avg_error or 0.0), 5),\n',
    '        "direction_accuracy_pct": round(_clip(direction_acc, 0, 100, 50), 2),\n',
    '        "error_penalty": round(error_penalty, 2),\n',
    '        "reliability_cap_from_feedback": round(reliability_cap, 2),\n',
    '        "feedback_loop_status": "history-calibrated" if samples >= 10 else "proxy / needs more completed prediction-vs-actual rows",\n',
    '    }\n',
    '\n',
    '\n',
    'def _extract_current_summary(flat: Dict[str, Any], data: Dict[str, Any]) -> Dict[str, Any]:\n',
    '    ohlc = data.get("ohlc")\n',
    '    pred = data.get("predicted")\n',
    '    close_col = _find_col(ohlc, ["close", "c"])\n',
    '    pred_close_col = _find_col(pred, ["close", "predicted_close", "forecast_close", "estimated_price_close", "price"])\n',
    '    last_close = None\n',
    '    forecast_close = _safe_num(_find_value(flat, ["estimated_price_close", "forecast_close", "prediction_close", "next_close"], None))\n',
    '    try:\n',
    '        if close_col:\n',
    '            last_close = float(pd.to_numeric(ohlc[close_col], errors="coerce").dropna().iloc[-1])\n',
    '        if forecast_close is None and pred_close_col:\n',
    '            forecast_close = float(pd.to_numeric(pred[pred_close_col], errors="coerce").dropna().iloc[0])\n',
    '    except Exception:\n',
    '        pass\n',
    '    regime = _find_value(flat, ["current_regime", "regime", "major_regime", "master_regime"], "-")\n',
    '    try:\n',
    '        hist = data.get("regime_hist")\n',
    '        if _is_df(hist):\n',
    '            rcol = _find_col(hist, ["regime", "current_regime", "major_regime", "master_regime", "label", "state"])\n',
    '            if rcol:\n',
    '                vals = hist[rcol].dropna().astype(str).str.strip()\n',
    '                if len(vals): regime = vals.iloc[-1]\n',
    '    except Exception:\n',
    '        pass\n',
    '    pred_dir = str(_find_value(flat, ["prediction_direction", "forecast_direction"], "") or "").upper()\n',
    '    if pred_dir not in {"BUY", "SELL", "WAIT"}:\n',
]
